import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const POLITICS_SUMMARIES = [
  {
    name: 'Qatar',
    country: 'Qatar',
    lat: 25.3548,
    lng: 51.1839,
    summary: `Qatar just voted away its only taste of democracy—and barely anyone seems to care. On November 5th, 2024, while the world obsessed over the U.S. presidential election, Qatari citizens quietly approved constitutional amendments ending elections to the Shura Council after just one voting cycle. The Interior Ministry reported 91% voted yes with 84% turnout—figures so stunningly high they'd make any autocrat blush. What's remarkable isn't just that Qatar abolished its fledgling elections, but that this represented the pragmatic choice for a country where tribal politics had created dangerous fractures. The 2021 elections—Qatar's first and now last general election—had exposed deep sectarian tensions between "original" Qataris (whose families settled pre-1930) and everyone else. When only certain tribal families could run for office, the electoral experiment risked institutionalizing divisions that the Al Thani ruling family had spent decades carefully managing. So they ended it. In November 2025, Qatar remains what it's always been: an absolute monarchy where Emir Tamim bin Hamad Al Thani and his inner circle make every consequential decision. But don't mistake this for typical Gulf autocracy. Qatar punches wildly above its weight—mediating between the Taliban and Washington, hosting World Cup 2022, running Al Jazeera, and now positioning itself as the indispensable Middle East broker in a region splitting between Saudi-UAE-Israel normalization and Iranian-axis resistance. This is a country of 300,000 citizens governing 2.5 million expatriates, sitting on the world's third-largest natural gas reserves, trying to navigate between American security guarantees, cautious engagement with Iran, and increasingly assertive Saudi neighbors who'd love to cut Doha down to size.

**The Shura Council Referendum: Why Qatar Chose Stability Over Votes**

Let's talk about what actually happened. In 2003, Qatar's constitution promised that two-thirds of the 45-member Shura Council would be elected, with the Emir appointing the remaining 15. For nearly two decades, nothing happened—the Shura remained fully appointed. Then in October 2021, Qatar finally held elections. And immediately, problems emerged. Only "original" Qatari citizens—those whose families had been in Qatar since before 1930—could run for the 30 elected seats. This excluded thousands of naturalized citizens, many from families who'd lived in Qatar for generations but whose ancestors came from neighboring Gulf states or Iran. Tribal candidates mobilized along family lines. The campaign period saw unusual public political mobilization. And when results came in, certain prominent families who'd long enjoyed palace favor found themselves without representation. Worse, the election exposed status hierarchies that Qatar's ruling family had carefully kept implicit. Suddenly you had "first-class" and "second-class" citizens—a dangerous dynamic in a tiny country where legitimacy depends on the Al Thani family being seen as inclusive patrons of all Qataris. The 2024 referendum fixed this. Article 77 now allows the Emir to appoint all 45 Shura members, though crucially, amendments removed the "original citizens" requirement—any Qatari can now be appointed. It's classic Qatari political management: close down the messy electoral process, but signal inclusivity through appointment criteria. Critics called it a step backward for democracy. But here's the thing: Qatar was never democratic, and the 2021 elections weren't building toward democracy—they were creating institutionalized tribal competition that threatened stability. The Shura Council has legislative powers only in narrow domestic policy areas; it cannot question the Emir's authority, control foreign policy, or manage Qatar's vast sovereign wealth. Elections gave the appearance of pluralism while risking real social division. The referendum resolved that contradiction. Meanwhile, voting for the Central Municipal Council—which handles local services—continues, providing a limited outlet for electoral participation without touching core political power.

**The Emir's Balancing Act: Between Saudi Arabia, Iran, and the United States**

Qatar's real politics happen at the top, and Emir Tamim has gotten very good at the balancing act. Since taking power in 2013, he's maintained Qatar's maverick foreign policy—staying in the U.S. security umbrella (Al Udeid Air Base hosts U.S. Central Command's forward headquarters) while keeping channels open to Iran, backing Islamist movements like Hamas and the Muslim Brotherhood, and positioning Qatar as the go-to mediator for everyone from Afghan peace talks to Gaza ceasefires. This has made Qatar indispensable but also deeply controversial. The Saudis and Emiratis imposed a brutal blockade on Qatar from 2017-2021, demanding Doha shut down Al Jazeera, cut ties with Iran, and stop backing Islamist groups. Qatar refused, weathered the siege, and came out stronger—the blockade ended with Qatar making zero concessions. In November 2025, relations with Riyadh have normalized but remain wary. Saudi Crown Prince Mohammed bin Salman views Qatar's independent streak as irritating and Doha's ties to Hamas as problematic for his normalization plans with Israel. Qatar, for its part, sees itself as a pragmatic broker while the Saudis play dangerous sectarian games. On Iran, Qatar shares the world's largest gas field—the North Dome/South Pars—with Tehran. You can't be hostile to your neighbor when your economic lifeblood depends on joint resource management. So Qatar maintains working relations with Iran even as it hosts U.S. forces preparing for potential conflict with Tehran. It's a tightrope walk, but it's made Qatar rich and relevant. With the Americans, Qatar has doubled down on its role as the reliable Gulf partner willing to do awkward things—host Taliban political offices, mediate hostage releases, quietly engage with groups Washington can't openly talk to. This makes Qatar useful, and usefulness buys autonomy.

**Institutions, Corruption, and the Rentier State Model**

Qatar's political institutions are straightforward: the Emir holds absolute power, the appointed cabinet runs day-to-day governance, and the Shura Council offers advisory input on limited domestic matters. There's no meaningful separation of powers, no independent judiciary that can challenge the ruling family, no free press (Al Jazeera reports critically on everyone except Qatar), and no political parties. The system works because Qatar is staggeringly wealthy—GDP per capita exceeds $85,000—and the ruling family distributes that wealth generously to citizens through subsidized utilities, free education and healthcare, government jobs, and land grants. Qatari citizens don't pay income tax. This is classic rentier state politics: as long as hydrocarbon revenues fund lavish benefits, citizens tolerate autocracy. Corruption isn't absent—major infrastructure projects involve murky contracts, and the World Cup 2022 construction was dogged by labor abuse allegations and bribery claims around the FIFA bid. But systemic graft is relatively constrained compared to other Gulf states because the ruling family's legitimacy depends on being seen as competent stewards of national wealth. Transparency International ranks Qatar mid-pack globally—better than Saudi Arabia or Russia, worse than Western Europe. The bigger governance issue is expatriate labor. Of Qatar's 2.8 million residents, 2.5 million are foreign workers—South Asians, Filipinos, Africans—who have virtually no political rights, face restrictive kafala sponsorship laws, and work in conditions that international human rights groups call exploitative. Qatar has reformed some labor laws post-World Cup scrutiny, but the fundamental model remains: a tiny citizen minority governs a vast disenfranchised migrant workforce. It's politically sustainable as long as Qatar stays rich, but deeply illiberal.

**The Bottom Line**

Qatar in November 2025 is an absolute monarchy that's completely comfortable with that fact. The brief electoral experiment is over, and Qatari citizens seem fine with it—they've traded voting rights for stability, wealth, and a government that's made their tiny nation a global player. The Shura Council referendum wasn't a democratic backslide because Qatar was never on a democratic path; it was a course correction away from elections that risked entrenching tribal divisions. What matters in Qatari politics isn't legislative debates or opposition parties—it's whether Emir Tamim can continue navigating between American, Saudi, and Iranian interests without getting crushed, whether Qatar's massive LNG wealth can sustain the rentier bargain as energy markets shift toward renewables, and whether Doha's maverick mediation role remains valuable or becomes a liability. Right now, Qatar is winning. It survived the Saudi blockade, successfully hosted the World Cup, and remains the indispensable broker in Middle East crises from Gaza to Afghanistan. But the region is shifting fast—Saudi-Israeli normalization could isolate Qatar, U.S. security commitments are uncertain with changing administrations, and over-reliance on gas exports is risky in a decarbonizing world. Watch whether Qatar can diversify its economy beyond hydrocarbons, whether its mediation diplomacy continues paying dividends, and whether the next generation of Al Thani leadership maintains the delicate balancing act. For now, Qatar is stable, wealthy, and punching above its weight. But in the Gulf, fortunes can shift very quickly.`,
    issues: JSON.stringify([
      'Constitutional referendum ending Shura Council elections',
      'Balancing act between US, Saudi Arabia, and Iran',
      'Rentier state model and expatriate labor rights',
      'Regional mediation role and foreign policy independence'
    ]),
    topStories: JSON.stringify([
      {
        title: 'Qataris vote to end limited voting for legislative seats',
        source: 'Courthouse News Service',
        link: 'https://www.courthousenews.com/qataris-decide-whether-to-end-limited-voting-for-legislative-seats-in-shadow-of-us-election/',
        pubDate: '2024-11-05'
      }
    ])
  },
  {
    name: 'Russia',
    country: 'Russia',
    lat: 55.7558,
    lng: 37.6173,
    summary: `Russia in November 2025 is a country at war, hemorrhaging money, and doubling down on authoritarianism—but Vladimir Putin's grip on power remains absolute. Putin just began his fifth presidential term after a March 2024 election that was as predictable as it was farcical: he won 87% of the vote with no genuine opposition allowed on the ballot. The real politics in Russia aren't about elections or legislative debates—they're about managing an economy increasingly strained by the Ukraine war, preparing society for sustained sacrifice, and ensuring the security services and regional governors remain loyal as costs mount. In November 2025, the Kremlin is implementing another round of painful austerity: VAT is rising from 20% to 22%, following last year's income and corporate tax hikes. The budget deficit is projected to hit 5.74 trillion rubles by year's end—one-sixth of total revenue—driven by massive military spending. And here's the politically clever bit: Putin is using regional governors and Federation Council senators to sell these unpopular measures, positioning them as the fall guys while he remains the distant, authoritative figure above the fray. It's classic Putinism: centralize power, distribute blame, keep the population atomized and compliant. Russia's political system isn't evolving toward pluralism or reform—it's calcifying into a personalist autocracy where opposition is crushed, civil society is gutted, and meaningful political competition is impossible. But don't mistake repression for fragility. Putin's regime is deeply entrenched, backed by security services, sustained by energy revenues (albeit declining), and legitimized by nationalist narratives around the Ukraine war. The question isn't whether Putin will fall—he won't—but whether Russia's economy can sustain this war indefinitely, and what happens when Putin eventually exits the scene.

**Putin's Fifth Term: Personnel, Power, and the Succession Question**

Let's start with the political reconfiguration. Putin's fifth term, which began in May 2024, brought significant personnel changes and government reshuffling that signal the regime's evolving priorities. In November 2025, the government is more militarized, more focused on economic resilience under sanctions, and more explicitly preparing for long-term confrontation with the West. Key appointments reflect this: technocrats focused on defense industry production, security service veterans in sensitive posts, and loyal regional governors replacing anyone who showed insufficient enthusiasm for the war effort. In early November, Putin appointed Vitaly Korolyov as acting governor of Tver Oblast—typical of the constant churn in regional leadership as the Kremlin tests loyalty and competence. The Duma remains a rubber stamp. United Russia, Putin's party, holds a supermajority alongside the other systemic opposition parties (Communists, Liberal Democrats, A Just Russia), all of which reliably vote with the Kremlin. The Duma's role is legislative theater—passing laws Putin wants while pretending to debate them. Real power resides in the Security Council, the Presidential Administration, and informal networks of siloviki (security service veterans) and oligarchs who manage sectors of the economy. The succession question looms quietly. Putin will turn 73 in 2025, and there's no clear heir. The current constitutional arrangement allows him to run again in 2030, potentially extending his rule into his eighties. But the system he's built is hyper-personalized—it's not clear how it survives his departure. That's intentional. Putin doesn't want rivals positioning themselves; he wants indispensability. But it makes the regime brittle in the long term. Personnel shifts in 2024-2025 suggest jockeying behind the scenes among factions—security services versus technocrats, military versus FSB, Kremlin hardliners versus pragmatists who understand Russia needs some economic engagement with the world. But none of this breaks into public view. Russian politics happen in backrooms and dachas, not parliaments or protest squares.

**The Ukraine War and Domestic Politics: Manufacturing Consent Through Repression**

The war in Ukraine—what the Kremlin still officially calls a "special military operation"—defines Russian politics in November 2025. It's now over three years old, with hundreds of thousands of Russian casualties, massive economic costs, and no clear endpoint. The Kremlin's strategy domestically is threefold: control the narrative through total information dominance, criminalize dissent so thoroughly that opposition is impossible, and mobilize nationalist sentiment while carefully managing the draft to avoid politically destabilizing middle-class backlash. On narrative control, Russian state media presents the war as existential defense against NATO expansion and Western degeneracy. Independent media has been destroyed—Novaya Gazeta shut down, Ekho Moskvy silenced, Meduza forced abroad. Social media is heavily censored, and a vast apparatus of laws criminalize "false information" about the military, "discrediting" the armed forces, or spreading "fake news" about the state. Thousands have been prosecuted, fined, or imprisoned for anti-war statements—even calling it a "war" rather than "special military operation" is legally risky. The result is a chilling effect where most Russians self-censor ruthlessly. On mobilization, the Kremlin has avoided another general call-up since the disastrous September 2022 mobilization that sparked protests and mass emigration. Instead, they're using financial incentives—offering huge signing bonuses for contract soldiers drawn from poor regions and ethnic minorities. It's politically savvy: keeps casualties concentrated in areas with little political clout while insulating Moscow and St. Petersburg's middle classes from the war's worst impacts. But casualties are mounting, and regional governors are now being tasked with recruitment quotas—making them unpopular scapegoats. On nationalism, the Kremlin frames the war in civilizational terms—Russia defending traditional values against a degenerate West. This resonates with portions of the population, especially older, rural, and conservative demographics. But younger, urban, educated Russians are far more skeptical. Many have left—estimates suggest up to a million Russians emigrated since the war began. Those who remain are largely cowed into silence.

**Economic Strain: Who Pays for the War?**

Russia's economy is under severe strain, and the November 2025 budget squeeze is forcing painful choices. The deficit has ballooned due to military spending (estimated at 6-7% of GDP, possibly higher when hidden costs are included) and plummeting oil and gas revenues due to sanctions and price caps. To close the gap, the government announced VAT increases to 22%—a regressive tax that hits ordinary Russians hardest. Income and corporate taxes were already raised last year. The Central Bank has kept interest rates high to combat inflation, which makes borrowing expensive for businesses. The message from the Kremlin is clear: the war will be funded, and if that means Russians get poorer, so be it. Here's the political gambit: Putin is using regional governors and Federation Council senators to announce and defend these unpopular measures, positioning them as the public face of austerity while he remains above the fray as the national leader focused on security. It's a classic authoritarian tactic—insulate the top, make mid-level officials absorb public anger, and rotate them out if discontent gets too high. So far, it's working. There's grumbling, but no organized opposition, no protests, no political outlet for frustration. The economic pain is real but diffuse—inflation eroding purchasing power, shortages of imported goods, businesses struggling with sanctions—but not yet catastrophic enough to spark unrest. The state's repressive capacity remains overwhelming. Alongside austerity, there's strategic resource nationalism. In November, Putin ordered the cabinet to develop a roadmap for extracting rare-earth minerals and improving transport links with China and North Korea. Russia is reorienting its economy toward Asia, particularly China, as Europe cuts energy ties. It's a long-term bet that Russia can survive as a resource supplier to authoritarian partners while developing indigenous production of sanctioned goods.

**Institutions, Corruption, and the Illusion of Governance**

Russian political institutions exist but have no real autonomy. The Duma legislates what it's told. The judiciary serves the state. Regional governors answer to the Kremlin. Civil society organizations have been labeled "foreign agents" or banned. The press is state-controlled. Elections happen but outcomes are predetermined. This isn't a system where institutions check power—it's a system where institutions perform loyalty. Corruption remains endemic. Transparency International ranks Russia near the bottom globally. Defense procurement is notoriously corrupt, with billions siphoned off before equipment reaches the front. But the system isn't chaotic—it's controlled corruption, where skimming is tolerated as long as loyalty is maintained and key objectives (military supply, resource extraction) are achieved. It's patrimonial governance: networks of patronage radiating from the top, lubricated by state funds and energy rents. What's striking is how little formal politics matters. There are no opposition parties that can campaign freely, no independent candidates who can win office, no legislative path to changing policy. All meaningful political contestation has been driven into exile (Navalny is dead, others have fled) or underground. What remains is a passive population, a performative democracy, and an autocrat with unrivaled power.

**The Bottom Line**

Russia in November 2025 is an entrenched autocracy at war, with an economy under strain but not yet breaking. Putin's fifth term consolidates his personalist rule, and there's no plausible scenario where he loses power in the near term. The system is too repressive, the opposition too shattered, the security services too loyal. But the long-term picture is concerning for the Kremlin. The war is expensive and open-ended. Economic isolation from the West is deepening. Dependence on China is growing, which brings its own risks. Casualties are mounting, and while the state can suppress dissent now, can it do so indefinitely if the war drags on for years? Demographic decline is accelerating—Russia is losing population, and emigration of educated young people compounds the problem. Sanctions are biting in complex ways, limiting technology access and investment. And the succession question looms: Putin has built a system where he's indispensable, which makes the system inherently unstable when he's gone. Watch three things: First, whether economic pain translates into political instability—so far, no, but there are limits. Second, whether the military can sustain operations in Ukraine without another mobilization—that's the tripwire for middle-class discontent. Third, whether elite fractures emerge as the costs of confrontation with the West outweigh the benefits for key constituencies. For now, Putin is firmly in control, and Russian politics in November 2025 are what they've been for years—authoritarian, repressive, and oriented entirely around one man's will to power.`,
    issues: JSON.stringify([
      'Putin\'s fifth term and personalist autocracy',
      'Ukraine war costs and domestic repression',
      'Economic austerity and budget deficit',
      'Succession question and regime stability'
    ]),
    topStories: JSON.stringify([
      {
        title: 'Putin orders roadmap for Russian rare earths extraction',
        source: 'Al Jazeera',
        link: 'https://www.aljazeera.com/news/2025/11/4/putin-orders-roadmap-for-russian-rare-earths-extraction-by-december',
        pubDate: '2025-11-04'
      },
      {
        title: 'The Kremlin Is Using Governors to Prepare Russians for Hard Times',
        source: 'Carnegie Endowment',
        link: 'https://carnegieendowment.org/russia-eurasia/politika/2025/11/russia-economic-fall-preparation',
        pubDate: '2025-11-07'
      }
    ])
  },
  {
    name: 'Rwanda',
    country: 'Rwanda',
    lat: -1.9403,
    lng: 29.8739,
    summary: `Rwanda in November 2025 is a country still entirely in Paul Kagame's grip—and that's not changing anytime soon. In July 2024, Kagame won his fourth presidential term with 99.2% of the vote, a result so lopsided it would embarrass even the most brazen autocrat. His main challengers weren't defeated; they were disqualified. Victoire Ingabire and Diane Rwigara—both prominent opposition figures—were barred from running on spurious grounds. The election wasn't a contest; it was a coronation. And here's the thing: many Rwandans genuinely support Kagame. Not because they're coerced—though coercion exists—but because he delivered on a promise. He ended the genocide, rebuilt the country, delivered economic growth, and turned Rwanda into the darling of international development agencies. But that support is now interwoven with fear, surveillance, and the complete absence of political alternatives. In November 2025, as Kagame settles into another term that could last until 2034, Rwanda's politics are defined by one question: what happens when Kagame eventually leaves power? The system he's built is hyper-personalized, deeply repressive, and entirely dependent on his authority. There's no mechanism for political transition, no space for opposition, and no independent institutions that could manage succession. Rwanda has achieved stability, but it's the stability of an autocracy, not a democracy. And the price—silenced dissent, surveilled citizens, exiled or dead critics—is steep.

**The Kagame Model: Delivery Plus Repression**

Let's be clear about what Paul Kagame has achieved. When he came to power after the 1994 genocide, Rwanda was a shattered nation—800,000 dead, infrastructure destroyed, economy collapsed, social fabric torn apart. Thirty years later, Rwanda is one of Africa's fastest-growing economies, with GDP growth averaging 7-8% annually. Kigali is spotless, safe, and well-governed. Corruption—at least petty corruption—is low by regional standards. Infrastructure is decent. Healthcare and education access have expanded dramatically. Gender equality indicators are strong; Rwanda's parliament is over 60% women. Foreign investors praise Rwanda's ease of doing business. Development organizations hold Rwanda up as a success story. Kagame delivered. But here's the other side: he delivered by crushing all opposition, surveilling the population, controlling media, jailing critics, and allegedly ordering assassinations of exiled dissidents. The Rwandan Patriotic Front (RPF), Kagame's party, has ruled since 1994 without meaningful challenge. Elections happen, but outcomes are predetermined. Opposition parties exist on paper but are functionally neutered. Civil society operates under tight restrictions. Journalists self-censor ruthlessly because crossing the government can mean imprisonment or worse. The state monitors social media, tracks dissent, and uses intimidation to enforce compliance. This is what scholars call "developmental authoritarianism"—a regime that delivers economic growth and public goods while denying political freedoms. And many Rwandans accept the bargain: stability and development in exchange for political passivity. The trauma of the genocide looms over everything. Kagame's legitimacy rests partly on his role ending the slaughter, but also on the implicit threat that without strong centralized control, ethnic violence could return. It's a powerful narrative, and the RPF wields it effectively. But it's also self-serving: by framing all opposition as divisionist or genocidal, Kagame justifies repression as existential necessity.

**The 2024 Election and the Absence of Opposition**

July 2024's election was a farce, but an instructive one. Kagame ran against two candidates—Frank Habineza of the Democratic Green Party and independent Philippe Mpayimana—both of whom are considered regime-friendly. Serious challengers were disqualified. Victoire Ingabire, who spent years in prison on terrorism charges widely seen as politically motivated, was barred from running due to her criminal record. Diane Rwigara, a businesswoman and activist who tried to run in 2017 and faced harassment and bogus charges, was again blocked. International observers noted the lack of genuine competition, restricted media access for opposition, and intimidation of voters. But Kagame doesn't care. The point of elections in Rwanda isn't to determine who governs—Kagame governs—it's to perform legitimacy domestically and internationally while reinforcing the RPF's dominance. The 99.2% result sends a message: resistance is futile. In November 2025, Kagame is emboldened. He's in his fourth term, and constitutional changes allow him to run again in 2029 and potentially serve until 2034, which would give him four decades in power. There's no succession plan, no obvious heir, no process for political transition. Kagame has built a system entirely around himself. Senior RPF figures are loyal lieutenants, not independent power centers. The military and security services answer to him personally. This is stability purchased through personalist autocracy, and it's inherently fragile—because when Kagame goes, there's no institutional framework to manage the transition.

**Repression, Surveillance, and the Exiled Opposition**

Rwanda's repression is sophisticated. It's not crude thuggery—it's legalistic, bureaucratic, and plausibly deniable. Critics are arrested on terrorism or genocide ideology charges. Trials happen but are rigged. Prison conditions are harsh. Dissidents are monitored, their families harassed. Exile isn't safe either. There's credible evidence linking the Rwandan government to attacks on dissidents abroad—Patrick Karegeya, a former intelligence chief turned critic, was murdered in South Africa in 2014. Others have survived assassination attempts or live under police protection in Europe. The message is clear: there's nowhere beyond Kagame's reach. Domestically, surveillance is pervasive. The state monitors communications, tracks social media, and employs informants. Self-censorship is the norm. Rwandans know not to criticize the government openly. This creates a chilling effect where political discussion becomes impossible. People focus on economic advancement, keeping their heads down, and avoiding trouble. The RPF's control extends to local governance. The system of community councils and local leaders is used for surveillance and control, ensuring that dissent is detected early and suppressed. In rural areas, where most Rwandans live, the state's presence is inescapable. The international community knows all this but says little. Rwanda is too useful—a stable partner in an unstable region, a host for refugee camps, a contributor to UN peacekeeping missions, and a compelling development success story. Western donors tolerate Kagame's authoritarianism because he delivers results they can showcase. It's deeply cynical.

**The Genocide Legacy and National Unity Ideology**

The 1994 genocide remains central to Rwandan politics. Kagame's RPF ended the genocide, and that gives the party immense moral authority. But the RPF also uses the genocide to shut down dissent. Under Rwandan law, "genocide ideology" and "divisionism" are crimes. These terms are vague and weaponized against critics. Questioning government policy can be framed as divisionism. Challenging the RPF's narrative about the genocide can be prosecuted as genocide ideology. It's a legal mechanism for repression wrapped in the language of national unity. Rwanda abolished ethnic identifiers on official documents and promotes a national identity over Hutu-Tutsi distinctions. On one level, this is genuine nation-building. On another, it's a tool for silencing legitimate grievances about how power is distributed—because raising such questions can be labeled divisionist. The RPF-dominated government is largely Tutsi, the demographic minority. The genocide targeted Tutsis, but Hutus are the majority. There are real questions about political representation, reconciliation, and accountability that Rwanda's official narrative doesn't address. But asking those questions publicly is dangerous. In November 2025, Kagame spoke at the Unity Club forum, emphasizing self-reliance and unity—key themes of his rule. The subtext is always the same: Rwanda must remain united under RPF leadership, and any challenge to that threatens to return the country to chaos. It's effective messaging, rooted in real trauma, but it also forecloses political pluralism.

**The Bottom Line**

Rwanda in November 2025 is stable, growing, and deeply authoritarian. Paul Kagame is in complete control, and there's no plausible scenario where he loses power before he chooses to leave—if he ever does. He's built a system that delivers economic development and public order while suffocating political freedom. For many Rwandans, especially those who remember the genocide, the tradeoff seems worth it. But it's a precarious stability, dependent entirely on one man. The big questions for Rwanda are these: Can economic growth continue as Rwanda exhausts easy development gains and faces middle-income trap challenges? What happens when Kagame leaves? The system has no succession plan, no independent institutions, no political competition—just Kagame. When he goes, there's a real risk of instability or elite infighting. Can Rwanda ever transition to genuine pluralism, or will it remain an autocracy indefinitely? Right now, there's no path from here to democracy. The opposition is crushed, civil society muzzled, media controlled. Any political opening would require Kagame himself to initiate reform, and there's no sign he's interested. Watch whether younger Rwandans, who don't remember the genocide firsthand, start demanding political freedoms as economic opportunities plateau. Watch whether international donors begin conditioning aid on political reform. And watch the succession question—because when Kagame eventually exits, Rwanda's carefully managed stability could unravel fast. For now, Rwanda is the textbook case of developmental authoritarianism: effective governance, economic progress, and zero political freedom. It's impressive and troubling in equal measure.`,
    issues: JSON.stringify([
      'Kagame\'s fourth term and personalist rule',
      'Repression of opposition and surveillance state',
      'Genocide legacy and national unity ideology',
      'Succession question and regime stability'
    ]),
    topStories: JSON.stringify([
      {
        title: 'Paul Kagame wins fourth term with 99.2% of vote',
        source: 'Al Jazeera',
        link: 'https://www.aljazeera.com/news/2024/7/16/rwanda-paul-kagame-wins-fourth-presidential-term',
        pubDate: '2024-07-16'
      },
      {
        title: 'No One Will Save Rwandans but Rwandans - President Kagame',
        source: 'KT Press',
        link: 'https://www.ktpress.rw/2025/11/no-one-will-save-rwandans-but-rwandans-president-kagame-to-unity-club/',
        pubDate: '2025-11-08'
      }
    ])
  },
  {
    name: 'Saudi Arabia',
    country: 'Saudi Arabia',
    lat: 24.7136,
    lng: 46.6753,
    summary: `Saudi Arabia in November 2025 is a country mid-transformation—or at least, that's the official story. Crown Prince Mohammed bin Salman (MBS) is pushing Vision 2030, his ambitious plan to diversify the economy beyond oil, modernize society, and turn Saudi Arabia into a regional powerhouse. And there's real progress: women can drive, cinemas have reopened, entertainment sectors are booming, and credit rating agencies have upgraded Saudi debt. But the politics beneath the glossy PR are brutal. MBS has consolidated power by sidelining rivals, jailing critics, crushing dissent, and wielding the security services to ensure absolute loyalty. The murder of journalist Jamal Khashoggi in 2018 was the most infamous example, but it's part of a broader pattern of repression. In November 2025, as MBS prepares for a key meeting with U.S. President Trump on November 18th, Saudi politics are defined by this tension: impressive modernization coexisting with intensifying authoritarianism. There's no parliament with real power, no independent judiciary, no free press, no political parties. All meaningful decisions flow from MBS and his inner circle. King Salman, now in his late eighties and in declining health, is a figurehead. MBS is the de facto ruler, and everyone knows it. The big questions are whether Vision 2030 can actually wean Saudi Arabia off oil dependence, whether MBS's authoritarian modernization can survive economic shocks, and what happens if the balancing act between Washington, Tehran, and regional rivals collapses.

**MBS and the Consolidation of Power**

Let's start with how Mohammed bin Salman took control. Traditionally, Saudi power was distributed among senior princes of the Al Saud family, with the King balancing factions. MBS smashed that system. In 2017, he orchestrated the Ritz-Carlton purge—arresting dozens of princes, ministers, and businessmen on corruption charges and holding them until they surrendered assets. It was marketed as anti-corruption, but it was really about removing rivals and consolidating wealth and power in MBS's hands. He sidelined Crown Prince Mohammed bin Nayef, who had been heir apparent, taking the succession for himself. He's placed loyalists in key positions—defense, interior, intelligence, economic ministries. The security services answer to him. So does the Saudi sovereign wealth fund, which controls trillions and is central to Vision 2030. In November 2025, MBS is unrivaled. There's no alternative power center within the royal family, no dissident princes plotting (at least not openly), no institutional checks. King Salman's health is poor, and MBS is already running the country. The formal transfer of the crown is a formality at this point. What's striking is how thoroughly he's centralized power. Saudi Arabia had always been autocratic, but power was diffused among factions. Now it's all MBS. That makes the system more decisive but also more brittle—if MBS fails, there's no one else to blame or absorb shock.

**Vision 2030: Progress and Peril**

Vision 2030 is MBS's signature project: diversifying the economy away from oil, building mega-projects like NEOM (a planned futuristic city), boosting tourism, entertainment, and technology sectors, and socially modernizing Saudi society. Progress is real. Women's rights have expanded dramatically—they can drive, travel without male guardian permission, and participate more in the workforce. The entertainment sector has exploded: concerts, cinemas, sporting events (Saudi Arabia is hosting major boxing matches, Formula 1, and bidding for World Cup 2034). Tourism is opening up, with new visa regimes attracting visitors. The Public Investment Fund (PIF) is investing globally, buying stakes in tech companies, sports teams, and infrastructure. Credit rating agencies upgraded Saudi debt in 2024-2025—Moody's to Aa3, S&P to A+, Fitch affirmed A+. That's a vote of confidence in fiscal management. But dig deeper and problems emerge. Vision 2030 requires vast spending—NEOM alone is budgeted at $500 billion. Saudi Arabia is running budget deficits despite high oil prices. The economy remains overwhelmingly dependent on oil revenues, which fund 60-70% of the budget. Diversification is happening at the margins, not fundamentally. Unemployment among young Saudis remains high. The private sector isn't creating enough jobs, so the government is still the main employer. Mega-projects are flashy but not necessarily productive—building a futuristic city in the desert doesn't create sustainable economic transformation unless you attract businesses, talent, and innovation. And socially, while reforms are real, they're top-down. There's no grassroots civil society pushing change; it's MBS granting freedoms he could revoke anytime. The reforms are about economic necessity (getting women into the workforce) and soft power (rebranding Saudi Arabia), not genuine liberalization. Religious conservatives—long the bedrock of Al Saud legitimacy—are sidelined and silenced, which carries risks.

**Repression and the Crackdown on Dissent**

While MBS modernizes socially, politically he's tightened the screws. Dissent is crushed ruthlessly. Activists who pushed for reforms MBS later implemented are in prison. Loujain al-Hathloul, who campaigned for women's right to drive, was jailed and tortured—released only after international outcry. Dozens of clerics, intellectuals, and businessmen have been detained without trial. The 2018 murder of Jamal Khashoggi—a Saudi journalist and critic living in the U.S., killed and dismembered in the Saudi consulate in Istanbul—was the most brazen example. U.S. intelligence concluded MBS ordered it. In November 2025, that calculation is clear: MBS modernizes on his terms, brooking no dissent. The judiciary is controlled, trials are secretive, and the security apparatus is pervasive. Human rights organizations consistently rank Saudi Arabia among the world's most repressive states. Women's rights activists, Shia minority leaders, reformist clerics—anyone who challenges the narrative faces arrest. Social media is monitored; critics abroad are tracked. There's credible evidence of Saudi agents harassing dissidents overseas. The message is clear: there's no safe space to criticize MBS, even beyond Saudi borders. This creates a chilling effect. Saudis self-censor, avoid politics, and focus on economic opportunities. The social contract is: accept MBS's rule, benefit from reforms and economic growth, and don't ask for political freedoms. For many, especially younger Saudis enjoying new entertainment options, that's acceptable. But it's a fragile bargain—if economic growth stalls or Vision 2030 fails to deliver, discontent could emerge with no outlet.

**Foreign Policy: Balancing Trump, Iran, and Regional Ambitions**

Saudi foreign policy is increasingly assertive under MBS, and November 2025 is a critical moment. On November 18th, MBS is meeting Trump in Washington, seeking ironclad U.S. security guarantees, advanced aircraft, and—most controversially—civilian nuclear technology. He's offering cooperation on Trump's Gaza peace plan in exchange. MBS needs American security backing, especially as Saudi-Iranian tensions simmer. The Yemen war—Saudi Arabia's disastrous intervention against Houthi rebels backed by Iran—officially ended, but Houthi threats continue. In early November, a Houthi leader threatened Saudi Arabia for allegedly violating ceasefire commitments. Any restart of war with the Houthis would derail Vision 2030, draining resources and focus. On oil policy, MBS is caught between Trump (who wants higher Saudi production to lower prices) and Russia. Saudi Arabia leads OPEC+, and Russia has successfully persuaded Riyadh to halt production increases into 2026, keeping prices elevated. It's a delicate dance: MBS needs high oil prices to fund Vision 2030, but he also needs American security and access to technology. Meanwhile, Saudi-Israeli normalization is advancing quietly. MBS has signaled openness, contingent on progress toward a Palestinian state—though he's vague on details. Normalization would be geopolitically massive, cementing a Saudi-Israeli-U.S. axis against Iran. But it's domestically risky for MBS; Saudis broadly support Palestinians, and normalization without meaningful Palestinian statehood could spark backlash. Regional rivals complicate things. The UAE is increasingly competitive—Dubai's rise as a business hub threatens Saudi ambitions. Iran remains the primary adversary, with proxy conflicts in Yemen, Iraq, Syria, and Lebanon. And Qatar, long a rival, is now conditionally reconciled but still irritating.

**The Bottom Line**

Saudi Arabia in November 2025 is an absolute monarchy undergoing managed modernization, with all power concentrated in Mohammed bin Salman's hands. Vision 2030 shows real progress—social reforms, economic diversification efforts, mega-projects—but remains dependent on oil revenues and vulnerable to economic shocks. Politically, the system is more authoritarian than ever: dissent is crushed, institutions are hollow, and MBS's rule is unchallengeable. The big risks are threefold. First, economic: can Saudi Arabia actually diversify away from oil dependence, or will Vision 2030 prove a mirage of expensive vanity projects? Second, political: can MBS's top-down modernization survive without political freedoms or genuine institutions? If economic growth falters and repression is the only governance tool, instability could follow. Third, regional: can Saudi Arabia manage tensions with Iran, balance U.S. and Russian interests, and pursue normalization with Israel without domestic or regional blowback? The November 18th Trump meeting is crucial—MBS is betting on U.S. security guarantees and technology access to underwrite Vision 2030. If that bet pays off, Saudi Arabia could emerge as a regional powerhouse. If it fails—if oil prices crash, mega-projects stall, or regional conflicts spiral—the authoritarian modernization model could unravel fast. Watch three things: Vision 2030's economic results (jobs, diversification, not just PR), whether repression intensifies or reforms create genuine pluralism (unlikely), and whether MBS can navigate the U.S.-Iran-Israel triangle without catastrophic miscalculation. For now, MBS is winning—consolidating power, modernizing society, and projecting confidence. But Saudi Arabia remains a brittle autocracy betting everything on one man's vision.`,
    issues: JSON.stringify([
      'MBS consolidation of power and authoritarianism',
      'Vision 2030 economic diversification and challenges',
      'Repression of dissent and human rights abuses',
      'Foreign policy balancing act with US, Iran, and regional rivals'
    ]),
    topStories: JSON.stringify([
      {
        title: 'Saudi MBS to meet Trump, seeking security guarantees and nuclear tech',
        source: 'Soufan Center',
        link: 'https://thesoufancenter.org/intelbrief-2025-november-6/',
        pubDate: '2025-11-06'
      },
      {
        title: 'Houthi leader threatens Saudi Arabia over ceasefire violations',
        source: 'Soufan Center',
        link: 'https://thesoufancenter.org/intelbrief-2025-november-6/',
        pubDate: '2025-11-01'
      }
    ])
  },
  {
    name: 'Senegal',
    country: 'Senegal',
    lat: 14.6928,
    lng: -17.4467,
    summary: `Senegal just pulled off something rare in West Africa: a genuine democratic transition where the opposition won and the incumbents left peacefully. In March 2024, Bassirou Diomaye Faye—a 44-year-old former tax inspector and political outsider—won the presidency, ending 12 years of rule by President Macky Sall and the old guard. Faye's PASTEF party then crushed it in November 2024 legislative elections, winning 130 of 165 seats—the biggest landslide since 1988. For a region plagued by coups and democratic backsliding, Senegal looked like a beacon. But in November 2025, the shine is coming off. PASTEF just dissolved the coalition that brought Faye to power, exposing a bitter rift between Faye and his political mentor Ousmane Sonko, who many see as the real power behind the throne. The IMF left Senegal last week without agreeing a new program, spooked by the revelation of $7 billion in unreported loans discovered when Faye took office. Senegal's dollar bonds have slumped. The economy is shaky. And the new government—elected on a transformative agenda of sovereignty, renegotiating resource contracts, and breaking with neocolonial structures—is learning that governance is harder than opposition. Senegal's democracy is still intact, but the PASTEF experiment is hitting turbulence fast. The big question is whether Faye can deliver on his ambitious promises, manage coalition tensions, and navigate economic constraints—or whether disillusionment sets in and Senegal's democratic moment becomes another African disappointment.

**The PASTEF Landslide and the End of the Old Guard**

Let's start with the dramatic rise of PASTEF (African Patriots of Senegal for Work, Ethics, and Fraternity). Until recently, they were outsiders—Ousmane Sonko, a fiery populist and tax inspector-turned-politician, built PASTEF into a movement against corruption, French neocolonialism, and elite impunity. Sonko ran for president in 2019 and came third, building a base among young, frustrated Senegalese tired of stagnant politics. In 2024, he was blocked from running due to legal troubles widely seen as politically motivated. So PASTEF fielded Bassirou Diomaye Faye, Sonko's protégé, who was literally in prison until days before the election. Faye won in March 2024 with 54% in the first round—a stunning upset. But Faye faced an opposition-controlled parliament, making it impossible to govern. So in September, he dissolved the National Assembly and called snap legislative elections for November 2024. PASTEF won 130 of 165 seats, dominating 40 of 46 departments. The old guard—Macky Sall's coalition, the Socialists—were obliterated. It was a mandate for change, and PASTEF promised big: renegotiating oil and gas contracts with foreign companies, pursuing "Vision Senegal 2050" transformation, rooting out corruption, and asserting sovereignty over resources. Voter turnout was high, enthusiasm palpable. Senegalese, especially the youth, believed change was finally coming. But now, a year into Faye's presidency, cracks are showing.

**The Faye-Sonko Rift and Coalition Collapse**

Here's where it gets messy. Ousmane Sonko, though not president, is prime minister and widely seen as the real ideological force behind PASTEF. Faye was his loyal deputy, but now there's a power struggle. In November 2025, PASTEF dissolved the coalition that helped elect Faye, citing "leadership tensions." Rumors of a rift between Faye and Sonko have circulated for months—both deny it publicly, but the coalition collapse fuels speculation. The dynamic is tricky: Faye is president, but Sonko commands the grassroots, the radical base, the populist energy. Faye is technocratic, cautious; Sonko is confrontational, ideological. As governing pressures mount—economic constraints, IMF negotiations, investor jitters—those differences are sharpening. Coalition partners are being sidelined, and PASTEF is consolidating power within a smaller, more ideologically rigid circle. Politically, this is risky. PASTEF's landslide gave them dominance, but coalitions exist for a reason—they broaden support, share blame, and manage expectations. Dissolving the coalition isolates PASTEF, making them solely responsible for successes and failures. If the economy worsens or promises go unmet, there's no one else to blame. Moreover, Sonko's hardline positions—demanding renegotiation of contracts, confronting France, pushing anti-corruption drives—play well in rallies but complicate governance. Foreign investors are nervous, the IMF is balking, and Senegal's business community is bracing for disruption. Faye, as president, has to manage these realities, which puts him at odds with Sonko's base. The rift is dangerous because PASTEF's legitimacy rests on internal cohesion. If Faye and Sonko split openly, it could fracture the party and disillusion supporters who believed PASTEF was different from the old corrupt elites.

**Economic Troubles and the IMF Standoff**

Senegal's economy is in trouble, and that's the elephant in the room. When Faye took office, his government announced the discovery of $7 billion in unreported loans taken by the previous administration—debts that weren't disclosed. It was a bombshell, revealing fiscal mismanagement and raising questions about Senegal's debt sustainability. Public debt now exceeds 70% of GDP, far above regional norms. The IMF had a program with Senegal, but negotiations for a new program collapsed in November 2025. The IMF left without agreement, spooked by fiscal opacity and PASTEF's ambitious spending plans. Senegal's dollar bonds slumped on the news, raising borrowing costs and signaling investor concern. PASTEF's agenda requires money—lots of it. Vision Senegal 2050 involves infrastructure, education, healthcare, and industrialization. Renegotiating oil and gas contracts could generate revenue long-term but creates uncertainty now, deterring investment. Meanwhile, inflation is rising, unemployment remains high (especially among youth, PASTEF's core base), and the cost of living is squeezing ordinary Senegalese. Faye's government is caught between populist promises and economic reality. The IMF wants fiscal discipline, subsidy cuts, and structural reforms—politically toxic measures. PASTEF's base wants transformative spending, not austerity. Threading that needle is proving impossible. The risk is that economic mismanagement undermines PASTEF's credibility. If growth stalls, inflation persists, and jobs don't materialize, voters who believed in change will lose faith. The old guard—battered but not destroyed—will seize on failures, arguing PASTEF is incompetent.

**Sovereignty, Resource Nationalism, and the France Question**

PASTEF's ideology centers on sovereignty and breaking neocolonial ties, especially with France. Senegal was a French colony, and France retains significant economic and political influence—CFA franc currency, military presence, business dominance in key sectors. Sonko and PASTEF have long argued that true independence requires ejecting French influence and controlling Senegal's resources. In power, they're pursuing this—reviewing contracts with foreign oil and gas companies (including French firms), pushing for local ownership of natural resources, and rhetorically distancing from France. This resonates domestically. Many Senegalese see France as exploitative, and resource nationalism is popular. Senegal has major offshore oil and gas discoveries coming online soon—projects that could transform the economy. PASTEF wants to ensure Senegalese benefit, not just foreign multinationals. But renegotiating contracts spooks investors. Companies that signed agreements under previous governments now face uncertainty. Capital is mobile; if Senegal is seen as hostile to foreign investment, money goes elsewhere. The government insists it's seeking fair terms, not expropriation, but the rhetoric is combative. On France, Senegal is balancing. Faye hasn't expelled French troops or exited the CFA franc (though debates continue). He's signaling autonomy without full rupture. But France is watching nervously, and if Senegal tilts further toward resource nationalism or geopolitical nonalignment (cozying up to China or Russia), it could strain relations.

**The Bottom Line**

Senegal in November 2025 is at a crossroads. Bassirou Diomaye Faye and PASTEF won a historic mandate for change, and Senegal's democratic credentials remain strong—this was a real election, a genuine transition, and the opposition conceded peacefully. But governance is proving harder than campaigning. The coalition that brought Faye to power is fracturing, exposing tensions between Faye and Sonko. The economy is shaky, the IMF negotiations have stalled, and investor confidence is slipping. Ambitious promises of transformation are colliding with fiscal constraints, and voters are watching closely. The big risks: First, the Faye-Sonko rift. If they split openly, PASTEF could fracture, and the political stability that's made Senegal exceptional in West Africa could erode. Second, economic performance. If PASTEF can't deliver jobs, growth, and living standard improvements, disillusionment will set in fast. The youth who voted for change won't wait forever. Third, investor confidence. Resource nationalism is popular, but if handled badly, it scares off capital Senegal desperately needs for development. Watch three things: whether Faye and Sonko publicly reconcile or the rift deepens, whether Senegal secures a new IMF program or faces fiscal crisis, and whether the oil and gas revenues materialize and benefit ordinary Senegalese or enrich elites. Senegal has a chance to prove that African democracies can deliver transformative change without coups or backsliding. But the window is narrowing. PASTEF has political dominance now, but if they mismanage the economy, fracture internally, or fail to meet expectations, Senegal's democratic moment could turn sour fast. For now, the jury is out. Senegal is still the most stable democracy in West Africa, but PASTEF's experiment in radical reform is being tested hard, and November 2025 is a pivotal moment. The stakes couldn't be higher.`,
    issues: JSON.stringify([
      'PASTEF landslide and coalition tensions',
      'Faye-Sonko power struggle and political rift',
      'Economic troubles and IMF standoff',
      'Resource nationalism and sovereignty agenda'
    ]),
    topStories: JSON.stringify([
      {
        title: 'Senegal dissolves coalition that helped elect President Faye',
        source: 'Bloomberg',
        link: 'https://www.bloomberg.com/news/articles/2025-11-12/senegal-dissolves-coalition-party-that-helped-elect-president',
        pubDate: '2025-11-12'
      },
      {
        title: 'Senegal\'s ruling party secures large majority in parliament',
        source: 'Anadolu Agency',
        link: 'https://www.aa.com.tr/en/africa/senegal-s-ruling-party-secures-large-majority-in-parliament/3401186',
        pubDate: '2024-11-19'
      }
    ])
  }
]

async function addPoliticsSummaries() {
  console.log('Adding Politics summaries for Batch 8 (Part 1/2)...\n')

  for (const summary of POLITICS_SUMMARIES) {
    try {
      const result = await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: summary.name,
            type: 'country',
            category: 'politics'
          }
        },
        create: {
          name: summary.name,
          type: 'country',
          country: summary.country,
          lat: summary.lat,
          lng: summary.lng,
          category: 'politics',
          summary: summary.summary,
          issues: summary.issues,
          topStories: summary.topStories,
          storyCount: 0,
          updatedAt: new Date()
        },
        update: {
          summary: summary.summary,
          issues: summary.issues,
          topStories: summary.topStories,
          updatedAt: new Date()
        }
      })

      console.log(`✅ ${summary.name} Politics added/updated`)
      console.log(`   ID: ${result.id}`)
      console.log(`   Category: ${result.category}`)
      console.log(`   Summary length: ${result.summary.length} characters`)
      console.log()
    } catch (error) {
      console.error(`❌ Error processing ${summary.name}:`, error)
      throw error
    }
  }

  console.log('Part 1/2 completed successfully!\n')
}

addPoliticsSummaries()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
