import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// UNITED STATES EDUCATION
const USA_EDUCATION = `The United States spends more per student than almost any country on Earth—around $16,000 annually—and gets mediocre results in return. PISA 2022 scores tell the story: American 15-year-olds scored 465 in mathematics (below the OECD average of 472), 504 in reading (above 476), and 499 in science (above 485). The U.S. rose in international rankings not because students improved, but because other countries fell further. Behind these averages hides America's real education story: savage inequality. Wealthy suburban districts deliver world-class education with small classes, experienced teachers, and lavish resources. Poor urban and rural districts operate schools that resemble minimum-security prisons—underfunded, understaffed, and producing graduates who can barely read. The achievement gap between rich and poor American students is among the widest in the developed world. Socioeconomic status predicts educational outcomes more reliably in the U.S. than in almost any OECD country, which is a polite way of saying America has built an education system that reinforces class privilege rather than disrupting it.

The structure is radically decentralized—16,000 school districts, each with its own governance, funding, and standards. This creates spectacular innovation in some places and spectacular failure in others, often in districts twenty miles apart. Funding comes primarily from local property taxes, which means rich neighborhoods fund excellent schools while poor neighborhoods can't afford textbooks. Federal efforts to equalize funding—Title I, Every Student Succeeds Act—barely dent the gaps. Teacher quality varies wildly: some districts attract top university graduates with competitive salaries and professional autonomy, while others staff classrooms with uncertified teachers because nobody else will take the job. The teaching profession itself is weirdly bifurcated—respected in some communities, politically attacked in others, and increasingly abandoned by young people who see better pay and working conditions elsewhere.

The literacy and numeracy situation is more complicated than headlines suggest. Most American students can decode text—the basic literacy rate is around 99%. The problem is comprehension and critical thinking. The National Assessment of Educational Progress shows only 35% of 4th graders read at proficient levels, and only 41% are proficient in math. By 8th grade, proficiency rates are similar. This isn't about access—it's about quality. Students attend school for years but don't learn to think critically, solve complex problems, or understand what they read beyond surface-level facts. Curriculum has been narrowed by high-stakes testing, especially in schools serving poor students, where test prep dominates and richer subjects—arts, history, science inquiry—get squeezed out.

The culture wars of 2024-2025 intensified education polarization. Battles over curriculum content—race, gender, history—consumed school board meetings, prompted teacher resignations, and resulted in book bans in conservative districts and ideological litmus tests in progressive ones. Both sides claim to defend children, but the real casualties are students whose education gets reduced to political theater. Teachers report demoralization, surveillance, and threats from parents and administrators. Enrollment in teacher preparation programs dropped 35% over the past decade, and districts face shortages, especially in math, science, and special education.

What America needs is obvious and politically impossible: equitable funding that doesn't depend on local wealth, curriculum that develops thinking rather than test-taking, restoration of teaching as a respected profession with competitive pay, and adults who agree that education's purpose is developing human potential rather than scoring political points. None of that is happening. The 2024 elections produced no consensus on education policy, and federal initiatives remain gridlocked. Meanwhile, American students continue attending schools that sort them by class, race, and geography into futures that were mostly determined before they learned to read.`

// CANADA EDUCATION
const CANADA_EDUCATION = `Canada has always been the education system Americans wish they had: high PISA scores, equitable funding, respected teachers, and social cohesion. But something is slipping. PISA 2022 showed Canadian 15-year-olds scoring 497 in mathematics—down 15 points from 2018—marking the steepest decline Canada has ever experienced in any PISA domain. Reading held steady at 507 (above the OECD average of 476), and science stayed strong at 515 (well above 485), but that math drop is alarming. One province, Newfoundland and Labrador, already fell below the OECD average. The decline reflects a decade of educational drift: discovery-based learning that sounds progressive but often means students don't master fundamentals, insufficient math coursework requirements for teacher certification, and curriculum reforms that prioritized equity rhetoric over ensuring every child actually learns to calculate. Canada isn't in crisis yet, but the trajectory is troubling for a country that built its identity partly on educational excellence.

The structural foundation remains strong. Education is provincially managed, which creates variation but also allows innovation and local responsiveness. Funding is relatively equitable—public dollars flow to schools based on enrollment and need rather than neighborhood wealth, so resource gaps between rich and poor districts are smaller than in the U.S. Teacher quality is high: entry requires university degrees and professional certification, salaries are competitive with other graduate professions, and teachers receive professional development and autonomy. The pupil-teacher ratio averages around 16:1 in primary schools—manageable for effective instruction. Infrastructure is solid, technology is standard, and most students have textbooks, supplies, and safe learning environments. These basics matter, and Canada delivers them.

But outcomes reveal deeper issues. The math decline isn't just numbers—it reflects pedagogical choices that didn't work. Canadian schools embraced inquiry-based and discovery learning, which research supports when done well but often devolves into minimal direct instruction and students left to figure things out themselves. This approach disadvantages students who lack home support or prior knowledge, widening gaps rather than closing them. Math education particularly suffered: fewer Canadian teachers have deep math backgrounds compared to top-performing countries, and professional development in math pedagogy has been inconsistent. Some provinces are reversing course—Ontario recently mandated more structured literacy instruction—but math reform lags.

Inequality exists but is less extreme than in peer countries. Indigenous students, recent immigrants, and students in remote communities face barriers—resource gaps, language challenges, cultural disconnection. The literacy rate overall is 99%, but that aggregate hides students who decode text without comprehending, especially among marginalized groups. Residential school legacies still shape Indigenous education outcomes, and reconciliation efforts in curriculum are beginning but uneven. Urban-rural gaps persist: Toronto and Vancouver offer excellent schools, while remote northern communities struggle with teacher retention, limited resources, and infrastructural deficits.

Higher education is accessible and high-quality. University enrollment rates are among the world's highest, driven by relatively affordable tuition (by North American standards), student aid programs, and strong employment returns to degrees. Canadian universities rank well internationally—University of Toronto, McGill, UBC—and produce graduates whose skills match labor market needs better than in many peer countries. The mismatch between credentials and employment exists but isn't catastrophic.

What Canada needs now is honest assessment of what's working and what isn't. The evidence shows discovery learning without sufficient structure leaves too many students behind, especially in math. Teacher training needs more math content and effective pedagogy. Curriculum must balance skills and knowledge, not choose one at the expense of the other. And Canada must confront the gaps facing Indigenous, immigrant, and remote students with more than good intentions—sustained investment and structural change. The PISA decline is a warning. Canada can correct course before mediocrity becomes the norm, but that requires acknowledging problems and acting on evidence rather than ideology. The next PISA results in 2026 will show whether Canada listened.`

// MEXICO EDUCATION
const MEXICO_EDUCATION = `Mexico's education system is a paradox: literacy reached 95.8%, enrollment is near universal, and the government's rhetorical commitment to education is boundless—yet 70% of students can't read a simple text with comprehension by third grade, learning outcomes are abysmal, and President López Obrador gutted the one reform that might have improved teacher quality. AMLO repealed the 2013 education reform that introduced teacher evaluations, eliminated the independent assessment institute (INEE), and cut education spending by $12 billion—a 10% reduction—since 2018. In November 2024, Instituto Natura hosted urgent discussions revealing that one in three third-graders cannot comprehend what they read, launching the Fundamental Learning Policy in five states. Mexico put children in schools, printed diplomas, and declared victory, but the system teaches very little. Attendance is high; learning is catastrophic.

The structure is large and unwieldy: 25 million students, 1.2 million teachers, and a federal-state funding arrangement that produces chaos and inequality. The wealthiest states—Mexico City, Nuevo León—deliver decent education with qualified teachers and functional infrastructure. The poorest states—Chiapas, Oaxaca, Guerrero—operate schools where students sit on dirt floors, share textbooks at ratios of 6:1, and learn from teachers who themselves barely completed secondary school. Indigenous communities face the worst conditions: literacy rates 10 times lower than in Mexico City, instruction in Spanish that students don't speak, and curriculum disconnected from their lives. The teacher's union, SNTE, is one of Latin America's most powerful political machines, historically more focused on job protection than student learning, though recent leadership has been somewhat reformist.

The teaching crisis defines everything else. AMLO's reversal of teacher evaluations meant hiring, promotion, and compensation no longer depend on performance—they depend on union seniority and political connections. Many teachers are poorly trained, frequently absent, or work second jobs because salaries are inadequate. Professional development is sporadic and low-quality. The best teachers leave for private schools or emigrate. Rural schools routinely operate with one teacher covering all grades, no materials, and no support. Urban schools fare better but still struggle with overcrowding, outdated curriculum, and assessment systems that measure memorization rather than thinking.

Learning outcomes are dismal despite high enrollment. Mexico doesn't participate in PISA regularly, but the 2018 results showed 15-year-olds scoring 409 in math, 420 in reading, and 419 in science—all well below OECD averages. National assessments paint an even darker picture: most elementary students can't solve basic math problems, can't understand grade-level texts, and can't think critically. Rote memorization dominates pedagogy. Students copy from blackboards, recite facts, and take exams that test recall rather than comprehension. Science education is entirely theoretical because labs don't exist. Dropout rates are high, especially in secondary school—only 60% complete upper secondary, and many who do have learned almost nothing.

Higher education expanded rapidly but quality is uneven. Public universities like UNAM are excellent but serve tiny fractions of students. Most attend overcrowded state universities or low-quality private institutions that credential without educating. Graduate unemployment is rising not because jobs don't exist but because degrees don't signal competence. Employers complain university graduates lack critical thinking, technical skills, and work readiness.

Mexico's education crisis isn't mysterious: you can't improve teaching quality by eliminating accountability, you can't close gaps by defunding schools, and you can't develop thinking by emphasizing memorization. AMLO's education policies reflected political calculations—rewarding the teacher's union—not evidence about what works. The Federal Commitment to Literacy is a step forward, but it's five states among thirty-two, and without teacher quality, infrastructure, and curriculum reform, literacy campaigns fail. Mexico has the resources to educate its children well. It lacks the political will to challenge vested interests, implement evidence-based policies, and sustain reform past one administration. A generation is growing up attending school for years and leaving barely able to read. That's not education—it's institutionalized failure.`

// BRAZIL EDUCATION
const BRAZIL_EDUCATION = `Brazil's PISA 2022 scores were brutal: 379 in mathematics, 410 in reading, 403 in science—all far below OECD averages and barely improved from 2009. Thirteen years of policy effort, billions in spending, and outcomes have flatlined. But here's what the averages hide: Brazil doesn't have one education system, it has dozens, and the gaps between them are grotesque. Students in wealthy São Paulo neighborhoods attend well-resourced schools with qualified teachers and score near OECD benchmarks. Students in rural Bahia or Amazonian communities attend schools without walls, teachers, or textbooks and score below sub-Saharan African averages. At the student level, attending a private school confers an advantage equivalent to four years of additional schooling. Brazil's education system doesn't reduce inequality—it manufacturers it at scale, ensuring rich children become rich adults and poor children stay poor.

The structure is federal, but implementation is state and municipal, creating radical variation. Brazil spends about 6% of GDP on education—meeting UNESCO recommendations—but distribution is grossly inequitable. The wealthiest states have adequate funding, infrastructure, and teachers; the poorest states operate schools that barely function. The Northeast and North regions face chronic underfunding, teacher shortages, and infrastructure deficits. Municipalities are responsible for primary education but often lack capacity or resources to deliver quality. Federal programs attempt to equalize—Fundeb, PNAE, textbook distribution—but they can't overcome structural inequality. Corruption siphons resources, political instability disrupts reforms, and vested interests resist change.

Teacher quality is wildly uneven. In wealthy regions, teachers have university degrees, professional training, and decent salaries. In poor regions, teachers are under-qualified, underpaid, and unsupported. The average salary is low enough that teachers need second jobs, morale is terrible, and turnover is high. Professional development is inconsistent, supervision minimal, and accountability weak. Teaching methods emphasize rote memorization and copying from blackboards. Critical thinking, problem-solving, and creativity are absent from most classrooms. Students spend years in school learning to recite but not to think.

Learning outcomes reflect these failures catastrophically. Only 44% of Brazilian students reach Level 2 proficiency in PISA mathematics—meaning 56% can't solve basic problems. Literacy rates are officially high—around 93%—but functional literacy is far lower. Many adults can decode text but not comprehend or apply information. Socioeconomic status is the single strongest predictor of educational outcomes—students from wealthy families succeed regardless of school quality, students from poor families fail regardless of talent or effort. Grade repetition is common and disastrous: repeating a grade has the largest negative effect on achievement, locking students into cycles of failure.

The inequality dimensions are brutal: race, class, region, and urban-rural all predict outcomes. Afro-Brazilian students score far below white students, even controlling for income. Indigenous students face catastrophic exclusion. Rural students score dramatically worse than urban students. Northeastern students score far below Southeastern students. The system delivers excellent education to the already privileged and barely-functional education to everyone else. This isn't accidental—it's structural, reflecting centuries of inequality that education policy hasn't challenged.

Higher education expanded dramatically—enrollment quintupled since 2000—but quality didn't keep pace. Public federal universities are excellent but serve tiny fractions of students. Most attend private institutions of wildly varying quality, often accumulating debt for degrees employers don't value. The labor market increasingly demands skills universities don't teach, creating graduate unemployment and underemployment. Vocational education exists but is underdeveloped and stigmatized.

Brazil's recent Novo Ensino Médio reform made upper secondary more flexible and vocational options more accessible—a genuine improvement if implemented well. But implementation is inconsistent, funding uncertain, and political commitment wavering. Brazil knows what needs to happen: equitable funding, massive investment in teacher quality, curriculum emphasizing thinking over memorization, and confronting the structural inequalities that predetermine outcomes. The 2025 PISA results will show whether the trajectory changed. Based on current evidence, expect more stagnation, more excuses, and another generation denied the education Brazil's constitution promises but its system doesn't deliver.`

// ARGENTINA EDUCATION
const ARGENTINA_EDUCATION = `Argentina's education system is collapsing in real time. The November 2024 Aprender assessment revealed only 45% of third-graders demonstrate sufficient reading comprehension—meaning 55% of eight-year-olds can't understand basic texts. Mathematics is worse: 65% are significantly behind. President Javier Milei responded with the Federal Commitment to Literacy, a national-provincial agreement to improve early literacy, while simultaneously cutting education funding by over 30% in real terms since 2023. Teacher training programs lost 40%, early childhood infrastructure dropped 60%, and scholarships for low-income students fell 40%. This is education policy as performance art: announce bold literacy campaigns while defunding schools. Argentina once had Latin America's best education system. Decades of economic chaos, political dysfunction, and now libertarian austerity have reduced it to shambles.

The structural problem is economic instability intersecting with policy incoherence. Argentina spends around 5% of GDP on education, but chronic inflation and currency crises mean real resources fluctuate wildly. Teachers' salaries erode monthly, striking repeatedly for wages that keep pace with inflation. Milei's government treats education as a budget line to cut rather than an investment to protect. Provincial governments manage schools, but many lack resources to pay teachers on time, maintain buildings, or provide materials. Inequality between provinces is extreme: Buenos Aires and Córdoba operate functional systems; poorer provinces like Formosa and Chaco barely function. Federal attempts at coordination—national curriculum standards, teacher training, assessment—are chronically underfunded and poorly implemented.

Teacher quality is declining. Salaries are low and falling in real terms, experienced educators leave for any job that pays reliably, and teacher training programs are underfunded. Those who remain are demoralized, often striking, and working in impossible conditions. Professional development is minimal, resources scarce, and support non-existent. Class sizes in urban schools exceed 40 students, rural schools operate with one teacher covering all grades, and many schools lack basic materials. The curriculum emphasizes rote memorization, students copy from blackboards because textbooks don't exist, and learning is reduced to preparing for standardized exams that measure recall rather than thinking.

Higher education tells a similar story. Argentina's public universities are tuition-free—a genuine achievement—but chronically underfunded, overcrowded, and producing graduates whose skills don't match labor market needs. The University of Buenos Aires operates in decaying buildings with underpaid faculty and 400-student lecture halls. Milei's government proposed charging tuition to foreign students, sparking massive protests. Academic quality is uneven, research funding negligible, and brain drain severe—Argentina's best graduates emigrate to countries where their degrees earn livable salaries. Graduate unemployment is high because degrees don't signal competence, while employers can't find workers with needed technical skills.

The inequality dimensions are stark. Private schools serve wealthy families and deliver education comparable to OECD standards. Public schools serve everyone else and deliver outcomes comparable to much poorer countries. In PISA 2022 (if Argentina participates—it withdrew in recent cycles), Argentine students scored around 379 in math, 400 in reading, and 404 in science, all well below OECD averages. But averages hide brutal disparities: affluent urban students score 100+ points higher than poor rural students. Socioeconomic status determines outcomes more reliably than any other factor. Argentina's education system reproduces class privilege rather than disrupting it.

What Argentina needs is economic stability, political commitment to education as a priority rather than a budget cut, massive investment in teacher salaries and training, infrastructure repair, and curriculum reform emphasizing critical thinking. None of that is happening under Milei, whose libertarian ideology treats public education as inefficient state waste. The Federal Commitment to Literacy is rhetoric unless accompanied by resources, and current policies guarantee deterioration. Argentina is experiencing educational collapse during economic crisis—again. This happened in the 1980s, the 1990s, the 2000s, and now the 2020s. Each cycle leaves a generation undereducated. The 55% of third-graders who can't read will become adults who can't fully participate in democracy or the economy, and Argentina will remain trapped in cycles of dysfunction partly because its education system failed them.`

// CHILE EDUCATION
const CHILE_EDUCATION = `Chile consistently ranks as Latin America's best-performing education system in PISA, alongside Uruguay, scoring 412 in mathematics, 448 in reading, and 444 in science in 2022—above regional peers and approaching OECD averages. But "best in Latin America" is damning with faint praise when the regional average is catastrophic, and Chile's scores remained stable only because other countries fell. Behind the relative success lies brutal inequality: Chile operates one of the world's most segregated education systems, where wealthy students attend excellent private schools and poor students attend chronally failing public schools. On average, 88% of the poorest students underperform in mathematics compared to 55% of the richest. Immigrant students score 29 points lower than non-immigrants, with 18 points remaining after controlling for socioeconomic factors. Chile's education system delivers quality to those who can pay and mediocrity to everyone else. This isn't a bug—it's the design.

The structure is radically market-based, inherited from Pinochet's neoliberal revolution. Private schools, charter schools, and voucher-funded schools educate most students, competing for enrollment. The theory: competition drives quality improvement. The reality: schools compete for wealthy students who boost test scores, reject poor students who don't, and inequality explodes. The wealthiest families pay for elite private schools with small classes, experienced teachers, and abundant resources. Middle-class families access decent voucher-funded schools. Poor families send children to underfunded municipal public schools that wealthier families abandoned, creating concentrations of poverty and dysfunction. Teachers sort themselves similarly: qualified, experienced educators work in private schools with competitive salaries and good conditions; under-qualified, novice teachers staff public schools because nobody else will take those jobs.

Funding is inequitable by design. Private schools charge tuition on top of state vouchers, accumulating resources public schools can't match. Municipal schools depend on vouchers that don't cover real costs, leading to chronic deficits, deferred maintenance, and resource shortages. The government attempts equalization through preferential vouchers for disadvantaged students, but the gaps remain vast. Infrastructure in private schools is modern; public schools operate in aging buildings without adequate furniture, technology, or materials. Class sizes in public schools exceed 40; private schools maintain 20. The 2015 Inclusion Law attempted reforms—prohibiting schools from selecting students based on ability or income, eliminating for-profit voucher schools—but implementation has been weak and resistance fierce.

Learning outcomes reflect these structural inequalities. Chile's PISA scores are respectable on average but hide massive variance. Students in wealthy Santiago neighborhoods score above OECD averages; students in poor rural areas or urban slums score below 350—over 100 points lower, equivalent to three years of schooling. Socioeconomic status is destiny: 44% of Chilean students reach Level 2 mathematics proficiency overall, but this masks near-universal proficiency among the wealthy and near-universal failure among the poor. Literacy rates are officially 96%, but functional literacy is far lower among marginalized students. Indigenous Mapuche students face particular exclusion: curriculum disconnection, discrimination, and under-resourced schools ensure failure.

Higher education expanded dramatically but remains highly stratified. Elite universities—Universidad de Chile, Pontificia Universidad Católica—deliver excellent education to students from wealthy families who survived the academic obstacle course. Mass universities serve middle and working-class students with uneven quality. For-profit universities exploded in the 2000s, enrolling students in debt-financed programs of dubious quality, creating graduate unemployment and debt crises. The 2018 student protests demanded free higher education, leading to government commitments that have been partially implemented but chronically underfunded.

What Chile needs is structural reform confronting market-driven segregation. That means eliminating private schools' ability to charge tuition, equalizing funding across schools regardless of student composition, ensuring qualified teachers work where they're needed most rather than where they're paid most, and curriculum reform emphasizing thinking rather than test preparation. The Inclusion Law was a start, but implementation stumbled on political resistance and insufficient funding. Chile's education system succeeds at credentialing elites and failing everyone else. That's not accidental—it's what market-based systems do. Chile can either accept brutal inequality as the price of "efficiency" or rebuild education around equity and public goods. Current trajectories suggest the former. The 2025 PISA results will likely show continued stagnation, continued inequality, and continued acceptance of failure as normal for Chile's poorest children.`

// COLOMBIA EDUCATION
const COLOMBIA_EDUCATION = `Colombia's literacy rate is officially 90%, which sounds respectable until you see that over 70% of upper-secondary students lack basic literacy and numeracy skills, meaning they can decode letters but not comprehend texts or solve problems. In PISA assessments, 47% of Colombian students score below international minimums—they spend years in school and emerge barely educated. The rural-urban divide is grotesque: urban literacy rates reach 95%, rural rates drop to 82%, and learning outcomes are even worse. Of the 4.6% of GDP Colombia invests in education, only 0.5% reaches rural areas, which explains why two in ten rural students still can't access schooling at all. Colombia succeeded at expanding enrollment—primary reaches 87%, secondary 75%—but completely failed at ensuring students learn anything once they arrive. This is what happens when education policy prioritizes quantity over quality: schools full of children learning almost nothing.

The structural problem is decentralization without capacity. Colombia's 1991 constitution devolved education to municipalities, which vary wildly in resources and governance. Wealthy urban areas like Bogotá and Medellín operate functional school systems with qualified teachers, adequate infrastructure, and curriculum delivery. Poor rural areas and conflict-affected regions operate schools in name only—buildings without teachers, teachers without training, students without textbooks. The national government sets standards, distributes some funding, and conducts assessments, but implementation depends on municipal capacity that often doesn't exist. Corruption diverts resources, bureaucratic dysfunction delays delivery, and remote areas are simply abandoned. The Ministry of Education knows these problems—its reports document them exhaustively—but fixing them requires confronting entrenched interests and investing in unsexy basics like roads, teacher housing, and administrative capacity.

Teacher quality is the central crisis. Colombia needs 50,000 more teachers just to meet current enrollment, and the existing workforce is under-qualified and inequitably distributed. Urban schools attract university-educated teachers with professional certification; rural schools get whoever will show up, often with only secondary education themselves. Salaries are low, working conditions terrible, and rural postings mean isolation, no infrastructure, and sometimes physical danger in conflict zones. Professional development is sporadic, supervision minimal, and support non-existent. The best teachers concentrate in cities, the weakest in rural areas where students need the most help—exactly backward. Teaching methods emphasize rote memorization because teachers don't know how else to teach. Students copy from blackboards, recite facts, and take exams measuring recall rather than comprehension.

Infrastructure inequality is staggering. Urban schools have electricity, running water, toilets, furniture, and textbooks. Rural schools often lack all of these. Students sit on dirt floors, share textbooks at ratios of 6:1, and learn without materials. Science education is entirely theoretical because labs don't exist. A 2025 study using Grounded Theory found persistent gaps in infrastructure, teacher training, and student retention in rural areas despite decades of policy attention. Roads matter enormously—a 2025 study found road improvements significantly increase education access and completion in rural Colombia, suggesting transportation infrastructure may matter more than school construction in remote areas. Colombia hasn't built the basic infrastructure enabling education.

Learning outcomes reflect systemic failure. Using PISA microdata from 2006-2012, researchers found rural students consistently score far below urban students, and the gap hasn't closed. Socioeconomic status, parental education, and location determine outcomes more reliably than student effort or ability. The curriculum is disconnected from students' lives, especially in rural areas where content assumes urban middle-class contexts. Students spend years in schools that don't teach them to think, problem-solve, or understand their world.

Higher education expanded rapidly but quality is uneven. Public universities in major cities—Universidad Nacional, Universidad de Antioquia—deliver decent education but serve tiny fractions of students. Most attend private universities of wildly varying quality, often accumulating debt for degrees employers don't value. Graduate unemployment is rising as university expansion outpaces labor market absorption. Colombia's peace process created education opportunities in formerly conflict-affected areas, but implementation has been slow and underfunded. Rural communities promised education infrastructure saw little delivery, undermining trust in government commitments. Colombia knows what it needs to do: triple rural education investment, recruit and train tens of thousands of teachers with incentives to work where they're needed, build basic infrastructure, and reform curriculum around competencies rather than memorization. The government has plans, strategies, and rhetoric. What it lacks is follow-through, and Colombian students pay the price. Enrollment is high, learning is catastrophic, and the system calls that success.`

// PERU EDUCATION
const PERU_EDUCATION = `Peru's education system is an inequality-generating machine, where socioeconomic status explains 21.5% of variance in reading scores—the highest level among all PISA-participating countries. That's not a typo: being born rich versus poor determines educational outcomes in Peru more than anywhere else PISA measures. In 2022, Peruvian 15-year-olds scored 391 in mathematics, 408 in reading, and 408 in science—all far below OECD averages and barely improved from 2000. The rural-urban divide is catastrophic: between 2007 and 2014, satisfactory reading levels climbed from 21% to 50% in urban areas but only 6% to 17% in rural areas. In mathematics, urban gains went from 9% to 30% while rural areas crept from 5% to 13%. Peru put millions of children in schools over the past two decades, but the schools in rural areas, indigenous communities, and urban slums don't teach them. This isn't an education system—it's an inequality preservation system with classrooms.

The structural problem is extreme centralization colliding with extreme geographic fragmentation. Peru's Ministry of Education sets national standards, manages curriculum, and distributes funding, but implementation happens across Andean mountains, Amazon rainforests, and coastal cities with zero infrastructure connecting them. Lima gets qualified teachers, functional schools, and resources; rural Ayacucho gets one-room schoolhouses with teachers who've completed only primary education themselves. The government attempted decentralization in the 2000s, devolving education management to regions, but most lacked capacity, and the reform stalled. The result: neither centralization nor decentralization works, and students fall through the cracks. Corruption is endemic—resources meant for schools disappear, ghost teachers collect salaries, and monitoring is too weak to catch it.

Teacher quality is wildly uneven and predictably inequitable. Urban schools attract university-educated teachers with professional certification, decent salaries, and career opportunities. Rural schools get whoever accepts remote postings—often locals with minimal training, teaching in Spanish they barely speak to students who speak Quechua or Aymara at home. The linguistic barrier alone is catastrophic: instruction happens in a language most rural students don't understand, guaranteeing failure. Professional development is sporadic and urban-biased. Teachers in Lima get workshops and support; teachers in rural areas get nothing. Salaries are low enough that urban teachers moonlight at second jobs and rural teachers farm to survive. Teaching methods emphasize memorization because that's how teachers were taught and because critical thinking requires resources and training that don't exist.

Infrastructure in rural areas is non-existent or collapsing. Schools operate without electricity, running water, toilets, or roofs. Students sit on dirt floors, share slates, and copy lessons because textbooks don't reach remote areas or arrive in Spanish that students can't read. Science education is entirely theoretical. The curriculum is designed for urban middle-class contexts and completely disconnected from rural students' lives. A child in an Amazon community learns Lima-centric history and geography irrelevant to their world, in a language they don't speak, from a teacher who doesn't live in the community and may not show up. Dropout rates are high because students and families see no value in education that doesn't teach useful skills or lead to opportunities.

Learning outcomes are predictably dismal. National assessments show most second-graders in rural areas can't read simple sentences in Spanish. By sixth grade, most still can't. Mathematics is worse: rural students complete primary school unable to solve basic problems. The rural-urban gap has persisted for decades despite government commitments to close it. Peru's education system is excellent at teaching wealthy urban children and catastrophic at teaching everyone else. This isn't accidental—it's structural, reflecting geographic inequality, ethnic discrimination, and political neglect.

Higher education expanded rapidly—enrollment quintupled since 2000—but quality didn't keep pace. Elite universities in Lima deliver decent education to tiny fractions of students who survived the academic obstacle course. Mass universities and for-profit institutions credential students without educating them. Many graduates are unemployed or underemployed because degrees don't signal competence. Employers complain university graduates lack basic skills—reading comprehension, mathematical reasoning, critical thinking—because the education system never taught them.

Peru needs to triple rural education investment, recruit and train teachers who speak indigenous languages and understand rural contexts, build basic infrastructure, shift to mother-tongue instruction in early grades, and reform curriculum around competencies rather than memorizing Lima-centric facts. None of this is happening at scale. Peru's education policy documents say all the right things, but implementation stumbles on corruption, capacity gaps, and political indifference. Socioeconomic status is destiny in Peru because the education system makes it so. Rich children get educated, poor children get babysitting with textbooks. That's not education—it's systemic failure dressed as policy.`

// VENEZUELA EDUCATION
const VENEZUELA_EDUCATION = `Venezuela's education system didn't decline—it collapsed. Teachers earn $6 to $11 per month, yes per month, even with decades of experience. Nearly 40% of classrooms lack a full-time teacher because educators emigrated, quit for any job paying survival wages, or stopped showing up without formally resigning. Between 2022 and 2023, teachers staged 3,200 protests—desperate attempts to demand wages allowing them to afford food and rent. It didn't work. Last year, 34% of children and young adults aged 3-24—three million people—did not attend any educational institution. Those who did attend found schools without teachers, textbooks, electricity, or often running water. Venezuela once had one of Latin America's best education systems, with near-universal literacy, strong universities, and respected teachers. Nicolás Maduro's authoritarian misgovernment destroyed it in a decade. This isn't education reform going badly—it's state collapse, and education is a casualty.

The crisis is economic and political. Hyperinflation, currency collapse, and economic sanctions created humanitarian catastrophe affecting every sector, but education was hit particularly hard. Teacher salaries, always modest, became worthless as inflation eroded them daily. A teacher's monthly salary buys maybe one week of groceries. Most teachers left the profession entirely, emigrating to Colombia, Chile, Ecuador, or anywhere offering survival wages. Of the eight million Venezuelans who fled the country, a disproportionate share were educated professionals—doctors, engineers, scientists, teachers. In Chile alone, 64% of registered Venezuelan residents have undergraduate or postgraduate degrees. This is brain drain on a catastrophic scale, and education bore the brunt. The teachers who remain are either unable to leave or stay out of desperation, but they can't afford transport to work, often skip meals, and moonlight at whatever jobs exist just to survive.

Infrastructure is collapsing. Schools operate without electricity, forcing students and teachers to work in darkness or abandon evening sessions. Running water is sporadic or absent, toilets don't function, and buildings are decaying without maintenance. Textbooks haven't been printed in years, and students learn by copying from blackboards when chalk exists. Science labs are empty, libraries are closed, and technology is non-existent. Rural schools fare even worse: many simply closed because teachers left and nobody replaced them. Urban schools in Caracas operate semi-functionally if teachers show up; rural schools across Barinas, Apure, or Zulia are abandoned shells.

Learning outcomes are impossible to measure because the assessment systems collapsed along with everything else. Venezuela stopped participating in international assessments years ago. National exams became meaningless because standards were lowered to the point where failure was nearly impossible—the government wanted passing rates to suggest normalcy. But anecdotal evidence and studies by Venezuelan universities paint a dire picture: most students finishing secondary school can barely read with comprehension, can't solve basic math, and lack foundational knowledge in any subject. Years in school don't translate to education because schools no longer function. Students attend when teachers appear, copy whatever is written, and receive diplomas signifying nothing.

Higher education mirrors the school crisis. Universidad Central de Venezuela, Universidad de Los Andes, and other once-prestigious institutions operate with electricity outages, broken infrastructure, and faculties decimated by emigration. Professors who remain are paid the same poverty wages as schoolteachers, research is impossible, libraries haven't acquired books in years, and students skip classes to work or because transport is unaffordable. Many students who can leave do—enrolling abroad or emigrating and finishing degrees elsewhere. Those who stay receive degrees increasingly meaningless because academic standards collapsed along with institutional capacity.

The Maduro regime treats education as a political tool rather than a public service. Curriculum includes obligatory Bolivarian ideology, loyalty to the regime is rewarded with access to scholarships or food programs, and teachers suspected of dissent face harassment or dismissal. The government announces education "missions" and "plans" with revolutionary names but zero implementation or funding. Education spending as a share of GDP collapsed, real resources disappeared, and the sector was abandoned. When teachers protested poverty wages, the government responded with repression rather than raises. International organizations provide some humanitarian education support, especially for displaced populations, but coverage is minimal compared to the scale of need.

Venezuela's education collapse is reversible only with economic recovery, political change, and sustained investment—none imminent. Even if conditions improve tomorrow, rebuilding takes decades. An entire generation has missed years of schooling or attended schools that taught nothing. Teachers who emigrated won't return quickly to a country still offering poverty wages. The infrastructure requires billions in reconstruction. Venezuela's education system was built over decades and destroyed in one, and the consequences will haunt the country for generations. Right now, Venezuelan children and youth are growing up without education, without skills, and without prospects, ensuring poverty and dysfunction long after Maduro is gone. That's not an education crisis—it's a humanitarian catastrophe with generational consequences.`

// ECUADOR EDUCATION
const ECUADOR_EDUCATION = `Ecuador's literacy rate reached 94.48% in 2021, and enrollment in primary and secondary schools is near universal—genuine achievements for a middle-income country. But here's what the averages hide: 71.2% of Ecuadorian adults have no more than basic reading skills, meaning they can decode text but not comprehend complex information or think critically. Nearly a third of children and teenagers suffer violent treatment or disciplinary punishments at school, and only 24% of students report feeling completely happy. Ecuador will participate in PISA 2025, its first regular PISA cycle after completing PISA-D in 2018, and the results (published in 2026) will reveal whether recent reforms improved learning or merely expanded access without quality. The education system's current challenge is violence: Ecuador's explosion of organized crime and gang warfare since 2021 is affecting schools, with research showing violence significantly influences learning outcomes. Ecuador built a system delivering access; now it must deliver safety and actual education.

The structure is centralized through the Ministry of Education, which sets national standards, manages curriculum, and distributes resources, but implementation depends on provincial and local capacity that varies wildly. Coastal urban areas like Guayaquil and highland cities like Quito operate functional school systems with qualified teachers and adequate infrastructure. Rural areas and indigenous communities face chronic underfunding, teacher shortages, and resource gaps. The indigenous population and Afro-Ecuadorians have dramatically higher illiteracy rates than mestizos, reflecting structural discrimination and disconnection between national curriculum and indigenous languages and cultures. The education system is bilingual in theory—Spanish and indigenous languages—but Spanish dominates, creating barriers for indigenous students.

Teacher quality improved modestly after 2000s reforms that increased training requirements, improved salaries, and strengthened professional development. But challenges persist: urban schools attract qualified teachers, rural schools get whoever will accept remote postings, and ongoing curriculum reforms require pedagogical changes many teachers struggle to implement. The current reform toward competency-based education emphasizes critical thinking and problem-solving over memorization—the right direction—but teacher training hasn't fully caught up. Salaries are adequate compared to regional peers but insufficient to attract top talent. Class sizes in urban schools are large, rural schools often have one teacher covering all grades, and professional development is inconsistent.

Infrastructure is adequate in urban areas—schools have buildings, furniture, electricity, water, and textbooks—but rural areas face deficits. Remote schools operate with minimal resources, aging buildings, and limited materials. Science education suffers everywhere because labs are scarce and practical work minimal. The digital divide is stark: urban middle-class students have internet and devices, rural and poor students have neither. The government invested in technology during the 2010s commodities boom, but maintenance lagged and much equipment is now obsolete or broken.

Learning outcomes are uneven. National assessments ("Ser Estudiante") show urban students performing reasonably in basic literacy and numeracy, but rural and indigenous students lag significantly. Comprehension and critical thinking are weak across demographics—students can decode and recite but struggle with understanding and application. The violence crisis compounds learning challenges: students experiencing or witnessing violence perform worse in all domains, and violence in Ecuador has exploded. Schools have become sites of gang recruitment, extortion, and violence, creating fear and trauma that make learning nearly impossible. Teachers report feeling unsafe, students are stressed and unhappy, and attendance suffers in conflict-affected areas.

Higher education expanded dramatically—enrollment rates climbed from 20% to over 50% in two decades—but quality is uneven. The government's 2008 higher education reforms closed low-quality universities and strengthened accreditation, improving standards. Public universities are tuition-free, which expanded access for poor and middle-class students, but overcrowding and resource constraints limit quality. Private universities vary from excellent to diploma mills. The 2023 reform decentralized admissions to individual universities, increasing flexibility but potentially reintroducing inequities the centralized system tried to address. Graduate unemployment is rising as credential inflation outpaces labor market needs.

What Ecuador needs now is addressing the violence crisis that's undermining schools, completing the competency-based curriculum reform with genuine teacher retraining, closing the rural-urban resource gaps, and ensuring indigenous students receive education in their languages with culturally relevant content. The ongoing reforms are promising on paper but implementation is always the challenge. Ecuador's "pivot to learning" in the 2010s improved enrollment and basic quality, but sustaining gains requires political will, continued investment, and security. The PISA 2025 results will be the first rigorous international benchmark since PISA-D in 2018. They'll likely show Ecuador performing below OECD averages but above some Latin American peers, with massive internal inequalities between urban and rural, wealthy and poor, mestizo and indigenous students. Ecuador is building an education system that could work if it addresses violence, inequality, and the gap between policies and classroom practice. Right now, it's halfway there—better than some neighbors, far from where it needs to be.`

// BOLIVIA EDUCATION
const BOLIVIA_EDUCATION = `Bolivia's literacy rate is officially 94%, which sounds respectable until you see that 70% of third-graders and 80% of sixth-graders can't interpret or reflect on written texts. They can decode letters but not comprehend meaning—functional illiteracy masquerading as literacy. The rural-urban divide is brutal: urban areas approach genuine literacy, rural areas remain deeply illiterate despite official statistics. Indigenous communities—Quechua and Aymara-speaking populations who constitute the majority—face the worst conditions: instruction in Spanish they don't speak, curriculum disconnected from their cultures, and schools without resources or qualified teachers. Bolivia's education system is failing the majority of its population, especially indigenous children who need education most. Access has expanded—enrollment rates are high—but learning outcomes are catastrophic. Bolivia built schools but didn't build education.

The structural problem is that education policy was designed by and for urban Spanish-speaking elites, and extending it to indigenous rural communities was an afterthought. The Ministry of Education sets national standards, but implementation depends on departmental and municipal capacity that barely exists in rural areas. The 2010 Avelino Siñani-Elizardo Pérez Law promised intercultural bilingual education, community participation, and decolonization of curriculum. The vision was radical and necessary: education respecting indigenous languages, knowledge systems, and governance. The implementation was disastrous: chronic underfunding, resistance from bureaucracy, lack of materials in indigenous languages, and insufficient teacher training. Bilingual education exists on paper but barely in practice. Most indigenous students still learn in Spanish, struggle from day one, and fail predictably.

Teacher quality is the central crisis. Urban schools attract university-educated teachers with professional certification; rural schools get locals with minimal training because nobody else will accept isolated postings with poverty wages and no infrastructure. The linguistic barrier is catastrophic: many rural teachers don't speak indigenous languages fluently, and most indigenous students don't speak Spanish fluently, so instruction happens across a language gap ensuring misunderstanding. Professional development barely exists in rural areas—teachers are trained once briefly and then abandoned. Teaching methods emphasize rote memorization because teachers don't know alternatives and because thinking skills require resources and training absent in Bolivia. Salaries are low enough that teachers need second incomes, morale is terrible, and turnover is high. The best teachers stay in cities; the weakest work in rural areas where students need the most help.

Infrastructure is grossly inadequate, especially in rural areas. Schools operate in aging buildings without maintenance, electricity, running water, or toilets. Students sit on broken furniture or floors, share textbooks at ratios exceeding 5:1, and learn without materials. Science education is entirely theoretical because labs don't exist. A 2025 study on Quechua and Aymara textbooks in the Kallawaya region found that even when bilingual materials exist, they're scarce, arrive late, and teachers lack training to use them effectively. Another 2025 study found infrastructure significantly affects educational outcomes—schools without basic facilities produce dramatically worse learning. Bolivia hasn't built the infrastructure necessary for education.

Learning outcomes are dismal. National assessments show most students completing primary school can't read with comprehension, can't solve basic math problems, and lack foundational knowledge in any subject. The rural-urban gap is vast: urban students perform marginally below regional peers, rural students score catastrophically low. Indigenous students face the worst outcomes—discrimination, linguistic barriers, curriculum disconnection, and resource deprivation combine to ensure failure. Dropout rates are high, especially in rural areas where families need children for labor and see no value in education that doesn't lead to opportunities. Cultural norms and economic necessity pressure students to leave school early, especially girls who face additional barriers from traditional gender roles and early marriage.

Higher education expanded access but not quality. Public universities like Universidad Mayor de San Andrés serve urban students, mostly mestizo, with uneven academic standards. Rural and indigenous students rarely reach university—they've been filtered out by the system long before. Private universities of varying quality serve middle-class students. Overall, higher education is disconnected from labor market needs, producing graduates who can't find work matching their credentials while employers can't find workers with needed skills.

What Bolivia needs is implementing the bilingual intercultural education the 2010 law promised but didn't deliver. That means training thousands of teachers fluent in indigenous languages and pedagogies, producing textbooks and materials in Quechua and Aymara, building infrastructure in rural schools, and reforming curriculum around competencies rather than Spanish-language memorization. It means addressing the structural inequalities and ethnic discrimination that ensure indigenous students fail. Bolivia's Morales government (2006-2019) made education reform central to its indigenous empowerment agenda, but implementation stumbled on capacity constraints, bureaucratic resistance, and insufficient funding. The post-Morales governments have been politically unstable, and education has been invisible in their agendas. Meanwhile, Bolivian children—especially indigenous rural children—attend schools that teach them they're failures because the system was never designed for their success. Bolivia's 94% literacy rate is a statistical fiction. The reality is functional illiteracy, especially in rural indigenous communities, and an education system that reproduces ethnic and class inequality rather than disrupting it.`

// PARAGUAY EDUCATION
const PARAGUAY_EDUCATION = `Paraguay's literacy rate is around 94%, and enrollment in primary and secondary schools reaches respectable levels—84% and 65% respectively. But the statistics mask Paraguay's defining education challenge: it's a bilingual country where 90% of rural children enter school speaking only Guaraní, yet instruction happens primarily in Spanish, creating a linguistic barrier guaranteeing failure for most students. The PISA test—Paraguay participated in PISA for Development and is joining PISA 2025—is administered solely in Spanish, meaning it assesses not just student knowledge but language proficiency, with predictable results: students who speak Spanish at home perform dramatically better than students who speak Guaraní. Paraguay's education system is failing the majority of its population not because schools don't exist but because instruction happens in a language most students don't speak. This is education policy as cultural imperialism, and it ensures rural, indigenous, and poor students learn almost nothing.

The structural problem is historical and cultural. Paraguay is unique in Latin America: Guaraní is spoken by the majority, including many mestizo and white citizens, not just indigenous communities. It's an official language alongside Spanish, embedded in daily life, music, and identity. Yet the education system treats Guaraní as inferior—a language to be overcome rather than celebrated. The Ministry of Education mandates bilingual education in theory, but implementation is weak and inconsistent. Urban schools in Asunción emphasize Spanish because urban middle-class families see Spanish as the language of economic opportunity. Rural schools are supposed to teach in Guaraní in early grades, transitioning to Spanish, but most teachers lack training in bilingual pedagogy, materials in Guaraní are scarce, and the curriculum is designed for Spanish-speakers. The result: rural students taught in a language they don't understand, guaranteeing they fall behind from day one and never catch up.

Teacher quality varies wildly by location and linguistic capacity. Urban schools attract university-educated teachers with professional certification; rural schools get whoever will accept remote postings, often with minimal training and sometimes limited Guaraní fluency themselves. Professional development in bilingual pedagogy is minimal, supervision weak, and support non-existent. Salaries are low enough that teachers need second jobs, morale is poor, and turnover is high. Teaching methods emphasize rote memorization—students recite Spanish vocabulary they don't understand, copy from blackboards in a language that's foreign to them, and take exams measuring recall rather than comprehension. Critical thinking requires understanding, which requires instruction in a language students speak, which Paraguay's system doesn't provide.

Infrastructure is adequate in urban areas but deficient in rural areas. Rural schools operate with minimal resources—aging buildings, insufficient furniture, scarce textbooks (mostly in Spanish), and no technology. The digital divide is stark: urban middle-class students have internet and devices, rural students have neither. Science education is theoretical everywhere because labs are scarce. Textbook ratios in rural areas reach 5:1 or worse, meaning students spend lessons copying notes rather than reading.

Learning outcomes are predictably dismal for Guaraní-dominant students. National assessments show urban Spanish-speaking students performing marginally below regional peers, while rural Guaraní-speaking students score catastrophically low. The language barrier explains much of the gap, but the education system blames students rather than its own policies. Dropout rates are high in rural areas because students and families see no value in education that doesn't teach in their language or lead to opportunities. Cultural norms and economic necessity pressure students, especially girls, to leave school for household labor or early marriage.

Higher education is concentrated in Asunción, accessible mainly to urban Spanish-speaking students who survived the academic obstacle course. Universities like Universidad Nacional de Asunción operate with limited resources, overcrowded facilities, and uneven quality. Instruction is entirely in Spanish, ensuring rural Guaraní-speaking students rarely reach university. Those who do struggle with academic Spanish after years of inadequate preparation. Graduate unemployment is rising as credential inflation outpaces economic growth, and degrees don't signal competence.

The school year runs February to November—181 days of instruction in 2025—which is standard regionally but insufficient given the learning deficits most students face. More time in schools teaching in the wrong language doesn't solve the problem.

What Paraguay needs is genuine bilingual education: Guaraní-dominant instruction in early grades with gradual Spanish introduction, teachers trained in bilingual pedagogy and fluent in both languages, curriculum and materials in Guaraní, and cultural shift recognizing Guaraní as equal to Spanish rather than inferior. This isn't mysterious pedagogy—it's basic linguistics. Children learn best in their mother tongue, and research globally shows bilingual education outperforms monolingual instruction in second languages. Paraguay knows this—the policy documents say the right things—but implementation fails because of linguistic prejudice, insufficient investment, and urban elites who see Spanish-only education as normal. The result is an education system that fails the majority of Paraguayan children because it refuses to teach them in the language they speak. Paraguay's 94% literacy rate is fiction. The reality is many Paraguayans can decode Spanish but not comprehend it, speak Guaraní fluently but can't read it, and received years of schooling that taught them their language and culture are inferior. That's not education—it's linguistic and cultural colonialism dressed as policy.`

// URUGUAY EDUCATION
const URUGUAY_EDUCATION = `Uruguay and Chile trade places as Latin America's top performers in PISA, and in 2022 Uruguay scored 409 in mathematics, 430 in reading, and 435 in science—below OECD averages but above regional peers. Uruguay's literacy rate is around 98.5%, enrollment is near universal, and the education system is equitably funded and relatively high-quality by Latin American standards. Public education is free from preschool through university, teacher salaries are competitive regionally, and infrastructure is decent. Uruguay's education success reflects its broader social democratic model: relatively equitable, well-governed, and committed to public goods. But "best in Latin America" doesn't mean good in absolute terms. Uruguay's PISA scores have stagnated or declined slightly over the past decade, learning outcomes reveal gaps between credentials and competence, and secondary completion rates lag despite universal access. Uruguay succeeded at building an education system that works reasonably well for most students, which is genuinely impressive regionally. Now it faces the harder challenge: improving quality, closing remaining gaps, and preparing students for economies requiring skills the system doesn't emphasize.

The structure is centralized and public. The National Administration of Public Education (ANEP) manages primary, secondary, and technical education, with uniform standards, curriculum, and teacher training. Funding comes primarily from national government, distributed equitably, so resource gaps between schools are smaller than in most countries. Private schools exist but serve minorities; most Uruguayan students attend public schools, including middle-class and wealthy families who in other Latin American countries flee to private systems. This matters enormously: when elites use public schools, they demand quality and fund adequately, preventing the public system abandonment that destroyed education elsewhere in the region. Teacher training is standardized, salaries are decent (though teachers still protest for better pay), and professional development exists though it's inconsistent.

Infrastructure is solid: schools have buildings, furniture, textbooks, electricity, water, and toilets—basics that sound trivial but are absent in many regional peers. The government invested in technology under the Plan Ceibal, providing laptops to all students—one of the world's most ambitious one-to-one computing programs. It improved access but didn't transform pedagogy as hoped; having laptops matters less than what students do with them, and many teachers lacked training to integrate technology meaningfully. Still, Uruguay's digital infrastructure is among the region's best, and the pandemic-era shift to remote learning was less catastrophic than in countries without devices or connectivity.

Learning outcomes are decent but not excellent. Uruguay's PISA scores are respectable regionally but below countries with similar income levels. The scores have stagnated since 2009, suggesting the system isn't improving. National assessments show most students achieve basic literacy and numeracy, but higher-order skills—comprehension, critical thinking, problem-solving—are weaker. Mathematics education particularly struggles: only 42% of students reach Level 2 proficiency in PISA, meaning 58% can't solve basic problems. Science performance is similar. Reading is marginally better at 430, but this still means many students complete school able to decode text without deep comprehension.

Inequality exists but is less extreme than in most peer countries. Uruguay's education system is more equitable than Brazil, Chile, or Peru, but socioeconomic status still predicts outcomes. Students from wealthier families attend better-resourced schools in Montevideo, while students from poor families attend under-resourced schools in rural areas or urban peripheries. Indigenous and Afro-Uruguayan students face additional barriers from discrimination and cultural disconnection. Rural schools are often small, with one teacher covering multiple grades, limited materials, and geographic isolation. But the gaps are smaller than elsewhere, and most students receive minimally adequate education.

Secondary education is the weakest link. Enrollment is high—around 80%—but completion rates are only 65%, meaning many students start secondary school and drop out before finishing. The curriculum is academic and rigid, designed for university preparation, leaving students uninterested in university with no clear pathway. Technical and vocational education exists but is underdeveloped and stigmatized. Students who struggle academically have few alternatives, contributing to dropout. Those who complete secondary often arrive at university underprepared because secondary education didn't develop strong literacy, numeracy, or thinking skills.

Higher education is free at public universities, which expanded access dramatically but created overcrowding and resource constraints. The University of the Republic operates with large classes, limited facilities, and variable quality. Many students start university and drop out because they're academically unprepared or because the programs don't match labor market needs. Graduate unemployment is rising as credential inflation outpaces economic growth. Employers complain university graduates lack critical thinking, problem-solving, and technical skills, suggesting the entire education pipeline—primary through tertiary—emphasizes credentialing over competence.

What Uruguay needs is secondary reform that diversifies pathways, develops technical education, and emphasizes competencies over content coverage. It needs curriculum reform across all levels emphasizing critical thinking, problem-solving, and application over memorization. Teacher professional development must shift toward active learning pedagogies. And Uruguay must sustain investment in equity, ensuring rural and marginalized students get resources needed to succeed. Uruguay has the governance capacity, political will, and social cohesion to implement these reforms—unlike many neighbors. The question is whether it will. Current trajectories suggest stagnation: the system works well enough that urgency is low, but mediocrity is becoming normalized. Uruguay is Latin America's education success story, which reveals how low the regional bar is. The next PISA results in 2026 will show whether Uruguay can shift from "best in region" to "genuinely good by global standards." Based on current evidence, expect continued stagnation, continued inequality (though less than neighbors), and continued acceptance that "better than Brazil" equals success.`

const COUNTRIES = [
  {
    name: 'United States',
    lat: 37.0902,
    lng: -95.7129,
    summary: USA_EDUCATION,
    chars: USA_EDUCATION.length
  },
  {
    name: 'Canada',
    lat: 56.1304,
    lng: -106.3468,
    summary: CANADA_EDUCATION,
    chars: CANADA_EDUCATION.length
  },
  {
    name: 'Mexico',
    lat: 23.6345,
    lng: -102.5528,
    summary: MEXICO_EDUCATION,
    chars: MEXICO_EDUCATION.length
  },
  {
    name: 'Brazil',
    lat: -14.2350,
    lng: -51.9253,
    summary: BRAZIL_EDUCATION,
    chars: BRAZIL_EDUCATION.length
  },
  {
    name: 'Argentina',
    lat: -38.4161,
    lng: -63.6167,
    summary: ARGENTINA_EDUCATION,
    chars: ARGENTINA_EDUCATION.length
  },
  {
    name: 'Chile',
    lat: -35.6751,
    lng: -71.5430,
    summary: CHILE_EDUCATION,
    chars: CHILE_EDUCATION.length
  },
  {
    name: 'Colombia',
    lat: 4.5709,
    lng: -74.2973,
    summary: COLOMBIA_EDUCATION,
    chars: COLOMBIA_EDUCATION.length
  },
  {
    name: 'Peru',
    lat: -9.1900,
    lng: -75.0152,
    summary: PERU_EDUCATION,
    chars: PERU_EDUCATION.length
  },
  {
    name: 'Venezuela',
    lat: 6.4238,
    lng: -66.5897,
    summary: VENEZUELA_EDUCATION,
    chars: VENEZUELA_EDUCATION.length
  },
  {
    name: 'Ecuador',
    lat: -1.8312,
    lng: -78.1834,
    summary: ECUADOR_EDUCATION,
    chars: ECUADOR_EDUCATION.length
  },
  {
    name: 'Bolivia',
    lat: -16.2902,
    lng: -63.5887,
    summary: BOLIVIA_EDUCATION,
    chars: BOLIVIA_EDUCATION.length
  },
  {
    name: 'Paraguay',
    lat: -23.4425,
    lng: -58.4438,
    summary: PARAGUAY_EDUCATION,
    chars: PARAGUAY_EDUCATION.length
  },
  {
    name: 'Uruguay',
    lat: -32.5228,
    lng: -55.7658,
    summary: URUGUAY_EDUCATION,
    chars: URUGUAY_EDUCATION.length
  }
]

async function addEducationSummaries() {
  console.log('Adding education summaries for 13 Americas countries (Batch 1)...\n')

  for (const country of COUNTRIES) {
    try {
      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: country.name,
            type: 'country',
            category: 'education'
          }
        },
        create: {
          name: country.name,
          type: 'country',
          country: country.name,
          lat: country.lat,
          lng: country.lng,
          category: 'education',
          summary: country.summary,
          issues: JSON.stringify([]),
          topStories: JSON.stringify([]),
          storyCount: 0,
          updatedAt: new Date()
        },
        update: {
          summary: country.summary,
          updatedAt: new Date()
        }
      })
      console.log(`✅ ${country.name} education summary saved (${country.chars} characters)`)
    } catch (error) {
      console.error(`❌ Error saving ${country.name}:`, error)
    }
  }

  console.log('\n✅ ALL 13 EDUCATION SUMMARIES COMPLETED!')
  console.log('\n📊 CHARACTER COUNTS:')
  COUNTRIES.forEach(c => {
    console.log(`   ${c.name}: ${c.chars} characters`)
  })
  console.log(`\n🎉 BATCH 1 COMPLETE - AMERICAS EDUCATION SUMMARIES`)
}

addEducationSummaries()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
