import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const COUNTRIES_ECONOMY = [
  {
    name: 'Qatar',
    lat: 25.3548,
    lng: 51.1839,
    summary: `Qatar's $237 billion economy is one of the world's most unusual: a city-state of 2.7 million people (only 10% citizens, 90% foreign workers) with the third-highest GDP per capita globally ($87,800), entirely dependent on a single commodity—liquefied natural gas (LNG). In November 2025, Qatar is navigating the complexities of being the world's largest LNG exporter (77 million tons annually, 25% of global supply) while facing unprecedented competitive pressure. The North Field expansion—$30 billion invested to increase LNG capacity to 126 million tons by 2027—is the largest energy project on earth, but the U.S. shale gas boom and new suppliers (Mozambique, Mauritania, Senegal) are challenging Qatar's market dominance. Natural gas and oil account for 85% of export revenues and 60% of government income, making the state's finances acutely sensitive to energy prices. Brent crude averaged $82 per barrel in 2024; gas prices fluctuated between $10-$14 per mmBtu—profitable, but down from the 2022 spike ($50+ per mmBtu) driven by Russia's invasion of Ukraine. The 2022 FIFA World Cup was Qatar's coming-out party: $300 billion spent on infrastructure (stadiums, metro, highways, hotels), but post-tournament, the economy is searching for a new growth driver. Non-oil GDP grew 4.2% in 2024, driven by tourism, finance, and logistics, but overall GDP contracted 1.3% due to oil production cuts under OPEC+ agreements. Inflation is low (2.8%), unemployment negligible (0.3% for citizens, though migrant workers face precarious conditions), and the fiscal surplus is projected at 5% of GDP for 2025. Qatar's sovereign wealth fund, the Qatar Investment Authority (QIA), manages $475 billion in assets—the world's ninth-largest—investing globally in real estate, tech, and finance. But the rentier state model has limits: how do you diversify an economy when 90% of the workforce is foreign, citizens expect cradle-to-grave welfare, and energy rents fund everything?

Qatar's economy is a textbook rentier state: hydrocarbon revenues finance public spending, citizens receive generous subsidies (free healthcare, education, energy, housing grants), and the private sector is dominated by state-owned enterprises and royal family holdings. Qatar Energy (formerly Qatar Petroleum) is the cornerstone—100% state-owned, it controls all oil and gas production, refining, and export. The North Field, the world's largest non-associated natural gas field (shared with Iran, which calls its side South Pars), contains 25 trillion cubic meters of gas—enough to sustain current production for 138 years. The North Field expansion, launching in phases through 2027, will cement Qatar's LNG dominance, but the capital intensity is staggering: $30 billion for liquefaction facilities, pipelines, and export terminals. Qatar's LNG is competitively priced (production costs are $3-$5 per mmBtu), but the market is shifting—Asian buyers (Japan, South Korea, China) are diversifying suppliers, Europe is building regasification terminals to reduce Russian dependence, and U.S. producers are flooding the market. The 2024 oil price average ($82/barrel) was healthy, but OPEC+ production cuts (Qatar participates) limited revenue growth. The government's fiscal policy is conservative: public debt is 42% of GDP (low by global standards), the budget surplus is structural, and the QIA's returns (6-8% annually) provide a buffer. But the state faces fiscal pressures: the World Cup infrastructure binge left underutilized assets (stadiums rarely filled, luxury hotels competing for tourists), and citizen expectations for public sector jobs and subsidies are rising. The private sector is anemic—dominated by construction, retail, and services catering to expatriates—and economic diversification beyond oil remains aspirational. Qatar National Vision 2030 (the government's development plan) targets a "knowledge-based economy," but progress is slow: non-oil sectors contributed 46% of GDP in 2024, up from 42% in 2020, but much of that is government-funded (education, healthcare) or expatriate-driven (services, logistics).

The economic model's biggest vulnerability is the labor force structure: 90% of residents are foreign workers (mostly South Asian), employed under the kafala system—a sponsorship framework that ties visas to employers, creating conditions ripe for exploitation. After international pressure (FIFA World Cup scrutiny, ILO complaints), Qatar reformed kafala in 2020—workers can now change jobs without employer permission, minimum wages were introduced ($275/month), and labor courts adjudicate disputes. But enforcement is patchy: construction workers still face wage theft, unsafe conditions, and passport confiscation. The World Cup exposed this: 6,500 migrant workers died between 2010-2020 on infrastructure projects (Qatar disputes the figure, saying many deaths were unrelated to work, but international monitors disagree). The economic contradiction is stark—Qatar needs foreign workers to build and operate the economy, but citizens view them as temporary labor, not residents. Qatari citizens make up 10% of the population, and they're sheltered from economic volatility: public sector employment (65% of citizens work for the government), generous salaries (average $7,000/month), subsidized utilities, and guaranteed housing. Youth unemployment among citizens is effectively zero (the state creates jobs), but this creates a bloated bureaucracy and entitlement culture. Economic diversification requires private sector growth, but Qatari youth prefer government jobs (stable, high-paying, minimal effort), and the private sector relies on cheap foreign labor. The tourism sector, a post-World Cup hope, is struggling: 4 million visitors in 2024 (up from 2.1 million in 2019), but occupancy rates are below projections, and Qatar competes with Dubai, Abu Dhabi, and Saudi Arabia (whose Vision 2033 is pouring $500 billion into tourism). Qatar's airline, Qatar Airways, is a global leader (voted world's best airline in 2024), and Hamad International Airport handled 44 million passengers in 2024, but the aviation sector's contribution to GDP is modest (3%). Financial services is another diversification bet—Qatar Financial Centre (QFC) hosts 1,000 firms, including asset managers, fintech, and insurers—but the sector is dwarfed by Dubai and Singapore.

The geopolitical dimension matters: Qatar's wealth enables outsized influence—hosting the Taliban (U.S. negotiations in 2020), mediating Yemen's civil war, funding Al Jazeera (the region's most influential media outlet), and maintaining ties with Iran (the North Field requires cooperation). The 2017-2021 blockade (Saudi Arabia, UAE, Bahrain, and Egypt isolated Qatar for alleged terrorism support) tested the economy—trade routes shifted to Turkey and Iran, food imports diversified, and Qatar proved resilient. But relations are now normalized, and Qatar is rebuilding Gulf ties. The U.S. relationship is strategic: Al Udeid Air Base hosts 10,000 American troops (the largest U.S. base in the Middle East), and Qatar is designated a major non-NATO ally. Energy security partnerships with Europe (post-Ukraine war, EU needs non-Russian gas) have deepened—Qatar signed 27-year LNG deals with Germany, Italy, and the Netherlands, guaranteeing demand through 2050. But China is also a major buyer (35% of Qatar's LNG exports), and Qatar must balance U.S. security ties with Chinese economic ties. The QIA's global investments ($475 billion) are concentrated in real estate (London, Paris, New York), sports (PSG football club, stakes in F1), tech (Uber, Airbnb), and finance—this diversifies revenue streams but also exposes Qatar to Western asset freezes if geopolitics sour. Looking ahead, the North Field expansion will keep Qatar competitive through 2030, but long-term risks loom: the energy transition (declining LNG demand as renewables scale), domestic consumption growth (Qatar uses more gas domestically, reducing exports), and succession politics (Emir Tamim bin Hamad, 44, is secure, but future transitions could destabilize).

**Bottom line:** Qatar's economy is an oil and gas machine wrapped in a welfare state. The North Field expansion guarantees LNG dominance through 2030, the sovereign wealth fund is enormous, and fiscal surpluses are structural. But the rentier model is fragile—90% foreign labor, bloated public sector, minimal private sector dynamism, and total dependence on hydrocarbons. Diversification is a slogan, not a strategy. As long as gas prices stay above $10 per mmBtu and Asian demand holds, Qatar thrives. But the energy transition, competitive pressures, and demographic imbalances are long-term time bombs. For now, though, this tiny emirate punches well above its weight.`,
    issues: ['World\'s largest LNG exporter facing new competition', 'North Field expansion ($30B) to increase capacity 63%', 'Rentier state model with 90% foreign workforce', 'Post-World Cup economic slowdown', 'Economic diversification remains aspirational', 'Sovereign wealth fund manages $475 billion']
  },
  {
    name: 'Romania',
    lat: 45.9432,
    lng: 24.9668,
    summary: `Romania's $351 billion economy is the EU's sleeper success story—GDP per capita has tripled since joining the bloc in 2007 ($18,500 in 2024), annual growth averaged 4.1% over the past decade, and Bucharest has transformed from post-communist backwater to Central Europe's tech and automotive hub. In November 2025, Romania is at an economic inflection point: twin deficits (fiscal deficit 6.2% of GDP, current account deficit 7.4%) are triggering EU excessive deficit procedures, inflation is stubbornly high (5.8%), and elections in December 2025 will determine whether the country continues pro-EU reforms or lurches toward nationalist populism. The economy's strengths are real—IT services exports ($8 billion annually), automotive production (550,000 vehicles in 2024 from Dacia, Ford, and suppliers), agriculture (Europe's breadbasket for wheat, corn, sunflower), and remittances from the 4 million Romanians working abroad ($6 billion in 2024). But structural weaknesses are glaring: chronic underinvestment in infrastructure (roads, railways, hospitals), a massive informal economy (25% of GDP, highest in the EU), endemic corruption (Transparency International ranks Romania 63rd globally), and a shrinking population (19 million in 2024, down from 23 million in 1990). The leu has been stable against the euro (averaging 4.95 in 2024), but eurozone entry—originally targeted for 2029—is now postponed indefinitely due to fiscal slippage. Romania's absorption of EU structural funds is improving (65% utilization rate in 2021-2027 budget cycle, up from 45% previously), and Brussels has allocated €79 billion for infrastructure, green transition, and digital projects. But the government's inability to control spending—bloated public sector wages, untargeted subsidies, and infrastructure white elephants—means Romania risks losing access to these funds if it doesn't meet fiscal consolidation targets by 2026. The private sector is dynamic (services and industry each account for 35% of GDP), but Romania remains one of the EU's poorest members (GDP per capita is 76% of the EU average), and the gap isn't closing fast enough.

The Romanian economy's transformation since 1989 is remarkable: from centrally planned Stalinist ruin to market economy, from agrarian backwater to industrial exporter, from Soviet satellite to EU member. But the transition has been uneven. Bucharest, Cluj-Napoca, Timișoara, and Brașov are booming—tech startups, foreign investment, modern infrastructure, rising living standards. But rural Romania (40% of the population) remains stuck: subsistence farming, poverty (23% live below the poverty line nationally, 40% in rural areas), and underdeveloped infrastructure. The automotive sector is Romania's industrial backbone—Dacia (owned by Renault) produced 350,000 cars in 2024 at its Mioveni plant, Ford's Craiova factory made 200,000 commercial vehicles, and 400+ suppliers employ 230,000 workers. Romania is Europe's ninth-largest auto producer, and the sector accounts for 12% of exports. IT services are the glamour sector—Romania is "Europe's Silicon Valley": UiPath (robotic process automation, valued at $10 billion) is Romanian, Bucharest hosts R&D centers for Amazon, Microsoft, Oracle, and IBM, and 150,000 software engineers earn above-average salaries ($30,000-$50,000 annually). Agriculture is a mixed story—Romania has Europe's largest arable land per capita (14 million hectares), produces 30 million tons of grain annually (wheat, corn, sunflower), and is a top exporter to North Africa and the Middle East. But productivity is low (small plots, outdated machinery, lack of irrigation), and farmers are aging (average age 57). Energy is another strength—Romania is 75% energy independent (the EU average is 40%), producing oil, natural gas, coal, hydro, and renewables. The Neptun Deep offshore gas field (Black Sea) is set to begin production in 2027, adding 100 billion cubic meters of reserves and potentially making Romania a net gas exporter.

The fiscal crisis is the immediate challenge: Romania's budget deficit hit 6.2% of GDP in 2024, well above the EU's 3% Maastricht limit, and the European Commission has launched an excessive deficit procedure—requiring Romania to bring the deficit below 3% by 2026 or face sanctions (loss of EU funds, restrictions on borrowing). The problem is political: successive governments have increased public sector wages (average $1,100/month), expanded social benefits (pensions, child allowances), and subsidized energy costs (capping electricity and gas prices during the 2022-2024 energy crisis), all while under-collecting taxes. Romania's tax-to-GDP ratio is 28% (EU average is 42%)—the informal economy is vast, tax evasion is rampant (especially VAT fraud in construction and agriculture), and the tax authority (ANAF) is underfunded and inefficient. The current account deficit (7.4% of GDP) is driven by high imports (consumer goods, energy, machinery) and relatively low exports (automotive and IT are strong, but not enough to offset). The leu is stable because the National Bank of Romania (NBR) manages the exchange rate tightly (controlled float), but reserves ($60 billion) are finite, and if foreign investor confidence wanes, the leu could weaken. Inflation spiked to 16% in 2022 (energy and food prices), fell to 5.8% in 2024, but remains above the NBR's 2.5% target. Interest rates are 6.5% (the NBR has held steady since mid-2023), but real rates are barely positive. The December 2025 elections (parliamentary and presidential) will determine fiscal policy: the Social Democratic Party (PSD) and National Liberal Party (PNL) have governed in coalition since 2021, but both are populist-leaning—they've resisted austerity and promised more spending. The far-right Alliance for the Union of Romanians (AUR) is polling at 20%, campaigning on nationalist themes (anti-EU, anti-immigration, anti-LGBTQ), and could force a fiscal reckoning if they enter government.

Looking ahead, Romania's growth potential is real—demographics are deteriorating (population shrinking 0.5% annually due to low birth rates and emigration), but EU funds, nearshoring trends (Western firms relocating from China), and energy independence offer tailwinds. The Neptun Deep gas project (operated by OMV Petrom and Romgaz) will generate $5 billion in investment and boost export revenues. Infrastructure investment is critical—Romania has Europe's worst road network (only 921 km of highways, compared to Poland's 4,800 km), and rail is underdeveloped. The government is building three major highway corridors (linking Bucharest to the Hungarian, Bulgarian, and Moldovan borders), financed by EU funds, but construction is slow (corruption, bureaucratic delays). Digitalization is progressing—Romania has Europe's fastest internet speeds (300 Mbps average), and e-government services are expanding (tax filing, business registration, healthcare). But institutional quality lags—the judiciary is politicized, corruption convictions are rare (despite anti-corruption agency DNA's high-profile cases), and rule of law concerns persist. The brain drain is the biggest long-term threat—500,000 Romanians left between 2020-2024 (mostly young, educated), and while remittances boost GDP, the loss of human capital undermines growth. Romania's eurozone entry, postponed indefinitely, would anchor the leu, lower borrowing costs, and attract more investment—but fiscal consolidation is a prerequisite, and current politics make that unlikely before 2027. Relations with the EU are stable but tense—Brussels is frustrated by Romania's fiscal profligacy and judicial backsliding, but Romania remains a reliable ally on Ukraine (hosting refugees, supporting sanctions, providing military aid).

**Bottom line:** Romania's economy is a tale of two countries—dynamic, urban, tech-driven Bucharest vs stagnant, rural, impoverished hinterlands. The fundamentals are solid (diversified industry, energy independence, EU integration), but twin deficits, political dysfunction, and demographic decline are structural drags. The December 2025 elections will determine whether Romania embraces fiscal discipline and continues reforms, or whether populism derails the EU convergence story. If Romania fixes the deficit, joins the eurozone by 2030, and retains its talent, it could become Central Europe's next Poland. If not, it risks becoming the EU's next problem child.`,
    issues: ['Twin deficits triggering EU excessive deficit procedures', 'Fiscal deficit at 6.2% of GDP, well above EU limits', 'Brain drain with 500,000 emigrating 2020-2024', 'December 2025 elections amid populist surge', 'Eurozone entry postponed indefinitely', 'Neptun Deep gas field to boost energy exports by 2027']
  },
  {
    name: 'Russia',
    lat: 61.5240,
    lng: 105.3188,
    summary: `Russia's $2.2 trillion economy is a war machine—literally. In November 2025, entering the fourth year of the Ukraine invasion, defense spending consumes 40% of the federal budget ($145 billion, 6.5% of GDP), unemployment is a record low 2.3% (because 1.5 million men are mobilized or working in defense industries), and GDP growth is projected at 3.9% for 2025 despite the most comprehensive Western sanctions regime ever imposed on a major economy. This is not normal economic activity—it's a command economy on steroids, fueled by oil and gas exports ($280 billion in 2024), propped up by China and India (who buy discounted Russian crude at $60-$70 per barrel, below Brent's $82 average), and sustained by massive fiscal stimulus (budget deficit 2.3% of GDP, financed by raiding the National Welfare Fund). The ruble has stabilized at 95-100 per dollar (down from 120 in late 2022 but well below the pre-war 75), inflation is running at 7.8% (officially—real inflation for food and consumer goods is likely 12-15%), and interest rates are 21% (the Central Bank hiked aggressively to defend the ruble and curb inflation). Consumer living standards are eroding—real wages fell 1.2% in 2024, poverty is rising (14.3% live below the subsistence line, up from 12% in 2021), and the middle class is being hollowed out by inflation and capital controls. But the state's fiscal position remains surprisingly strong: foreign exchange reserves are $580 billion (down from $640 billion pre-war, but stabilized), the sovereign debt-to-GDP ratio is 18% (among the world's lowest), and the budget deficit is manageable as long as oil revenues hold. The economy's long-term trajectory is grim—capital flight ($250 billion since February 2022), technological isolation (Western firms exited, sanctions block advanced semiconductors and machinery), demographic collapse (1.3 million excess deaths during the pandemic, plus war casualties and emigration)—but in the short term, Russia's war economy is functioning. The question is: how long can this last?

Russia's economic model is fundamentally a petrostate—oil and gas account for 60% of export revenues, 40% of federal budget income, and 20% of GDP. In 2024, Russia exported 240 million tons of crude oil and 200 billion cubic meters of natural gas. Europe, once the biggest customer (50% of Russian gas, 30% of oil), has slashed imports to near zero—EU gas imports from Russia fell from 155 bcm in 2021 to 15 bcm in 2024. But Russia redirected: China now takes 30% of Russian oil and gas (via pipelines and tanker shipments), India bought $50 billion in Russian crude in 2024 (up from $2 billion in 2021), and Turkey serves as a transshipment hub. The "shadow fleet"—500+ aging tankers, often uninsured and flying flags of convenience—moves Russian oil to buyers evading sanctions. Western price caps ($60 per barrel for Russian crude) are widely circumvented: India refines Russian oil and re-exports it as "Indian" petroleum products, China stores Russian crude in strategic reserves, and buyers pay in yuan, rupees, or barter arrangements. The Russian government has adapted—pushing "payment in rubles" schemes, diversifying export markets, and using SPFS (Russia's SWIFT alternative) for transactions. But sanctions bite: Russia can't access $300 billion in frozen Central Bank reserves (held in U.S., EU, and G7 jurisdictions), Western technology imports are banned (semiconductors, machinery, aircraft parts), and Russian firms can't access Western capital markets. Defense production is the growth engine—tank, artillery, and missile factories run triple shifts, 3.5 million Russians work in defense-related industries (up from 2 million pre-war), and the state pays premium wages (50-100% above average) to attract workers. This creates labor shortages elsewhere—agriculture, construction, services—driving up wages and inflation.

The fiscal situation is precarious but not collapsing. The 2025 budget projects revenues of $445 billion (oil and gas $180 billion, taxes $240 billion, other $25 billion) and spending of $456 billion (defense $145 billion, social $120 billion, infrastructure $85 billion, debt service $35 billion, other $71 billion). The $11 billion deficit (0.5% of GDP) is tiny, but this assumes oil at $70/barrel—if prices fall below $60, the deficit balloons. The National Welfare Fund (NWF), Russia's sovereign wealth fund, had $140 billion in 2022, but $65 billion has been spent on war and deficit financing, leaving $75 billion. At current burn rates, the NWF depletes by 2027. The Central Bank, led by Elvira Nabiullina (widely respected, surprisingly retained by Putin despite her initial opposition to the war), has been the economy's stabilizing force: raising rates from 7.5% in early 2022 to 21% in November 2025, imposing capital controls (mandatory conversion of export revenues to rubles, restrictions on foreign currency withdrawals), and managing the ruble float. But 21% rates are crushing—corporate borrowing has collapsed, small businesses are failing, and mortgage lending (a Kremlin priority for the middle class) is unaffordable. Inflation is the regime's biggest vulnerability: food prices are up 30% since 2022 (butter, eggs, potatoes are staples, and scarcity is visible), consumer goods are expensive (imported electronics, clothing, cars are 40-60% pricier), and Russians are dipping into savings. The official poverty line is $210/month—14.3% live below it, but regional disparities are massive (poverty is 25%+ in rural areas, North Caucasus, and Siberia). Pensioners are hit hardest—pensions average $250/month, and inflation erodes purchasing power. The middle class—10 million urbanites in Moscow, St. Petersburg, and regional capitals—is shrinking: those who could leave did (500,000 emigrated in 2022-2023, mostly young professionals, IT workers, and liberals), and those who remain face declining living standards.

The long-term outlook is bleak: Russia is technologically regressing—Western firms (Boeing, Airbus, Siemens, Caterpillar, Apple, Microsoft) exited, and domestic substitution is slow. Airlines are cannibalizing planes for parts (Aeroflot's fleet is aging, and no new aircraft deliveries since 2022). Automotive production collapsed—foreign brands (Renault, Volkswagen, Hyundai) left, and 2024 production was 500,000 units (down from 1.5 million in 2021). Russia is assembling Chinese and Iranian vehicles, but quality is poor. The IT sector, once vibrant (Yandex, Kaspersky, mail.ru), is isolated—sanctions block access to advanced semiconductors, cloud services, and global markets. Demographics are catastrophic: Russia's population is 144 million, but it's shrinking 0.5% annually (low birth rates, high mortality, emigration). The working-age population (20-64) will decline 10% by 2035, exacerbating labor shortages. The war has killed 50,000-120,000 Russian soldiers (estimates vary—the government doesn't publish figures), and 300,000+ are wounded. This is a lost generation. The economic partnership with China is deepening—bilateral trade hit $240 billion in 2024 (up 30% from 2021), China supplies consumer goods, machinery, and electronics, and Russia sells energy and raw materials. But it's asymmetric: Russia needs China far more than China needs Russia, and Beijing extracts discounts and concessions. The yuan's share of Russian trade settlements is 40% (up from 5% pre-war), effectively making Russia economically dependent on China. Relations with India are transactional—Delhi buys cheap oil but maintains strategic autonomy (India abstains on UN votes condemning Russia, but doesn't recognize Crimea or the occupied territories). Sanctions will remain indefinitely—the West has no incentive to lift them until Putin exits or Ukraine is restored, and even then, frozen reserves ($300 billion) are likely used for Ukraine reconstruction.

**Bottom line:** Russia's war economy works in the short term—oil revenues, defense spending, and Chinese support keep it afloat—but it's unsustainable. Inflation, labor shortages, technological isolation, and demographic decline are structural drags. The NWF depletes by 2027, and if oil prices crash or China reduces purchases, fiscal collapse looms. Living standards are eroding, the middle class is hollowed out, and the economy is regressing to Soviet-era autarky. Putin has bet Russia's future on the war—if he wins, the economic damage might be forgiven domestically; if he loses, the reckoning will be severe. For now, the economy muddles through, but the trajectory is downward, and there's no plan beyond "endure until the West blinks."`,
    issues: ['Defense spending consumes 40% of federal budget', 'Inflation at 7.8%, interest rates at 21%', 'Western sanctions isolating economy from technology', 'Oil exports redirected to China and India', 'National Welfare Fund depleting by 2027', 'Demographic collapse and technological regression']
  }
]

async function main() {
  console.log('Starting economy batch 8 insertion (Part 1: Qatar, Romania, Russia)...\n')

  for (const country of COUNTRIES_ECONOMY) {
    try {
      console.log(`Processing ${country.name}...`)

      // Check if already exists
      const existing = await prisma.locationSummary.findUnique({
        where: {
          name_type_category: {
            name: country.name,
            type: 'country',
            category: 'economy'
          }
        }
      })

      if (existing) {
        console.log(`  ⚠️  ${country.name} economy writeup already exists, skipping\n`)
        continue
      }

      // Insert the writeup
      await prisma.locationSummary.create({
        data: {
          name: country.name,
          type: 'country',
          lat: country.lat,
          lng: country.lng,
          category: 'economy',
          summary: country.summary,
          issues: JSON.stringify(country.issues),
          topStories: JSON.stringify([]),
          storyCount: 0
        }
      })

      console.log(`  ✅ Successfully added ${country.name} economy writeup\n`)
    } catch (error) {
      console.error(`  ❌ Error processing ${country.name}:`, error)
      console.log()
    }
  }

  console.log('✨ Economy batch 8 (Part 1) insertion complete!')
}

main()
  .catch((e) => {
    console.error('Fatal error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
