import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// BELIZE EDUCATION
const BELIZE_EDUCATION = `Belize has a literacy rate hovering around 82%—respectable for Central America—and an education system that's almost entirely privatized in structure despite being publicly funded. Here's the peculiar arrangement: nearly all schools are operated by churches—Catholic, Anglican, Methodist—under a system dating to colonial times, where religious organizations own the buildings and hire teachers while the government pays the bills. This creates a bizarre accountability vacuum where the Ministry of Education funds schools but doesn't fully control them, religious bodies manage operations but don't bear financial risk, and parents navigate a fragmented landscape where school quality depends entirely on which denomination runs the local facility. The result is massive inequality: urban schools in Belize City and Belmopan have libraries, computers, and trained teachers, while rural schools in the Toledo or Stann Creek districts operate with minimal resources, under-qualified teachers, and completion rates below 60%. Belize's education system works reasonably well for urban middle-class families and fails rural indigenous communities almost entirely.

The structural challenge is governance fragmentation. With schools managed by religious bodies, curriculum standards are uneven, teacher quality varies wildly, and accountability is nearly impossible. The Ministry of Education sets national exams—Primary School Examination (PSE) and Caribbean Examinations Council (CXC) exams—but has limited leverage over school operations. Teacher training happens through the University of Belize and denominational colleges, producing graduates with varying levels of preparation. Salaries are government-paid and reasonably competitive, but deployment favors urban areas, leaving rural schools chronically understaffed. The pupil-teacher ratio officially averages 18:1 in primary schools—excellent by regional standards—but that masks disparities where rural schools exceed 40:1 while urban schools are adequately staffed.

Learning outcomes reflect geographic and ethnic inequalities. Urban schools produce students who pass PSE exams at 75-80% rates and transition smoothly to secondary education. Rural and indigenous students—particularly Maya and Garifuna communities—have completion rates below 50%, pass exams at 40%, and face secondary schools that are either inaccessible or unaffordable despite official fee elimination. English is the medium of instruction from day one, which disadvantages Spanish-speaking and indigenous-language communities where children arrive speaking little English. The curriculum doesn't accommodate linguistic diversity, and bilingual education programs are minimal. The result: students who struggle with language barriers are labeled as poor learners rather than victims of curriculum design.

Secondary education completion is only 65%, and that figure drops below 40% in rural areas. Students who complete secondary school and take CXC exams face high failure rates, especially in mathematics and sciences, because schools lack labs, equipment, and specialized teachers. The University of Belize serves around 4,500 students—tiny for a country of 400,000—and offers limited programs, mostly in education, business, and nursing. Students seeking engineering, medicine, or advanced degrees must study abroad, creating brain drain as many don't return. Higher education quality is uneven, faculty are underpaid, and research capacity is negligible.

What Belize needs is governance reform that shifts control from religious organizations to the state, ensuring accountability and equitable resource distribution. It needs massive investment in rural infrastructure, teacher recruitment and deployment to underserved areas, and bilingual education programs that respect linguistic diversity. The denominational management system made sense in 1950; in 2025, it's an anachronism perpetuating inequality. Belize's education outcomes are decent on average but mask brutal disparities between urban and rural, between mestizo and indigenous, between coast and interior. The system works for some and fails others, and the government lacks the will or capacity to fix it.`

// UNITED KINGDOM EDUCATION
const UK_EDUCATION = `The United Kingdom's education system is simultaneously one of the world's most prestigious and most unequal. England's PISA 2022 scores—489 in reading, 492 in mathematics, 500 in science—place it solidly above OECD averages, and the country's universities dominate global rankings. Yet 54% of school leaders report that teacher shortages hinder instruction, the attainment gap between disadvantaged and advantaged students is one of Europe's widest, and regional disparities mean children in London significantly outperform peers in coastal towns and former industrial areas. This is the paradox: Britain built an education system capable of producing world-class outcomes for some students while systematically failing others based on postcode and parental income. Excellence and inequity coexist, and recent reforms have tilted resources toward academization and marketization rather than addressing structural disadvantages.

The teacher recruitment and retention crisis defines current challenges. England needs thousands more teachers annually, but training program enrollments fall short, especially in STEM subjects. Workload is crushing—British teachers report among the highest stress levels in the OECD—and salaries lag behind other graduate professions, making teaching unattractive to top candidates. The academies system, where schools operate independently of local authority control, fragments the profession: pay and conditions vary by school chain, career progression is unclear, and collective bargaining is weakened. Schools in disadvantaged areas struggle most to recruit, creating vicious cycles where poor areas get inexperienced teachers, learning outcomes suffer, and teachers leave for better postings. The 2024/25 data shows slight increases in Northern Ireland but decreases elsewhere, and the overall shortage persists.

The attainment gap is the system's moral failure. Disadvantaged students—those eligible for free school meals—lag advantaged peers by 18 months by age 16, one of the widest gaps in the developed world. The gap opens early, in primary school, and compounds through secondary education. Interventions like pupil premium funding (extra money for disadvantaged students) show modest impacts, but structural factors—poverty, housing instability, parental education, neighborhood effects—overwhelm school efforts. Grammar schools in selective areas worsen inequality by creaming off high-achieving students, leaving comprehensives with concentrated disadvantage. The private school sector educates only 7% of students but produces disproportionate shares of university entrants, especially to Oxbridge, perpetuating class advantages across generations.

Regional disparities are stark. London schools outperform despite higher poverty because of better teachers, more resources, and diverse populations. Coastal towns and former industrial areas—Blackpool, Hartlepool, Barnsley—have lower attainment, worse post-school outcomes, and limited opportunities. The government's "levelling up" rhetoric hasn't translated to meaningful education investment in left-behind areas. Scotland, Wales, and Northern Ireland run separate systems with different curricula and governance, adding complexity and making UK-wide comparisons difficult.

Higher education is a global strength: Oxford, Cambridge, Imperial, LSE, Edinburgh, and others attract talent worldwide and drive research. But undergraduate tuition fees—£9,250 annually plus living costs—create massive student debt, disadvantaging working-class students who graduate with £50,000+ debt while wealthier peers rely on family support. The Russell Group universities remain dominated by privately educated and affluent students, despite widening participation efforts.

What the UK needs is bold action on teacher retention—competitive pay, workload reduction, career structures that reward excellent teaching, not just administration. It needs sustained focus on closing attainment gaps through early intervention, better funding for disadvantaged areas, and grammar school abolition or reform. The academies experiment shows mixed results at best and should be reconsidered. Britain's education system succeeds at producing elite outcomes; it fails at ensuring every child gets a decent education regardless of background. That's a political choice, not an inevitability, and it's correctable if the will exists.`

// FRANCE EDUCATION
const FRANCE_EDUCATION = `France's education system is in decline, and the PISA 2022 results made it undeniable: 29% of 15-year-olds lack basic skills in mathematics—up from previous cycles—and the socioeconomic gradient is steeper than almost anywhere in Europe. Among disadvantaged students, 49% fail to reach minimum proficiency in math. This is shocking in a country that invented the centralized education model, staffs schools with highly trained career civil servants, and spends 5.4% of GDP on education. France proves that structure and spending don't guarantee outcomes if pedagogy is outdated, inequality is entrenched, and reform efforts are politically impossible. The baccalauréat is prestigious, French universities are free, and the elite grandes écoles produce world-class graduates—but the system is failing nearly a third of students, particularly those from immigrant and working-class backgrounds. Republican universalism promised equal opportunity; the reality is brutal stratification by neighborhood, with suburban banlieues receiving education that looks nothing like what central Paris provides.

The pedagogical crisis reflects institutional rigidity. French teaching emphasizes rote learning, teacher-led instruction, and discipline over creativity, critical thinking, or active learning. Classrooms are formal, hierarchical, and focused on content transmission rather than skill development. Students sit in rows, copy from blackboards, memorize facts for exams, and are rarely asked to apply knowledge or work collaboratively. This approach worked when the goal was credentialing a small elite; it fails when the goal is mass proficiency in complex skills. Teacher training—through competitive exams (CAPES, agrégation) and university programs—produces subject specialists with deep content knowledge but minimal pedagogical preparation. Teachers arrive in classrooms able to discuss Voltaire or solve equations but untrained in differentiated instruction, formative assessment, or managing diverse learners. Professional development is limited, and the culture resists innovation.

Inequality is structural and geographic. Schools in affluent urban arrondissements have engaged families, motivated students, and ample resources. Schools in banlieues—suburban areas with concentrated immigrant populations and poverty—face violence, teacher shortages, student disengagement, and abysmal results. The carte scolaire (school zoning system) theoretically ensures equal access but entrenches inequality by tying school quality to neighborhood wealth. Middle-class families game the system through private schools (20% of students), strategic moves, or derogations (exemptions), leaving disadvantaged areas with concentrated failure. The grandes écoles pathway—prep classes (classes préparatoires) leading to elite engineering and business schools—recruits overwhelmingly from affluent Parisian backgrounds, perpetuating elite reproduction.

The government's 2023-2025 reforms address some gaps. The "Schoolwork Done" program provides mandatory after-school support for Grade 6 students, and personalized tutoring launched in 2023 targets struggling students. The 2025 early childhood curriculum updates aim to improve foundational skills. These are marginal improvements, but they don't confront the pedagogical rigidity, geographic inequality, or elite capture that define the system. France needs curriculum reform emphasizing competencies over content coverage, teacher retraining toward active learning methods, and massive resource redistribution toward disadvantaged areas. The political will doesn't exist—teacher unions resist change, suburban middle classes defend privileges, and elites benefit from the status quo.

Higher education is bifurcated: universities are free, open-access, and overcrowded with limited resources; grandes écoles are selective, elite, and well-funded. Universities produce mass graduates with uneven skills; grandes écoles produce elites who dominate government and business. The disconnect between school education and university expectations is vast—students arrive unprepared, dropout rates exceed 30% in some programs, and degrees don't always signal competence. France's education system excels at credentialing elites; it's failing at mass skill development, and PISA 2022 proves it. Unless France confronts pedagogical conservatism and structural inequality, the decline will continue.`

// GERMANY EDUCATION
const GERMANY_EDUCATION = `Germany's education system is in freefall, and the numbers are brutal. PISA 2022 showed declines in all three domains—reading, math, science—continuing a 12-year downward trend. Nearly 30% of students fail to reach basic proficiency in math, socioeconomically disadvantaged high achievers dropped from 26.5% in 2015 to 17.8% in 2022, and digital skills are abysmal: the 2023 ICILS study found 41% of 8th graders lack basic digital competencies. Meanwhile, Germany faces a projected shortage of 49,000 teachers by 2035, concentrated in STEM subjects, and only a third of teachers report receiving training in digital tools. This is catastrophic for a country that built its prosperity on engineering excellence and Mittelstand innovation. The education system that once produced world-leading technical skills is now failing to teach basics, prepare students for digital economies, or address inequality. Federalism fragments policy, conservative pedagogy resists change, and immigration creates linguistic diversity that schools aren't equipped to handle.

The structural problem is federalism. Germany's 16 Länder each control education, creating 16 different curricula, examination systems, teacher training programs, and resource allocations. Coordination is minimal, standards vary, and mobility between Länder disrupts students. Some states perform well (Bavaria, Saxony), others poorly (Bremen, Berlin), and the gaps reflect political priorities and wealth disparities. Federal government efforts to support digitalization—the "Digital Pact 2.0" investing €5 billion by 2030—help at the margins but can't overcome structural fragmentation. The result is incoherence: no national strategy, no consistent standards, and outcomes depending on where students happen to live.

The teacher crisis is acute. Germany needs thousands more teachers annually, but training program enrollments lag, and STEM subjects face severe shortages. Part-time teaching increased significantly from 2018 to 2022, indicating retention problems—teachers leave full-time work due to workload, stress, or better opportunities. Salaries are decent but not competitive with other graduate professions. The Gymnasien (academic secondary schools) attract the best teachers; Hauptschulen and Realschulen (vocational tracks) struggle to staff. This compounds inequality because disadvantaged students are disproportionately tracked into vocational streams with under-qualified teachers, while affluent students in Gymnasien receive excellent instruction. Tracking happens at age 10—obscenely early—and is heavily influenced by parental background, entrenching inequality from primary school onward.

Immigration creates linguistic and cultural challenges the system hasn't addressed. Germany accepted over 1 million refugees since 2015, and integrating non-German-speaking students into classrooms designed for native speakers overwhelms teachers. Many schools lack German-as-a-second-language specialists, and students who arrive with limited German are mainstreamed without adequate support. Achievement gaps between immigrant and native-born students are among Europe's widest. The StartChances program, launched in 2024, targets schools with high proportions of disadvantaged students, but it's too small and too new to show impact.

Digital skills deficiency is alarming. Despite Digital Pact funding, most teachers lack training in digital pedagogy, schools have outdated equipment, and students don't gain competencies needed for digital economies. The ICILS finding that 41% of 8th graders lack basic digital skills is disqualifying for a country whose economic model depends on technological sophistication. Universities maintain quality in engineering, sciences, and applied fields, but vocational education—Germany's historical strength—faces declining prestige and enrollment. Dual study programs integrating work and academics show promise with lower dropout rates (7% vs. 28% in traditional programs), suggesting pathways that work.

Germany needs national education standards, earlier and better German language instruction for immigrants, ending or delaying tracking to reduce inequality, massive teacher recruitment and retraining (especially in STEM and digital pedagogy), and curriculum reform emphasizing critical thinking over rote learning. The federal structure makes reform politically difficult, and conservative educational culture resists change. But the PISA trajectory is unsustainable, and Germany's economic competitiveness depends on reversing it. The engineering excellence that built Germany's prosperity wasn't automatic—it was produced by education systems that worked. The current system doesn't, and time is running out to fix it.`

// ITALY EDUCATION
const ITALY_EDUCATION = `Italy's education system is improving in reading, stable in science, but declining in mathematics—and that mixed PISA 2022 performance obscures deeper problems. The North-South divide is catastrophic: students in Lombardy and Veneto score near the top of European rankings, while students in Calabria and Sicily score near the bottom, creating achievement gaps within one country that exceed gaps between some countries. Early school leaving among immigrants reaches 25.5%—nearly triple the 9.1% rate for native-born Italians—and youth unemployment exceeds 20%, suggesting massive disconnects between education outputs and labor market needs. Italy spends reasonably on education (4.1% of GDP), has nearly universal enrollment, and maintains prestigious universities in Bologna, Milan, and Rome. But the system suffers from bureaucratic sclerosis, pedagogical conservatism, geographic inequality, and a vocational education sector that's underdeveloped and stigmatized. Reforms are perpetual—the 2025/2026 school year introduces the "Esame di maturità" changes and a new Liceo of Made in Italy—but they tinker at margins rather than confronting structural failures.

The North-South divide reflects decades of uneven development. Northern regions have strong economies, engaged communities, functional governance, and well-resourced schools. Southern regions face poverty, organized crime, weak institutions, and schools operating with minimal support. Teachers prefer northern postings, so southern schools get less experienced, less qualified staff. Infrastructure is worse, dropout rates higher, and post-school opportunities fewer. This isn't new—the Mezzogiorno has lagged since unification—but education policy treats it as a technical problem rather than a political and economic crisis requiring sustained investment and structural reform.

Immigrant integration is failing. The 25.5% early leaving rate among non-native students reflects linguistic barriers, poverty, discrimination, and curriculum that doesn't accommodate cultural diversity. Many immigrant students arrive speaking little Italian and are mainstreamed without adequate language support. Schools in areas with high immigrant concentrations—Milan suburbs, Rome outskirts—are under-resourced and overwhelmed. The achievement gaps are predictable consequences of policy failures: Italy expanded immigration without expanding integration infrastructure, and schools bear the cost.

The vocational education gap is strategic failure. Italy's economy needs technicians, craftsmen, and skilled trades, but vocational pathways are stigmatized as inferior to academic licei (high schools). The new "4+2" technological-professional pathway—four years of school plus two at ITS Academies—aims to provide technical skills, but enrollment remains low because cultural preferences favor university pathways regardless of labor market signals. The result: university graduates in humanities and social sciences can't find work, while employers can't find skilled technicians. The ITS Academies (higher technical institutes) offer post-secondary technical training and have strong employment outcomes, but they're small-scale and underfunded.

University quality is uneven. Elite institutions in Milan, Bologna, and Rome maintain academic standards and research output, but many universities are underfunded, overcrowded, and produce graduates whose skills don't match employer needs. The academic job market is notoriously nepotistic—hiring favors internal candidates and political connections over merit—which stifles innovation and demoralizes talented young scholars. Research funding is inadequate, and brain drain sees Italy's best students pursue PhDs and careers abroad.

The 2025/2026 reforms—revised curriculum guidelines, the Liceo of Made in Italy, the 4+2 pathway—are incremental adjustments, not transformations. What Italy needs is massive investment in southern schools to close regional gaps, comprehensive immigrant integration programs including intensive Italian language instruction, vocational education destigmatization and expansion, and university reform that funds research, breaks nepotism, and aligns programs with economic needs. The political will doesn't exist—governments change frequently, reforms are reversed, and vested interests resist change. Italy's education system limps forward, producing uneven outcomes that reflect and reinforce the country's broader dysfunctions. The North-South divide in PISA scores isn't an education problem—it's a governance problem, and education reform alone won't fix it.`

// SPAIN EDUCATION
const SPAIN_EDUCATION = `Spain's PISA 2022 scores are aggressively mediocre—slightly above OECD average in math and reading, at average in science—and that's after two decades of PISA-driven reform efforts. What's worse: regional disparities are enormous, with Castile & León scoring better than the Netherlands in math while the Canary Islands score well below all OECD averages. Boys outperform girls in math by 10 points; girls outperform boys in reading by 25 points. Teacher precarity is structural: 22.5% of teachers have temporary contracts, ranging from 4.7% to 43.4% by region, and Spain has one of the lowest shares of teachers under 30 (6.1%) in the OECD, indicating an aging workforce and recruitment failures. The government pledged to reduce temporary contracts to 8% by 2025, but the deadline passed without achievement. Spain spends adequately (4.6% of GDP on education), enrollment is universal, and universities serve hundreds of thousands—but outcomes lag peer countries, and structural problems—teacher precarity, regional inequality, pedagogical conservatism, university nepotism—persist despite perpetual reform rhetoric.

The regional disparities are absurd for a single country. Castile & León's education outcomes rival Northern Europe's; the Canary Islands' rival Southern Europe's weakest. The reasons are political and economic: wealthy, well-governed regions invest in education, attract better teachers, and support schools effectively. Poorer regions with weaker governance don't. Spain's devolution of education to autonomous communities creates 17 different systems with different resources, priorities, and outcomes. The result is lottery by birth: where you're born determines education quality. National standards exist on paper but are weakly enforced, and the Partido Popular and PSOE governments have alternated reforms—LOMCE, LOMLOE—that change structure without improving outcomes.

Teacher precarity is scandalous. Over a fifth of Spanish teachers have temporary contracts, meaning they lack job security, stable income, or career progression. They're hired year-to-year, often learning their assignments weeks before school starts, and can't develop expertise or institutional knowledge. Regions with the worst precarity (Andalusia, Canary Islands) face constant teacher turnover, which devastates learning continuity. The aging workforce—only 6.1% under 30—indicates teaching isn't attracting young talent. Salaries are adequate but not competitive with other graduate professions, working conditions vary wildly by region, and the career path is unappealing. The government's digital training programs are impressive—over 800,000 teachers participated, exceeding 2025 targets—but they paper over structural employment problems.

Pedagogical conservatism persists despite curriculum reforms. Spanish classrooms emphasize teacher-led instruction, textbook memorization, and exam preparation. Active learning, project-based work, and critical thinking are rhetorical commitments, not classroom realities. Teacher training produces subject specialists with minimal pedagogical preparation, and professional development is uneven. The system credentials students who can recall facts but struggle with application, problem-solving, and creative thinking—exactly the skills modern economies need.

University endogamy is notorious. Spanish universities hire their own graduates, perpetuating mediocrity and stifling innovation. Nepotism and favoritism determine hiring more than academic merit. Research output is limited, international rankings are middling, and many degrees don't prepare graduates for employment. Youth unemployment exceeds 25%, partly because university curricula don't match labor market needs. The system produces humanities and social science graduates while employers need STEM skills and technical training.

What Spain needs is national standards with teeth, eliminating teacher precarity through permanent contracts and competitive salaries, pedagogical reform emphasizing competencies over content, and university reform that breaks endogamy and funds research. Regional autonomy makes national reform difficult, political instability leads to policy reversals, and vested interests resist change. Spain's education system has been "reforming" for 25 years without transforming. PISA scores are stagnant, regional inequality persists, and structural problems remain. Unless Spain confronts teacher employment, pedagogical conservatism, and regional fragmentation seriously, another 25 years of mediocrity awaits.`

// POLAND EDUCATION
const POLAND_EDUCATION = `Poland's education system is in crisis, and the PISA 2022 results were a wake-up call: the decline in reading and math was twice the OECD average, in science three times the average. After being Europe's PISA darling—the 1999 reform that delayed tracking and extended comprehensive education produced spectacular gains through the 2010s—Poland's students now perform worse than their European peers in basic skills. Teacher salaries are the EU's lowest, morale is abysmal, shortages affect schools and kindergartens, curricula are overloaded, student and teacher well-being is poor, and inequalities are rising. The government responded with "Reform26: Compass of Tomorrow," a comprehensive restructuring beginning in 2025/2026 that introduces new subjects (citizenship education, health education), core curriculum changes, project-based learning, a new grading system, and more teacher autonomy. It's ambitious, but Poland is attempting to fix in six years what took a decade to break—and whether political will and resources match the scale of the challenge is uncertain.

Poland's earlier success story provides the blueprint. The 1999 reform extended comprehensive schooling, delayed tracking from age 14 to 16, strengthened standards, and improved teacher training. PISA scores soared, inequality declined, and Poland became proof that system-level reform could transform outcomes. Then the Law and Justice government reversed course after 2015, re-introducing earlier tracking (back to age 14), overloading curricula with nationalist content, underfunding schools, and ignoring teacher salaries. Teachers protested, morale collapsed, and COVID-19 exacerbated learning losses. PISA 2022 showed the consequences: Poland's gains evaporated, basic skills declined sharply, and inequalities returned. The 2024 election brought a reform-minded government, and Reform26 is the response—but undoing damage takes longer than causing it.

The teacher crisis is existential. Polish teachers earn the EU's lowest salaries—barely above minimum wage in some regions—and working conditions are terrible. Overloaded curricula mean 25+ hours of contact time weekly, plus grading, planning, and administrative tasks. Shortages affect every level, from kindergartens to secondary schools, and rural areas face the worst gaps. Young people don't enter teaching, experienced teachers leave, and those who remain are demoralized. The Ministry submitted draft regulations on minimum teacher pay for 2025, but whether increases are sufficient or timely is doubtful. Without competitive salaries and workload reductions, teacher shortages will worsen, and reform efforts will fail because there won't be enough qualified teachers to implement them.

Reform26 is conceptually sound: lighter core curriculum, more project-based learning, new grading systems emphasizing growth over ranking, and subjects (citizenship, health) addressing social needs. Delaying or eliminating early tracking would reduce inequality. But implementation requires teacher buy-in, training, resources, and time—precisely what Poland lacks. Teachers are exhausted, underpaid, and skeptical of top-down reforms after years of policy churn. The reform unfolds over six years (2025-2031), but Polish politics are volatile, and governments change. If Reform26 is reversed mid-course, it will cause more harm than good.

Higher education quality is reasonable—Poland hit tertiary attainment targets—but mismatches persist. Universities produce humanities and social science graduates while employers need STEM and technical skills. Vocational education is ineffective, and adult learning participation is low. The skills shortages in the workforce reflect education system failures to anticipate labor market needs.

Poland's education crisis is reversible—the 1999 reforms proved system transformation is possible. But reversal requires sustained political will, adequate funding, teacher salary increases, workload reductions, curriculum coherence, and patience. Reform26 is the right direction, but Poland is racing against time, budget constraints, and teacher morale collapse. If the government delivers—competitive teacher pay, genuine curricular simplification, reduced bureaucracy, and consistent implementation—Poland could recover. If it doesn't, the PISA decline will continue, and a generation will pay the price. Poland succeeded once; whether it can succeed again depends on choices made in the next two years.`

// UKRAINE EDUCATION
const UKRAINE_EDUCATION = `Ukraine's education system is operating under conditions that should make schooling impossible: 4,358 educational institutions destroyed or damaged, 2,046 schools among them, and $13.4 billion in direct losses as of October 2025. Over 90% of schools have some form of shelter, 15 underground campuses are completed with 180+ more scheduled by year's end, and hybrid learning—combining in-person and online instruction—has become permanent infrastructure. Teachers work under air raid sirens, students study in basements, and entire regions face interrupted education for nearly four years. Ukrainian students' learning losses equal two years of missed schooling according to PISA surveys conducted in October 2022. The educational gap between a Kyiv child and one from occupied or frontline areas reaches five academic years. Yet schools remain open, exams continue, and reforms proceed—Ukraine is simultaneously defending its existence and attempting to modernize education. This is either heroic or insane, likely both, and the long-term consequences won't be understood for decades.

The infrastructure devastation is staggering. Over 4,000 institutions damaged or destroyed means entire districts lack functional schools. Reconstruction happens slowly—funding is limited, active combat prevents building in frontline areas, and priorities favor military needs over education. The underground campus solution is pragmatic: if schools can't be safe above ground, build them below. Fifteen are operational, more under construction, and they include classrooms, gyms, cafeterias, and shelters. This is education as wartime necessity, and it works—children attend school, teachers teach, and learning happens. But the psychological costs are enormous: children growing up in shelters, perpetually anxious about sirens, traumatized by displacement, loss, or violence. Ukraine hasn't just lost infrastructure; it's losing childhoods, and the long-term impacts on mental health and development are incalculable.

The educational inequality is geographic and brutal. Kyiv maintains relatively normal schooling: hybrid formats, functional infrastructure, and continuity. Frontline areas—Kherson, Donetsk, Zaporizhzhia—face constant bombardment, frequent closures, and minimal in-person schooling. Occupied territories see enforced Russification, Ukrainian curriculum banned, and teachers coerced or replaced. The five-year achievement gap between privileged and frontline students isn't an education problem—it's a war consequence. Remediation will require years of intervention, targeted support, and resources Ukraine doesn't have.

Higher education faces similar challenges. Nearly 3,600 institutions damaged, classes in shelters, faculty and students displaced or mobilized, and research capacity destroyed. Ukrainian universities maintain operations—degrees are awarded, classes continue online and in-person—but quality suffers. Labs are destroyed, libraries inaccessible, and academic exchange impossible. Brain drain is severe: talented students and scholars flee to Europe or North America, and many won't return. Ukraine is losing human capital at precisely the moment it needs maximum talent for reconstruction.

The LEARN program—expected to reach one million students, teachers, and staff by end of 2025—provides school safety improvements, transportation, textbooks, and teacher training. International support is substantial: EU, U.S., and bilateral donors fund emergency education, infrastructure repairs, and digital learning tools. But support is temporary, and donor fatigue is real. Ukraine's long-term education needs exceed current funding by orders of magnitude.

The reforms continuing despite war are remarkable. Curriculum modernization, competency-based learning, teacher professional development, and digital integration—all proceed as if normalcy existed. This reflects two realities: Ukraine's education ministry refuses to let war halt progress, and post-war reconstruction will require modern skills, so curriculum reform can't wait. Whether these reforms are implemented effectively amid chaos is questionable, but the attempt matters.

Ukraine's education system is surviving, not thriving. Schools operate, children learn, exams happen—but the costs are enormous, the inequalities widening, and the long-term damage incalculable. If Ukraine wins, rebuilding education infrastructure, addressing learning losses, healing trauma, and closing achievement gaps will require a generation and tens of billions of dollars. If Ukraine loses, the entire system collapses into Russification and cultural erasure. Education in Ukraine isn't about PISA scores or university rankings—it's about civilizational survival. That they're keeping schools open at all is extraordinary; that they're attempting reform while doing so is almost unbelievable. The consequences—positive and negative—will shape Ukraine's future regardless of how the war ends.`

// RUSSIA EDUCATION
const RUSSIA_EDUCATION = `Russia's education system produces strong outcomes in international assessments—PISA scores consistently exceed OECD averages in math and science, reading performance is solid, and over 600,000 students participate in testing cycles—yet the system suffers from authoritarian rigidity, urban-rural inequality, university quality crises, and increasing ideological control that stifles critical thinking. Russian schools excel at producing students who can solve math problems and recall scientific facts; they fail at fostering creativity, questioning, or independent thought. The structure is centralized, standardized, and focused on the Unified State Exam (EGE)—a high-stakes test determining university admission—which drives rote learning, exam coaching, and teaching to the test. Teacher training is thorough, salaries are modest but stable, and infrastructure is adequate in cities and abysmal in rural areas. Putin's regime tightened ideological control post-2022, mandating patriotic education, censoring curricula, and punishing dissent, which poisons intellectual culture. Russia demonstrates that authoritarian systems can produce measurable academic achievement while destroying the habits of mind democratic societies need—skepticism, debate, and intellectual courage.

The structural strengths are real. Russian schools follow a national curriculum covering mathematics, sciences, literature, history, and foreign languages thoroughly. Students at elite schools in Moscow and St. Petersburg receive education rivaling anywhere globally. Teacher training is serious: four-year degrees, pedagogical preparation, and subject mastery. Professional development exists, and teachers are civil servants with stable employment. The EGE standardized testing, introduced in the 2000s, replaced corrupt university admission processes and provided meritocratic pathways. Students who score well access prestigious universities; those who don't pursue vocational training or lower-tier institutions. The system is orderly, predictable, and produces graduates with solid foundational knowledge.

The weaknesses are equally real. Urban-rural inequality is vast: Moscow schools have modern facilities, technology, and highly qualified teachers, while rural Siberian schools operate in decaying Soviet-era buildings with under-qualified teachers and minimal resources. Infrastructure investment favors cities, and rural depopulation leaves some areas with barely functional schools. Teacher salaries in rural areas are too low to attract talent, and experienced teachers migrate to cities or leave the profession. The digital divide is severe—urban schools have computers and internet, rural schools don't.

University quality is the system's Achilles heel. Russia has prestigious institutions—Moscow State University, St. Petersburg State, MIPT, Higher School of Economics—but most universities are mediocre or worse. Academic culture suffers from rote learning, minimal critical thinking, authoritarian professors, and resistance to innovation. Research funding outside elite institutions is negligible, academic freedom is limited, and corruption in admissions and grading persists despite EGE reforms. Brain drain is catastrophic: Russia's best students pursue advanced degrees abroad and often don't return. The war accelerated emigration—tens of thousands of educated Russians fled in 2022-2023, taking skills and talent with them.

Ideological tightening post-2022 is corrosive. The regime mandates "patriotic education," revises history curricula to glorify Soviet and Russian imperialism, censors discussions of Ukraine, and punishes teachers or students who dissent. Universities face increased surveillance, academic freedom is constrained, and critical inquiry is dangerous. This produces conformity, self-censorship, and intellectual stagnation. Students learn what to think, not how to think—exactly what authoritarian regimes want and exactly what modern economies don't need.

The vocational education system (PTU system) historically provided skilled workers for Soviet industries but declined post-1991. The government attempts to revive it, emphasizing technical training and workforce readiness, but prestige is low, and students prefer academic pathways even when job prospects are better in trades. The mismatch between education outputs and labor market needs persists.

Russia's education system succeeds at producing disciplined, knowledgeable conformists and fails at producing creative, critical, independent thinkers. PISA scores are high because PISA measures content knowledge, not intellectual courage or creativity. The system worked for Soviet industrialization, works for maintaining authoritarian control, and doesn't work for innovation-driven economies. Russia's best talent leaves, universities stagnate, and ideological control tightens—this is educational decline disguised as stability. Strong PISA scores and university enrollment statistics hide deeper rot: a system that teaches students to obey, not to question, and that's producing exactly the citizens Putin's regime wants and exactly the human capital Russia's economy doesn't need.`

// TURKEY EDUCATION
const TURKEY_EDUCATION = `Turkey's education system is enormous—18 million students, 1 million teachers, universal enrollment—and profoundly unequal. PISA 2022 results show that teacher certification correlates with student achievement more in Turkey than almost anywhere (2nd out of 18 countries), but teacher support is among the lowest (78th out of 79 countries). Digital device policies are strictly enforced (2nd out of 45 countries), yet learning outcomes remain mediocre and highly stratified by socioeconomic status and geography. Urban schools in Istanbul, Ankara, and Izmir function reasonably well; rural schools in eastern Anatolia are under-resourced, understaffed, and produce abysmal outcomes. The Ministry of National Education controls everything centrally—curriculum, hiring, textbooks, exams—which should ensure consistency but instead produces bureaucratic sclerosis. The national university entrance exam (YKS) is a high-stakes bottleneck that drives a toxic exam-prep culture, enriching private dershanes (cram schools) while distorting pedagogy. Turkey proves that enrollment isn't education: millions attend school, but quality, equity, and outcomes lag what the country needs to escape the middle-income trap.

The centralization problem creates rigidity. The Ministry of National Education sets national curricula, manages teacher hiring and deployment, and controls examinations. This means schools lack autonomy, teachers lack flexibility, and local needs go unmet. The curriculum emphasizes content coverage over competencies, memorization over critical thinking, and religious and nationalist themes over inquiry. Pedagogy is teacher-centered, hierarchical, and focused on exam preparation. Students sit in rows, copy notes, memorize facts, and are trained to pass the YKS university entrance exam—which determines futures. Failure means second-tier universities, limited opportunities, and constrained life prospects. Success means access to elite universities and career pathways. The pressure creates a national obsession with exam scores, distorting education into test prep.

Teacher quality varies wildly. Certified teachers in well-resourced urban schools provide decent instruction; under-qualified or temporary teachers in rural schools don't. Teacher training requires four-year degrees with subject specialization and pedagogy, but the quality of training institutions varies. Salaries are modest, working conditions differ drastically between urban and rural posts, and professional development is limited. The data showing high correlation between teacher certification and student achievement suggests quality matters—but Turkey hasn't ensured all students get quality teachers. Rural areas, especially in the southeast (Kurdish regions), face chronic teacher shortages, high turnover, and infrastructure deficits.

The inequality is geographic, socioeconomic, and ethnic. Urban middle-class students attend schools with trained teachers, functional facilities, and resources; rural and working-class students don't. Kurdish-majority areas in the southeast face additional challenges: poverty, conflict legacies, linguistic discrimination (Kurdish isn't a medium of instruction), and cultural marginalization. Gender gaps have closed in enrollment but persist in outcomes and subject choices—girls are steered away from STEM fields, and conservative families in rural areas limit girls' educational ambitions.

The university bottleneck is brutal. Turkey has over 200 universities, but only a handful (Boğaziçi, METU, Istanbul Technical, Istanbul University) are internationally respected. The YKS exam determines admission, and competition is fierce—millions take it annually, and only a fraction get preferred placements. Those who don't access top universities attend lower-tier institutions with limited resources, weaker faculty, and degrees that don't signal competence. Humanities and social sciences dominate enrollments because programs are cheap to run, but labor markets need STEM and technical skills. Youth unemployment exceeds 20%, partly because education outputs don't match economic needs.

The private sector fills gaps the state doesn't. Private dershanes coach students for YKS, private schools offer better resources (at high cost), and wealthy families pay for quality education the public system doesn't provide equitably. This creates class stratification: the wealthy buy educational success, the poor depend on underfunded public schools and usually fail to access elite pathways.

What Turkey needs is decentralization giving schools autonomy, curriculum reform emphasizing critical thinking over memorization, teacher salary increases and equitable deployment, investment in rural and southeastern infrastructure, linguistic accommodations for Kurdish populations, and university reform reducing dependence on high-stakes exams. None of this is happening under Erdogan's increasingly authoritarian regime, which prioritizes religious conservatism and political control over education quality. Turkey's education system produces mass enrollment without mass learning, credentials without competence, and inequality that reinforces class and regional divides. Unless Turkey confronts centralization, exam culture, and inequity seriously, it won't escape middle-income status—because the human capital development needed for high-income economies requires education systems that produce critical thinkers, not test-takers.`

// GREECE EDUCATION
const GREECE_EDUCATION = `Greece's education system is failing measurably, and PISA 2022 made it undeniable: 47.2% of 15-year-olds underperform in mathematics—nearly half the student population can't reach minimum proficiency. Classroom disciplinary climate is among the worst internationally, students perceive teachers as unsupportive compared to other PISA countries, and outcomes show no improvement trajectory toward the government's 2027 goal of reaching OECD averages. Teacher salaries are 31% below comparably educated workers—worse than the 17% OECD average gap—yet turnover is low (2.6% retire annually, 0.1% resign), suggesting teachers stay despite poor conditions because alternatives don't exist. Greece spends adequately (4% of GDP), has universal enrollment, and universities that are tuition-free, yet the system produces dismal outcomes, low student engagement, and graduates unprepared for labor markets. Decades of economic crisis, political instability, and governance failures hollowed out institutions, and education reflects broader state dysfunction. The 2025/2026 reforms allowing private universities and the Onassis Foundation's 22 model schools are incremental; they don't address the pedagogical rigidity, teacher demoralization, or structural inequities defining the system.

The pedagogical crisis is visible in every classroom. Greek teaching emphasizes rote memorization, teacher-led lectures, and textbook copying. Students sit passively, take notes, memorize facts for exams, and aren't asked to think critically, collaborate, or apply knowledge. The culture is authoritarian: teachers talk, students listen, and questioning is discouraged. Discipline problems are rampant—PISA data shows Greece has among the worst classroom climates—because students are disengaged, unmotivated, and bored. When pedagogy is purely transmissive and content is divorced from relevance, students tune out. The result: years in school produce credentials but not competencies.

Teacher demoralization is structural. Salaries are non-competitive—31% below comparable professions—and working conditions are poor. Class sizes are large, resources are limited, and professional development is minimal. The Greek bureaucracy is infamous for inefficiency, and teachers face administrative burdens that steal time from instruction. Yet turnover is low because Greece's job market is terrible—unemployment is high, alternative professional opportunities are scarce, and civil service positions provide stability even if salaries are low. Teachers stay because leaving isn't an option, not because the profession is rewarding. This produces a demoralized, aging workforce that teaches because they're stuck, not because they're passionate.

Inequality is socioeconomic and geographic. Urban middle-class students in Athens and Thessaloniki access better schools, private tutoring (frontisteria), and family support. Rural and working-class students don't. Greece's economic crisis hit poorer families hardest, reducing resources for education, and austerity measures cut school budgets. Frontisteria—private cram schools preparing students for university entrance exams (Panhellenic exams)—are ubiquitous and expensive, creating pathways to success only wealthy families can afford. The system is meritocratic in theory (exams determine university admission), but in practice, it advantages those who can pay for prep.

University access is free, but quality is uneven. Greek universities are overcrowded, underfunded, and academically weak by international standards. The 2025/2026 reform allowing private universities and overseas branches aims to introduce competition and improve quality, but it's controversial—critics worry it will create two-tier systems where wealthy students attend private institutions and poor students are stuck in underfunded public ones. Public universities need more funding, better facilities, and academic reforms emphasizing research and innovation, but the resources don't exist.

The Onassis Foundation's 22 model schools, launched in January 2025, are an experiment: well-funded, well-staffed schools demonstrating what's possible with resources. If successful, they'll prove that quality is achievable; they'll also highlight by contrast how underfunded regular public schools are. The risk is that model schools become elite enclaves rather than templates for system-wide improvement.

Greece's education crisis is a governance crisis. Decades of clientelism, corruption, political instability, and economic collapse destroyed state capacity, and education suffered accordingly. Fixing Greek education requires fixing Greek governance, which requires political will, resources, and time that don't exist. The 47.2% math underperformance rate isn't an education problem—it's a symptom of state failure. Unless Greece rebuilds governance, funds institutions adequately, reforms pedagogy, motivates teachers, and addresses inequality, PISA scores won't improve. The 2027 goal of reaching OECD averages is fantasy without transformation, and transformation isn't happening. Greek education is stuck, and the students trapped in it pay the price.`

// BELGIUM EDUCATION
const BELGIUM_EDUCATION = `Belgium's education system is one of Europe's most unequal, and the data is damning: 26.5% of students report repeating at least one grade—the highest in the EU—and among disadvantaged students, the rate reaches 46.7% (3rd out of 76 PISA-participating countries). One in four 15-year-olds fails to reach minimum proficiency in math, reading, and science, and performance is declining, especially among top achievers. Early tracking funnels disadvantaged students into vocational programs at nearly three times the rate of advantaged peers, creating socially segregated pathways. Teacher shortages are severe—1.8% of positions unfilled in Flanders, 2.6% in Wallonia—and the share of non-fully qualified teachers reaches 12.7% in Wallonia. Belgium spends adequately, has strong universities, and produces high-achieving elite students, but the system's structural inequalities—grade repetition, early tracking, linguistic division, and school segregation—create apartheid by socioeconomic status. This isn't accidental; it's designed. Belgium's education system sorts students early and permanently, ensuring advantages reproduce across generations and disadvantages compound. Reform efforts are stymied by linguistic and political fragmentation across Flanders, Wallonia, and Brussels.

The grade repetition crisis is uniquely Belgian. Nowhere else in Europe do over a quarter of students repeat grades, and nowhere else does repetition correlate so strongly with socioeconomic status. Disadvantaged students repeat at 46.7% rates—meaning nearly half are held back at least once—while advantaged students proceed normally. Research shows grade repetition harms learning, damages self-esteem, increases dropout risk, and costs enormous amounts—yet Belgium maintains it because cultural beliefs hold that students must "master" content before advancing. In practice, repetition becomes a sorting mechanism: those who repeat (disproportionately poor, immigrant, minority students) are tracked into lower pathways, while those who don't proceed to university. The result is inequality entrenched by age 12.

Early tracking compounds the damage. At age 12, Belgian students choose between academic (general secondary) and vocational pathways. This choice determines futures: academic tracks lead to university; vocational tracks lead to manual work or lower-tier jobs. The choice isn't free—school guidance counselors, influenced by grades (which correlate with socioeconomic status), steer students. Disadvantaged students are funneled into vocational tracks at three times advantaged students' rates, creating socially segregated schools. Vocational schools face concentrated disadvantage, fewer resources, weaker teachers, and worse outcomes. The system sorts children by class and locks them in.

The linguistic division creates three separate systems: Flanders (Dutch-speaking), Wallonia (French-speaking), and bilingual Brussels. Each has different governance, curricula, and resources. Flanders generally performs better and is better funded; Wallonia performs worse and faces higher teacher shortages (2.6% unfilled positions, 12.7% non-fully qualified teachers). Brussels is complex—both communities operate schools, immigrant populations are concentrated, and socioeconomic disadvantage is high. Coordination across communities is minimal, and reforms in one don't transfer to others. This fragmentation prevents national solutions to national problems.

Teacher shortages worsen inequality. Schools in disadvantaged areas struggle most to recruit, face highest turnover, and rely on unqualified or temporary teachers. Students who most need excellent teaching get the worst teachers—a vicious cycle that reproduces inequality. The 2023 expert committee recommended strengthening school leadership, governance, and policy-making capacity, but implementation lags. Teacher salaries are reasonable, but working conditions in high-disadvantage schools are terrible, and talented teachers avoid them.

University quality is strong—KU Leuven, Ghent University, Université Libre de Bruxelles rank internationally—but access is unequal. Students from academic secondary tracks proceed to university; those from vocational tracks don't. The system produces elite graduates who dominate professions while excluding working-class students from higher education pathways. Social mobility is low, and education reinforces class stratification rather than disrupting it.

Belgium needs to abolish or drastically reduce grade repetition, delay tracking until age 16, integrate schools to reduce segregation, equalize resources between communities, and invest in high-disadvantage schools. The linguistic division makes federal reform nearly impossible—Flanders and Wallonia operate independently, and neither prioritizes equity over efficiency. Belgium's elite students excel, but that's not evidence of system success—it's evidence of a system designed to advantage the already advantaged. The 26.5% repetition rate, 46.7% disadvantaged repetition rate, and socially segregated tracking aren't bugs—they're features. Unless Belgium confronts inequality structurally, it will keep producing elite winners and mass losers, sorted by birth. That's not education; it's class reproduction with textbooks.`

// AUSTRIA EDUCATION
const AUSTRIA_EDUCATION = `Austria's education system faces a teacher crisis so severe it's warping outcomes: 4,778 vacancies represent 4.6% of all teaching positions—second only to Sweden in the OECD—and the share of non-fully qualified teachers filling gaps doubled from 2.4% in 2014/15 to 5.7% in 2022/23. Teacher attrition rates nearly doubled from 3.2% to 6.2%, with half leaving voluntarily and 58% of those departing within five years of starting. PISA 2022 results declined, students report teachers as less supportive than peers in other countries, and experts warn that teacher shortages are directly harming learning outcomes. Austria spends adequately (5.1% of GDP), has a well-structured system, and maintains strong universities, but it can't staff classrooms with qualified teachers. The shortages hit disadvantaged schools hardest, compounding inequalities. Early tracking at age 10—into academic Gymnasien or vocational schools—sorts students by class and entrenches advantages. Austria proves that affluent countries with good intentions can fail at education if they don't make teaching attractive, competitive, and sustainable as a profession. The teacher pipeline is broken, and unless Austria fixes it, outcomes will continue declining regardless of curriculum reforms or spending increases.

The teacher shortage is a recruitment and retention crisis. Austria can't attract enough young people into teaching because salaries aren't competitive with other graduate professions, working conditions are difficult, and the profession lacks prestige. Teacher training programs struggle to fill spots, especially in STEM subjects and shortage areas. Those who do enter teaching leave at alarming rates—6.2% attrition means the workforce churns constantly, and institutional knowledge disappears. The 58% of departures happening within five years indicates new teachers find realities worse than expectations: workload is crushing, support is minimal, bureaucracy is stifling, and student behavior is challenging. The non-fully qualified teachers filling gaps (5.7% of the workforce) are Band-Aids on hemorrhages—they keep classrooms covered but can't provide quality instruction. Students who need excellent teaching get the worst teachers, worsening inequality.

Early tracking at age 10 is obscenely young for life-determining decisions. Austrian students are sorted into academic Gymnasien (leading to university) or vocational schools (leading to trades and technical careers). The sorting heavily correlates with parental education and socioeconomic status—middle-class children go to Gymnasien, working-class children to vocational schools. This creates socially segregated pathways where inequality compounds. Vocational schools face concentrated disadvantage, teacher shortages, and limited resources. Academic Gymnasien serve advantaged students with better teachers and resources. Tracking entrenches class advantages by age 10, long before students can make informed choices.

PISA 2022 results show the consequences: performance declined, support for struggling students is inadequate, and inequalities are rising. Austria's PISA scores remain near OECD averages, but trajectories are downward, and the teacher shortage ensures continued decline. Students perceive teachers as less supportive compared to international peers, suggesting workload pressures and demoralization affect classroom culture. The system is failing at the basics: ensuring every student has qualified, supported teachers who can teach effectively.

Infrastructure and resources are generally adequate—Austrian schools aren't crumbling—but human capital is the crisis. Buildings don't teach; teachers do, and Austria doesn't have enough good ones. Higher education quality is strong—University of Vienna, TU Wien, Innsbruck, Graz—and the 2025-2030 National Development Plan for Public Universities aims to strengthen research and teaching. But universities can't succeed if secondary education doesn't prepare students adequately, and secondary education can't succeed without qualified teachers.

What Austria needs is drastic action on teacher recruitment and retention: salary increases making teaching competitive with other professions, workload reductions through smaller class sizes and reduced bureaucracy, better working conditions especially in disadvantaged schools, and prestige campaigns attracting top talent. It needs to delay or abolish tracking to reduce inequality. It needs sustained investment in professional development and induction support for new teachers so they don't leave within five years. The National Development Plan for universities addresses higher education, but the school-level teacher crisis demands equal urgency.

Austria's education system is stuck: early tracking perpetuates inequality, teacher shortages worsen outcomes, attrition rates drain capacity, and PISA results decline. The system works for affluent students in well-staffed Gymnasien; it fails working-class students in under-resourced vocational schools. Unless Austria fixes the teacher pipeline—making teaching attractive, sustainable, and rewarding—no amount of curriculum reform, infrastructure investment, or policy innovation will matter. Teachers are the system's foundation, and Austria's foundation is crumbling. The 4.6% vacancy rate isn't a statistic—it's a crisis that ensures declining outcomes, widening inequality, and wasted potential. Austria needs to treat teacher recruitment and retention as the existential challenge it is, or the education system will keep failing the students who need it most.`

const COUNTRIES = [
  {
    name: 'Belize',
    lat: 17.189877,
    lng: -88.49765,
    summary: BELIZE_EDUCATION,
    chars: BELIZE_EDUCATION.length
  },
  {
    name: 'United Kingdom',
    lat: 55.378051,
    lng: -3.435973,
    summary: UK_EDUCATION,
    chars: UK_EDUCATION.length
  },
  {
    name: 'France',
    lat: 46.227638,
    lng: 2.213749,
    summary: FRANCE_EDUCATION,
    chars: FRANCE_EDUCATION.length
  },
  {
    name: 'Germany',
    lat: 51.165691,
    lng: 10.451526,
    summary: GERMANY_EDUCATION,
    chars: GERMANY_EDUCATION.length
  },
  {
    name: 'Italy',
    lat: 41.87194,
    lng: 12.56738,
    summary: ITALY_EDUCATION,
    chars: ITALY_EDUCATION.length
  },
  {
    name: 'Spain',
    lat: 40.463667,
    lng: -3.74922,
    summary: SPAIN_EDUCATION,
    chars: SPAIN_EDUCATION.length
  },
  {
    name: 'Poland',
    lat: 51.919438,
    lng: 19.145136,
    summary: POLAND_EDUCATION,
    chars: POLAND_EDUCATION.length
  },
  {
    name: 'Ukraine',
    lat: 48.379433,
    lng: 31.16558,
    summary: UKRAINE_EDUCATION,
    chars: UKRAINE_EDUCATION.length
  },
  {
    name: 'Russia',
    lat: 61.52401,
    lng: 105.318756,
    summary: RUSSIA_EDUCATION,
    chars: RUSSIA_EDUCATION.length
  },
  {
    name: 'Turkey',
    lat: 38.963745,
    lng: 35.243322,
    summary: TURKEY_EDUCATION,
    chars: TURKEY_EDUCATION.length
  },
  {
    name: 'Greece',
    lat: 39.074208,
    lng: 21.824312,
    summary: GREECE_EDUCATION,
    chars: GREECE_EDUCATION.length
  },
  {
    name: 'Belgium',
    lat: 50.503887,
    lng: 4.469936,
    summary: BELGIUM_EDUCATION,
    chars: BELGIUM_EDUCATION.length
  },
  {
    name: 'Austria',
    lat: 47.516231,
    lng: 14.550072,
    summary: AUSTRIA_EDUCATION,
    chars: AUSTRIA_EDUCATION.length
  }
]

async function addEducationSummaries() {
  console.log('Adding education summaries for 13 countries (Batch 3)...\n')

  for (const country of COUNTRIES) {
    try {
      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: country.name,
            type: 'country',
            category: 'education'
          }
        },
        create: {
          name: country.name,
          type: 'country',
          country: country.name,
          lat: country.lat,
          lng: country.lng,
          category: 'education',
          summary: country.summary,
          issues: JSON.stringify([]),
          topStories: JSON.stringify([]),
          storyCount: 0,
          updatedAt: new Date()
        },
        update: {
          summary: country.summary,
          updatedAt: new Date()
        }
      })
      console.log(`✅ ${country.name} education summary saved (${country.chars} characters)`)
    } catch (error) {
      console.error(`❌ Error saving ${country.name}:`, error)
    }
  }

  console.log('\n✅ ALL 13 EDUCATION SUMMARIES COMPLETED!')
  console.log('\n📊 CHARACTER COUNTS:')
  COUNTRIES.forEach(c => {
    console.log(`   ${c.name}: ${c.chars} characters`)
  })
  console.log(`\n🎉 BATCH 3 COMPLETE!`)
}

addEducationSummaries()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
