import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// TANZANIA HEALTHCARE
const TANZANIA_HEALTHCARE = `The question in Tanzania isn't whether universal health insurance will work—it's whether the system can handle it. The Universal Health Insurance Act passed in 2023, mandating coverage for all 65 million Tanzanians by 2025. Life expectancy climbed from 61 to 66 years in twelve years, child mortality dropped, and the government talks confidently about "health service delivery that meets citizens' needs." But here's what the Ministry of Health won't tell you at the Tanzania Health Summit: only 40% of rural facilities have essential supplies, healthcare spending sits at $51 per capita (WHO recommends at least $86), and the system needs 81% more funding just for human resources and infrastructure by 2025. You can legislate insurance, but you can't legislate doctors, medicines, or functioning clinics. Tanzania is attempting the hardest thing in global health—bringing 65 million people into a system that barely serves 30 million—and doing it without the money, staff, or infrastructure to make it real.

The structural challenge is arithmetic. Healthcare costs must rise from 3.7 trillion shillings in 2021 to 6 trillion in 2025—a 62% increase in four years—with the largest gaps in human resources and infrastructure. Tanzania has made progress: decentralization brought services closer to communities, payment-for-performance incentivized quality, and the government hired thousands of healthcare professionals for primary care. But the distribution is brutal. Urban hospitals in Dar es Salaam have specialists, equipment, diagnostic capacity; rural clinics in Mtwara have nurses, maybe a clinical officer, intermittent electricity, and drug shortages that last weeks. The insurance mandate covers everyone on paper, but coverage without access is a political promise, not a health system. Maternal mortality remains high despite facility births increasing, because facilities lack blood banks, cesarean capacity, or reliable referral systems. Infectious disease burden—HIV, TB, malaria—still drives mortality, but non-communicable diseases are rising faster than the system can adapt.

Wait times depend entirely on where you live and what you have. Urban facilities see queues of hundreds; patients arrive at dawn, wait six hours, maybe see someone. Rural areas have a different problem: no wait times because there's no one to wait for. The doctor visits monthly, the drugs ran out last week, and the ambulance hasn't worked since 2019. The Universal Health Insurance Act attempts to solve the financing problem, but financing doesn't create doctors, and Tanzania's medical schools graduate 400 physicians annually for a population of 65 million. Nurses and clinical officers shoulder the load, but they're overwhelmed, underpaid, and leaving for private clinics or emigrating. The government's strategy emphasizes primary healthcare strengthening, which is correct in principle but requires the unsexy work of supply chains, supervision systems, and reliable salaries—exactly the things that don't happen when 5.6% of GDP funds the entire health system.

The path forward exists but requires honesty about scale. Universal health insurance creates demand; Tanzania must simultaneously build supply. That means training and retaining thousands more health workers, ensuring rural facilities have electricity and water before worrying about CT scanners, and fixing pharmaceutical supply chains so essential drugs don't vanish for months. The government has prioritized medical supplies and primary care hiring, which shows understanding of the crisis. But execution stumbles on corruption, bureaucracy, and insufficient budget. Tanzania's health system isn't failing—it's succeeding at a level far below what's needed. Life expectancy gains prove interventions work; the insurance mandate shows political will exists. The question is whether Tanzania can build a health system as fast as it's expanding health coverage. Right now, the gap is widening, and 65 million people are depending on a system that isn't ready for them.`

// UGANDA HEALTHCARE
const UGANDA_HEALTHCARE = `Uganda just declared victory over its 2025 Ebola outbreak, and that's the good news. The bad news is everything else. The U.S. contributed $8 million to contain the outbreak—funding surveillance, contact tracing, lab diagnostics, infection control—and Uganda's public health infrastructure, strengthened over years of donor investment, detected cases within hours instead of weeks. But here's what didn't make the press release: maternal mortality sits at 336 deaths per 100,000 live births, less than 2% of the population has financial risk protection for health costs, and total health expenditure is $48 per capita—one-third of what's needed to deliver basic services. Uganda excels at epidemic response because that's where the money and attention flow. Routine healthcare—the pregnant woman who bleeds out because there's no blood bank, the diabetic who can't afford insulin, the child with pneumonia whose clinic has no oxygen—that's where the system collapses daily, quietly, and lethally.

The mathematics of Ugandan healthcare are unforgiving. Health spending is 6.4% of GDP, which sounds reasonable until you see that out-of-pocket payments comprise 40% of total health expenditure. That means families pay when they're sickest and poorest, which is why medical costs drive poverty and people avoid care until conditions become emergencies. The government shifted priorities in 2010 from social sector investment toward infrastructure development—roads, dams, power—and health services deteriorated accordingly. Clinics ran out of essential medicines, health workers went unpaid for months, and the system that had made impressive gains on HIV, malaria, and child mortality stagnated. Universal health coverage is official policy, but only 15% of Ugandans have medical aid coverage, and the National Health Insurance Scheme enrollment is advancing glacially because premiums are unaffordable for subsistence farmers who comprise most of the population.

What kills Ugandans isn't mysterious. Maternal mortality should be far lower given that facility births have increased, but facilities lack skilled attendants, blood products, and surgical capacity for emergencies. During COVID-19, health facility births dropped and maternal deaths spiked—not because of the virus, but because pregnant women avoided clinics fearing infection. The system recovered to pre-pandemic levels, but "pre-pandemic" means 336 women dying per 100,000 births, which is unconscionable. Malaria, HIV, TB, and respiratory infections still dominate, but non-communicable diseases are rising and the system has no capacity for chronic care management. Diabetes, hypertension, cancer—these require functional supply chains for medications, trained providers, and long-term follow-up, which are exactly what Uganda's system can't provide outside Kampala's referral hospitals.

Infrastructure is the unsexy determinant of health outcomes. Labs with quality assurance reduce diagnostic errors and treatment delays; U.S. government investment in laboratory systems has been transformative for Uganda's epidemic preparedness. But most rural clinics lack electricity, running water, or reliable drug supplies. Health workers are scarce, maldistributed, and demoralized—why stay in a village with no equipment, no drugs, and irregular pay when Kampala hospitals or NGOs pay triple? The government knows the problems: the Abuja Declaration calls for 15% of GDP to go to health; Uganda spends less than half that. Free primary healthcare exists in theory, but "capacity constraints" mean services don't reach those who need them most.

Uganda's health system isn't broken—it's functioning exactly as a chronically underfunded system functions. Epidemic response works because donors fund it, routine care fails because it's neglected. The fix requires doubling health spending, hiring and retaining thousands more health workers, ensuring rural facilities have basics before advanced care, and implementing financial risk protection so illness doesn't bankrupt families. Uganda has built strong public health infrastructure for outbreaks; now it needs to build the boring, essential infrastructure for everyday health. Ebola makes headlines, maternal mortality doesn't—but the latter kills far more Ugandans, and fixing it requires the political will to fund health systems, not just emergency responses.`

// ZIMBABWE HEALTHCARE
const ZIMBABWE_HEALTHCARE = `The mammography machine at Parirenyatwa Hospital has been broken for fifteen years. Fifteen years of women with breast lumps unable to get timely diagnoses, fifteen years of cancers detected late, fifteen years of a major referral hospital unable to perform a basic diagnostic procedure. That's Zimbabwe's healthcare crisis in one detail: the system isn't collapsing, it already collapsed. The country has 3,500 doctors for 16 million people—a ratio of 0.91 per 1,000, half the global average. Between June 2023 and June 2024, 35,938 Zimbabweans got UK work visas, most as healthcare workers, because nurses earn $250 monthly in Harare and $2,500 in Manchester. WHO added Zimbabwe to the "red list" of countries facing critical health worker shortages. The brain drain isn't slowing; it's accelerating. Half of urban health workers surveyed intend to migrate. This isn't about individuals seeking better lives—it's a systems failure where the healthcare workforce has decided there's no future in staying.

What remains is a skeleton system. In 2022, Zimbabwe reported 1,724 doctors and 17,245 nurses employed in public hospitals—nowhere near WHO's recommended standards for a population this size. Rural areas suffer most: hospitals lack doctors entirely, nurses cover wards meant for teams, and essential supplies vanish for weeks. Infrastructure is crumbling—facilities lack functional water supply, reliable electricity, adequate sanitation. Outdated equipment sits unused, drugs are perpetually short, and basic consumables are privileges, not guarantees. Urban hospitals fare marginally better, but only marginally. The brain drain creates cascading gaps: specialized services disappear when surgeons leave, diagnostic capacity shrinks when lab technicians emigrate, maternal care suffers when midwives flee. Remote areas already struggling now have no coverage at all.

The salary structure is absurd. Doctors average $450 monthly, nurses $250—barely survival wages in an economy with hyperinflation history and currency instability. Even junior healthcare workers in the UK earn five times what experienced Zimbabwean specialists make. Why stay? The government has no answer, and health workers vote with their feet. Those who remain are demoralized, overworked, and often moonlight in private clinics just to pay rent. The 2022 coup installed a new government that promised reforms, but healthcare spending remains inadequate, salaries stagnant, and infrastructure neglected. The public system serves those who can't afford private care—meaning the poor, rural, and desperate receive the worst care from an exhausted workforce with no resources.

Wait times are meaningless when there's no one to wait for. Urban hospitals see queues of hundreds; patients arrive predawn, wait all day, maybe see someone. Rural areas simply lack providers—the clinic is empty, the nurse visits weekly, the doctor quit months ago. Maternal mortality is rising, child mortality remains high, and infectious diseases like HIV and TB overwhelm the gutted system. Non-communicable diseases—diabetes, hypertension, cancer—are death sentences outside Harare and Bulawayo because management requires consistent medication, lab monitoring, and specialist input, none of which exist in the public system.

The tragedy is that this was preventable. Zimbabwe once had a functional health system, trained workforce, and decent infrastructure. Decades of economic mismanagement, corruption, and political instability destroyed it. Rebuilding requires tripling health spending, paying healthcare workers competitive salaries, fixing infrastructure, ensuring drug supplies—and none of that happens without economic recovery and political will. The brain drain reflects a deeper crisis: Zimbabwe's healthcare workforce has concluded the system is unsalvageable and their futures lie elsewhere. Until the government treats healthcare as a priority rather than a budget afterthought, the exodus continues, and the mammography machine stays broken. Fifteen years and counting.`

// CAMEROON HEALTHCARE
const CAMEROON_HEALTHCARE = `Cameroon introduced Africa's first malaria vaccine in January 2024, achieving 47% coverage by December—a genuine public health achievement in a country where malaria is the leading killer despite free treatment for under-fives since 2011. Meanwhile, 95% of HIV patients receive treatment at PEPFAR-supported sites, infant HIV transmission dropped from 3.22% to 1.78% in one year, and CDC helped establish Central Africa's first ISO-accredited laboratory and internationally certified blood bank. These are real gains. But they coexist with brutal disparities: urban-rural healthcare inequality is vast, infrastructure is inadequate, the workforce is insufficient, and funding chronically short. Over 500,000 Cameroonians live with HIV, malaria still kills thousands, and maternal mortality remains high. Cameroon's healthcare system is a study in contrasts—targeted programs showing what's possible, structural weaknesses revealing what's failing.

The infrastructure tells the story. CDC supports clinical services in 340+ facilities across all ten regions, five laboratories achieved ISO 15189 accreditation, and health systems strengthening has built epidemiology, surveillance, lab, and research capacity. These successes are real but narrow: they concentrate in HIV/TB programs, malaria control, and epidemic preparedness—the areas with donor funding. Outside those verticals, the system struggles. Rural areas lack basic health facilities, urban hospitals are overcrowded and under-resourced, and the Anglophone regions—where separatist conflict has killed 6,000 since 2016—have seen healthcare collapse entirely. Hospitals attacked, health workers fled or killed, supply chains severed. The government controls urban centers, but countryside populations have no access to care at all.

The workforce shortage is severe. Cameroon lacks enough doctors, nurses, midwives, and specialists to cover 28 million people, and those who exist cluster in cities, leaving rural areas underserved. Health worker training pipelines are inadequate, salaries low, and working conditions poor—leading to emigration or concentration in private urban clinics that serve the wealthy. Maternal mortality persists because facilities lack skilled birth attendants, emergency obstetric care, blood banks, and referral systems. A woman in Yaoundé with pregnancy complications has a chance; one in a village in the North-West has almost none. The same applies to chronic diseases—diabetes, hypertension, cancer—which require consistent medication, monitoring, and specialist input available only in major cities.

Wait times vary radically. In urban hospitals, patients queue for hours, sometimes overnight, for services that may or may not be available depending on whether drugs arrived this month. Rural areas have different problems: clinics exist on paper but are staffed intermittently, if at all, and drugs run out for weeks. The conflict zones have no functioning system—displaced populations rely on humanitarian organizations when accessible, and die when not.

Cameroon's healthcare paradoxes reflect its governance crisis. The country can implement malaria vaccine rollout (with Gavi support) but can't ensure rural clinics have basic antibiotics. It can achieve 95% PEPFAR coverage for HIV but can't pay health workers in conflict zones. The system functions where donor funding and political priorities align—epidemic control, vertical disease programs, urban centers. Everywhere else, it's improvisation and neglect. Paul Biya is 92, consumed by political survival after a disputed October 2025 election, and healthcare reform is invisible on his agenda. The infrastructure needed—universal health coverage, rural facility expansion, workforce training and retention, supply chain reliability—requires sustained investment and competent governance, both absent. Cameroon's healthcare system succeeds in narrow verticals and fails everywhere else. That's not good enough for 28 million people.`

// ZAMBIA HEALTHCARE
const ZAMBIA_HEALTHCARE = `Life expectancy in Zambia rose 16.5 years in two decades—from 44.5 years in 2000 to 61 in 2021—which is an extraordinary achievement reflecting progress on HIV, malaria, child mortality, and facility births. The government offers free basic healthcare at primary level through the National Health Care Package, and since 2017 has expanded the National Health Insurance Scheme toward universal coverage. These are real gains. But only 15% of Zambians have medical aid, out-of-pocket spending remains high, and government health spending is chronically low—leading to perpetual drug shortages, long waits, and crumbling infrastructure. The Chimwemwe Hospital, an 80-bed facility budgeted at $25 million, has been 80% structurally complete since May 2023—meaning it's still not functioning. Zambia has built a healthcare system that keeps people alive longer but can't meet demand, maintain quality, or protect families from financial catastrophe when illness strikes.

The infrastructure challenge is everywhere. Facilities lack essential drugs, medical supplies, and equipment. Low government spending means shortages aren't exceptional—they're routine. Clinics run out of antimalarials during malaria season, antiretrovirals for HIV patients arrive late, and basic surgical supplies are unreliable. The healthcare workforce is insufficient and maldistributed—urban hospitals have too many patients per provider, rural areas have too few providers period. The system struggles with the basics: electricity, water, sanitation, cold chain for vaccines. Construction projects like Chimwemwe drag on for years, showing the government's limited capacity to execute infrastructure plans even when funded. Zambia's Multisectoral Cholera Elimination Plan aimed to eliminate cholera by 2025, but rainy seasons still bring outbreaks because water, sanitation, and housing conditions haven't improved enough.

Universal health coverage is official policy, but implementation stumbles. The National Health Insurance Scheme theoretically facilitates access to quality services, but only 15% enrollment means the vast majority still pay out-of-pocket or go without. Premiums are unaffordable for most Zambians, and the insurance scheme struggles with provider payment delays, limited benefit packages, and bureaucratic inefficiency. Free primary care exists in theory, but "capacity constraints" mean services are rationed by queue length, drug availability, and whether staff showed up. The poorest—who most need the National Health Care Package—often don't receive it because facilities in their areas lack supplies, personnel, or functioning infrastructure.

Wait times are punishing. Patients arrive hours before dawn, wait through the day, and might see a nurse or clinical officer (rarely a doctor) for a few minutes. Urban facilities are overwhelmed; rural facilities are understaffed or unstaffed. Maternal mortality has dropped but remains too high—facility births increased but many facilities lack skilled attendants, blood products, or cesarean capacity for emergencies. Malaria, HIV, TB, and diarrheal diseases still drive mortality, and non-communicable diseases are rising faster than the system can adapt. Diabetes and hypertension require chronic care management—consistent medication, monitoring, lifestyle support—which Zambia's overstretched system can't provide outside tertiary hospitals.

Zambia's healthcare progress is undeniable: 16.5 years of life expectancy gains don't happen by accident. HIV treatment scale-up, malaria control, expanded immunization, and increased facility births all worked. The National Health Insurance Scheme and free primary care show political commitment to universal health coverage. But commitment without funding is aspiration, not reality. Zambia needs to triple enrollment in the insurance scheme, double health worker training and hiring, fix supply chains so drugs don't vanish, and complete infrastructure projects on time. The government knows this—policy documents say all the right things. Execution is the problem. Corruption, inefficiency, and insufficient budgets mean plans stall, facilities decay, and health workers leave. Zambia has proven it can improve health outcomes dramatically; now it must prove it can build and sustain a system that serves everyone, not just those lucky enough to live near a functioning facility.`

// MALI HEALTHCARE
const MALI_HEALTHCARE = `Mali has one of the world's lowest health worker densities, and that statistic explains almost everything else. More than 85% of the population lives over five kilometers from the nearest health facility—which, even when reachable, often lacks trained staff, essential drugs, and basic infrastructure. Malaria is the leading cause of death, especially in children under five, and hard-to-reach communities are seeing rising rates of severe malaria and preventable diseases due to collapsed healthcare access. Then in 2025, USAID cut funding, and patients who had relied on free malaria medication at health centers found it was no longer available. This is healthcare in Mali: underfunded, understaffed, under-equipped, and now losing the external support that was barely keeping it functional. Violence and unrest have left entire regions without adequate health workers to reduce maternal and child mortality or respond to infectious diseases. Mali's health system isn't in crisis—it's the crisis.

Infrastructure is dismal. Most facilities have dilapidated buildings and equipment, making even standard procedures risky. Difficulty obtaining medical supplies means clinics routinely run out of essential drugs, vaccines, and consumables. The 2023 catastrophic harvest and escalating armed conflict exacerbated food insecurity, which compounds malnutrition and disease vulnerability, especially in Northern and Central Mali. Health facilities exist on paper but are often inaccessible—either geographically (no roads, insecurity) or functionally (no staff, no supplies). The few health workers who remain are poorly supported: irregular pay, no supplies, no supervision, no opportunities for training or advancement. Why stay in a village clinic with nothing when you could work for an NGO in Bamako or emigrate?

The impact on health outcomes is catastrophic. Maternal mortality remains extremely high because women can't reach facilities, and when they do, facilities lack skilled birth attendants, blood products, or emergency obstetric surgery capacity. Child mortality is among the world's highest—malaria, pneumonia, diarrhea, malnutrition kill thousands annually, all preventable or treatable with basic interventions that Mali's system can't reliably deliver. Infectious disease control is failing: malaria is spreading, TB treatment is inconsistent, HIV services are sparse, and epidemic preparedness is minimal. The armed conflict has displaced populations, destroyed health facilities, and made humanitarian access nearly impossible in large areas. Aid organizations try to fill gaps, but insecurity, bureaucratic obstacles, and funding cuts limit their reach.

Wait times are the least of the problems. In areas where facilities function at all, patients wait hours or days, but the real barrier is distance and danger—traveling to a clinic might mean walking for hours or crossing conflict zones. In much of the country, there's no healthcare to access at all. Rural populations rely on traditional healers, self-medication, and luck. The USAID funding cuts in 2025 hit hard: programs providing free malaria drugs, maternal health services, and child immunizations are scaling back or closing. Donors are exhausted, the government is broke, and the military junta prioritizes security (unsuccessfully) over social services.

Mali's healthcare system reflects its state collapse. The government controls Bamako and some regional capitals; beyond that, authority is contested or absent. Healthcare workers have fled violence, facilities have been looted or destroyed, and supply chains are severed. Rebuilding requires security, which doesn't exist; funding, which is declining; and political will, which is focused elsewhere. Mali needs thousands more health workers, rebuilt infrastructure, reliable supply chains, and functioning referral systems—all impossible without peace and investment. International support is waning as the junta alienates Western donors and pivots toward Russia, which offers military support but not health systems strengthening. The humanitarian crisis deepens, malnutrition rises, and diseases spread. Mali's health system is failing because Mali as a functional state is failing. Without security and governance, healthcare improvements are impossible, and millions suffer accordingly.`

// NIGER HEALTHCARE
const NIGER_HEALTHCARE = `One in 187 women in Niger dies during pregnancy, childbirth, or postpartum—a maternal mortality ratio that declined from 709 to 520 per 100,000 births between 2000-2011 but has stagnated since. Less than half of mothers and children live close to a health facility, and less than one-fifth of emergency maternal and neonatal care needs are covered. The child malnutrition crisis is severe despite some progress: stunting fell from 52.1% in 2000 to 46.7% in 2020, but nearly half of all children remain chronically malnourished. Wasting dropped from 16.2% to 9.8% over two decades—a real gain—but almost one in ten children is acutely malnourished, and anemia in pregnancy affects 59% of women. These numbers describe a health system failing at the most basic functions: keeping mothers alive during childbirth and children nourished in their first years. Niger has the world's highest fertility rate, a population doubling every generation, and a healthcare system that can't remotely meet the need.

The structural barriers are overwhelming. Health workforce and infrastructure are insufficient and inequitably distributed—cities have hospitals, rural areas have little. Insecurity has plagued the country for over a decade, disrupting services, displacing populations, and making large areas inaccessible to health workers and aid organizations. High fertility compounds every challenge: more pregnancies mean more maternal deaths in absolute terms, more childbirths strain a system without enough midwives or functioning delivery wards, more infants need nutrition and immunization programs that don't exist in most villages. Cultural barriers prevent care-seeking—women need male relatives' permission to travel to facilities, traditional practices dominate over biomedical care, and facility births are low especially in rural areas.

Infrastructure is scarce and concentrated. Health facilities exist mainly in towns; rural populations must travel hours over poor roads or paths to reach care. Even when reachable, facilities lack skilled attendants, drugs, equipment, and referral capacity for emergencies. Maternal mortality is high because complications—hemorrhage, obstructed labor, sepsis—require immediate skilled intervention, blood products, and surgical capacity that almost no rural facility has. Emergency obstetric care coverage is below 20%, meaning four in five obstetric emergencies are handled without adequate resources or personnel. That's why women die. Child malnutrition is similarly structural: families lack food security, clean water, sanitation, and healthcare access. Children experience repeated infections—diarrhea, pneumonia, malaria—which cause wasting, and chronic food insufficiency causes stunting. Anemia in pregnancy reflects poor maternal nutrition and malaria burden.

Wait times are irrelevant when facilities don't exist or are unreachable. For those who can access care, waits are long, quality is poor, and costs—though theoretically subsidized—are often prohibitive. Traditional birth attendants deliver most births because facilities are too far, too expensive, or too poorly regarded. Healthcare workers are scarce: Niger has among the world's lowest health worker densities, and those trained often leave for cities or neighboring countries. Training pipelines are inadequate, retention is terrible, and supervision is minimal. The health workforce that remains is overwhelmed, unsupported, and unable to change outcomes at the scale required.

Niger's health crisis is a crisis of state capacity. The government cannot provide basic services to a rapidly growing population spread across a vast, arid territory. Insecurity limits access to the north and border areas. Poverty means families can't afford care even when available. Donor funding helps—UNICEF, WHO, USAID support nutrition, maternal health, immunization programs—but fills gaps rather than building systems. Niger needs massive health workforce expansion, infrastructure construction, supply chain reliability, and sustained funding for programs that keep mothers and children alive. It also needs security, economic development, and lower fertility—all beyond the health sector's control. Progress is possible: malnutrition rates have declined, facility births are gradually rising, and maternal mortality did drop for a decade. But "progress" at this pace means millions more children stunted, hundreds of thousands of maternal deaths, and generations damaged by preventable conditions. Niger's health system isn't collapsing—it never reached the level required to serve its population. Building it from scratch while the population doubles is the challenge, and right now, Niger is losing.`

// CHAD HEALTHCARE
const CHAD_HEALTHCARE = `Chad has the world's second-highest maternal mortality rate: 1,140 deaths per 100,000 live births—one of every 88 women will die from pregnancy-related causes. Life expectancy is 55.4 years, nearly nine years below the global average and below even Africa's 64.2-year average. Only 34% of births are assisted by qualified personnel. Nearly half of Chad's skilled health workforce is in N'Djamena, serving less than 10% of the population. Chad has 79.1% fewer physicians and 84.3% fewer nurses and midwives than average African nations. Women often walk several hours to reach a health center—and when they arrive, there's limited staff, medicines, and equipment. This is what health system failure looks like: not an absence of facilities, but an absence of capacity so profound that pregnancy is a mortal risk, basic infectious diseases kill routinely, and life expectancy is a decade shorter than it should be.

The maternal mortality crisis alone reveals the system's incapacity. The rate has barely budged in two decades—modest reductions compared to low-income countries generally, which halved their MMR to 409 per 100,000 by 2020. Chad remains stuck at 1,140. Why? Inadequate national health financing, weak infrastructure, insufficient and inequitably distributed workforce, lack of coordination, and underreporting of deaths—which means the real number is likely higher. Most women deliver at home without skilled attendants because facilities are too far, too expensive, or too poorly equipped to help. When complications occur—hemorrhage, obstructed labor, eclampsia—women die because there's no blood bank, no cesarean capacity, no transport. The few functioning facilities are overwhelmed, understaffed, and lack supplies. Maternal death audits and response systems barely exist, so the system doesn't learn from failures.

Workforce scarcity drives every other failure. Chad has too few doctors, nurses, midwives, and clinical officers—and those who exist cluster in the capital, leaving rural areas with almost no coverage. Women walk hours to health centers staffed by undertrained community health workers with no drugs, no equipment, and no referral options. Medical and nursing schools graduate too few providers, retention is abysmal, salaries are low and irregular, and working conditions are dire. Why stay in a rural clinic with nothing when you could work in N'Djamena or emigrate? The health workforce shortage isn't just numbers—it's catastrophic maldistribution. The capital has doctors; villages have no one.

Infrastructure is non-existent or collapsed across much of the country. Health centers lack electricity, running water, cold chain for vaccines, and basic medical equipment. Drug supply chains are unreliable—facilities run out of antimalarials, antibiotics, and oxytocin. Labs are rare and poorly equipped, making diagnostics guesswork. Referral systems don't function: ambulances don't exist, roads are impassable, and higher-level facilities are too far or too full. The few hospitals in regional centers are overwhelmed, under-resourced, and unable to provide emergency obstetric, surgical, or critical care. Coordination within the health system is minimal—national policies don't translate to local implementation, data is poor, and accountability is absent.

Chad's health system is what happens when a state has no capacity and no resources. Health financing is grossly inadequate—Chad spends far below even low-income averages, and most spending is out-of-pocket, pushing families into poverty. Donor funding helps, but it's fragmented, project-based, and doesn't build systems. Chad needs to quintuple health spending, train and deploy thousands of health workers, build infrastructure in rural areas, ensure supply chains function, and create referral systems that transport women with complications to facilities that can help. None of that happens without security, governance, and economic growth—all absent. Chad's conflicts, food insecurity, and extreme poverty make health system strengthening nearly impossible. Women will keep dying in childbirth, children will keep dying from preventable diseases, and life expectancy will stay ten years shorter than it should be. Chad's health crisis is a governance crisis, and there's no fix without addressing the underlying state failure.`

// BURKINA FASO HEALTHCARE
const BURKINA_HEALTHCARE = `Nearly one-third of Burkina Faso's health facilities are affected by the crisis—17.7% completely closed—and six million people urgently need healthcare, two million critically. In 2023, violence doubled from 2022 levels, killing over 8,400 people. Jihadist insurgency controls vast territory, health facilities are attacked, healthcare workers flee or are killed, and supply chains are severed. The facilities that remain—58% were reopened in 2024, up from 37% in 2023—are overwhelmed, under-resourced, and operating in active conflict zones. Maternal mortality is 320 per 100,000 births, and pregnant women face unsafe delivery conditions because clinics lack skilled attendants, drugs, or referral capacity. Children miss vaccinations, chronic illness patients experience treatment interruptions, and displaced populations—over two million people—have almost no healthcare access at all. Burkina Faso has 10 physicians per 100,000 people, 41 nurses, and 13 midwives—nowhere near what's needed even in peacetime. This is healthcare under siege, and the system is losing.

The government approved a $299.5 million plan to expand primary healthcare—20 new community medical centers, nine regional ambulance branches, strengthened blood transfusion systems across seven regions—but implementation amid insurgency is nearly impossible. The plan targets structural challenges: inadequate workforce, unequal access, limited rural infrastructure. But planning doesn't stop attacks, and facilities can't function when health workers have fled and supply routes are controlled by militants. The reopening of facilities from 37% to 58% shows resilience, but it also means 42% remain closed, and many "open" facilities function minimally—no drugs, no staff, intermittent hours. Maternal health, child immunization, chronic disease management, and infectious disease control all require reliable access, consistent staffing, and supply chains. Burkina Faso has none of these.

Healthcare workforce crisis predates the conflict but has been catastrophically worsened by it. The country had critical shortages before insurgents started killing or displacing health workers. Now, no new community health volunteers were recruited in 2024 despite a target of 500. Trained personnel fled conflict zones, leaving rural areas unserved. Urban facilities are overwhelmed by displaced populations and referrals from closed rural clinics. The workforce that remains is traumatized, exhausted, and working without supplies, security, or support. Maternal mortality reflects this: women can't reach facilities, and when they do, facilities lack skilled attendants or capacity for emergency obstetric care. Child malnutrition and vaccine-preventable diseases are rising because routine services collapsed.

Insecurity makes healthcare logistics impossible. Drug supply chains require transport through insurgent-controlled areas, which is dangerous and often impossible. Humanitarian organizations try to reach affected populations but face attacks, bureaucratic obstacles, and funding shortfalls. Health workers in conflict zones face impossible choices: stay and risk death, or flee and leave populations without care. Many have fled. The government's $299.5 million plan is ambitious, but executing infrastructure projects in active war zones is unrealistic. Ambulance services, blood banks, and community medical centers require security, which doesn't exist in 30% of the national territory.

Burkina Faso's healthcare crisis is inseparable from its state collapse. The military junta extended its rule to 2029, prioritizes security (unsuccessfully), and can't govern territory outside major cities. Healthcare requires functioning states—supply chains, trained workforces, infrastructure, supervision systems. Burkina Faso has fragments of these, mostly in areas the government still controls. Elsewhere, populations rely on humanitarian organizations if accessible, and nothing if not. The maternal mortality rate, workforce shortages, facility closures, and infectious disease spread all worsen as the conflict drags on. Reopening facilities is progress, but 58% functionality in a warzone still means millions lack care. Burkina Faso needs peace before it can rebuild its health system, and peace isn't coming. Until then, pregnant women deliver without help, children die from preventable diseases, and displaced populations suffer without access to even basic care.`

// RWANDA HEALTHCARE
const RWANDA_HEALTHCARE = `Rwanda's community-based health insurance—Mutuelle de Santé—covers 83.5% of the population, accounting for over 90% of all insured individuals, and has helped raise life expectancy from 49.7 years in 2001 to 69.6 in 2022—a 20-year leap in life expectancy in just two decades. There are 58,286 community health workers serving 14,837 villages, providing primary care and making referrals up the system. The poorest citizens get free coverage, the wealthiest pay $8 per adult annually, and the middle tiers pay on a sliding scale. The model empowers everyone, as Rwandans say—it's a national pride. Insurance enrollment is high because community health workers educated villagers about benefits, because premiums are affordable, and because the system actually delivers care. This is the success story: Rwanda built near-universal health coverage in one of the world's poorest countries, and it works. But now the system faces new challenges—expanding coverage to include specialized treatments like elephantiasis, managing the shift from infectious to non-communicable diseases, and sustaining the model as expectations and costs rise.

The architecture is elegant. Community health workers form the foundation, treating minor illnesses and referring upward to health posts, then health centers, then district hospitals, and finally referral hospitals. CBHI reduces financial barriers—premiums are low, and co-payments are minimal—so families seek care earlier, preventing minor conditions from becoming emergencies. The result: maternal mortality dropped, child mortality plummeted, malaria and HIV treatment reached nearly universal coverage, and life expectancy surged. Insurance alone doesn't do this—the system works because facilities are staffed, stocked with drugs, and accessible. Rwanda invested in health infrastructure, trained thousands of community health workers, and ensured supply chains functioned. The government political commitment was total: universal health coverage wasn't rhetoric, it was policy enforced and funded.

But success creates new demands. Dr. Alexis Rulisa, Director of CBHI, is expanding coverage by 2025 to include specialized treatments not previously covered—complex conditions requiring referrals, advanced diagnostics, or prolonged care. This is the right move, but it strains the system. Rwanda's disease burden is shifting: infectious diseases still matter, but non-communicable diseases—diabetes, hypertension, cancer, respiratory conditions—are rising. These require chronic care management: consistent medication, monitoring, lifestyle interventions, and specialist input. The community health worker model excels at acute care and referrals but isn't designed for chronic disease management. Rwanda must adapt the system without losing what works.

Infrastructure gaps remain. Urban areas have hospitals with reasonable diagnostic and surgical capacity; rural areas rely on health centers that lack specialists, advanced diagnostics, or intensive care. Referral systems work but are strained—district hospitals are often overcrowded, and referral hospitals in Kigali face long waits. The health workforce is better distributed than most African countries, but specialists are scarce, and training pipelines struggle to keep pace with demand. Drugs and supplies are reliable by regional standards, but shortages still occur, especially for newer or expensive medications needed for non-communicable disease management.

Rwanda proves universal health coverage is possible even in low-income settings if governments prioritize it, design systems intelligently, and execute with discipline. CBHI works because premiums are affordable, benefits are real, and facilities function. Community health workers make the model sustainable by extending reach without overwhelming hospitals. But the system's success raises expectations—patients want coverage for more conditions, access to specialists, advanced treatments. Costs will rise as the population ages and non-communicable diseases increase. Rwanda's challenge is sustaining and expanding coverage without losing financial sustainability or quality. The government is expanding benefits in 2025, which shows continued commitment. The question is whether Rwanda can manage the epidemiological transition—from infectious to chronic diseases—while maintaining the community-based, insurance-financed model that delivered 20 years of life expectancy gains. Right now, Rwanda is the model others should study. Whether it remains so depends on navigating the next phase without breaking what works.`

// BOTSWANA HEALTHCARE
const BOTSWANA_HEALTHCARE = `Botswana has diamonds and democratic transitions, but its healthcare system is stuck in middle-income limbo—good enough to achieve progress, not good enough to meet expectations. Life expectancy climbed from catastrophic lows during the HIV epidemic to 69 years in 2023, which is a triumph of antiretroviral therapy scale-up and political will. Botswana achieved one of the world's fastest HIV treatment expansions, bringing prevalence down and keeping people alive. But the system remains overly dependent on donor funding, especially PEPFAR, and is now managing a dual disease burden: HIV, TB, and malaria still require attention, but non-communicable diseases—diabetes, hypertension, cardiovascular disease, cancer—are rising fast. Healthcare infrastructure exists but is aging, unevenly distributed, and strained. The new government under Duma Boko promises universal health coverage and increased social spending, but Botswana's fiscal space is tight as diamond revenues collapse. Healthcare progress is real, but so are the limits.

The HIV story is remarkable. At the epidemic's peak, Botswana had one of the world's highest HIV prevalence rates, and life expectancy plummeted below 50 years. The government, with PEPFAR and donor support, rolled out free antiretroviral therapy nationwide, achieving near-universal treatment coverage. Life expectancy rebounded to 69 years—a 20+ year gain in two decades. Botswana's HIV program is a model: widespread testing, treatment, and prevention services, supported by functional supply chains and trained health workers. But donor dependency is a vulnerability—PEPFAR funding props up the system, and if it declines, sustainability is uncertain. The government must transition to domestic financing while maintaining coverage, which is difficult as other demands rise.

The dual burden is the next challenge. HIV and TB still require ongoing management, and malaria remains endemic in northern regions. But non-communicable diseases now drive increasing mortality: diabetes, hypertension, cardiovascular disease, respiratory conditions, and cancer. These require different health system capacities—chronic care management, specialist services, diagnostic imaging, long-term medication adherence, and behavioral interventions. Botswana's system is organized around infectious disease control, and shifting focus is hard. Urban hospitals in Gaborone and Francistown have capacity; rural clinics don't. Access to specialists, advanced diagnostics, and cancer treatment is limited outside cities, and screening programs for hypertension, diabetes, and cervical cancer are inconsistent.

Infrastructure is functional but uneven. Public hospitals and clinics exist nationwide, staffed by trained health workers and generally stocked with essential medicines. Wait times are long—patients queue for hours, especially at urban facilities—but care is accessible and mostly free at point of service. The private sector serves those with insurance or cash, offering faster access and better amenities but covering a minority of the population. Rural areas have clinics but lack specialists, diagnostic capacity, and referral systems. Maternal and child health have improved, but maternal mortality remains higher than it should be because emergency obstetric care isn't uniformly available.

Botswana's new government promises universal health coverage expansion, but execution requires funding, infrastructure, and workforce growth. Diamond revenues—historically funding social services—are declining, and diversifying the economy takes time. Healthcare spending is relatively high by regional standards, but not sufficient for universal coverage of both infectious and non-communicable diseases. The workforce is better educated and distributed than most African countries, but specialist shortages and urban-rural gaps persist. Botswana has the governance capacity and political will to improve healthcare—the democratic transition proves institutions function—but fiscal constraints limit ambitions. Expanding coverage, improving rural access, and managing the dual burden require sustained investment. Botswana's healthcare system is at an inflection point: it succeeded in the HIV era, but the next phase demands broader capacities, more domestic funding, and systemic adaptation. Whether the new government can deliver depends on economic performance, political priorities, and execution—none guaranteed.`

const COUNTRIES = [
  {
    name: 'Tanzania',
    lat: -6.369028,
    lng: 34.888822,
    summary: TANZANIA_HEALTHCARE,
    chars: TANZANIA_HEALTHCARE.length
  },
  {
    name: 'Uganda',
    lat: 1.373333,
    lng: 32.290275,
    summary: UGANDA_HEALTHCARE,
    chars: UGANDA_HEALTHCARE.length
  },
  {
    name: 'Zimbabwe',
    lat: -19.015438,
    lng: 29.154857,
    summary: ZIMBABWE_HEALTHCARE,
    chars: ZIMBABWE_HEALTHCARE.length
  },
  {
    name: 'Cameroon',
    lat: 7.369722,
    lng: 12.354722,
    summary: CAMEROON_HEALTHCARE,
    chars: CAMEROON_HEALTHCARE.length
  },
  {
    name: 'Zambia',
    lat: -13.133897,
    lng: 27.849332,
    summary: ZAMBIA_HEALTHCARE,
    chars: ZAMBIA_HEALTHCARE.length
  },
  {
    name: 'Mali',
    lat: 17.570692,
    lng: -3.996166,
    summary: MALI_HEALTHCARE,
    chars: MALI_HEALTHCARE.length
  },
  {
    name: 'Niger',
    lat: 17.607789,
    lng: 8.081666,
    summary: NIGER_HEALTHCARE,
    chars: NIGER_HEALTHCARE.length
  },
  {
    name: 'Chad',
    lat: 15.454166,
    lng: 18.732207,
    summary: CHAD_HEALTHCARE,
    chars: CHAD_HEALTHCARE.length
  },
  {
    name: 'Burkina Faso',
    lat: 12.238333,
    lng: -1.561593,
    summary: BURKINA_HEALTHCARE,
    chars: BURKINA_HEALTHCARE.length
  },
  {
    name: 'Rwanda',
    lat: -1.940278,
    lng: 29.873888,
    summary: RWANDA_HEALTHCARE,
    chars: RWANDA_HEALTHCARE.length
  },
  {
    name: 'Botswana',
    lat: -22.328474,
    lng: 24.684866,
    summary: BOTSWANA_HEALTHCARE,
    chars: BOTSWANA_HEALTHCARE.length
  }
]

async function addHealthcareSummaries() {
  console.log('Adding healthcare summaries for 11 African countries (Batch 10 - FINAL)...\n')

  for (const country of COUNTRIES) {
    try {
      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: country.name,
            type: 'country',
            category: 'healthcare'
          }
        },
        create: {
          name: country.name,
          type: 'country',
          country: country.name,
          lat: country.lat,
          lng: country.lng,
          category: 'healthcare',
          summary: country.summary,
          issues: JSON.stringify([]),
          topStories: JSON.stringify([]),
          storyCount: 0,
          updatedAt: new Date()
        },
        update: {
          summary: country.summary,
          updatedAt: new Date()
        }
      })
      console.log(`✅ ${country.name} healthcare summary saved (${country.chars} characters)`)
    } catch (error) {
      console.error(`❌ Error saving ${country.name}:`, error)
    }
  }

  console.log('\n✅ ALL 11 HEALTHCARE SUMMARIES COMPLETED!')
  console.log('\n📊 CHARACTER COUNTS:')
  COUNTRIES.forEach(c => {
    console.log(`   ${c.name}: ${c.chars} characters`)
  })
  console.log(`\n🎉 BATCH 10 COMPLETE - THIS CONCLUDES ALL 128 HEALTHCARE SUMMARIES!`)
}

addHealthcareSummaries()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
