import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// CAMEROON CULTURE SUMMARY
const CAMEROON_CULTURE = `Douala's Bwo Art Gallery opened in 2023 and it's already the conversation—not because Cameroon suddenly discovered contemporary art, but because this country has precious few exhibition spaces willing to back living artists with actual money and wall space. Brice Yonkeu and Noelle Mukete-Elhalaby are showcasing talent from Cameroon and across the African diaspora, and in a nation where the National Museum in Yaoundé is basically it for state-supported contemporary art infrastructure, that matters. Meanwhile, Doual'art, the OG public art space founded by Marilyn Douala Bell and Didier Schaub in 1992, continues doing the heavy lifting—the Prince Claus Fund called them revolutionary, and they're not wrong. But here's the tension: Cameroon's cultural scene is vibrant, according to curator Simon Njami, yet it exists in a country where Paul Biya just "won" his eighth presidential term at 92 and armed forces are shooting protesters in the streets.

The film industry—affectionately called "Camwood"—is having a moment. CAMIFF (Cameroon International Film Festival) is positioning itself as Central Africa's premier film event, and Netflix has purchased four Cameroonian films since 2008, including "Therapy," the first to hit the platform. Over 300 movies have been produced since 2008, with local filmmakers increasingly working in English, French, and Pidgin to capture Cameroon's 250 ethnic groups and their wildly diverse stories. The 2024 CAMIFF awards went to "The Dead Man's Wish" for Best Cameroon Film, with Richard Mofe-Damijo and Jeanne Benti winning acting honors. Multiplexes are sprouting in major cities—audiences want comfortable seating and state-of-the-art sound, and they're finally getting it. Directors are tackling social inequalities, corruption, and ethnic conflicts head-on, which is brave considering the government's track record on dissent. The country's Anglophone regions—where separatists and government forces have killed 6,000+ people since 2016—are reflected in this cinema, even if obliquely. Cameroonian filmmakers are finding ways to speak truth without getting disappeared.

UNESCO just inscribed the Ngondo festival—the Sawa people's water oracle worship and associated cultural traditions—on the Intangible Cultural Heritage list in December 2024. The Ngondo takes place every December in Douala, featuring traditional canoe races and water rituals where priests communicate with spirits to seek blessings. It's spectacular, deeply rooted, and now internationally recognized. The Nguon Festival, celebrating the Bamoun people of the West Region, happens every two years and stretches across seven days of 600-year-old traditions. Cameroon has three UNESCO World Heritage Sites, including the Dja Faunal Reserve. But cultural preservation is happening despite, not because of, government support. The Anglophone crisis means entire regions are cut off from national cultural life—schools closed, heritage sites inaccessible, artists in exile or silenced. The performing arts scene exists in pockets: Théâtre de Yaoundé stages productions when funding allows, traditional dance troupes perform at festivals, but there's no national arts funding infrastructure to speak of.

The music scene is where Cameroon's cultural resilience really shines. Makossa and bikutsi rhythms dominate, with contemporary artists blending traditional sounds with Afrobeat, hip-hop, and electronic influences. But try organizing a large-scale music festival in a country where protests get tear-gassed and opposition leaders are jailed. The cultural sector operates in survival mode—artists create, galleries open, filmmakers shoot, musicians record, all while navigating an authoritarian gerontocracy that views independent cultural expression with suspicion. Cameroon's culture is thriving in spite of everything, which makes it both inspiring and tragic. The talent is undeniable, the creativity unstoppable, but imagine what this scene could be with actual government support, press freedom, and political stability. Instead, artists work around censorship, self-fund projects, and hope the 92-year-old president's succession doesn't plunge the country into chaos that destroys what little infrastructure exists. That's the Cameroonian cultural paradox: excellence under duress, brilliance in the margins.`

const CAMEROON_ISSUES = [
  "Bwo Gallery opening fills infrastructure gap for contemporary art",
  "Film industry growth despite minimal state support",
  "UNESCO recognition of Ngondo and Nguon festivals",
  "Anglophone crisis disrupting cultural access and production",
  "Artistic freedom constrained by political repression"
]

// CANADA CULTURE SUMMARY
const CANADA_CULTURE = `Canada just announced $21 million for arts festivals and $46.5 million for performing arts presentations in Budget 2025, plus $150 million to CBC/Radio-Canada—which sounds generous until you realize the Canada Cultural Spaces Fund simultaneously stopped accepting construction projects due to "limited funding." That's the Canadian arts contradiction in a nutshell: celebrating cultural GDP contributions of $65.3 billion and 670,000 jobs while telling venues they can't build anymore. TIFF just turned 49 (the 50th edition runs September 4-14, 2025) and screened 211 features, 61 shorts, and 8 series from 73 countries, with 700,000 attendees and $240 million CAD economic impact. TIFF is launching a full film market in 2026, which is either brilliantly ambitious or desperately necessary given streaming's decimation of theatrical distribution. The Canada's Top Ten list for 2024 showcases "bold artistry" and "fresh perspectives," but you wonder how many of those films got proper theatrical releases versus straight-to-streaming burial.

The visual arts scene is healthier. Art Toronto 2025 brought galleries from Buenos Aires, Frankfurt, London, Mexico City, New York, Santiago, and Sydney, with a new Arte Sur section celebrating Latin American artistry. The Art Gallery of Ontario is hosting "Joyce Wieland: Heart On" (June 21 to January 4, 2026), a 100-artwork retrospective of one of Canada's most important artists—Wieland was a fierce feminist filmmaker and visual artist who deserves this canonization. The show travels to Montreal Museum of Fine Arts (February 8 to May 4, 2025), proving Canadian institutions still do major traveling exhibitions. Art Vancouver hits April 24-27, 2025, showcasing Western Canada's contemporary scene, while Bau-Xi Gallery celebrates its reputation across Toronto and Vancouver locations. The Museum of Contemporary Art Toronto (MOCA) has exhibitions running through August 2025. But here's the thing: Canada's art scene is increasingly Toronto-Vancouver-Montreal-centric, with smaller cities and rural areas losing infrastructure as federal funding shifts toward "feasibility studies" instead of actual construction.

The policy changes are revealing. The Canada Cultural Investment Fund eliminated its Strategic Initiatives component—applications closed, no new funding. Arts organizations can now request the lesser of 50% of average operating revenues or $1.5 million, but only if their endowment is under $10 million. Translation: established institutions with big endowments are fine; mid-tier organizations scrambling to build sustainability are squeezed. The Canada Cultural Spaces Fund is "experimenting" with expanded feasibility studies while construction funding disappears. It's the neoliberal arts funding playbook: lots of talk about innovation and experimentation, less money for the boring work of keeping buildings standing and artists paid. Canadian Heritage's 2024-2025 Departmental Sustainable Development Strategy sounds progressive until you read the fine print and realize sustainability means fiscal austerity, not long-term cultural investment.

Canada has 20 UNESCO World Heritage Sites (including Head-Smashed-In Buffalo Jump, L'Anse aux Meadows, and Old Quebec), but federal heritage funding is stagnant. Indigenous arts are finally getting institutional recognition—major museums are repatriating artifacts, commissioning Indigenous artists, decolonizing collections—but it's happening slowly and unevenly. The National Gallery of Canada, Canadian Museum of History, and provincial institutions are doing the work, but smaller venues lack resources for meaningful reconciliation efforts. Music festivals across Canada—from Montreal's Jazz Fest to Calgary Stampede—draw massive crowds, but COVID-era funding hasn't been replaced, and venues are struggling with inflation, rising rents, and declining ticket sales as audiences stay home.

Canadian culture is institutionally strong but financially fragile. The infrastructure exists—TIFF, major museums, respected galleries, vibrant Indigenous art movements, internationally recognized filmmakers—but the funding model is cracking. Streaming killed theatrical distribution, pandemic aid ended, and now governments are cutting construction funds while celebrating cultural GDP. Artists are brilliant and prolific; institutions are world-class. But you can feel the squeeze. Budget 2025's $21 million for festivals sounds generous until you divide it across thousands of organizations over three years. Canada's culture sector is running on momentum and goodwill, hoping the next budget doesn't pull the rug out entirely. It's not a crisis yet, but it's not sustainable either.`

const CANADA_ISSUES = [
  "TIFF 50th anniversary and new film market launch in 2026",
  "Major retrospectives: Joyce Wieland at AGO and MMFA",
  "Budget 2025 arts funding versus infrastructure cuts",
  "Cultural Spaces Fund stops construction projects",
  "Indigenous arts gaining recognition but progress uneven"
]

// CHAD CULTURE SUMMARY
const CHAD_CULTURE = `N'Djamena's cultural scene is the definition of resilience under impossible conditions. The N'Djamena International Cultural Festival happens every late April/early May with traditional and contemporary African music, art, and dance—a vibrant celebration in a city where daily life involves navigating Chad's brutal political and economic realities. The Institut Français du Tchad screens films, hosts exhibitions, and presents concerts, giving Chadians a window into francophone culture and contemporary arts. The Cultural Center of Chad showcases established and emerging artists in a country with almost no arts infrastructure, no government funding, and an international reputation as a conflict zone. The N'Djamena Biennale highlights contemporary African art and culture, and the fact that it exists at all is remarkable. The Festival of the Spheres, a more recent addition, celebrates contemporary art and traditional crafts, promoting Chad's cultural diversity to anyone paying attention (which, internationally, is almost nobody).

Music is where Chad's culture truly lives. Traditional Chadian rhythms played on ngoni and other unique instruments mix with contemporary Afrobeat bands electrifying audiences at local festivals. The soundscape is rich and varied, blending Arab, African, and Sahelian influences in ways that reflect Chad's geographic and cultural position at the crossroads of the continent. But here's the brutal context: Chad is recovering from decades of civil war, currently dealing with spillover violence from conflicts in Sudan, Libya, and the Central African Republic, and governed by a transitional military council that seized power after President Idriss Déby was killed in 2021. His son, Mahamat Déby, promised a transition to civilian rule, held elections in 2024, and—surprise—won the presidency. Cultural production in this environment isn't just difficult; it's a minor miracle.

There are no major museums to speak of. The National Museum of Chad in N'Djamena has a small collection of archaeological artifacts and traditional crafts, but it's underfunded, rarely open, and barely functional by international standards. There's no contemporary art museum. Galleries are makeshift spaces in artists' studios or temporary exhibitions at cultural centers. The concept of government arts funding is laughable—Chad's government barely provides basic services like electricity and clean water, let alone grants for artists. The UNESCO World Heritage Sites—Lakes of Ounianga, a stunning series of desert lakes—are natural wonders, not cultural sites, and they're in remote regions most Chadians will never visit. Cultural preservation happens through oral traditions, community festivals, and the determination of individual artists working without institutional support.

Film and theater are virtually non-existent as organized industries. Occasional screenings at Institut Français, rare independent productions, but nothing resembling a film festival, cinema infrastructure, or theatrical tradition beyond traditional storytelling and performance. Music festivals bring international acts occasionally, but the security situation makes large-scale events risky. The Panafrican Film and Television Festival of Ouagadougou (FESPACO) happens in neighboring Burkina Faso; Chadian filmmakers sometimes participate, but Chad itself lacks the infrastructure to host. Artists face censorship not through formal mechanisms but through the chilling effect of operating in a militarized authoritarian state where dissent is dangerous.

What's happening in N'Djamena is cultural survival, not cultural flourishing. Artists create despite everything—despite poverty, despite instability, despite international neglect. The fact that festivals happen, that musicians perform, that visual artists exhibit, is a testament to human creativity's refusal to be extinguished. But let's be clear: this isn't a thriving arts scene; it's a struggling one operating on fumes and willpower. International attention is almost zero (unless it's about oil or conflict), funding is non-existent, and infrastructure is absent. Chad's cultural story is one of potential brutally constrained by circumstance. The talent is there, the traditions are deep, but without stability, investment, or institutional support, it remains marginal, fragile, and vulnerable to collapse.`

const CHAD_ISSUES = [
  "N'Djamena festivals maintain cultural life amid instability",
  "Institut Français providing rare contemporary arts access",
  "Traditional music blending with contemporary Afrobeat",
  "Zero government arts funding or museum infrastructure",
  "Cultural production as survival in militarized state"
]

// CHILE CULTURE SUMMARY
const CHILE_CULTURE = `Santiago is getting a new contemporary art museum and it's about time. Businessman-philanthropist Claudio Engel's NuMu (New Museum of Santiago) breaks ground in August 2025 as Chile's first large-scale contemporary art museum in a purpose-built structure. This is huge—Chile has the MAC (Museum of Contemporary Art, run by Universidad de Chile since 1947 with 2,000+ works), the Museo de la Solidaridad Salvador Allende, and the National Center for Contemporary Art Cerrillos (CNACC, repository for Chilean art since 1967), but they're all retrofitted spaces in older buildings. A dedicated contemporary art museum signals institutional maturity, private sector investment, and growing collector confidence. Galleries like Patricia Ready (avant-garde innovator), Galería XS, Galería AFA, and Galería Isabel Aninat have built Santiago's commercial art market into something serious. PLOP! Gallery, founded 2010, pioneered Chilean illustration and comics, and Artespacio dominates sculpture. This is a city where the art world isn't just looking backward at Matilde Pérez and José Balmes—though MAC's collection rightly honors them—but actively building contemporary infrastructure.

Chilean cinema is in an interesting place. The Valdivia International Film Festival (FICValdivia) held its 2024 edition with "Future Chilean Cinema," an industry-focused program that's less about celebrity and more about sustainable production infrastructure. SANFIC, the International Film Festival in Santiago, brings producers, directors, distributors, critics, and actors together around local and international productions—it's the kind of serious industry gathering that signals maturity beyond festival circuit glamour. But here's the context: Chile's film industry operates without the massive state support of Argentina or Brazil. Filmmakers hustle for funding, co-productions, and international partnerships. The work is often politically engaged—Chile's dictatorship past and Pinochet's legacy still haunt the culture—and contemporary films grapple with inequality, indigenous rights (especially Mapuche struggles), and environmental destruction from mining and resource extraction.

Music festivals are where Chile really flexes. Lollapalooza Chile (March 13-15, 2025, Santiago) brings global headliners and massive crowds. Ultra Chile (October 11-12, 2025, Santiago) dominates the EDM scene. But the crown jewel is the Viña del Mar International Song Festival, held annually over the last week in February at the Quinta Vergara Amphitheater. It's a televised spectacle, a cultural institution, and a massive tourism draw. Chilean music blends Andean folk traditions (cueca, tonada) with rock, cumbia, reggaeton, and electronic music. Artists like Mon Laferte, Ana Tijoux, and Javiera Mena are internationally recognized, and the music scene is vibrant, diverse, and commercially viable. But it's also heavily concentrated in Santiago and Valparaíso—regional scenes exist but lack infrastructure and visibility.

UNESCO World Heritage Sites include Rapa Nui (Easter Island), Valparaíso's historic quarter, the Sewell Mining Town, and the Churches of Chiloé. These are cultural and natural treasures, but preservation funding is inconsistent, and climate change threatens coastal sites. The government talks a good game about cultural heritage, but budgets don't always follow. Performing arts are strong in Santiago—Teatro Municipal stages opera and ballet, independent theaters experiment with political and experimental work—but venues outside the capital struggle. Chilean arts funding is largely through FONDART (Fondo Nacional de Desarrollo Cultural y las Artes), which distributes grants competitively. It's better than nothing, but it's also bureaucratic, competitive, and insufficient for demand.

Chilean culture is urban, sophisticated, politically conscious, and unevenly distributed. Santiago and Valparaíso get the galleries, the festivals, the infrastructure. Smaller cities and rural areas—especially in the north and south—are culturally underserved. Indigenous arts, particularly Mapuche, are gaining recognition and institutional support, but it's slow and often tokenistic. Censorship isn't overt—Chile is a democracy—but commercial pressures, conservative cultural gatekeepers, and funding scarcity create soft constraints. NuMu's opening in 2025 is exciting, a signal that Chile's contemporary art scene is maturing. But the bigger question is whether that maturity translates beyond elite circles into genuinely democratic cultural access. Right now, it's a capital-centric boom with the rest of the country watching from the sidelines.`

const CHILE_ISSUES = [
  "NuMu breaking ground as first purpose-built contemporary museum",
  "Valdivia and SANFIC film festivals building industry infrastructure",
  "Lollapalooza and Viña del Mar dominating music festival scene",
  "FONDART funding competitive but insufficient",
  "Cultural infrastructure concentrated in Santiago and Valparaíso"
]

// CHINA CULTURE SUMMARY
const CHINA_CULTURE = `Beijing's 798 Art District recorded 12.57 million visits in 2024, features nearly 80 exhibitions monthly, and wants to be "The Global Art Destination." Gallery Weekend Beijing in May 2024—coinciding with Beijing Dangdai Art Fair (122 exhibitors, 14 countries, 80,000 visitors) and JingArt—made May the capital's unofficial "art month." The UCCA (Ullens Center for Contemporary Art) is staging major retrospectives: Hiroshi Sugimoto's "Time Machine" ran in 2024, and the institution founded by Belgian collectors Guy and Myriam Ullens remains one of China's leading contemporary art centers. Hive Center for Contemporary Art, Beijing Commune, Pace Beijing, Lisson Gallery, Tang Contemporary Art, M Woods, HdM Gallery—these aren't scrappy startups, they're serious international players operating in a 148-acre district of converted factories that's been ground zero for Chinese contemporary art since 2002. Shanghai gets the glamour and the international art fairs, but Beijing is where you go to understand what's happening at the interface between contemporary Chinese art and contemporary Chinese society. That interface is heavily surveilled, ideologically constrained, and commercially explosive.

The film industry is in crisis. China's 2024 box office revenue totaled $5.82 billion, down 22.6% from 2023 and 34% from 2019. Moviegoers dropped by a fifth compared to a decade ago. The China Film Administration—which controls what appears on screens—announced in July 2024 that all short films need permits for foreign festival appearances. The government's direct involvement through regulation and censorship has stifled creativity, negatively impacting theater attendance. Films deemed "politically incorrect" or "seditious" are denied licenses outright, and decisions seem arbitrary. In November 2025, Chinese authorities harassed directors and producers causing them to pull films from the inaugural IndieChina Film Festival in New York City—that's extraterritorial censorship, reaching beyond China's borders to suppress diaspora expression. Hong Kong's once-mighty film industry is grappling with changing market realities and political pressures from Beijing. The government funds "Main Melody" films—patriotic, socialist, historically sanitized productions—but audiences increasingly aren't showing up. Lab-grown diamonds, streaming, government ideology: pick your metaphor, but Chinese cinema's golden age is over, replaced by risk-averse propaganda and plummeting attendance.

Music and performing arts are booming in the commercial sphere—K-pop-style idol groups, huge arena concerts, elaborate theatrical productions—but anything politically sensitive gets shut down immediately. The Qintai Concert Hall in Wuhan, the National Centre for the Performing Arts in Beijing, and Shanghai Grand Theatre host world-class performances (opera, ballet, orchestral music, traditional Chinese opera), but programming is carefully curated to avoid controversy. Rock, hip-hop, and electronic music scenes exist in Beijing, Shanghai, and Guangzhou, with venues like MAO Livehouse and Yugong Yishan hosting shows, but lyrics are scrutinized, performances occasionally shut down, and artists self-censor to survive. Traditional arts—Peking opera, calligraphy, classical Chinese painting—receive state funding and institutional support as "national heritage," but contemporary reinterpretations that critique government or society face censorship.

China has 57 UNESCO World Heritage Sites (the Great Wall, Forbidden City, Terracotta Warriors, classical gardens of Suzhou, Mogao Caves, etc.)—an incredible cultural patrimony. But preservation is uneven: major tourist sites get investment, smaller sites deteriorate, and development pressures often override heritage concerns. The National Art Museum of China, the Shanghai Museum, and the Palace Museum have world-class collections, but contemporary art museums face ideological constraints on what they can exhibit. Ai Weiwei is internationally celebrated; domestically, he's persona non grata. That's the Chinese art paradox: globally influential artists who can't exhibit at home, a commercial market that's enormous but ideologically constrained, and a government that simultaneously promotes "cultural confidence" (Xi Jinping's phrase) while suppressing anything that questions official narratives.

Chinese culture in 2024-2025 is massive, sophisticated, and suffocating. The talent is undeniable—artists, filmmakers, musicians, performers—and the audience is enormous. But the government's control is comprehensive and intensifying. The 798 Art District thrives as long as it doesn't get too political. Filmmakers make brilliant work that can't get released. Musicians draw huge crowds playing music with carefully sanitized lyrics. It's a cultural superpower operating with one hand tied behind its back, or more accurately, with the Party's hand on the throat. The tragedy is that Chinese culture could be even more influential, innovative, and globally resonant if artists had actual freedom. Instead, it's excellence under constraint, brilliance within limits, creativity that knows exactly where the red lines are.`

const CHINA_ISSUES = [
  "798 Art District 12.57M visits, Gallery Weekend Beijing success",
  "Film industry crisis: box office down 34% from 2019",
  "Censorship intensifying: short films need permits for foreign festivals",
  "IndieChina Film Festival in NYC shut down by Beijing pressure",
  "57 UNESCO sites with uneven preservation and development pressures"
]

// COLOMBIA CULTURE SUMMARY
const COLOMBIA_CULTURE = `Bogotá and Medellín are having a cultural moment and the world is finally paying attention. MAMBO (Museo de Arte Moderno de Bogotá), designed by the late great architect Rogelio Salmona and completed in 1985, houses 3,633 works across four floors, six exhibition halls, an auditorium, project room, workshops, library, bookstore, and restaurant—it's a serious institution doing serious work. The Museo de Arte Contemporaneo de Bogota in Minuto de Dios is free, which matters in a country where economic inequality is massive and cultural access shouldn't require disposable income. The Museo de Arte de la Universidad Nacional is another strong university-backed contemporary space. In Medellín, MAMM (Medellín Museum of Modern Art) plays a crucial role in the city's cultural development—this is a city that's transformed from Pablo Escobar's violent capital into a cultural and innovation hub, and MAMM is part of that narrative. But let's be clear: these museums exist despite, not because of, lavish government funding. Colombia's arts infrastructure is built by passionate individuals, universities, and private donors more than state support.

Colombian cinema is punching above its weight. The Colombian International Film Festival gears up for its 12th edition in spring 2025. FICCI, the oldest film festival in Latin America, showcases all genres with a special section for Colombian cinema—it's prestigious, well-attended, and genuinely influential. The Macondo Awards are Colombia's most important film recognition from the Colombian Academy of Cinematographic Arts and Sciences. Colombian filmmakers are telling stories about narcotrafficking legacy, internal displacement from decades of FARC conflict, urban violence, and Afro-Colombian and indigenous experiences. Directors like Ciro Guerra ("Embrace of the Serpent"), Alejandro Landes ("Monos"), and Laura Mora are internationally recognized, and Colombian films regularly hit the festival circuit at Cannes, Berlin, Venice, Sundance. But distribution remains tough—international acclaim doesn't always translate to domestic box office, and streaming deals are unpredictable.

Music festivals are where Colombia absolutely shines. Estéreo Picnic brought Billie Eilish, Drake, and Tame Impala in 2023—it's the country's premier multi-genre music festival. Rock al Parque attracts 300,000+ visitors annually and is the largest music festival in Colombia with free admission, which is incredible for access and crowd size. La Solar Festival in Medellín (February 16-17, 2024) expected 45,000 attendees with electronic, urban, and alternative rhythms. Storyland is Colombia's biggest electronic music festival. Salsa al Parque showcases Latino salsa artists from around the world, especially Cali-based talent (Cali is Colombia's salsa capital). Baum Festival gives local DJs and up-and-coming performers a global platform. This is a country where music is infrastructure—festivals are massive, diverse, well-organized, and culturally central in ways that go beyond entertainment.

Colombia's cultural diversity is staggering: Afro-Colombian communities on the Pacific and Caribbean coasts, indigenous groups in the Amazon and Andes, Spanish colonial heritage in cities like Cartagena and Popayán (both UNESCO World Heritage Sites), and contemporary urban cultures in Bogotá, Medellín, and Cali. The Barranquilla Carnival, inscribed on UNESCO's Intangible Cultural Heritage list, is one of the world's largest carnivals and a spectacular expression of Caribbean Colombian culture. The San Agustín Archaeological Park, the Coffee Cultural Landscape, and the historic centers of Cartagena and Mompox are UNESCO World Heritage Sites receiving tourism and preservation attention, though funding is always inadequate and pressures from development are constant.

Censorship isn't a major issue—Colombia is a democracy with robust press freedom relative to neighbors like Venezuela or Nicaragua—but violence against cultural workers, especially those documenting conflict, human rights abuses, or environmental destruction, is real. Social leaders, journalists, and activists get killed with disturbing regularity, and that creates a chilling effect. Performing arts are strong in major cities—Teatro Colón in Bogotá, Teatro Pablo Tobón Uribe in Medellín—staging opera, ballet, theater, and experimental work, but again, it's concentrated in urban centers while rural areas lack access.

Colombia's cultural scene is vibrant, diverse, and resilient. The infrastructure exists, the talent is undeniable, the festivals are world-class. But it's also a country emerging from decades of armed conflict, grappling with profound inequality, and navigating the tension between heritage preservation and rapid urban development. Artists create brilliantly despite the odds, institutions operate on shoestring budgets, and the government's cultural spending is inadequate for the country's size and diversity. Colombia deserves more investment, more international recognition, and more security for cultural workers. What's happening is impressive; what could happen with proper support would be transformative.`

const COLOMBIA_ISSUES = [
  "MAMBO and MAMM anchoring contemporary art in Bogotá and Medellín",
  "FICCI and Macondo Awards elevating Colombian cinema internationally",
  "Rock al Parque and Estéreo Picnic drawing massive free/affordable audiences",
  "UNESCO heritage sites under development pressures",
  "Violence against cultural workers creating chilling effect"
]

// CONGO (BRAZZAVILLE) CULTURE SUMMARY
const CONGO_CULTURE = `Brazzaville and Kinshasa were jointly designated African Capitals of Culture for 2024-2025, which is both historic and bittersweet. Historic because these twin capitals separated by the Congo River are collaborating despite being in different countries (Republic of Congo and DRC). Bittersweet because the designation highlights how little international attention Central African culture receives and how much this region needs infrastructure investment. The first event launched January 24, 2024, marking World Day of African and Afro-descendant Culture. Brazzaville is experiencing a "cultural renaissance"—that's the official language, and there's truth to it. FESPAM (Pan-African Music Festival), a major biennial event promoting African music across traditional, modern, and religious genres, draws visitors from around the world. The International Festival of Contemporary Dance provides cultural enrichment and entertainment. These aren't small neighborhood events; they're genuinely international gatherings showcasing Congo-Brazzaville's cultural ambitions.

The contemporary art scene is a dynamic fusion of tradition and modernity, which sounds like marketing copy until you see the work. The Poto-Poto School of Painting (Ecole de Peinture de Poto-Poto), established in one of Brazzaville's most famous neighborhoods, is one of Africa's most celebrated painting schools—it's produced generations of artists blending indigenous aesthetics with contemporary techniques. Rhode Bathe-Scheba Makoumbou is among the rising contemporary Congolese painters gaining international attention. Moyi Arts Concept, founded in 2022 by diplomat and Georgetown alum Sarah Marie-Chantal Andely, is registered in both Congo-Brazzaville and the U.S., delivering Congolese fine arts and crafts to global markets. This is how scenes grow: committed individuals building infrastructure one gallery, one export deal, one exhibition at a time.

But let's be honest about the challenges. Congo-Brazzaville has minimal museum infrastructure—there's the National Museum in Brazzaville, but it's underfunded and limited in scope. There are no major contemporary art museums with permanent collections, climate-controlled storage, or international exhibition programs. Visual arts happen in studios, temporary exhibition spaces, and cultural centers. Government funding for the arts is minimal to non-existent—oil revenues dominate the economy, and arts spending is not a priority. The country faces poverty, infrastructure deficits, and political instability under President Denis Sassou Nguesso, who's ruled for 38 of the last 43 years. Cultural production happens despite governance failures, not because of enlightened cultural policy.

Music is Congo-Brazzaville's international calling card. Congolese rumba—the infectious dance music born in Kinshasa and Brazzaville in the mid-20th century—influenced music across Africa and the diaspora. Artists like Papa Wemba, Koffi Olomide, and Fally Ipupa (though technically from DRC Kinshasa) represent the Congolese music tradition that's enormous in francophone Africa. FESPAM brings together traditional musicians playing likembe (thumb piano), ngoma drums, and contemporary bands blending rumba with soukous, ndombolo, and Afrobeat. The festival is genuinely pan-African, a platform for musical exchange that matters culturally and commercially.

Film and theater are nascent. There's no significant film industry infrastructure—occasional screenings, rare independent productions, but nothing resembling a festival circuit or production ecosystem. French cultural centers (Institut Français) occasionally host screenings and performances, providing rare access to international culture. Theater happens in community spaces and schools, drawing on oral storytelling traditions and political satire, but without formal venues or funding. UNESCO World Heritage Sites in Congo-Brazzaville include the Sangha Trinational (shared with CAR and DRC), a natural site protecting rainforest biodiversity—important ecologically, but not a cultural heritage site in the artistic sense.

Congo-Brazzaville's cultural story is one of resilience and potential. The Capitals of Culture designation in 2024-2025 brought visibility and pride, but it didn't bring sustainable funding or infrastructure. Artists create brilliant work without institutional support, festivals happen through hustle and international partnerships, and the cultural scene survives on passion and improvisation. The tragedy is that this region—home to musical traditions that shaped African popular music, visual artists blending ancestral and contemporary practices, and performance traditions dating back centuries—remains internationally invisible outside specialist circles. With investment, Congo-Brazzaville could be a regional cultural powerhouse. Without it, the scene remains fragile, dependent on individuals and vulnerable to the next political or economic crisis.`

const CONGO_ISSUES = [
  "Brazzaville-Kinshasa designated African Capitals of Culture 2024-2025",
  "FESPAM and dance festivals drawing international audiences",
  "Poto-Poto School of Painting legacy continuing with new artists",
  "Moyi Arts Concept connecting Congolese arts to global markets",
  "Minimal museum infrastructure and government arts funding"
]

// COSTA RICA CULTURE SUMMARY
const COSTA_RICA_CULTURE = `San José has ICA (Instituto de Arte Contemporáneo), a contemporary art museum in downtown with exhibitions running through March 2026, and MADC (Museo de Arte y Diseño Contemporáneo), established 1994 in a converted national liquor factory with four exhibition rooms, an auditorium, and an open-air terrace. MADC showcased Costa Rican textile artist Katrin Aason's solo exhibition from July to November 2024—that's the kind of specific, local-artist-focused programming that matters in a small country where cultural visibility is hard-won. The Museo de Arte Costarricense in La Sabana Park is free, features historical and contemporary Costa Rican art, and includes a sculpture garden and the Golden Room. These aren't world-famous institutions, but they're well-run, accessible (free admission!), and committed to Costa Rican artists alongside international work. In a country of 5 million people with limited arts funding, that's impressive.

Costa Rica doesn't have a massive film industry—it's not Colombia or Mexico—but it has a scrappy independent cinema scene producing documentaries and narrative features about environmental conservation (Costa Rica is famous for eco-tourism and biodiversity), social inequality, and Central American migration. Filmmakers like Paz Fábrega, Ishtar Yasin, and Jurgen Ureña are making internationally recognized work on micro-budgets. The lack of major film festivals or studio infrastructure means Costa Rican cinema is under-distributed and under-funded, but the work that gets made is often politically engaged and formally inventive. Streaming platforms occasionally pick up Costa Rican films, but theatrical distribution is almost non-existent, and most Costa Ricans encounter their own cinema at international festivals or online rather than in local theaters.

Music is where Costa Rica's culture gets interesting. Traditional marimba and pre-Columbian indigenous music blends with contemporary rock, reggae, cumbia, and electronic scenes. Bands like Malpaís (folk-rock), Sonámbulo Psicotropical (psychedelic cumbia), and the ska-punk scene in San José have cult followings regionally and in the Central American diaspora. But here's the limitation: Costa Rica doesn't have major music festivals on the scale of Lollapalooza Chile or Rock in Rio. Smaller festivals happen—Envision Festival (transformational/electronic music in Uvita), independent rock and punk shows in San José—but they lack infrastructure and international visibility. Costa Rican musicians often migrate to Mexico, U.S., or Europe for career opportunities because the domestic market is too small to sustain professional music careers.

UNESCO World Heritage Sites include Cocos Island National Park, Talamanca Range-La Amistad Reserves, and Guanacaste Conservation Area—all natural sites reflecting Costa Rica's environmental priorities. The Pre-Columbian Stone Spheres are the only cultural UNESCO sites, and they're archaeological, not contemporary. That tells you something: Costa Rica's international cultural brand is "eco-tourism and biodiversity," not arts and culture. There's no UNESCO-listed performing arts tradition, no historic city center on the World Heritage list. The government invests heavily in environmental conservation and tourism infrastructure, less so in cultural production. Arts funding comes primarily through the Ministry of Culture, but budgets are modest and competitive.

Performing arts in San José include Teatro Nacional (opera, ballet, classical music in a beautiful 1897 building), Teatro Melico Salazar, and smaller independent theaters staging contemporary work. But outside the capital, performing arts infrastructure is minimal. Dance companies, theater groups, and musicians exist, but they operate on shoestring budgets without sustainable funding models. Censorship isn't a major issue—Costa Rica is a stable democracy with strong press freedom—but economic constraints and lack of audience development mean many artists struggle to professionalize.

Costa Rica's cultural scene is small, earnest, and under-resourced. The museums are accessible and well-intentioned, the independent film scene is scrappy, the music scene is vibrant but limited by market size, and performing arts are concentrated in the capital. What's missing is scale and investment. This is a country that abolished its military in 1949 and redirected spending toward education and healthcare—a genuinely progressive choice. But cultural spending didn't get the same priority, and it shows. Artists create despite the limitations, institutions operate on minimal budgets, and international visibility is low. Costa Rica deserves credit for punching above its weight, but the scene remains marginal, fragile, and dependent on passionate individuals rather than robust institutional support.`

const COSTA_RICA_ISSUES = [
  "MADC and ICA providing contemporary art access in San José",
  "Free admission at Museo de Arte Costarricense improving cultural access",
  "Independent film scene producing work on micro-budgets",
  "Music festivals limited by small domestic market size",
  "Government prioritizing eco-tourism over cultural investment"
]

// CROATIA CULTURE SUMMARY
const CROATIA_CULTURE = `Zagreb's Museum of Contemporary Art (MSU) is the biggest and most modern museum in Croatia, and under new director Vesna Meštrić (as of 2024), it's presenting ambitious programming: Sean Scully's "Passenger" retrospective (September-November 2025), "Meaning Distances," "To Make the World a Better Place," "Vibraception—Investigations in Wavespace," "The Smell of Freshly Chopped Wood," and "The Valley of Uncanny Lovers" all running through late 2024 and into 2025. The permanent display, "Collection in Motion," showcases 620 works by 240 artists—half Croatian, half international—including Carsten Höller's interactive Double Slide and Sanja Iveković's "Ženska Kuća" installation dealing with violence against women. MSU is open Tuesday-Friday 11am-7pm, Saturday-Sunday 11am-6pm, with free admission the first Wednesday of every month. That's real cultural accessibility. Karas Gallery and the galleries in Martićeva (Zagreb's design district) are smaller but influential, hosting exhibitions, workshops, residencies, and maintaining active digital platforms.

Film festivals are thriving. The Dubrovnik Summer Festival (July 10 - August 25, 2025) runs its 76th edition with over 70 cultural performances across 47 days: drama, opera, ballet, folklore, exhibitions, film screenings, and book discussions. The Mediterranean Film Festival in Split (June, past 6 years) premieres Mediterranean-region films in Croatia. These aren't niche events—they're major cultural draws for both locals and tourists. Music festivals are massive: Ultra Europe at Split's Park Mladezi Stadium (July 11-13, 2025) is one of Europe's top EDM events. The Split Summer Festival (mid-July to mid-August) features open-air theater, music, and dance in and around Diocletian's Palace—imagine watching contemporary performance in a 1,700-year-old Roman palace. Dubrovnik Musical Spring (April 13 - June 17, 2025) presents the Dubrovnik Symphony Orchestra. These festivals aren't struggling for audiences; they're integral to Croatia's cultural and tourism economy.

But here's the tension: Croatian culture is increasingly tourism-dependent. Dubrovnik and Split are Game of Thrones and ancient ruins to most visitors, not contemporary art scenes. The festivals cater to international audiences, ticket prices reflect tourism economics, and locals sometimes feel priced out of their own cultural life. Croatian artists—filmmakers, musicians, visual artists—often migrate to larger European markets (Berlin, Vienna, London) because the domestic market is small (population 3.9 million) and funding is limited. Croatian cinema has produced internationally recognized directors like Dalibor Matanić, Hana Jušić, and Antoneta Alamat Kusijanović (whose "Murina" won Camera d'Or at Cannes 2021), but domestic distribution is weak and state funding is competitive and insufficient.

UNESCO World Heritage Sites include Dubrovnik's Old City, Diocletian's Palace in Split, Plitvice Lakes, the Euphrasian Basilica in Poreč, and the Stari Grad Plain. These sites are stunning, well-preserved, and absolutely mobbed with tourists. That's the Croatian paradox: UNESCO recognition brings tourism revenue that funds preservation, but also brings crowds that threaten the sites' integrity and push locals out of historic centers. The government invests in heritage preservation because it's economically rational (tourism accounts for ~20% of GDP), not necessarily because of deep cultural commitment.

Performing arts in Zagreb, Split, and Rijeka include opera, ballet, theater, and experimental work, but funding is precarious and audiences skew older. Croatian National Theatre in Zagreb stages ambitious productions, but younger audiences increasingly consume culture digitally or at festivals rather than traditional venues. Music ranges from traditional klapa (a cappella vocal groups from Dalmatia) to thriving rock, electronic, and hip-hop scenes in urban centers. But again, commercialization and emigration are constant pressures—artists chase opportunities abroad, and domestic cultural infrastructure struggles to retain talent.

Croatia's cultural scene is sophisticated, well-organized, and tourism-inflected. The museums are professional, the festivals are world-class, the heritage sites are spectacular. But sustainability is a question mark. Can cultural institutions thrive when they're designed primarily for tourists rather than locals? Can artists build careers in a small market with limited funding and constant brain drain to richer EU countries? Croatia's culture is impressive, but it's also precarious—dependent on tourism, vulnerable to economic downturns, and struggling to balance heritage preservation with contemporary innovation. The talent is there, the infrastructure exists, but long-term sustainability requires more domestic investment and less reliance on foreign visitors' wallets.`

const CROATIA_ISSUES = [
  "MSU Zagreb presenting ambitious exhibitions with Sean Scully retrospective",
  "Dubrovnik and Split festivals combining heritage and contemporary arts",
  "Ultra Europe and summer festivals driving music tourism",
  "Cultural scene increasingly tourism-dependent and pricing out locals",
  "Brain drain as artists migrate to larger European markets"
]

// CUBA CULTURE SUMMARY
const CUBA_CULTURE = `The XV Havana Biennial is running from November 15, 2024 to February 28, 2025—40th anniversary, theme "Shared Horizons," organized by the Wifredo Lam Center. Nelson Ramírez de Arellano describes the conceptual cores: mediation, collaboration, interdisciplinarity. The Biennial takes the city itself as setting—streets, studios, galleries, museums all become exhibition space—which is brilliant when infrastructure is crumbling and budgets are non-existent. Commemorative exhibitions are showing collections from Casa de las Américas and the Wifredo Lam Centre, and for the first time there's a commemorative exhibition of Cuban artists. This is happening while Cuba faces daily blackouts, severe shortages, and tourism down 30% in 2025. That the Biennial is happening at all is remarkable. That it's ambitious and international despite economic collapse is either inspiring or absurd, depending on whether you're an optimist or a realist.

Here's the e-flux question: "Can a Biennial Respect Difference in a Country that Represses Dissidence?" It's the right question. Cuba's contemporary art scene is sophisticated, internationally connected, and ideologically constrained. The Wifredo Lam Center, Museum of Fine Arts' Cuban Collection, Center for the Development of Visual Arts, and Habana Gallery showcase brilliant work by Cuban artists. But artists who explicitly criticize the government—like Tania Bruguera or the San Isidro Movement artists—face harassment, detention, and exile. The regime tolerates cultural production as long as it doesn't challenge political authority. Abstraction is fine, social commentary is risky, explicit dissent is forbidden. Many of Cuba's most internationally successful contemporary artists live abroad (Miami, Mexico City, Madrid) because operating in Cuba means navigating censorship and political pressure.

Music is Cuba's international cultural export: son, salsa, timba, reggaeton—Cuban rhythms shaped Latin music globally. Havana's music scene is vibrant: jazz clubs, salsa venues, underground hip-hop, electronic music parties. The Buena Vista Social Club legacy still draws tourists, but contemporary Cuban music is more diverse and politically engaged than nostalgia tourism suggests. Artists like Cimafunk blend Afro-Cuban rhythms with funk, and young rappers tackle racism, inequality, and political frustration. But state control is comprehensive: major venues are government-owned, lyrics are monitored, and musicians who get too political face censorship or exile. Concerts happen in homes, underground venues, and informal spaces to avoid state oversight.

Film in Cuba has a storied history—ICAIC (Cuban Institute of Cinematographic Art and Industry) produced internationally recognized films for decades—but the industry is severely constrained by funding shortages, censorship, and economic crisis. Filmmakers like Fernando Pérez and Arturo Infante make powerful work, but distribution is limited and state approval required. The Havana Film Festival happens annually, showcasing Latin American cinema, but programming is politically vetted. Cuban filmmakers increasingly produce work abroad or in exile, where creative freedom and funding are more accessible.

UNESCO World Heritage Sites include Old Havana, Trinidad, Viñales Valley, San Pedro de la Roca Castle, and the Alejandro de Humboldt National Park. These sites are spectacular and culturally significant, but preservation is inadequate—buildings collapse in Old Havana, infrastructure crumbles, and tourism revenue doesn't translate to effective conservation. The government talks about heritage preservation while Havana literally falls apart. Performing arts—ballet (Ballet Nacional de Cuba is world-class), theater, opera—survive on minimal budgets and international partnerships. Artists are incredibly skilled but severely under-resourced.

Cuba's culture is a paradox: world-class talent operating under authoritarian constraints, international recognition paired with domestic repression, vibrant creativity amid economic collapse. The Havana Biennial showcases brilliant contemporary art while dissidents are jailed. Musicians create infectious rhythms while navigating state censorship. Filmmakers make powerful work that may never be seen domestically. Heritage sites crumble while tourism is promoted. Cuban culture survives despite the government, not because of it. Artists are resilient, creative, and determined, but the system is failing them. The Biennial's "Shared Horizons" theme is poignant: Cuban artists share horizons with the international art world but are trapped on an island where freedom—artistic, political, economic—remains elusive.`

const CUBA_ISSUES = [
  "XV Havana Biennial running despite economic crisis and blackouts",
  "Wifredo Lam Center anchoring contemporary art amid resource constraints",
  "Censorship constraining artists while tolerating politically safe work",
  "Music scene vibrant but state-controlled, underground scenes thriving",
  "UNESCO heritage sites deteriorating despite tourism promotion"
]

// CYPRUS CULTURE SUMMARY
const CYPRUS_CULTURE = `NiMAC (Nicosia Municipal Arts Centre) has been operating since January 1994 in the renovated Old Powerhouse—Europa Nostra Award winner—and it's the oldest and largest contemporary art center on the island. Thirty years, 100+ exhibitions, well-known Cypriot and international artists: that's institutional maturity. The State Gallery of Contemporary Art occupies an exquisitely restored edifice with 20th-century Cypriot paintings and sculptures, and the SPEL Building in Old Nicosia is being renovated as an annex. The Cyprus Museum of Modern Arts (Near East University, founded 2018) claims to be the largest modern art museum in the Near East region with 8,000+ artworks from the 1940s to present, offering 21 unique exhibitions free of charge. The A.G. Leventis Gallery has impressive Cypriot, Greek, and Parisian collections. The Zampelas Art Museum in Nicosia features 1,200+ works including Picasso and Dalí. This is serious infrastructure for an island of 1.2 million people (and that's complicated by the Turkish-occupied north).

The JELO6 Project Cyprus 2025 runs November 12-16 at the Old Town Hall of Nicosia, focusing on contemporary jewelry and metalwork—niche but internationally connected. Cyprus has strong gallery scenes in Nicosia, Limassol, and Paphos (PLOP! Gallery, Galería XS, etc.), showing contemporary Cypriot and regional artists. But here's the context: Cyprus is divided. The Republic of Cyprus (Greek Cypriot south) has these institutions; the Turkish-occupied north has separate cultural infrastructure that's internationally unrecognized. This political division fractures the cultural scene, limiting collaboration and creating parallel art worlds on a tiny island.

Cypriot cinema is minimal—occasional independent productions, rare international festival presence, but no significant film industry infrastructure. The Cyprus Film Days international festival happens annually, showcasing European and Mediterranean cinema, but Cypriot filmmaking is underfunded and under-distributed. Theater and performing arts happen in Nicosia and Limassol—opera, ballet, contemporary theater—but venues are limited and audiences small. The Cyprus Symphony Orchestra and local dance companies perform regularly, but funding is precarious.

UNESCO World Heritage Sites include Paphos (archaeological site), Painted Churches in the Troodos Region, Choirokoitia (Neolithic settlement). These are archaeological and medieval heritage sites, not contemporary cultural infrastructure. The government invests in heritage tourism—archaeological parks, museum renovations—but contemporary arts funding is modest. Music ranges from traditional Cypriot folk (including Turkish Cypriot traditions in the north) to contemporary rock, electronic, and pop scenes in urban centers. Festivals are small-scale, and the domestic market can't sustain professional music careers, so artists often relocate to Athens, London, or other European cities.

The division is everything. A Greek Cypriot artist in Nicosia can't easily exhibit in Turkish-occupied Kyrenia, and vice versa. Cultural exchange happens informally and despite political barriers, but institutionally it's fragmented. The Republic of Cyprus is an EU member with access to European funding and cultural programs; the north is internationally isolated, dependent on Turkey, and culturally cut off. This artificially splits an already small cultural scene, duplicating infrastructure and limiting collaboration. International artists visiting Cyprus often engage only with the south, unaware of or unable to access the north's cultural life.

Cyprus culture is sophisticated, well-organized, and politically constrained. The museums are professional, the galleries active, the heritage sites impressive. But the market is tiny, funding is limited, and the political division creates structural barriers. Artists are talented but often emigrate for opportunities. Institutions operate well but struggle with sustainability. The island's cultural life is richer than its size suggests, but it's also fragile—dependent on tourism, vulnerable to political instability, and limited by geography and division. What could be a thriving Mediterranean cultural crossroads is instead two separate scenes operating side by side, unable to fully connect.`

const CYPRUS_ISSUES = [
  "NiMAC celebrating 30 years as island's leading contemporary art center",
  "Cyprus Museum of Modern Arts offering 8,000 artworks free of charge",
  "Political division fracturing cultural scene into Greek and Turkish sectors",
  "Small domestic market driving artist emigration to Europe",
  "Archaeological heritage tourism overshadowing contemporary arts funding"
]

// CZECH REPUBLIC CULTURE SUMMARY
const CZECH_REPUBLIC_CULTURE = `DOX Centre for Contemporary Art is Prague's leading modern art space, the largest independent institution focusing on contemporary art in the Czech Republic, housed in converted 19th-century industrial buildings in Holešovice with a permanent rooftop airship installation (cozy beanbags included). DOX presents thought-provoking exhibitions, international and Czech artists, and it's genuinely ambitious—this isn't provincial posturing, it's serious curatorial work. The National Gallery Prague's Trade Fair Palace (Veletržní Palác) houses one of the largest modern and contemporary art collections in the Czech Republic. Founded 1796, it's among the world's oldest public galleries, spread across multiple buildings citywide. Museum Kampa, in the former Sova's Mills, focuses on European art with special emphasis on Czech artists. MeetFactory, founded 2001 by sculptor David Černý, is a not-for-profit contemporary art center encouraging cross-genre dialogue—exhibitions, concerts, theater, residencies. Museum Montanelli is one of the Czech Republic's few private museums with a serious reputation. Kunsthalle Praha has exhibitions running into 2026. This is a deep bench.

Czech cinema has a legendary history—Miloš Forman, Jiří Menzel, Věra Chytilová, the Czech New Wave—and the contemporary scene continues producing internationally recognized work, though nothing like the 1960s golden age. Karlovy Vary International Film Festival is Central Europe's most prestigious film festival, A-list status, major premieres, serious industry presence. The festival draws international stars, distributors, and press annually. Czech filmmakers like Jan Svěrák, Bohdan Sláma, and younger directors continue making politically engaged, formally inventive films, but state funding is competitive and distribution is challenging. Barrandov Studios in Prague remains a major production facility for international films (Mission: Impossible, Casino Royale, etc.), so there's infrastructure and technical expertise, but Czech stories sometimes feel overshadowed by foreign productions using Prague as a cheap Vienna or Paris.

Music in Prague ranges from world-class classical (Czech Philharmonic, Prague Spring Festival) to vibrant rock, electronic, and experimental scenes. Venues like Roxy, MeetFactory, and Cross Club host international and local acts. The Prague Spring International Music Festival (May-June annually) is a major classical music event with orchestras and soloists from around the world. But there's also a thriving underground: punk, metal, electronic music, jazz—remnants of the dissident culture from communist era morphing into contemporary scenes. Festivals like United Islands of Prague (free multi-genre music festival) and Colours of Ostrava (massive multi-day festival) draw tens of thousands. Czech music history is rich (Dvořák, Smetana, Janáček) and contemporary Czech composers and musicians continue that legacy, though international visibility is limited compared to visual arts and film.

UNESCO World Heritage Sites include Prague's historic center, Český Krumlov, Kutná Hora, the Holy Trinity Column in Olomouc, and the Villa Tugendhat in Brno. These sites are spectacularly preserved and absolutely mobbed with tourists—Prague gets 8+ million visitors annually, and heritage sites are both culturally significant and economically valuable. But over-tourism is destroying the experience: Prague's historic center feels like Disneyland, locals priced out, cultural life commercialized. Preservation funding is adequate for major sites, but smaller heritage sites and contemporary cultural infrastructure compete for limited state resources.

Performing arts are strong: National Theatre (opera, ballet, drama), Estates Theatre (where Mozart premiered Don Giovanni), and numerous independent theaters staging contemporary Czech and international work. Black light theater and puppet theater are Czech specialties—touristy but also genuinely inventive and part of the cultural tradition. Laterna Magika pioneered multimedia performance in the 1950s and continues producing experimental work. But economic pressures, audience decline (especially among younger demographics), and competition from digital entertainment strain traditional performing arts institutions.

Czech culture is institutionally robust, historically significant, and tourism-saturated. The contemporary art scene is excellent, film festivals are prestigious, music ranges from classical to cutting-edge, and heritage sites are world-class. But sustainability is a question: can cultural institutions serve local audiences when they're designed primarily for tourists? Can artists build careers when brain drain to Berlin, Vienna, and London is constant? Czech culture in 2024-2025 is impressive but precarious, dependent on tourism revenue, vulnerable to economic downturns, and struggling to balance heritage preservation with contemporary innovation. The talent and infrastructure exist, but long-term viability requires more domestic investment, less tourist dependence, and stronger support for living artists rather than just celebrating dead composers and Cold War-era filmmakers.`

const CZECH_REPUBLIC_ISSUES = [
  "DOX Centre and National Gallery anchoring contemporary art scene",
  "Karlovy Vary Film Festival maintaining A-list international status",
  "Prague Spring Festival and Colours of Ostrava showcasing musical diversity",
  "UNESCO sites suffering from over-tourism and commercialization",
  "Brain drain to Western Europe as artists seek better opportunities"
]

// DEMOCRATIC REPUBLIC OF CONGO CULTURE SUMMARY
const DRC_CULTURE = `Brazzaville and Kinshasa were jointly designated African Capitals of Culture 2024-2025, which is symbolically powerful—twin capitals separated by the Congo River, one in Republic of Congo, one in DRC, collaborating on cultural programming despite being in different countries with complicated histories. But here's the brutal reality: there are no commercial art galleries in Kinshasa. Very few museums. No government support for the arts. The National Museum of DRC (MNRDC) opened November 2019 as a modern institution dedicated to preserving Congolese cultural heritage, open Monday-Saturday 9am-3:30pm (closed Sundays), and it's the exception proving the rule. Vitshois Mwilambwe Bondo established Kin ArtStudio in 2011 with an artist residency and the Congo Biennial—that's individual initiative creating infrastructure in the absence of state support. The Academy of Fine Arts in Kinshasa trains students in painting, sculpture, carving, architecture, ceramics, producing the next generation of artists despite minimal resources.

The "Breaking the Mould" exhibition featured 12 emerging DRC artists, predominantly Academy of Fine Arts alumni: Arlette Bashizi, Beau Disundi, Ghislain Ditshekedi, and others. Eddy Kamuanga Ilunga creates vividly colored large-scale paintings depicting young Congolese with bodies scarified in electronic circuit motifs—referencing cobalt mining, the tech industry's reliance on Congolese resources, and bodies as sites of extraction. It's powerful, politically charged work that's gaining international auction attention. There's talk of Kinshasa becoming Africa's next art hub, reminiscent of developments in Dakar, Lagos, Accra. But those cities have commercial galleries, government funding, and collector bases. Kinshasa has talent, desperation, and international speculation. The art market interest feels extractive—foreign buyers discovering "the next big thing" while local artists lack basic infrastructure.

Music is where DRC truly dominates internationally. Congolese rumba—soukous, ndombolo, the infectious dance music born in Kinshasa and Brazzaville—shaped African popular music globally. Artists like Fally Ipupa, Koffi Olomide, and Papa Wemba (RIP) are superstars across francophone Africa. Kinshasa's music scene is vibrant, commercially viable, and culturally central in ways that visual arts aren't. Live music venues, recording studios, international tours—the infrastructure exists for music in ways it doesn't for visual arts or film. But even music operates despite, not because of, government support. Artists self-fund, rely on diaspora networks, and navigate Kinshasa's chaotic informal economy.

Film and theater are minimal. There's no significant film industry—occasional documentaries, rare narrative features, but nothing resembling a production ecosystem or festival circuit. Theater happens in schools and community spaces, drawing on oral storytelling traditions, but without formal venues or funding. The Academy of Fine Arts has programs, but graduates often leave Kinshasa for opportunities abroad. The brain drain is massive: artists who gain international recognition often relocate to Europe or North America because sustainable cultural careers in Kinshasa are nearly impossible.

UNESCO World Heritage Sites in DRC include Virunga National Park, Garamba National Park, Kahuzi-Biega National Park, Salonga National Park, and Okapi Wildlife Reserve—all natural sites, all endangered by poaching, mining, and armed conflict. There are no DRC cultural sites on the UNESCO list, which reflects both the country's biodiversity richness and the international neglect of Congolese cultural heritage. The lack of heritage preservation funding is part of a larger governance crisis: decades of dictatorship under Mobutu, civil wars killing millions, ongoing conflict in the east, and resource extraction enriching elites while infrastructure crumbles.

DRC culture is resilient, innovative, and catastrophically under-resourced. The artists are brilliant—Kamuanga Ilunga's work commands international auction prices, musicians fill stadiums across Africa, Academy graduates produce sophisticated work—but they operate in one of the world's most challenging environments. No galleries, minimal museums, zero government funding, ongoing conflict, and pervasive poverty. The "art hub" speculation feels premature and exploitative: foreign collectors positioning themselves to "discover" Congolese artists while those artists lack basic studios, materials, or exhibition opportunities. Kinshasa could be a cultural powerhouse with investment, stability, and infrastructure. Without those, it's talent struggling to survive, brilliance constrained by circumstance, and international art market voyeurism masquerading as cultural appreciation.`

const DRC_ISSUES = [
  "Kinshasa-Brazzaville designated Capitals of Culture despite minimal infrastructure",
  "Academy of Fine Arts producing artists without gallery ecosystem to support them",
  "Eddy Kamuanga Ilunga and emerging artists gaining international attention",
  "Congolese rumba and soukous dominating francophone African music scene",
  "Zero government arts funding, no commercial galleries, museum infrastructure minimal"
]

async function generateSummaries() {
  console.log('Generating Culture & Arts summaries for countries 27-39...\n')

  const countries = [
    { name: 'Cameroon', code: 'CM', lat: 7.369722, lng: 12.354722, summary: CAMEROON_CULTURE, issues: CAMEROON_ISSUES },
    { name: 'Canada', code: 'CA', lat: 56.1304, lng: -106.3468, summary: CANADA_CULTURE, issues: CANADA_ISSUES },
    { name: 'Chad', code: 'TD', lat: 15.4542, lng: 18.7322, summary: CHAD_CULTURE, issues: CHAD_ISSUES },
    { name: 'Chile', code: 'CL', lat: -35.6751, lng: -71.543, summary: CHILE_CULTURE, issues: CHILE_ISSUES },
    { name: 'China', code: 'CN', lat: 35.8617, lng: 104.1954, summary: CHINA_CULTURE, issues: CHINA_ISSUES },
    { name: 'Colombia', code: 'CO', lat: 4.5709, lng: -74.2973, summary: COLOMBIA_CULTURE, issues: COLOMBIA_ISSUES },
    { name: 'Congo', code: 'CG', lat: -4.0383, lng: 21.7587, summary: CONGO_CULTURE, issues: CONGO_ISSUES },
    { name: 'Costa Rica', code: 'CR', lat: 9.7489, lng: -83.7534, summary: COSTA_RICA_CULTURE, issues: COSTA_RICA_ISSUES },
    { name: 'Croatia', code: 'HR', lat: 45.1, lng: 15.2, summary: CROATIA_CULTURE, issues: CROATIA_ISSUES },
    { name: 'Cuba', code: 'CU', lat: 21.5218, lng: -77.7812, summary: CUBA_CULTURE, issues: CUBA_ISSUES },
    { name: 'Cyprus', code: 'CY', lat: 35.1264, lng: 33.4299, summary: CYPRUS_CULTURE, issues: CYPRUS_ISSUES },
    { name: 'Czech Republic', code: 'CZ', lat: 49.8175, lng: 15.473, summary: CZECH_REPUBLIC_CULTURE, issues: CZECH_REPUBLIC_ISSUES },
    { name: 'Democratic Republic of Congo', code: 'CD', lat: -4.0383, lng: 21.7587, summary: DRC_CULTURE, issues: DRC_ISSUES },
  ]

  try {
    for (const country of countries) {
      console.log(`\n📝 Processing ${country.name}...`)
      console.log(`   Character count: ${country.summary.length}`)

      await prisma.locationSummary.create({
        data: {
          name: country.name,
          type: 'country',
          country: country.code,
          lat: country.lat,
          lng: country.lng,
          category: 'culture',
          summary: country.summary,
          issues: JSON.stringify(country.issues),
          topStories: '[]',
          storyCount: 0,
        }
      })

      console.log(`   ✅ ${country.name} culture summary saved to database`)
    }

    console.log('\n' + '='.repeat(80))
    console.log('✅ ALL CULTURE SUMMARIES SAVED!')
    console.log('='.repeat(80))
    console.log('\nSummary of character counts:')
    countries.forEach(c => {
      console.log(`  ${c.name}: ${c.summary.length} characters`)
    })

  } catch (error) {
    console.error('❌ Error generating summaries:', error)
    throw error
  }
}

generateSummaries()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
