import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const COUNTRIES_ECONOMY = [
  {
    name: 'Rwanda',
    lat: -1.9403,
    lng: 29.8739,
    summary: `Rwanda's $14 billion economy is Africa's development darling—GDP has grown at 7.2% annually since 2000, per capita income has quadrupled to $1,000, and poverty has fallen from 77% in 1994 (post-genocide) to 38% in 2024. In November 2025, Rwanda is pitching itself as "Africa's Singapore": a small, densely populated (14 million people in 26,000 square kilometers), authoritarian state with competent technocrats, zero tolerance for corruption, ambitious infrastructure projects, and a business-friendly environment. Kigali, the capital, is spotless (plastic bags are banned, monthly community clean-up is mandatory), safe (crime rates are among Africa's lowest), and increasingly modern (fiber optic internet, digital payments, glass towers). President Paul Kagame, in power since 2000 and reelected in July 2024 with 99.15% of the vote (his opponent got 0.53%—not a typo), has made Rwanda the poster child for authoritarian developmentalism: GDP per capita growth has averaged 5.1% annually, but political freedoms are nonexistent (Freedom House rates Rwanda "Not Free"), and dissent is crushed. The economy's pillars are coffee and tea exports ($450 million), tourism ($600 million, driven by gorilla trekking permits at $1,500 each), mining ($1.2 billion, mostly tin, tantalum, tungsten, and gold), foreign aid ($1.3 billion annually, 9% of GDP), and remittances ($500 million). But the real growth story is services—finance, telecommunications, transport, and government services account for 52% of GDP. Rwanda is positioning as a regional hub: Kigali hosts conferences, African Union summits, and corporate headquarters; RwandAir connects 28 African cities; and the government has ambitious plans for a $1.3 billion Bugesera International Airport (opening 2028). Yet structural challenges persist: Rwanda imports 70% of what it consumes (fuel, food, machinery), the trade deficit is 15% of GDP, public debt is 73% of GDP, and the economy is heavily dependent on donor goodwill. And then there's the elephant in the room: Rwanda's military involvement in the Democratic Republic of Congo (DRC)—supporting the M23 rebel group—has triggered U.S. and EU sanctions, threatened aid flows, and raised questions about whether Kagame's regional ambitions will derail the development miracle.

Rwanda's economic model is state-led capitalism—the government sets priorities, state-owned enterprises dominate key sectors (energy, water, telecom, aviation), and the ruling Rwandan Patriotic Front (RPF) controls a vast business empire through its investment arm, Crystal Ventures, which owns stakes in construction, hospitality, real estate, media, and logistics. This isn't a free market economy—it's a centrally planned system with private sector participation where permitted. The government's Vision 2050 targets upper-middle-income status ($4,000 per capita by 2035, $12,000 by 2050) and sets sectoral priorities: digitalization (Rwanda has 4G coverage for 98% of the population, fiber optic backbone reaching all districts), financial inclusion (73% of adults have bank accounts or mobile money), and urbanization (60% urban by 2050, up from 23% today). Agriculture still employs 60% of the workforce but contributes only 24% of GDP—productivity is low, farms are small (average 0.7 hectares), and the sector is vulnerable to climate shocks. Coffee and tea are export crops (300,000 smallholders), but global prices fluctuate—coffee averaged $1.80/lb in 2024, down from $2.50 in 2022, squeezing farmers. The government is pushing land consolidation, mechanization, and irrigation, but progress is slow. Mining is lucrative but contested—tin, tantalum, and tungsten (the "3Ts") are used in electronics, and Rwanda is a major supplier. But much of the production comes from artisanal miners (40,000 workers) in dangerous conditions, and there are persistent allegations that Rwanda smuggles minerals from the DRC (where conflict is fueled by resource extraction) and launders them as "Rwandan" exports. Tourism is the pride of the economy—450,000 visitors in 2024 (up from 300,000 in 2019), generating $600 million. Mountain gorilla trekking in Volcanoes National Park is the marquee product ($1,500 permits, booked months in advance), and the government has invested in luxury lodges, ecotourism, and conservation. But the sector is vulnerable—security concerns (DRC border instability), visa costs, and competition from Uganda and Tanzania limit growth.

The fiscal situation is precarious: government revenues are $3.2 billion (23% of GDP), expenditures are $4.1 billion (29% of GDP), leaving a deficit of $900 million (6.4% of GDP). This is financed by borrowing (domestic and international) and donor grants ($1.3 billion, 9% of GDP). Public debt is 73% of GDP ($10.2 billion)—manageable but rising, and 60% is external (owed to China, World Bank, IMF, and bilateral creditors). Rwanda's largest creditor is China ($2.1 billion)—Beijing financed the Kigali Convention Centre, roads, fiber optics, and a planned $800 million Kigali-Bugesera expressway. Debt service consumes 25% of government revenues—a squeeze that limits spending on health, education, and infrastructure. The Rwandan franc has been stable at 1,300-1,350 per dollar (the Central Bank manages a dirty float), but foreign exchange reserves are $1.9 billion (4 months of import cover—the IMF recommends 6 months). Inflation is moderate (5.2% in 2024), driven by food and fuel imports. Monetary policy is tight—the policy rate is 7.5%, and the central bank prioritizes price stability over growth. The external position is weak: exports were $2.3 billion in 2024, imports $5.8 billion, creating a trade deficit of $3.5 billion (25% of GDP). The gap is filled by aid, remittances, and borrowing, but if donor flows dry up or debt becomes unsustainable, Rwanda faces a balance of payments crisis. The business environment is strong—Rwanda ranks 38th globally on the World Bank's Ease of Doing Business (the highest in Africa), and starting a business takes 4 days (compared to 24 days average in sub-Saharan Africa). But the private sector is small—SMEs struggle to access credit (lending rates are 16-18%), and foreign investors dominate (Chinese, Turkish, and Indian firms in construction, mining, and trade).

The DRC crisis is the biggest economic threat: Rwanda's military support for the M23 rebel group (which controls parts of eastern DRC and threatens Goma, a city of 2 million) has triggered international backlash. In October 2024, the U.S. suspended $49 million in development aid and military assistance, citing Rwanda's destabilizing role. The EU and UK are reviewing aid programs, and UN experts accuse Rwanda of profiting from DRC's mineral wealth (cobalt, gold, tin) by facilitating smuggling. Kagame denies the allegations and accuses the DRC of harboring FDLR rebels (remnants of the 1994 genocide perpetrators), but the evidence is damning. If Western donors cut aid (which funds 30% of the budget), Rwanda faces fiscal collapse—social programs (health insurance, education, infrastructure) would be slashed, and the development model breaks. The domestic economy is constrained by scale—Rwanda is tiny, landlocked, and resource-poor (no oil, gas, or significant minerals). Regional integration is critical—Rwanda joined the East African Community (EAC) and is pushing for a single market, but trade barriers (tariffs, customs delays) remain. Rwanda's bet on services (finance, tech, logistics) requires regional stability, but the DRC conflict and Uganda tensions (Kagame and Museveni have a fraught relationship) limit potential. Unemployment is officially 16%, but underemployment is 40%+—millions of young Rwandans (60% of the population is under 25) lack formal jobs, and the informal sector (street vending, small-scale trade) dominates. The government's solution is TVET (technical and vocational training) and entrepreneurship programs, but job creation lags population growth (2.4% annually). Inequality is rising—the Gini coefficient is 0.43 (moderate), but wealth is concentrated in Kigali, and rural areas (80% of the population) remain poor.

Looking ahead, Rwanda's trajectory depends on three factors: donor relations, DRC stability, and economic diversification. If Kagame withdraws support for M23, aid flows resume, and Western investors return, Rwanda can sustain 6-7% growth through 2030. If aid is cut and debt becomes unsustainable, the model collapses. Diversification is slow—manufacturing is 13% of GDP (mostly low-value food processing and textiles), and Rwanda lacks the market size or resources to become an industrial power. The Bugesera airport, set to open in 2028, is a $1.3 billion bet on Rwanda as a regional transit hub, but success depends on RwandAir's competitiveness and Kigali's attractiveness to tourists and businesses. Kagame's succession is the wildcard—he's 67, and while he amended the constitution to allow him to rule until 2034, his eventual exit will test the system. The RPF's dominance is total, but without Kagame's personal authority, factionalism could emerge. The economic model is brittle—it works under stable, technocratic, authoritarian rule, but it's unclear whether it survives a transition.

**Bottom line:** Rwanda is Africa's development success story—GDP growth, poverty reduction, infrastructure, and governance are impressive. But the model is fragile: small market, landlocked, aid-dependent, and increasingly isolated by the DRC conflict. Kagame has delivered stability and growth, but at the cost of political freedoms and regional tensions. If donors cut aid, the miracle ends. For now, Rwanda remains the continent's best example of authoritarian developmentalism—efficient, clean, and ruthlessly controlled.`,
    issues: ['Aid-dependent model threatened by DRC conflict sanctions', 'Public debt at 73% of GDP and rising', 'Trade deficit 25% of GDP filled by aid and borrowing', 'M23 rebel support straining Western donor relations', '$1.3 billion Bugesera airport bet on regional hub status', 'Small domestic market limits economic diversification']
  },
  {
    name: 'Saudi Arabia',
    lat: 23.8859,
    lng: 45.0792,
    summary: `Saudi Arabia's $1.1 trillion economy is undergoing the most ambitious transformation in modern Middle Eastern history—Crown Prince Mohammed bin Salman's Vision 2030, launched in 2016, aims to diversify away from oil (which accounts for 75% of exports and 60% of government revenue) and build a post-carbon economy anchored by tourism, entertainment, technology, and finance. In November 2025, the early results are mixed: non-oil GDP grew 4.8% in 2024 (outpacing the 1.2% contraction in oil GDP due to OPEC+ production cuts), the Public Investment Fund (PIF) has $700 billion in assets and is building megaprojects (NEOM, Red Sea, Qiddiya), and Saudi society is liberalizing (cinemas opened, women drive, concerts are common, restrictions on dress and mixing have eased). But the scale and cost of Vision 2030 is staggering—$1.3 trillion in planned investments through 2030, financed by oil revenues, sovereign debt (107% of GDP in 2024, up from 5% in 2014), and PIF borrowing ($50 billion raised in international markets in 2024 alone). The economy's fundamentals remain oil-dependent: crude production was 9 million barrels/day in 2024 (below the 12 million bpd capacity due to OPEC+ cuts), oil prices averaged $82/barrel, and hydrocarbon export revenues were $280 billion. The fiscal deficit is projected at 2.3% of GDP in 2025 (down from 4.5% in 2024), but that assumes oil at $80/barrel—if prices fall to $60, the deficit balloons to 8-10%. Saudi Arabia's breakeven oil price (the price needed to balance the budget) is $85/barrel, meaning the state runs deficits at current prices. Unemployment is 7.8% overall, but 15.4% for Saudis (expatriates dominate the private sector), and youth unemployment (ages 15-24) is 22%. The government's Saudization policy mandates hiring citizens in retail, hospitality, and services, but private firms resist (Saudis demand higher wages, shorter hours, and better conditions than expatriates). Population growth is 2.3% annually (36 million people, 60% under 30), and job creation isn't keeping pace. Vision 2030's moonshots—NEOM ($500 billion), a planned 170 km linear city in the desert with flying cars and robot dinosaurs (yes, really); the Red Sea Project ($100 billion), luxury tourism resorts on pristine islands; Qiddiya ($58 billion), an entertainment megacity with theme parks and stadiums—are audacious but unproven. If they succeed, Saudi Arabia becomes the Middle East's tourism and entertainment capital; if they flop, the kingdom is saddled with debt and white elephants.

Saudi Arabia's economy is dominated by the state—the government controls oil (Saudi Aramco, the world's most valuable company, is 98% state-owned), petrochemicals (SABIC), banking (NCB, Al Rajhi), telecoms (STC), and utilities. The private sector is mostly expatriate-driven (12 million foreign workers, 33% of the population): construction, retail, hospitality, and services. Vision 2030's core strategy is twofold: (1) diversify revenue sources by developing non-oil sectors (tourism, entertainment, technology, finance, logistics) and (2) reduce reliance on government employment by growing the private sector. Saudi Aramco is the economic engine—it earned $160 billion in net profit in 2024 (the world's most profitable company), produces 9 million bpd of crude, and owns the world's largest refining and petrochemical complex (Motiva, Yasref). Aramco's 2019 IPO (1.5% of shares listed on Tadawul, Riyadh's stock exchange) raised $29 billion, the largest IPO ever, and the company's market cap is $2.1 trillion. The PIF, chaired by MBS, is Vision 2030's financial architect—it manages $700 billion (up from $150 billion in 2016) and invests domestically (NEOM, Red Sea, Qiddiya, sports clubs) and internationally (stakes in Uber, Lucid Motors, Newcastle United FC, LIV Golf). The PIF raised $50 billion in 2024 via bond issuances (international investors bought eagerly, attracted by high yields and Saudi Arabia's AA- credit rating), but the fund's liabilities are mounting—it's financing megaprojects that won't generate returns for a decade, and if oil revenues fall, the PIF must choose between slowing projects or taking on more debt. The government's fiscal policy is expansionary: spending was $330 billion in 2024 (30% of GDP), focused on infrastructure, subsidies (energy, water, healthcare, education are heavily subsidized), and Vision 2030 projects. Revenues were $322 billion (oil $200 billion, non-oil taxes $105 billion, other $17 billion), leaving a $8 billion deficit (0.7% of GDP). But public debt is 107% of GDP ($1.18 trillion)—among the highest in the Gulf, and rising. Debt service costs are $45 billion annually (14% of spending), squeezing other priorities.

The non-oil economy is growing but still small: tourism generated $70 billion in 2024 (6.4% of GDP), up from $30 billion in 2019, driven by religious tourism (Hajj and Umrah pilgrims, 13 million visitors in 2024), regional tourists (Saudis and Gulf nationals vacationing domestically), and new attractions (AlUla, Red Sea resorts, Riyadh Season entertainment festivals). The government's target is 150 million tourists by 2030 (vs 100 million in 2024), but infrastructure is incomplete (hotels, roads, airports are being built), and Saudi Arabia's reputation for social restrictions (alcohol is banned, dress codes apply, religious police still exist) limits appeal to Western tourists. Entertainment and sports are growth bets—Saudi Arabia hosts Formula 1, heavyweight boxing (Fury vs Usyk rematch in Riyadh, May 2025), LIV Golf (the PIF-funded breakaway league), and top-tier football (Cristiano Ronaldo plays for Al-Nassr on a $200 million/year contract). This is "sportswashing"—using sports to improve Saudi Arabia's image and distract from human rights abuses (the 2018 murder of journalist Jamal Khashoggi, the Yemen war, the repression of dissidents). But it's also economic strategy—sports and entertainment create jobs, attract investment, and position Saudi Arabia as a global destination. Technology is nascent—the government is building a tech ecosystem (startups, venture capital, R&D), and Saudi Arabia's startup funding hit $2.5 billion in 2024 (up from $500 million in 2020). But the ecosystem is immature, and most "Saudi" startups are founded by expatriates or foreigners attracted by subsidies. The financial sector is sophisticated—Tadawul (the stock exchange) has a market cap of $3.2 trillion (the largest in the Middle East), and Riyadh is competing with Dubai to be the region's financial capital. But Dubai's advantages (free trade, liberal social environment, global connectivity) are hard to overcome.

The risks are existential: oil dependence, debt, megaproject execution, and geopolitics. If oil prices fall below $60/barrel (due to global recession, renewables scaling, or OPEC+ collapse), Saudi Arabia faces fiscal crisis—the government would slash spending, delay projects, and potentially default (though this is unlikely given reserves and borrowing capacity). The megaprojects are high-risk—NEOM's $500 billion price tag is speculative (no comparable projects exist), and if tourists and investors don't come, it's a desert ghost town. Critics note that Saudi Arabia's tourism ambitions ignore realities: alcohol bans, strict social codes, and regional instability (Yemen, Iran tensions) limit appeal. Execution risk is huge—Saudi bureaucracy is slow, corruption persists (despite MBS's anti-corruption purge in 2017, which was also a power consolidation), and imported labor and expertise (expats, consultants, contractors) dominate projects. Saudization is failing—private sector firms evade quotas (they hire Saudis on paper but don't employ them, or they hire unqualified Saudis and keep expatriates to do the work), and unemployed youth are frustrated. Politically, MBS has consolidated power—his father, King Salman (88), is in declining health, and MBS is de facto ruler. But succession is uncertain: MBS is 39, and if he rules for 40+ years (possible), Saudi Arabia is locked into his vision. If he's removed or dies, Vision 2030 could be abandoned. Geopolitics matters: Saudi-Iran tensions eased (China-brokered diplomatic normalization in 2023), but mistrust remains. The Yemen war (2015-2025) cost $250 billion and damaged Saudi Arabia's reputation. Relations with the U.S. are transactional—Biden was cold (he called Saudi Arabia a "pariah" over Khashoggi), but Trump is warm (he visited Riyadh on his first foreign trip, and Saudi Arabia bought $100 billion in U.S. weapons). Relations with Israel are warming—Saudi Arabia is negotiating normalization (contingent on Palestinian statehood progress), and economic ties (tech, defense, trade) are deepening covertly.

**Bottom line:** Saudi Arabia is betting $1.3 trillion that Vision 2030 works—that oil money can build a post-oil economy before the oil runs out (or demand collapses). The scale is unprecedented, the ambition is audacious, and MBS is all-in. Non-oil growth is real (4.8% in 2024), tourism is booming, and society is liberalizing. But debt is 107% of GDP, the breakeven oil price is $85/barrel, and megaprojects are unproven. If oil stays above $80, Saudi Arabia has a decade to make this work. If prices crash, the kingdom faces a reckoning. For now, MBS is building—NEOM's steel and glass towers rising from the desert, Red Sea resorts under construction, Riyadh transforming into a megacity—but the jury's out on whether Vision 2030 is genius or hubris.`,
    issues: ['Vision 2030 requires $1.3 trillion through 2030', 'Public debt surged to 107% of GDP from 5% in 2014', 'Fiscal breakeven oil price at $85/barrel', 'NEOM megaproject costing $500 billion faces execution risk', 'Youth unemployment at 22% despite Saudization push', 'Oil dependence remains at 75% of exports']
  },
  {
    name: 'Senegal',
    lat: 14.4974,
    lng: -14.4524,
    summary: `Senegal's $31 billion economy is West Africa's stability anchor—one of the region's few functioning democracies, a peaceful presidential transition in March 2024 (Bassirou Diomaye Faye won with 54% in the first round), and a reputation for transparent governance. But in November 2025, Senegal is at an economic turning point: offshore oil and gas production begins in 2024-2025 (the Sangomar oil field and Greater Tortue Ahmeyim LNG project), potentially transforming the country from agricultural exporter to energy producer. GDP growth was 4.3% in 2024, driven by agriculture (peanuts, fish, horticulture), services (finance, telecoms, tourism), and construction (Dakar's infrastructure boom). But structural challenges persist: 38% poverty rate (7 million of 18 million people), youth unemployment at 25%, a fiscal deficit of 5.5% of GDP, public debt at 73% of GDP, and an economy heavily dependent on imports (70% of food, all fuel). The new government, led by President Faye and Prime Minister Ousmane Sonko (the charismatic populist who was barred from running but dominates policy), promised a "left turn"—renegotiating mining and fishing contracts, increasing taxes on extractive industries, boosting social spending, and auditing the previous government's finances. In November 2024, Faye's government announced that an audit revealed Senegal's actual debt is $2 billion higher than reported (83% of GDP, not 73%), triggering credit rating downgrades and investor panic. The government has walked back some radical promises (no expropriation of foreign assets, no tearing up oil contracts), but uncertainty lingers. Senegal's challenge is managing the oil and gas windfall—estimated at $1 billion annually by 2026—without falling into the resource curse (corruption, Dutch disease, authoritarian backsliding) that has plagued Nigeria, Angola, and Equatorial Guinea. The country's democratic institutions are strong (Freedom House rates it "Free"), civil society is active, and the press is vibrant, but oil wealth tests even the best systems. If Faye's government invests oil revenues wisely (infrastructure, education, healthcare, diversification) and maintains transparency, Senegal could become West Africa's success story. If corruption, mismanagement, or elite capture dominate, the oil curse looms.

Senegal's economy is service-driven (60% of GDP)—finance, telecoms, transport, trade, and government services dominate. Agriculture employs 60% of the workforce but contributes only 17% of GDP—productivity is low, rainfall is erratic, and farms are small (average 2 hectares). Peanuts are the signature crop (1.7 million tons annually, 60% of exports), but global prices are volatile ($500-$900 per ton), and Senegalese farmers lack processing infrastructure (most peanuts are exported raw to Europe and China, where they're processed and sold back to Africa at higher prices). Fishing is the second pillar—Senegal's coastline (700 km on the Atlantic) yields 500,000 tons annually (sardinella, tuna, octopus), generating $500 million in export revenues. But overfishing is a crisis—foreign trawlers (Chinese, EU, Russian) have decimated fish stocks, and artisanal fishermen (100,000 workers) struggle to compete. The Faye government has pledged to renegotiate fishing licenses (currently, foreign fleets pay $30 million annually for access—absurdly low) and enforce quotas, but China and the EU have leverage (they provide aid and investment), and Senegal needs foreign exchange. Tourism is growing—1.9 million visitors in 2024 (up from 1.5 million in 2019), drawn by beaches (Saly, Cap Skirring), culture (Gorée Island, Saint-Louis), and stability. But infrastructure is poor (roads, hotels, airports), and Senegal competes with Morocco, Ghana, and Kenya for African tourism dollars. The formal private sector is small—dominated by French firms (telecoms, banking, utilities) and Lebanese traders (retail, import-export). Dakar's port handles 80% of Senegal's trade and is a regional hub (serving Mali, Mauritania, and landlocked Sahel countries), generating $1.2 billion in revenues.

Oil and gas are game-changers: the Sangomar oil field, operated by Woodside Energy (Australia), began production in June 2024, producing 100,000 barrels per day (ramping to 150,000 bpd by 2026). At $80/barrel, that's $12 million/day in revenue, or $4.4 billion/year—roughly 14% of GDP. The Greater Tortue Ahmeyim (GTA) LNG project, a joint venture between BP, Kosmos Energy, and Senegal/Mauritania, is producing 2.5 million tons of LNG annually (split equally between the two countries). Senegal's share generates $500 million/year at current prices ($12 per mmBtu). Combined, oil and gas revenues could reach $1 billion annually by 2026—transformative for a country with a $31 billion economy. But risks abound: oil prices are volatile (if crude falls to $60, revenues drop 25%), production depends on foreign operators (Senegal lacks technical capacity), and revenue management is critical. The Faye government has established a sovereign wealth fund (modeled on Norway's) to save oil revenues for future generations, but it's untested—will politicians resist the temptation to raid it for short-term spending? Senegal's institutions are strong, but oil wealth corrupts—Angola, Nigeria, and Chad all promised transparency and failed. The debt audit revelations (actual debt is $2 billion higher than reported) are alarming—they suggest either incompetence or deliberate hiding of liabilities by the previous government. The IMF and World Bank have suspended programs pending clarification, and Moody's downgraded Senegal's credit rating to B2 (junk status), raising borrowing costs.

The fiscal situation is tight: government revenues are $6.2 billion (20% of GDP), expenditures are $7.9 billion (25% of GDP), leaving a deficit of $1.7 billion (5.5% of GDP). This is financed by borrowing (domestic and international) and donor grants. Public debt is officially 73% of GDP ($22.6 billion), but the audit suggests it's 83% ($25.7 billion)—including contingent liabilities (state guarantees for parastatal borrowing). Senegal's largest creditors are China ($3.5 billion, financing roads, ports, and stadiums), the World Bank ($2.8 billion), IMF ($1.5 billion), and France ($1.2 billion). Debt service consumes 35% of revenues—a squeeze that limits spending on health, education, and infrastructure. The Faye government inherited a fiscal mess: the previous government (Macky Sall, 2012-2024) borrowed heavily to finance infrastructure (highways, bridges, the Dakar Regional Express Train), but much spending was wasteful (stadiums for the 2026 Youth Olympics, which were later postponed, leaving empty white elephants). The CFA franc (pegged to the euro at 656 FCFA = 1 euro) is stable, but the peg limits monetary policy flexibility—Senegal can't devalue to boost exports or print money to finance deficits. Inflation is low (3.1% in 2024), but food and fuel prices are high (imports are expensive, and the franc's euro peg makes imports pricier). Foreign exchange reserves are $4.8 billion (5 months of import cover), managed by the Central Bank of West African States (BCEAO), which sets policy for eight francophone countries.

Looking ahead, Senegal's economic future hinges on oil revenue management and governance. If the Faye-Sonko government saves oil windfalls, invests in education (literacy is 60%, well below Ghana's 80% or Rwanda's 75%), healthcare (doctor-to-patient ratio is 1:10,000), and infrastructure (roads, electricity, water), Senegal could reach middle-income status ($4,000 per capita) by 2035. But if oil money is stolen, wasted, or squandered on populist giveaways, Senegal joins the list of African oil producers cursed by their wealth. The government's audit and transparency push are promising—Sonko, the prime minister, is a firebrand anti-corruption crusader (he was jailed multiple times by the previous government for criticizing graft), and his base demands accountability. But Sonko's populism (promising free electricity, doubling teacher salaries, banning foreign fishing) is fiscally unsustainable—oil revenues aren't enough to fund these promises without blowing up the deficit. The IMF is negotiating a new program (Senegal's previous $1.5 billion Extended Credit Facility expired in 2024), but demands fiscal discipline, subsidy cuts, and tax reforms—politically toxic. Senegal's private sector is constrained by red tape (starting a business takes 15 days, getting electricity 90 days), high taxes (corporate rate 30%, VAT 18%), and poor infrastructure (electricity is unreliable, internet is slow outside Dakar). The youth bulge is a time bomb—60% of the population is under 25, 300,000 young people enter the labor market annually, but formal job creation is 50,000/year. Many migrate to Europe (via dangerous boat crossings from Senegal to Spain's Canary Islands, costing thousands of lives annually) or join the informal sector. Senegal's democratic strength is its biggest asset—peaceful transitions (four presidents since 2000, all via elections), free press, and active civil society. But oil wealth tests democracies, and vigilance is essential.

**Bottom line:** Senegal stands at a crossroads—oil and gas revenues starting in 2024-2025 offer a path to prosperity, but only if managed well. The Faye-Sonko government's transparency push (audit, renegotiations) is promising, but populist promises risk fiscal explosion. If Senegal invests oil windfalls wisely and avoids the resource curse, it becomes West Africa's success story. If corruption and mismanagement dominate, it becomes another cautionary tale. The institutions are strong, the people are mobilized, and the opportunity is real—but the stakes couldn't be higher.`,
    issues: ['Oil and gas production begins 2024-2025, $1B annual revenues expected', 'Debt audit reveals actual debt 83% of GDP, not 73%', 'Fiscal deficit 5.5% of GDP constraining spending', 'Youth unemployment at 25%, 300,000 enter labor market annually', 'Renegotiating fishing licenses and mining contracts', 'Resource curse risk as oil wealth tests democratic institutions']
  },
  {
    name: 'Serbia',
    lat: 44.0165,
    lng: 21.0059,
    summary: `Serbia's $78 billion economy is the Balkans' largest—a manufacturing and agricultural hub positioned between the EU (its biggest trade partner) and Russia (a political ally), and in November 2025, President Aleksandar Vučić's government is navigating the impossible: maintaining EU accession hopes while refusing to sanction Russia, attracting Western investment while hosting Chinese factories, and claiming economic success (GDP growth 3.8% in 2024, unemployment 9.2%, fiscal surplus 0.5% of GDP) while critics point to cronyism, corruption, and environmental disasters. The economy's strengths are real—Serbia is a regional manufacturing powerhouse (automotive, electronics, steel), a major agricultural exporter (wheat, corn, sunflower, raspberries), and a services hub (IT, finance, logistics). Foreign direct investment was $4.5 billion in 2024 (5.8% of GDP), driven by German carmakers (Mercedes-Benz, Volkswagen), Chinese tech (Huawei, ZTE), and U.S. firms (Microsoft, NCR). The dinar has been stable at 117 per euro (the National Bank of Serbia manages a controlled float), inflation is 4.3% (down from 12% in 2022), and public debt is 52% of GDP (down from 70% in 2020). But underneath, the model is fragile: GDP per capita is $11,600 (68% of the EU average), 23% of the population lives near poverty, youth unemployment is 19%, and the informal economy is 25% of GDP. Vučić's Serbian Progressive Party (SNS) dominates—controlling parliament, the presidency, most municipalities, and state media—and the line between state and party is blurred. Public sector jobs, state contracts, and subsidies flow to loyalists, while opponents face harassment, lawsuits, and exclusion. Environmental protests (against lithium mining by Rio Tinto, pollution from Chinese-owned steel mills) have surged, and Vučić's response is repression—police crackdowns, arrests, and vilification of protesters as "foreign agents." EU membership remains Serbia's stated goal (negotiations began in 2014), but progress is glacial—Serbia refuses to recognize Kosovo (a dealbreaker for the EU), won't sanction Russia (despite EU pressure), and has made minimal progress on rule of law reforms. The EU's leverage is weakening: China invests heavily ($10 billion since 2010 in roads, railways, energy, and factories), Russia supplies gas and political support, and Gulf states (UAE, Saudi Arabia) are buying land and businesses. Vučić is playing all sides, but the strategy has limits—if the EU loses patience, Serbia is stuck in limbo; if Russia collapses or China pivots, Serbia's alternatives narrow.

Serbia's economic model is state-led capitalism—the government owns or controls banks (Komercijalna Banka), energy (NIS, the oil company owned by Russian Gazprom Neft), utilities (EPS electricity, Srbijagas), telecoms (Telekom Srbija), and airlines (Air Serbia, 49% owned by Etihad, effectively controlled by the state). The private sector is dominated by foreign multinationals—German carmakers (Mercedes-Benz invested $1.5 billion in a new factory in Novi Sad, producing 50,000 vehicles annually), Chinese manufacturers (Linglong Tire built a $1 billion factory, Shandong Sunco runs the Smederevo steel mill), and Turkish construction firms. Domestic SMEs are squeezed—they lack access to credit (lending rates are 7-9%, high for the region), face red tape (starting a business takes 12 days, getting permits 20+ days), and compete with subsidized state enterprises and politically connected firms. Agriculture is a strength—Serbia has 3.5 million hectares of arable land (50% of the country), producing 6 million tons of grain (wheat, corn, sunflower) and 300,000 tons of fruit (raspberries, plums, apples). Exports to the EU, Middle East, and Africa totaled $3.2 billion in 2024. But productivity is low (small farms, lack of irrigation, outdated machinery), and young people are leaving villages for cities or emigrating. Manufacturing is the economy's backbone—automotive (Fiat, Mercedes, suppliers), electronics (Leoni, Aptiv), steel (Smederevo), and textiles employ 250,000 workers and generate $8 billion in exports. But wages are low ($700/month average), labor rights are weak (unions are politicized), and environmental standards are lax (Chinese-owned factories pollute rivers and air with minimal oversight). Services are 55% of GDP—retail, finance, telecom, transport, and IT. The IT sector is a bright spot—20,000 software engineers, 1,000 startups, and $2 billion in exports. Belgrade has attracted outsourcing centers (Microsoft, IBM, SAP), and the government offers tax breaks and subsidies to tech firms.

The fiscal position is strong—Serbia ran a 0.5% of GDP surplus in 2024, the first in decades, driven by strong tax revenues (VAT, corporate, income) and controlled spending. Public debt fell to 52% of GDP (from 70% in 2020), helped by GDP growth, fiscal discipline, and debt restructuring. But spending priorities are questionable—the government spends heavily on subsidies ($2 billion annually for state enterprises, agriculture, and politically connected firms), infrastructure (highways, railways, airports), and public sector wages (30% of the budget). Healthcare and education are underfunded (doctor-to-patient ratio is 1:400, hospitals lack equipment, teachers' salaries are $600/month). The dinar's stability is managed—the National Bank of Serbia intervenes in FX markets to prevent volatility, burning through reserves ($26 billion, 8 months of import cover) when needed. Inflation spiked to 12% in 2022 (energy and food prices surged due to Ukraine war), but fell to 4.3% in 2024 as energy prices stabilized and monetary policy tightened (the key rate is 6.5%). Serbia's trade deficit is structural—exports were $27 billion in 2024, imports $37 billion, leaving a $10 billion gap (13% of GDP). The deficit is financed by FDI, remittances ($4.2 billion from the Serbian diaspora), and borrowing. Serbia's largest trade partner is Germany (15% of exports, 12% of imports), followed by Italy, Bosnia, and China. The EU accounts for 60% of trade, but China's share is rising (8% of imports, driven by electronics, machinery, and consumer goods).

The political economy is the core problem: Vučić's SNS dominates every lever of power—parliament (120 of 250 seats), the presidency (Vučić won 60% in 2022), municipalities (SNS controls 90% of local governments), state media (RTS, Pink TV), and the judiciary (judges are politically appointed). Corruption is endemic—Serbia ranks 63rd on Transparency International's Corruption Perceptions Index (down from 87th in 2012). Public procurement is rigged (contracts go to SNS-connected firms), state jobs are patronage (SNS membership is required for public sector employment), and opposition parties are harassed (lawsuits, audits, smear campaigns). Environmental disasters are mounting—protests erupted in 2024 over Rio Tinto's lithium mining project in Jadar Valley (locals fear water contamination and land expropriation) and over pollution from the Smederevo steel mill (owned by Chinese Hesteel, spewing toxins into the air and Danube River). Vučić's response is classic authoritarianism—police crackdowns, arrests of protest leaders, and branding activists as "traitors" and "foreign mercenaries." EU accession is stalled—Serbia opened 22 of 35 negotiation chapters, but progress on rule of law (chapters 23 and 24) is nil. The EU demands that Serbia normalize relations with Kosovo (essentially, recognize it), crack down on corruption, reform the judiciary, and ensure media freedom. Serbia refuses—Vučić says Kosovo recognition is "red line," and nationalist sentiment (stoked by SNS) supports him. The EU's leverage is weakening: Vučić cultivates China (which invests without political conditions), Russia (which supplies gas at subsidized rates and backs Serbia on Kosovo), and Gulf states (UAE bought JAT Airways and is investing in real estate). The EU is Serbia's largest trade partner and donor ($3 billion in pre-accession funds since 2007), but accession is increasingly theoretical.

Looking ahead, Serbia faces three scenarios: (1) Vučić continues balancing EU, China, and Russia, growing the economy modestly (3-4% annually) while entrenching autocracy—this is the most likely outcome; (2) the EU offers a clear accession path (2030 membership), Serbia recognizes Kosovo, and Vučić pivots fully to the West—this is unlikely given domestic politics and Vučić's reliance on nationalism; (3) the EU cuts funding, Serbia drifts toward China and Russia, and the economy stagnates—this is possible if the EU loses patience or if Vučić overplays his hand. The Mercedes factory in Novi Sad, the Linglong Tire plant, and Chinese infrastructure projects show that Serbia attracts investment despite political risks—low labor costs ($700/month), strategic location (Balkan crossroads), and state incentives (subsidies, tax breaks) are attractive. But environmental backlash, brain drain (300,000 Serbs have emigrated since 2012, mostly young and educated), and cronyism undermine growth. The 2027 parliamentary elections will test Vučić—opposition parties are weak, but if protests intensify (environmental, anti-corruption), SNS could lose support. Succession is uncertain—Vučić is 55, and if he exits, the SNS could fracture (no clear number two exists).

**Bottom line:** Serbia's economy is functional but flawed—growth is steady, debt is manageable, and investment flows in. But Vučić's authoritarian model stifles dynamism, corruption is endemic, and environmental disasters loom. EU accession is a mirage—Serbia won't recognize Kosovo, the EU won't admit Serbia without it, and Vučić profits from limbo (playing all sides). For investors, Serbia is a bet on stability over democracy; for Serbs, it's a trade-off between modest prosperity and creeping autocracy. The economy works, but at what cost?`,
    issues: ['EU accession stalled over Kosovo recognition refusal', 'Environmental protests over Rio Tinto lithium mining', 'Cronyism and corruption under Vučić\'s SNS dominance', 'Balancing EU, China, and Russia economically and politically', 'Brain drain with 300,000 emigrating since 2012', 'Chinese investment in factories raising pollution concerns']
  }
]

async function main() {
  console.log('Starting economy batch 8 insertion (Part 2: Rwanda, Saudi Arabia, Senegal, Serbia)...\n')

  for (const country of COUNTRIES_ECONOMY) {
    try {
      console.log(`Processing ${country.name}...`)

      // Check if already exists
      const existing = await prisma.locationSummary.findUnique({
        where: {
          name_type_category: {
            name: country.name,
            type: 'country',
            category: 'economy'
          }
        }
      })

      if (existing) {
        console.log(`  ⚠️  ${country.name} economy writeup already exists, skipping\n`)
        continue
      }

      // Insert the writeup
      await prisma.locationSummary.create({
        data: {
          name: country.name,
          type: 'country',
          lat: country.lat,
          lng: country.lng,
          category: 'economy',
          summary: country.summary,
          issues: JSON.stringify(country.issues),
          topStories: JSON.stringify([]),
          storyCount: 0
        }
      })

      console.log(`  ✅ Successfully added ${country.name} economy writeup\n`)
    } catch (error) {
      console.error(`  ❌ Error processing ${country.name}:`, error)
      console.log()
    }
  }

  console.log('✨ Economy batch 8 (Part 2) insertion complete!')
}

main()
  .catch((e) => {
    console.error('Fatal error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
