import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const POLITICS_SUMMARIES = [
  {
    name: 'Serbia',
    country: 'Serbia',
    lat: 44.7866,
    lng: 20.4489,
    summary: `Serbia in November 2025 is a country in revolt—sort of. President Aleksandar Vučić, who's dominated Serbian politics for over a decade, is facing the most sustained mass protests of his rule. On November 1st, at least 40,000 people (independent observers say twice that) gathered in Novi Sad to honor 15 people killed when a railway station roof collapsed last November—a disaster widely blamed on corruption and shoddy construction linked to Vučić's government. The protests have compounded. Students are leading marches demanding accountability, media freedom, and electoral reform. In March, Prime Minister Miloš Vučević resigned under pressure. Vučić, scrambling, appointed Đuro Macut—a 62-year-old endocrinologist with zero political experience—as the new prime minister. It's a desperate move signaling Vučić's isolation: he can't find a credible political ally, so he's installing a technocratic nobody. But Vučić isn't going anywhere. His party, the Serbian Progressive Party (SNS), still controls parliament. The security services are loyal. State media remains his mouthpiece. And he's a master at playing victim, framing protesters as foreign-backed destabilizers. In November 2025, Serbia is caught in a stalemate: Vučić weakened but entrenched, opposition energized but fragmented, and the European Union watching nervously as a country that's supposed to be on a path to EU membership slides deeper into autocracy. The big question is whether sustained protest can force genuine change—or whether Vučić, like autocrats before him, weathers the storm and tightens his grip further.

**The Novi Sad Disaster and the Collapse of Public Trust**

Let's start with the spark. On November 1st, 2024, the roof of Novi Sad's railway station collapsed, killing 15 people and injuring others. The station had just been renovated as part of a high-profile infrastructure project tied to Chinese investment and Vučić's government. Immediately, questions emerged: Why did the roof collapse? Were safety standards ignored? Who profited from the contracts? The government promised investigations, but the response was seen as inadequate and evasive. Protests erupted, initially focused on accountability for the disaster but quickly broadening. By November 2025, the Novi Sad catastrophe has become a symbol of everything Serbians resent about Vučić's rule: pervasive corruption, crony contracts enriching the politically connected, media suppression preventing scrutiny, and a justice system that protects the powerful. Protesters are demanding prosecutions, transparency in public contracts, and structural reforms. But they're also voicing deeper frustrations—lack of media freedom, rigged elections, environmental degradation, police brutality, and a sense that Vučić's government prioritizes staying in power over governing competently. The protests are student-led, which gives them moral authority. University students have organized marches, sit-ins, and lectures on democracy and rule of law. They're disciplined, non-violent, and media-savvy. This isn't a opposition party protest—it's a grassroots movement, and that makes it harder for Vučić to dismiss as partisan politics. But sustaining momentum is hard. Serbia has seen protests before—in 2018-19, environmental protests in 2020, farmer protests—and Vučić has always outlasted them. He ignores demands, waits for fatigue to set in, then continues as before.

**Vučić's Political Machinery: Weakened but Not Broken**

Aleksandar Vučić has been Serbia's dominant political figure since 2012—first as prime minister, then president since 2017. He's built a hybrid regime: formally democratic with elections and a parliament, but practically autocratic with state media, clientelism, and intimidation ensuring outcomes favor him. His party, the SNS, controls parliament, local governments, state companies, and courts. Elections happen but are marred by irregularities, media bias, and voter intimidation. Opposition parties are fractured and weak. Vučić's base is rural voters, pensioners, public sector employees who fear losing jobs, and nationalist conservatives who see him as defending Serbia's interests. The March 2025 resignation of Prime Minister Vučević was a concession under pressure—a sacrificial lamb to calm protesters. But Vučević was always Vučić's subordinate; real power stays with the president. Appointing Đuro Macut, an apolitical academic, as prime minister is classic Vučić: deflect criticism by installing someone bland and unthreatening, while retaining control behind the scenes. But it signals desperation. Vučić couldn't find a credible political figure willing to take the role amid mounting protests. His coalition is fraying. Some SNS members are privately worried the protests could spiral. Crucially, Vučić's relationship with the international community is strained. The EU has been pressing Serbia on rule of law, media freedom, and judicial independence as conditions for accession. The protests underscore that Serbia is backsliding, not progressing. In early November, European Commission President Ursula von der Leyen told Serbia to "get concrete" about EU membership. Translation: stop the performance, start real reforms. Vučić can't afford full EU rupture, but he also can't afford genuine democratization, which would threaten his power. So he plays for time, making minimal gestures while changing nothing fundamental.

**The Geopolitical Balancing Act: EU, Russia, China**

Serbia's politics are inseparable from its geopolitical position. Officially, Serbia is an EU candidate country pursuing membership. In reality, Vučić has hedged, maintaining close ties with Russia and China while nominally moving toward Brussels. It's a balancing act that's becoming untenable. On Russia, Serbia hasn't joined EU sanctions over Ukraine. Vučić frames this as neutrality, but it's alignment. Russia supplies Serbia with cheap gas and backs Serbia on Kosovo (refusing to recognize Kosovo's independence). Vučić plays to nationalist sentiment by positioning Serbia as independent from Western pressure. But in November 2025, that position is causing friction. Russia publicly rebuked Serbia after Vučić suggested Serbia might sell ammunition to the EU, which could end up supporting Ukraine. Russian Foreign Ministry spokeswoman Maria Zakharova demanded clarification, reminding Vučić of promises that Serbian ammunition wouldn't reach Ukraine. It's a humiliating reminder that Serbia's "neutrality" is constrained by Russian leverage. On China, Serbia has embraced Belt and Road projects—railways, infrastructure, factories. Chinese investment is welcome, and Vučić touts it as proof Serbia doesn't need EU conditionality. But projects like the Novi Sad railway—built with Chinese contractors—are now under scrutiny after the collapse. On the EU, Vučić knows membership is the path to legitimacy and economic access, but he's unwilling to meet democratic standards. The EU's leverage is limited; Serbia can stall indefinitely. Meanwhile, Brussels is frustrated but reluctant to fully abandon Serbia, fearing it would push Belgrade further toward Moscow or Beijing. This geopolitical ambiguity allows Vučić to play sides, but it also means Serbia is stuck—neither fully European, nor aligned with authoritarian alternatives, just drifting.

**Media Freedom, Rule of Law, and Institutional Decay**

Serbia's political system has institutions—parliament, courts, media—but they're hollowed out. State media is pure propaganda, promoting Vučić and demonizing opponents. Independent outlets exist but face harassment, lawsuits, and financial pressure. Investigative journalists are attacked; some have been beaten. Press freedom rankings place Serbia near the bottom of Europe. The judiciary is nominally independent but politically captured. Judges who rule against government interests are sidelined. High-profile corruption cases involving government allies drag on inconclusively or are quietly dropped. The constitutional court is packed with loyalists. Electoral integrity is compromised. The electoral commission is stacked with pro-government figures. Opposition parties complain of voter intimidation, media blackout, and irregularities. International observers note deficiencies but stop short of calling elections fraudulent—it's more subtle, a tilted playing field rather than outright rigging. Parliament is theatrical. The SNS majority rubber-stamps government proposals. Opposition MPs protest, boycott, but lack power. Real decisions are made in Vučić's office, not the legislature. Civil society and NGOs face hostile environments. Organizations receiving foreign funding are labeled "foreign agents" and targeted. Environmental activists, human rights groups, and watchdog organizations operate under constant pressure. The result is a system that looks democratic on paper but functions autocratically. Vučić has centralized power, weakened institutions, and ensured that opposition operates within boundaries he controls. It's not full dictatorship—there's space for dissent, protests happen, independent media survive precariously—but it's deeply illiberal.

**The Bottom Line**

Serbia in November 2025 is at a turning point—or perhaps just another cycle of protest and repression. Vučić is weakened by sustained demonstrations, the Novi Sad disaster, economic stagnation, and international pressure. But he's not collapsing. His machinery of control—state media, clientelist networks, security services—remains intact. The opposition is energized but fragmented, unable to unite around a leader or program. Students lead morally powerful protests, but without political organization, they struggle to translate momentum into change. The big risks for Vučić: First, if protests sustain and broaden—if workers, farmers, and middle-class Serbians join students—his position becomes precarious. Second, if elites fracture—if SNS members defect or security services waver—the regime could crumble fast. Third, if the EU actually conditions progress on democratic reforms and Serbia faces isolation, economic pain could force change. But Vučić is a survivor. He's outlasted protests before. He controls the levers of power. And opposition remains divided. The November 1st Novi Sad anniversary protest was massive, but one protest doesn't topple entrenched autocrats. Watch three things: whether protests sustain through winter or fatigue sets in, whether Vučić prosecutes anyone significant for the Novi Sad disaster (a genuine accountability test), and whether the EU applies real pressure or continues empty rhetoric. Serbia's path is uncertain. It could slide further toward authoritarianism, Vučić weathering this crisis like others. Or, this could be the moment where sustained civic pressure forces a democratic opening. Right now, it's a stalemate—Vučić holds power but is bleeding legitimacy, and Serbians are demanding change without yet forcing it. For a country supposedly on a European path, November 2025 looks more like stagnation and confrontation than progress.`,
    issues: JSON.stringify([
      'Mass protests after Novi Sad railway disaster',
      'Vučić\'s weakened but entrenched rule',
      'Geopolitical balancing between EU, Russia, and China',
      'Institutional decay and media suppression'
    ]),
    topStories: JSON.stringify([
      {
        title: 'How a year of protests changed Serbia and why Vučić is still in power',
        source: 'European Pravda',
        link: 'https://www.eurointegration.com.ua/eng/news/2025/11/4/7224046/',
        pubDate: '2025-11-04'
      },
      {
        title: 'Serbia\'s Vucic angers Russia with comments about selling ammo to EU',
        source: 'Al Jazeera',
        link: 'https://www.aljazeera.com/news/2025/11/7/serbias-vucic-angers-russia-with-comments-about-selling-ammo-to-eu',
        pubDate: '2025-11-07'
      }
    ])
  },
  {
    name: 'Singapore',
    country: 'Singapore',
    lat: 1.3521,
    lng: 103.8198,
    summary: `Singapore in November 2025 is still Singapore—stable, prosperous, efficiently governed, and utterly dominated by the People's Action Party (PAP). In May 2025, Prime Minister Lawrence Wong led the PAP to a decisive victory in general elections, securing 65.6% of the vote and 87 of 97 parliamentary seats. It was Wong's first election as PM after succeeding Lee Hsien Loong in 2024, and it validated his leadership. The opposition Workers' Party held its 10 seats but made no gains. In November, at the PAP's biennial convention, Wong delivered a clear message: the party will defend "clean, honest, and constructive politics" against populism and divisiveness, even at political cost. Singapore's politics are as predictable as its trains—on time, efficient, and with no room for deviation. The PAP has ruled since independence in 1965, and there's no plausible scenario where they lose power. Elections happen, opposition exists, but the system is structured to ensure PAP dominance. That said, Singapore faces pressures. An aging population, rising costs of living, inequality, foreign worker tensions, and younger voters with different expectations are testing the PAP's model. Wong is trying to refresh the party's image—he's younger (relatively), more consultative in style, and emphasizes inclusive governance. But the fundamentals remain: Singapore is a soft authoritarian state with limited political pluralism, where governance effectiveness substitutes for democratic accountability. It works—Singapore is wealthy, clean, safe, and well-run—but it's also a model that doesn't tolerate much dissent.

**Lawrence Wong and the PAP's Renewed Mandate**

Lawrence Wong became Singapore's fourth Prime Minister in May 2024, succeeding Lee Hsien Loong in a carefully managed leadership transition. The May 2025 general election was his first test, and he passed convincingly. The PAP's 65.6% vote share was up 4 percentage points from 2020—a strong endorsement. The party won 87 of 97 seats, maintaining overwhelming dominance. The Workers' Party (WP), Singapore's main opposition, held 10 seats but couldn't expand beyond its traditional strongholds in Aljunied and Sengkang. The election was fought on familiar PAP themes: competent governance, economic stewardship, and social stability. Wong positioned himself as a "fresh" leader for a "changed world," emphasizing the party's ability to adapt while maintaining continuity. The PAP's machinery is formidable—massive resources, control of state media, tight links with grassroots organizations, and the advantages of incumbency. Opposition parties are legal and can campaign, but they face structural disadvantages: limited media access, defamation suits that bankrupt critics, constituency boundaries drawn to favor the PAP, and a Group Representation Constituency (GRC) system that makes it hard for small parties to compete. The WP is the only opposition with parliamentary presence, and even they struggle. In November, at the PAP convention, Wong addressed 1,800 party activists, emphasizing the need to "stand firm" against erosion of Singapore's political standards. He framed the PAP as defenders of constructive politics against populism, divisiveness, and "easy answers." It's classic PAP messaging: we're the adults in the room, opposition is irresponsible. But there's subtext. Wong knows the PAP's vote share, while strong, has declined from 70%+ in earlier decades. Younger voters are less deferential, more willing to vote opposition. The WP's seats prove that dissent exists. Wong's task is to keep the PAP relevant to a changing electorate without loosening the party's grip on power.

**The Political System: Soft Authoritarianism with Efficient Governance**

Singapore's political system is unique: formally democratic with regular elections, but structured to ensure PAP dominance. It's what political scientists call "competitive authoritarianism" or "soft authoritarianism"—the opposition can exist and compete, but the playing field is tilted so heavily that the ruling party almost never loses. Here's how it works: The PAP controls the state apparatus, state media, and the courts. Critical journalism exists in some outlets, but defamation laws (with harsh penalties) chill investigative reporting. Opposition politicians who speak too boldly face lawsuits that can bankrupt them. Lee Kuan Yew famously bankrupted opposition figures this way, and the tactic continues. The GRC system requires parties to field teams of candidates (usually 4-6 people) to contest electoral districts. This makes it hard for opposition parties with limited resources to compete—you need multiple strong candidates and significant funding. The PAP argues it ensures minority representation (each GRC must include a minority candidate), but critics say it's designed to lock out opposition. Electoral boundaries are redrawn before elections by a nominally independent commission, but adjustments consistently favor the PAP. The Internal Security Act allows detention without trial for security threats—it's rarely used now, but its existence creates a chilling effect. NGOs, civil society, and foreign funding for political activities are tightly controlled. Public assemblies require permits, which are often denied. The result: political opposition operates within narrow bounds. You can criticize policies, contest elections, and hold alternative views, but stepping outside acceptable limits brings swift legal and financial consequences. The PAP's legitimacy rests on performance: Singapore is one of the world's wealthiest countries per capita, corruption is virtually nonexistent, infrastructure is world-class, crime is low, education is excellent, and governance is efficient. The social contract is: accept PAP dominance, and we'll deliver prosperity and stability. For decades, Singaporeans accepted this bargain. But it's being tested.

**Emerging Challenges: Cost of Living, Inequality, and Generational Shifts**

Singapore's governance model is under strain. First, cost of living. Singapore is one of the world's most expensive cities. Housing costs are astronomical despite public housing (HDB flats) for most citizens. Healthcare, education, and childcare are costly. Inequality is rising—Singapore has high GDP per capita, but wealth is concentrated. Lower-income Singaporeans and migrant workers face precarity. The PAP has responded with targeted subsidies, wage credits, and social support, but there's a sense that the benefits of growth aren't shared equitably. Second, immigration and foreign workers. Singapore's economy depends on foreign labor—from high-skilled expats to low-wage construction and domestic workers. Citizens resent competition for jobs and space. The PAP walks a tightrope: businesses need labor, but voters want restrictions. Anti-foreigner sentiment periodically flares, and the PAP adjusts policies to placate voters. Third, generational shifts. Older Singaporeans remember the PAP transforming Singapore from a post-colonial backwater to a global city. They're loyal. Younger Singaporeans, born into prosperity, take stability for granted and want more political voice, social freedoms, and diversity. They're more willing to vote opposition, demand accountability, and question PAP paternalism. The WP's strength in younger, educated constituencies reflects this. Fourth, political pluralism. Even within the PAP's dominance, there's growing sentiment that some opposition in parliament is healthy. The WP's presence provides mild checks—questioning ministers, raising alternative views. Some voters intentionally vote WP not to oust the PAP, but to ensure the PAP isn't complacent. Wong's response has been to emphasize renewal—bringing in younger PAP candidates, consulting more widely, and adjusting policies. But the party's instinct is control, not pluralism. The PAP sees itself as indispensable to Singapore's success and views strong opposition as dangerous.

**Foreign Policy and Geopolitical Pressures**

Singapore's politics are also shaped by its geopolitical position. A tiny city-state surrounded by larger neighbors (Malaysia, Indonesia), Singapore has always prioritized security, stability, and neutrality. It maintains strong defense capabilities, close ties with the U.S., and pragmatic relations with China. Wong's government continues this balancing act. Singapore hosts U.S. military assets, supports American presence in the region, but also engages deeply with China economically. It's walking a tightrope as U.S.-China tensions rise. Domestically, the PAP uses external threats to justify strong governance—Lee Kuan Yew's famous argument that Singapore's survival requires disciplined, centralized leadership because it's surrounded by potential adversaries. Ethnic tensions in the region (Singapore is majority Chinese in a Malay-majority region) also inform the PAP's emphasis on racial harmony and social cohesion. The PAP's legitimacy is tied to external competence: maintaining Singapore's relevance as a global financial hub, logistics center, and diplomatic player. Any perception that Singapore is losing its edge—if Hong Kong recovers, if regional rivals rise, if global trade shifts—would threaten the PAP's narrative.

**The Bottom Line**

Singapore in November 2025 is stable, prosperous, and firmly under PAP control. Lawrence Wong has a strong mandate, the opposition is contained, and governance remains efficient. The PAP isn't facing any existential threat. But the model is being tested by rising costs, inequality, generational change, and demands for more political voice. Wong's challenge is to adapt the PAP without loosening its grip—to appear consultative while maintaining dominance, to refresh the party without empowering opposition. So far, he's succeeding. The May 2025 election was a validation. The November convention messaging emphasized continuity and defending PAP values against populism. But the PAP's long-term vulnerability is complacency. If governance performance slips, if economic growth stalls, if inequality worsens, or if younger voters demand real pluralism, the party's legitimacy could erode. The WP's 10 seats are a warning sign—limited, but proof that dissent exists. Watch three things: whether the PAP continues delivering economic growth and managing cost-of-living pressures, whether opposition can expand beyond the WP's strongholds in future elections, and whether younger Singaporeans push for more political openness. For now, the PAP is secure. Singapore's politics are stable and predictable. But stable doesn't mean static, and the pressures building beneath the surface could, over time, challenge the model that's worked for sixty years. Lawrence Wong's task is to ensure the PAP remains indispensable—and that's harder in 2025 than it was in 1965.`,
    issues: JSON.stringify([
      'PAP dominance and Lawrence Wong\'s mandate',
      'Soft authoritarianism and limited political pluralism',
      'Rising costs, inequality, and generational shifts',
      'Geopolitical balancing between US and China'
    ]),
    topStories: JSON.stringify([
      {
        title: 'Singapore\'s PAP scores decisive victory in general election',
        source: 'The Diplomat',
        link: 'https://thediplomat.com/2025/05/singapores-pap-scores-decisive-victory-in-general-election',
        pubDate: '2025-05-03'
      },
      {
        title: 'Lawrence Wong addresses PAP convention on party values',
        source: 'Mothership',
        link: 'https://mothership.sg/2025/11/pap-convention-2025-lawrence-wong/',
        pubDate: '2025-11-09'
      }
    ])
  },
  {
    name: 'Slovakia',
    country: 'Slovakia',
    lat: 48.6690,
    lng: 19.6990,
    summary: `Slovakia in November 2025 is sliding toward authoritarianism, and Prime Minister Robert Fico is accelerating the descent. Fico returned to power in October 2023 after winning elections on a populist, pro-Russia platform, and he's spent the last two years systematically dismantling Slovakia's democratic institutions. In November 2025, his government abolished the Velvet Revolution holiday—the commemoration of Slovakia's peaceful transition to democracy in 1989—as part of austerity measures. It's symbolically brutal: Fico is erasing the democratic legacy while consolidating power. His coalition holds just a one-seat majority in parliament (76 of 150 seats), making it the most fragile government Slovakia has had in years. Fico himself has publicly warned that early elections are increasingly likely. But fragility hasn't made Fico cautious—if anything, he's doubling down. He's attacking the press, purging the judiciary, cozying up to Russia, blocking EU support for Ukraine, and embracing far-right rhetoric. Reporters Without Borders put Fico on its 2025 list of "Press Freedom Predators," ranking Slovakia 38th globally—a precipitous drop. In November, Slovakia opposed using frozen Russian assets to support Ukraine. The EU is watching nervously as a member state drifts into Viktor Orbán's orbit. Slovakia's politics in November 2025 are defined by one question: can democratic institutions survive Fico's assault, or is Slovakia becoming the next Hungary—a member of the EU in name, but an illiberal democracy in practice?

**Fico's Fourth Government: Fragile but Dangerous**

Robert Fico has been Slovakia's dominant political figure for two decades—serving as prime minister from 2006-2010, 2012-2018, and now since October 2023. He's a populist chameleon: once center-left, now nationalist and pro-Russia. His current coalition includes his own Smer-SD party, the nationalist Slovak National Party (SNS), and the centrist Hlas party. Together they hold 76 seats—a razor-thin majority. The government is fragile. Internal tensions are constant, with coalition partners disagreeing on policy and jockeying for influence. In November 2024, Fico publicly warned at a Smer-SD party congress that early elections might be necessary, and that warning looks more realistic by the month. Individual MPs have threatened to defect over controversial policies. Losing even one vote could collapse the government. But Fico's political instincts are sharp. Rather than moderating to hold his coalition together, he's radicalizing—using nationalist rhetoric, anti-EU sentiment, and pro-Russia positions to rally his base and distract from governance failures. It's a high-risk strategy: if the coalition collapses, Fico could lose power. But if he consolidates his base and intimidates opponents, he could govern through fear and polarization. The abolition of the Velvet Revolution holiday is telling. Officially, it's a cost-cutting measure—Slovakia is facing budget pressures. But the symbolism is unmistakable. The Velvet Revolution is Slovakia's foundational democratic moment, when Czechs and Slovaks peacefully overthrew communism. Erasing it from the calendar signals Fico's contempt for liberal democracy. It's a middle finger to Slovakia's pro-European, pro-democracy opposition.

**Attacking Democratic Institutions: Media, Judiciary, Civil Society**

Fico's playbook is familiar—it's Hungary's Viktor Orbán, Poland's former PiS government, and illiberal populists across Europe. Step one: capture the media. Slovakia's public broadcaster RTVS is being restructured, with government loyalists replacing independent journalists. Private media faces legal harassment, advertising boycotts from state companies, and political pressure. Investigative journalists who expose corruption are attacked publicly by Fico, labeled as "foreign agents" or "Soros puppets." In October 2025, Reporters Without Borders included Fico on its Press Freedom Predators list, citing his government's systematic efforts to undermine media independence. Slovakia dropped to 38th in press freedom rankings—shocking for an EU member. Step two: control the judiciary. Fico's government is pushing judicial reforms that give the ruling coalition more control over judicial appointments and prosecutions. The goal is to shield Fico and his allies from corruption investigations and to weaponize courts against opponents. Slovakia's Prosecutor General, appointed under the previous government, is under political pressure. Step three: intimidate civil society. NGOs critical of the government face funding cuts, audits, and smear campaigns. Pro-democracy activists, environmental groups, and human rights organizations operate in an increasingly hostile environment. The message is clear: dissent is dangerous. Fico's government presents these moves as defending Slovakia's sovereignty against "Brussels bureaucrats" and "foreign interference." It's nationalist rhetoric that resonates with portions of the electorate—especially older, rural, and conservative voters who feel left behind by globalization and EU integration.

**Pro-Russia Stance and EU Tensions**

Fico's most controversial position is his pro-Russia stance. Unlike most EU leaders, Fico opposes sanctions on Russia and military aid to Ukraine. In November 2025, Slovakia blocked a proposal to use frozen Russian assets to support Ukraine, arguing it violates international law. Fico has visited Moscow, praised Putin, and framed the Ukraine war as a Western provocation. This puts Slovakia at odds with the EU and NATO. The EU has been funding Ukraine's defense and imposing sanctions on Russia. Slovakia, as an EU and NATO member, is supposed to align with those positions. But Fico sees political advantage in defying Brussels. His base is euro-skeptic and views the war in Ukraine as a distant problem that's driving up energy costs and inflation. By positioning himself as defending Slovak interests against EU overreach, Fico shores up nationalist support. But it's risky. Slovakia depends on EU funds for infrastructure, development, and economic stability. Brussels has mechanisms to pressure member states—withholding funds, triggering rule-of-law procedures, and applying diplomatic pressure. If Slovakia continues drifting toward Russia and undermining EU unity, consequences could follow. For now, the EU's leverage is limited. Slovakia is a member state, and expelling a member is practically impossible. But if Fico aligns too closely with Russia, he risks isolating Slovakia economically and diplomatically.

**Economic Troubles and Austerity**

Slovakia's economy is struggling, and Fico's government is implementing austerity measures—tax increases, spending cuts, and subsidy reductions. Inflation has hit household budgets, energy costs are up, and economic growth is sluggish. Fico promised populist giveaways during the 2023 campaign, but fiscal reality has forced painful choices. The abolition of the Velvet Revolution holiday was framed as cost-cutting, though the savings are negligible. More significant are cuts to public services, education, and healthcare. Public sector workers are striking, teachers are underpaid, and hospitals face shortages. Economic pain creates political risk. If living standards decline and unemployment rises, Fico's base could turn on him. His coalition partners, especially the centrist Hlas party, are nervous about being blamed for unpopular austerity. But Fico's response is to scapegoat—blaming the EU, Brussels, Ukraine, and opposition for Slovakia's problems. It's classic populist deflection: distract from governance failures by stoking cultural and nationalist grievances.

**The Opposition and the Possibility of Collapse**

Slovakia's opposition is fragmented but energized. The Progressive Slovakia party, led by liberal reformers, has strong support among younger, urban, educated Slovaks. They're pro-EU, pro-Ukraine, and anti-corruption. But they struggle to connect with rural and older voters. Other opposition parties—Christian Democrats, centrist liberals—exist but lack cohesion. The opposition's strategy is to highlight Fico's corruption, authoritarian drift, and economic mismanagement. But they face structural disadvantages: limited media access, state resources mobilized against them, and a polarized electorate. However, Fico's fragile coalition creates openings. If even one or two coalition MPs defect, the government collapses. Opposition parties are courting potential defectors, offering immunity or political deals. Fico is aware and has tightened party discipline, but desperation grows as his government flails. In November 2025, rumors swirl of backroom negotiations, coalition tensions, and possible early elections. If the government collapses, Slovakia could hold elections in 2025 or early 2026. Polls suggest a tight race—Fico's Smer-SD retains a base, but opposition parties collectively poll higher. The outcome would hinge on coalition-building and turnout.

**The Bottom Line**

Slovakia in November 2025 is a democracy under siege. Robert Fico's government is systematically attacking media freedom, judicial independence, and civil society while aligning with Russia and defying the EU. His coalition is fragile, holding power by a single seat, but Fico is gambling that nationalist rhetoric and polarization will sustain him. The big risks are threefold. First, if economic pain intensifies and austerity bites, Fico's support could collapse, triggering early elections. Second, if the EU applies real pressure—cutting funds, triggering rule-of-law mechanisms—Slovakia could face economic crisis, forcing political change. Third, if coalition MPs defect, Fico's government falls, and Slovakia gets a chance to reverse course. But the danger is that Fico consolidates power before any of that happens. He's moving fast—capturing media, controlling courts, intimidating opponents. If he succeeds, Slovakia could become the next Hungary: formally democratic, practically autocratic, and an EU member in name only. Watch three things: whether Fico's coalition holds together or collapses, whether the EU applies meaningful pressure on Slovakia's rule-of-law violations, and whether opposition parties can unite and mobilize voters for potential early elections. For now, Slovakia is sliding toward illiberalism. The Velvet Revolution's legacy—peaceful, democratic transition—is being dismantled by a leader who prefers power to principle. November 2025 in Slovakia isn't about democracy thriving; it's about democracy surviving.`,
    issues: JSON.stringify([
      'Fico\'s authoritarian drift and institutional attacks',
      'Pro-Russia stance and EU tensions',
      'Fragile coalition government at risk of collapse',
      'Media freedom crackdown and judicial capture'
    ]),
    topStories: JSON.stringify([
      {
        title: 'Fico included on Reporters Without Borders Press Freedom Predators list',
        source: 'Index on Censorship',
        link: 'https://www.indexoncensorship.org/2025/11/the-dissident-family-challenging-slovakias-robert-fico/',
        pubDate: '2025-10-15'
      },
      {
        title: 'Slovakia opposes use of frozen Russian assets to support Ukraine',
        source: 'Pravda Ukraine',
        link: 'https://ua.news-pravda.com/en/world/2025/11/09/78046.html',
        pubDate: '2025-11-09'
      }
    ])
  },
  {
    name: 'Slovenia',
    country: 'Slovenia',
    lat: 46.1512,
    lng: 14.9955,
    summary: `Slovenia in November 2025 is a small, stable EU democracy with politics that are refreshingly normal—at least by Central European standards. There's no strongman consolidating power, no erosion of democratic norms, no constitutional crises. Instead, there's coalition government, routine legislative gridlock, and preparation for parliamentary elections scheduled for March 2026. Prime Minister Robert Golob, who won a landslide in 2022 with his liberal Freedom Movement party, is governing in coalition and facing typical mid-term pressures: opposition criticism, policy debates, and the challenge of keeping coalition partners aligned. In November 2025, Slovenia is dealing with standard European issues—inflation, cost of living, healthcare funding, climate policy, immigration—without the drama consuming neighbors like Hungary or Slovakia. But don't mistake quiet for irrelevance. Slovenia is navigating significant issues: a far-right party called The Guard was just announced on November 21st, joining a crowded field ahead of the 2026 elections. The Constitutional Court ruled that bans on lesbian couples and single women accessing IVF are unconstitutional, advancing LGBT rights but sparking conservative backlash. And beneath the surface, Slovenia's politics reflect broader European tensions: liberal urban elites versus conservative rural voters, EU integration versus national sovereignty, progressive social values versus traditional identities. Slovenia is small—2 million people—but it's a functioning democracy where elections matter, institutions work, and political competition is genuine. In a region where that's increasingly rare, Slovenia's normality is worth noting.

**Golob's Freedom Movement: Governing After the Landslide**

Let's start with how we got here. In April 2022, Slovenia held parliamentary elections after a turbulent period under right-wing Prime Minister Janez Janša, who had cozied up to Viktor Orbán, attacked media freedom, and polarized the country. Robert Golob—a former energy executive turned political outsider—founded the Freedom Movement just months before the election and won 34% of the vote, crushing Janša's SDS party. It was a stunning upset. Golob's campaign promised green transition, anti-corruption, and reversing Janša's illiberal drift. He formed a coalition government with Social Democrats and the Left party, securing a comfortable majority. By November 2025, Golob's government is mid-term, and the honeymoon is over. Governing is harder than campaigning. Coalition partners have different priorities—the Left pushes progressive social policy, Social Democrats focus on labor and welfare, Golob's Freedom Movement emphasizes green economy and tech investment. Balancing these factions creates friction. Slovenia's economy is sluggish—growth is modest, inflation persists, and cost-of-living pressures strain households. Opposition parties attack Golob as ineffective, out of touch, and better at slogans than delivery. Golob's approval has dipped from post-election highs, though he remains personally popular compared to alternatives. The healthcare system is under strain—long wait times, underfunding, and staff shortages are major public concerns. Education funding debates are contentious. Climate policy—Golob's signature issue—faces resistance from industries worried about transition costs.

**The 2026 Election and the Emerging Far-Right**

Parliamentary elections are scheduled for March 2026, and parties are positioning. The far-right is making moves. On November 21st, 2025, a new party called The Guard was announced—a Catholic nationalist party positioning itself on the hard right. It's joining an already crowded field: Janša's SDS remains the largest opposition party, polling competitively with Golob's Freedom Movement. SDS is conservative, Eurosceptic-lite, and aligned with Europe's right-wing populists. The New Slovenia party represents Christian Democrats—socially conservative, economically centrist. Then there are smaller liberal and centrist parties competing for moderate voters. The Guard's emergence signals that Slovenia, like much of Europe, is seeing far-right mobilization. Catholic nationalism, anti-immigration rhetoric, and cultural conservatism are gaining traction among rural and older voters. The Guard is unlikely to win big in 2026, but even 5-10% of the vote could pull the political center rightward and complicate coalition-building. Polls suggest the 2026 election will be tight. Golob's Freedom Movement and Janša's SDS are running neck-and-neck. No party will win a majority, so coalition negotiations will determine the government. If Golob's bloc (Freedom Movement, Social Democrats, Left) retains a majority, he continues. If SDS and right-wing parties gain more seats, Janša could return—a nightmare for liberals worried about Slovenia following Hungary's path. The Constitutional Court's November ruling on IVF access will be a campaign issue. Liberals celebrate it as progress; conservatives frame it as judicial overreach imposing "gender ideology." Expect culture war battles around LGBT rights, traditional family values, and secularism versus religious identity.

**Democratic Institutions: Functioning but Pressured**

Slovenia's democratic institutions are healthier than most Central European neighbors. The judiciary is independent—the Constitutional Court's IVF ruling proves courts can check government and parliament. Media is pluralistic—there's a mix of public, private, liberal, and conservative outlets. Press freedom is strong; Slovenia ranks well in international indices. Civil society is active, NGOs operate freely, and protests happen without repression. Elections are free and fair, with transparent processes and credible results. But institutions face pressures. During Janša's 2020-2022 tenure, he attacked the judiciary, cut funding to public media, and used state resources to pressure critics. Golob reversed much of that, but the precedent worries democrats—if Janša returns, he could resume where he left off. The judiciary is under strain from caseloads and funding shortages. Public media faces financial pressures and political interference attempts. Civil society organizations worry about populist attacks and funding cuts if the right returns to power. Slovenia's EU membership provides guardrails—Brussels monitors rule-of-law issues, and EU funds are conditional on democratic standards. But Hungary and Poland show those guardrails are imperfect. If Slovenian politics shift right and institutions come under sustained attack, EU leverage is limited.

**Foreign Policy and Regional Position**

Slovenia is firmly pro-EU and pro-NATO, without the equivocation seen in Hungary or Slovakia. Golob's government supports Ukraine strongly, backs EU sanctions on Russia, and aligns with Western positions on China and global security. Slovenia is a small player, but it punches at its weight class—contributing to EU policy debates, participating in NATO missions, and maintaining good relations with neighbors. Slovenia borders Italy, Austria, Hungary, and Croatia. Relations are generally good, though there are occasional border disputes with Croatia and concerns about Hungary's illiberalism spilling over. Slovenia sees itself as a stable, democratic anchor in the Western Balkans region, supporting EU enlargement and integration. Economically, Slovenia is integrated into European supply chains, particularly in manufacturing and automotive sectors. Trade with Germany, Italy, and Austria is critical. EU membership has brought prosperity—Slovenia's GDP per capita is close to the EU average, a success story for post-communist transition. But global economic headwinds—energy costs, supply chain disruptions, inflation—are hitting Slovenia. The government is trying to manage these without the populist scapegoating seen elsewhere. Slovenia's politics benefit from relative prosperity. Unlike Hungary, Poland, or Slovakia, Slovenia lacks the deep economic frustrations that fuel populism. That doesn't make it immune—cost-of-living pressures and inequality could shift politics—but it provides cushion.

**The Bottom Line**

Slovenia in November 2025 is a small, stable democracy functioning normally in a region where that's increasingly exceptional. Robert Golob's government is governing without drama—no authoritarian drift, no constitutional crises, just routine coalition politics, policy debates, and preparation for elections. But normal doesn't mean secure. The March 2026 election is crucial. If Golob's coalition retains power, Slovenia continues its liberal, pro-EU path. If Janša's SDS and right-wing parties win, Slovenia could shift toward Hungary's illiberal model—not overnight, but incrementally. The emergence of The Guard and other far-right parties signals that populist nationalism is growing, fueled by cultural anxieties, immigration fears, and traditionalist backlash against progressive social policies. The Constitutional Court's IVF ruling is a flashpoint. Watch three things: whether Golob can deliver economic improvements and boost his coalition's electoral prospects, whether the far-right gains traction or remains marginal, and whether turnout in March 2026 favors liberals (younger, urban voters) or conservatives (older, rural voters). For now, Slovenia is a success story—a post-communist country that joined the EU, adopted the euro, and built functioning democratic institutions. Its politics are competitive but stable, its institutions resilient but not invulnerable. In a region where democracy is under threat, Slovenia's normality is something to cherish—and protect. November 2025 in Slovenia isn't about crisis; it's about preparation for an election that will determine whether that normality continues or begins to erode.`,
    issues: JSON.stringify([
      'Golob\'s Freedom Movement governing in coalition',
      'March 2026 elections and far-right emergence',
      'Constitutional Court ruling on IVF access',
      'Democratic stability in unstable region'
    ]),
    topStories: JSON.stringify([
      {
        title: 'Far-right Catholic nationalist party The Guard announced ahead of 2026 elections',
        source: 'FEPS Europe',
        link: 'https://feps-europe.eu/slovenian-governmental-parties-lose-election-to-right-wing-opposition/',
        pubDate: '2025-11-21'
      },
      {
        title: 'Constitutional Court rules IVF ban unconstitutional',
        source: 'Freedom House',
        link: 'https://freedomhouse.org/country/slovenia/freedom-world/2025',
        pubDate: '2025-11-15'
      }
    ])
  },
  {
    name: 'Somalia',
    country: 'Somalia',
    lat: 2.0469,
    lng: 45.3182,
    summary: `Somalia in November 2025 is a country at a crossroads—and the wrong turn could be catastrophic. President Hassan Sheikh Mohamud's government is facing three existential crises simultaneously: al-Shabaab's resurgence after the militant group's February 2025 offensive reversed years of military gains; a bitter political standoff with federal member states Puntland and Jubaland over electoral reforms and power-sharing; and the looming withdrawal of AUSSOM (African Union Support and Stabilisation Mission), which has been the backbone of security operations against al-Shabaab. In November 2025, Somalia is holding state-level elections while preparing for federal parliament and presidential elections by May 2026. The government wants to transition from indirect voting (where clan elders select MPs) to universal suffrage—a democratic advance in theory, but deeply controversial in practice. Puntland and Jubaland are boycotting, accusing Mogadishu of centralizing power and undermining federalism. Meanwhile, al-Shabaab controls more territory now than at any point since 2022, having recaptured swathes of central and southern Somalia. External support is dwindling—AUSSOM funding is uncertain, international attention has shifted elsewhere, and Somali security forces are overstretched and underfunded. Somalia has been here before—on the precipice of state collapse. But this time feels different. The government has built institutions, held elections, and made progress. The question is whether that progress is durable or a fragile facade. If Somalia's politics fracture further, if al-Shabaab continues expanding, and if international support evaporates, the country could slide back into chaos.

**The Federal Government vs. Federal Member States: A Crisis of Federalism**

Somalia's political system is federal, with the central government in Mogadishu and five federal member states (FMS): Puntland, Jubaland, Southwest, Galmudug, and Hirshabelle. On paper, it's a power-sharing arrangement. In reality, it's a constant tug-of-war. President Hassan Sheikh Mohamud, elected in May 2022, has pushed for stronger federal authority, arguing that a unified government is necessary to defeat al-Shabaab and govern effectively. But Puntland and Jubaland see this as Mogadishu overreaching and eroding their autonomy. The conflict centers on two issues: electoral reform and resource control. The federal government wants to replace the indirect electoral system (where clan elders choose MPs) with one-person-one-vote universal suffrage. It's framed as democratization, but FMS leaders argue it centralizes power in Mogadishu by weakening clan-based representation. Puntland and Jubaland are boycotting the process, refusing to participate in state-level elections scheduled for November 2025. Without their participation, national elections in 2026 lack legitimacy. Resource control is equally contentious. Somalia's federal structure leaves key questions unresolved: Who controls natural resources? How are revenues shared? What powers do FMS have over security forces? The federal government argues it needs authority to manage resources for national interest. FMS leaders argue Mogadishu can't be trusted and want autonomy to develop their regions. This isn't abstract constitutional debate—it's about power and money. The tensions have become personal. Puntland's President Said Abdullahi Deni and Jubaland's President Ahmed Madobe are strong regional leaders with militias, clan support, and international contacts. They're not subordinates to Mogadishu; they're rivals. Hassan Sheikh has tried cajoling, pressuring, and isolating them, but neither side is backing down. In November 2025, the standoff is unresolved, and it's paralyzing governance. Without federal-FMS cooperation, security coordination against al-Shabaab is compromised, economic development stalls, and political legitimacy erodes.

**Al-Shabaab's Resurgence: The War Is Far from Over**

Somalia made real progress against al-Shabaab in 2022-23. The government, backed by AUSSOM and clan militias, launched an offensive that recaptured towns and territory across central Somalia. For the first time in years, there was optimism that al-Shabaab could be defeated. That optimism is gone. In February 2025, al-Shabaab launched a massive counter-offensive, and the government's gains collapsed. Since then, al-Shabaab has retaken much of the Middle and Lower Shabelle regions, parts of Hiiraan, and expanded influence in Jubaland. The group now controls more territory than at any point since 2022. Why the reversal? First, the government offensive stalled. Somali security forces advanced quickly but couldn't hold territory. Local governance didn't follow military gains, leaving populations vulnerable to al-Shabaab's return. Second, political infighting between Mogadishu and FMS diverted attention and resources from the war. When the federal government and regional states are fighting each other, al-Shabaab benefits. Third, AUSSOM troop levels have declined. International support is waning—donors are fatigued, funding is uncertain, and the African Union mission is set to transition or withdraw. Without AUSSOM, Somali forces struggle. Fourth, al-Shabaab adapted. The group retreated tactically in 2022, avoided direct confrontation, and rebuilt. Now it's stronger, better organized, and exploiting government weaknesses. In November 2025, al-Shabaab's strategy is clear: control territory, provide governance (harsh, but predictable), tax populations, and demonstrate that the federal government can't protect citizens. In areas al-Shabaab controls, it runs courts, collects taxes, and enforces order. It's a shadow state, and for many Somalis exhausted by chaos, al-Shabaab's brutal consistency is preferable to government absence. The government's counter-offensive has stalled. Somali forces are overstretched, underfunded, and poorly equipped. Morale is low. Corruption is rampant—soldiers go unpaid, equipment is sold, and commanders skim funds. International partners are frustrated but unsure how to help. This isn't a war the government is winning.

**Elections in Crisis: Can Somalia Hold Legitimate Polls?**

Somalia is supposed to hold federal parliament and presidential elections by May 2026. But in November 2025, it's unclear if that's possible. The government wants one-person-one-vote elections—a historic step for a country that's never held universal suffrage at the national level. But the logistics are daunting. Much of the country is controlled by al-Shabaab and can't participate. Puntland and Jubaland are boycotting. Voter registration is incomplete. Security can't be guaranteed. Election infrastructure barely exists. Opposition politicians and civil society groups are skeptical, arguing the government is using electoral reform to consolidate power rather than genuinely democratize. They point out that Hassan Sheikh hasn't held transparent consultations, that the process is rushed, and that conditions for free and fair elections don't exist. If elections go ahead without Puntland, Jubaland, and al-Shabaab-controlled areas, they'll be partial and lack legitimacy. If they're delayed, Hassan Sheikh's term technically expires, creating a constitutional crisis. If the government reverts to the old indirect system, it undermines reformist credibility. Somalia is caught in a political trap with no good options. In November, state-level elections are happening, but unevenly. Some FMS are holding polls, others aren't. Opposition figures allege manipulation and fraud. International observers are cautious, noting that while elections are better than none, they're far from meeting democratic standards.

**International Support: Declining and Uncertain**

Somalia has depended on international support since the state collapsed in 1991. AUSSOM (formerly AMISOM) has been the security backbone, preventing al-Shabaab from overrunning Mogadishu and supporting government offensives. But AUSSOM is winding down. Donor fatigue, budget constraints, and shifting priorities mean funding is declining. African Union members contributing troops—Uganda, Kenya, Ethiopia, Burundi—want exit strategies. The mission is supposed to transition to Somali forces, but they're not ready. In November 2025, AUSSOM's future is uncertain. If it withdraws without adequate Somali capacity, al-Shabaab could overwhelm government forces. UN Security Council resolutions have extended the mission, but with reduced mandates and funding. Somalia needs billions for security sector reform, but international donors are hesitant, citing corruption and lack of progress. The U.S. maintains a counterterrorism presence—drones, special forces, airstrikes targeting al-Shabaab leaders. But American focus has shifted to great power competition with China and Russia. Somalia isn't a priority. Europe cares about Somali migration but provides limited security support. Gulf states (UAE, Qatar, Turkey) have competing interests, backing different Somali factions and complicating unity. The result: Somalia is getting less help at a time when it needs more. International partners are frustrated by Somalia's political infighting and lack of capacity. Somali leaders are frustrated by declining support despite progress made. It's a vicious cycle where distrust deepens and cooperation erodes.

**The Bottom Line**

Somalia in November 2025 is fragile, and the trajectory is worrying. The federal government and regional states are locked in a power struggle that undermines governance and security. Al-Shabaab is resurgent, controlling more territory and demonstrating the government's weakness. Elections are approaching but may not be legitimate or feasible. International support is declining just when Somalia needs it most. The big risks: First, if the federal-FMS standoff isn't resolved, Somalia's political system could fracture, with Puntland or Jubaland effectively seceding. Second, if al-Shabaab continues expanding and AUSSOM withdraws, the group could threaten Mogadishu itself, collapsing the government. Third, if elections are bungled—either fraudulent, partial, or delayed—legitimacy evaporates, and Somalia faces constitutional crisis. But Somalia has survived worse. The government is still functioning, elections are happening (imperfectly), and there's international presence. The question is whether Somali leaders can prioritize national interest over factional power, whether security forces can stabilize despite challenges, and whether international partners re-commit to supporting Somalia's transition. Watch three things: whether Hassan Sheikh reconciles with Puntland and Jubaland or the standoff deepens, whether the May 2026 elections happen and gain acceptance, and whether AUSSOM's transition is managed or collapses. Somalia in November 2025 isn't a failed state—yet. But it's on a knife's edge. The choices made in the next six months could determine whether Somalia consolidates as a functional, federal state or slides back into the chaos it's spent two decades trying to escape. For a country that's been at war for a generation, that's a terrifyingly familiar position.`,
    issues: JSON.stringify([
      'Federal government vs. states power struggle',
      'Al-Shabaab resurgence and territorial gains',
      'Electoral crisis and legitimacy questions',
      'Declining international support and AUSSOM withdrawal'
    ]),
    topStories: JSON.stringify([
      {
        title: 'Al-Shabaab offensive reverses government gains since February 2025',
        source: 'War on the Rocks',
        link: 'https://warontherocks.com/2025/06/flailing-state-the-resurgence-of-al-shabaab-in-somalia/',
        pubDate: '2025-06-15'
      },
      {
        title: 'Somalia at a crossroads: Resurgent insurgents, fragmented politics',
        source: 'West Point CTC',
        link: 'https://ctc.westpoint.edu/somalia-at-a-crossroads-resurgent-insurgents-fragmented-politics-and-the-uncertain-future-of-aussom/',
        pubDate: '2025-09-12'
      }
    ])
  },
  {
    name: 'South Africa',
    country: 'South Africa',
    lat: -30.5595,
    lng: 22.9375,
    summary: `South Africa in November 2025 is governed by something unprecedented: a Government of National Unity (GNU) that brings together the African National Congress (ANC) and its historic rival, the Democratic Alliance (DA), along with eight smaller parties. In May 2024, for the first time in 30 years, the ANC lost its parliamentary majority, winning just 40% of the vote. Rather than forming a coalition with the radical left (Economic Freedom Fighters and MK Party), President Cyril Ramaphosa chose the center-right DA, South Africa's second-largest party. It was pragmatic, controversial, and politically risky. In November 2025, the GNU is functioning—but barely. On November 1st, Ramaphosa, Deputy President Paul Mashatile, and GNU leaders gathered for a retreat at Mogale City, trying to manage tensions that are pulling the coalition apart. The DA is furious about Ramaphosa signing the Expropriation Bill and refusing to meet about the National Health Insurance (NHI)—policies the DA vehemently opposes. The ANC's traditional allies—the South African Communist Party (SACP), trade union COSATU, and civil society groups—feel betrayed, accusing Ramaphosa of abandoning the left for neoliberal DA policies. And Ramaphosa himself is squeezed, trying to hold a coalition together while delivering on ANC priorities and managing economic crises. South Africa's politics in November 2025 are defined by this fragile experiment: can historic enemies govern together, or will the GNU collapse into recrimination and paralysis? The stakes are massive—South Africa's economy is struggling, unemployment is at 32%, inequality is staggering, and service delivery failures are fueling public anger. If the GNU fails, South Africa faces political chaos, economic decline, and the potential rise of radical populists. But if it works, it could stabilize South Africa and model how democracies navigate fragmented politics.

**The 2024 Election and the End of ANC Dominance**

Let's start with the earthquake. In May 2024, the ANC won just 40% of the vote—its worst result since 1994. For three decades, the ANC was synonymous with South African governance, winning comfortable majorities based on liberation credentials. But corruption scandals (especially the Zuma years), economic stagnation, electricity blackouts, collapsing public services, and rising unemployment eroded support. The DA won 21%, the new MK Party (formed by Jacob Zuma after his ANC expulsion) took 15%, and the Economic Freedom Fighters (EFF) got 9%. The ANC faced a choice: govern with the radical left (EFF and MK), forming a majority but committing to radical economic transformation, land expropriation, and anti-business policies that would spook investors. Or govern with the DA, forming a centrist GNU that would reassure markets but alienate the ANC's base and traditional allies. Ramaphosa chose the DA. The GNU includes 10 parties total—ANC, DA, and eight smaller parties—collectively holding over 60% of parliament. The DA got significant cabinet positions: Public Works, Communications, and others. It was a bold gambit: prioritize stability and economic pragmatism over ideology. In November 2025, the consequences are playing out.

**GNU Tensions: Policy Clashes and Coalition Fragility**

The GNU is fracturing over policy. In January 2025, the DA formally declared a "dispute" over two issues: the Expropriation Bill and the National Health Insurance (NHI). The Expropriation Bill allows the state to seize land without compensation in certain circumstances—it's central to ANC policy on land reform and redressing apartheid-era dispossession. The DA opposes it as unconstitutional and economically destructive, arguing it will deter investment and undermine property rights. Ramaphosa signed it anyway, ignoring the DA's objections. The NHI is even more explosive. It's the ANC's flagship health policy—creating a single-payer universal healthcare system funded by taxpayers, replacing private medical insurance. The DA calls it fiscally reckless, unaffordable, and a threat to quality healthcare. DA leader John Steenhuisen demanded meetings with Ramaphosa to negotiate changes. Ramaphosa refused to meet. These aren't minor disagreements—they're fundamental ideological clashes. The ANC sees land reform and universal healthcare as moral imperatives tied to redressing apartheid's legacy. The DA sees them as economically reckless policies that will tank growth and investment. Ramaphosa is caught. If he caves to the DA, he betrays ANC principles and loses his base. If he ignores the DA, the coalition collapses. So far, he's gambling he can push ANC priorities through while keeping the DA in the tent by giving them ministerial posts and limited influence. It's a high-wire act. Meanwhile, the ANC's traditional allies feel abandoned. The SACP, COSATU, and civic movements that supported the ANC for decades are now sidelined. The GNU prioritizes "fiscal consolidation" and "pragmatic technocratic" policies—code for austerity, limited spending, and market-friendly reforms. The left sees this as neoliberalism, a betrayal of the working class, and capitulation to capital. They're organizing protests, calling for Ramaphosa's removal, and threatening to break with the ANC entirely. If the ANC loses its traditional base, its electoral future is grim.

**Economic Pressures: Unemployment, Inequality, and Investor Confidence**

South Africa's economy is a mess, and that's the subtext of every political fight. Unemployment is 32% officially, higher if you include discouraged workers. Youth unemployment exceeds 60%. Inequality is among the world's highest—South Africa is one of the most unequal societies on Earth. The electricity grid has collapsed repeatedly, with rolling blackouts (load-shedding) crippling businesses and households. State-owned enterprises like Eskom (electricity) and Transnet (logistics) are dysfunctional, corrupt, and bankrupt. Service delivery is failing—water shortages, crumbling infrastructure, inadequate housing, and collapsing municipalities. The GNU's economic policy rests on fiscal consolidation—reducing deficits, managing debt, and avoiding IMF intervention. It's conservative, and it's what investors want. But it doesn't create jobs, redistribute wealth, or address inequality. The ANC promised radical economic transformation—land reform, nationalization, wealth redistribution. The DA promised business-friendly policies, tax cuts, and deregulation. The GNU's compromise—vague technocratic pragmatism—satisfies neither side and delivers little. Investor confidence is fragile. South Africa's credit ratings are barely above junk status. Capital flight is a constant risk. Foreign investment has dried up. The rand is weak. Businesses are cautious, waiting to see if the GNU can govern or if it collapses into chaos. If the GNU holds, and if economic policy remains predictable, investment might return. If it fractures, South Africa faces capital flight, currency collapse, and debt crisis.

**The ANC's Existential Crisis and the Rise of Populism**

The GNU is the ANC's response to losing its majority, but it's also a sign of the party's deeper crisis. The ANC is no longer the liberation movement that ended apartheid—it's a party fractured by factionalism, tainted by corruption, and struggling to deliver on promises. Zuma's presidency (2009-2018) was catastrophic—state capture, corruption, economic mismanagement. Ramaphosa promised clean governance and renewal, but progress is slow, and the ANC remains divided between Ramaphosa's reformist faction and a corrupt old guard. The rise of MK Party (Zuma's vehicle) and the EFF shows populist alternatives are gaining traction. MK won 15% in 2024 by mobilizing Zulu voters and Zuma loyalists. The EFF mobilizes young, Black, urban voters with radical rhetoric about land, wealth redistribution, and anti-white populism. If the GNU fails and the ANC's support collapses further, South Africa could see radical populists dominate the next election. That would terrify investors, alienate Western partners, and risk economic implosion. But for millions of South Africans living in poverty, the status quo is intolerable. The ANC's challenge is existential: can it deliver enough to retain legitimacy, or does it become another liberation movement that failed in power?

**The Bottom Line**

South Africa in November 2025 is governed by a fragile, historically unprecedented coalition trying to manage overlapping crises: economic stagnation, unemployment, inequality, and collapsing infrastructure. The GNU is holding—barely—but tensions over policy, ideology, and leadership are fracturing it. Ramaphosa is gambling that pragmatic centrism can stabilize South Africa and deliver growth. The DA is betting it can influence policy and prevent ANC radicalism. The ANC's left flank feels betrayed and is mobilizing opposition. The big risks: First, if the DA walks out over Expropriation or NHI, the GNU collapses, forcing new elections that could empower populists. Second, if the ANC's base revolts, the party fractures further, accelerating its decline. Third, if economic conditions worsen—unemployment rises, inequality deepens, service delivery fails—public anger could explode into instability. But there's also a path where the GNU works. If it delivers basic governance, stabilizes the economy, and avoids catastrophic policy mistakes, South Africa could rebuild investor confidence and create conditions for recovery. It's not exciting, but boring competence would be revolutionary after years of dysfunction. Watch three things: whether the DA-ANC tensions explode or stabilize, whether the economy shows improvement or continues declining, and whether the ANC can retain its base or loses ground to populists in the next election. South Africa in November 2025 is at a crossroads. The GNU is an experiment in pragmatic coalition governance amid deep polarization. If it works, South Africa might stabilize. If it fails, the country faces a dangerous drift toward populism, instability, and economic collapse. For now, the jury is out, and the stakes couldn't be higher.`,
    issues: JSON.stringify([
      'Government of National Unity and ANC-DA tensions',
      'Policy clashes over Expropriation Bill and NHI',
      'Economic crisis: unemployment, inequality, service delivery failures',
      'ANC decline and rise of populist alternatives'
    ]),
    topStories: JSON.stringify([
      {
        title: 'GNU leaders hold retreat amid tensions over policy disputes',
        source: 'Africa News',
        link: 'https://theafrican.co.za/sunday-tribune/opinion/2025-11-09-anc-dumps-traditional-allies-for-gnu-to-shape-sas-policy-trajectory/',
        pubDate: '2025-11-01'
      },
      {
        title: 'DA declares formal GNU dispute over Expropriation Bill and NHI',
        source: 'Democratic Alliance',
        link: 'https://www.da.org.za/2025/01/da-declares-formal-gnu-dispute-over-expropriation-bill-and-nhi',
        pubDate: '2025-01-15'
      }
    ])
  },
  {
    name: 'South Korea',
    country: 'South Korea',
    lat: 37.5665,
    lng: 126.9780,
    summary: `South Korea in November 2025 is rebuilding after a political earthquake. In June 2025, Lee Jae-myung of the Democratic Party won the presidency with 51.7% of the vote in a snap election triggered by the impeachment and removal of conservative President Yoon Suk Yeol. Lee's victory—by the largest margin in 28 years and with the highest turnout since 1997—was a resounding rejection of Yoon's disastrous presidency and a mandate for change. But in November 2025, five months into Lee's term, South Korea is still grappling with the trauma of Yoon's brief, bizarre attempt to impose martial law in December 2024. That crisis—when Yoon declared emergency military rule, only to see parliament and the public force him to back down within hours—shattered South Korea's sense of democratic stability. Lee's task is to restore trust in institutions, heal political divisions, and navigate mounting economic and security challenges. And he's doing it with a supermajority in the National Assembly—the Democratic Party controls parliament, giving Lee legislative power his predecessor lacked. But power brings responsibility. If Lee can't deliver on promises of reform, economic revival, and political reconciliation, disillusionment will set in fast. South Korea in November 2025 is a democracy recovering from a near-miss authoritarian moment, trying to figure out how it got there and how to ensure it never happens again.

**Yoon's Fall: Martial Law, Impeachment, and Constitutional Crisis**

Let's start with the chaos. Yoon Suk Yeol won the presidency in 2022 by a razor-thin margin—less than 1%—running as a conservative prosecutor promising to fight corruption and take a harder line on North Korea. But his presidency was a disaster from the start. He faced a hostile National Assembly controlled by the opposition Democratic Party, making governance nearly impossible. His approval ratings plummeted—by late 2024, they were in the 20s. Corruption scandals involving his wife, Kim Keon Hee, eroded credibility. His hardline policies alienated progressives, and his abrasive style alienated moderates. Then came December 3rd, 2024. In a stunning, desperate move, Yoon declared martial law, claiming national security threats and legislative obstruction justified emergency military rule. It was an authoritarian power grab, and it backfired spectacularly. Within hours, the National Assembly convened and voted to lift martial law. Protesters flooded the streets. Military commanders refused to suppress the assembly. By the next day, Yoon backed down, but the damage was done. Impeachment proceedings began immediately. On April 4th, 2025, the Constitutional Court unanimously upheld Yoon's impeachment, formally removing him from office. It was a moment of constitutional crisis—but also a triumph of democratic institutions. Parliament, courts, military, and civil society all rejected authoritarianism. The snap presidential election was scheduled for early June 2025. The campaign was intense, emotional, and existential. Lee Jae-myung, the Democratic Party candidate and a seasoned politician who'd narrowly lost to Yoon in 2022, framed the election as a referendum on democracy. His conservative opponent, Kim Moon-soo, tried to distance himself from Yoon but couldn't escape the association. Lee won decisively—51.7% to 39.3%—and took office in June. In November 2025, Lee's presidency is still defined by that context: rebuilding after Yoon's disastrous attempt to subvert democracy.

**Lee Jae-myung's Presidency: Reform, Reconciliation, and Realpolitik**

Lee's campaign promised three things: political reform to prevent another Yoon, economic revitalization to address inequality and stagnant growth, and pragmatic foreign policy balancing the U.S. and China. In November 2025, he's working on all three—with mixed results. On political reform, Lee pledged to "end the political crisis" and restore trust in institutions. That means accountability for Yoon's actions (legal proceedings are ongoing), reforms to strengthen parliamentary checks on executive power, and rebuilding the judiciary's independence (Yoon had stacked courts with loyalists). Lee's Democratic Party supermajority gives him legislative power to push reforms through. But there's risk: if Lee overreaches, stacks institutions with his allies, or uses his majority to consolidate power, he repeats Yoon's mistakes. On the economy, South Korea is struggling. Growth is sluggish, youth unemployment is high, household debt is massive, and inequality is severe. The "Hell Joseon" sentiment—young Koreans feeling trapped by economic precarity—was a major campaign issue. Lee promised investment in jobs, affordable housing, and social safety nets. He's pushing expansionary fiscal policy, but fiscal space is limited, and inflation concerns constrain spending. Structural reforms—labor market flexibility, corporate governance, chaebol regulation—are politically difficult. Five months in, Lee hasn't delivered transformative economic results, but expectations are high. On foreign policy, Lee is pivoting from Yoon's hardline approach. Yoon had cozied up to Japan and the U.S., taking a tough stance on North Korea and China. Lee is more pragmatic: he supports the U.S.-South Korea alliance but wants to reduce tensions with China (South Korea's largest trading partner) and pursue conditional engagement with North Korea. This is a delicate balance. Washington wants Seoul firmly in the anti-China camp; Beijing wants South Korea to stay neutral; Pyongyang is unpredictable. Lee's trying to maximize South Korea's autonomy without alienating key partners.

**Democratic Consolidation vs. Partisan Revenge**

South Korea's politics are intensely polarized, and Lee faces a dilemma: does he prioritize reconciliation or accountability? His base wants Yoon prosecuted to the fullest extent—treason charges, imprisonment, accountability for the martial law attempt. Conservatives see this as partisan revenge and fear Lee will use the supermajority to crush opposition. Lee's rhetoric has been conciliatory—he speaks of "healing divisions" and "rebuilding consensus"—but actions matter more. Legal proceedings against Yoon are ongoing, and how aggressively Lee's government pursues them will signal his intentions. If it's measured and rule-of-law-focused, it's accountability. If it's vindictive and expansive, it's revenge. South Korea has a history of prosecuting former presidents—nearly every living ex-president has faced corruption charges or imprisonment. It's a pattern that reflects both accountability and political vendetta culture. Breaking that cycle requires restraint, but voters also want justice for Yoon's authoritarianism. Lee's supermajority is both an asset and a liability. It lets him govern effectively without legislative gridlock. But unchecked power tempts overreach. South Korea's democracy depends on institutions—courts, prosecutors, media, civil society—checking executive power. If Lee respects those checks, he strengthens democracy. If he undermines them, he becomes what he opposed.

**North Korea, China, and the U.S.: Geopolitical Pressures**

South Korea's domestic politics can't be separated from geopolitics. North Korea remains a nuclear-armed threat, conducting missile tests and provocations. Under Yoon, South Korea-North Korea relations were frozen, with no dialogue. Lee has signaled openness to conditional engagement—economic incentives for denuclearization, humanitarian aid, and diplomatic contact—but Pyongyang has shown little interest. Kim Jong Un is focused on solidifying ties with Russia and China, not Seoul. China is South Korea's largest trading partner but also a strategic competitor. Yoon angered Beijing by aligning closely with the U.S., participating in AUKUS-adjacent security frameworks, and supporting Taiwan. Lee wants to recalibrate—maintaining the U.S. alliance while repairing economic and diplomatic ties with China. Beijing is watching closely, hoping Lee's pragmatism translates into distancing from Washington. The U.S. wants South Korea as a linchpin of its Indo-Pacific strategy. Washington invested heavily in the U.S.-South Korea-Japan trilateral alignment under Yoon. Lee's election worried American officials, who fear he'll soften on China and North Korea. In November 2025, Lee is reassuring Washington that the alliance is solid while quietly adjusting policy toward Beijing. It's a balancing act with no easy answers. South Korea's security depends on the U.S., but its economy depends on China. Any hard tilt toward one alienates the other.

**The Bottom Line**

South Korea in November 2025 is a democracy that dodged an authoritarian bullet and is now rebuilding. Lee Jae-myung's presidency is five months old, and he's inherited a political system traumatized by Yoon's martial law attempt, an economy struggling with inequality and stagnant growth, and geopolitical pressures from North Korea, China, and the U.S. Lee has a supermajority, a strong mandate, and public goodwill. But he also faces sky-high expectations, deep polarization, and the risk of overreach. The big questions: Can Lee restore trust in institutions without weaponizing them against opponents? Can he deliver economic results that improve ordinary Koreans' lives? Can he balance U.S. alliance commitments with pragmatic engagement with China and North Korea? And can he break South Korea's cycle of prosecuting former presidents and partisan revenge politics? Watch three things: whether Lee governs with restraint or uses his supermajority to consolidate power, whether economic conditions improve or public frustration grows, and whether Lee's foreign policy balancing act holds or collapses under U.S. and Chinese pressure. South Korea's democracy is resilient—it survived Yoon's attempted power grab. But resilience doesn't mean invulnerability. November 2025 is a moment of cautious optimism: Lee has a chance to strengthen democratic institutions, revitalize the economy, and navigate geopolitics wisely. But he could also squander that chance through overreach, partisanship, or policy failures. For a country that's endured dictatorship, war, rapid development, and democratic consolidation, South Korea in November 2025 is writing the next chapter—and it's not yet clear how the story ends.`,
    issues: JSON.stringify([
      'Recovery from Yoon\'s martial law crisis and impeachment',
      'Lee Jae-myung\'s reform agenda and supermajority',
      'Economic challenges: inequality, youth unemployment, growth',
      'Geopolitical balancing between US, China, and North Korea'
    ]),
    topStories: JSON.stringify([
      {
        title: 'Lee Jae-myung wins South Korea presidency in landslide snap election',
        source: 'Al Jazeera',
        link: 'https://www.aljazeera.com/news/2025/5/31/south-koreas-snap-presidential-election-2025-all-you-need-to-know',
        pubDate: '2025-06-03'
      },
      {
        title: 'Constitutional Court upholds Yoon Suk Yeol impeachment',
        source: 'Carnegie Endowment',
        link: 'https://carnegieendowment.org/research/2025/04/yoons-impeachment-and-south-koreas-future',
        pubDate: '2025-04-04'
      }
    ])
  }
]

async function addPoliticsSummaries() {
  console.log('Adding Politics summaries for Batch 8 (Part 2/2)...\n')

  for (const summary of POLITICS_SUMMARIES) {
    try {
      const result = await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: summary.name,
            type: 'country',
            category: 'politics'
          }
        },
        create: {
          name: summary.name,
          type: 'country',
          country: summary.country,
          lat: summary.lat,
          lng: summary.lng,
          category: 'politics',
          summary: summary.summary,
          issues: summary.issues,
          topStories: summary.topStories,
          storyCount: 0,
          updatedAt: new Date()
        },
        update: {
          summary: summary.summary,
          issues: summary.issues,
          topStories: summary.topStories,
          updatedAt: new Date()
        }
      })

      console.log(`✅ ${summary.name} Politics added/updated`)
      console.log(`   ID: ${result.id}`)
      console.log(`   Category: ${result.category}`)
      console.log(`   Summary length: ${result.summary.length} characters`)
      console.log()
    } catch (error) {
      console.error(`❌ Error processing ${summary.name}:`, error)
      throw error
    }
  }

  console.log('Part 2/2 completed successfully!\n')
}

addPoliticsSummaries()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
