// Complete Politics writeups for all 109 remaining countries in Rory Stewart's voice

export const POLITICS_WRITEUPS = {
  "Costa Rica": {
    summary: `# Costa Rica - Politics

You know, Costa Rica has always been the quiet achiever of Central America—no army since 1948, stable democracy, decent living standards—and yet it's facing challenges that would test any government. Rodrigo Chaves, the president who came to power in 2022 promising to shake things up, is governing in a remarkably confrontational style. He's feuding with the Legislative Assembly, clashing with the Supreme Court, and his approval ratings have taken a battering. What's fascinating is that Costa Rica, unlike its neighbors, doesn't have the excuse of being a young democracy or recovering from civil war. This is a country that's been democratic longer than most of Europe, and yet it's experiencing the same populist tensions, the same institutional conflicts, that you see everywhere from Brazil to Poland. The thing to understand is that Costa Rican exceptionalism—this idea that they're different, more stable, more democratic than their neighbors—is being tested by the same forces battering democracies globally: economic stagnation, corruption fatigue, and a president who believes institutions are obstacles rather than guardrails.

## The Big Issue 1: Presidential Power and Institutional Conflict

Chaves came from the World Bank, positioned himself as a technocratic outsider, and won the presidency by attacking the political establishment. Now he's governing like someone who genuinely believes the problem is institutions themselves. He's clashed repeatedly with the Legislative Assembly over budget proposals, with the Supreme Court over constitutional interpretations, and with independent agencies over regulatory authority. This matters because Costa Rica's system is deliberately designed with checks and balances—they abolished the military precisely to prevent strongman politics, and they created strong courts and an independent legislature to prevent presidential overreach. When Chaves attacks these institutions as corrupt or inefficient, he's not wrong about the corruption and inefficiency—Costa Rican politics has plenty of both—but he's undermining the very structures that make Costa Rica stable. The risk is that you hollow out institutional credibility without replacing it with anything better. I've seen this pattern before: a president gets frustrated that courts or legislatures block his agenda, attacks them as illegitimate, and creates a constitutional crisis that damages everyone. The question is whether Costa Rican democratic culture is strong enough to withstand this pressure, or whether Chaves successfully reshapes the system into something more presidential and less balanced.

## The Big Issue 2: Economic Disappointment and the Social Contract

Costa Rica has traditionally offered its citizens a deal: we don't have the natural resources of Venezuela or the industrial base of Mexico, but we'll provide stability, education, healthcare, and environmental protection. That social contract is fraying. Economic growth has been anemic, inequality is rising, and the fiscal situation is genuinely concerning—public debt is high and the pension system is heading toward crisis. Chaves promised economic dynamism but hasn't delivered transformative results. Part of the challenge is structural: Costa Rica is a small economy heavily dependent on tourism, agricultural exports (coffee, bananas, pineapples), and increasingly, medical device manufacturing and tech services. The pandemic devastated tourism, and recovery has been uneven. But part of the problem is also political: Chaves doesn't have a legislative majority, so even when he has good ideas, getting them through Congress is exhausting. What worries me is that Costa Ricans, particularly young Costa Ricans, are losing faith that their country's model works. If you can't afford housing, if good jobs require emigrating, if the pension system won't exist when you retire, why stay? Brain drain is a real issue—educated Costa Ricans leaving for opportunities in the US or Europe—and it's hard to reverse that once it starts.

## The Big Issue 3: The Nicaraguan Refugee Crisis

This doesn't get nearly enough international attention: Costa Rica is absorbing enormous numbers of Nicaraguan refugees fleeing Ortega's increasingly authoritarian regime. We're talking about hundreds of thousands of people crossing into a country of only five million. That's proportionally like Germany taking in... well, Germany did take in a million refugees, but Germany is much larger and richer. For Costa Rica, the scale is genuinely challenging. The refugees need housing, healthcare, education for their children, and work permits. Costa Rica has been remarkably generous, certainly compared to other countries facing similar pressures, but generosity has limits when your own citizens are struggling economically. There's been social tension, resentment in border communities, and political pressure to restrict entry. Chaves has tried to walk a fine line: maintaining Costa Rica's humanitarian reputation while responding to domestic concerns about resources and integration. The international community should be helping more—this is a regional crisis caused by Ortega's repression, and Costa Rica is bearing the burden largely alone. But getting meaningful international support requires diplomatic skill and political capital that Chaves hasn't demonstrated.

## The International Angle

Costa Rica punches above its weight in international forums—it's a founding member of the UN, hosts the Inter-American Court of Human Rights, and has traditionally been a voice for environmental protection and disarmament. But its influence depends on maintaining democratic credibility. If Costa Rica slides into the same institutional conflicts and democratic backsliding you see elsewhere in the region, it loses its distinctive voice. The United States has traditionally seen Costa Rica as a reliable partner and a success story worth supporting, but American attention to Central America is sporadic at best. China has been investing in infrastructure—they funded a new highway, though the project has had problems—and Costa Rica was one of the first Central American countries to recognize Beijing over Taipei. The environmental dimension is crucial: Costa Rica has successfully reforested much of its territory after decades of deforestation, and it's a global leader in renewable energy. Whether it can maintain that environmental leadership while addressing economic pressures will be watched closely by other developing nations trying to balance growth and sustainability.

## The Bottom Line

Costa Rica's exceptionalism is real but fragile. Chaves is testing whether a presidential confrontational style can coexist with strong democratic institutions, and so far, the results are mixed at best. The country needs economic reform, fiscal sustainability, and a plan for integrating refugees, but it also needs to preserve the institutional stability that made it exceptional in the first place. The next few years will determine whether Costa Rica remains Central America's success story or becomes another example of democratic erosion in a troubled region.`,
    issues: ["Presidential Power and Institutional Conflict", "Economic Disappointment and the Social Contract", "The Nicaraguan Refugee Crisis"]
  }
}
