import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const writeups = [
  {
    name: "Brazil",
    lat: -14.2350,
    lng: -51.9253,
    summary: `# Brazil - Economy & Business

Brazil's economy in November 2025 is doing this fascinating thing where it's simultaneously hosting COP30 (the global climate conference), prosecuting coup plotters from the last election, and dealing with a central bank that just raised interest rates to 11.25% because inflation is back above target. (Nothing says "emerging market" quite like political instability mixed with monetary tightening.) Lula's third term is economically complicated: growth is sluggish at 1.8%, the fiscal deficit is widening, and markets are nervous about government spending plans. But here's what's interesting—Brazil's real (the currency, not the adjective) has actually stabilized after years of volatility, corporate profits are strong, and the São Paulo stock exchange is near record highs. The dichotomy is that Brazil the country is messy, but Brazil the market is oddly functional. Foreign investors have this love-hate thing with Brazil: they know it should be rich (massive agriculture, industrial base, educated population), but it keeps finding new ways to underperform. The latest drama involves Petrobras (the state oil company) trying to navigate between Lula's social spending demands and investor pressure for profitability, while China remains Brazil's largest trading partner but the U.S. is trying to pull Brazil closer geopolitically.

## The Big Issue 1: The Petrobras Dilemma—State Oil Company or Social Policy Instrument?

Petrobras is Brazil's most valuable company, a symbol of national energy independence, and also a political football that gets kicked around every election cycle. Under Bolsonaro, it was run somewhat commercially—dividends were paid, investments were made, market pricing for fuel prevailed. Under Lula, there's pressure to use Petrobras for social policy: keep domestic fuel prices low (even when global oil prices rise), fund social programs, prioritize hiring from favored constituencies. In November, Petrobras announced $102 billion in capital expenditures through 2029, focusing on deepwater pre-salt oil fields. This is genuinely significant—Brazil's pre-salt reserves are among the world's largest untapped oil deposits, technically challenging but economically viable at current prices. The problem is that global oil demand is supposed to peak this decade (maybe), the energy transition is accelerating (theoretically), and investing $102 billion in oil infrastructure is either visionary or catastrophic depending on whether you believe peak oil demand forecasts. From a pure cash flow perspective, Petrobras is a monster—it generates billions in free cash flow, pays dividends, and trades at a low multiple because investors assume the government will eventually mess it up. (History supports this assumption.) The real question is whether Petrobras can balance commercial discipline with political demands. Every time a new president comes in, the company gets reorganized, executives get fired, and strategy shifts. That's not how you run an oil major; that's how you create uncertainty and destroy value. Brazil's economy needs Petrobras to succeed, but Brazil's politics treat Petrobras as a piggy bank.

## The Big Issue 2: The Fiscal Deficit Nobody Wants to Fix

Brazil's fiscal situation is genuinely concerning but also weirdly familiar—like a problem everyone knows exists but nobody wants to solve. The budget deficit is running around 8% of GDP, public debt is 89% of GDP and rising, and the government's spending is constitutionally protected by rules that mandate minimum spending on health and education. So you have automatic spending increases, constitutionally protected entitlements, and limited ability to cut spending without amending the constitution. Meanwhile, tax revenue is capped by a complex and inefficient tax code that everyone agrees needs reform but nobody can reform because vested interests block changes. Lula's government proposed a tax reform in October—simplifying the VAT, reducing corporate tax distortions, creating a carbon tax—which sounds great in theory but implementation is Brazil's chronic problem. (Brazil has been "about to reform" for decades.) The central bank, which is operationally independent (thank god for small favors), raised rates to 11.25% in November to combat 4.6% inflation. This is working—inflation expectations are anchored—but higher rates increase debt servicing costs, which worsens the fiscal deficit, which makes investors nervous, which puts pressure on the currency, which requires higher rates. It's a doom loop, except Brazil has been in doom loops before and always manages to muddle through without catastrophe. The IMF isn't involved (Brazil doesn't need IMF money), so there's no external pressure for fiscal discipline. Markets provide some discipline through higher borrowing costs, but not enough to force actual reform. So Brazil continues with a fiscal policy that's unsustainable long-term but manageable short-term, which describes basically every year since 2014.

## The Big Issue 3: China Trade and the U.S. Geopolitical Squeeze

Brazil's largest trading partner is China, by a lot—China buys massive quantities of Brazilian soybeans, iron ore, and beef. In 2024, bilateral trade exceeded $150 billion, and China has invested heavily in Brazilian infrastructure, ports, and energy through Belt and Road adjacent projects. This trade relationship is economically rational: China needs commodities, Brazil produces commodities, prices are good for both sides. But geopolitically, the U.S. is nervous. Trump's administration (and really, any U.S. administration) views China's growing influence in Latin America as a strategic problem. So Brazil faces pressure to choose sides, except Brazil doesn't want to choose sides because choosing means losing trade with one or the other. Lula is trying to play both—maintain trade with China, improve relations with the U.S., lead the "Global South" in multilateral forums, and position Brazil as a neutral broker. It's a smart strategy if you can pull it off, but it requires constant diplomatic gymnastics. In November, Brazil hosted Chinese President Xi for a state visit, signed multiple trade agreements, and then immediately announced closer security cooperation with the U.S. on drug trafficking. This is the definition of hedging. The economic risk is that if U.S.-China tensions escalate into a real trade war (not just tariffs, but full decoupling), Brazil gets squeezed: does it keep selling to China and risk U.S. sanctions, or cut China ties and lose its biggest customer? The smart money is on Brazil continuing to hedge as long as possible, which probably works until it doesn't.

## The International Angle

Brazil's economic trajectory matters globally because it's the world's 9th largest economy, a major food exporter (feeding China and the world), and a test case for whether commodity-driven growth can coexist with democratic instability. For global agriculture markets, Brazil is indispensable—it's the world's largest soybean exporter, a top beef producer, and a rising force in corn. If Brazilian agriculture stumbles, food prices globally rise. For climate politics, Brazil's role is paradoxical: Lula positions Brazil as a climate leader (COP30 host, Amazon protection), but also presides over an economy heavily dependent on agriculture (which requires deforestation) and oil (Petrobras' pre-salt investments). The world wants Brazil to preserve the Amazon, but nobody wants to pay Brazil the hundreds of billions it would cost to forgo economic development. For investors, Brazil is the ultimate "story stock" at country scale—everyone knows it should be richer, but the execution risk is always high. If Brazil ever got its fiscal house in order and political stability, it could be a growth powerhouse. But that's a big "if."

## The Bottom Line

Brazil in November 2025 is economically stable but not thriving—growth is slow, debt is high, and structural reforms remain elusive. Petrobras is investing big in oil just as the world is supposedly transitioning away from it, the fiscal deficit is widening with no political will to fix it, and geopolitical pressures are forcing Brazil to navigate between China and the U.S. The currency is stable, markets are resilient, and the country isn't in crisis—but it's also not reaching its potential, which has been the story of Brazil for decades. Lula's third term will be judged not by whether Brazil avoids disaster (it will) but by whether it finally delivers sustained growth. So far, the signs are mixed.`,
    issues: ["The Petrobras Dilemma—State Oil Company or Social Policy Instrument?", "The Fiscal Deficit Nobody Wants to Fix", "China Trade and the U.S. Geopolitical Squeeze"]
  },
  {
    name: "Canada",
    lat: 56.1304,
    lng: -106.3468,
    summary: `# Canada - Economy & Business

Canada just got its first technocrat prime minister in Mark Carney—former Bank of Canada governor, former Bank of England governor, Goldman Sachs alumnus—and markets basically cheered. (Nothing says "fiscal responsibility" quite like putting a central banker in charge.) Carney took over from Trudeau in March after Chrystia Freeland's spectacular resignation broke the Liberal government, and he's now navigating a Canadian economy that's simultaneously dealing with Trump tariff threats, a housing affordability crisis, and the weird situation where unemployment is rising (6.5%) while job openings remain elevated. The Bank of Canada has cut rates three times since June, bringing the policy rate to 3.75%, because inflation finally came down to 1.6%—below target for the first time since 2021. But the rate cuts aren't really stimulating growth; GDP growth is barely 1.2%, and per capita GDP is actually declining (which is genuinely unusual for Canada). Meanwhile, Trump keeps making bizarre comments about annexing Canada or imposing 25% tariffs on Canadian goods, which would devastate an economy where 75% of exports go to the U.S. Carney's pitch is that he's the adult who can manage this relationship without either capitulating or starting a trade war, and so far markets believe him.

## The Big Issue 1: The Trump Tariff Threat and Economic Dependency

Here's an uncomfortable question: What do you do when your entire economy depends on a trading partner run by someone who keeps threatening to blow up the relationship? Canada exports 75% of its goods to the U.S.—autos, oil, lumber, agriculture. The integrated supply chains mean that Canadian auto parts cross the border multiple times before becoming finished vehicles. Trump's threatened 25% tariffs on Canadian goods (he says it's about border security and fentanyl, which is absurd but also doesn't matter because tariffs aren't really about the stated reason). If those tariffs happen, Canada's manufacturing sector collapses, the loonie plummets, and unemployment spikes. Carney's strategy seems to be: remain calm, emphasize the mutual dependency (U.S. needs Canadian oil and electricity), quietly diversify trade relationships, and wait for Trump's attention to shift elsewhere. It's not a terrible strategy, but it's also not proactive. The diversification problem is real: you can't easily replace 75% of your export market. Europe is far away and has its own problems, Asia is protectionist in different ways, and Latin America isn't big enough to absorb Canadian exports. So Canada is stuck in a dependency relationship with an unreliable partner, which is economically dangerous but politically difficult to change. The other element is that every Trump tariff threat causes the loonie to weaken, which actually helps Canadian exporters (their goods become cheaper), but also makes imports more expensive, which feeds inflation. The Bank of Canada is cutting rates to stimulate growth, but if the currency keeps weakening, they might have to stop cutting or even raise rates to defend the exchange rate. It's a mess.

## The Big Issue 2: The Housing Crisis That Won't End

Canadian housing prices are genuinely insane—Toronto and Vancouver are among the world's most expensive cities relative to incomes, and even mid-sized cities like Ottawa and Calgary are unaffordable for young Canadians. The average home price in Toronto is $1.1 million; median household income is $70,000. Do the math: that's 15x income, which is historically unprecedented outside of asset bubbles. How did this happen? Multiple factors: restrictive zoning (NIMBYism is strong in Canada), foreign investment (though recent rules have limited this), low interest rates for a decade (which inflated asset prices), and immigration-driven population growth without corresponding housing supply. Carney's November budget included $30 billion for housing—subsidies for first-time buyers, incentives for developers, infrastructure for new communities. This is standard government housing policy, and it will probably fail because it doesn't address the core problem: not enough supply. Building more housing requires fixing zoning (municipal issue), speeding up permitting (provincial issue), and changing neighborhood opposition (cultural issue). The federal government can throw money at the problem, but it can't force Toronto to allow fourplexes or Vancouver to rezone single-family neighborhoods. The economic consequence is that young Canadians are either priced out of homeownership entirely or spending 50%+ of income on housing, which means less spending on everything else, lower fertility rates, and growing resentment toward immigration (which gets blamed for housing pressure, rightly or wrongly). Housing affordability is the defining economic issue for millennial and Gen Z Canadians, and no government has figured out how to fix it without crashing prices (which would hurt existing homeowners who vote). So Carney is trying Band-Aids when what's needed is surgery.

## The Big Issue 3: The Energy Transition Paradox

Canada is a petro-state that wants to be a climate leader, which is an awkward position. Alberta's oil sands produce 3 million barrels per day, making Canada one of the world's top oil exporters. Oil revenues fund federal transfers to poorer provinces, employ hundreds of thousands of workers, and generate massive tax revenue. But Canada is also committed to net-zero emissions by 2050, which theoretically means phasing out oil production, except that would bankrupt Alberta and cripple federal finances. The Trudeau government tried to navigate this with a carbon tax (to reduce emissions) while also buying the Trans Mountain pipeline (to expand oil exports). This satisfied nobody: environmentalists saw hypocrisy, oil workers saw betrayal, and Albertans concluded Ottawa hates them. Carney is trying a different approach: emphasize carbon capture technology (which lets oil production continue while capturing emissions), promote renewable energy, and frame the transition as gradual rather than sudden. In November, Canada announced $15 billion in subsidies for carbon capture projects in Alberta, which is either visionary climate tech or massive corporate welfare depending on your perspective. The economic reality is that global oil demand isn't disappearing quickly—IEA forecasts show demand plateauing in the 2030s, not collapsing—so Canadian oil will have buyers for decades. But capital markets are moving away from fossil fuel investments, which makes it harder for Canadian energy companies to raise money for new projects. The result is an industry that's still profitable but existentially uncertain, which creates weird investment dynamics: high cash flow, low growth, massive dividends, and depressed valuations because nobody knows if oil demand will still exist in 20 years.

## The International Angle

Canada's economy matters internationally because it's a top-10 global economy, a major commodity exporter (oil, minerals, agriculture), and a test case for whether resource economies can transition to clean energy. For the U.S., Canada is the largest trading partner and an essential supplier of oil and electricity—one-fifth of U.S. oil imports come from Canada, and several northern U.S. states depend on Canadian electricity. If Trump actually goes through with tariffs, both economies get hurt, but Canada gets hurt more because it's smaller. For China, Canada is a source of canola, lumber, and potash, though relations have been icy since the Meng Wanzhou affair. For global energy markets, Canada is a stability factor—it's a rule-of-law country that doesn't have coups or expropriate oil assets (usually), so Canadian oil is less risky than oil from the Middle East or Venezuela. The housing crisis is also globally relevant: Toronto and Vancouver are canaries in the coal mine for what happens when housing supply fails to keep up with demand in desirable cities. Other countries (Australia, New Zealand, the UK) are watching Canada's housing experiments closely.

## The Bottom Line

Carney inherited an economy with slow growth, rising unemployment, a housing crisis, and an unreliable U.S. trading partner. His bet is that technocratic competence and central banking credibility can stabilize markets and navigate Trump. The early signs are okay: the loonie is stable, inflation is low, rates are coming down. But the structural problems—housing unaffordability, energy transition uncertainty, U.S. trade dependency—aren't fixable by good management alone. They require political will for difficult reforms, and Carney hasn't fought an election yet. If he can win the upcoming election and deliver economic stability despite Trump chaos, he'll be vindicated. If Trump tariffs blow up Canadian trade or housing prices crash, Carney becomes the technocrat who couldn't deliver. It's a high-stakes experiment.`,
    issues: ["The Trump Tariff Threat and Economic Dependency", "The Housing Crisis That Won't End", "The Energy Transition Paradox"]
  },
  {
    name: "Chile",
    lat: -35.6751,
    lng: -71.5430,
    summary: `# Chile - Economy & Business

Chile's economy is in this weird limbo where it's not in crisis (growth is 2.4%, inflation is under control at 3.8%) but also nobody is happy about it. The presidential election this Sunday will likely produce either Jeannette Jara (left-wing, Boric's labor minister) or José Antonio Kast (right-wing, wants to privatize everything), and both represent pretty different visions for an economy that's been Latin America's success story but recently feels stuck. Here's the thing about Chile: it has the highest GDP per capita in South America ($16,000), excellent infrastructure, low corruption by regional standards, and massive copper reserves (producing 25% of global copper). But it also has extreme inequality (worst in OECD), a pension system that leaves retirees in poverty, and cost of living increases that triggered the 2019 social explosion. The economic model—call it "Chicago School-lite" after the Pinochet-era reforms—produced growth for decades but also concentrated wealth. Boric tried to reform this with a new constitution and expanded social programs, and voters rejected both. Now markets are nervous about Jara (will she govern as a moderate or push left-wing policies?) and also nervous about Kast (will his austerity trigger more protests?). Meanwhile, copper prices are high because of electric vehicle demand, which should be great for Chile, except lithium (which Chile also has) is more valuable and Chile is losing the lithium race to China.

## The Big Issue 1: Copper Boom Meets Lithium Fumble

Chile is the world's copper king—25% of global copper production comes from Chilean mines, mostly in the Atacama Desert. Copper prices are elevated (around $4.20/lb) because the energy transition requires massive amounts of copper for EV wiring, charging infrastructure, and grid upgrades. This is windfall territory for Chile: Codelco (state copper company) and private miners are generating huge profits, tax revenues are flowing to the government, and employment in mining is strong. But here's the paradox: Chile is also sitting on the world's largest lithium reserves (9 million tons), lithium is the "white gold" of the EV transition, and Chile is getting crushed by China in lithium production. Why? Because Chile's lithium production is concentrated in two companies (SQM and Albemarle) with old concessions, and the government hasn't figured out how to expand production while ensuring domestic benefits. Neighboring Argentina has been more aggressive in attracting lithium investment, and China now controls large parts of Argentine lithium production. Chile's policy paralysis means it's winning on copper but losing on lithium, which is frustrating because both are essential for the same energy transition. The Boric government proposed nationalizing lithium (following Bolivia's disastrous example), markets freaked out, and the policy was walked back. Now there's a hybrid model where the state owns lithium reserves but private companies can partner with the state to extract them. This sounds reasonable, but the implementation is messy: concession terms aren't clear, environmental reviews take forever, and local communities (rightly) demand water protections in a desert region. The result: Chile talks about lithium wealth but doesn't actually produce much, while competitors grab market share.

## The Big Issue 2: The Pension System That Everyone Hates

Chile's private pension system (AFPs) is famous internationally—it was the model for partial privatization experiments worldwide—and also deeply unpopular domestically. Here's how it works: workers contribute 10% of salary to private pension funds, the funds invest in stocks and bonds, and workers retire on whatever their account accumulated. In theory, this is market-based, avoids pay-as-you-go pyramid scheme dynamics, and aligns retirement security with economic growth. In practice, it produces terrible outcomes for most workers: the average pension is $400/month (poverty level), women get lower pensions because they live longer and take career breaks, and market downturns directly hurt retirees. The 2019 protests were triggered partly by metro fare increases, but the underlying anger was about pensions and cost of living. Boric promised to reform the pension system, creating a state-funded pillar alongside the private system. The reform passed Congress in watered-down form: employers now contribute 6% (previously workers contributed everything), which helps, but the structural problems remain. The left wants a fully state-funded system (like most OECD countries have), which would require higher taxes and probably better outcomes for low-income workers. The right defends the AFP model, arguing that returns have been good over time (true for high earners, not for low earners) and that state systems are fiscally unsustainable (see Argentina, Brazil). Markets care because pensions are Chile's largest pool of domestic capital—AFP funds invest heavily in Chilean stocks and bonds, so changes to the system affect capital markets directly. If Chile shifted to a full state system, that capital would need to be redirected, which could spike borrowing costs. It's economically complex and politically toxic, which means it probably doesn't get fully resolved no matter who wins.

## The Big Issue 3: Inequality and the Social Contract

Chile's Gini coefficient (inequality measure) is 0.45, the worst in the OECD. The top 10% control 60% of wealth, and the bottom 50% control 3%. This isn't just a moral issue; it's economically destabilizing. Extreme inequality means limited domestic consumption (because most people are poor), reliance on exports (copper, agriculture), and vulnerability to global commodity price swings. It also creates political instability: the 2019 protests were fundamentally about inequality, and they brought Chile's political system to a halt. Boric's response was ambitious—new constitution, expanded social programs, higher taxes on the wealthy, more state intervention in mining and utilities. Voters rejected the constitution 62-38, which tells you something about Chilean preferences: they want more redistribution but not radical system change. The pension reform, healthcare expansion, and education subsidies that Boric passed are incremental—they help at the margins but don't fundamentally alter inequality. The economic question is whether you can have sustained growth in a highly unequal society, and Chile is testing that question. Some economists argue inequality doesn't matter as long as everyone's income is rising (Pinochet-era growth lifted millions from poverty despite inequality). Others argue inequality creates instability that eventually undermines growth (see: 2019 protests). Chile's election is basically a referendum on which view is correct: Jara promises more redistribution (higher taxes, more state services), Kast promises more growth (lower taxes, deregulation, private sector). Markets prefer Kast's growth story, but voters might prefer Jara's redistribution story. We'll know Sunday.

## The International Angle

Chile matters globally as both a commodity powerhouse and a test case for market-based development. For copper markets, Chile is essential—any disruption in Chilean production (strikes, political instability, earthquties) spikes global copper prices. For lithium and the energy transition, Chile is a missed opportunity: it has the resource but not the policy framework to capitalize on it. For Latin American politics, Chile is a bellwether—it was the first to try Chicago School economics (under Pinochet), the first to have massive anti-inequality protests (2019), and the first to reject radical constitutional change (2022). If Jara wins and governs successfully from the left, it provides a template for progressive economics in the region. If Kast wins and restores market confidence, it validates pro-business policies. For pension reform globally, Chile is a cautionary tale: privatization sounded great in theory but produced bad outcomes in practice, which complicates arguments for similar reforms elsewhere.

## The Bottom Line

Chile's economy is stable but unsatisfying—growth is okay, inflation is controlled, copper revenues are strong, but inequality remains extreme and voters are frustrated. The election will determine whether Chile moves left (more redistribution, more state) or right (more markets, more growth), and both paths have risks. Jara could scare investors and trigger capital flight; Kast could trigger protests and social instability. The copper boom provides fiscal breathing room, but the lithium fumble shows policy paralysis on critical issues. Whoever wins has to fix pensions, reduce inequality, and navigate global commodity volatility. That's a tough job, and Chilean voters aren't patient.`,
    issues: ["Copper Boom Meets Lithium Fumble", "The Pension System That Everyone Hates", "Inequality and the Social Contract"]
  },
  {
    name: "Colombia",
    lat: 4.5709,
    lng: -74.2973,
    summary: `# Colombia - Economy & Business

Colombia's economy under leftist President Gustavo Petro is doing something genuinely unusual: implementing progressive taxation while not actually scaring away investors (yet). Petro came to power in 2022 promising to transform Colombia's economic model, tax the rich, end oil dependence, and reduce inequality. Two years in, he's passed a major tax reform (raising $4 billion annually), expanded social programs, and pushed aggressive environmental regulation of oil and gas. Markets were supposed to freak out, but instead GDP growth is 2.1%, unemployment dropped to 9.9% (high by developed country standards, but good for Colombia), and foreign direct investment is holding steady at $17 billion. The Colombian peso has been volatile (weakening against the dollar), inflation hit 9.5% before coming back down to 5.8%, and the central bank raised rates to 13.25% before starting to cut in November. Petro's economic experiment is basically: can a left-wing government in Latin America implement redistribution without triggering capital flight and fiscal crisis? So far, the answer is "sort of." The tax increases worked (revenue is up), but spending is also up, the fiscal deficit is 4.4% of GDP, and public debt is rising toward 60% of GDP. Oil production is declining because Petro won't grant new exploration licenses (he wants to phase out fossil fuels), which is ideologically consistent but economically risky for a country where oil exports are 40% of total exports.

## The Big Issue 1: The Great Oil Phase-Out Experiment

Gustavo Petro campaigned on ending oil and coal production in Colombia, arguing that fossil fuels are driving climate change and that Colombia needs to transition to a green economy. (He's not wrong about climate change, but the economics are complicated.) In office, he's refused to grant new oil exploration licenses, pushed for renewable energy expansion, and generally tried to wind down the hydrocarbon sector. The problem: Colombia produces 750,000 barrels per day of oil, and oil exports generate $15 billion annually—that's 40% of export earnings and a significant chunk of government revenue. If oil production declines without a replacement revenue source, Colombia faces fiscal crisis. Petro's argument is that the transition will create jobs in renewables and that Colombia's biodiversity can support ecotourism and sustainable agriculture. This is optimistic. Renewable energy requires massive upfront investment, doesn't employ as many people as oil, and doesn't generate export revenue quickly. Ecotourism is great, but it's not replacing $15 billion in oil exports anytime soon. The market reaction has been interesting: oil companies (Ecopetrol is the state oil company) are investing less in Colombia, shifting capital to Peru and Brazil, which means declining production is a self-fulfilling prophecy. Colombia's oil output peaked in 2013 at 1 million bpd and has been declining since. Without new exploration, reserves deplete, production falls further, and export revenues drop. The fiscal math doesn't work unless you believe Colombia can quickly develop alternative revenue sources, and the evidence for that is limited. Petro is betting that climate leadership and green economy positioning will attract international finance (climate funds, green bonds), but so far that capital hasn't materialized at scale.

## The Big Issue 2: Tax Reform and Redistribution—Does It Work?

Petro's signature achievement is a major tax reform passed in 2023, raising $4 billion annually through higher taxes on corporations, the wealthy, and financial transactions. This is genuinely progressive taxation—exactly what left-wing economists advocate. The revenue is funding expanded social programs: subsidies for poor families, free university tuition, healthcare expansion. In theory, this reduces inequality, boosts domestic consumption, and creates a more inclusive economy. In practice, it's working okay but not transformatively. Poverty rates have declined slightly (39.5% to 37.2%), but unemployment remains stubbornly high, and informality (people working off the books) is still 60% of the workforce. The tax increases haven't triggered mass capital flight (which was the big fear), partly because Petro has maintained macroeconomic discipline—the central bank is independent, the fiscal rules are being followed (sort of), and there's no Venezuelan-style money printing. But corporate profits have declined, foreign investment in extractive industries has slowed, and there's general business uncertainty about what Petro might do next. The risk is that higher taxes and regulation gradually erode Colombia's competitiveness, businesses relocate to Peru or Chile, and you end up with less investment and slower growth. It's a slow-motion risk, not a sudden crisis, which makes it harder to detect. The counterfactual question is: would Colombia's economy be growing faster with business-friendly policies? Probably yes, but also with less redistribution and higher inequality. Petro is betting that voters prefer redistribution to growth, and so far polling suggests he's right—his approval rating is around 40%, which is low but not catastrophic for a left-wing president in Latin America.

## The Big Issue 3: The Fiscal Deficit and Debt Dynamics

Colombia is running a fiscal deficit of 4.4% of GDP, and public debt is approaching 60% of GDP. These numbers aren't crisis levels (see: Argentina at 89% debt-to-GDP), but they're concerning because they're rising without an obvious path to stabilization. The deficit is driven by Petro's social spending increases: subsidies, pensions, healthcare, education. These are politically popular and socially beneficial, but they're permanent expenditures that require permanent revenue. The tax reform helps, but as oil revenues decline (because of Petro's anti-oil policies), the fiscal math gets worse. Colombia has a fiscal rule requiring deficits to decline over time, but Petro has been stretching the rule's boundaries, arguing that social spending is investment (which sounds nice but doesn't change the accounting). Markets are watching nervously: Colombia's sovereign bonds are rated BBB- (investment grade but barely), and any further fiscal deterioration could trigger a downgrade to junk status. A junk downgrade would raise borrowing costs, worsen the fiscal deficit (debt servicing costs increase), and potentially trigger capital outflows. The central bank has been hiking rates to combat inflation, but high rates also increase government debt costs, which worsens the fiscal position. It's a delicate balancing act. Petro needs either faster economic growth (to boost tax revenues) or spending cuts (politically difficult) or additional tax increases (risky for investment). None of these options are easy. The wildcard is that Colombia has traditionally been fiscally responsible by Latin American standards, which gives it credibility with markets. If Petro maintains that reputation, Colombia can probably run deficits for a while longer without crisis. If markets lose confidence, things deteriorate quickly.

## The International Angle

Colombia matters regionally as Latin America's third-largest economy and a key test of whether left-wing economics can work. For the U.S., Colombia is a crucial ally on drug policy (though Petro is pushing to end coca eradication programs), and bilateral trade is significant ($30 billion annually). For oil markets, Colombia is a mid-tier producer, but declining output contributes to global supply tightness. For climate politics, Colombia is trying to position itself as a green leader (Petro speaks at every climate conference), but the credibility depends on whether the oil phase-out actually produces a green economy or just economic stagnation. For investors, Colombia is a frontier market with decent institutions (rule of law, independent central bank) but elevated political risk. The peso's volatility reflects this uncertainty: when Petro says something markets don't like, the peso drops; when economic data is good, it recovers. It's more volatile than Chile or Peru but less volatile than Argentina or Brazil.

## The Bottom Line

Petro's economic experiment is risky but not irrational: he's trying to reduce dependence on oil, redistribute wealth through taxation, and build a more inclusive economy. The results are mixed—poverty has declined slightly, social spending is up, but growth is slow, oil production is falling, and fiscal deficits are rising. The question is whether this model is sustainable or whether it gradually erodes investment and competitiveness. So far, Colombia hasn't hit a crisis, and Petro's approval is stable enough to govern. But the fiscal math is concerning, the oil revenue decline is a real problem, and markets are skeptical. If global oil prices stay high and Colombia can attract green economy investment, Petro might pull it off. If oil prices drop or fiscal discipline breaks, Colombia faces a more serious reckoning.`,
    issues: ["The Great Oil Phase-Out Experiment", "Tax Reform and Redistribution—Does It Work?", "The Fiscal Deficit and Debt Dynamics"]
  },
  {
    name: "Costa Rica",
    lat: 9.7489,
    lng: -83.7534,
    summary: `# Costa Rica - Economy & Business

Costa Rica is Central America's Switzerland (small, stable, neutral) but with better beaches and worse infrastructure. The economy grew 4.2% in 2024—genuinely solid for a small open economy—driven by foreign direct investment in tech, medical devices, and tourism. (Intel left years ago, but Costa Rica replaced it with pharma and service sector FDI.) The fiscal situation is slowly improving after years of crisis: the deficit dropped to 2.8% of GDP, public debt declined to 62% from a peak of 70%, and in November Fitch upgraded Costa Rica's credit rating to BB (still junk, but trending upward). President Rodrigo Chaves, elected in 2022 on an anti-corruption platform, is business-friendly but also abrasive—he's picked fights with legislators, journalists, and international organizations. The result is political dysfunction (his party controls only 10 of 57 legislative seats) but also economic pragmatism: he can't pass radical legislation, so he focuses on incremental reforms and attracting foreign investment. Inflation spiked to 8.3% in 2022, came down to 2.1% by October 2025, and the central bank is cutting rates. The colón (Costa Rican currency) has been stable, tourism is booming (3.5 million visitors expected in 2025), and unemployment is low at 7.8%. The problems: infrastructure is crumbling (roads are terrible), inequality remains high, and dependence on tourism makes the economy vulnerable to external shocks.

## The Big Issue 1: The Post-Intel Reinvention

Costa Rica's economic history has this fascinating arc: it was a coffee economy, then Intel built a chip plant in 1997 and suddenly Costa Rica was a tech hub, then Intel left in 2014 and everyone panicked, and then Costa Rica reinvented itself again. The current model is medical devices, pharmaceuticals, and business services. Boston Scientific, Baxter, Abbott, and other medtech companies have massive plants in Costa Rica, exporting high-value medical devices globally. Why Costa Rica? Political stability (no coups, no civil wars since 1948), educated workforce (free public education, high literacy), strategic location (time zones work for U.S. companies), and tax incentives (Free Trade Zones offer tax breaks). The bet is that Costa Rica can be the "quality manufacturing" hub of Central America—not competing on low wages (Guatemala and Honduras are cheaper) but on reliability and skills. It's working: FDI reached $3.6 billion in 2024, unemployment is relatively low, and exports are diversified. The risk is that this model depends on continued foreign investment, which is fickle. If U.S. tax law changes (reducing incentives for offshore manufacturing), or if other countries offer better deals, Costa Rica loses its advantage. The other challenge is that FDI-driven growth doesn't always create broad-based prosperity. The tech and pharma sectors employ skilled workers and generate taxes, but they don't employ the 50% of Costa Ricans working in informal services. So you have a dual economy: modern, globalized export sectors and a large informal domestic economy. This creates inequality and social tension, even as headline GDP growth looks good.

## The Big Issue 2: Fiscal Consolidation—Did Costa Rica Actually Fix Its Deficit?

Costa Rica spent most of the 2010s in fiscal crisis—running large deficits, public debt rising toward 70% of GDP, and markets demanding higher interest rates on sovereign bonds. In 2018, after tense negotiations, Costa Rica passed a fiscal reform: introducing VAT, capping public sector wage growth, and creating a fiscal rule limiting deficits. The reform worked, sort of: deficits have declined, debt is stabilizing, and Fitch just upgraded Costa Rica's credit rating. But the consolidation has been painful—public sector wages have stagnated (creating strikes and protests), social spending has been constrained, and infrastructure investment has been delayed. Costa Rica's roads are genuinely terrible, which is weird for a country trying to attract foreign investment. The reason is that fiscal consolidation prioritized debt reduction over infrastructure spending, which is fiscally responsible but economically limiting. You can't be a logistics hub for medical devices if trucks can't get to ports without hitting potholes. Chaves has tried to increase infrastructure spending, but with limited legislative support, he's relying on public-private partnerships (concessions for toll roads, ports, airports). These work but take years to implement, so the infrastructure deficit persists. The broader question is whether Costa Rica's fiscal discipline is sustainable. Public sector unions are angry about wage caps, social spending is lower than it was in the 2000s (creating pressure for increases), and interest groups want targeted spending for their sectors. So far, the fiscal rule is holding, but it's politically fragile. If a populist government comes to power promising spending increases, the fiscal gains could evaporate quickly.

## The Big Issue 3: Tourism Dependency and the Pura Vida Paradox

Costa Rica's tourism sector is massive—3.5 million visitors annually, generating $4.5 billion (8% of GDP). The "pura vida" brand (pure life—it's a national motto) positions Costa Rica as an eco-tourism paradise: rainforests, beaches, biodiversity, zip-lining, surfing. It works; Costa Rica is one of the world's most visited small countries. But tourism dependency creates vulnerabilities: COVID-19 collapsed tourism in 2020-21, devastating the economy and creating a fiscal crisis (tourism taxes dropped, unemployment spiked). The recovery has been strong, but the underlying fragility remains. If another pandemic happens, or if U.S. recessions reduce travel, Costa Rica gets hit hard. The other issue is environmental sustainability. Costa Rica brands itself as green (carbon neutral by 2050, renewable energy, conservation), but mass tourism puts pressure on ecosystems. Beach towns are overdeveloped, water resources are strained, and local communities are priced out by tourism-driven real estate speculation. This creates a paradox: tourism funds conservation efforts, but tourism also damages the ecosystems being conserved. The government is trying to manage this through protected areas (27% of Costa Rica's land is protected), limits on development in sensitive areas, and promoting "sustainable tourism." But enforcement is weak, development pressure is intense, and corruption remains a problem (protected land gets developed through bribes or loopholes). The economic question is whether Costa Rica can maintain its eco-tourism brand while actually protecting its environment, or whether over time the brand erodes as ecosystems are damaged. So far, Costa Rica has balanced it, but the balance is delicate.

## The International Angle

Costa Rica matters internationally as Central America's success story—it avoided the civil wars that plagued neighbors (Guatemala, El Salvador, Nicaragua), abolished its military in 1948 (unique in the region), and built a stable democracy. For multinational companies, Costa Rica is the preferred Central American location for manufacturing and services. For conservation, Costa Rica is the poster child: reversing deforestation, protecting biodiversity, and proving that economic development and environmental protection can coexist. For tourism, Costa Rica is a top-10 destination in the Americas. The geopolitical role is limited (small country, neutral foreign policy), but Costa Rica is a reliable U.S. ally and a stable democracy in a region where those are rare. The immigration dynamic is interesting: Costa Rica attracts immigrants from Nicaragua (fleeing poverty and dictatorship) and Venezuela (fleeing crisis), creating labor supply but also social tensions. Costa Rica is generally welcoming but also has limited capacity to absorb large immigrant populations, so this creates policy challenges.

## The Bottom Line

Costa Rica's economy is stable and growing, driven by FDI, tourism, and fiscal discipline. The fiscal consolidation worked—debt is declining, deficits are manageable—but came at a cost of constrained public spending and deteriorating infrastructure. Tourism is booming but creates dependency risk. The FDI-driven growth model is working but doesn't benefit everyone equally. Chaves' government is business-friendly but politically weak, which limits big reforms but also prevents big mistakes. The credit rating upgrade signals market confidence, and the economic fundamentals are solid. Costa Rica won't be rich, but it's stable, which in Central America is a major achievement.`,
    issues: ["The Post-Intel Reinvention", "Fiscal Consolidation—Did Costa Rica Actually Fix Its Deficit?", "Tourism Dependency and the Pura Vida Paradox"]
  }
]

async function main() {
  console.log('Saving economy writeups batch 2 (Brazil through Costa Rica)...\n')

  for (const writeup of writeups) {
    console.log(`Processing ${writeup.name}...`)

    try {
      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: writeup.name,
            type: "country",
            category: "economy"
          }
        },
        create: {
          name: writeup.name,
          type: "country",
          country: writeup.name,
          lat: writeup.lat,
          lng: writeup.lng,
          category: "economy",
          summary: writeup.summary,
          issues: JSON.stringify(writeup.issues),
          topStories: JSON.stringify([]),
          storyCount: 0,
          updatedAt: new Date()
        },
        update: {
          summary: writeup.summary,
          issues: JSON.stringify(writeup.issues),
          updatedAt: new Date()
        }
      })
      console.log(`✓ ${writeup.name} saved (${writeup.summary.length} chars)\n`)
    } catch (error) {
      console.error(`✗ Error saving ${writeup.name}:`, error)
    }
  }

  await prisma.$disconnect()
  console.log('Batch 2 complete!')
}

main().catch(console.error)
