import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const writeups = [
  {
    name: "Cuba",
    lat: 21.5218,
    lng: -77.7812,
    summary: `# Cuba - Economy & Business

Cuba's economy is, to put it mildly, not functioning. GDP contracted 2% in 2024, inflation is officially 30% but realistically much higher (nobody believes government statistics), and the country is experiencing rolling blackouts that sometimes last 12+ hours. The electrical grid collapsed completely in October—twice—leaving the entire island without power. (When your national grid fails twice in one month, that's not a technical glitch; that's a failed state.) The currency situation is Byzantine: there's the official exchange rate (24 pesos per dollar), the informal rate (120-150 pesos per dollar), and the MLC stores that only accept dollars or euros. Ordinary Cubans can't access dollars, so they can't buy basic goods, which means the economy functions through remittances (Cubans abroad send money), black markets, and a growing exodus of young people. Over 400,000 Cubans have left since 2022, mostly to the U.S. via the Mexican border. Tourism, which was supposed to save the economy after the USSR collapsed, is recovering but still below pre-COVID levels. The government blames U.S. sanctions (true, but not the whole story), and reforms are incremental and slow. This is what happens when you maintain a centrally planned economy for 60+ years despite overwhelming evidence that it doesn't work.

## The Big Issue 1: The Energy Crisis and Grid Collapse

Cuba's electrical grid failed completely in October—once on October 18th and again on October 20th. The entire country went dark. This is genuinely extraordinary: national grid collapses happen in war zones or after natural disasters, not in peacetime. The causes are multiple: aging infrastructure (some power plants are 50+ years old), lack of fuel (Cuba imports fuel oil from Venezuela, which is itself an economic basket case), and deferred maintenance (no money to repair or upgrade equipment). The government responded by declaring an "energy emergency," rationing electricity, and instructing state enterprises to reduce consumption. Obviously this doesn't solve the underlying problem. The economic impact is devastating: businesses can't operate without reliable electricity, refrigeration fails (destroying food), hospitals lose power (people die), and the quality of life becomes intolerable. This is why Cubans are leaving—not just for political freedom but because basic services don't function. The government has talked about solar and renewable energy (Cuba has sun, obviously), but implementation requires capital that Cuba doesn't have. Foreign investors are reluctant because of currency controls, property rights uncertainties, and U.S. sanctions that limit access to U.S. financial systems. So Cuba is stuck: the grid is failing, replacement requires money, nobody wants to lend money to a country with a collapsed grid. It's a doom loop.

## The Big Issue 2: The Peso's Slow-Motion Collapse

Cuba has a genuinely insane currency system: there's an official exchange rate of 24 pesos per dollar (the CAD rate established in 2021), but on the informal market it's 120-150 pesos per dollar. That's a 5-6x difference. This is how you get hyperinflation without admitting it: the government claims the peso is worth 24 to the dollar, but nobody accepts pesos at that rate, so prices are set in informal dollars and then converted at street rates. A chicken costs 2,000 pesos, which sounds manageable until you realize average salaries are 5,000 pesos per month, and that chicken is really $13-17 at street exchange rates. The government created MLC stores (moneda libremente convertible—freely convertible currency) that only accept dollars, euros, or digital payments in hard currency. These stores have actual goods—food, toiletries, electronics—but Cubans earning pesos can't shop there unless they receive remittances from abroad. So you have a two-tier economy: dollar economy (functioning) and peso economy (collapsing). About $2 billion in annual remittances flow from Cubans in the U.S. to relatives in Cuba, which is basically life support for the economy. The government has tried to capture these dollars through currency controls and special exchange houses, but people evade through informal transfers. The economic absurdity is total: Cuba is a socialist economy dependent on capitalist remittances from Cuban exiles who fled socialism. The peso's collapse reflects underlying economic failure—the state sector produces almost nothing people want, imports exceed exports, and the only thing keeping Cuba afloat is external money.

## The Big Issue 3: Emigration and Brain Drain

Over 400,000 Cubans have left since 2022, mostly via the U.S.-Mexico border. This is enormous for an island of 11 million people—that's 3.6% of the population in two years. And it's not random emigration; it's young, educated people who see no future in Cuba. Doctors, engineers, teachers—people who could be building the economy are instead leaving. The causes are economic (no opportunities, low wages, food shortages) and political (repression, lack of freedom), but the economic factors dominate. You can't eat political freedom, and Cuba doesn't have food security. The government's response has been contradictory: sometimes trying to limit emigration (making exit visas harder), sometimes allowing it (because it reduces domestic pressure and increases remittances). The demographic impact is terrible: Cuba's population is aging (birth rates are low, young people leave), which worsens the fiscal situation (fewer workers, more retirees, more healthcare costs). There's no economic model where a country survives by exporting its most productive citizens. The remittance dependency is also problematic: it keeps the economy limping along, which removes pressure for reform, which perpetuates dysfunction. If remittances stopped, Cuba would face humanitarian crisis immediately, but remittances also enable the government to avoid hard choices. It's a subsidy for the status quo.

## The International Angle

Cuba matters less internationally than it did during the Cold War, but it's still symbolically important. For the U.S., Cuba is a foreign policy failure: 60+ years of embargo have not produced regime change, and instead, they've become a talking point for critics of U.S. policy. The Biden administration slightly eased restrictions (remittances, travel), but Trump will likely reverse those. For Latin America, Cuba is a cautionary tale about state socialism: Venezuela, Nicaragua, and Bolivia watched Cuba's economic collapse and should have learned lessons (they didn't). For China and Russia, Cuba is a geopolitical liability—both provide some support, but neither wants to subsidize Cuba the way the USSR did. The collapse of Venezuelan oil shipments to Cuba (Venezuela's own crisis reduced exports) has hurt Cuba enormously. For migration, Cuba is part of a broader Caribbean-Central American exodus: Haitians, Cubans, Venezuelans, Nicaraguans all fleeing to the U.S., creating domestic U.S. political pressure. The humanitarian situation is concerning: food insecurity, medicine shortages, infrastructure collapse—but there's no international mechanism to help because Cuba's government doesn't allow it.

## The Bottom Line

Cuba's economy is in structural collapse—contracting GDP, failed infrastructure, currency chaos, mass emigration. The government clings to state socialism despite overwhelming evidence it doesn't work, and reforms are too slow and limited to matter. The energy crisis is accelerating the collapse: without reliable electricity, what's left of the economy shuts down. Remittances keep people alive but also enable government dysfunction. Emigration provides an escape valve but drains the country of talent. There's no realistic path to recovery without fundamental economic reform (property rights, market mechanisms, foreign investment), and there's no political will for that. So Cuba continues its slow decline, kept barely functional by external money and the exodus of its most capable citizens.`,
    issues: ["The Energy Crisis and Grid Collapse", "The Peso's Slow-Motion Collapse", "Emigration and Brain Drain"]
  },
  {
    name: "Dominican Republic",
    lat: 18.7357,
    lng: -70.1627,
    summary: `# Dominican Republic - Economy & Business

The Dominican Republic is the Caribbean's growth champion, and honestly, it's not close. GDP grew 5.1% in 2024—one of the fastest in Latin America—driven by tourism (7 million visitors), remittances ($10 billion from Dominicans in the U.S.), and nearshoring manufacturing. (American companies are discovering that having factories a two-hour flight from Miami is better than having them in China.) President Luis Abinader won reelection in 2024 with 58% of the vote, basically a mandate for continuity: business-friendly policies, infrastructure investment, and pragmatic governance. Inflation dropped to 3.5%, the peso is stable, unemployment is 5.6% (low for the region), and the central bank is cutting rates because the economy is actually overheating. The fiscal deficit is 2.9% of GDP (manageable), public debt is 54% of GDP (not terrible), and Fitch rates the DR at BB+ with a positive outlook. The DR has figured out something its neighbors haven't: how to be pro-business without being oligarchic, how to attract foreign investment without resource dependency, and how to maintain growth without populist boom-bust cycles. Obviously there are problems—inequality is high, healthcare is weak, and electricity is still unreliable despite improvements—but compared to Haiti (which shares the island and is in total collapse) or Venezuela or Cuba, the DR looks like Singapore.

## The Big Issue 1: Tourism Boom and Nearshoring Strategy

The DR's economy is built on two pillars: tourism and nearshoring manufacturing. Tourism is massive—7 million visitors in 2024, generating $9 billion (8% of GDP). Punta Cana and Puerto Plata are beach resort destinations for American and European tourists, and the all-inclusive resort model works: tourists fly in, spend money, fly out, and the DR captures revenue through hotel taxes, employment, and services. The pandemic crushed tourism (2020-21 was brutal), but recovery has been V-shaped. The DR was quick to reopen, emphasized health protocols, and marketed aggressively. It worked. Occupancy rates are back to pre-pandemic levels, new resorts are under construction, and airlift capacity is expanding. The nearshoring story is newer but potentially bigger: American companies are reshoring manufacturing from Asia, and the DR is competitive. It offers low labor costs (but not as low as Haiti or Central America), proximity to the U.S. (two-hour flight), trade agreements (CAFTA-DR provides tariff-free access to the U.S.), and relatively stable institutions. Medical devices, textiles, and electronics are growing sectors. Free Trade Zones (tax incentives for exporters) employ over 200,000 people, and FDI hit $4 billion in 2024. The bet is that the DR can be the "Mexico of the Caribbean"—a manufacturing hub serving the U.S. market. It's working so far, but competition is intense (Mexico, Central America, Vietnam), and the DR needs to keep improving infrastructure and education to stay competitive.

## The Big Issue 2: The Electricity Problem—Still Not Solved

The DR's Achilles' heel is electricity. Despite years of investment and reform, power supply remains unreliable: outages are common, transmission losses are high (30%+ of generated power is lost or stolen), and residential consumers face frequent blackouts. The government has invested heavily—building new plants, upgrading grids, reducing subsidies—but the sector remains dysfunctional. Why? Multiple reasons: theft (illegal connections are rampant in poor neighborhoods), corruption (electricity distribution companies are politically connected and resist reform), and underinvestment (distribution infrastructure is old and poorly maintained). The economic impact is real: businesses need backup generators (expensive), manufacturing competitiveness suffers (unreliable power raises costs), and quality of life is diminished. The government has tried various reforms: privatizing distribution (didn't work, private companies underinvested), re-nationalizing (didn't work either), and now a hybrid model with state oversight and private operation. The latest reform aims to eliminate subsidies (which cost $1.5 billion annually), improve collections, and upgrade infrastructure. But this is the DR's third or fourth "electricity reform," so skepticism is warranted. The political problem is that fixing electricity requires raising prices (to cover costs and fund upgrades), which is unpopular, or cutting subsidies (same political problem), or cracking down on theft (which hurts poor people who can't afford to pay). So governments half-reform, avoid the hardest choices, and the problem persists.

## The Big Issue 3: Inequality and Haiti Spillover

The DR's growth is real, but inequality is also real: the Gini coefficient is 0.43, and the top 10% capture most economic gains. Poverty rates have declined (from 30% in 2010 to 23% in 2023), but millions of Dominicans still live in precarious conditions—informal work, limited healthcare, inadequate housing. The remittance economy is crucial: $10 billion annually from Dominicans in the U.S., Spain, and elsewhere. For many families, remittances are the difference between poverty and subsistence. This creates a migration-remittance cycle: Dominicans emigrate (legally or illegally), send money home, and that money funds consumption and investment. It works economically but creates social costs (family separation, brain drain). The Haiti situation is uniquely challenging: the DR shares an island with Haiti, which is in total state collapse—gangs control Port-au-Prince, the economy is destroyed, and Haitians flee across the border into the DR. The DR hosts an estimated 500,000-1 million Haitians (official numbers are unreliable), many undocumented. This creates labor supply for low-wage sectors (agriculture, construction, services), but also social tensions, strain on public services, and political backlash. Abinader has taken a hard line: mass deportations (over 200,000 deported in 2023-24), border wall construction, and strict enforcement. This is popular domestically but criticized internationally as inhumane. The economic calculation is that Haitian immigration provides cheap labor but also creates fiscal costs (healthcare, education), so the net benefit is unclear. The humanitarian question is what responsibility the DR has for Haitian refugees, and the answer from the DR government is "not much."

## The International Angle

The DR matters as the Caribbean's economic success story and a model for small-island development. For the U.S., the DR is a stable partner, a growing market, and a nearshoring destination—bilateral trade exceeds $18 billion annually. For tourism globally, the DR is a top-10 destination in the Americas, competing with Mexico, Jamaica, and the Bahamas. The business model is all-inclusive resorts, which critics say isolate tourists and limit local economic benefit, but which undeniably generate revenue and employment. For Haiti, the DR is both a refuge (Haitians flee there) and an adversary (mass deportations). The contrast between the DR and Haiti—two countries sharing an island, one thriving and one collapsing—is striking and depressing. The DR's success shows that good governance and economic openness can produce growth even in a poor Caribbean island; Haiti's failure shows that bad governance can destroy everything. For migration, the DR is a destination country (Haitians and Venezuelans migrate there) and a transit country (some migrants use the DR as a stepping stone to the U.S.).

## The Bottom Line

The DR's economy is firing on all cylinders—strong growth, low inflation, fiscal discipline, thriving tourism, and growing nearshoring. Abinader's reelection provides continuity, and markets are confident (positive credit outlook, stable currency). The electricity problem remains frustrating but not economy-destroying. Inequality is high but declining slowly. The Haiti situation is tragic and unresolved, creating humanitarian and political challenges. Overall, the DR is the Caribbean's best economic bet: stable institutions, pro-business policies, and pragmatic governance. If it can fix electricity and manage Haiti spillover, it's positioned for sustained growth.`,
    issues: ["Tourism Boom and Nearshoring Strategy", "The Electricity Problem—Still Not Solved", "Inequality and Haiti Spillover"]
  },
  {
    name: "Ecuador",
    lat: -1.8312,
    lng: -78.1834,
    summary: `# Ecuador - Economy & Business

Ecuador elected Daniel Noboa in late 2023, a 36-year-old banana heir (yes, really) who ran on a platform of defeating drug cartels and restoring security. (When "not being murdered by gangs" becomes your main economic policy, you know things have gone badly.) The security situation improved dramatically—he declared a state of emergency, deployed the military against cartels, and homicides dropped 50% in 2024. But the economy remains deeply troubled: GDP growth is barely 1%, unemployment is stuck at 4.5% (official, but informal work is 70% of employment), inflation hit 2.1% (low, but only because the economy is stagnant), and the fiscal deficit is running around 3% of GDP. Ecuador uses the U.S. dollar as its currency (dollarization happened in 2000 after a banking crisis), which provides price stability but also eliminates monetary policy flexibility. The government can't print money or devalue the currency, so all adjustment happens through fiscal austerity or wage cuts. Public debt is 63% of GDP, borrowing costs are high (Ecuador defaulted on bonds in 2020, restructured, and markets remain skeptical), and tax revenue is weak. Meanwhile, energy shortages are causing blackouts—droughts have reduced hydropower generation, and Ecuador doesn't have enough thermal backup capacity. So you have a young president trying to fix security, a dollarized economy with limited policy tools, and energy infrastructure that can't keep the lights on.

## The Big Issue 1: Dollarization—Blessing and Curse

Ecuador dollarized in 2000 after a banking crisis and hyperinflation destroyed the sucre (previous currency). Dollarization stabilized prices, restored confidence, and saved the economy from collapse. Twenty-five years later, dollarization is both Ecuador's anchor and its straitjacket. The blessing: Ecuador hasn't had currency crises, inflation is low, and people trust the monetary system (nobody expects their savings to evaporate overnight, which is a real concern in Argentina or Venezuela). The curse: Ecuador can't adjust the exchange rate, can't print money, and can't run independent monetary policy. If the economy needs stimulus, too bad—the government has to borrow or cut spending. If wages are too high relative to productivity, too bad—adjustment happens through unemployment instead of devaluation. The current energy crisis illustrates the problem: droughts reduced hydropower generation, the government needs to import fuel for thermal plants, but importing fuel requires dollars, and Ecuador is running low on dollars because exports are weak and imports are strong. A normal country would let its currency depreciate (making imports expensive and exports cheap), but Ecuador can't. So instead, it rations electricity, implements rolling blackouts, and hopes rainfall returns. The fiscal constraint is binding: Ecuador can't borrow easily (markets are skeptical after the 2020 default), tax revenue is limited (informal economy is huge), and spending needs are enormous (security, infrastructure, social programs). Dollarization forces fiscal discipline, which is good long-term but painful short-term.

## The Big Issue 2: The Security Turnaround—Can Noboa Sustain It?

Ecuador transformed from one of Latin America's safest countries to one of its most dangerous in less than a decade. Homicides spiked from 6 per 100,000 in 2018 to 47 per 100,000 in 2023—worse than Mexico, comparable to Colombia in the 1990s. What happened? Drug trafficking: Mexican cartels (Sinaloa, CJNG) and local gangs started using Ecuador as a cocaine transit point (cocaine from Colombia and Peru moves through Ecuador to the U.S. and Europe), and violence exploded. Prisons became cartel headquarters, gang leaders ordered hits from behind bars, and cities like Guayaquil became war zones. Noboa's response was aggressive: declared an "internal armed conflict," deployed 22,000 soldiers, raided prisons, transferred gang leaders to high-security facilities, and maintained states of emergency. It worked—homicides dropped 50% in 2024, and security is measurably better. But the question is sustainability: military deployments are expensive (straining the already tight fiscal budget), heavy-handed tactics risk human rights abuses, and the underlying drug trafficking economics haven't changed. As long as cocaine is profitable and Ecuador is a useful transit point, cartels will keep trying. The comparison to El Salvador is interesting: Nayib Bukele used similar tactics (mass arrests, gang crackdowns, militarized policing) and achieved dramatic crime reduction, but also created an authoritarian state. Noboa isn't there yet, but the emergency powers and military presence raise concerns. Economically, security improvement is essential for growth: tourists return, businesses invest, foreign companies consider Ecuador for nearshoring. If security deteriorates again, investment flees.

## The Big Issue 3: The Energy Crisis and Infrastructure Deficit

Ecuador is experiencing rolling blackouts—up to 12 hours per day in some regions—because of energy shortages. The problem is simple: Ecuador relies heavily on hydropower (70% of electricity generation), drought reduced water levels in reservoirs, and backup thermal capacity is insufficient. The government implemented blackouts to ration remaining power, which has obvious economic costs: businesses can't operate, refrigeration fails, hospitals run on generators, and quality of life plummets. Why doesn't Ecuador have better infrastructure? Underinvestment and poor planning. Oil revenues (Ecuador is an oil exporter, producing 500,000 bpd) should have funded infrastructure, but instead, they funded current spending, subsidies, and corruption. Ecuador subsidizes electricity heavily (residential rates are among the lowest in Latin America), which reduces revenue for investment and encourages overconsumption. The reform solution is clear: raise electricity prices, cut subsidies, invest in generation capacity, and improve grid resilience. But politically, raising prices is toxic (the left opposes it as neoliberalism, the right worries about social backlash), so governments defer action until crisis forces it. Noboa is trying to push through energy reforms—increasing rates, accelerating renewable energy projects, importing emergency generation capacity—but implementation is slow and politically fraught. The broader infrastructure deficit is severe: roads, ports, and public transit all need upgrades. Ecuador's geographic position (Pacific coast, Andean mountains, Amazon rainforest) makes infrastructure expensive, and fiscal constraints limit spending. The result is chronic underinvestment that hampers growth.

## The International Angle

Ecuador matters as a test case for whether security can be restored after state failure. For Latin America, Ecuador's gang violence was alarming because it showed how quickly a peaceful country can descend into cartel-controlled chaos. Noboa's turnaround provides a playbook: military force, prison reforms, and sustained pressure. For the drug trade, Ecuador is a crucial node: cocaine flows from Colombia and Peru through Ecuador to global markets, and disrupting that flow requires international cooperation. The U.S. provides some security assistance, but Ecuador also needs to manage relations with Colombia (where cocaine production is rising) and international partners. For dollarization debates, Ecuador is a long-term case study: 25 years in, it's provided stability but also constrained growth. The energy crisis matters for regional electricity markets: Ecuador has sometimes exported power to Colombia and Peru, but now it's a net importer, which affects regional grids. For investors, Ecuador is high-risk but with potential: if Noboa stabilizes security and fixes infrastructure, Ecuador could attract tourism and nearshoring. If he fails, it's another failed state.

## The Bottom Line

Ecuador is at a crossroads: Noboa has improved security dramatically, but economic challenges remain severe. Dollarization provides stability but limits policy options, the energy crisis is crippling growth, and fiscal constraints are binding. The security turnaround is real but fragile—if violence returns, foreign investment evaporates. If Noboa can maintain security, fix energy infrastructure, and attract investment, Ecuador could achieve sustained growth. If he can't, Ecuador slips back into instability. The next year is critical.`,
    issues: ["Dollarization—Blessing and Curse", "The Security Turnaround—Can Noboa Sustain It?", "The Energy Crisis and Infrastructure Deficit"]
  },
  {
    name: "El Salvador",
    lat: 13.7942,
    lng: -88.8965,
    summary: `# El Salvador - Economy & Business

El Salvador is running the world's boldest (or craziest) experiment in Bitcoin, authoritarianism, and gang eradication—all at once. President Nayib Bukele, who's basically a millennial strongman with great social media skills, has transformed El Salvador from murder capital to tourist destination, but at the cost of civil liberties and rule of law. The economy grew 3.5% in 2024 (solid for Central America), tourism surged 30%, foreign investment is increasing, and unemployment dropped to 3.5%. But this growth is built on: (1) mass incarceration—Bukele jailed 75,000 suspected gang members without trials, dropping homicides from 52 per 100,000 to under 3; (2) Bitcoin adoption—El Salvador made Bitcoin legal tender in 2021, built a Bitcoin city, and bought 5,800 BTC (worth $580 million at current prices); and (3) fiscal stimulus funded by borrowing. Public debt is 85% of GDP (dangerously high), the fiscal deficit is 4.8%, and El Salvador can't access international capital markets because the IMF won't lend while Bitcoin is legal tender. Bukele just won reelection with 84% of the vote despite constitutional term limits (he changed the constitution). So El Salvador is simultaneously a security success story, a crypto experiment, and an authoritarian drift.

## The Big Issue 1: The Bitcoin Gamble

El Salvador became the first country to adopt Bitcoin as legal tender in September 2021. Bukele's argument was that Bitcoin would attract investment, reduce remittance costs (Salvadorans abroad send $7 billion annually), and position El Salvador as a tech hub. Three years later, the results are... mixed. The Bitcoin experiment has attracted attention: Bitcoin conferences in San Salvador, crypto entrepreneurs visiting, and global media coverage. Tourism is up, partly because of Bitcoin branding. El Salvador holds 5,800 BTC (purchased at various prices), which is currently worth around $580 million—a paper gain because Bitcoin's price has risen. The government is building "Bitcoin City" (a planned city funded by Bitcoin bonds), though construction is slow. But adoption has been limited: most Salvadorans don't use Bitcoin for daily transactions (too volatile, too complicated), businesses prefer dollars, and the Chivo wallet (government Bitcoin app) has had technical problems. Remittances haven't shifted to Bitcoin in significant numbers—most still come through Western Union or banks. The IMF refuses to lend to El Salvador while Bitcoin is legal tender (the Fund views it as risky and destabilizing), which limits El Salvador's access to emergency financing. Markets are skeptical: El Salvador's sovereign bonds trade at distressed levels (implying default risk), and the country can't issue new debt at reasonable rates. The Bitcoin position is a huge fiscal gamble: if Bitcoin keeps rising, El Salvador makes hundreds of millions; if it crashes, the government loses money it can't afford to lose. It's the definition of volatility.

## The Big Issue 2: Bukele's Security Crackdown—Effective but Authoritarian

Bukele's signature achievement is crushing gang violence. MS-13 and Barrio 18 (El Salvador's dominant gangs) controlled neighborhoods, extorted businesses, and murdered anyone who resisted. Homicide rates peaked at 52 per 100,000 in 2015—among the world's highest. Bukele declared a "state of exception" in March 2022, suspended constitutional rights, and arrested 75,000 people suspected of gang membership—about 1% of the entire population. Trials? Not really. Evidence? Often minimal. Human rights? Suspended. The prisons are packed beyond capacity, with shirtless, tattooed inmates crammed into cells and filmed for propaganda videos that Bukele posts on Twitter. And here's the thing: it worked. Homicides dropped to under 3 per 100,000 in 2024, the lowest in Latin America. Businesses no longer pay extortion, tourism is booming, and Salvadorans feel safe walking streets that were previously war zones. The economic impact is real: FDI increased, tourism revenue rose 30%, and consumer confidence is high. But the cost to civil liberties is severe: mass incarceration without due process, families separated, and credible reports of abuse in prisons. International human rights groups condemn Bukele, but Salvadorans overwhelmingly support him (84% approval). The trade-off is stark: security and economic growth vs. civil liberties and rule of law. Most Salvadorans have chosen security. The question is whether this model is sustainable or whether it eventually collapses into corruption and authoritarianism.

## The Big Issue 3: Fiscal Sustainability and the Debt Wall

El Salvador's public debt is 85% of GDP—dangerously high for a dollarized economy with limited growth. The government runs deficits of 4-5% annually, funded partly by domestic banks (who buy government bonds) and partly by external borrowing. But external borrowing is increasingly difficult: the IMF won't lend while Bitcoin is legal tender, and private markets demand high yields (El Salvador's bonds yield 10%+, reflecting default risk). In January 2025, El Salvador faces a $1.4 billion bond maturity—a "debt wall" that the government needs to refinance or repay. If El Salvador can't roll over this debt, it faces default. Bukele's strategy has been to delay the problem: negotiate with creditors, use fiscal reserves, and hope Bitcoin gains cover shortfalls. But the fundamental arithmetic doesn't work: spending exceeds revenue, debt is rising, and growth isn't fast enough to outrun the deficit. The security improvements help (more economic activity means more tax revenue), and Bitcoin gains provide a buffer (selling some BTC could fund bond payments), but these are short-term fixes. Long-term fiscal sustainability requires either cutting spending (politically difficult, undermines Bukele's popularity) or raising taxes (same problem) or achieving much higher growth (requires continued security and investment). The IMF could help—provide financing, restructure debt—but only if El Salvador abandons Bitcoin as legal tender. Bukele refuses, viewing Bitcoin as central to his brand and El Salvador's identity. So El Salvador is in a fiscal standoff: keep Bitcoin and risk default, or drop Bitcoin and get IMF support. Bukele is betting that growth and Bitcoin gains let him avoid this choice.

## The International Angle

El Salvador matters as a test case for three global debates: Can Bitcoin work as national currency? Can mass incarceration defeat gang violence? And can authoritarian methods be justified by results? For cryptocurrency advocates, El Salvador is the proof of concept: if it works, Bitcoin adoption spreads globally. For human rights advocates, El Salvador is a disaster: suspending due process and jailing tens of thousands without trials is unacceptable regardless of outcomes. For security policy, El Salvador is the "Bukele model": overwhelming force, mass arrests, propaganda, and popular support. Other Latin American countries (Honduras, Ecuador, Colombia) are watching closely. For the U.S., El Salvador is complicated: Washington wants gang violence reduced (less migration pressure), but also worries about democratic backsliding. The migration flow from El Salvador has dropped (fewer people fleeing violence), which is a win for U.S. border policy, but Bukele's authoritarianism creates diplomatic tension.

## The Bottom Line

El Salvador under Bukele is a paradox: security and economic growth are up, but democracy and fiscal stability are down. The Bitcoin gamble is ongoing—potentially lucrative if prices rise, potentially catastrophic if they crash. The security crackdown worked but created an authoritarian state. The debt wall looms, and without IMF support, default risk is real. Bukele's 84% approval shows Salvadorans prioritize security over civil liberties, at least for now. If the economy keeps growing and Bitcoin keeps rising, Bukele looks visionary. If the fiscal situation collapses or violence returns, he looks reckless. It's high-risk, high-reward governance.`,
    issues: ["The Bitcoin Gamble", "Bukele's Security Crackdown—Effective but Authoritarian", "Fiscal Sustainability and the Debt Wall"]
  },
  {
    name: "Guatemala",
    lat: 15.7835,
    lng: -90.2308,
    summary: `# Guatemala - Economy & Business

Guatemala just inaugurated Bernardo Arévalo in January 2024, an anti-corruption crusader who won despite a political establishment that tried everything to stop him, including attempting to invalidate his election and prosecute his party. (When the outgoing government tries to cancel your election, that's not a healthy democracy.) Arévalo's first year has been politically tumultuous but economically stable: GDP grew 3.8%, inflation dropped to 4.1%, remittances hit a record $20 billion (15% of GDP), and the central bank cut rates to 5.5%. The currency (quetzal) is stable, foreign reserves are solid, and fiscal deficits are low (1.8% of GDP). But Guatemala remains Central America's most unequal country: 60% poverty rate, 70% informal employment, and an indigenous majority (60% of population) that's economically marginalized. The big economic story is remittances: $20 billion from Guatemalans in the U.S. is more than double export earnings, and it's keeping millions of families afloat. Meanwhile, corruption remains endemic (Guatemala ranks 150th globally on Corruption Perceptions Index), tax collection is abysmal (12% of GDP, lowest in Latin America), and infrastructure is crumbling. Arévalo is trying to reform, but he faces entrenched opposition from business elites, corrupt politicians, and military remnants. The question is whether one honest president can change a system designed for extraction.

## The Big Issue 1: The Remittance Economy—Blessing and Trap

Guatemala's economy runs on remittances. $20 billion annually from Guatemalans in the U.S.—that's 15% of GDP, more than export earnings, more than tourism, more than anything else. For individual families, remittances are transformative: they fund education, healthcare, housing, and consumption. Poverty would be catastrophically higher without remittances—estimates suggest they lift 10-15% of the population above the poverty line. But this creates a perverse economic model: instead of building an economy that provides opportunity, Guatemala exports its most ambitious people, who then send money home. It's extractive migration—young Guatemalans leave (often via dangerous illegal routes through Mexico), work low-wage jobs in the U.S., and send money to relatives. The government doesn't have to fix the economy because remittances paper over structural problems. Tax collection is abysmal (12% of GDP—compare to 18-20% in similar countries) because the elite don't pay taxes and the government doesn't enforce collection. Why would they? Remittances provide consumption, which keeps the population from revolting, and elites can keep extracting rents without accountability. The U.S. policy dimension is crucial: if Trump cracks down on immigration and deports Guatemalans, remittances drop, and Guatemala faces economic crisis. Arévalo is trying to create legal migration pathways (guest worker programs, H-2A visas for agriculture), which would regularize flows and protect workers, but this requires U.S. cooperation, which is uncertain. The bigger question is whether Guatemala can ever build a productive domestic economy or whether it's stuck in the remittance trap permanently.

## The Big Issue 2: Corruption as Economic System

Guatemala's corruption isn't just "some officials take bribes"; it's a systematic extraction mechanism that shapes the entire economy. The business elite (a small oligarchy) controls imports, construction, telecommunications, and major industries, and they've captured state institutions to protect their monopolies. Tax enforcement is weak because elites evade taxes with impunity. Public contracts are awarded through kickbacks, not competitive bidding. Land ownership is concentrated, and indigenous communities lack property rights. The judiciary is politicized, and prosecutors who investigate corruption face threats or exile. (The UN-backed anti-corruption commission CICIG was expelled in 2019 after it got too effective.) Arévalo's party, Semilla, explicitly campaigned against this system, which is why the establishment tried to stop him from taking office. Since inauguration, he's attempted reforms: investigating corrupt contracts, reforming procurement, and supporting judicial independence. But the resistance is intense—Congress blocks his appointments, the constitutional court (controlled by the old guard) obstructs reforms, and business groups threaten capital flight. The economic cost of corruption is enormous: Guatemala could collect 18-20% of GDP in taxes (like Costa Rica or Panama) but instead collects 12%, costing the government $6-8 billion annually. That money could fund education, healthcare, infrastructure—instead, it stays in elite pockets. Foreign investors avoid Guatemala (except for extractive industries that can pay off the right people), limiting job creation. The informal economy is 70% of employment because starting a legal business requires navigating corruption and bureaucracy that most people can't afford. Fixing this requires dismantling entrenched power structures, which is nearly impossible without a political majority (which Arévalo doesn't have).

## The Big Issue 3: Indigenous Exclusion and Economic Marginalization

Guatemala is 60% indigenous (mostly Maya), but indigenous people are systematically excluded from economic opportunity. Poverty rates among indigenous Guatemalans are over 75%, compared to 40% among non-indigenous. Land ownership is concentrated in non-indigenous hands, education access is limited (especially in rural indigenous areas), and discrimination in employment is rampant. The economic consequence is that Guatemala wastes the productive potential of the majority of its population. Indigenous communities are subsistence farmers, informal workers, or migrants—none of which builds a modern economy. Arévalo has promised greater inclusion: land reform, education investment, recognition of indigenous languages, and anti-discrimination enforcement. But these are long-term structural changes that require resources (which the government doesn't have because of low tax collection) and political will (which Congress opposes). The extractive industries dynamic is particularly ugly: mining and hydroelectric projects are often imposed on indigenous land without consent, profits accrue to foreign companies and local elites, and environmental damage is borne by communities. This creates conflict: indigenous groups protest, the government represses (sometimes violently), and investment is delayed or canceled. A more equitable model would recognize indigenous land rights, ensure profit-sharing, and require environmental safeguards—but that would reduce elite profits, so it doesn't happen. The economic irony is that marginalizing 60% of your population guarantees low growth, but the elite prefers low growth with high extraction to higher growth with wealth-sharing.

## The International Angle

Guatemala matters for U.S. immigration policy: Guatemalans are a significant portion of migrants at the U.S.-Mexico border, and remittances are a major economic stabilizer. If the U.S. cracks down on migration, Guatemala faces economic and political instability, which creates more migration—it's a doom loop. For anti-corruption efforts globally, Guatemala is a test: Arévalo represents a genuine reform mandate, but he's facing institutional obstruction. If he succeeds, it proves that electoral democracy can overcome corruption; if he fails, it suggests that corruption is too entrenched without international support (like CICIG provided). For indigenous rights, Guatemala is a critical case: how can indigenous majorities gain economic and political power in countries historically controlled by settler elites? For nearshoring and manufacturing, Guatemala should be competitive (low wages, proximity to the U.S., trade agreements), but corruption and weak institutions scare away investors. If Arévalo can improve governance, Guatemala could attract the manufacturing investment going to Mexico and the Dominican Republic.

## The Bottom Line

Guatemala's economy is stable on the surface—growth is okay, inflation is controlled, remittances are booming—but structurally broken. The remittance dependency masks domestic dysfunction, corruption drains resources that should fund development, and indigenous exclusion wastes human potential. Arévalo has a reform mandate, but he's facing entrenched opposition from elites who benefit from the status quo. If he can gradually build institutional capacity, increase tax collection, and reduce corruption, Guatemala could achieve sustained growth. If he fails, Guatemala continues as a low-growth, high-inequality, corruption-dominated economy that exports people instead of products.`,
    issues: ["The Remittance Economy—Blessing and Trap", "Corruption as Economic System", "Indigenous Exclusion and Economic Marginalization"]
  }
]

async function main() {
  console.log('Saving economy writeups batch 3 (Cuba through Guatemala)...\n')

  for (const writeup of writeups) {
    console.log(`Processing ${writeup.name}...`)

    try {
      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: writeup.name,
            type: "country",
            category: "economy"
          }
        },
        create: {
          name: writeup.name,
          type: "country",
          country: writeup.name,
          lat: writeup.lat,
          lng: writeup.lng,
          category: "economy",
          summary: writeup.summary,
          issues: JSON.stringify(writeup.issues),
          topStories: JSON.stringify([]),
          storyCount: 0,
          updatedAt: new Date()
        },
        update: {
          summary: writeup.summary,
          issues: JSON.stringify(writeup.issues),
          updatedAt: new Date()
        }
      })
      console.log(`✓ ${writeup.name} saved (${writeup.summary.length} chars)\n`)
    } catch (error) {
      console.error(`✗ Error saving ${writeup.name}:`, error)
    }
  }

  await prisma.$disconnect()
  console.log('Batch 3 complete!')
}

main().catch(console.error)
