import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const writeups = [
  {
    name: "Haiti",
    lat: 18.9712,
    lng: -72.2852,
    summary: `# Haiti - Economy & Business

Haiti is not an economy; it's a humanitarian catastrophe with some economic activity happening in the margins. GDP contracted 2% in 2024 (and that's probably optimistic), inflation is running at 30%+, the currency (gourde) has collapsed from 100 to the dollar in 2021 to over 160 in 2025, and the government controls maybe 10% of the capital, Port-au-Prince. Gangs control 80% of the city, extort businesses, kidnap for ransom, and function as de facto government in most neighborhoods. The official unemployment rate is meaningless because there's no formal economy—90% of people work informally (street vending, subsistence farming, crime). The government has no revenue (tax collection is non-existent), provides no services (hospitals and schools don't function), and has no legitimacy (the president was assassinated in 2021, no elections since). A Kenyan-led security force arrived in June 2024 to restore order, funded by the U.S. and UN, but it's massively understaffed (400 Kenyans against thousands of gang members) and ineffective. This is a failed state, and the economy reflects that: no investment, no growth, massive emigration. Over 100,000 Haitians have fled in the last two years, mostly to the Dominican Republic (where they face deportation) or the U.S. (via the border).

## The Big Issue 1: Gang Control and Economic Paralysis

Haiti's gangs aren't just criminal organizations; they're quasi-governments that control territory, tax businesses, and provide (violent) order. The G9 gang federation, led by former cop Jimmy "Barbecue" Chérizier, controls Port-au-Prince's port and main roads. If you want to import goods, you pay the gangs. If you run a business, you pay protection. If you refuse, you're kidnapped or killed. The economic effect is total: businesses can't operate (supply chains are disrupted, customers can't reach shops safely), foreign companies have left (Digicel, the telecom provider, is barely functioning), and domestic investment is zero. The port shutdowns mean Haiti can't import food (70% of food is imported), creating food insecurity for millions. The Kenyan security force deployment in June was supposed to change this. It hasn't. The force is too small (400-600 personnel against an estimated 200+ gangs with thousands of fighters), poorly equipped, and operating without clear strategy. The U.S. is funding the mission ($300 million committed) but won't send American troops (politically toxic after past interventions). The result is security theater: some patrols, some arrests, but no fundamental change in gang control. The economic recovery is impossible without security restoration, but security restoration requires resources and political will that don't exist. It's a doom loop: no security means no economy, no economy means no tax revenue, no tax revenue means no capacity to restore security.

## The Big Issue 2: Currency Collapse and Inflation

The Haitian gourde has lost 60% of its value against the dollar since 2021. This is hyperinflation in slow motion: prices rise constantly, savings are destroyed, and anyone with money converts to dollars immediately. The causes are monetary (the central bank prints money to fund government operations) and structural (exports are minimal, imports are essential, so dollars flow out). The currency collapse makes imports more expensive, which drives inflation, which worsens poverty, which destabilizes politics further. Food prices have doubled in two years. The minimum wage is 500 gourdes per day (about $3 at black market rates), which buys maybe one meal. People survive on remittances (Haitians abroad send $4 billion annually—about 30% of GDP), humanitarian aid, and informal work. The central bank has lost all credibility—nobody believes the gourde will stabilize, so rational actors dollarize their savings, which accelerates the currency's collapse. The standard IMF prescription would be: stabilize the currency through fiscal discipline, raise interest rates to defend the peg, cut government spending, and restore confidence. But Haiti doesn't have a functioning government to implement these policies. The IMF and World Bank have suspended programs (you can't lend to a government that doesn't control its territory), and international donors are wary (aid often gets stolen by gangs or corrupt officials). So the currency continues collapsing, inflation continues rising, and the population gets poorer.

## The Big Issue 3: The Emigration Exodus

Over 100,000 Haitians have emigrated since 2022, mostly to the Dominican Republic (crossing the land border) or the U.S. (via flights to Nicaragua or Panama, then overland through Mexico). This is economic migration driven by state failure: there are no jobs, no security, no future. The people leaving are often the most capable—educated, entrepreneurial, willing to take risks—which creates brain drain. Haiti needs these people to rebuild the economy, but they rationally conclude there's no point staying. The Dominican Republic has responded with mass deportations (over 200,000 in 2023-24) and border wall construction. The U.S. has tried to limit Haitian migration through Title 42 expulsions, CBP One appointments, and interdiction at sea, but the pressure continues. The remittance dependency is extreme: $4 billion annually from Haitians abroad is literally keeping the population alive. Without remittances, famine would be widespread. This creates a perverse dependency: Haiti can't build an economy because talent emigrates, but emigration provides the remittances that prevent total collapse. The political class has no incentive to fix the underlying problems because remittances paper over state failure. The international community is stuck: doing nothing means humanitarian catastrophe, but intervening requires military force (politically difficult) and long-term governance support (expensive and historically ineffective in Haiti).

## The International Angle

Haiti matters as a humanitarian crisis on America's doorstep and a cautionary tale about state failure. For the U.S., Haiti drives migration (creating domestic political pressure), requires humanitarian spending (hundreds of millions annually), and represents a foreign policy failure (decades of intervention and aid haven't stabilized Haiti). For the Dominican Republic, Haiti is an existential challenge: millions of potential migrants sharing an island, requiring constant border enforcement and deportations. For the UN, Haiti is a peacekeeping disaster: multiple missions over decades have failed to create stability, and there's little appetite for another large intervention. The Kenyan-led mission is under-resourced and unlikely to succeed without massive expansion (which isn't happening). For development economics, Haiti is the extreme example of why institutions matter: Haiti and the Dominican Republic share an island, but the DR has grown while Haiti has collapsed, entirely due to governance differences. For migration policy globally, Haiti shows that without addressing root causes (security, governance, economic opportunity), migration pressure is unstoppable.

## The Bottom Line

Haiti's economy doesn't exist in any meaningful sense—gangs control the territory, the government is absent, the currency is collapsing, and the population survives on remittances and humanitarian aid. The Kenyan security mission is too small to matter, international donors are exhausted and skeptical, and there's no political force capable of rebuilding the state. The emigration exodus will continue, remittances will keep flowing, and Haiti will limp along as a failed state indefinitely. Nobody has a solution, and until someone does, this is the status quo.`,
    issues: ["Gang Control and Economic Paralysis", "Currency Collapse and Inflation", "The Emigration Exodus"]
  },
  {
    name: "Honduras",
    lat: 15.2000,
    lng: -86.2419,
    summary: `# Honduras - Economy & Business

Honduras under left-wing President Xiomara Castro is doing this interesting dance where it's economically pragmatic while politically radical. (She's the first female president, the wife of the president who was overthrown in a 2009 coup, and she's reestablished diplomatic relations with China while maintaining ties with the U.S.—that's a balancing act.) The economy grew 4.2% in 2024, inflation dropped to 6.1%, unemployment is around 8%, and remittances hit $9 billion (27% of GDP—among the highest globally). Foreign reserves are strong ($10 billion), the fiscal deficit is manageable (3.2% of GDP), and the central bank cut rates to 7.5% in November. But Honduras is still Central America's second-poorest country, poverty affects 60% of the population, and violence remains high (36 homicides per 100,000). Castro's government is trying to reduce poverty through social spending, combat corruption through institutional reform, and attract investment through pro-business policies. It's working okay: poverty declined slightly, corruption prosecutions increased, and nearshoring investment is growing (U.S. companies are relocating manufacturing from Asia). The big question is whether Honduras can sustain growth without resolving underlying issues: gang violence, weak institutions, and massive emigration.

## The Big Issue 1: The Remittance Economy—Even More Extreme

Honduras receives $9 billion annually in remittances from Hondurans working abroad (mostly in the U.S.). That's 27% of GDP—the highest remittance dependency in the Americas after El Salvador and Jamaica. For context: exports are $8 billion, so remittances exceed export earnings. For hundreds of thousands of families, remittances are the only income. The poverty rate would be 75%+ without remittances; instead, it's "only" 60%. This dependency creates the same problems as Guatemala: the government doesn't have to build a functioning economy because remittances provide consumption, and the most ambitious people emigrate instead of building businesses at home. Tax collection is weak (18% of GDP—better than Guatemala, worse than Costa Rica), partly because remittance-funded consumption doesn't generate much tax revenue. The fiscal policy is basically: rely on remittances to keep the population fed, use international aid to fund social spending, and hope nearshoring investment creates jobs. It's not a terrible strategy given constraints, but it's fragile: if U.S. immigration policy tightens (mass deportations, border closure), remittances drop, consumption collapses, and Honduras faces crisis. Castro is pushing for legal migration pathways (guest worker programs, H-2A agricultural visas), which would stabilize flows and protect workers, but this requires U.S. cooperation. The alternative—building a domestic economy that provides opportunity—requires institutional capacity, security, and investment that Honduras doesn't have.

## The Big Issue 2: The China Pivot and Geopolitical Hedging

In March 2023, Honduras cut diplomatic ties with Taiwan and recognized China, reversing decades of policy. This was geopolitically significant: China is expanding influence in Latin America, and Honduras was one of the last Taiwan holdouts in the region. The economic calculus was clear: China offered $3 billion in investment (ports, dams, infrastructure) and increased trade. Taiwan couldn't match that. The U.S. was not happy—Honduras is strategically located (Nicaragua Canal alternative routes, proximity to U.S. border), and Washington views Chinese infrastructure as geopolitical leverage. But Castro made a bet: Honduras needs investment desperately, China has money, and maintaining Taiwan ties was sentimentality without economic benefit. Since the switch, Chinese investment has increased: Huawei is building telecom infrastructure, Chinese firms are bidding on port upgrades, and trade is growing. But the promised $3 billion hasn't fully materialized (Chinese investment promises often exceed actual flows), and there's concern about debt traps (loans that can't be repaid, leading to Chinese control of assets). Honduras is trying to balance: maintain U.S. security cooperation (drug trafficking, migration), accept Chinese investment (infrastructure, trade), and avoid picking sides definitively. It's the classic small-country strategy in great-power competition: extract benefits from both without fully aligning with either. The risk is that if U.S.-China tensions escalate, Honduras gets squeezed: the U.S. could cut aid or cooperation, China could demand political alignment, and Honduras loses leverage.

## The Big Issue 3: Security and the Bukele Temptation

Honduras has high violence (36 homicides per 100,000) but not total gang control like El Salvador or Haiti. MS-13 and Barrio 18 operate in Honduras, extort businesses, and control some neighborhoods, but the state still functions. Castro has taken a mixed approach: increased police presence, prosecuted some gang leaders, but also emphasized social programs (jobs, education) to reduce gang recruitment. This is a more moderate approach than Bukele's mass incarceration in El Salvador. The results are mixed: violence has declined slightly, but gangs remain powerful. The political pressure is immense: Hondurans see El Salvador's security improvements and ask "why can't we do that?" Castro's concern is that mass arrests without trials undermine rule of law (which Honduras is trying to rebuild after years of corruption and coups). But voters want results, and Bukele's approach gets results. The economic dimension is clear: security improvement attracts investment, tourism recovers, and businesses operate normally. Insecurity drives emigration, scares away investors, and limits growth. The temptation is to copy Bukele: declare emergencies, suspend rights, arrest thousands, and reduce violence immediately. But Castro believes (probably correctly) that Bukele's model is authoritarian and unsustainable. The question is whether a democratic, human-rights-respecting approach can reduce violence fast enough to satisfy voters and attract investment, or whether Hondurans eventually demand authoritarian security policies.

## The International Angle

Honduras matters as a migration source (Hondurans are a major share of U.S. border arrivals), a nearshoring destination (cheap labor, trade agreements), and a geopolitical pivot point (China recognition). For the U.S., Honduras is frustrating: close partner on drug trafficking and security, but also aligned with China on investment and infrastructure. The U.S. provides hundreds of millions in aid annually but struggles to compete with Chinese infrastructure offers. For China, Honduras is a foothold: gaining recognition from a U.S. neighbor sends a signal, and infrastructure investments create economic dependence. For nearshoring, Honduras is competitive with Guatemala and El Salvador: low wages, trade agreements, proximity to the U.S. If security improves, manufacturing investment could surge. For migration, Honduras is a push factor: violence, poverty, and lack of opportunity drive emigration. Reducing these requires economic development, which requires security, which requires investment—and that cycle is hard to break.

## The Bottom Line

Honduras is economically stable but not thriving: growth is okay, remittances are massive, and nearshoring is growing. But poverty remains high, violence is elevated, and dependence on remittances is extreme. Castro is trying to balance economic pragmatism (attract investment, maintain fiscal discipline) with political reform (anti-corruption, social spending). The China pivot provides investment but creates geopolitical risk. Security improvement is slow, and voters are impatient. If Castro can sustain growth, attract nearshoring, and gradually reduce violence, Honduras could break the poverty trap. If remittances drop or violence spikes, Honduras faces crisis.`,
    issues: ["The Remittance Economy—Even More Extreme", "The China Pivot and Geopolitical Hedging", "Security and the Bukele Temptation"]
  },
  {
    name: "Mexico",
    lat: 23.6345,
    lng: -102.5528,
    summary: `# Mexico - Economy & Business

Mexico just elected Claudia Sheinbaum in June 2024, the first female president and a scientist (PhD in energy engineering), and she inherited an economy that's simultaneously thriving (nearshoring boom, strong manufacturing, peso at multi-year highs) and troubled (security crisis, fiscal deficit widening, state-owned companies hemorrhaging money). GDP grew 3.2% in 2024, powered by nearshoring—American companies are relocating manufacturing from China to Mexico, and FDI hit a record $36 billion. But inflation is stubborn at 4.9% (above target), the budget deficit ballooned to 5.9% of GDP under AMLO (previous president), and Pemex (state oil company) has $100 billion in debt. Sheinbaum is trying to maintain AMLO's populist social programs while also reassuring markets that fiscal policy won't spiral out of control. It's a tough balancing act: she needs to fund infrastructure, social spending, and security while bringing deficits down and refinancing Pemex debt. The peso weakened after her election (markets nervous about fiscal policy), but has since stabilized as she appointed a market-friendly finance minister. The big story is nearshoring: Mexico is becoming North America's manufacturing hub, displacing China in supply chains. If she can manage fiscal policy, security, and USMCA renegotiation (2026), Mexico could have a generational growth opportunity.

## The Big Issue 1: The Nearshoring Boom—Real or Hype?

Mexico's "nearshoring" moment is genuinely significant. U.S. companies are moving manufacturing from Asia to Mexico because of: geopolitical tensions (U.S.-China rivalry), supply chain vulnerabilities exposed by COVID, labor cost increases in China, and "friendshoring" (producing in allied countries). The numbers are real: FDI hit $36 billion in 2024, up from $30 billion in 2023. Manufacturing employment is rising, particularly in automotive, electronics, and aerospace. Tesla is building a gigafactory in Nuevo León, BMW is expanding in San Luis Potosí, and dozens of smaller manufacturers are relocating. The economic impact is substantial: manufacturing exports exceeded $500 billion in 2024, surpassing China's exports to the U.S. in some categories. But there are bottlenecks: infrastructure is inadequate (ports are congested, freight rail is slow, electricity is unreliable), skilled labor is scarce (Mexico needs engineers and technicians, not just assembly workers), and security remains a concern (cartel violence affects business confidence). The fiscal policy dimension is critical: nearshoring requires infrastructure investment (roads, ports, water, electricity), but Mexico's fiscal position is weak. Sheinbaum needs to invest billions in infrastructure while also reducing the deficit, which is mathematically difficult. The other challenge is USMCA renegotiation in 2026: Trump (or whoever wins in 2024) might demand changes, particularly around labor standards, energy, and Chinese content rules. If renegotiation goes badly, nearshoring could stall. But if Sheinbaum can maintain trade access, improve infrastructure, and provide stable governance, nearshoring could drive 5%+ growth for years.

## The Big Issue 2: The Pemex Debt Bomb

Pemex is Mexico's state-owned oil company, a national symbol, and also an economic disaster. It has $100 billion in debt (among the world's most indebted companies), declining production (down from 3.4 million bpd in 2004 to 1.7 million today), aging infrastructure, and chronic underinvestment. AMLO spent his presidency propping up Pemex with government transfers ($14 billion in 2024 alone), refusing to allow private participation, and insisting on energy sovereignty. This was nationalist politics but economic nonsense: Pemex's debt continued growing, production continued declining, and fiscal costs mounted. Sheinbaum, who served in AMLO's cabinet, is stuck defending his policies while also recognizing they're unsustainable. Her solution seems to be: gradual private sector participation (euphemistically called "strategic alliances"), financial restructuring to reduce debt servicing costs, and increased efficiency. But Pemex's unions are powerful, corruption is endemic, and any serious reform faces political backlash from the nationalist left. The fiscal arithmetic is brutal: every dollar spent propping up Pemex is a dollar not spent on education, healthcare, or infrastructure. Pemex's debt is guaranteed by the government, so default risk is sovereign default risk, which would collapse Mexico's credit rating and spike borrowing costs. Sheinbaum can't let Pemex fail, but she also can't keep funding it indefinitely. The solution is probably a slow-motion nationalization-lite: keep Pemex nominally state-owned, bring in private partners to fund investment, and hope production stabilizes. But this requires navigating nationalist politics and union resistance, neither of which is easy.

## The Big Issue 3: Security—The Unsolved Crisis

Mexico's security situation is bad and not improving. Homicides are around 28,000 annually (about 22 per 100,000), cartels control large swaths of territory, and violence affects daily life in many regions. AMLO's strategy was "hugs not bullets"—social programs instead of military confrontation—which didn't work; violence stayed high throughout his term. Sheinbaum is trying a new approach: deploying the National Guard more aggressively, increasing intelligence cooperation with the U.S., and targeting cartel leadership. But the underlying economics of drug trafficking haven't changed: fentanyl production is massively profitable, the U.S. market is enormous, and cartels have the resources to outgun local police. The economic cost is substantial: businesses pay extortion, investment is deterred in violent regions, tourism suffers in affected areas, and human capital is lost (people killed or displaced). The nearshoring opportunity is threatened by security concerns: if foreign executives don't feel safe, they won't relocate operations. Sheinbaum's challenge is that security improvement requires sustained effort over years (dismantling cartels, reforming police, strengthening judiciary), but voters want immediate results. The temptation to adopt Bukele-style mass arrests exists, but Mexico is too large and complex for that approach to work. The U.S. dimension is critical: U.S. demand for drugs drives the business, U.S. guns arm the cartels, and U.S. cooperation is essential for intelligence and enforcement. But U.S. politics is unpredictable, and Trump's threatened "bombing cartels" or other unilateral actions would destabilize Mexico further.

## The International Angle

Mexico matters as the U.S.'s largest trading partner ($779 billion in bilateral trade in 2024), a major oil exporter, and the frontline of U.S. migration and drug policy. The nearshoring boom positions Mexico as North America's manufacturing hub, which could reshape global supply chains. The security crisis affects U.S. fentanyl deaths (90%+ of fentanyl in the U.S. comes through Mexico), creating domestic political pressure for action. The USMCA renegotiation in 2026 is critical: if trade access is maintained, nearshoring continues; if tariffs or restrictions are imposed, the boom ends. For China, Mexico is both competitor (displacing Chinese exports to the U.S.) and partner (Chinese firms are using Mexico as an export platform to avoid U.S. tariffs). For global energy markets, Mexico is a marginal player now (declining oil production), but it has potential if Pemex is reformed. For migration, Mexico is both a destination (Central Americans transit through) and a source (Mexicans still migrate north, though less than before).

## The Bottom Line

Mexico stands at an inflection point: nearshoring provides a generational growth opportunity, but fiscal and security challenges could derail it. Sheinbaum needs to reduce the deficit (markets demand it), support Pemex (politically necessary), invest in infrastructure (nearshoring requires it), and improve security (investment depends on it). That's a lot of competing priorities with limited fiscal space. If she can balance them—market-friendly fiscal policy, pragmatic Pemex reform, security improvement—Mexico could grow 4-5% annually for years. If she can't, the nearshoring boom fizzles, fiscal problems worsen, and Mexico remains stuck in the middle-income trap.`,
    issues: ["The Nearshoring Boom—Real or Hype?", "The Pemex Debt Bomb", "Security—The Unsolved Crisis"]
  },
  {
    name: "Nicaragua",
    lat: 12.8654,
    lng: -85.2072,
    summary: `# Nicaragua - Economy & Business

Nicaragua under Daniel Ortega is an authoritarian state masquerading as an economy. (When the president's wife is the vice president and they've jailed all opposition leaders, that's not democracy; that's a family business.) The economy officially grew 4.5% in 2024, which nobody believes because Ortega's government controls statistics and has every incentive to lie. Independent estimates suggest growth is closer to 2%, driven mainly by remittances ($2.5 billion, about 15% of GDP) and agricultural exports (coffee, beef, gold). Inflation is officially 6%, probably higher. The currency (córdoba) is managed through a crawling peg (slow devaluation), which maintains stability but also creates black market premiums. Foreign reserves are around $4 billion (adequate), the fiscal deficit is officially 2% of GDP (probably higher), and public debt is manageable at 55% of GDP. But none of these numbers are trustworthy. What we know for certain: Ortega has crushed civil society, expelled NGOs and international organizations, seized property from opponents, and created a climate of fear that stifles economic activity. Over 500,000 Nicaraguans have fled since 2018 (when protests against Ortega were violently repressed), creating brain drain. Foreign investment is minimal (only sanctioned countries like Russia and China), and the U.S. has imposed sanctions on regime officials. This is a managed decline economy.

## The Big Issue 1: The Remittance Dependency and Emigration

Nicaragua receives $2.5 billion in remittances annually (15% of GDP), mostly from Nicaraguans who fled Ortega's repression. The irony is perfect: Ortega's authoritarianism drives emigration, emigrants send money home, and that money keeps the economy functional, which allows Ortega to stay in power. It's a remittance subsidy for dictatorship. The emigration wave since 2018 has been massive: over 500,000 people (out of 6.5 million population) have left, mostly to Costa Rica, the U.S., and Spain. These aren't just random emigrants; they're political opponents, students, professionals, and business owners—exactly the people Nicaragua needs to build an economy. The effect is severe brain drain: reduced entrepreneurship, lower productivity, and a population skewed toward the less educated and elderly. But remittances paper over the economic damage: families receiving dollars spend on consumption, which maintains demand and keeps shops open. The government doesn't have to provide opportunity or services because remittances provide subsistence. The political calculation is cynical: Ortega doesn't care if ambitious people leave because they're potential threats. Better to export the opposition and collect remittances than to tolerate dissent. The economic consequence is stagnation: no investment, no innovation, no growth beyond remittance-fueled consumption. Nicaragua could be a nearshoring destination (low wages, proximity to the U.S., trade agreements), but who would invest in a country where the president seizes property arbitrarily and jails critics?

## The Big Issue 2: Isolation and Authoritarian Alignment

Nicaragua is economically and diplomatically isolated by choice. Ortega has expelled international organizations (UN agencies, OAS observers, USAID), broken relations with the EU, and aligned with Russia, China, Iran, and Venezuela. This is geopolitical posturing (Ortega fashions himself as anti-imperialist) but also economic self-harm. The EU suspended preferential trade treatment, the U.S. imposed sanctions on regime officials, and international financial institutions won't lend (the IMF and World Bank have no active programs). So Nicaragua is cut off from Western capital, technology, and markets. The alternative is supposed to be Russia and China, but neither is providing significant economic support. Russia offers rhetoric and symbolic visits but limited money. China has some investment (a textile plant, infrastructure projects) but nothing transformative. The promised Nicaragua Canal (Chinese-funded alternative to the Panama Canal) has been "under development" for a decade with zero progress—it's a fantasy project. The economic cost of isolation is substantial: Nicaragua can't access concessional financing (multilateral development banks won't lend), foreign investment is minimal (only sanctioned countries will invest), and trade opportunities are limited. The coffee and beef exports continue (these are commodity exports that don't require political alignment), but value-added manufacturing, tourism, and services are stunted. The fiscal situation is manageable only because Nicaragua runs a tight budget (limited spending, authoritarian control over institutions), but this also means no investment in education, healthcare, or infrastructure. It's managed decline.

## The Big Issue 3: Property Seizures and Rule of Law Collapse

Ortega's government has seized property from political opponents, NGOs, universities, and media outlets—over 3,000 organizations have been shut down, their assets confiscated. This isn't just authoritarianism; it's wealth transfer from civil society to regime loyalists. The Catholic Church has been a particular target: bishops have been jailed, church property seized, and religious freedom crushed. The economic impact is chilling: if the government can seize property arbitrarily, why would anyone invest? Property rights are the foundation of market economies—if they don't exist, neither does economic activity beyond subsistence. Foreign investors won't touch Nicaragua (the risk is too high), domestic investment is limited to regime-connected businesses, and entrepreneurship is stifled. The legal system is completely politicized: courts rule as Ortega dictates, contracts aren't enforceable, and there's no recourse for expropriation. This is extractive institutions in the Acemoglu-Robinson sense: the regime extracts wealth from society without providing public goods, which guarantees poverty and stagnation. The comparison to Venezuela is apt: both are leftist authoritarian regimes with oil or natural resources, both have driven away productive citizens, both rely on remittances and external support, and both are economically dysfunctional despite official statistics claiming growth. Nicaragua doesn't have Venezuela's hyperinflation (the crawling peg prevents that), but it has the same underlying pathology: a predatory state destroying the economy while enriching ruling elites.

## The International Angle

Nicaragua matters as a cautionary tale about dictatorship's economic costs and as a geopolitical irritant in the U.S. backyard. For Central America, Nicaragua is a push factor: emigrants flee to Costa Rica (which doesn't want them) and the U.S. (creating migration pressure). For U.S. policy, Nicaragua is frustrating: sanctions haven't dislodged Ortega, regime change attempts have failed, and there's no obvious strategy beyond containment. For the Catholic Church, Nicaragua is persecution: the regime has jailed bishops and seized church property, creating an unusual direct conflict between a Latin American government and the Vatican. For Russia and China, Nicaragua is a cheap geopolitical win: providing rhetorical support costs nothing, and Nicaragua votes with them in international forums. But neither is providing the economic support Nicaragua needs, so the partnership is mostly symbolic. For human rights, Nicaragua is backsliding: political prisoners, media censorship, NGO expulsions, and religious persecution are all severe and worsening.

## The Bottom Line

Nicaragua's economy is stagnant and isolated, sustained only by remittances from emigrants fleeing Ortega's dictatorship. Property seizures and rule-of-law collapse prevent investment, international isolation cuts off capital and trade, and brain drain reduces productivity. Ortega has consolidated power completely, eliminated opposition, and will likely stay in power until he dies (he's 79). The economic trajectory is continued decline: slow growth driven only by remittances and commodity exports, no investment in human capital or infrastructure, and increasing poverty masked by official statistics. There's no catalyst for change—Ortega controls everything, and external pressure has failed. So Nicaragua remains a managed decline economy indefinitely.`,
    issues: ["The Remittance Dependency and Emigration", "Isolation and Authoritarian Alignment", "Property Seizures and Rule of Law Collapse"]
  },
  {
    name: "Panama",
    lat: 8.5380,
    lng: -80.7821,
    summary: `# Panama - Economy & Business

Panama is Central America's success story—the richest, most developed, and most stable economy in the region. GDP per capita is $18,000 (triple Nicaragua, double Costa Rica), growth was 6.2% in 2024 (the fastest in Latin America), inflation is low at 1.8%, and the dollarized economy provides monetary stability. The Panama Canal generated $4.3 billion in revenue in fiscal 2024 (October 2023-September 2024), and it's the government's single largest revenue source. Banking and financial services contribute 7% of GDP (Panama is Latin America's financial hub), logistics and trade are massive (the Canal, Tocumen airport, Colon Free Zone), and construction is booming (new metro lines, infrastructure projects). President José Raúl Mulino, elected in May 2024, is pro-business and pragmatic. The fiscal situation is solid: deficit of 2.1% of GDP, public debt at 58% of GDP (manageable), and investment-grade credit ratings. But Panama faces challenges: inequality is high (Gini 0.49), indigenous and rural populations are left behind, and the Canal is experiencing drought-related water shortages that limit ship transits. Also, Trump keeps threatening to "retake" the Canal (which is both absurd and economically threatening—Panama's economy depends on Canal sovereignty).

## The Big Issue 1: The Canal and Water Scarcity

The Panama Canal is an engineering marvel, an economic engine, and increasingly, a climate vulnerability. The Canal uses about 50 million gallons of fresh water per ship transit (it's a lock system, so water flows from Gatún Lake to the ocean with each transit). In 2023-24, droughts reduced Gatún Lake levels, forcing the Canal Authority to limit ship transits from 36-38 per day to 24 at the worst point. This created bottlenecks: ships waited weeks for transit slots, shipping costs spiked, and some carriers diverted around South America (Cape Horn route, adding weeks to voyages). Canal revenues dropped from projected $4.9 billion to actual $4.3 billion—a $600 million shortfall. The government is responding with infrastructure investments: a new reservoir (Indio River) to supplement water supply, water recycling systems, and efficiency improvements. But these are multi-year, multi-billion-dollar projects. The underlying issue is climate change: Panama's rainfall patterns are shifting, droughts are more frequent, and the Canal's water supply is vulnerable. This is existential for Panama's economy—30% of government revenue comes from Canal operations, and the entire logistics economy (ports, railroads, warehousing) depends on Canal traffic. The economic question is whether Panama can maintain Canal competitiveness while managing water scarcity. The alternatives—routing ships around South America or through the Suez Canal—are more expensive, which gives Panama pricing power, but only if it can actually move ships efficiently. If the Canal becomes unreliable due to water shortages, global shipping routes could permanently shift.

## The Big Issue 2: The Banking Hub and Financial Services

Panama is Latin America's banking and financial services hub—over 80 international banks operate there, and the sector contributes 7% of GDP. The model is offshore banking (favorable tax treatment, banking secrecy, dollar stability), corporate services (Panama is a global ship registry leader), and wealth management (Latin American elites park money in Panamanian banks). This has made Panama rich but also attracted money laundering, tax evasion, and corruption. The 2016 Panama Papers scandal revealed that Panamanian law firms were facilitating global tax evasion and money laundering, creating reputational damage. Since then, Panama has tried to clean up: strengthening anti-money-laundering rules, increasing banking transparency, and cooperating with international authorities (OECD, FATF). The tension is that Panama's banking model depends partly on secrecy and favorable treatment, but international pressure demands transparency and enforcement. If Panama fully complies with international standards, some banking business migrates to less-compliant jurisdictions (Cayman Islands, BVI, Dubai). If it doesn't comply, it risks being blacklisted (placed on FATF grey or black lists), which would devastate the sector. Mulino's government is trying to balance: maintain Panama's attractiveness for legitimate banking while cracking down on illegal flows. The economic stakes are high—banking and financial services employ tens of thousands, generate tax revenue, and fund consumption. But the reputational risk is also high: another Panama Papers-scale scandal would be catastrophic.

## The Big Issue 3: Inequality and Indigenous Exclusion

Panama's aggregate wealth masks extreme inequality. The Gini coefficient is 0.49 (among the highest in Latin America), and indigenous populations (about 12% of the population) have poverty rates exceeding 80%. The wealth is concentrated in Panama City (gleaming skyscrapers, international banking, high-end services), while rural areas and indigenous comarcas (autonomous regions) lack basic services. This creates social tension: indigenous groups have protested mining projects, blocked roads, and demanded better services. The government's response has been mixed: increased social spending (education, healthcare, cash transfers) but also repression of protests and limited consultation on extractive industries. The economic challenge is that Panama's growth model—services, logistics, finance—doesn't directly benefit rural and indigenous populations. They're subsistence farmers or informal workers in sectors that don't connect to Panama City's prosperity. The extractive industries debate is particularly fraught: Panama has copper deposits, and a large mine (Cobre Panamá) was operating until 2023, when massive protests shut it down over environmental and contract concerns. The mine contributed 5% of GDP and significant tax revenue, but opponents argued it was environmentally destructive and the contract terms favored the foreign company. The mine is now closed, the company is seeking international arbitration, and the government lost significant revenue. The broader question is whether Panama can have inclusive growth—spreading prosperity beyond Panama City—or whether the dual economy persists: urban wealth and rural poverty.

## The International Angle

Panama matters as a global logistics hub (the Canal handles 5% of global trade), a regional financial center, and a geopolitical flashpoint (Trump's "retake the Canal" rhetoric). For shipping companies, Panama is essential: the Canal is still the fastest route between Atlantic and Pacific, and any disruption affects global supply chains. For Latin American elites, Panama is the preferred destination for wealth storage and corporate structuring. For the U.S., Panama is a close partner (U.S. dollar adoption, security cooperation, drug trafficking interdiction), but Trump's Canal rhetoric creates tension. For China, Panama is strategically important: China is the second-largest Canal user (after the U.S.), has invested in port infrastructure, and has diplomatic recognition (Panama switched from Taiwan to China in 2017). The U.S. views Chinese presence nervously, but Panama needs Chinese trade and investment. The climate dimension is global: if the Canal becomes unreliable due to water scarcity, global shipping routes and costs change permanently.

## The Bottom Line

Panama's economy is thriving—fastest growth in Latin America, low inflation, stable currency, and strong Canal revenues. Mulino's government is pro-business and stable. The Canal's water challenges are serious but manageable with investment. Banking and financial services remain strong despite regulatory pressures. But inequality is extreme, indigenous populations are excluded, and extractive industries create conflict. If Panama can invest in water infrastructure, maintain Canal competitiveness, and address inequality, sustained growth is achievable. If the Canal becomes unreliable or social tensions escalate, growth slows. Overall, Panama is Central America's safest economic bet.`,
    issues: ["The Canal and Water Scarcity", "The Banking Hub and Financial Services", "Inequality and Indigenous Exclusion"]
  },
  {
    name: "Paraguay",
    lat: -23.4425,
    lng: -58.4438,
    summary: `# Paraguay - Economy & Business

Paraguay is South America's quiet overachiever—you don't hear about it much, but the economy is chugging along. GDP grew 4.8% in 2024 (among the fastest in the region), inflation dropped to 3.5% (below target), unemployment is just 5.8%, and the guaraní (currency) has been stable despite regional volatility. The fiscal deficit is tiny (1.5% of GDP), public debt is manageable (42% of GDP—among the lowest in Latin America), and foreign reserves are solid. President Santiago Peña, elected in 2023, is pro-business and market-friendly (he's a former IMF and central bank official). The economy is commodity-based: soybeans, beef, and electricity (from Itaipú Dam, the world's second-largest hydroelectric plant) are the main exports. The Paraguay-Argentina border is one of Latin America's busiest commercial zones, and contraband trade (both legal and illegal) is massive. But Paraguay has problems: it's landlocked (making exports expensive), infrastructure is weak (roads are terrible outside Asunción), and inequality is extreme (land ownership is highly concentrated). Also, there's a fascinating crypto-mining boom—Paraguay's cheap electricity (from Itaipú) attracts Bitcoin miners, making it one of the world's top mining locations.

## The Big Issue 1: The Soybean Economy and Commodity Dependence

Paraguay is the world's fourth-largest soybean exporter (after the U.S., Brazil, Argentina), and soybeans account for 40% of exports. This is commodity dependence in its purest form: when soy prices are high, Paraguay booms; when they're low, growth stalls. In 2024, soy prices have been decent ($12-13/bushel), and Paraguay's export earnings have been strong. The agricultural model is large-scale, mechanized farming concentrated in the eastern region (near Brazil and Argentina). Much of this is Brazilian-owned or operated (Brazilians crossed the border decades ago, bought land, and created a hybrid Brazilian-Paraguayan culture). The economic benefits are real: export earnings, tax revenue, and employment (both direct farm jobs and logistics). But the social costs are also real: land concentration (large landowners dominate, smallholders are squeezed), environmental damage (deforestation for soy cultivation), and limited diversification (the economy depends on one crop). The political economy is classic: landowners have political influence, block land reform, and capture government policy. Smallholder farmers and indigenous groups (who are pushed off land by soy expansion) have limited voice. The economic question is whether Paraguay can diversify beyond soybeans or whether it remains a commodity exporter forever. The government talks about industrialization, value-added agriculture, and tourism, but implementation is limited. The reality is that soybeans are easy—plant, harvest, export—and don't require complex institutions or technology. Building a diversified economy requires investment, education, and industrial policy that Paraguay hasn't prioritized.

## The Big Issue 2: The Bitcoin Mining Boom and Energy Surplus

Paraguay has a massive energy surplus from Itaipú Dam (shared with Brazil) and Yacyretá Dam (shared with Argentina). Paraguay uses only about 30% of its Itaipú allocation; the rest is sold to Brazil at below-market rates (contractually locked). This creates a bizarre situation: Paraguay has excess electricity but limited domestic use. Enter Bitcoin miners. Cheap electricity (about $0.03/kWh) makes Paraguay one of the world's most profitable locations for cryptocurrency mining. Miners have flocked to Paraguay since 2021: Chinese miners fleeing China's crackdown, international operations seeking competitive costs, and local entrepreneurs entering the space. Estimates suggest Paraguay hosts 10-15% of global Bitcoin hashrate (computing power), making it a top-5 mining country. The government has been cautiously supportive: allowing operations, creating regulatory frameworks, and collecting taxes. The economic benefits are real: miners pay for electricity (revenue for state utilities), employ some technical workers, and attract investment. But the costs are also real: Bitcoin mining uses enormous amounts of electricity (reducing the surplus available for domestic industry), creates limited employment (mining is automated), and has reputational risk (crypto is volatile and controversial). The political debate is whether Paraguay should prioritize Bitcoin mining or use its energy surplus for industrialization (attracting manufacturing that needs cheap power). The Bitcoin advocates argue mining generates revenue and is easier than attracting manufacturers. The industrialization advocates argue mining is extractive (uses resources, creates few jobs) and that Paraguay should build value-added industries. So far, the government is allowing both, but as energy demand grows, there will be trade-offs.

## The Big Issue 3: Landlocked Geography and Contraband Economy

Paraguay is landlocked, which is an economic curse: exporting soybeans or importing goods requires transiting through Argentina or Brazil, adding cost and time. The Paraguay River provides some access (goods can be shipped downriver to the Atlantic), but it's seasonal (droughts reduce navigability) and slow. The result is that Paraguay has high logistics costs, which reduces competitiveness. The contraband economy is Paraguay's workaround. Ciudad del Este (on the tri-border with Brazil and Argentina) is one of the world's largest contraband hubs: electronics, cigarettes, alcohol, and counterfeit goods flow across borders, evading tariffs and regulations. Estimates suggest contraband trade is 30-40% of official GDP—it's enormous and integral to the economy. The Paraguayan government tolerates it (corruption and complicity are factors), Brazil and Argentina complain (they lose tariff revenue), and consumers benefit (cheaper goods). The economic logic is clear: Paraguay's formal economy is small, so contraband provides employment, consumption, and cross-border trade. But it also limits state capacity: if much economic activity is informal, tax collection suffers, rule of law weakens, and integration with global markets is limited. The government's stated goal is to formalize the economy, increase tax collection, and reduce contraband. But this requires enforcement (costly and politically difficult) and would reduce consumption (goods become more expensive), hurting voters. So contraband persists, and Paraguay remains a dual economy: formal soybean exports and informal contraband trade.

## The International Angle

Paraguay matters regionally as a commodity exporter (soybeans to China and elsewhere), an energy exporter (electricity to Brazil and Argentina), and a contraband hub. For China, Paraguay is one of the last Latin American countries still recognizing Taiwan (Honduras switched in 2023, leaving Paraguay and a few small countries). China has offered investment and trade in exchange for diplomatic recognition, but Paraguay has resisted (maintaining Taiwan ties for now). The U.S. views Paraguay as a partner on counterterrorism (the tri-border area allegedly has Hezbollah financing networks) and drug trafficking. For Bitcoin globally, Paraguay is a significant player—if it continues friendly policies, it attracts more miners; if it restricts, mining migrates elsewhere. For regional integration (Mercosur), Paraguay is the smallest economy but strategically located (bordering Brazil and Argentina, the bloc's giants). For energy markets, Paraguay's electricity surplus is valuable: Brazil wants more, and Paraguay could potentially export to Chile or other neighbors if transmission infrastructure is built.

## The Bottom Line

Paraguay's economy is stable and growing, driven by soybean exports, cheap electricity, and contraband trade. Peña's government is pro-business and fiscally responsible, which markets like. The Bitcoin mining boom is interesting but economically limited (uses energy, creates few jobs). The landlocked geography is a constraint, and contraband trade is both economic lifeline and governance problem. Inequality is extreme, with large landowners dominating and indigenous populations marginalized. If Paraguay can diversify beyond soybeans, formalize the contraband economy, and invest in infrastructure, sustained growth is possible. If it remains commodity-dependent and informal, growth is limited. Overall, Paraguay is stable and boring, which in South America is an achievement.`,
    issues: ["The Soybean Economy and Commodity Dependence", "The Bitcoin Mining Boom and Energy Surplus", "Landlocked Geography and Contraband Economy"]
  }
]

async function main() {
  console.log('Saving economy writeups batch 4 (Haiti through Paraguay)...\n')

  for (const writeup of writeups) {
    console.log(`Processing ${writeup.name}...`)

    try {
      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: writeup.name,
            type: "country",
            category: "economy"
          }
        },
        create: {
          name: writeup.name,
          type: "country",
          country: writeup.name,
          lat: writeup.lat,
          lng: writeup.lng,
          category: "economy",
          summary: writeup.summary,
          issues: JSON.stringify(writeup.issues),
          topStories: JSON.stringify([]),
          storyCount: 0,
          updatedAt: new Date()
        },
        update: {
          summary: writeup.summary,
          issues: JSON.stringify(writeup.issues),
          updatedAt: new Date()
        }
      })
      console.log(`✓ ${writeup.name} saved (${writeup.summary.length} chars)\n`)
    } catch (error) {
      console.error(`✗ Error saving ${writeup.name}:`, error)
    }
  }

  await prisma.$disconnect()
  console.log('Batch 4 complete!')
}

main().catch(console.error)
