import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient({ datasources: { db: { url: 'file:/home/user/NewsMap/prisma/dev.db' } } })

const W = [
  { name: 'Benin', lat: 9.3077, lng: 2.3158, summary: `Benin's energy system serves approximately 13 million people with limited domestic generation capacity, relying heavily on electricity imports from neighboring countries and thermal generation from imported fuel. Energy access has improved but remains below 50% nationally, concentrated in urban areas.

Benin has minimal fossil fuel resources, importing petroleum products for transport and diesel generation. Natural gas deposits exist offshore but remain undeveloped due to financing and infrastructure constraints.

Electricity generation capacity totals approximately 400 MW, far below peak demand of over 600 MW. Benin imports substantial electricity from Nigeria, Ghana, and Togo, transmitted via West African Power Pool interconnections. These imports comprise over 60% of electricity supply, creating dependence on neighbors' reliability.

Renewable energy potential exists but is largely untapped. Solar resources are abundant in Benin's tropical climate. Small-scale solar deployment has occurred in rural areas through off-grid systems, but utility-scale solar farms remain limited. Hydropower potential is modest.

Energy policy targets increased access and domestic generation, with plans for solar farms and natural gas development if financing materializes.` },
  { name: 'Bhutan', lat: 27.5142, lng: 90.4336, summary: `Bhutan's energy strategy is unique: the Himalayan kingdom has achieved near-total renewable electricity through hydropower, exports surplus power to India generating crucial revenue, and maintains carbon-negative status through forest preservation and hydropower-dominated energy mix.

Hydropower dominates Bhutan's electricity generation. The country has developed approximately 2.3 GW of installed hydro capacity through run-of-river projects exploiting glacial melt and monsoon runoff. Major plants include Tala (1,020 MW), Chukha (336 MW), and Kurichu (60 MW). Additional projects under construction will add gigawatts.

Bhutan's domestic electricity demand is small given the population of 750,000. Surplus power is exported to India under long-term power purchase agreements, providing over 25% of government revenues. India finances most hydro projects through grants and loans, recognizing mutual energy security benefits.

However, Bhutan's hydropower faces climate change risks. Glacier retreat and altered monsoon patterns threaten long-term water availability. Glacial lake outburst floods (GLOFs) pose dam safety hazards.

Biomass (wood fuel) still dominates household cooking and heating energy in rural areas, contributing to indoor air pollution and forest pressure despite Bhutan's conservation ethic.

Bhutan imports petroleum products from India for transport, as the mountainous terrain limits alternatives. Electric vehicles are being promoted to reduce oil dependence.` },
  { name: 'Bolivia', lat: -16.2902, lng: -63.5887, summary: `Bolivia possesses significant natural gas reserves that underpin its energy economy and export revenues, yet political instability, underinvestment, and infrastructure constraints have prevented full exploitation. The country's energy landscape reflects broader governance challenges and resource nationalism.

Natural gas dominates Bolivia's energy mix and exports. Proven reserves total approximately 10 trillion cubic feet, mostly in the Tarija region. Gas provides electricity generation, industrial energy, and export revenue. Bolivia exports gas via pipeline to Brazil and Argentina under long-term contracts, generating billions annually—crucial for the fiscally strapped government.

However, production has stagnated around 1.3 billion cubic feet per day and may decline without major new discoveries and investment. The Morales government's resource nationalism—including nationalization of Petrobras and other foreign assets in 2006—deterred investment. Current President Arce faces similar challenges attracting capital while maintaining populist policies.

Electricity generation totals approximately 2.5 GW capacity. Natural gas thermal plants provide the majority. Hydropower contributes significantly, though droughts affect reliability. Renewable deployment is limited despite Bolivia's solar potential in high-altitude regions.

Bolivia has enormous lithium reserves in the Uyuni salt flats—potentially the world's largest. Lithium is crucial for batteries in the global energy transition. However, extraction has been slow due to technical challenges, political disputes, and governance issues.

Energy policy remains populist. Subsidized fuel and electricity prices cost billions annually, draining fiscal resources while discouraging efficiency.` },
  { name: 'Bosnia and Herzegovina', lat: 43.9159, lng: 17.6791, summary: `Bosnia and Herzegovina's energy system reflects its post-war political fragmentation: aging coal plants providing cheap but polluting electricity, substantial hydropower, and governance structures split between Bosniak-Croat Federation and Republika Srpska that complicate unified energy policy.

Coal dominates electricity generation. Bosnia operates several lignite-fired plants including Tuzla and Kakanj (in the Federation) and Ugljevik (in Republika Srpska). These aging Soviet-era facilities provide baseload power but cause severe air pollution—Bosnia has some of Europe's worst air quality in winter. EU accession pressures will eventually require either retrofitting with pollution controls (costing billions) or retirement.

Hydropower is substantial, providing approximately 35% of electricity from plants along the Neretva, Drina, and other rivers. Additional hydro potential exists, with controversial dam projects proposed in pristine river valleys—opposed by environmentalists.

Bosnia's complex governance hinders energy policy. The Federation and Republika Srpska operate separate electricity companies (Elektroprivreda BiH and Elektroprivreda RS) with limited coordination. Entity politics prevents coherent renewable strategy.

Bosnia exports electricity to neighbors when hydro production is high but imports during dry periods and cold winters when demand surges.

Renewable energy beyond hydro is minimal. Some wind and solar deployment has occurred, but permitting is slow and investment limited.` }
]

for (let i = 5; i <= 28; i++) {
  const countries = [
    { idx: 5, name: 'Botswana', lat: -22.3285, lng: 24.6849 },
    { idx: 6, name: 'Brazil', lat: -14.2350, lng: -51.9253 },
    { idx: 7, name: 'Brunei', lat: 4.5353, lng: 114.7277 },
    { idx: 8, name: 'Bulgaria', lat: 42.7339, lng: 25.4858 },
    { idx: 9, name: 'Burkina Faso', lat: 12.2383, lng: -1.5616 },
    { idx: 10, name: 'Burundi', lat: -3.3731, lng: 29.9189 },
    { idx: 11, name: 'Cambodia', lat: 12.5657, lng: 104.9910 },
    { idx: 12, name: 'Cameroon', lat: 7.3697, lng: 12.3547 },
    { idx: 13, name: 'Canada', lat: 56.1304, lng: -106.3468 },
    { idx: 14, name: 'Central African Republic', lat: 6.6111, lng: 20.9394 },
    { idx: 15, name: 'Chad', lat: 15.4542, lng: 18.7322 },
    { idx: 16, name: 'Chile', lat: -35.6751, lng: -71.5430 },
    { idx: 17, name: 'China', lat: 35.8617, lng: 104.1954 },
    { idx: 18, name: 'Colombia', lat: 4.5709, lng: -74.2973 },
    { idx: 19, name: 'Costa Rica', lat: 9.7489, lng: -83.7534 },
    { idx: 20, name: 'Croatia', lat: 45.1, lng: 15.2 },
    { idx: 21, name: 'Cuba', lat: 21.5218, lng: -77.7812 },
    { idx: 22, name: 'Cyprus', lat: 35.1264, lng: 33.4299 },
    { idx: 23, name: 'Czechia', lat: 49.8175, lng: 15.4730 },
    { idx: 24, name: 'Democratic Republic of the Congo', lat: -4.0383, lng: 21.7587 },
    { idx: 25, name: 'Denmark', lat: 56.2639, lng: 9.5018 },
    { idx: 26, name: 'Djibouti', lat: 11.8251, lng: 42.5903 },
    { idx: 27, name: 'Dominican Republic', lat: 18.7357, lng: -70.1627 },
    { idx: 28, name: 'East Timor', lat: -8.8742, lng: 125.7275 }
  ].find(c => c.idx === i);
  
  if (countries) {
    const summaries = {
      5: `Botswana's energy landscape is defined by coal abundance and limited domestic generation capacity requiring electricity imports from South Africa. As a middle-income diamond economy, Botswana has resources to invest in energy infrastructure but faces the challenge of balancing coal utilization with climate commitments. Coal dominates Botswana's energy endowment. The country has substantial coal reserves, primarily in the Morupule field near Palapye. The Morupule B power station, commissioned in 2012, was intended to provide energy self-sufficiency but has suffered chronic breakdowns and operates well below its 600 MW capacity. Technical problems and poor construction quality have made Morupule B a cautionary tale. Electricity generation totals approximately 600 MW installed capacity, far below peak demand exceeding 700 MW. Botswana imports substantial power from South Africa's Eskom and the Southern African Power Pool, creating dependence on neighbors. Solar potential is excellent given Botswana's Kalahari Desert climate with intense sunshine. However, utility-scale solar deployment has been slow. Recent projects including the 100 MW Mabesekwa solar farm represent growing momentum. Energy policy targets reduced import dependence and increased renewable generation.`,
      6: `Brazil's energy system is one of the world's most remarkable: hydropower provides over 60% of electricity, making Brazil's grid among the cleanest globally while creating vulnerability to drought. Add vast oil reserves from pre-salt fields, sugarcane ethanol leadership, and massive renewable potential, and Brazil emerges as an energy superpower navigating the transition. Hydropower has powered Brazil's development for decades. Iconic dams like Itaipu (14 GW, shared with Paraguay), Belo Monte (11 GW on the Amazon), and Three Gorges rival projects define Brazil's generation fleet. Total hydro capacity exceeds 100 GW. However, dependence creates vulnerability—2021's severe drought forced rationing and increased thermal generation, spiking electricity prices and emissions. Oil production has surged from pre-salt discoveries in deep Atlantic waters. Brazil produces approximately 3 million bpd, making it the ninth-largest producer globally. Petrobras operates massive platforms in the Santos Basin. Brazil targets 5 million bpd by 2030. Natural gas associated with oil is increasingly being monetized. Ethanol from sugarcane has made Brazil a biofuel pioneer. Flex-fuel vehicles dominate sales, running on gasoline-ethanol blends. This reduces oil import dependence and provides a use for agricultural surplus. Renewable energy is booming. Brazil's wind capacity exceeds 25 GW, concentrated in northeastern states. Solar deployment is accelerating rapidly. Biomass from sugarcane bagasse contributes significantly.`,
      7: `Brunei's energy landscape is defined by oil and gas wealth that funds a welfare state, providing citizens with subsidized fuel and electricity while the sultanate navigates the challenge of declining reserves and diversification imperatives. As a small nation of 450,000, Brunei punches above its weight in Southeast Asian energy. Oil production averages approximately 100,000 bpd from onshore and offshore fields, down from peaks above 200,000 bpd as mature fields decline. Crude exports generate substantial revenue, though less than in the past. Natural gas is strategically crucial. Brunei produces approximately 1.2 billion cubic feet per day, with most liquefied for export. Brunei LNG has operated for decades, exporting to Japan, South Korea, and other Asian markets. Long-term contracts provide stable revenue, though global LNG market shifts create uncertainty. Electricity generation is entirely gas-fired through thermal plants. Domestic electricity and fuel prices are heavily subsidized—among the world's lowest—reflecting oil wealth distribution but encouraging wasteful consumption. Brunei has minimal renewable energy despite equatorial sunshine. Solar deployment is negligible, with government focus remaining on hydrocarbon exploitation. The challenge is diversification. Brunei Vision 2035 aims to reduce oil dependence, but implementation lags. Declining reserves mean Brunei faces energy transition from a position of weakening petro-revenue, complicating financing of alternatives.`,
      8: `Bulgaria's energy system reflects its post-communist legacy and strategic position: heavy reliance on nuclear power and Russian gas, aging infrastructure, and challenges balancing EU decarbonization commitments with economic constraints and energy security imperatives intensified by the Ukraine war. Nuclear power provides approximately 35% of Bulgaria's electricity through the Kozloduy plant, which operates two Russian VVER reactors. Four older Soviet reactors were shut down as a condition of EU accession, reducing capacity. Plans exist to build new units with Russian, American, or Korean technology, but financing and geopolitics complicate decisions. Coal, primarily lignite, provides another 40% of electricity from aging plants including Maritsa East complex. These facilities are among Europe's most polluting but provide cheap baseload power and employ thousands in mining regions. EU emissions rules will force retrofits or closures, creating economic and social challenges. Natural gas, almost entirely imported from Russia via pipelines through Ukraine and Turkey, heats buildings and provides backup power generation. The Ukraine war forced Bulgaria to scramble for alternatives, securing LNG via Greece and signing contracts with Azerbaijan. Renewable energy has grown. Wind farms in northeastern Bulgaria and solar installations contribute approximately 20% of electricity. Further expansion requires grid upgrades.`,
      9: `Burkina Faso's energy system serves one of West Africa's poorest nations with minimal electricity access and heavy dependence on biomass. Security challenges from jihadist insurgency further constrain energy infrastructure development and investment. Electricity access is approximately 20% nationally, concentrated in Ouagadougou and Bobo-Dioulasso. Rural electrification is minimal. Installed capacity totals roughly 400 MW, far below potential demand if access expanded. Generation relies on imported fuel for thermal plants and some solar. Burkina Faso imports all petroleum products, creating vulnerability to price shocks. Diesel generators provide backup power for businesses and wealthy households. Biomass—primarily firewood and charcoal—provides over 80% of household energy, contributing to deforestation and indoor air pollution. Solar potential is excellent given Sahel sunshine. Several solar farms have been developed with donor financing, including the Zagtouli solar plant near Ouagadougou. Off-grid solar systems are expanding in rural areas through NGO programs. Energy policy targets increased access and renewable deployment, but security crisis and limited fiscal resources constrain implementation.`,
      10: `Burundi's energy system serves one of the world's poorest countries with minimal electricity access and heavy reliance on biomass. Hydropower provides limited electricity generation while the majority of Burundians depend on firewood, contributing to severe deforestation. Electricity access is approximately 10% nationally, among Africa's lowest. Installed capacity totals roughly 100 MW, primarily from small hydropower plants on the Rusizi River and Lake Tanganyika tributaries. Generation falls far short of even current limited demand, causing frequent outages in Bujumbura. Biomass provides over 95% of household energy. Firewood and charcoal consumption has stripped hillsides, causing erosion and environmental degradation. Burundi imports petroleum products for transport and generators, consuming scarce foreign exchange. The country has no domestic fossil fuel production. Renewable potential exists. Additional hydropower sites could be developed with financing. Solar resources are good, and small-scale solar deployment is occurring through donor programs and off-grid systems. Peat deposits exist and have been used for power generation experimentally, though environmental and efficiency concerns limit viability. Energy policy targets increased access through both grid extension and off-grid renewables, but implementation requires international financing Burundi lacks.`,
      11: `Cambodia's energy system has expanded rapidly to support economic growth but relies heavily on imported coal and increasing amounts of hydropower with controversial environmental and social impacts. The country faces the challenge of balancing development energy needs with sustainability. Coal has become Cambodia's dominant electricity source. Large coal plants using imported Indonesian coal provide baseload power. The controversial Cambodian coal plants at Sihanoukville and elsewhere burn imported thermal coal, creating air pollution and climate concerns. Hydropower provides significant generation through dams on the Mekong, Stung Treng, and tributary rivers. Major dams including Lower Sesan 2 have generated controversy over displacement of communities, impacts on fisheries, and downstream effects on the Mekong River system critical to millions. Natural gas potential exists offshore, but development has been slow due to regulatory and investment challenges. Thailand has expressed interest in Cambodian gas for import. Solar deployment is growing. Cambodia's tropical sunshine provides excellent potential, and utility-scale solar farms are being developed. Rooftop solar is expanding in Phnom Penh. Biomass from rice husks and agricultural waste contributes some generation. Cambodia imports petroleum products for transport. Electricity prices are relatively high compared to neighbors, creating competitiveness concerns.`,
      12: `Cameroon's energy landscape reflects the challenges facing many African countries: significant hydro and fossil fuel potential but low electricity access and underinvestment in infrastructure. Oil production provides export revenue while most Cameroonians lack grid electricity. Oil production averages approximately 60,000 bpd from offshore fields and the Bakassi peninsula, down from peaks above 150,000 bpd as fields mature. Oil exports generate crucial revenue for the government. Cameroon operates a small refinery at Limbe, though most refined products are imported. Natural gas associated with oil production is largely flared, though plans exist to monetize gas for power generation and LNG export. The Kribi gas plant represents efforts to utilize this resource. Hydropower dominates electricity generation. Major dams include Lagdo on the Bénoué River, Edéa, and Song Loulou. Additional large hydro projects are under development, including the massive Grand Inga project if it proceeds. However, electricity access is only approximately 60% nationally, dropping to 20% in rural areas. Biomass provides the majority of household energy, contributing to deforestation. Solar potential is good, and off-grid solar is expanding in rural areas. Cameroon's energy challenge is translating resource potential into accessible, affordable electricity.`,
      13: `Canada is an energy superpower blessed with vast fossil fuel reserves, hydropower, uranium, and renewable potential. The country is the world's fourth-largest oil producer, a major natural gas exporter, and generates 60% of electricity from hydropower. Yet energy politics are deeply divisive, splitting provinces and political parties. Oil is concentrated in Alberta's oil sands—170 billion barrels of reserves, though extraction is energy-intensive and high-cost. Production totals approximately 5.5 million bpd. Pipelines to transport crude to markets are politically contentious. The Trans Mountain expansion faced years of opposition before completion in 2024. Keystone XL was canceled. Natural gas production approaches 17 billion cubic feet per day, with exports via pipeline to the United States and growing LNG exports from British Columbia. Canada is becoming a major LNG supplier to Asia and Europe. Hydropower dominates electricity in Quebec, British Columbia, Manitoba, and Newfoundland/Labrador. Nuclear provides baseload in Ontario. Coal has been phased out of power generation in most provinces, replaced by renewables. Oil-rich Alberta and Saskatchewan clash with climate-focused provinces over emissions policy. Federal carbon pricing sparked fierce opposition from conservative provinces. The challenge: balancing energy exports that fund prosperity with emissions reductions necessary for climate goals.`,
      14: `Central African Republic's energy system barely functions in a country devastated by civil conflict. Electricity access is approximately 15%—among the world's lowest—concentrated in Bangui. The CAR has hydropower potential but chronic instability prevents development. The Boali hydropower plant near Bangui provides limited generation when operational, but conflict and lack of maintenance cause frequent failures. Electricity supply in Bangui is sporadic at best, with frequent multi-day outages. Imported diesel generators provide backup power for those who can afford fuel. Biomass—firewood and charcoal—provides over 95% of household energy. Forests are being depleted despite low population density, as charcoal production for Bangui's markets drives cutting. The CAR imports petroleum products, primarily from Cameroon, via poor roads that make transport expensive and unreliable. Renewable potential exists—solar resources are excellent, and additional hydropower sites could be developed. However, investment requires stability that has eluded the CAR for decades. Energy policy is effectively non-existent given state collapse and ongoing conflict.`,
      15: `Chad's energy system reflects extreme underdevelopment: oil production generates export revenue while domestic electricity access is minimal and biomass dominates household energy. The gap between oil wealth and energy poverty is stark. Oil production averages approximately 130,000-150,000 bpd from the Doba fields in southern Chad, exported via pipeline through Cameroon to Atlantic markets. Oil revenues fund much of the government budget, though corruption and mismanagement limit benefits for ordinary Chadians. Domestic refinery capacity is minimal. Chad imports refined petroleum products, creating the absurdity of an oil-producing nation suffering fuel shortages and high prices. Electricity access is approximately 10% nationally, among Africa's lowest. N'Djamena and a few other cities have limited grid electricity, primarily from diesel generators. Generation capacity totals roughly 100 MW for a population of 17 million. Biomass provides over 90% of household energy. Firewood and charcoal consumption contributes to desertification in Chad's Sahel regions. Solar potential is exceptional given Chad's Saharan climate. However, deployment is minimal—limited to small off-grid systems and donor projects. Chad's energy challenge is translating oil wealth into basic energy access, requiring governance improvements and massive investment.`,
      16: `Chile's energy transformation over the past decade exemplifies how a country can shift rapidly from fossil fuel dependence to renewable leadership. Once reliant on imported coal and gas, Chile now generates over 30% of electricity from solar and wind, with targets reaching 70% by 2030. Chile's renewable surge stems from exceptional resources and smart policy. The Atacama Desert receives the world's highest solar irradiation. Massive solar farms now carpet northern Chile, generating cheap electricity that has driven down wholesale prices. Wind resources in Patagonia and central Chile are equally impressive. Installed renewable capacity has skyrocketed. Historically, Chile imported natural gas from Argentina via pipeline (supplies were cut off in 2004 crisis) and coal. Limited domestic fossil fuels forced dependence. LNG import terminals supplied gas for power plants. Hydropower provides significant baseload, though droughts and environmental concerns about new dams limit expansion. Electricity prices have dropped dramatically as renewables displaced expensive imported fuel. However, transmission constraints sometimes cause solar curtailment in the north while Santiago experiences shortages—requiring massive grid investment. Lithium in the Atacama is crucial for global battery supply. Chile is the world's second-largest producer after Australia. Energy policy targets carbon neutrality by 2050, with coal phase-out by 2040.`,
      17: `China's energy system is the world's largest and most consequential for global climate. As the top energy consumer, coal burner, renewable deployer, and emissions source, China's energy choices shape humanity's future. Understanding China requires grasping contradictions: leading solar and wind installation while building coal plants, dominating EV and battery production while consuming record oil. Coal remains dominant, providing approximately 60% of primary energy and electricity generation despite pledges to peak coal consumption. China burns more coal than the rest of the world combined. New coal plants continue being built even as China leads renewable deployment. Oil consumption exceeds 15 million bpd, with growing import dependence. China imports approximately 75% of oil needs, primarily from Middle East, Russia, and Africa. Strategic petroleum reserves and pipeline projects like Power of Siberia aim to enhance security. Natural gas consumption is rising as China shifts from coal for heating and industry. LNG imports have surged, making China the world's largest importer. Pipelines from Central Asia and Russia supplement LNG. Renewable energy deployment is staggering. China installs more solar and wind annually than the rest of the world combined. Solar capacity exceeds 600 GW. Wind capacity tops 400 GW. China manufactures 80% of global solar panels. Nuclear power is expanding with aggressive reactor construction. Hydropower, including Three Gorges, provides massive generation. EVs are transforming transport—China leads production and adoption.`,
      18: `Colombia's energy landscape reflects Andean hydropower abundance, growing oil and gas production, and renewable potential that positions the country as a regional clean energy leader while navigating the challenge of fossil fuel export dependence. Hydropower dominates electricity generation, providing approximately 70% through dams exploiting Colombia's mountainous geography and heavy rainfall. Major plants include El Quimbo, Hidroituango (despite construction disasters), and numerous smaller facilities. This clean generation makes Colombia's grid among the world's least carbon-intensive. Oil production averages approximately 800,000 bpd from fields including Caño Limón, Rubiales, and offshore Caribbean prospects. Production has declined from peaks above 1 million bpd, spurring efforts to boost exploration. Oil exports generate crucial revenue. Colombia operates refineries including Barrancabermeja, though some refined product imports are still necessary. Natural gas production serves domestic consumption and small-scale exports. Coal, primarily thermal coal from Cerrejón and other mines, is exported to global markets, generating revenue but creating climate contradictions. Renewable energy is surging. Solar and wind projects are being developed in La Guajira and other regions with excellent resources. Colombia targets 70% renewable electricity by 2030. Energy policy balances fossil fuel revenues with climate commitments. President Petro has pledged to halt new oil and coal development, though implementation faces industry and fiscal pressures.`,
      19: `Costa Rica's energy achievement is remarkable: over 98% of electricity from renewables for years running, making this small Central American nation a global clean energy exemplar. Hydropower, geothermal, wind, solar, and biomass provide almost all generation, demonstrating that high renewable penetration is achievable. Hydropower dominates, exploiting Costa Rica's mountainous terrain and abundant rainfall. Major dams and run-of-river plants provide baseload and peaking power. Seasonal variations create some challenges during dry periods. Geothermal from volcanic resources is crucial. The Miravalles geothermal complex and other plants tap the volcanic arc's heat. Geothermal provides stable baseload complementing hydropower's variability. Wind farms in the central highlands contribute significantly. Costa Rica's wind resources are good, and projects like Tierras Morenas have been developed. Solar deployment is growing rapidly, with distributed rooftop systems expanding and utility-scale farms being built. Bagasse from sugar processing provides biomass generation. However, transport remains dependent on imported petroleum. Costa Rica imports all oil for vehicles, creating the main emissions source. The country targets transport electrification and has promoted EV adoption. Costa Rica's achievement demonstrates that clean electricity is possible with political will and suitable geography. The challenge now is decarbonizing transport while maintaining grid reliability.`,
      20: `Croatia's energy system serves a mid-sized EU member balancing hydropower resources, limited fossil fuel production, and growing renewable deployment with import dependence for much of its energy needs. Tourism's energy demands and seasonal variations create additional challenges. Hydropower provides approximately 40% of electricity through dams on the Drina and other rivers. Hydro output varies significantly with seasonal rainfall, causing shortfalls during dry years. Natural gas provides heating and power generation. Croatia produces some gas domestically from fields including the offshore Northern Adriatic, but imports are necessary to meet demand. Pipelines from Russia (disrupted since Ukraine invasion) and the Krk LNG terminal (operational since 2021) provide supplies. Oil production is small-scale. Croatia operates the Sisak refinery, though refined product imports supplement domestic output. Coal has been phased out of power generation. Renewable energy is growing. Wind farms along the Adriatic coast exploit strong winds. Solar deployment is accelerating with EU support. Croatia targets higher renewable shares to meet EU climate commitments. Energy policy focuses on diversifying away from Russian gas while expanding renewables.`,
      21: `Cuba's energy crisis epitomizes the island's broader dysfunction: chronic blackouts, aging Soviet-era infrastructure, limited domestic fossil fuels, and an economy in collapse. Energy has become the most acute crisis facing Cubans enduring hours-long daily outages. Oil production is minimal—approximately 40,000-50,000 bpd from aging onshore fields—far below consumption. Cuba historically relied on subsidized Venezuelan oil under Chavismo's patronage. However, Venezuela's collapse reduced supplies, forcing Cuba to import expensive oil it cannot afford. The result: fuel shortages and power crisis. Electricity generation relies on obsolete Soviet-era thermal plants burning heavy fuel oil. These facilities frequently break down. When major plants like Matanzas go offline, system failures cascade, causing island-wide blackouts. September 2024's extended blackouts demonstrated infrastructure fragility. Renewable deployment is minimal. Cuba has solar potential but lacks financing for large-scale projects. Some distributed solar exists. Bagasse from sugar mills provides some generation. Energy policy is constrained by Cuba's economic isolation. U.S. sanctions prevent access to financing and technology. Russian and Chinese assistance has been limited. Cuba's energy future is dire without massive investment it cannot afford.`,
      22: `Cyprus's energy landscape is shaped by its division, isolation, and recent offshore gas discoveries that promise to transform the island's fortunes while intensifying geopolitical tensions with Turkey. Energy dependence and high costs have long burdened Cyprus, making gas finds potentially transformative. Cyprus relies entirely on imported petroleum for electricity generation and transport. Heavy fuel oil and diesel power plants provide electricity, making generation expensive and polluting. Electricity prices are among Europe's highest. The discovery of the Aphrodite gas field offshore in 2011, followed by additional finds including Glaucus, created excitement. Estimated reserves exceed 4 trillion cubic feet. However, development has been slow due to disputes with Turkey over maritime boundaries, modest field sizes that challenge economics, and debates over monetization (pipeline vs. LNG). Renewable energy is growing. Solar potential is excellent given Mediterranean sunshine. Rooftop solar has expanded rapidly, and utility-scale farms are being built. Wind resources are good, with projects in mountain areas. Cyprus targets 23% renewable electricity by 2030. Energy policy focuses on natural gas development to reduce oil dependence while expanding renewables. However, Turkish military opposition to drilling in disputed waters creates risks.`,
      23: `Czechia's energy system reflects its post-communist legacy: heavy reliance on coal for electricity and heating, substantial nuclear power, and import dependence for oil and gas. As an EU member, Czechia faces pressure to decarbonize while managing social and economic costs of transition. Coal, primarily brown coal (lignite), has provided cheap electricity for decades. Major plants in northern Bohemia burn domestic coal, creating severe air pollution but supporting employment in mining regions. Czechia's coal phase-out timeline is debated—EU pressure pushes for 2033, but government and industry seek delays. Nuclear power provides approximately 37% of electricity through the Dukovany and Temelín plants using Soviet-designed but modernized reactors. Plans exist to build new nuclear capacity to replace aging coal, but financing and technology choices create political battles. Natural gas, mostly imported from Russia via pipelines through Slovakia, provides heating and industrial energy. The Ukraine war forced scramble for alternatives, including LNG via German terminals. Oil is entirely imported. Renewable energy is growing but lags EU averages. Solar deployment expanded rapidly after generous subsidies then crashed when policies changed. Wind has been slower due to permitting challenges. Czechia targets 30% renewable electricity by 2030.`,
      24: `The Democratic Republic of Congo's energy paradox is profound: the Inga Falls on the Congo River has potential for 40,000+ MW hydropower—more than enough to power all of Africa—yet only 20% of Congolese have electricity access. Resource wealth coexists with energy poverty. Current electricity generation totals approximately 2,700 MW, primarily from the Inga 1 and Inga 2 dams built in the 1970s-80s. These aging facilities operate below capacity due to poor maintenance. Inga 3 project has been planned for decades but remains unrealized due to corruption, financing challenges, and governance failures. If built, Grand Inga could transform African energy, providing power across the continent via transmission interconnections. However, DRC lacks capacity to execute such megaprojects. Small hydro plants provide power in provincial centers, but generation is limited and unreliable. Biomass provides over 90% of household energy. Firewood and charcoal consumption drives deforestation. The DRC has significant oil production in offshore Atlantic fields and onshore in the west, totaling approximately 25,000 bpd. However, limited refining capacity necessitates fuel imports. Energy policy theoretically prioritizes access expansion and Inga development, but implementation requires governance and financial capacity DRC lacks.`,
      25: `Denmark exemplifies the European renewable energy transition: wind power provides over 50% of electricity, making Denmark a global leader while highlighting challenges of intermittency and system integration. Ambitious climate targets drive continued transformation. Wind dominates Denmark's energy story. Offshore wind farms in the North Sea and Baltic including Horns Rev, Kriegers Flak, and numerous others generate massive power. Denmark pioneered offshore wind technology and deployment. Onshore wind adds further capacity. During windy periods, wind can exceed 100% of demand, with exports to Norway, Sweden, and Germany. Natural gas provides flexible backup generation and heating. Denmark produces gas from North Sea fields, though production is declining. Imports supplement domestic output. Oil production from North Sea fields like Dan and Halfdan has also declined from peaks. Denmark was briefly oil-independent but is now a modest net importer. Biomass, particularly waste and agricultural residues, provides heat and power through district heating systems and CHP plants. Solar deployment is growing despite northern latitude limitations. Energy policy targets 100% renewable electricity and 70% overall emissions reduction by 2030. However, wind intermittency requires massive grid connections to Scandinavian hydro (Norway) and German backup. Battery storage and power-to-X (hydrogen) are being developed. Denmark's success demonstrates renewable potential but also integration challenges.`,
      26: `Djibouti's energy system serves a small nation of strategic importance as a Red Sea port and military hub. The country has minimal domestic generation capacity and imports most electricity from Ethiopia, creating dependence that drives renewable development plans. Electricity access is approximately 60% nationally. Djibouti City has grid access, but rural areas rely on diesel generators or lack power entirely. Installed capacity totals roughly 130 MW, inadequate for growing demand. Electricity imports from Ethiopia via transmission lines provide substantial supply. However, dependence creates vulnerability to disruptions and price fluctuations. Djibouti imports all petroleum products for transport and diesel generators. Renewable potential is substantial. Geothermal resources in the Afar region, part of the East African Rift, could provide baseload power. Projects have been planned but development is slow due to financing challenges. Solar potential is excellent given Red Sea sunshine. Wind resources are good. Some solar projects have been developed. Energy policy targets renewables to reduce import dependence, but implementation requires foreign investment.`,
      27: `Dominican Republic's energy system serves a Caribbean nation with growing electricity demand from tourism and development, relying heavily on imported fossil fuels that create high costs and vulnerability. Renewable deployment is accelerating but from a low base. Natural gas provides the largest share of electricity generation through plants using imported LNG. The AES Andrés facility and others burn gas in combined-cycle plants, providing efficiency and lower emissions than previous oil firing. Coal is used in some plants despite environmental opposition. Petroleum products, entirely imported, fuel transport and diesel backup generation. Oil import dependence creates fiscal stress when global prices spike. Hydropower provides some generation through dams, but potential is limited and drought affects reliability. Renewable energy is growing. Solar farms are being developed, exploiting the Caribbean's abundant sunshine. Wind farms in mountainous regions contribute capacity. Biomass from sugarcane bagasse supplements generation during harvest seasons. The Dominican Republic targets 25% renewable energy by 2025, requiring accelerated deployment. Electricity prices are high compared to regional averages, reflecting import dependence. Energy policy focuses on diversifying fuels and expanding renewables to reduce costs and improve energy security.`,
      28: `East Timor's energy system faces the challenges of a young nation (independent since 2002) with offshore oil and gas wealth that funds government but limited domestic energy infrastructure. Most Timorese lack reliable electricity, creating stark contrasts between resource revenue and energy poverty. Oil and gas from the Joint Petroleum Development Area in the Timor Sea, particularly the Bayu-Undan field, has provided billions in revenue funding East Timor's budget. However, production has declined as fields mature, creating fiscal pressures. The massive Greater Sunrise field holds potential but remains undeveloped due to disputes over development pathway and revenue sharing with Australia. Electricity access is approximately 50% nationally. Dili and district capitals have grid power, primarily from imported diesel generators, but reliability is poor with frequent outages. Rural areas largely lack grid access. Imported petroleum products fuel everything from generators to transport, consuming scarce foreign exchange. Renewable potential is good. Solar resources are excellent given tropical latitude. Some solar projects have been developed with donor assistance. Small hydro potential exists. Energy policy targets increased access and renewable deployment, but implementation requires investment and capacity East Timor struggles to mobilize despite oil revenues.`
    };
    
    if (summaries[i]) {
      W.push({ name: countries.name, lat: countries.lat, lng: countries.lng, summary: summaries[i] });
    }
  }
}

async function main() {
  console.log(`Saving ${W.length} Energy writeups (batch B - large batch)...\n`)
  for (const w of W) {
    try {
      await prisma.locationSummary.upsert({
        where: { name_type_category: { name: w.name, type: 'country', category: 'energy' } },
        update: { summary: w.summary, lat: w.lat, lng: w.lng, issues: '[]', topStories: '[]', storyCount: 0, updatedAt: new Date() },
        create: { name: w.name, type: 'country', country: w.name, lat: w.lat, lng: w.lng, category: 'energy', summary: w.summary, issues: '[]', topStories: '[]', storyCount: 0 }
      })
      console.log(`✅ ${w.name}`)
    } catch (error) { console.error(`❌ ${w.name}:`, error) }
  }
  
  const total = await prisma.locationSummary.count({ where: { category: 'energy', type: 'country' } });
  console.log(`\n📊 Total Energy writeups: ${total}/128`)
}

main().finally(() => prisma.$disconnect())
