import { saveEntertainmentSummaries } from './save-entertainment-summaries'

const BATCH_07 = [
  {
    name: 'South Korea',
    summary: `South Korean entertainment has achieved genuine global dominance through strategic cultural investment, creative excellence, and savvy understanding of international markets—the Korean Wave (Hallyu) represents one of the most successful national cultural export campaigns in modern history. Film industry produces everything from auteur works by directors like Bong Joon-ho (whose "Parasite" became the first foreign-language Best Picture Oscar winner) and Park Chan-wook to commercial blockbusters and genre films that blend Korean sensibilities with international appeal. Korean cinema's willingness to genre-bend, social commentary, and tonal shifts distinguishes it globally. Television has conquered the world through K-dramas—from romantic comedies to historical epics, zombie thrillers to social critiques—shows like "Squid Game," "Kingdom," and countless others became global phenomena through Netflix and other platforms. K-pop is perhaps Korea's most visible cultural export—groups like BTS, Blackpink, and countless others command massive global fandoms through meticulously produced music, elaborate choreography, and social media mastery. The K-pop industry system, while controversial for its treatment of trainees, produces extraordinarily polished entertainment. Korean gaming industry is massive—both in development (producing globally successful titles) and esports, where Korea pioneered competitive gaming culture and maintains dominance in multiple titles, particularly League of Legends and StarCraft. Korean variety shows, beauty standards, and fashion influence global trends. Social media usage is intense, with Korean creators building global followings. Korean entertainment succeeds through professionalism, investment, and understanding that quality production values combined with emotionally resonant storytelling can transcend linguistic and cultural barriers, making Korea a cultural superpower wildly disproportionate to its population.`
  },
  {
    name: 'North Korea',
    summary: `North Korean entertainment exists entirely as state propaganda, every film, television show, song, and performance serving the Kim regime's political objectives and personality cult with no independent creative expression permitted. Film production consists mainly of works glorifying the Kim dynasty, demonizing America and South Korea, and depicting North Korean life as socialist paradise despite catastrophic reality. The regime kidnapped South Korean director Shin Sang-ok and actress Choi Eun-hee in the 1970s to improve North Korean cinema, forcing them to produce propaganda films before their eventual escape. Contemporary productions remain crude by international standards though technically competent for propaganda purposes. Television broadcasts only state-controlled content—news praising the leadership, approved films, and performances. The Moranbong Band, an all-female pop group, represents regime-approved modern entertainment, performing sanitized pop music celebrating the nation and leadership. Traditional Korean music and dance performances maintain cultural heritage in highly controlled contexts. Gaming doesn't exist in recognizable form—the population has no access to international games or gaming culture, though the regime has produced simple educational and propaganda games for internal use. Social media is nonexistent for ordinary citizens—North Korea is almost entirely offline, with only elite access to heavily monitored internal networks. Entertainment consumption means watching state television, attending approved performances, or reading approved literature. The regime occasionally produces material attempting to mimic South Korean or Western entertainment styles but imbued with propaganda messaging. North Korean entertainment represents totalitarianism's cultural dead end—complete control producing joyless, artistically worthless propaganda that serves only political indoctrination, demonstrating that entertainment requires creative freedom to produce anything resembling actual value or pleasure.`
  },
  {
    name: 'Indonesia',
    summary: `Indonesian entertainment operates at enormous scale befitting the world's fourth-most populous nation, creating content across film, television, music, and digital platforms that serves diverse audiences spanning hundreds of ethnic groups and islands while navigating Islamic conservatism, democratic freedoms, and rapid technological change. Film industry produces substantial output from commercial horror films and romantic comedies to social dramas and occasional auteur works that earn international festival recognition. Indonesian cinema increasingly explores contemporary social issues including religious extremism, corruption, and class divisions within permissible boundaries. Action films, particularly "The Raid" series, demonstrated Indonesian martial arts cinema's global appeal. Television produces enormous quantities of content from soap operas (sinetron) to reality shows, religious programming to variety shows, serving audiences across the archipelago. Streaming platforms have invested heavily in Indonesian content recognizing the massive market. Music is extraordinarily diverse—dangdut (a distinctive Indonesian pop style blending Malay, Indian, and Arabic influences) remains hugely popular; Indonesian pop spans from saccharine ballads to contemporary hip-hop and electronic music; punk and metal scenes thrive; while traditional gamelan and regional music forms maintain cultural vitality. Indonesian artists primarily serve domestic and Southeast Asian markets. Gaming culture is massive—Indonesia has one of the world's largest gaming populations, with mobile gaming particularly dominant. Esports viewership and participation are enormous, with Indonesian teams competing regionally. Social media usage is intense, with Indonesians among the world's most active social media users, creating content across platforms particularly comedy, music, and lifestyle material. Indonesian entertainment reflects the nation's complexity—majority Muslim but pluralistic, traditional yet rapidly modernizing, serving massive domestic markets while building regional influence.`
  },
  {
    name: 'Australia',
    summary: `Australian entertainment punches significantly above its population weight, producing globally successful work across multiple sectors while maintaining distinctively Australian characteristics—irreverent humor, unpretentious creativity, and healthy skepticism of authority and pretension. Film industry has generated international stars and acclaimed directors—from Mad Max through Crocodile Dundee to contemporary auteurs like George Miller, Baz Luhrmann's maximalist spectacles, and indie directors crafting intimate Australian stories. Australian actors dominate Hollywood (Cate Blanchett, Hugh Jackman, Margot Robbie, Chris Hemsworth, Nicole Kidman, endless others) while often maintaining Australian film careers. Government funding supports diverse Australian stories though budgets can't compete with Hollywood. Television produces quality work from soap operas like "Neighbours" that launched countless careers to crime dramas, comedies, and reality shows, with Australian formats and programs selling internationally. Streaming investments have accelerated local production. Music scene is ferociously vibrant—from AC/DC and INXS through contemporary indie rock, electronic music, hip-hop artists, and pop stars who achieve varying degrees of international success. Australian music festivals draw massive crowds while pub rock culture maintains grassroots vitality. Gaming culture is substantial—Australian developers have created globally successful titles, though controversial rating systems and internet infrastructure have created challenges. Esports communities thrive despite geographic isolation creating latency issues. Social media creators leverage Australia's stunning landscapes, beach culture, and deadly wildlife humor, building massive followings. Australian entertainment succeeds through authenticity and quality—Australians make distinctively Australian work without trying to imitate American or British productions, trusting that authentic voices and good stories will find audiences regardless of accent or setting.`
  },
  {
    name: 'New Zealand',
    summary: `New Zealand entertainment operates with remarkable effectiveness for a nation of five million, leveraging stunning landscapes, government support, and distinctive Kiwi creativity into international recognition far exceeding the country's tiny population. Film industry achieved global prominence through Peter Jackson's "Lord of the Rings" and "Hobbit" trilogies, which demonstrated New Zealand's production capabilities and established the nation as a premier filming location. Directors like Jane Campion and Taika Waititi craft distinctive work blending New Zealand perspectives with international appeal, with Waititi particularly successfully navigating between intimate Kiwi comedies and Marvel blockbusters. New Zealand's Māori culture increasingly shapes entertainment, from "Whale Rider" through contemporary works centering indigenous perspectives. Television produces quality content from comedies like "Flight of the Conchords" earning cult international followings to the recent streaming investments in New Zealand stories. Music scene maintains vitality despite tiny domestic market—artists from Crowded House through Lorde, from Fat Freddy's Drop to countless indie bands demonstrate New Zealand's musical creativity, while the nation's isolation creates distinctive sounds. Gaming culture thrives—New Zealand developers have created successful titles, while the country's esports communities maintain passionate engagement despite small population. Social media creators capitalize on New Zealand's spectacular landscapes, adventure tourism, and Kiwi humor, building substantial followings particularly in travel and outdoor adventure sectors. New Zealand entertainment succeeds through leveraging natural advantages (landscapes that appear otherworldly on screen), government support that enables risk-taking, and creative confidence that produces distinctly Kiwi work without provincialism. The nation proves small populations needn't limit cultural influence when quality, distinctiveness, and strategic support align effectively.`
  },
  {
    name: 'Pakistan',
    summary: `Pakistani entertainment navigates complex terrain—Islamic values, censorship, political instability, economic challenges, and rivalry with India's dominant entertainment industry, yet producing work of genuine quality and cultural significance, particularly in television and music. Pakistani cinema has historically struggled, with "Lollywood" facing competition from Bollywood until recent revivals producing commercial successes and occasional quality films exploring Pakistani identity, history, and contemporary issues within religious and political constraints. Film production remains modest compared to India but shows growth. Television drama is Pakistan's entertainment crown jewel—Pakistani serials are sophisticated, well-acted explorations of family, marriage, social issues, and tradition versus modernity that earn massive viewership across Pakistan and South Asian diaspora communities. Shows tackle complicated social issues including domestic violence, class divisions, and women's rights within culturally acceptable frameworks. Music remains vital—Qawwali and classical traditions maintain importance; Nusrat Fateh Ali Khan's legacy influences globally; pop, rock, and contemporary artists like Atif Aslam and Coke Studio Pakistan showcase Pakistani musical creativity; while underground scenes navigate religious conservatism's constraints. Gaming culture exists but faces limitations—infrastructure challenges, economic constraints, and religious conservatism around gaming content limit development, though PUBG Mobile and similar games maintain popularity among youth. Social media usage has exploded, with Pakistani creators building substantial followings particularly in comedy, lifestyle, and political commentary, though content must navigate religious and political sensitivities carefully. Pakistani entertainment's challenge is serving conservative domestic audiences while competing with superior-resourced Indian productions and international content, succeeding when it embraces Pakistani specificity and cultural values rather than imitating Bollywood or Western models.`
  },
  {
    name: 'Bangladesh',
    summary: `Bangladeshi entertainment operates somewhat under international radar despite the nation's enormous population, producing content primarily for domestic consumption while navigating economic constraints, periodic political instability, and cultural conservatism. Film industry, known as Dhallywood, produces substantial output though quality varies dramatically—from earnest social dramas to formulaic romantic films and action movies often compared unfavorably to Bollywood productions. Bangladeshi cinema has historically struggled with funding, piracy, and competition from Indian films, though occasional works earn critical acclaim for exploring Bengali identity, history, and contemporary issues. Liberation War films remain popular, commemorating 1971 independence struggle. Television produces enormous quantities of content, from soap operas exploring family dynamics to reality shows, religious programming to news and talk shows serving Bangladeshi audiences domestically and across diaspora communities. Music spans from traditional Baul and folk forms maintaining cultural importance through contemporary pop, rock, and fusion artists blending Bengali sensibilities with global genres. Bangladesh's musical heritage connects to broader Bengali culture shared with India's West Bengal. Gaming culture has grown substantially among youth—mobile gaming particularly, with affordable smartphones enabling access. Esports communities are emerging though infrastructure and economic constraints limit development. Social media usage has exploded, with Bangladeshi creators building followings particularly in comedy, music, and lifestyle content, while platforms serve as crucial spaces for political discourse despite occasional government crackdowns. Bangladeshi entertainment's fundamental challenge is resources—creating quality content with limited budgets while competing with better-funded Indian productions and international content, succeeding when focusing on distinctly Bangladeshi stories told with authenticity and cultural specificity that resonates domestically even if international recognition remains limited.`
  },
  {
    name: 'Afghanistan',
    summary: `Afghan entertainment has experienced catastrophic collapse following the Taliban's August 2021 return to power, decades of cultural development obliterated as the regime banned music, restricted television, and imposed severe constraints on all artistic expression, particularly for women now forbidden from singing publicly or appearing in media. Before the Taliban takeover, Afghan entertainment had experienced remarkable revival—television produced popular dramas, reality shows like Afghan Star (Afghanistan's version of American Idol), and news programming; film industry created modest but culturally significant works exploring Afghan identity and history; music scenes spanning from traditional Afghan instruments and styles through pop singers who became massive regional stars, with artists like Aryana Sayeed building international followings. Afghan musicians blend Persian, Turkic, Indian, and Central Asian influences creating distinctive sounds. The entertainment industry had become economically significant employer, particularly in Kabul, providing opportunities especially for young people and women in conservative society. Social media had enabled Afghan creators to build audiences and express perspectives otherwise restricted. Gaming culture existed primarily around internet cafés and mobile devices. Post-Taliban, Afghan entertainment exists mainly in diaspora—musicians, actors, and creators who fled Afghanistan continue working in exile, maintaining Afghan cultural production while grieving the collapse at home. Inside Afghanistan, entertainment has returned to the Taliban's previous ban on most music and imagery, with only Taliban-approved religious content and propaganda permitted. Afghan entertainment's tragedy is its destruction just as it was flourishing, demonstrating culture's fragility under totalitarian ideology that views artistic expression as threat, with Afghan creative community scattered globally attempting to preserve traditions and contemporary expressions while hoping for eventual return.`
  },
  {
    name: 'Iran',
    summary: `Iranian entertainment operates under severe Islamic Republic restrictions yet manages to produce work of genuine artistic merit, particularly in cinema where Iranian directors have achieved remarkable international recognition despite—or sometimes because of—censorship constraints that force metaphorical, oblique storytelling. Film directors like Abbas Kiarostami, Asghar Farhadi, and Jafar Panahi craft profound works exploring human nature, social dynamics, and Iranian society within strict content rules prohibiting physical contact, sexual content, and political criticism. Iranian cinema's reputation for subtle, humanistic storytelling has made it festival circuit staple, with films earning Oscars and Cannes prizes. However, filmmakers face arrest, travel bans, and censorship, with Panahi currently imprisoned. Television consists mainly of state-controlled content—religious programming, approved historical dramas, and sanitized entertainment, though satellite dishes (illegal but widespread) enable Iranians to access international programming. Music faces severe restrictions—pop music performances are banned or tightly controlled, Western instruments and styles officially discouraged, female solo singing prohibited in public. Yet underground music scenes thrive, with Iranian hip-hop, rock, and electronic artists circulating music digitally despite risks. Traditional Persian music maintains cultural importance. Gaming exists in gray areas—video games are popular among Iranian youth despite official suspicion, with Iranian gamers participating in international communities using VPNs. Social media is simultaneously restricted and enormous—Iranians use VPNs to access banned platforms, with Iranian social media usage among the world's highest despite government blocks. Iranian entertainment's tragedy and triumph is creative persistence despite authoritarian constraints, artists finding ways to create meaningful work even when freedom would enable so much more.`
  },
  {
    name: 'Israel',
    summary: `Israeli entertainment operates with remarkable vitality, this small nation producing quality work across multiple sectors that achieves international recognition while serving diverse domestic audiences spanning secular and religious, Jewish and Arab, native-born and immigrant communities. Television has become Israel's most successful cultural export—shows like "Fauda," "Shtisel," and "Tehran" have been adapted internationally or streamed globally, while "Homeland" and "In Treatment" are based on Israeli series, demonstrating Israeli television's creativity in exploring political tensions, religious communities, and security obsessions through compelling narratives. Streaming platforms heavily invest in Israeli content. Film production includes auteur works exploring Israeli identity, history, and Palestinian conflict through various perspectives, with directors earning festival recognition, alongside commercial films and documentaries. Israeli cinema often grapples with military service, Holocaust legacy, and contemporary politics. Music scene is extraordinarily diverse—from Mizrahi music blending Middle Eastern and Mediterranean influences to Israeli rock, electronic music, hip-hop, and pop artists achieving varying international success. Eurovision provides platform for Israeli artists, with occasional wins. Classical music maintains high standards. Gaming culture thrives—Israel has produced successful game developers and maintains strong esports communities, with Israeli tech expertise translating into gaming innovation. Social media creators build substantial followings, from tech influencers to lifestyle and beauty content, though political content navigates polarized audiences. Israeli entertainment reflects the nation's contradictions—Western-oriented yet Middle Eastern-influenced, ancient history and startup culture, security obsessions and creative freedom, creating distinctly Israeli cultural products that engage with complexity rather than simplifying it.`
  }
]

async function main() {
  console.log('🎬 ENTERTAINMENT BATCH 07: Countries 61-70')
  console.log('='.repeat(80))

  const result = await saveEntertainmentSummaries(BATCH_07)

  console.log('\n✅ Batch 07 complete!')
  console.log(`Saved ${result.successCount} summaries to database`)
}

main()
