import { saveEntertainmentSummaries } from './save-entertainment-summaries'

const BATCH_04 = [
  {
    name: 'Italy',
    summary: `Italian entertainment operates in the shadow of its own glorious past while simultaneously producing vital contemporary work that honors tradition without being imprisoned by it. Cinema remains the jewel—from Fellini and Antonioni's legacy through current masters like Paolo Sorrentino (whose baroque visual style and thematic obsessions with beauty and decay earned him an Oscar for "The Great Beauty") and Matteo Garrone (whose genre-hopping from Neorealist crime dramas to dark fairy tales demonstrates Italian cinema's range). The Venice Film Festival maintains its prestige as one of the world's most important, while Italian genre cinema, from giallo to poliziotteschi, influences filmmakers globally. Television has evolved dramatically, with shows like "My Brilliant Friend" and "Gomorrah" earning international acclaim for their unflinching portrayals of Italian society, from Naples' criminal underworld to female friendship's complexities. Italian music maintains curious contradictions: domestically, the Sanremo Festival drives mainstream pop culture with dramatic intensity Americans reserve for the Super Bowl, while internationally, Italian artists struggle for visibility beyond opera and classical traditions. Yet artists like Måneskin recently proved Italian rock can conquer global charts, their Eurovision victory launching genuine worldwide success. Hip-hop in Italian has grown massively, with artists like Ghali, Sfera Ebbasta, and Mahmood blending Italian sensibilities with international urban sounds. Gaming culture is substantial—Italy boasts significant esports communities and game development studios, while social media creators thrive in fashion, food, and lifestyle sectors where Italian expertise translates into global authority. Italian entertainment succeeds when it embraces its contradictions—ancient and modern, high culture and low, provincial and cosmopolitan—creating work that feels simultaneously timeless and urgently contemporary.`
  },
  {
    name: 'Spain',
    summary: `Spanish entertainment has experienced a remarkable renaissance over the past two decades, evolving from regional industry to global player with confidence, creativity, and commercial savvy. Film production showcases extraordinary range: Pedro Almodóvar continues crafting visually sumptuous melodramas exploring desire, identity, and Spanish society; directors like Alejandro Amenábar and J.A. Bayona deliver polished genre films that travel internationally; while younger filmmakers like Carla Simón craft intimate, observational works earning festival acclaim. Spanish television's streaming-era explosion has been extraordinary—"Money Heist" became Netflix's most-watched non-English series, while shows like "Elite," "Veneno," and "The Cook of Castamar" demonstrate Spanish producers' ability to craft addictive, culturally specific content that translates globally. Music remains vibrantly diverse: flamenco's traditional forms coexist with fusion innovators; Latin trap and reggaeton artists like Rosalía, Bad Gyal, and C. Tangana blur lines between Spanish and Latin American markets; while rock, indie, and electronic scenes thrive domestically. Spain's linguistic advantage—sharing language with Latin America's massive markets—enables artists to achieve scale impossible for most European nations. Gaming culture is massive, with Spain boasting one of Europe's largest gaming markets, successful esports organizations, and thriving game development studios. Social media creators leverage Spain's visual appeal, lifestyle, and cultural richness, building massive followings in travel, food, and fashion sectors. The Goya Awards maintain prestige domestically while Spanish talent increasingly appears in international productions. What distinguishes Spanish entertainment is its fearless embrace of melodrama, visual excess, and emotional intensity, creating work that feels refreshingly alive in an often ironically detached entertainment landscape.`
  },
  {
    name: 'Poland',
    summary: `Polish entertainment navigates complex cultural currents—simultaneously grappling with historical trauma, post-communist transformation, and contemporary political tensions while producing work of genuine artistic merit and popular appeal. Film remains Poland's strongest cultural export, with directors like Paweł Pawlikowski crafting austere masterpieces ("Ida," "Cold War") that earn Oscar nominations and festival prizes, while mainstream filmmakers deliver historical epics and war dramas exploring Poland's turbulent twentieth century. The country's film schools continue producing talented cinematographers and directors who work internationally. Television has evolved significantly, with platforms like HBO and Netflix investing in Polish originals that explore everything from communist-era stories to contemporary crime dramas, though political pressures on public broadcasting create complications. Poland's music scene operates somewhat under international radar despite domestic vibrancy—hip-hop and trap dominate youth culture, with artists like Taco Hemingway and Quebonafide achieving massive local success; electronic music scenes in Warsaw and Krakow remain influential in European club circuits; while jazz maintains surprising vitality, honoring Poland's historical jazz importance during communist repression. Gaming culture is absolutely enormous—Poland produced CD Projekt Red, developers of "The Witcher" series and "Cyberpunk 2077," making the nation a legitimate gaming powerhouse. Esports viewership and participation continue growing, with Polish teams competitive internationally. Social media creators often address Polish history, culture, and contemporary politics, building communities among Poland's substantial diaspora. Polish entertainment succeeds when it balances historical consciousness with contemporary relevance, creating work that honors memory without being consumed by it, looking forward while remaining aware of what lies behind.`
  },
  {
    name: 'Ukraine',
    summary: `Ukrainian entertainment, even before the 2022 Russian invasion devastated the nation, operated in survival mode—creating vital culture while navigating economic challenges, political instability, and Russian cultural imperialism. The film industry punched above its weight, with directors like Sergei Loznitsa crafting formally rigorous documentaries and fiction films exploring Ukrainian and Soviet history, while mainstream productions increasingly told distinctly Ukrainian stories in Ukrainian language, consciously differentiating from Russian cultural dominance. The post-Maidan period saw accelerated cultural Ukrainianization as artists reclaimed national identity previously suppressed or marginalized. Television evolved dramatically, with the rise of Ukrainian-language programming challenging Russian content's previous dominance, though the comedian who starred in the satirical political series "Servant of the People" later becoming actual president Volodymyr Zelensky represents Ukrainian entertainment's surreal intersection with politics. Music showcases fierce creativity: traditional folk music experiences revival as artists modernize ancient forms; Ukrainian hip-hop, electronic, and indie rock scenes thrived in Kyiv and Lviv; Eurovision became a platform for Ukrainian artists to assert cultural identity internationally, with Kalush Orchestra's 2022 victory carrying profound symbolic weight. Gaming culture was growing significantly before the invasion, with Ukrainian developers creating successful titles and esports communities flourishing. Social media became crucial during the war, with Ukrainian creators, artists, and ordinary citizens documenting resistance, maintaining cultural practices under bombardment, and humanizing Ukrainian identity for international audiences. Ukrainian entertainment's greatest achievement is its persistence—continuing to create, perform, and share culture despite catastrophic circumstances, proving art's essential role in national survival and identity.`
  },
  {
    name: 'Russia',
    summary: `Russian entertainment operates in increasingly isolated circumstances following international sanctions and cultural boycotts sparked by the Ukraine invasion, though the nation's cultural infrastructure and creative talent remain formidable despite mounting constraints. Russian cinema has historically produced powerful work—from Tarkovsky's metaphysical masterpieces through contemporary directors like Andrey Zvyagintsev whose films ("Leviathan," "Loveless") offer bleak, unflinching critiques of Russian society that somehow navigated censorship. Post-2022, international co-productions have evaporated and many prominent directors and actors have fled Russia or been effectively exiled. Television remains state-dominated, with propaganda increasingly displacing quality entertainment programming, though streaming platforms offered some creative breathing room before many withdrew from the Russian market. Music spans enormous range: classical traditions remain world-class; pop music occupies a unique space mixing Western influences with distinctly Russian sentimentality; hip-hop has exploded among youth, though political content risks severe consequences; electronic music scenes in Moscow and St. Petersburg remain vibrant despite isolation. Artists like Little Big achieved viral international success before the war upended everything. Russia's gaming industry was growing impressively, with developers creating globally successful titles and Russian esports competitors dominating certain games, though international tournaments now exclude Russian players. Social media has become a battleground, with state-controlled content competing against independent creators risking prosecution for dissent. Russian entertainment's tragedy is its untapped potential—immense talent, deep cultural traditions, and sophisticated audiences trapped within an increasingly authoritarian state that views independent creativity as threat rather than asset, squandering human and cultural capital that won't easily be recovered.`
  },
  {
    name: 'Turkey',
    summary: `Turkish entertainment has become a genuine global force, particularly in television where Turkish dramas have conquered markets from Latin America to the Middle East, Africa to the Balkans, proving serialized storytelling's universal appeal when executed with production polish and emotional intensity. Turkish dizi (series) like "The Magnificent Century," "Resurrection: Ertuğrul," and countless romantic dramas have made Turkish actors household names across multiple continents, generating hundreds of millions in exports and soft power influence. The formula—lush production values, melodramatic plotting, conservative enough for Middle Eastern markets yet sophisticated enough for European audiences—has proven remarkably effective. Film production showcases greater range, from Nuri Bilge Ceylan's contemplative masterworks that earn Cannes Palme d'Ors to commercial comedies and action films serving domestic audiences. The Istanbul Film Festival maintains international prestige despite occasional government interference. Turkish music spans extraordinary diversity: traditional folk music, Arabesque, Turkish pop, and increasingly hip-hop and electronic music, with artists like Tarkan achieving international recognition while domestic stars maintain massive regional followings. Turkey's geographic position enables musicians to blend European and Middle Eastern influences distinctively. Gaming culture is enormous—Turkey boasts one of the world's largest gaming markets, with passionate esports communities and successful Turkish teams competing internationally. Social media creators leverage Turkey's visual beauty, cuisine, and cultural richness, building massive followings in travel, food, and lifestyle sectors. Turkish entertainment's success demonstrates culture's capacity to transcend political complexities, creating emotional connections across linguistic and cultural boundaries even as Turkey's domestic politics grow increasingly authoritarian and polarizing.`
  },
  {
    name: 'Greece',
    summary: `Greek entertainment operates in the long shadow of ancient glory while navigating modern economic challenges and political turbulence, producing work that alternates between celebrating cultural heritage and grappling with contemporary crises. Greek cinema's "weird wave" of the 2010s, led by directors like Yorgos Lanthimos, Athina Rachel Tsangari, and Panos Koutras, put Greece back on international film maps with deliberately strange, allegorical works that used absurdism to explore Greek society's dysfunctions—though this movement has somewhat dispersed as directors moved to international productions. Mainstream Greek cinema serves domestic audiences with comedies and dramas, while documentaries increasingly reckon with the economic crisis's human costs. Television traditionally centered on soap operas and variety shows, though streaming platforms have begun investing in Greek originals exploring contemporary issues. Music remains vibrantly diverse: rebetiko tradition persists alongside modern laïkó (folk pop); Greek hip-hop has exploded among youth; electronic music scenes in Athens and Thessaloniki connect to broader European club culture; while diaspora artists sometimes achieve international success. The economic crisis decimated cultural funding, forcing Greek artists to operate with minimal resources while producing work about precarity, unemployment, and social breakdown. Gaming culture exists but remains smaller than in wealthier European nations, though Greek developers have created successful indie titles. Social media creators capitalize on Greece's stunning islands, ancient sites, and Mediterranean lifestyle, building travel and lifestyle brands. Greek entertainment's persistent challenge is financial—maintaining cultural production amid economic constraints while competition from better-funded American, British, and Turkish content dominates screens, yet Greek creators persist, driven by stories only they can tell.`
  },
  {
    name: 'Belgium',
    summary: `Belgian entertainment operates under the constant tension of being a small nation divided linguistically yet producing disproportionately excellent work, from Flemish television's dark crime dramas to Walloon cinema's socially conscious narratives. The Dardenne brothers—Jean-Pierre and Luc—remain Belgian cinema's greatest international ambassadors, their morally rigorous social realist films earning multiple Cannes Palme d'Ors while inspiring filmmakers globally. Beyond the Dardennes, Belgian directors like Jaco Van Dormael, Michaël R. Roskam, and Lukas Dhont craft distinctive work that travels internationally despite Belgium's small market. Television splits between Flemish and Francophone production, with Flemish shows like "Clan" and "Tabula Rasa" earning international streaming deals and demonstrating Belgium's facility with taut psychological drama. The country's multilingualism enables Belgian actors and creators to work across European markets seamlessly. Music showcases Belgium's diversity: electronic music from Ghent and Brussels remains influential in European club scenes; Belgian hip-hop exists in both French and Dutch; while indie rock and pop artists occasionally break through internationally, most notably Stromae, whose intelligent electro-pop earned global success. Belgium's music festival scene (Tomorrowland, Rock Werchter) attracts international crowds and performers. Gaming culture thrives, with Belgian game developers creating critically acclaimed titles and esports communities growing. Social media creators often leverage Belgium's architectural beauty, beer culture, and chocolate heritage, though content typically targets either Flemish or Francophone audiences rather than unified Belgian market. Belgian entertainment succeeds through quality and specificity—Belgium may be small and divided, but its creators produce work of such excellence that international audiences happily navigate linguistic and cultural complexities.`
  },
  {
    name: 'Austria',
    summary: `Austrian entertainment operates somewhat in Germany's cultural shadow while producing distinctive work that's often darker, more psychologically complex, and more willing to explore uncomfortable historical legacies. Film directors like Michael Haneke craft brutally rigorous examinations of bourgeois violence and social decay that earn festival prizes while deliberately alienating casual viewers—Austrian cinema often feels like an endurance test, probing psychology's darkest corners with unflinching precision. Directors like Ulrich Seidl push boundaries further still, creating provocative, sometimes shocking works that force confrontation with human behavior's ugliest aspects. Not all Austrian film operates at this intensity—mainstream productions serve German-speaking markets with comedies, romances, and historical dramas, while documentaries often explore Alpine landscapes and environmental themes. Television splits between Austrian productions and German imports, with crime dramas and Alpine-set mysteries popular domestically. Austria's music scene maintains its classical heritage—Vienna remains a classical music capital, with world-class orchestras, opera houses, and concert halls—while contemporary music scenes span from electronic (Vienna's club scene is sophisticated and influential) to indie rock to hip-hop, though Austrian artists often struggle for visibility beyond German-speaking markets. The country's music festivals, from Salzburg Festival's classical focus to Vienna's electronic music events, draw international audiences. Gaming culture exists but remains modest compared to larger nations, though Austrian developers have created successful titles. Social media creators leverage Austria's spectacular Alpine landscapes, architectural heritage, and café culture, building travel and lifestyle content. Austrian entertainment's distinctive quality is its intellectual seriousness—even popular entertainment often carries philosophical weight, psychological complexity, and historical consciousness that distinguishes it from lighter neighboring fare.`
  },
  {
    name: 'Finland',
    summary: `Finnish entertainment embodies the nation's complex character—simultaneously melancholic and humorous, modest and ambitious, fiercely independent yet internationally minded. Film production consistently surprises, from Aki Kaurismäki's deadpan comedies of working-class life (his minimalist style and bone-dry humor influencing filmmakers worldwide) to darker psychological dramas and genre films that embrace Finland's harsh landscapes and long winter nights. Finnish cinema often explores loneliness, alienation, and quiet desperation with visual beauty and understated humanity. Television has evolved significantly, with crime dramas and Nordic noir contributing to the broader Scandinavian television phenomenon, though Finnish shows often embrace darker, stranger elements than their Swedish or Danish counterparts. Music is where Finland truly punches above its weight: the nation produces extraordinary metal, from symphonic metal (Nightwish) to folk metal (Korpiklaani) to countless subgenres, making Finland perhaps the world's most metal nation per capita. Beyond metal, Finnish electronic music, indie rock, and pop have achieved international success, while traditional folk music maintains cultural importance. Finland's gaming industry is disproportionately influential—Rovio (Angry Birds), Remedy Entertainment (Max Payne, Control), and Supercell (Clash of Clans) are Finnish companies that created globally dominant titles and franchises. Esports communities are substantial, with Finnish players competing at the highest levels. Social media creators often explore Finnish culture's peculiarities—saunas, sisu (resilience), the midnight sun, and Finnish introversion—building communities around Nordic lifestyle content. Finnish entertainment succeeds through authenticity and quality, never trying to be something it isn't, creating distinctively Finnish work that resonates precisely because it's so unapologetically itself.`
  }
]

async function main() {
  console.log('🎬 ENTERTAINMENT BATCH 04: Countries 31-40')
  console.log('='.repeat(80))

  const result = await saveEntertainmentSummaries(BATCH_04)

  console.log('\n✅ Batch 04 complete!')
  console.log(`Saved ${result.successCount} summaries to database`)
}

main()
