import { saveEntertainmentSummaries } from './save-entertainment-summaries'

const BATCH_06 = [
  {
    name: 'Netherlands',
    summary: `Dutch entertainment operates with characteristic directness and pragmatism, this small but wealthy nation producing quality work across multiple sectors while maintaining distinctive Dutch sensibilities—liberal, globally minded, often ironic. Film production includes everything from auteur cinema (directors like Paul Verhoeven achieved international success, though he's worked primarily outside Netherlands for decades) to commercial productions and documentaries. Contemporary Dutch directors craft work exploring national identity, colonialism, and multiculturalism as Netherlands grapples with changing demographics and politics. Dutch film funding supports diverse voices, though small domestic markets limit commercial potential. Television has evolved significantly, with Dutch reality TV formats (Big Brother, The Voice) conquering global markets—Netherlands is arguably the world leader in reality TV format creation, selling concepts internationally while maintaining robust domestic production. Streaming platforms have begun investing in Dutch originals including crime dramas and historical series. Music showcases Dutch diversity: electronic dance music is where Netherlands truly dominates globally—Dutch DJs like Tiësto, Armin van Buuren, Martin Garrix, and Afrojack are among the world's biggest, while Amsterdam Dance Event is a crucial industry gathering. Beyond EDM, Dutch hip-hop, rock, and pop serve domestic audiences while occasionally breaking through internationally. Gaming culture is substantial—Netherlands has strict gambling laws that affect loot boxes and microtransactions in games, making Dutch market influential in industry practices. Dutch developers create successful titles, while esports communities thrive. Social media creators leverage Amsterdam's canals, cycling culture, and Dutch directness, often addressing Netherlands' progressive policies, drug tolerance, and social systems. Dutch entertainment succeeds through professionalism and global orientation—English proficiency enables Dutch creators to work internationally while serving domestic audiences with distinctly Dutch content.`
  },
  {
    name: 'Romania',
    summary: `Romanian entertainment, particularly cinema, has achieved remarkable international recognition over the past two decades, the Romanian New Wave producing some of Europe's most critically acclaimed films while navigating post-communist transformation and EU integration. Directors like Cristian Mungiu, Cristi Puiu, and Corneliu Porumboiu craft unflinching, formally rigorous works exploring Romanian society, communist legacy, and contemporary corruption with long takes, minimal scores, and absolute commitment to realism that's earned countless festival prizes including Cannes Palme d'Ors. Romanian cinema's austere aesthetic and moral seriousness stand apart from more commercially minded European productions, creating films that challenge viewers while offering profound insights into Romanian and universal human experiences. Beyond art cinema, Romanian commercial films and television serve domestic audiences with everything from comedies to crime dramas. Television includes both domestic productions and international streaming content, with Romanian shows beginning to appear on global platforms. Music spans traditional folk forms through manele (a controversial Balkan-Roma-Turkish fusion wildly popular domestically despite critical dismissal), rock, electronic, and emerging hip-hop scenes. Romanian musicians often struggle for international visibility beyond Eastern European markets. Gaming culture has grown substantially—Romania has produced successful game developers and maintains passionate esports communities, particularly in Counter-Strike, Dota, and League of Legends, with Romanian players competing at the highest international levels. Social media creators often focus on Romanian Carpathian landscapes, medieval cities, and cultural traditions, building followings among diaspora and curious international audiences. Romanian entertainment's greatest achievement is cinema's critical success despite minimal budgets, proving artistic vision and rigorous craft can produce world-class work regardless of financial constraints, positioning Romania as essential voice in European cinema.`
  },
  {
    name: 'Serbia',
    summary: `Serbian entertainment navigates complex post-Yugoslav reality—simultaneously proud of regional cultural influence, grappling with 1990s conflicts' legacies, and asserting distinctive Serbian identity while maintaining connections to broader Balkan culture. Film production includes internationally recognized directors like Emir Kusturica (whose maximalist, magical-realist style divided critics but built devoted followings) and contemporary filmmakers exploring Serbian history, identity, and contemporary society with varying degrees of confrontation with nationalist narratives. Serbian cinema spans from festival-circuit art films to commercial comedies and action films popular across former Yugoslav territories. The FEST Belgrade Film Festival maintains regional importance. Television produces content that travels across Balkan markets despite political complications, with Serbian shows, particularly crime dramas and historical series, finding audiences in Bosnia, Croatia, and beyond. Music is where Serbia truly influences the region—turbo-folk, that controversial fusion of traditional Balkan music with electronic dance beats, originated largely in Serbia and conquered regional markets despite (or because of) its connections to nationalism and criminal underworlds. Serbian hip-hop, rock, and alternative scenes thrive, while brass band traditions maintain cultural vitality. Exit Festival in Novi Sad has become one of Europe's major music events. Gaming culture is substantial—Serbia has produced world-class esports players particularly in basketball games, shooters, and MOBAs, while game development is emerging. Social media creators often address Serbian culture, humor, and contemporary life, building communities across the diaspora. Serbian entertainment operates in complicated space—balancing Serbian nationalism with Yugoslav nostalgia, regional influence with international aspirations, creating work that reflects these tensions while seeking audiences beyond Serbia's borders.`
  },
  {
    name: 'Switzerland',
    summary: `Swiss entertainment operates across linguistic and cultural divisions—German, French, Italian, and Romansh-speaking regions each maintain distinct cultural productions while Swiss creators navigate relationships with larger neighboring nations sharing their languages. Film production includes internationally recognized directors from various linguistic regions: German-Swiss directors often connect to broader German film industry; French-Swiss filmmakers to French cinema; while Italian-Swiss and Romansh creators work in smaller markets. Swiss documentary filmmaking is particularly strong, exploring Alpine environments, Swiss banking, neutrality, and contemporary social issues with characteristic Swiss precision. Swiss funding supports diverse cinematic voices though fragmentation across language regions limits unified national cinema. Television operates regionally—German-Swiss viewers watch Swiss German and German programming; French-Swiss consume Swiss French and French content, creating multiple parallel entertainment ecosystems within one small nation. Music similarly fragments: German-Swiss scenes connect to German music; French-Swiss to French; while traditional Alpine music maintains cultural importance particularly in conservative regions. Electronic music and jazz scenes in cities like Zürich, Geneva, and Basel connect to international circuits. Gaming culture exists but remains modest, though Swiss precision and tech expertise support growing game development. Esports communities participate in broader German, French, or Italian competitive scenes. Social media creators leverage Switzerland's spectacular Alpine landscapes, banking discretion humor, chocolate, watches, and multilingual absurdities. Swiss entertainment's fundamental challenge is scale—small populations further divided linguistically prevent unified national entertainment industry, forcing Swiss creators to orient toward larger neighboring markets while trying to maintain Swiss distinctiveness, succeeding when they embrace rather than fight against Switzerland's fundamental plurality and complexity.`
  },
  {
    name: 'Slovakia',
    summary: `Slovak entertainment operates in the shadow of its Czech former partner while building distinctive national cultural identity following the Velvet Divorce, creating work that reflects Slovak experiences while navigating limited markets and resources. Film production includes both art-house cinema exploring Slovak identity, history, and contemporary society (directors gradually establishing Slovak cinema separate from Czech traditions) and commercial productions serving domestic audiences. Slovak film funding supports diverse projects though budgets remain limited compared to Western European nations. The country's mountain landscapes and medieval towns provide attractive filming locations for international productions. Television operates across public and private channels, with Slovak shows ranging from comedies to dramas, though Czech programming remains popular given linguistic similarities. Music spans traditional folk forms (maintaining particular importance in Slovak cultural identity) through rock, pop, and emerging hip-hop scenes, with Slovak artists primarily serving domestic and regional markets. Classical music maintains cultural prestige with quality orchestras and performers. Gaming culture has grown significantly—Slovakia has produced successful game developers and maintains passionate esports communities, particularly in Counter-Strike and other first-person shooters. Slovak esports players occasionally compete at international levels. Social media creators often focus on Slovak nature, particularly High Tatras mountains, castles, and cultural traditions, building followings among diaspora communities in Czech Republic, North America, and beyond. Slovak entertainment's challenge is visibility—creating culturally specific work in Slovak language for small domestic market while competing with Czech, Hungarian, and international content, requiring Slovak creators to produce quality work that serves national audiences while occasionally achieving broader regional recognition, gradually establishing Slovak cultural production distinct from Czech while maintaining linguistic and cultural connections.`
  },
  {
    name: 'Lithuania',
    summary: `Lithuanian entertainment reflects the Baltic nation's complex history—centuries of Polish and Russian domination, Soviet occupation, and relatively recent independence creating cultural identity that's simultaneously defensive and confident, traditional and innovative. Film production has gained international recognition through directors exploring Lithuanian history, particularly Holocaust and Soviet experiences, with works earning festival attention for their unflinching historical reckonings and formal ambition. Contemporary filmmakers also craft genre films and commercial productions serving domestic audiences. Lithuanian animation maintains particularly strong tradition, with distinctive visual styles earning international recognition. Television operates across public and private channels, with Lithuanian shows ranging from reality TV to dramas and comedies, though small market size limits production budgets. Music spans traditional folk singing (dainos maintain cultural importance, particularly multi-part sutartinės) through contemporary scenes including rock, electronic, and hip-hop. Lithuanian musicians primarily serve Baltic markets though occasionally achieve broader recognition. The nation's jazz scene maintains surprising vitality. Gaming culture has grown substantially—Lithuanian developers have created successful titles, while esports communities particularly around basketball games (naturally, given Lithuania's basketball obsession) and shooters maintain passionate followings. Social media creators often explore Lithuanian nature, including the Curonian Spit's unique landscapes, medieval Vilnius, and cultural traditions, building communities among substantial Lithuanian diaspora. Lithuanian entertainment navigates interesting tensions between Baltic and Eastern European identities, between preserving traditions and embracing contemporary global culture, between serving small domestic market and seeking international recognition, creating work that's distinctly Lithuanian while engaging with broader European and global cultural conversations, gradually building Lithuanian cultural presence separate from Soviet legacy.`
  },
  {
    name: 'Latvia',
    summary: `Latvian entertainment operates in challenging circumstances—small population, limited resources, and linguistic isolation (Latvian is spoken almost nowhere else) creating obstacles that Latvian creators navigate with determination and creativity. Film production includes both art-house cinema exploring Latvian history and identity (particularly Soviet occupation, independence struggles, and contemporary multiculturalism given Latvia's large Russian-speaking minority) and commercial productions. Latvian directors occasionally achieve international festival recognition, while documentaries often explore the nation's complex relationship between Latvian and Russian communities. Animation maintains particular strength, with Latvian animated films earning international recognition for distinctive visual styles and creative storytelling. Television operates across Latvian and Russian-language channels serving different communities, with domestic productions ranging from reality TV to dramas, though limited budgets constrain production quality compared to Western European standards. Music spans traditional folk song (dainas are fundamental to Latvian cultural identity, with massive song festivals representing national unity) through contemporary rock, electronic, and hip-hop scenes. Latvian musicians primarily serve Baltic markets. The Latvian Song and Dance Festival, held every five years, represents one of the world's largest amateur cultural events. Gaming culture has grown, with Latvian developers creating successful titles and esports communities maintaining passionate followings particularly in Counter-Strike and Dota. Social media creators often focus on Riga's Art Nouveau architecture, Baltic coast, and Latvian cultural traditions, building followings among diaspora communities. Latvian entertainment's fundamental challenge is sustainability—creating quality Latvian-language content for small domestic market while competing with Russian, English, and other foreign content, requiring creativity, efficiency, and cultural commitment to maintain Latvian cultural production in face of market realities.`
  },
  {
    name: 'China',
    summary: `Chinese entertainment operates as simultaneously one of the world's largest industries and one of its most constrained, Communist Party censorship shaping what can be produced, distributed, and consumed while hundreds of millions of viewers, gamers, and music fans create massive markets that global entertainment companies desperately want to access. Film production is enormous—China is the world's largest film market, producing everything from propaganda celebrating Party achievements and nationalist historical epics to commercial blockbusters, romantic comedies, and genre films that navigate censorship restrictions. Directors like Zhang Yimou and Jia Zhangke craft visually stunning works exploring Chinese society within permissible boundaries, while action directors deliver spectacular martial arts films and CGI-heavy blockbusters. Censorship prevents politically sensitive topics, ghosts, time travel (without proper justification), and countless other restrictions. Television produces massive quantities of content from historical costume dramas to contemporary romances, reality shows to variety programs, all subject to strict content controls. Streaming platforms like iQiyi and Tencent Video compete with short-video apps like Douyin (Chinese TikTok) for audience attention. Music spans from Mandopop and Cantopop to hip-hop, rock, and electronic scenes, all navigating censorship that's intensified recently. Gaming is where China truly dominates globally—Chinese companies like Tencent own or invest in countless international gaming companies, while Chinese-developed mobile games generate billions, and Chinese esports players and teams dominate multiple competitive scenes. Yet gaming faces strict time limits for minors and content restrictions. Social media creators thrive on platforms like Weibo, Douyin, and Bilibili, building massive followings while carefully avoiding political redlines. Chinese entertainment's tragedy and triumph is its scale—enormous creative energy and massive markets constrained by authoritarian controls that prevent Chinese culture from achieving the global influence its population and resources suggest should be possible.`
  },
  {
    name: 'India',
    summary: `Indian entertainment operates at staggering scale—Bollywood alone produces more films annually than Hollywood, while regional film industries in Tamil, Telugu, Malayalam, Bengali, and other languages create vast quantities of content serving India's linguistic diversity. Hindi cinema, commonly called Bollywood, creates everything from romantic musicals to action spectacles, increasingly sophisticated dramas to comedy blockbusters, with stars achieving deity-like status and films often running three hours with elaborate song-and-dance sequences. Regional cinemas maintain distinct identities—Telugu cinema (Tollywood) produces massive action spectacles; Malayalam cinema crafts more realistic social dramas; Tamil cinema blends commercial appeal with political messaging. Recent films like "RRR" and "Baahubali" demonstrated Indian cinema's global appeal when executed with sufficient spectacle. Streaming platforms have revolutionized content, producing shows that explore contemporary Indian society with unprecedented frankness about sex, politics, and social issues. Music industry is enormous—film music dominates, but independent artists increasingly find audiences through streaming; classical traditions maintain vitality; while contemporary artists blend Indian instruments and sensibilities with global genres. India's gaming market is exploding—mobile gaming particularly, with hundreds of millions playing PUBG Mobile (in its Indian form), Free Fire, and countless other titles. Esports is growing rapidly. Social media usage is massive, with Indian creators building global followings particularly in comedy, music, and dance content—TikTok was enormous before its ban, with audiences migrating to Instagram Reels and YouTube Shorts. Indian entertainment succeeds through scale, diversity, and increasing quality—serving domestic markets while gradually building international presence as production values improve and streaming enables global distribution.`
  },
  {
    name: 'Japan',
    summary: `Japanese entertainment is a global cultural force of extraordinary influence—from anime and manga that shape international pop culture to video games that defined entire genres, from J-pop idol culture to auteur cinema that influenced filmmakers worldwide. Film industry spans from masters like Kurosawa and Ozu whose legacies remain towering through contemporary directors like Hirokazu Kore-eda crafting intimate family dramas and Takashi Miike's prolific genre-hopping, plus massive anime film productions from Studio Ghibli (whose works compete for beauty and emotional depth with any cinema globally) to countless other studios. Television produces everything from elaborate variety shows to high-quality dramas, anime series that build global fandoms, and reality shows that blend sincerity and absurdity distinctively. Streaming platforms invest heavily in Japanese content recognizing its international appeal. Music is extraordinarily diverse—J-pop idol groups maintain massive domestic followings; J-rock spans from heavy metal to alternative; electronic music producers innovate constantly; while traditional music forms maintain cultural importance. Japanese gaming industry is legendary—Nintendo, PlayStation, countless iconic franchises from Mario to Pokémon to Final Fantasy to Dark Souls—Japanese developers fundamentally shaped global gaming culture. Esports grows despite some cultural resistance, with fighting game communities particularly strong. Social media in Japan operates somewhat distinctly—LINE dominates messaging, Twitter remains massive, while YouTube and TikTok host enormous Japanese creator communities. Manga and light novels generate endless adaptations across media. Japanese entertainment's influence is so pervasive it's almost invisible—anime aesthetics, gaming conventions, storytelling structures, and cultural concepts have been absorbed globally, making Japanese pop culture fundamental to contemporary global entertainment landscape in ways that exceed even America's influence in certain sectors and demographics.`
  }
]

async function main() {
  console.log('🎬 ENTERTAINMENT BATCH 06: Countries 51-60')
  console.log('='.repeat(80))

  const result = await saveEntertainmentSummaries(BATCH_06)

  console.log('\n✅ Batch 06 complete!')
  console.log(`Saved ${result.successCount} summaries to database`)
}

main()
