import { saveEntertainmentSummaries } from './save-entertainment-summaries'

const BATCH_08 = [
  {
    name: 'Palestine',
    summary: `Palestinian entertainment exists as act of cultural resistance and survival, creating and preserving identity under Israeli occupation, restricted movement, economic constraints, and periodic violence that devastate infrastructure and kill artists. Film has become Palestine's most internationally visible cultural form—directors like Elia Suleiman, Hany Abu-Assad, and younger filmmakers craft works exploring occupation, displacement, and Palestinian life with dark humor, visual poetry, and unflinching documentation. Palestinian cinema gains festival recognition and Oscar nominations, serving crucial role in humanizing Palestinian experiences for international audiences while providing Palestinians themselves with representations beyond victim narratives. Documentary filmmaking particularly thrives, recording daily realities of checkpoints, settlements, and resistance. Television production faces enormous challenges—limited infrastructure, electricity problems, funding constraints—yet Palestinian productions including dramas and comedies serve audiences in West Bank, Gaza, and diaspora. Music maintains cultural vitality across genres: traditional Palestinian folk music preserves heritage; contemporary artists blend Arabic and Western influences; hip-hop artists like DAM use music for political commentary and social criticism; while dabke traditional dance remains culturally central. Gaming and esports face infrastructure limitations—internet restrictions, electricity problems, movement constraints—yet young Palestinians game when possible. Social media has become crucial platform for Palestinians documenting their experiences, building international solidarity, and maintaining cultural expression despite attempts to censor or silence Palestinian voices online. Palestinian entertainment's fundamental achievement is its existence and persistence—creating culture despite occupation designed to eliminate Palestinian identity, preserving traditions while expressing contemporary experiences, refusing cultural erasure through determination to continue producing Palestinian art regardless of circumstances.`
  },
  {
    name: 'Iraq',
    summary: `Iraqi entertainment struggles to rebuild after decades of devastating wars, sanctions, occupation, and sectarian violence that destroyed infrastructure and scattered artistic communities while fundamentalist groups attacked cultural expression. Historically, Iraq was Arab world's cultural powerhouse—Baghdad produced influential music, cinema, and literature before descending into catastrophe. Contemporary efforts to revive Iraqi entertainment face enormous challenges: security threats, political instability, economic crisis, brain drain as artists fled abroad, and competing visions about appropriate cultural expression in Islamic society. Film production has attempted revival, with some Iraqi directors producing works exploring war trauma, sectarian violence, and occupation's legacies, though funding and security constraints limit output. Documentaries record Iraq's ongoing struggles while feature films attempt to establish post-Saddam Iraqi cinema. Television produces content ranging from religious programming to dramas and reality shows, with Iraqi shows competing with Turkish, Egyptian, and other Arab programming. Music remains culturally vital despite attacks on musicians during ISIS occupation—traditional maqam singing, contemporary pop blending Iraqi and broader Arab styles, and underground rock and metal scenes demonstrate Iraqi musical persistence. Gaming culture exists primarily in internet cafés where young Iraqis escape brutal reality through FIFA, Call of Duty, and mobile games. Esports communities are emerging slowly. Social media provides platform for Iraqi creators to document daily life, share music and comedy, and build communities despite ongoing instability. Iraqi entertainment's tragedy is its enormous unrealized potential—rich cultural heritage, talented artists, and engaged audiences trapped in cycles of violence and instability that prevent cultural production from flourishing, with Iraqi creativity surviving despite catastrophic circumstances but unable to thrive until stability returns.`
  },
  {
    name: 'Jordan',
    summary: `Jordanian entertainment operates as regional cultural hub benefiting from relative stability compared to neighboring conflicts while navigating conservative social values and limited domestic market that pushes Jordanian creators toward broader Arab audiences. Film production includes both Jordanian works exploring national identity, Bedouin heritage, and contemporary social issues, plus Jordan serving as filming location for international productions attracted by dramatic desert landscapes (including "Lawrence of Arabia," "The Martian," and countless others) providing industry infrastructure and expertise. Jordanian directors contribute to Arab cinema while occasionally earning international festival attention. Television production serves broader Arab markets—Jordanian shows including dramas and comedies travel regionally, while production companies create content for pan-Arab networks and streaming platforms. Jordan's capital Amman has become production center for regional entertainment industry. Music blends traditional Bedouin forms with contemporary Arabic pop, with Jordanian artists achieving varying levels of regional success. Jordan's music scene is less dominated by religious conservatism than some neighbors, enabling more artistic freedom. Gaming culture has grown substantially among Jordanian youth, with internet cafés popular and mobile gaming widespread. Esports communities are developing, with Jordanian teams beginning to compete regionally. Social media creators leverage Jordan's ancient sites (Petra, Wadi Rum) and relative openness compared to more restrictive neighbors, building travel and lifestyle brands while younger creators produce comedy and cultural content. Jordanian entertainment's advantage is stability—while not wealthy like Gulf states, Jordan's consistent governance and moderate social environment enable cultural production to develop steadily, serving as regional hub where Arab creators can work with greater freedom than in more restrictive or unstable nations.`
  },
  {
    name: 'Cambodia',
    summary: `Cambodian entertainment is slowly rebuilding from near-total cultural genocide—the Khmer Rouge systematically murdered musicians, actors, dancers, and artists during their 1975-79 reign of terror, obliterating Cambodia's vibrant pre-war entertainment industry and leaving traumatic void that continues affecting Cambodian culture. The country's golden age of 1960s film and music was destroyed, with most films lost and artists killed, creating cultural rupture that younger generations are working to bridge. Contemporary film industry remains modest, with Cambodian directors producing works that explore Khmer Rouge legacy, rural poverty, and contemporary social issues while international co-productions enable higher production values. Davy Chou and Rithy Panh create powerful documentaries and fiction films engaging with traumatic history. Television produces content primarily for domestic audiences—soap operas, variety shows, and news programming competing with Thai and other regional content. Music has experienced revival, with researchers recovering and preserving 1960s recordings while contemporary artists blend traditional Khmer music with modern genres. Rock, pop, and hip-hop scenes exist alongside classical Khmer music and Apsara dance that maintain cultural heritage. Gaming culture has grown among urban youth with smartphone proliferation, mobile gaming being most accessible form. Social media creators build followings particularly around Angkor Wat tourism, Khmer food culture, and contemporary Cambodian life, with platforms enabling cultural expression and entrepreneurship. Cambodian entertainment's challenge is limited resources—Cambodia remains poor with minimal cultural infrastructure, yet Cambodian artists persist in reviving traditions, creating contemporary culture, and healing the traumatic rupture through cultural production that honors the murdered artists while building Cambodia's creative future.`
  },
  {
    name: 'Laos',
    summary: `Lao entertainment operates on minimal scale befitting one of Southeast Asia's poorest and most isolated nations, communist government control constraining cultural production while limited resources and small population restrict industry development. Film production is extremely limited—Laos produces few films, mainly documentaries or modest dramas exploring rural life and development challenges, with occasional international co-productions enabling higher quality work. The country's stunning natural beauty attracts some international filming. Television broadcasts government-controlled content including news, educational programming, and limited entertainment shows, though Lao audiences widely consume Thai television given linguistic similarities and Thailand's vastly superior production values. Music maintains traditional forms alongside contemporary Lao pop influenced heavily by Thai music, with mor lam traditional singing remaining culturally important particularly in rural areas. Lao rock and contemporary musicians exist but face limited domestic markets and infrastructure. Gaming culture is growing slowly—internet access remains limited outside cities, but mobile gaming has found audiences among urban youth. Gaming cafés exist in Vientiane and other cities. Social media usage has increased with smartphone adoption, with Lao creators producing content around Lao culture, food, and Buddhist traditions, though Thai and Vietnamese social media content often dominates among Lao youth. Esports exists at minimal scale. Lao entertainment faces fundamental challenges of poverty, limited infrastructure, communist controls on expression, and competition from better-resourced Thai content, creating entertainment landscape that's culturally thin compared to neighbors. Yet Lao culture persists through traditional music, Buddhist festivals, and cultural practices maintained despite modernization pressures and entertainment industry's underdevelopment.`
  },
  {
    name: 'Myanmar',
    summary: `Myanmar entertainment has experienced catastrophic collapse following the February 2021 military coup, decades of gradual opening and cultural development destroyed as the junta cracks down on artistic expression, arrests entertainers supporting democracy, and imposes censorship while civil war devastates the nation. Before the coup, Myanmar's entertainment industry was experiencing revival after decades of military dictatorship—film production created works exploring Burmese identity and history; television produced dramas, variety shows, and news programming; music scenes spanning traditional Burmese instruments through contemporary pop, hip-hop, and rock were flourishing. Yangon hosted film festivals and music concerts introducing international culture. Social media had exploded in Myanmar as internet access expanded, with Myanmar social media users among the world's most active, creating content across platforms. Post-coup, many entertainers fled Myanmar or were arrested for supporting democracy protests—musicians, actors, and creators forced into exile or underground. The junta censors content strictly while pro-democracy artists produce work from hiding or abroad. Some traditional culture continues under junta oversight, but contemporary creative expression faces severe restrictions. Gaming culture existed primarily in urban centers but has been disrupted by conflict and internet shutdowns the junta uses to control information. The entertainment industry that was tentatively developing during Myanmar's democratic opening has largely collapsed or gone underground. Myanmar entertainment's tragedy mirrors Afghanistan's—brief flowering of cultural freedom destroyed by authoritarian takeover, with Myanmar's creative community scattered, imprisoned, or silenced, creating void that may take generations to fill if democracy ever returns.`
  },
  {
    name: 'Nepal',
    summary: `Nepali entertainment operates with limited resources yet considerable cultural vitality, this Himalayan nation producing films, music, and content that serve domestic audiences and vast Nepali diaspora while navigating economic constraints and competition from Indian entertainment industry. Film industry, known as Kollywood, produces works primarily in Nepali language exploring Nepali identity, mountain life, migration, and contemporary social issues, though production values and budgets can't compete with Bollywood productions that dominate Nepali screens. Occasional Nepali films achieve critical recognition or commercial success domestically. Television produces content from news programming to dramas, reality shows to music competitions, serving Nepali audiences at home and across substantial diaspora in India, Middle East, and beyond. Music is culturally vital—traditional folk music from various ethnic groups maintains importance; modern Nepali pop blends Nepali and Indian influences; while rock, metal, and hip-hop scenes exist particularly in Kathmandu. Nepali musicians often struggle with limited domestic market size and competition from Bollywood music. Gaming culture exists primarily in urban centers, with gaming cafés popular among young people and mobile gaming growing with smartphone adoption. Esports communities are emerging slowly. Social media has become crucial platform for Nepali creators producing comedy, music, cultural content, and lifestyle material, with platforms enabling diaspora connections and cultural preservation. Mount Everest and Himalayan content generates international interest. Nepali entertainment's challenge is resources—creating quality content with minimal budgets while competing with superior-funded Indian productions, succeeding when focusing on distinctly Nepali stories and cultural specificity that resonates with Nepali audiences even if international recognition remains limited.`
  },
  {
    name: 'Mongolia',
    summary: `Mongolian entertainment reflects the nation's unique position between Russia and China, vast landscapes, nomadic heritage, and post-communist transformation creating cultural landscape that's simultaneously traditional and rapidly modernizing. Film production includes works exploring Mongolian history (particularly Genghis Khan legacy), nomadic traditions, and contemporary urban versus rural tensions, with Mongolian directors occasionally earning international festival recognition for visually stunning works showcasing Mongolia's dramatic steppes and deserts. Documentary filmmaking particularly leverages Mongolia's distinctive culture and landscapes. Television produces content from news to entertainment programming, with Mongolian shows competing with Russian, Chinese, and Korean content. Music showcases Mongolia's extraordinary throat singing traditions (khoomei) which have achieved international recognition as one of the world's most distinctive musical forms, while contemporary Mongolian rock bands blend traditional instruments like the morin khuur (horsehead fiddle) with modern sounds creating unique fusion. Mongolian hip-hop and pop serve domestic audiences. Gaming culture is substantial particularly in capital Ulaanbaatar, with Mongolian gamers passionate about MOBAs, shooters, and strategy games. Mongolia has produced competitive esports players despite small population. Social media creators leverage Mongolia's stunning landscapes, nomadic culture, and throat singing traditions, building international followings fascinated by Mongolian uniqueness. Naadam Festival and eagle hunting provide spectacular content. Mongolian entertainment succeeds when embracing Mongolia's distinctiveness—throat singing, nomadic heritage, dramatic landscapes—creating culturally specific work that interests international audiences precisely because it's so different from entertainment produced elsewhere, while serving Mongolian audiences with content reflecting their own experiences navigating tradition and modernity.`
  },
  {
    name: 'Papua New Guinea',
    summary: `Papua New Guinea's entertainment landscape reflects the nation's extraordinary diversity—over 800 languages spoken across difficult terrain creating fragmented media environment where national cultural production struggles to emerge cohesively. Film production is minimal—occasional documentaries explore PNG's cultures, environments, and social challenges, while feature film production barely exists due to funding constraints and infrastructure limitations. The country's cultural diversity and natural environments occasionally attract international documentary filmmakers. Television broadcasting exists through state and private channels, but electricity access remains limited outside cities, constraining audience reach. Radio is more culturally significant given infrastructure limitations. Music maintains enormous diversity reflecting the hundreds of distinct cultural groups—traditional music forms vary dramatically across regions, while contemporary PNG musicians create string band music (a distinctive local style), reggae, and gospel music popular particularly in urban areas. Urban music scenes in Port Moresby incorporate international genres. Gaming culture exists primarily among urban youth with electricity and internet access, which excludes much of the population. Mobile gaming is growing as phone networks expand. Social media adoption is increasing but remains limited by infrastructure and costs, with PNG creators producing content around music, culture, and contemporary life for domestic and diaspora audiences. PNG's entertainment industry faces fundamental development challenges—geographic fragmentation making unified national media difficult, linguistic diversity preventing single-language content from reaching majority of population, poverty and infrastructure constraints limiting production capabilities, and competition from Australian and other international content. PNG's cultural richness remains largely unexpressed in modern entertainment formats, with traditional cultural practices maintaining vitality even as contemporary entertainment industry remains underdeveloped.`
  },
  {
    name: 'Fiji',
    summary: `Fijian entertainment operates on modest scale befitting a small Pacific island nation, creating content primarily for domestic consumption while navigating ethnic divisions between indigenous Fijians and Indo-Fijians, limited resources, and competition from Australian, New Zealand, and Bollywood productions. Film production is minimal—occasional documentaries and feature films explore Fijian culture, natural environment, and social issues, while Fiji occasionally serves as filming location for international productions attracted by tropical beauty. Television broadcasts mix of local news, sports (rugby being national obsession), and entertainment programming alongside imported content from Australia, New Zealand, India, and US. Music reflects Fiji's cultural diversity: indigenous Fijian music incorporating traditional instruments and vocal styles, Indo-Fijian music influenced by Bollywood and Indian classical traditions, reggae and island pop blending various influences, while contemporary Fijian artists create music spanning genres. Fijian musicians achieve occasional regional success in Pacific markets. Gaming culture exists primarily in urban centers, with internet cafés and mobile gaming popular among youth. Social media creators leverage Fiji's stunning beaches, coral reefs, and island culture, building tourism-oriented content and diaspora connections. Rugby content generates substantial engagement given the sport's cultural importance. Fijian entertainment's challenge is scale—tiny population and limited resources constrain industry development while competition from larger nations dominates screens, yet Fijian culture persists through traditional practices, contemporary music, and cultural content that serves Fijian audiences and substantial diaspora in Australia, New Zealand, and North America, maintaining cultural connections across Pacific distances.`
  }
]

async function main() {
  console.log('🎬 ENTERTAINMENT BATCH 08: Countries 71-80')
  console.log('='.repeat(80))

  const result = await saveEntertainmentSummaries(BATCH_08)

  console.log('\n✅ Batch 08 complete!')
  console.log(`Saved ${result.successCount} summaries to database`)
}

main()
