import { saveEntertainmentSummaries } from './save-entertainment-summaries'

const BATCH_05 = [
  {
    name: 'Denmark',
    summary: `Danish entertainment projects an influence wildly disproportionate to the nation's modest population, from Dogme 95's revolutionary cinema movement to contemporary television that's conquered international streaming platforms. Danish film remains exceptional—Lars von Trier continues provoking and dividing audiences with formally ambitious, psychologically brutal works; Thomas Vinterberg crafts powerful dramas like "The Hunt" and "Another Round" that explore masculinity, community, and human frailty; while genre filmmakers and documentarians maintain high standards. Danish cinema's commitment to risk-taking and artistic integrity, supported by robust funding structures, enables filmmakers to pursue visions that might seem uncommercial yet often find international audiences. Television has become Denmark's most successful entertainment export—"The Killing," "Borgen," and "The Bridge" launched the Nordic noir phenomenon that transformed global television, proving subtitled shows could achieve mainstream success in English-speaking markets. These productions' moral ambiguity, complex characterization, and visual atmospherics influenced countless imitators. Music spans from avant-garde electronic experimentation to mainstream pop, though Danish artists often struggle for international visibility beyond Scandinavian markets—exceptions like Lukas Graham and MØ prove Danish pop can travel, while underground electronic and metal scenes remain influential in European circuits. Denmark's gaming industry contributes significantly to the global market, with developers creating innovative titles, while esports communities grow steadily. Social media creators leverage hygge culture, Scandinavian design aesthetics, and Danish lifestyle content, building followings among audiences seeking Nordic minimalism and coziness. Danish entertainment succeeds through confidence in Danish stories told with uncompromising quality—trusting that specificity breeds universality, that local authenticity resonates globally when executed with sufficient craft and vision.`
  },
  {
    name: 'Ireland',
    summary: `Irish entertainment operates with characteristic wit, melancholy, and literary sophistication, punching far above the island's population while navigating complex relationships with British culture and American diaspora. Film production has flourished in recent decades—from Neil Jordan's poetic narratives through contemporary directors like Lenny Abrahamson, John Crowley, and Lorcan Finnegan who craft everything from intimate character studies to mind-bending genre films. Irish actors dominate international screens (Saoirse Ronan, Colin Farrell, Cillian Murphy, Ruth Negga) often while maintaining careers in Irish productions and theater. The film industry benefits from tax incentives that attract international productions while supporting indigenous work. Television has evolved from small-scale domestic productions to streaming-era originals like "Normal People" and "Bad Sisters" that achieve global success, proving Irish stories with Irish sensibilities can captivate international audiences. Music remains gloriously diverse: traditional Irish music maintains vitality through artists who honor and innovate upon ancient forms; rock and indie scenes have produced internationally successful acts from U2 through The Cranberries to contemporary bands; Irish hip-hop is emerging; while electronic and alternative scenes thrive in Dublin and beyond. Ireland's literary culture infuses much entertainment with linguistic playfulness and narrative sophistication. Gaming culture has grown significantly, with Irish developers creating successful titles and esports communities expanding. Social media creators often explore Irish identity, landscape, humor, and culture, building communities particularly among the vast global diaspora hungry for connections to heritage. Irish entertainment's distinctive quality is its embrace of contradiction—brutal history and wry humor, deep melancholy and infectious joy, intimate scale and epic ambition—creating work that feels authentically Irish yet speaks to universal human experiences.`
  },
  {
    name: 'Hungary',
    summary: `Hungarian entertainment navigates increasingly authoritarian political conditions while maintaining creative traditions dating back to the nation's remarkable cinematic legacy and cultural sophistication. Film has historically been Hungary's cultural crown jewel—from the Hungarian New Wave through contemporary directors like László Nemes (whose "Son of Saul" earned an Oscar) and Kornél Mundruczó who craft formally ambitious, often historically engaged works that earn international festival attention. However, government consolidation of film funding and media has created challenges for filmmakers whose work doesn't align with nationalist narratives, forcing some artists abroad while others navigate careful political tightropes. Mainstream Hungarian cinema serves domestic audiences with comedies, romances, and historical epics, often celebrating Magyar identity. Television has split between state-controlled channels promoting government messages and international streaming platforms beginning to invest in Hungarian originals that explore the country's complex contemporary society. Music spans traditional folk forms (experiencing revival among nationalist movements and progressive innovators alike) through vibrant electronic music scenes in Budapest's famous ruin bars and clubs, with Hungarian DJs and producers influential in European dance music. Hip-hop has grown among Hungarian youth, while classical music maintains its historical importance. Gaming culture is substantial—Hungary has produced successful game developers and maintains strong esports communities, particularly in League of Legends and Counter-Strike. Social media creators often focus on Budapest's unique architecture, thermal baths, and food culture, though political content navigates careful paths. Hungarian entertainment's greatest challenge is maintaining creative freedom and artistic integrity amid political pressures while serving audiences hungry for both escapism and honest engagement with Hungarian reality.`
  },
  {
    name: 'Czech Republic',
    summary: `Czech entertainment maintains the nation's tradition of sophisticated cultural production mixed with absurdist humor and healthy skepticism of authority, creating work that's simultaneously intellectually serious and genuinely entertaining. Film continues the legacy of Czech New Wave masters, with contemporary directors like Jan Švěrák crafting Oscar-winning dramas while others produce everything from historical epics to genre films and animated works. Prague's architectural beauty and relatively low production costs make it a favored filming location for international productions, supporting local film infrastructure. Czech television operates across public and private channels, with domestic productions ranging from crime dramas to sketch comedies that reference Czech absurdist traditions, though international streaming platforms are beginning to invest in Czech originals. The country's animation tradition, both stop-motion and computer-generated, maintains international recognition for technical excellence and creative storytelling. Music showcases Czech diversity: classical music heritage remains strong with world-class orchestras and composers; rock and alternative scenes have thrived since Velvet Revolution, with Czech bands maintaining devoted followings; electronic music scenes in Prague remain influential; while folk music maintains cultural importance. Czech hip-hop and metal scenes cater to dedicated audiences. Gaming culture is substantial—Czech developers have created globally successful titles including the "Kingdom Come: Deliverance" medieval RPG, while esports communities particularly around first-person shooters and MOBAs continue growing. Social media creators leverage Czech Republic's stunning architecture, beer culture, and Central European position. Czech entertainment succeeds through intelligence leavened with humor, creating work that respects audience sophistication while delivering entertainment value, maintaining the Czech tradition of using culture as subtle resistance against conformity and pomposity.`
  },
  {
    name: 'Bulgaria',
    summary: `Bulgarian entertainment operates somewhat under international radar despite producing quality work across multiple sectors, navigating post-communist transformation and European integration while maintaining distinctive cultural identity. Film production includes art-house cinema that occasionally earns festival recognition (directors like Theodor Ushev and Ralitza Petrova crafting visually striking, thematically challenging works) alongside commercial productions serving domestic audiences. Bulgaria's film industry also supports international productions attracted by low costs and diverse locations, providing employment for local crews while developing infrastructure. Television has evolved from state broadcaster dominance to include private channels and increasingly streaming content, with Bulgarian shows ranging from reality TV to crime dramas and historical series exploring the country's complex past. Music spans traditional folk (chalga, a controversial folk-pop fusion, remains hugely popular domestically despite critical disdain), through thriving rock and metal scenes, to electronic music producers contributing to European dance music. Bulgarian musicians often struggle for international visibility beyond Balkan and Eastern European markets. Gaming culture has grown significantly, with Bulgarian developers creating successful titles and esports communities particularly around Counter-Strike and Dota maintaining passionate followings. Bulgaria has produced world-class esports players who compete internationally. Social media creators often focus on Bulgarian nature, Black Sea coast, mountains, and cultural traditions, building followings among diaspora communities. Bulgarian entertainment's challenge is visibility—creating quality content that navigates linguistic barriers (Bulgarian uses Cyrillic, limiting casual international accessibility) while serving domestic audiences with culturally specific material that may not translate easily, yet Bulgarian creators persist, building audiences gradually through quality and authenticity.`
  },
  {
    name: 'Croatia',
    summary: `Croatian entertainment has evolved significantly since independence, building cultural infrastructure while navigating complicated regional relationships and establishing distinctive national identity separate from Yugoslav legacy. Film production showcases diversity from festival-circuit art films exploring Croatian history and identity (directors like Dalibor Matanić and Zvonimir Jurić crafting intimate character studies and historical reckonings) to commercial productions and genre films. The Pula Film Festival maintains tradition as the region's oldest film festival, though Croatian cinema struggles with limited funding and small domestic markets. Television includes domestic productions ranging from crime dramas to comedies, with some Croatian shows beginning to appear on streaming platforms, while the country's stunning Adriatic coast provides filming locations for international productions including "Game of Thrones," bringing revenue and exposure. Music spans traditional klapa singing (multi-part a cappella that's distinctly Dalmatian) through Slavic pop, rock, and emerging hip-hop scenes. Croatian artists occasionally achieve regional success across former Yugoslav territories despite political complications, while electronic music festivals along the coast have built international reputations. Gaming culture has grown substantially, with Croatian esports players competing internationally and game development beginning to establish foothold. Social media creators capitalize on Croatia's spectacular coastline, ancient cities, and natural parks, building massive travel and lifestyle followings that have contributed to Croatia's tourism explosion. Croatian entertainment navigates complex identity questions—balancing European orientation with Balkan heritage, Mediterranean culture with Slavic traditions, Yugoslav nostalgia with Croatian nationalism—creating work that reflects these tensions while striving for broader international relevance beyond the complicated regional dynamics.`
  },
  {
    name: 'Estonia',
    summary: `Estonian entertainment operates with characteristic Nordic efficiency and digital sophistication, this tiny Baltic nation punching above its weight through quality over quantity and leveraging technological prowess into cultural production. Film remains Estonia's strongest cultural export—from Andrus Kivirähk's darkly comic takes on Estonian history and mythology to documentary filmmakers exploring post-Soviet identity, Estonian cinema crafts distinctive work often blending naturalism with magical realism in ways that feel uniquely Baltic. Animation particularly excels, with Estonian stop-motion and experimental animation earning international recognition for technical virtuosity and creative storytelling. The Tallinn Black Nights Film Festival has grown into one of Northern Europe's major film events. Television operates on limited budgets but maintains quality, with Estonian crime dramas and comedies serving domestic audiences while occasionally traveling to other Nordic and Baltic markets. Music showcases Estonian diversity: the nation's choral tradition remains exceptionally strong (Estonia arguably cares more about choral music than any nation on Earth); contemporary composers create innovative classical and experimental electronic music; indie rock and alternative scenes thrive in Tallinn despite small audiences; while Estonian hip-hop and electronic music draw from both Nordic and Eastern European influences. The annual Song Festival represents Estonian cultural identity powerfully—massive choral events that historically played crucial roles in national independence movements. Gaming culture is substantial for Estonia's size, with the nation's digital infrastructure and tech-savvy population producing game developers and esports competitors. Social media creators leverage Estonia's medieval architecture, digital society, and Nordic-Baltic culture. Estonian entertainment succeeds through distinctiveness and quality—Estonia may be small, but its cultural output is unmistakably Estonian, creating work that doesn't try to be something it isn't.`
  },
  {
    name: 'Norway',
    summary: `Norwegian entertainment benefits from oil wealth that funds cultural production at levels most nations can't match, enabling risk-taking and quality that's positioned Norway as a significant Nordic cultural force. Film production spans from international breakthroughs like Joachim Trier's Oslo trilogy (intimate character studies of young Norwegian lives) to commercial successes including the "Troll Hunter" mockumentary and disaster films that leverage Norway's dramatic landscapes, while documentaries often explore environmental themes and Arctic regions. Norwegian cinema maintains distinctive voice—often quieter and more contemplative than Danish or Swedish productions, with particular attention to landscape's psychological dimensions. Television has contributed significantly to Nordic noir with shows like "Occupied" and "Beforeigners" blending genre elements with social commentary, while lighter fare like "Skam" achieved unexpected international cult success, particularly among teenagers worldwide who connected with its raw, authentic portrayal of adolescence. Music showcases Norwegian creativity: black metal scenes in the 1990s achieved notorious international recognition; contemporary pop artists like Aurora and Sigrid craft ethereal, emotionally intelligent music; electronic music producers and indie rock bands maintain devoted followings; while traditional folk music, particularly Sami joik singing, maintains cultural importance. Norway's jazz scene is surprisingly influential internationally. Gaming culture thrives—Norwegian developers have created critically acclaimed titles, while esports communities particularly around winter sports games and shooters maintain passionate engagement. Social media creators leverage Norway's spectacular fjords, northern lights, and outdoor culture, building massive travel and lifestyle followings. Norwegian entertainment reflects the nation's comfortable prosperity while grappling with questions of meaning, identity, and purpose in one of the world's wealthiest, most comfortable societies.`
  },
  {
    name: 'Sweden',
    summary: `Swedish entertainment maintains remarkable global influence for a nation of ten million, from ABBA's enduring pop dominance through crime novels that conquered international bestseller lists to streaming shows that prove Swedish stories travel universally. Film production balances art-house cinema (from Ingmar Bergman's towering legacy through contemporary auteurs like Ruben Östlund, whose class-conscious provocations earn Cannes Palme d'Ors) with genre films and commercial productions. Swedish directors, cinematographers, and actors work internationally while maintaining connections to Swedish film industry. Television has experienced extraordinary international success—shows like "The Bridge" helped launch Nordic noir globally, while recent series demonstrate Swedish television's range from crime dramas to comedies to science fiction. Music is where Sweden truly dominates: beyond performing artists, Swedish songwriters and producers (Max Martin, Shellback, Bloodshy & Avant) have crafted countless global pop hits for international superstars, making Stockholm an unexpected pop music capital. Swedish artists from Robyn to The Cardigans to First Aid Kit to Swedish House Mafia demonstrate the nation's musical range, while death metal scenes remain influential in heavy music. Gaming culture is massive—Sweden produced Minecraft, arguably the most influential game of the century, plus Battlefield, Candy Crush, and countless other successful titles, making Sweden a gaming superpower. Esports infrastructure and competitions are well-established. Social media creators leverage Swedish design aesthetics, lifestyle, and lagom philosophy (not too much, not too little), building global audiences for Swedish minimalism and sustainable living. Swedish entertainment succeeds through professionalism, quality, and understanding that universal stories require specific, authentic cultural grounding rather than bland internationalism.`
  },
  {
    name: 'Portugal',
    summary: `Portuguese entertainment operates somewhat in Spain's shadow while producing distinctive work that reflects Portugal's unique position as Atlantic-facing, post-colonial, and culturally complex. Film has experienced a remarkable renaissance—directors like Miguel Gomes, Pedro Costa, and João Pedro Rodrigues craft formally ambitious, often challenging works that earn festival acclaim and position contemporary Portuguese cinema among Europe's most adventurous. These films often explore Portuguese history, colonialism, and identity with visual beauty and narrative complexity that demands patient, engaged viewing. More commercial Portuguese cinema serves domestic audiences with comedies and dramas. Television has evolved significantly, with Portuguese-language productions traveling to Brazilian markets and Lusophone Africa, while streaming platforms are beginning to invest in Portuguese originals. Music remains vibrantly diverse: fado, Portugal's traditional melancholic song form, maintains cultural centrality with contemporary artists honoring and innovating upon traditions; Portuguese hip-hop has grown substantially; rock and electronic scenes thrive in Lisbon and Porto; while connections to Brazilian and African Portuguese-speaking nations create distinctive musical fusions. Language sharing with Brazil's massive market creates opportunities but also challenges as Brazilian content often dominates Portuguese screens. Gaming culture has grown, with Portuguese developers creating successful indie titles and esports communities expanding, though infrastructure remains less developed than in wealthier Northern European nations. Social media creators leverage Portugal's stunning coastline, historic cities, and Lusophone cultural connections, building travel and lifestyle followings. Portuguese entertainment succeeds through distinctiveness—embracing Portugal's specific historical experiences, linguistic particularities, and cultural character rather than trying to compete directly with larger Spanish or Brazilian markets, creating authentically Portuguese work that finds audiences precisely through its specificity.`
  }
]

async function main() {
  console.log('🎬 ENTERTAINMENT BATCH 05: Countries 41-50')
  console.log('='.repeat(80))

  const result = await saveEntertainmentSummaries(BATCH_05)

  console.log('\n✅ Batch 05 complete!')
  console.log(`Saved ${result.successCount} summaries to database`)
}

main()
