import { saveEntertainmentSummaries } from './save-entertainment-summaries'

const BATCH_03 = [
  {
    name: 'Costa Rica',
    summary: `Costa Rica punches well above its weight in the entertainment sphere, carving out a niche that's part eco-conscious storytelling, part pure tropical escapism. The nation's film industry has gained traction with works like "El Despertar de las Hormigas" and "Medea," showcased at Cannes and Toronto, proving Central American cinema can hold its own on the global stage. Director Neto Villalobos and cinematographer Nicolás Wong have become names to watch, crafting intimate character studies against lush rainforest backdrops that double as environmental meditations. The country's "pura vida" ethos permeates its creative output, from the surf documentaries that flood streaming platforms to the growing presence of Costa Rican locations in Hollywood productions seeking that perfect jungle aesthetic. Music-wise, the nation has evolved beyond its traditional calypso and marimba roots into a vibrant fusion scene where artists like Debi Nova blend electronic pop with Latin sensibilities, while the underground reggae and ska movements in Limón continue to thrive. Costa Rican gamers have made surprising inroads in the esports arena, particularly in FIFA and fighting game communities, with tournaments in San José drawing regional competitors. The social media landscape explodes with wildlife content creators and eco-tourism influencers who've turned the country's biodiversity into compelling digital narratives, accumulating millions of followers fascinated by sloth sanctuaries and volcanic landscapes. What's particularly striking is how Costa Rica's entertainment exports consistently center environmental themes without feeling preachy, embedding conservation messages in genuinely entertaining packages that resonate internationally.`
  },
  {
    name: 'Panama',
    summary: `Panama's entertainment landscape thrives at the crossroads of the Americas, a cultural mixing bowl where Caribbean rhythms collide with urban Latin pop and Hollywood occasionally comes to film the Canal Zone. The film industry here remains modest but ambitious, with directors like Pituka Ortega-Heilbron breaking through internationally—her film "Salsipuedes" earned critical acclaim for its unflinching look at gang violence and systemic poverty. The Panama International Film Festival has become a crucial platform for Central American cinema, while local productions increasingly explore the country's complex racial and cultural identity, from Afro-Panamanian stories to indigenous narratives often overlooked in mainstream Latin American media. Musically, Panama gave the world reggaeton before the genre exploded globally—artists like El General pioneered Spanish-language reggae fusion in the early 90s. Today's scene vibrates with plena, cumbia, and reggae en español, while contemporary artists like Sech, Joey Montana, and Flex dominate Latin charts, their sounds instantly recognizable worldwide. The streaming era has been kind to Panamanian musicians, who leverage the country's geographic position to blend North and South American influences seamlessly. Gaming culture flourishes in Panama City's cyber cafés and tournament venues, with strong League of Legends and Counter-Strike communities. Social media creators have capitalized on Panama's stunning visual diversity—from cosmopolitan cityscapes to pristine beaches and rainforests—building travel and lifestyle brands that attract international sponsorships. The entertainment industry here understands its unique position, serving as both participant and bridge in the broader Latin American cultural conversation.`
  },
  {
    name: 'Jamaica',
    summary: `Jamaica's cultural influence on global entertainment remains so profound it's almost impossible to overstate—for an island of under three million people, its creative output rivals nations fifty times its size. Music, obviously, forms the cornerstone: from Bob Marley's revolutionary reggae to dancehall's aggressive evolution, from ska's infectious energy to the recent Afrobeats-dancehall fusion dominating charts worldwide. Contemporary artists like Koffee, Popcaan, Shenseea, and Skillibeng carry the torch, their tracks unavoidable in global playlists while maintaining authentically Jamaican sounds and patois. The island's film industry, while smaller, has produced memorable works like "The Harder They Come" which defined Caribbean cinema, and more recently "Sprinter" and "Yardie," showcasing stories of ambition, struggle, and diaspora. Jamaican directors increasingly find opportunities in international co-productions, bringing island perspectives to larger audiences. Television production remains largely regional, but Jamaican personalities dominate Caribbean broadcasting, while the island's natural beauty makes it a favorite filming location for everything from Bond films to resort commercials. Gaming culture has exploded among Jamaican youth, with FIFA tournaments drawing massive participation and Caribbean esports leagues gaining legitimacy. But perhaps most significantly, Jamaican social media creators and dancehall artists have mastered viral culture, their dance challenges, slang, and aesthetic choices rippling through TikTok, Instagram, and YouTube with remarkable consistency. The island's entertainment exports succeed because they never dilute authenticity for accessibility—the world comes to Jamaica's cultural wavelength, not the reverse, and that confidence, that refusal to compromise, is precisely what makes Jamaican entertainment so irresistible.`
  },
  {
    name: 'Trinidad and Tobago',
    summary: `Trinidad and Tobago's entertainment DNA is coded with carnival, calypso, and an almost supernatural ability to fuse disparate influences into something uniquely Trinidadian. The twin-island nation invented the steelpan, arguably the twentieth century's only new acoustic instrument, and that innovative spirit permeates every creative sector. Musically, Trinidad birthed calypso and soca, genres that dominate Caribbean festivals and influence global pop—artists like Machel Montano, Bunji Garlin, and Nailah Blackman command massive regional followings, while newer acts incorporate Afrobeats, dancehall, and trap elements into evolving soca sounds. The country's chutney music scene, blending Indian classical influences with Caribbean rhythms, reflects the nation's significant Indo-Trinidadian population and creates a distinctive fusion found nowhere else. Film production has historically struggled with funding, yet directors like Frances-Anne Solomon and Christopher Din have crafted compelling narratives exploring race, identity, and history, with works screening at Toronto, London, and New York film festivals. Television remains vibrant, with local sitcoms and cultural programming maintaining strong viewership despite cable and streaming competition. Trinidad's Carnival culture generates endless content—the elaborate costumes, massive street parties, and soca competitions provide spectacular visual material that social media creators transform into viral content annually. The gaming community, particularly in Port of Spain, has organized around FIFA, NBA 2K, and fighting games, with regional tournaments growing in prestige. What distinguishes Trinidadian entertainment is its fearless hybridity, its refusal to choose between influences—everything gets thrown into the creative mixing bowl, from Bollywood to dancehall to American hip-hop, emerging as something distinctly, defiantly Trini.`
  },
  {
    name: 'Guyana',
    summary: `Guyana's entertainment landscape operates somewhat under the radar compared to its Caribbean neighbors, but this South American nation with Caribbean soul produces culturally rich work that deserves wider recognition. The country's unique position—geographically South American but culturally Caribbean—creates fascinating artistic tension that filmmakers and musicians navigate with varying degrees of success. The film industry remains nascent, though documentaries exploring Guyana's complex ethnic composition (African, Indian, Indigenous, and Chinese populations) and environmental challenges have gained international festival attention. Music thrives across multiple traditions: chutney, reflecting the Indo-Guyanese majority, dominates alongside reggae and soca, while artists like Timeka Marshall blend these influences with contemporary R&B and pop sensibilities. The Guyanese diaspora in New York, Toronto, and London often drives musical innovation, creating sounds that reference homeland traditions while incorporating global urban influences. Local television consists mainly of news, talk shows, and cultural programming, with limited dramatic production due to funding constraints. Social media has become crucial for Guyanese artists seeking audiences beyond the nation's 800,000 population, with creators focusing on comedy, cultural education, and music videos that rack up views across the diaspora. Gaming culture centers on FIFA and cricket games, naturally, with small but dedicated esports communities emerging in Georgetown. What's most compelling about Guyanese entertainment is its preservation role—in a rapidly changing nation experiencing an oil boom, artists consciously document and celebrate traditions, languages, and cultural practices that might otherwise fade, making entertainment both pleasure and archive, celebration and resistance against cultural homogenization.`
  },
  {
    name: 'Suriname',
    summary: `Suriname's entertainment scene reflects its extraordinary diversity—this tiny South American nation speaks Dutch, practices multiple religions, and blends Javanese, Indian, African, Chinese, and indigenous influences into a cultural stew unlike anywhere else on Earth. Music forms the liveliest sector, with kaseko (a fusion of African, European, and Caribbean styles) serving as the national sound, while artists also produce kawina, traditional Maroon music, and Javanese gamelan performances that would fit comfortably in Indonesia. Contemporary musicians like Damaru blend these traditional forms with hip-hop, dancehall, and electronic music, creating genuinely unique fusions that confound easy categorization. The Dutch-language connection provides Surinamese artists access to European markets, with several musicians achieving success in the Netherlands, though this sometimes creates tension about cultural authenticity and brain drain. Film production remains extremely limited, with most visual storytelling happening through documentaries that explore the country's complex history of colonization, slavery, and indentured labor. Television programming mixes Dutch imports with locally-produced talk shows, cultural programs, and religious broadcasting reflecting the nation's denominational diversity. Social media creators often address cultural identity questions, explaining Surinamese traditions to curious international audiences while building communities among the scattered diaspora. Gaming culture exists but remains small, hampered by limited internet infrastructure outside Paramaribo, though mobile gaming has gained traction. What makes Surinamese entertainment fascinating is its resistance to singular national narratives—entertainment here doesn't try to synthesize diverse influences into one "Surinamese" identity but rather celebrates multiplicity, maintaining distinct cultural traditions side-by-side in productive, occasionally chaotic coexistence.`
  },
  {
    name: 'Belize',
    summary: `Belize occupies a peculiar entertainment niche—Central American by geography, Caribbean by culture, English-speaking in a Spanish-speaking region, and perpetually discovering itself creatively. The music scene pulses with punta and brukdown, traditional Garifuna and Creole styles respectively, while contemporary artists incorporate reggae, dancehall, and soca influences. Musicians like Supa G, Tanya Carter, and Ernestine Carballo carry Belizean sounds internationally, though reaching beyond regional audiences remains challenging for most artists. The country's small population (under 400,000) limits industry infrastructure, yet this intimacy also creates tight creative communities where collaboration thrives. Film production has recently accelerated, with works like "No Mames Güey" and various documentaries showcasing Belizean stories, while the country's stunning barrier reef, jungles, and Mayan ruins make it an attractive filming location for international productions seeking Caribbean and Central American settings. Television consists mainly of local news and imported programming from the US, Mexico, and Caribbean, though cultural shows preserve Garifuna, Maya, and Creole traditions. Belize's diaspora in Los Angeles and New York drives much musical innovation, creating fusion sounds that reference home while addressing immigrant experiences. Gaming culture centers on FIFA and basketball games, with small tournaments in Belize City, while social media creators focus on travel content, environmental conservation, and cultural education—the country's incredible biodiversity and cultural diversity provide endless material. The entertainment landscape here feels perpetually on the verge of breakthrough, talented artists constrained by small markets yet refusing to dilute their distinctively Belizean perspectives for broader commercial appeal.`
  },
  {
    name: 'United Kingdom',
    summary: `British entertainment remains a global juggernaut, its cultural influence wildly disproportionate even to its considerable size—from James Bond to Beatles, from Shakespearean drama to grime music, the UK exports culture at extraordinary volume and quality. Film production thrives across the spectrum: prestige period dramas that vacuum up Oscars, gritty social realism from directors like Ken Loach and Andrea Arnold, genre-bending work from auteurs like Steve McQueen and Lynne Ramsay, plus Marvel blockbusters shot at Pinewood and Leavesden. British television arguably leads the world creatively, from BBC nature documentaries that set visual standards to Channel 4's provocative dramas, from cozy detective series to "Black Mirror's" dystopian brilliance. Streaming has intensified production, with Netflix, Amazon, and Apple+ investing billions in UK-based shows that travel globally. The music scene remains ferociously vibrant: British hip-hop and grime artists like Stormzy, Dave, and Little Simz earn critical acclaim and commercial success, while pop stars like Adele, Dua Lipa, and Harry Styles dominate charts worldwide. The UK's alternative and indie scenes continue generating influential acts, from post-punk revivalists to experimental electronic producers. Gaming culture is massive, from FIFA and Call of Duty tournaments to the thriving British game development industry (Rockstar North, Rare, Creative Assembly) producing globally successful titles. Social media creators span every niche imaginable, from beauty and fashion to political commentary, with British YouTubers and TikTokers commanding massive followings. What distinguishes British entertainment is its range—high and low culture coexist productively, prestige and populism inform each other, tradition and innovation remain in constant, creative conversation.`
  },
  {
    name: 'France',
    summary: `French entertainment operates with characteristic independence, producing culture that proudly prioritizes artistic vision over commercial calculation, though the results can be as commercially successful as they are critically acclaimed. French cinema remains arguably Europe's most vital, protected by subsidy systems and quota requirements that enable auteurs like Claire Denis, Céline Sciamma, and Jacques Audiard to craft uncompromising works while genre filmmakers deliver stylish thrillers and comedies for domestic audiences. The Cannes Film Festival anchors the global film calendar, while French actors like Marion Cotillard, Léa Seydoux, and Omar Sy move fluidly between French productions and Hollywood blockbusters. Television has evolved dramatically, with shows like "Lupin," "Call My Agent," and "The Bureau" proving French series can captivate international streaming audiences without sacrificing distinctively French sensibilities. Music showcases extraordinary diversity: French hip-hop artists like PNL and Nekfeu dominate charts with atmospheric, introspective sounds distinct from American rap; electronic music legends like Daft Punk and Justice influenced global dance music; meanwhile, chanson traditions persist through contemporary artists. France's music market remains Europe's second-largest, fiercely protective of French-language content through radio quotas. Gaming culture thrives, with major developers like Ubisoft (Assassin's Creed, Far Cry) based in France, while esports viewership and participation continue growing. Social media sees French creators building substantial followings, particularly in fashion, beauty, and lifestyle sectors where French cultural capital translates globally. What's remarkable about French entertainment is its self-assurance—it doesn't chase trends or pander to international tastes but trusts that quality, distinctive work will find audiences, and more often than not, that confidence proves justified.`
  },
  {
    name: 'Germany',
    summary: `German entertainment has shed much of its post-war cultural reticence, now producing confident, internationally relevant work across multiple sectors while maintaining distinctively German characteristics—thoughtful, technically excellent, occasionally darkly humorous. Television has experienced a renaissance, with shows like "Dark," "Babylon Berlin," and "Deutschland 83" earning global streaming audiences and demonstrating that German narratives can resonate far beyond German-speaking markets. Film production splits between art-house cinema that continues the New German Cinema traditions (directors like Christian Petzold and Maren Ade crafting psychologically complex character studies) and commercial productions serving domestic audiences. The country's robust film funding infrastructure supports diverse voices, from migrant stories to historical reckonings with Nazi and Communist pasts. Germany's music scene is fascinatingly bifurcated: internationally, German electronic music from labels like Kompakt and Ostgut Ton remains influential, while Rammstein represents German hard rock globally; domestically, German-language hip-hop has exploded, with artists like Capital Bra, Apache 207, and Bonez MC dominating charts with sounds blending US trap influences with distinctly German attitudes. The country hosts massive music festivals (Rock am Ring, Wacken) that draw international crowds. Gaming culture is enormous—Germany is Europe's largest gaming market, with massive esports audiences, thriving development studios, and Gamescom in Cologne serving as a major industry event. Social media creators thrive, from gaming influencers to educational content makers who leverage Germany's reputation for engineering and precision. German entertainment succeeds by balancing quality and accessibility, intellectual rigor and entertainment value, creating work that respects audience intelligence while delivering genuine pleasure.`
  }
]

async function main() {
  console.log('🎬 ENTERTAINMENT BATCH 03: Countries 21-30')
  console.log('='.repeat(80))

  const result = await saveEntertainmentSummaries(BATCH_03)

  console.log('\n✅ Batch 03 complete!')
  console.log(`Saved ${result.successCount} summaries to database`)
}

main()
