import { saveEntertainmentSummaries } from './save-entertainment-summaries'

const BATCH_02 = [
  {
    name: 'Bolivia',
    summary: `Bolivian entertainment operates at Latin America's margins, chronically underfunded yet culturally rich. The film industry produces perhaps two or three features annually, usually social realist dramas exploring indigenous identity, migration to cities, or coca cultivation politics. Jorge Sanjinés remains the towering historical figure—his revolutionary cinema of the 1960s-70s created genuinely Bolivian cinematic language. Contemporary directors struggle with near-total absence of funding infrastructure. Films premiere at international festivals, win awards, then barely screen domestically. The disconnect between critical success and economic viability is stark.

Music offers more vitality. Traditional Andean music—charangos, panpipes, drums—remains culturally central, performed at festivals and protests. The hip-hop scene grows steadily, young Bolivians blending Spanish, Aymara, and Quechua lyrics over beats referencing both trap and Andean rhythms. Folkloric music evolves—groups like Los Kjarkas achieved international recognition decades ago, newer acts update the tradition. The challenge is infrastructure—limited recording studios, radio dominated by foreign music, streaming economics making sustainable careers nearly impossible.

Television consists mostly of cheap telenovelas and news programming. The state broadcaster promotes government messaging, commercial channels operate on minimal budgets. Production values lag far behind wealthier neighbors. Bolivian television feels stuck in earlier era, unable to compete with streaming platforms that younger urban Bolivians increasingly prefer. Gaming culture exists primarily in internet cafés where Counter-Strike and Dota 2 maintain devoted followings. Social media entertainment grows—Bolivian YouTubers create comedy and commentary, building modest audiences. The creator economy offers opportunities, though monetization remains challenging in one of South America's poorest nations. Bolivian entertainment persists through sheer will rather than institutional support, maintaining cultural identity against economic and infrastructural odds.`
  },
  {
    name: 'Paraguay',
    summary: `Paraguayan entertainment operates in profound obscurity, even within Latin America. The film industry barely exists—perhaps one feature film every few years, usually made on microscopic budgets by directors who fund projects through international grants and personal savings. Paz Encina's films screen at major festivals, her meditative style finding audiences among cinephiles while remaining invisible domestically. The challenge isn't just funding but infrastructure—lack of film schools, equipment, theaters willing to screen Paraguayan work. Cinema survives as passionate individual efforts rather than functioning industry.

Music reflects Paraguay's cultural isolation and bilingualism. Guaraní-language music remains popular, particularly polca paraguaya and guaranía—distinctly Paraguayan forms that rarely travel beyond borders. The harp tradition is remarkable, Paraguay having developed unique playing styles. Contemporary music sees small rock and pop scenes in Asunción, bands singing in Spanish and Guaraní to modest audiences. Reggaeton and trap arrive late but gain traction among youth. The streaming era helps—Paraguayan artists can theoretically reach global audiences, though in practice few break through.

Television offers telenovelas and variety shows produced cheaply for domestic consumption. SNT and Telefuturo maintain viewership without investing in quality programming that might compete regionally. Paraguayan television exists in weird time warp, producing content that feels dated by international standards yet satisfies its intended audience. The internet provides escape—younger Paraguayans watch YouTube and Netflix rather than domestic channels. Gaming culture grows slowly, limited by economic constraints making consoles and gaming PCs luxury items. Social media entertainment emerges—Paraguayan TikTokers and YouTubers create content in Spanish and Guaraní, finding small but devoted audiences. The creator economy offers possibilities in nation where traditional employment often disappoints. Paraguayan entertainment persists despite everything, maintaining cultural identity through sheer will rather than institutional support.`
  },
  {
    name: 'Uruguay',
    summary: `Uruguayan entertainment punches slightly above its weight, benefiting from relatively high education levels and cultural sophistication in tiny market. The film industry operates on limited scale but genuine ambition—films like A Twelve-Year Night and Bad Day to Go Fishing win international recognition. Directors explore Uruguayan history, particularly dictatorship era, with subtlety that avoids didacticism. Production companies manage perhaps three to five features annually, usually through co-productions with Argentina, Spain, or international grants. The domestic market can't sustain professional filmmaking, but Uruguay's filmmakers persist through resourcefulness and international connections.

Music remains eclectic, reflecting Uruguay's position between Argentine sophistication and Brazilian vitality without fully embodying either. Candombe, the Afro-Uruguayan drumming tradition, maintains cultural significance, performed during Carnival and cultural events. Rock and pop scenes exist in Montevideo—bands like La Vela Puerca, No Te Va Gustar, Cuarteto de Nos achieved regional success. The electronic music scene is surprisingly robust for country of 3.5 million, Uruguayan DJs and producers gaining international recognition. Contemporary artists blend influences freely, making music that feels cosmopolitan rather than parochially Uruguayan.

Television is dominated by Argentine and Brazilian imports, though domestic channels produce news, sports coverage, and occasional series. Canal 10 and Teledoce maintain viewership without budgets for ambitious production. The small population makes quality television economically challenging—audience just isn't large enough to justify major investment. Streaming platforms provide content Uruguayan television can't afford to make. Gaming culture exists among younger, economically comfortable Uruguayans. Esports sees limited participation given tiny player base. Social media entertainment grows—Uruguayan YouTubers and influencers create content that often targets Argentine and broader Spanish-language audiences, recognizing domestic market limitations. The creator economy offers opportunities, though most successful Uruguayan creators eventually expand beyond national borders to sustain careers. Uruguayan cultural confidence persists despite small scale, producing work that reflects sophisticated society operating within severe economic constraints.`
  },
  {
    name: 'Cuba',
    summary: `Cuban entertainment exists in surreal contradiction—nation of extraordinary creative talent operating under extraordinary constraints. The film industry functions through ICAIC, the state film institute, which for decades produced remarkable work despite (or perhaps because of) limitations. Tomás Gutiérrez Alea's films remain classics of Latin American cinema. Contemporary Cuban directors navigate complex realities—making work that can't be explicitly political yet unavoidably reflects political circumstances. Recent films explore emigration, economic hardship, LGBTQ+ experiences in ways previously impossible. The internet's gradual arrival transforms everything, younger filmmakers making work for festivals and streaming platforms rather than state approval.

Music is where Cuba's cultural power remains undeniable. Son, rumba, timba—Cuban music fundamentally shaped Latin music globally. The Buena Vista Social Club revival demonstrated international appetite for traditional Cuban sounds. Contemporary Cuba produces remarkable musicians working across genres—jazz, hip-hop, electronic, pop—often leaving island to sustain careers. The reggaeton explosion owes debts to Cuban originators who rarely received credit or compensation. Today's Cuban music scene is vibrant despite economic crisis, artists performing in paladares and cultural centers, recording in makeshift studios, distributing through internet when connectivity allows.

Television remains state-controlled, offering propaganda, sports, telenovelas, and occasional quality drama. The arrival of streaming through black market and gradual legal access transforms consumption—Cubans watch foreign content on phones and laptops, bypassing state television entirely. The generational divide is stark—older Cubans watch state TV, younger Cubans watch everything else. Gaming culture exists in limited form—internet cafés where connection permits, phones running whatever games work offline. The social media explosion has been transformative. Cuban YouTubers and TikTokers document daily life, create comedy, build audiences among diaspora. The creator economy offers actual income in collapsing peso economy—dollars from YouTube and Patreon represent genuine salvation. Cuban entertainment is diaspora-izing rapidly, talent leaving while those who remain navigate increasingly absurd contradictions.`
  },
  {
    name: 'Haiti',
    summary: `Haitian entertainment persists despite catastrophe, creativity surviving circumstances that would destroy most industries. The film industry is barely whisper—occasional documentaries, rare features made with international support. Raoul Peck is Haiti's most prominent director, though his career has been international for decades. The infrastructure for filmmaking in Haiti essentially doesn't exist—chronic instability, poverty, lack of equipment and training make production nearly impossible. Yet Haitians tell stories, document their reality, make films in interstices between crises.

Music remains culturally vital. Compas, the Haitian dance music that dominated Caribbean clubs for decades, continues evolving. Haitian artists blend traditional rhythms with hip-hop, R&B, and electronic production. The diaspora looms large—most successful Haitian musicians eventually relocate to Miami, Paris, or Montreal, maintaining connection to Haiti while basing careers elsewhere. Rap kreyòl has exploded, young Haitians making music documenting gang violence, political corruption, and daily survival. The music is raw, immediate, unpolished—recorded on phones in neighborhoods without electricity, distributed through WhatsApp and YouTube.

Television barely functions—infrastructure destroyed by earthquakes and political chaos, programming consists mostly of news, evangelical content, and whatever can be produced on minimal budgets. Streaming exists for privileged few with reliable electricity and internet. Most Haitians access entertainment through phones when connectivity and power align. Gaming culture is essentially nonexistent beyond mobile games on phones.

Social media becomes lifeline and documentary archive. Haitian TikTokers and YouTubers document daily reality—gang violence, political protests, power outages, survival strategies. The content is often harrowing, sometimes darkly humorous, always immediate. The diaspora watches obsessively, maintaining connection to homeland through digital platforms. The creator economy offers modest income in nation where formal employment barely exists. Haitian entertainment is increasingly made by diaspora or those documenting crisis in real-time, cultural production continuing against genuinely catastrophic circumstances.`
  },
  {
    name: 'Dominican Republic',
    summary: `Dominican entertainment thrives on tourism dollars, baseball excellence, and musical innovation that reshaped Latin pop globally. The film industry is modest—perhaps a dozen features annually, usually comedies or dramas exploring contemporary Dominican life. Directors increasingly gain international festival recognition, though commercial viability remains challenging. The DR serves as production location for international projects, infrastructure improving. Government support through DGCINE funds production, though budgets pale compared to Puerto Rican or Colombian levels.

Music is where Dominican cultural power truly radiates. Bachata and merengue are national exports that conquered Latin dance floors globally. Juan Luis Guerra is cultural icon, Romeo Santos makes bachata stadium-scale. The dembow explosion—Dominican contribution to reggaeton and urban music—fundamentally shaped the genre. Contemporary artists like El Alfa dominate Latin charts. The music scene is commercially vibrant, live performances central to tourism economy. Santo Domingo's music culture is diverse and creative.

Television produces telenovelas, variety shows, and sports programming. Baseball broadcasts are culturally central—the DR produces extraordinary MLB talent, games are national obsession. Reality TV formats find audiences, though production budgets are modest compared to larger markets. Streaming platforms increasingly produce Dominican originals, recognizing market potential. The tourism angle influences content—shows highlighting Dominican culture for both domestic and tourist audiences.

Gaming culture grows among urban youth. Internet access improving, gaming cafés popular. Esports infrastructure develops, though at smaller scale than Puerto Rico or Mexico. Baseball remains dominant sports passion, but younger Dominicans engage gaming culture actively.

Social media creators build substantial followings—beauty influencers, comedians, musicians using platforms to reach audiences beyond DR borders. Dominican YouTubers and TikTokers create content that circulates throughout Spanish-speaking world. The creator economy offers entrepreneurial possibilities in nation with significant unemployment despite tourism revenues. Dominican digital content often emphasizes music, dance, humor—reflecting national cultural confidence and extroverted social culture. The diaspora connection is strong, content circulating among Dominicans in US and elsewhere.`
  },
  {
    name: 'Guatemala',
    summary: `Guatemalan entertainment operates in shadows of violence and poverty, cultural production persisting despite challenging circumstances. The film industry is tiny—perhaps two to three features annually, made on minimal budgets through government support and international co-productions. Jayro Bustamante is Guatemala's most internationally recognized contemporary director, his films exploring indigenous identity, LGBTQ+ experiences, and violence's legacy with formal sophistication. The challenge is infrastructure and funding—film schools barely exist, equipment is scarce, distribution is nearly impossible. Yet Guatemalan filmmakers persist, documenting reality and imagining alternatives.

Music reflects Guatemala's indigenous majority and complex colonial legacy. Marimba remains national instrument, performed at ceremonies and cultural events. Contemporary music sees rock and pop scenes in Guatemala City, though commercial viability is limited. Reggaeton and trap dominate youth markets, while traditional música folklórica maintains audiences in rural indigenous communities. The music industry is underdeveloped—limited recording studios, radio dominated by Mexican and American content, streaming offering distribution possibilities but minimal revenue.

Television consists primarily of imported telenovelas, news, and variety shows. Domestic production is minimal, budgets constrained by small advertising market. Evangelical programming is substantial, reflecting Guatemala's religious transformation. Sports broadcasting focuses on football. Streaming platforms provide alternatives for those who can afford subscriptions. The class divide in entertainment access is stark.

Gaming culture exists among urban middle class. Internet cafés provide access where home infrastructure is lacking. Mobile gaming more widespread than PC or console gaming. Esports infrastructure is minimal, though interest exists among younger demographics.

Social media entertainment grows—comedians, political satirists, lifestyle creators building audiences. Guatemalan YouTubers and TikTokers create content despite infrastructure challenges. The creator economy offers possibilities in nation with widespread poverty and limited formal employment. Indigenous creators increasingly assert presence, producing content in Mayan languages. Guatemalan digital entertainment often engages violence, migration, and inequality that mainstream media sometimes avoids. The diaspora connection is strong, content circulating among Guatemalans in US.`
  },
  {
    name: 'Honduras',
    summary: `Honduran entertainment operates amid gang violence and poverty that create challenging production environment. The film industry barely exists—occasional features made on microscopic budgets, usually addressing migration, violence, or rural life. International recognition is rare, infrastructure is minimal, funding nearly nonexistent. Documentary filmmaking offers slightly more viable path, particularly work addressing migration crisis and gang violence. Yet Honduran filmmakers persist, telling stories that would otherwise go untold.

Music offers more cultural vitality. Punta, the Afro-indigenous Garifuna music, represents Honduras's distinctive cultural contribution. Contemporary punta artists blend traditional rhythms with modern production. Reggaeton and trap dominate urban youth markets, while traditional música folklórica maintains rural audiences. The live music scene is constrained by violence and poverty, though musicians persist. The diaspora plays crucial role—Honduran musicians in US maintain cultural connections while building careers abroad.

Television consists primarily of news, telenovelas, and sports programming. Domestic production is minimal, production values modest. Football broadcasts command attention, especially national team matches. Evangelical programming is substantial. Violence and poverty limit what can be produced and how safely crews can operate. Streaming platforms offer escape for those with access, though subscription costs are prohibitive for most.

Gaming culture exists in limited form—internet cafés in safer neighborhoods, mobile gaming on phones. Infrastructure challenges and poverty limit gaming's reach. Esports infrastructure is essentially nonexistent, though interest exists among urban youth.

Social media becomes crucial platform for documenting reality and maintaining diaspora connections. Honduran YouTubers and TikTokers create content despite challenging circumstances—comedy, commentary, music, daily life documentation. The creator economy offers modest income possibilities in nation where formal employment is scarce and dangerous. Migration dominates much content—journeys north, life in US, family separations. Honduran digital entertainment reflects nation in crisis, yet creativity and cultural production persist against genuinely difficult odds.`
  },
  {
    name: 'El Salvador',
    summary: `Salvadoran entertainment operates in aftermath of civil war and gang violence that shaped national consciousness. The film industry is minimal—perhaps one to two features annually, usually addressing war memory, gang violence, or migration. Directors work on microscopic budgets, funding cobbled from international sources. The infrastructure barely exists, yet films get made—testimonials, resistance, documentation. Distribution remains nearly impossible, though international festivals occasionally showcase Salvadoran work.

Music reflects the nation's complicated history and transnational identity. Cumbia, salsa, and rock en español maintain audiences, while reggaeton and trap dominate youth markets. The diaspora looms enormous—most successful Salvadoran musicians operate from Los Angeles, maintaining cultural connections while building careers in larger market. Hip-hop scenes in both El Salvador and diaspora engage gang violence, poverty, migration—the music is often raw documentation of lived experience. Traditional música folklórica persists in rural areas.

Television consists of news, telenovelas, and sports programming. Domestic production is limited by small market and limited advertising revenue. Football broadcasts are popular, particularly national team and international matches. Evangelical programming is substantial, reflecting El Salvador's religious transformation. Streaming platforms offer alternatives for urban middle class, though most Salvadorans rely on broadcast television or increasingly on internet-based content.

Gaming culture exists among urban youth despite infrastructure challenges. Internet cafés provide access, mobile gaming is widespread. Esports infrastructure is minimal, though interest exists. Violence constrains many social activities, making gaming attractive indoor entertainment.

Social media entertainment grows rapidly—comedy creators, musicians, political commentators building audiences. Salvadoran YouTubers and TikTokers create content engaging daily realities—Bukele's government, gang crackdown, migration, family separation. The creator economy offers entrepreneurial possibilities in nation with limited formal employment. The diaspora connection is fundamental—content circulates between El Salvador and US communities, maintaining cultural bonds across borders. Salvadoran digital entertainment often processes violence and migration through humor and music, cultural production continuing despite challenging circumstances.`
  },
  {
    name: 'Nicaragua',
    summary: `Nicaraguan entertainment operates under authoritarian repression that constrains creative freedom. The film industry is minimal—perhaps one feature every year or two, made on microscopic budgets despite government censorship and limited funding. Directors in exile produce work addressing repression and migration, while those remaining navigate careful self-censorship. The infrastructure barely exists, festivals are occasionally shut down, independent cultural production faces genuine state hostility.

Music offers somewhat more freedom, though political content risks consequences. Traditional música nicaragüense—marimbas, guitars, folkloric forms—maintains cultural presence. Contemporary music sees small rock and pop scenes, while reggaeton and trap dominate youth markets. Politically engaged music mostly circulates through diaspora networks or social media. The protest movement of 2018 generated musical responses that government suppressed. Musicians often operate cautiously or from exile.

Television is increasingly state-controlled propaganda mixed with entertainment programming. Independent news channels were shut down, telenovelas and variety shows continue under government watchful eye. Sports broadcasting focuses on baseball and football. Streaming platforms offer alternatives for those with access, becoming crucial for escaping state media control. The generational divide is significant—older Nicaraguans watch state television, younger Nicaraguans find content online.

Gaming culture exists among urban youth despite infrastructure limitations. Internet cafés operate where permitted, mobile gaming is widespread. Esports infrastructure is minimal, government control of internet complicates organization.

Social media becomes crucial for independent expression and diaspora connection. Nicaraguan YouTubers and TikTokers create content carefully navigating political red lines or operating from exile. Comedy and music offer somewhat safer content zones, though political satire risks consequences. The creator economy offers possibilities, though monetization challenges in cordoba economy and political repression create genuine risks. Nicaraguan digital entertainment increasingly splits between domestic content under state oversight and exile content addressing repression directly. The diaspora grows as young Nicaraguans flee, taking creative talent with them.`
  }
]

async function main() {
  console.log('🎬 ENTERTAINMENT BATCH 02: Countries 11-20')
  console.log('='.repeat(80))

  const result = await saveEntertainmentSummaries(BATCH_02)

  console.log('\n✅ Batch 02 complete!')
  console.log(`Saved ${result.successCount} summaries to database`)
}

main()
