import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const countries = [
  { name: 'Jordan', lat: 30.5852, lng: 36.2384 },
  { name: 'Kuwait', lat: 29.3117, lng: 47.4818 },
  { name: 'Kyrgyzstan', lat: 41.2044, lng: 74.7661 },
  { name: 'Laos', lat: 19.8563, lng: 102.4955 },
  { name: 'Latvia', lat: 56.8796, lng: 24.6032 },
  { name: 'Lebanon', lat: 33.8547, lng: 35.8623 },
  { name: 'Lesotho', lat: -29.6100, lng: 28.2336 },
  { name: 'Liberia', lat: 6.4281, lng: -9.4295 },
  { name: 'Libya', lat: 26.3351, lng: 17.2283 },
  { name: 'Lithuania', lat: 55.1694, lng: 23.8813 },
  { name: 'Luxembourg', lat: 49.8153, lng: 6.1296 },
  { name: 'Madagascar', lat: -18.7669, lng: 46.8691 },
  { name: 'Malawi', lat: -13.2543, lng: 34.3015 },
  { name: 'Malaysia', lat: 4.2105, lng: 101.9758 },
  { name: 'Mali', lat: 17.5707, lng: -3.9962 },
  { name: 'Mauritania', lat: 21.0079, lng: -10.9408 },
  { name: 'Mexico', lat: 23.6345, lng: -102.5528 },
  { name: 'Moldova', lat: 47.4116, lng: 28.3699 },
  { name: 'Mongolia', lat: 46.8625, lng: 103.8467 },
  { name: 'Montenegro', lat: 42.7087, lng: 19.3744 },
  { name: 'Morocco', lat: 31.7917, lng: -7.0926 },
];

const summaries: Record<string, string> = {
  'Jordan': `Jordan maintains relative stability in a turbulent region, with moderate crime rates carefully managed by security services. Conventional crime including theft, burglary, and fraud occurs primarily in Amman and tourist areas like Petra. Violent crime is relatively rare compared to neighbors. Terrorism remains a concern, with ISIS-inspired attacks occurring occasionally despite effective counter-terrorism. Jordan hosts massive refugee populations from Syria, Iraq, and Palestine, straining resources. The Public Security Directorate, which includes police functions, is well-trained and generally professional, though human rights concerns exist regarding treatment of detainees. Intelligence services wield significant power. The judiciary operates within Islamic and civil law frameworks, with State Security Courts handling terrorism and some political cases under procedures criticized as lacking due process. Regular courts function with reasonable independence, though executive influence occurs. Jordan's prisons face overcrowding, particularly as terrorism prosecutions have increased inmate populations. Conditions vary, with newer facilities better than older ones. Political prisoners and terrorism convicts are held separately. Corruption exists at moderate levels, with the monarchy and security apparatus largely insulated from oversight. Business regulations and public services see petty corruption. Anti-corruption campaigns occur periodically. Jordan serves as a transit point for drug trafficking, particularly amphetamines from Syria. The massive Captagon trade involves Jordanian interdiction efforts. Human trafficking affects vulnerable refugee populations. Honor crimes, though prosecuted more seriously than previously, continue to claim lives, primarily of women. Syrian refugee criminality has been exploited politically despite data showing minimal involvement. Drug use among youth has increased.`,

  'Kuwait': `Kuwait enjoys low crime rates by regional standards, with wealth from oil revenues supporting extensive security services and generous welfare reducing economic motivations for crime. Violent crime is rare, though domestic violence occurs but is underreported due to cultural factors. Property crime including theft occurs, particularly in commercial areas. Financial crimes and fraud affect businesses. Drug trafficking and use have increased, with enforcement strict including harsh penalties. The Kuwait Police Force is well-equipped and trained, though reliance on foreign labor in lower ranks creates language and integration challenges. Security services wield substantial power. The judiciary operates within Islamic and civil law frameworks, with courts generally functioning professionally though subject to political and social pressures, particularly regarding cases touching on the ruling family or religion. Kuwaiti nationals and foreign residents face different practical treatment. Kuwait's prison system holds both Kuwaitis and foreigners, with conditions generally meeting international standards though concerns about overcrowding and treatment of foreign workers exist. Death penalty remains for serious crimes. Corruption is moderate, lower than many regional neighbors but significant in contracting and business dealings. Kuwait's relatively vibrant parliament provides some oversight. Financial crimes including money laundering involve the banking sector given Kuwait's role as a financial hub. Expatriate workers, comprising over 70% of the population, face exploitation and abuse constituting trafficking for labor. The kafala sponsorship system enables employer control criticized as enabling forced labor conditions. Domestic workers, primarily women from Asia and Africa, are particularly vulnerable to abuse with limited legal protections. Stateless Bidoon population faces systemic discrimination. Political dissent is managed through prosecution of speech offenses and activism. Sectarian tensions between Sunni and Shia populations occasionally manifest, carefully monitored by authorities.`,

  'Kyrgyzstan': `Kyrgyzstan experiences moderate to high crime rates with a criminal justice system struggling amid political instability and corruption. Theft, robbery, and burglary are common, particularly in Bishkek and Osh. Violent crime including assault occurs, with domestic violence widespread but underreported. Organized crime groups operate in drug trafficking, human trafficking, and protection rackets. Ethnic tensions, particularly between Kyrgyz and Uzbeks, periodically erupt into violence as seen in the deadly 2010 Osh riots. The police, reformed from Soviet structures, face severe corruption problems with officers often expecting bribes for basic services. Professionalism and training are inadequate. Political influence over law enforcement is substantial. The judiciary lacks independence, with executive control routine. Corruption within courts is pervasive, with verdicts often determined by bribes or political pressure. Fair trials are difficult to obtain without connections or money. Kyrgyzstan's prisons suffer from overcrowding, tuberculosis epidemics, torture, and harsh conditions. Human rights organizations document systematic abuse. Political prisoners have been held following various government transitions. Corruption is endemic at all levels, with Kyrgyzstan consistently ranking among Central Asia's most corrupt. Multiple presidents have been overthrown amid corruption-fueled popular anger, yet systems persist. Police, judges, and officials routinely demand bribes. Drug trafficking from Afghanistan through Central Asia involves Kyrgyzstan heavily as a transit route and increasingly for consumption. Heroin and synthetic drugs flow through, with corruption enabling trafficking. Human trafficking for labor and sexual exploitation affects women and children, with poverty driving vulnerability. Bride kidnapping, though illegal, still occurs in some communities. Political instability has seen multiple violent government changes. Organized criminal groups have regional connections.`,

  'Laos': `Laos presents limited transparency regarding crime and justice, with authoritarian single-party rule restricting information. Official statistics show low crime rates, though independent verification is impossible. Petty crime including theft occurs in cities like Vientiane and tourist areas. Violent crime is relatively uncommon. The country's location in the Golden Triangle makes it central to drug production and trafficking. Methamphetamine production has exploded, with massive quantities manufactured and trafficked regionally. Opium cultivation continues despite eradication efforts. The Lao People's Armed Forces Police face capacity limitations and corruption. Rural areas have minimal law enforcement presence. Political control over police is absolute. The judiciary lacks independence entirely, operating as an instrument of the Communist Party. Trials lack due process, particularly in political cases. Legal representation is limited. Defendants have minimal rights. Laos' prisons hold political prisoners alongside conventional criminals, with conditions harsh and information restricted. International access is denied. Torture and mistreatment occur with impunity. Corruption is pervasive throughout government and society, with the party-state elite enriching themselves through control of economic resources. Laos ranks among Asia's most corrupt nations. Chinese and Vietnamese influence involves resource extraction with extensive graft. Drug trafficking involves officials at multiple levels, with some areas effectively controlled by trafficking networks. The border with Myanmar sees particularly heavy trafficking. Human trafficking for labor and sexual exploitation affects vulnerable populations, particularly ethnic minorities. Women and girls are trafficked to Thailand and China. Political dissent is not tolerated, with activists imprisoned. Freedom of expression does not exist. Unexploded ordnance from massive US bombing during the Vietnam War continues killing and injuring people.`,

  'Latvia': `Latvia maintains relatively low crime rates since independence from the Soviet Union and integration into the European Union, though challenges remain. Property crime including theft and burglary occurs primarily in Riga, often targeting tourists and vehicles. Violent crime is relatively rare, with most incidents domestic or alcohol-related. Organized crime operates in drug trafficking, human trafficking, and financial crimes, with Russian-speaking criminal networks having historical presence. The State Police of Latvia are generally professional, having undergone significant reforms for EU accession. Language issues between Latvian-speaking majority and Russian-speaking minority occasionally complicate policing. Corruption has been significantly reduced but periodic scandals emerge. The judiciary operates within the civil law tradition with constitutional independence. Courts have improved transparency and efficiency following EU membership requirements. Rule of law indicators are strong by regional standards, though some concerns about political influence remain. Latvia's prisons operate near capacity with conditions generally meeting international standards after reforms. Older Soviet-era facilities have been upgraded or closed. Pretrial detention rates are moderate. Corruption has decreased substantially from the chaotic 1990s post-Soviet era, though problems persist in certain sectors. Latvia has prosecuted high-profile corruption cases including of politicians and officials. Banking sector has faced money laundering scandals involving Russian and CIS money, leading to major regulatory actions. Drug trafficking, particularly synthetic drugs from elsewhere in Eastern Europe, affects Latvia as both transit country and consumer market. Human trafficking for sexual and labor exploitation targets vulnerable populations. Latvia's citizenship policies create a significant stateless population among Russian speakers, leading to social tensions. Hate crimes and discrimination against minorities occur. Domestic violence is addressed through legal reforms and support services.`,

  'Lebanon': `Lebanon's criminal justice system has been devastated by political instability, sectarian conflict, economic collapse, and state weakness. Crime rates have surged amid the economic crisis, with theft, robbery, and kidnapping increasing dramatically. Survival crimes have multiplied as poverty has exploded. Armed groups affiliated with political factions and Hezbollah operate with impunity in areas they control, creating parallel authority structures. Bank robberies by depositors unable to access frozen accounts have become common. The Internal Security Forces face resource shortages, unpaid salaries, and sectarian divisions. Many officers have emigrated. Effectiveness has collapsed. Political and sectarian militias wield more power than formal security services in many areas. The judiciary is paralyzed by political crisis, with judicial appointments blocked for years. Sectarian quotas and political influence compromise independence. Corruption is endemic. Backlogs are massive. Prosecutions of powerful figures are essentially impossible. Lebanon's prisons are overcrowded and suffering from the economic crisis, with inadequate food, medicine, and basic services. Pretrial detention is lengthy. Riots have occurred. Corruption is pervasive and catastrophic, with the political elite accused of looting the state and banking sector, causing economic collapse that has impoverished millions. Lebanese consistently rank corruption among their top concerns. The port explosion investigation has been obstructed by political interference. Drug production, particularly cannabis in the Bekaa Valley and increasingly Captagon amphetamines, involves political protection. Lebanon has become a major Captagon producer and exporter, with Hezbollah involvement alleged. Syrian refugee population strains resources and faces exploitation. Human trafficking affects vulnerable populations. Political violence and assassinations have historically gone unpunished. State collapse is ongoing.`,

  'Lesotho': `Lesotho faces significant crime challenges amid poverty, political instability, and institutional weakness. Crime rates are high, with stock theft representing a traditional but persistent problem affecting rural livelihoods. Armed robbery, murder, and assault are common in urban areas like Maseru. Violent crime has increased amid political turbulence. Gang activity, sometimes linked to South African gangs, affects security. Lesotho Mounted Police Service and police face resource constraints, corruption allegations, and political interference. Multiple police commissioners have been killed or forced into exile amid political conflicts. Police reforms have stalled. The military has been involved in political disputes, occasionally intervening in governance. The judiciary has shown independence in high-profile political cases, but faces political pressure, corruption concerns, and severe resource limitations. Courts operate slowly with substantial backlogs. Judges have fled amid political tensions. Lesotho's prisons are overcrowded and characterized by poor conditions. Pretrial detention is lengthy with many inmates awaiting trial for extended periods. Resources for food, medicine, and maintenance are inadequate. Corruption affects multiple levels of government and society, with political elite enrichment common. Diamond mining sector has been particularly prone to corruption and smuggling. Anti-corruption efforts have been selective and politicized. South African influence affects Lesotho's governance. Lesotho's position as an enclave entirely surrounded by South Africa makes it a transit point for smuggling. Cannabis production for the South African market is widespread, providing income for farmers. Lesotho has recently legalized medical cannabis, though implementation is ongoing. Human trafficking for labor, particularly of children for herding and domestic work, occurs. Political instability has seen multiple coups and coup attempts. Assassination of military officers and political figures has occurred.`,

  'Liberia': `Liberia is rebuilding its criminal justice system after devastating civil wars that destroyed institutions and normalized violence. Crime rates remain elevated, with armed robbery, theft, and assault common in Monrovia and other areas. Rape and sexual violence rates are extremely high, with children particularly vulnerable. Violence against women is endemic. Mob justice occurs frequently as formal justice systems fail. The Liberian National Police are slowly rebuilding capacity with international assistance, but face resource constraints, corruption, low pay, and inadequate training. Public trust is limited. UN peacekeepers departed in 2018, transferring full security responsibility to national forces. The judiciary is weak and corrupt, with many judges lacking proper legal training. Political interference occurs. Bribery is common. Trial by ordeal and traditional justice operate in many areas when formal courts are inaccessible. Liberia's prisons are severely overcrowded with horrific conditions lacking adequate food, water, sanitation, and medical care. Pretrial detention is the norm, with many held for years. Children are sometimes incarcerated with adults. Corruption is pervasive across government and society, with Liberia ranking among the world's most corrupt nations. Rubber concessions and natural resource exploitation involve extensive graft. Former President Taylor's war crimes conviction highlighted the kleptocratic system. Current anti-corruption efforts face resistance. Drug trafficking, particularly cocaine from South America, has increased with Liberia used as a transit point. Corruption facilitates trafficking. Land disputes fuel violence as war-displaced populations return to find land occupied. Accountability for civil war atrocities remains elusive, with truth and reconciliation efforts incomplete. War-era weapons remain in circulation. Child labor and trafficking persist. Secret societies hold significant social power. Many ex-combatants were never properly demobilized or reintegrated.`,

  'Libya': `Libya's criminal justice system has collapsed amid civil war and state fragmentation since the 2011 revolution. Crime has exploded with armed militias controlling territory, kidnapping for ransom common, and human trafficking widespread. Tripoli and Benghazi see constant armed clashes between competing factions. Murder rates have soared. Weapons proliferate. Libya has fragmented into competing governments—the internationally recognized Government of National Accord in Tripoli and the Tobruk-based government allied with General Haftar's forces—each claiming legitimacy. Militias operate with impunity, often nominally aligned with one government but pursuing own interests. Criminal and jihadist groups operate amid chaos, with ISIS having established presence before being militarily defeated, though cells remain. Police institutions have largely disintegrated, with competing forces loyal to different factions. Officer training is minimal. Many police units are actually militias given official titles. Resources are inadequate where police exist. The judiciary is split between competing governments with judges unable to function amid insecurity. Assassinations of judges and prosecutors occur. Trials are impossible in much of the country. Militias operate their own detention facilities. Libya's prisons and detention centers are controlled by various militias, with horrific abuses documented including torture, extrajudicial executions, and inhuman conditions. Migrants are held in detention centers where abuse including slavery-like conditions occurs. Corruption is pervasive with oil revenues siphoned by armed groups and officials. Libya has become the primary transit route for African migrants attempting to reach Europe, with trafficking networks operating openly. Migrants face horrific abuses including slavery, torture for ransom, rape, and murder. Smuggling of weapons, drugs, and goods is widespread. Landmines and unexploded ordnance threaten civilians. Accountability for war crimes and abuses is absent.`,

  'Mali': `Mali faces a catastrophic security and justice crisis amid jihadist insurgency, ethnic conflicts, and state collapse in much of the territory. Crime statistics are unreliable, but violence has exploded since the 2012 crisis. Jihadist groups affiliated with Al-Qaeda and ISIS control vast areas in the north and center, imposing harsh interpretations of sharia law. Kidnapping for ransom targets both locals and foreigners. Armed groups, including separatist groups like MNLA, control territory. Ethnic violence, particularly affecting Fulani and Dogon communities, has killed thousands. The Malian police and gendarmerie have minimal presence in jihadist-controlled areas. Attacks on security forces are frequent. Corruption and low morale undermine effectiveness. French and UN forces provided security assistance, though France withdrew in 2022 after relations deteriorated. Russian Wagner Group mercenaries now operate. The judiciary operates only in government-controlled areas, with much of the country under parallel systems. Courts in Bamako face corruption and capacity limits. Sharia courts operate in jihadist areas. Mali's prisons in government areas are overcrowded with poor conditions. In jihadist-controlled areas, harsh punishments including amputations and executions occur. Mass prison breaks have occurred. Corruption is endemic, with Mali ranking among the world's most corrupt nations. Military coups in 2020 and 2021 overthrew democratic government. Transitional military rulers have extended their rule and expelled critical observers. Drug trafficking, particularly cocaine from South America to Europe and cannabis production, involves terrorist group financing and official corruption. Human trafficking and smuggling of migrants through Mali toward Libya and Europe generates revenues. Gold mining, both legal and artisanal, involves exploitation and conflict. Ethnic violence has displaced hundreds of thousands. Massacres of civilians by armed groups and security forces occur. Child soldiers are recruited by armed groups. Female genital mutilation is widespread.`,

  'Mauritania': `Mauritania faces substantial criminal justice challenges rooted in authoritarianism, slavery legacies, and underdevelopment. Crime rates are moderate, with theft and property crime most common in Nouakchott. Violent crime is relatively low. Terrorism remains a concern with Al-Qaeda in the Islamic Maghreb (AQIM) operating in the Sahel, though Mauritania has avoided major attacks through security measures and alleged accommodations with extremists. The police and gendarmerie operate with limited resources and training. Corruption is common. Human rights abuses including arbitrary detention and torture occur. Security services focus heavily on terrorism and political dissent rather than conventional crime. The judiciary lacks independence, with executive interference routine. Islamic law applies to personal status issues. Political trials do not meet fair trial standards. Slavery-related cases are rarely prosecuted despite laws. Mauritania's prisons suffer from harsh conditions including overcrowding, inadequate food and water, and disease. Abuse of inmates occurs. Political prisoners and activists are held. Corruption is significant, with Mauritanian officials enriching themselves through resource exploitation and foreign assistance. Former President Abdel Aziz faced unprecedented prosecution for corruption, a rare event, though outcomes remain uncertain. Fishing sector involves extensive corruption. Slavery and slavery-like practices persist despite formal abolitions and laws criminalizing slavery. Descendants of slaves, known as Haratines, face systematic discrimination and bonded labor. Prosecutions are extremely rare. Human trafficking for labor and sexual exploitation affects vulnerable populations. Mauritania serves as a transit point for African migrants heading toward Europe, with smuggling networks operating. Drug trafficking through the Sahel involves Mauritanian territory. Ethnic and tribal tensions exist, particularly affecting Black Africans who face discrimination. Land disputes arise from historical injustices. Torture is documented despite official denials. Freedom of expression is restricted with journalists and activists arrested.`,

  'Mexico': `Mexico suffers from one of the world's most severe criminal violence crises, with drug cartels operating as quasi-state actors controlling territory and corrupting institutions. Murder rates have soared, reaching historic highs in recent years with over 30,000 homicides annually. Cartel violence involves massacres, torture, disappearances, and spectacular displays of brutality. Cartels including Sinaloa, Jalisco New Generation, and numerous smaller groups battle over trafficking routes and drug production territory. Extortion, kidnapping, and human trafficking generate additional revenues. The Mexican police forces—federal, state, and municipal—are deeply infiltrated by organized crime. Corruption is endemic, with entire departments sometimes working for cartels. Police are outgunned by cartel arsenals. Officers who resist corruption face assassination. Thousands of police have been killed. Trust is minimal. The military has been deployed for domestic security for years despite constitutional concerns and human rights abuses. The judiciary faces intimidation, corruption, and overwhelming caseloads. Judges, prosecutors, and attorneys have been assassinated. Impunity rates exceed 95% for violent crimes, with most murders never investigated seriously. Forced confessions and torture are common. Mexico's prisons are overcrowded and often controlled by cartels from inside. Riots and massacres occur regularly. Corruption enables privileges for cartel members. Escapes of high-profile criminals have embarrassed authorities. Corruption is pervasive across levels of government, with cartels bribing officials from local police to high political figures. Anti-corruption efforts have had limited success. Drug trafficking to the US market generates tens of billions in revenue. Synthetic drug production, particularly fentanyl and methamphetamine, has exploded. Violence has spread from traditional trafficking routes to previously safe areas. Femicide and disappearances of women have reached epidemic levels, with thousands murdered annually. Mass graves are regularly discovered. Journalists face extreme danger, with Mexico among the world's deadliest countries for media workers. Forced displacement has affected thousands fleeing cartel violence.`,

  'Moldova': `Moldova experiences moderate crime rates while facing significant criminal justice challenges rooted in corruption, economic distress, and political instability. Property crime including theft and burglary is common, particularly in Chisinau. Violent crime occurs but at moderate rates. Organized crime operates in human trafficking, drug trafficking, and smuggling, with moldovan networks having transnational reach particularly to EU countries. Cybercrime emanating from Moldova targets victims internationally. The Police of Moldova, reformed from Soviet-era structures, struggle with corruption, low pay, inadequate resources, and political interference. Public trust is limited. Investigations are often ineffective, particularly when powerful interests are involved. The judiciary lacks independence, with corruption and political control pervasive. Courts are widely perceived as delivering justice based on bribes and connections rather than law. Judges face pressure from political figures and oligarchs. Trials are often predetermined. Moldova's prisons suffer from severe overcrowding, tuberculosis epidemics, and harsh conditions. Facilities lack adequate food, heating, and medical care. Torture and abuse have been documented. Pretrial detention is lengthy. Corruption is endemic at all levels of government and society, with Moldova consistently ranking among Europe's most corrupt nations. Law enforcement, judiciary, customs, and healthcare all affected. High-level corruption involves state capture by oligarchs. The banking sector scandal involving the disappearance of $1 billion highlighted systemic corruption. Drug trafficking involves Moldova as a transit route from Asia to Europe, with local consumption increasing. Human trafficking from Moldova has been extensive, with women and children trafficked for sexual exploitation to EU countries and beyond. Economic desperation drives vulnerability. Transnistria, a breakaway region, operates as a black hole with organized crime, smuggling, and unaccountable governance. Weapons stockpiles pose risks. Political instability and foreign interference complicate governance. Russian influence remains strong. Recent reforms face resistance from entrenched interests.`,

  'Mongolia': `Mongolia maintains moderate crime rates with criminal justice challenges rooted in rapid urbanization, inequality, and corruption. Property crime including theft and burglary is common in Ulaanbaatar, where nearly half the population lives, often in the sprawling ger districts. Violent crime including assault occurs, often alcohol-fueled. Domestic violence is widespread but underreported due to cultural factors. Organized crime operates in drug trafficking, wildlife trafficking, and prostitution. Child trafficking for labor and sexual exploitation affects vulnerable children. The Mongolian police have modernized since democracy but face corruption concerns, inadequate resources, and capacity limitations. Rural areas have minimal law enforcement presence. Investigations are often ineffective. Torture to extract confessions has been documented. The judiciary operates with constitutional independence, but corruption and political pressure affect outcomes. Courts are overburdened with backlogs. Access to justice is limited for the poor and rural populations. Judicial reforms have improved some aspects but challenges persist. Mongolia's prisons face severe overcrowding, with facilities operating at over 200% capacity. Conditions are harsh, particularly in winter when heating is inadequate. Tuberculosis rates are high. Pretrial detention is lengthy. Juvenile offenders are sometimes held with adults. Corruption affects multiple levels of government and business, particularly in the mining sector which dominates the economy. Mining licenses, customs, and procurement involve extensive graft. Anti-corruption efforts have been inconsistent and sometimes politically motivated. Mongolia's vast borders with Russia and China create smuggling opportunities. Wildlife trafficking, particularly of endangered species like snow leopards and saiga antelope, involves international networks. Drug trafficking from China affects Mongolia. Air pollution in Ulaanbaatar from coal burning creates health crises. Hate crimes against Chinese and other foreigners occur. Alcoholism drives much social dysfunction. Judicial corporal punishment was abolished recently. Democracy remains relatively strong compared to neighbors, though institutions face pressure.`,

  'Montenegro': `Montenegro has made substantial progress in criminal justice reform as part of EU accession process, though significant challenges remain. Crime rates are moderate, with property crime and theft most common in coastal tourist areas and Podgorica. Violent crime is relatively low. Organized crime, including drug trafficking, cigarette smuggling, and money laundering, has deep roots from the 1990s era when Montenegro (then part of Yugoslavia) became notorious for smuggling. Some political figures have alleged connections to organized crime. The Montenegrin police have been reformed and professionalized for EU accession, but concerns about political influence and selective enforcement persist. High-profile assassinations of organized crime figures have occurred publicly. Corruption within police exists. The judiciary has improved independence and capacity through EU-mandated reforms, with new prosecutors and judges appointed. However, political influence in high-profile cases remains a concern. Trials proceed slowly with backlogs substantial. Rule of law indicators have gradually improved but remain below EU standards. Montenegro's prisons operate near capacity with conditions generally acceptable though older facilities need upgrades. Pretrial detention rates are moderate. Corruption remains significant, with high-level political corruption a key concern for EU accession. The ruling party's long hold on power (30+ years until recent change) created networks of patronage. Public procurement and privatization involve graft. Anti-corruption efforts have been selective, with critics alleging political motivations. Drug trafficking involves Montenegro as a transit point for cocaine and heroin to Europe, with cigarette smuggling historically significant. Maritime smuggling uses Adriatic ports. Money laundering affects the financial sector, with real estate investment a concern. Chinese investment and influence have grown. Organized crime groups have Balkan regional connections. Political tensions between pro-Serbian and pro-independence factions persist. Press freedom concerns exist with attacks on journalists.`,

  'Morocco': `Morocco maintains relatively controlled crime rates through extensive security services, though human rights concerns accompany this stability. Property crime including theft and pickpocketing affects tourist areas like Marrakech and Fes. Violent crime is relatively low compared to regional standards. Terrorism remains a concern with Morocco having experienced attacks and prevented others. Many Moroccan citizens joined ISIS, with returnees presenting monitoring challenges. The police and gendarmerie are well-resourced and professional, maintaining strong control but facing allegations of human rights abuses including torture, arbitrary detention, and harsh treatment of protesters. Surveillance of activists and dissidents is extensive. The judiciary operates within Islamic and French-influenced civil law frameworks, with independence limited by monarchy's ultimate authority. Political trials often fail to meet fair trial standards, with harsh sentences for speech crimes and activism. Ordinary criminal trials generally function reasonably. Morocco's prisons have undergone reforms improving conditions, but overcrowding persists and allegations of torture and abuse continue. Political prisoners are held, with human rights activists and journalists among them. Conditions vary by facility. Corruption exists at moderate levels, with Morocco making some progress but still facing significant problems. Police often expect small bribes. Larger corruption in business and government contracts occurs. Anti-corruption efforts have been selective. Drug trafficking, particularly cannabis production in the Rif mountains, is substantial with Morocco historically a major global producer. Recent legalization for medical and industrial use aims to regulate the sector. Cocaine trafficking from West Africa to Europe involves Morocco. Human trafficking affects sub-Saharan migrants attempting to reach Europe through Morocco. Exploitation and smuggling networks operate. Western Sahara dispute involves control over territory claimed by Morocco. Treatment of Sahrawi activists raises human rights concerns. Domestic violence is widespread though legal reforms have improved protections. Honor crimes occur. Press freedom is restricted with journalists facing prosecution.`,
};

async function generateAndSave() {
  console.log('Generating Crime writeups for Batch 2 (Jordan through Morocco - 21 countries)...\n');

  for (const country of countries) {
    const summary = summaries[country.name];

    if (!summary) {
      console.log(`⚠️  No summary for ${country.name}`);
      continue;
    }

    try {
      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: country.name,
            type: 'country',
            category: 'crime'
          }
        },
        update: {
          summary: summary,
          lat: country.lat,
          lng: country.lng,
          updatedAt: new Date()
        },
        create: {
          name: country.name,
          type: 'country',
          category: 'crime',
          lat: country.lat,
          lng: country.lng,
          country: country.name,
          summary: summary,
          issues: '[]',
          topStories: '[]',
          storyCount: 0
        }
      });

      console.log(`✓ ${country.name} (${summary.length} chars)`);
    } catch (error) {
      console.error(`✗ Error saving ${country.name}:`, error);
    }
  }

  await prisma.$disconnect();
  console.log('\n✓ Batch 2 complete!');
}

generateAndSave();
