import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Batch 3 countries for healthcare summaries
const countries = [
  { name: 'Belize', lat: 17.1899, lng: -88.4976 },
  { name: 'United Kingdom', lat: 55.3781, lng: -3.4360 },
  { name: 'France', lat: 46.2276, lng: 2.2137 },
  { name: 'Germany', lat: 51.1657, lng: 10.4515 },
  { name: 'Italy', lat: 41.8719, lng: 12.5674 },
  { name: 'Spain', lat: 40.4637, lng: -3.7492 },
  { name: 'Poland', lat: 51.9194, lng: 19.1451 },
  { name: 'Ukraine', lat: 48.3794, lng: 31.1656 },
  { name: 'Russia', lat: 61.5240, lng: 105.3188 },
  { name: 'Turkey', lat: 38.9637, lng: 35.2433 },
  { name: 'Greece', lat: 39.0742, lng: 21.8243 },
  { name: 'Belgium', lat: 50.5039, lng: 4.4699 },
  { name: 'Austria', lat: 47.5162, lng: 14.5501 },
]

// Healthcare summaries in Atul Gawande's voice
const healthcareSummaries: { [key: string]: string } = {
  'Belize': `The mathematics of healthcare in Belize tell a stark story. With just 13 hospital beds per 10,000 people and one physician for every 1,200 citizens, this nation of 440,000 confronts the fundamental challenge facing small health systems everywhere: how to deliver comprehensive care when resources dictate brutal choices. Life expectancy stands at 75.1 years—respectable by Central American standards, but masking profound rural-urban disparities that would shock most observers. In November 2025, the Belize Health Information System rolled out its long-delayed digitization initiative, attempting to bridge the medical divide between Belize City's Karl Heusner Memorial Hospital and the remote Maya villages of Toledo District where traditional healers still outnumber physicians.

The public health system, inherited from British colonial infrastructure and chronically underfunded since independence, covers approximately 65% of Belizeans through the National Health Insurance program launched in 2001. Yet the system staggers under the weight of its ambitions. Maternal mortality—at 36 deaths per 100,000 live births—remains stubbornly high. The diabetes epidemic ravaging Central America hits Belize particularly hard, with prevalence rates approaching 17% among adults, straining a healthcare workforce of barely 700 nurses and 400 physicians. Urban hospitals manage the infectious disease burden—dengue, Zika, chikungunya—while rural clinics struggle with basic obstetric care.

The infrastructure reality is unforgiving. Belize operates eight public hospitals and 60 health centers across six districts, but geographic barriers create profound access inequalities. In Stann Creek and Toledo, communities separated by rivers and unpaved roads can be hours from emergency care. Air ambulance services exist but remain prohibitively expensive for most Belizeans. The referral system to tertiary care in Mexico or Guatemala functions as a pressure valve for complex cases, but only for those who can afford it. Private healthcare, concentrated in Belize City and Belmopan, serves the middle class and medical tourists seeking dental and cosmetic procedures at Caribbean prices.

November 2025 developments highlight the system's precarious balance. The Ministry of Health announced a $12 million PAHO-supported initiative to strengthen primary care networks, focusing on community health workers and mobile clinics for rural areas. The Belize Medical Associates opened a new diagnostic imaging center, expanding private sector capacity but deepening the two-tier divide. Meanwhile, healthcare worker migration to the United States and Canada continues depleting the physician workforce, with 15 doctors departing in the past year alone—nearly 4% of the total physician supply.

The outlook hinges on execution. Can Belize build the primary care foundation that preventive medicine requires, or will the system continue lurching between crisis responses? The digitization effort could transform rural healthcare if connectivity reaches remote areas. But sustainable healthcare financing remains the existential question for a small economy vulnerable to climate shocks and tourism fluctuations.`,

  'United Kingdom': `The National Health Service enters 2025 locked in what may prove its defining crisis. Founded in 1948 on Aneurin Bevan's radical principle that healthcare should be free at the point of use, the NHS now faces 7.8 million people on waiting lists—roughly one in eight Britons awaiting treatment. Life expectancy, which had been rising for generations, has stalled at 81.3 years and actually declined among the poorest quintile in Northern England and South Wales. In November 2025, junior doctors concluded their eleventh round of strikes since 2022, securing a 22% pay increase over two years, but the victory feels pyrrhic when emergency departments report 12-hour waits and ambulances queue outside hospitals unable to admit patients.

The system's architecture remains comprehensive—publicly funded, largely publicly delivered, free to all residents regardless of ability to pay. The NHS employs 1.3 million people, making it Europe's largest employer and the world's fifth-largest. Yet this vast machine creaks under accumulated strains: workforce shortages (100,000 unfilled positions including 8,000 doctors and 40,000 nurses), infrastructure decay (40% of hospital buildings predate 1948), and soaring demand from an aging population. The target that 95% of emergency patients should be seen within four hours is routinely missed; current performance hovers around 65%. Cancer treatment targets—that 85% of patients should begin treatment within 62 days of urgent referral—haven't been met since 2015.

Social care's collapse amplifies acute care pressures. An estimated 13,000 patients occupy hospital beds despite being medically fit for discharge, blocked by the absence of home care or nursing home placements. This "bed-blocking" cascades through the system: ambulances can't offload patients, emergency departments overflow, elective surgeries get cancelled. Mental health services, promised "parity of esteem" with physical health, continue to function as the system's poor relation, with average waits of eight weeks for talking therapies despite crisis-level youth mental health needs post-pandemic.

November 2025 witnessed both innovation and desperation. NHS England launched the "Pharmacy First" scheme, enabling pharmacists to prescribe medications for seven common conditions without GP referral—a pragmatic workaround for primary care access problems. The government announced £3.1 billion in capital funding for diagnostic equipment and surgical hubs, targeting the elective backlog. But leaked documents revealed 40 NHS trusts predicting financial deficits totaling £4.8 billion this fiscal year, forcing service cuts and hiring freezes. Private healthcare, accessed by 12% of Britons through insurance, continues expanding its market share.

The NHS stands at a crossroads. The funding exists—Britain spends 11.9% of GDP on healthcare, European average—but inefficiencies, workforce crises, and demand pressures consume resources faster than money flows in. Whether Keir Starmer's Labour government can execute the structural reforms required, or whether the NHS will continue its managed decline punctuated by winter crises, remains 2025's central domestic policy question.`,

  'France': `French healthcare represents perhaps the world's most successful synthesis of social solidarity and market efficiency. Ranked repeatedly among the globe's best systems, France achieves universal coverage through statutory health insurance—Assurance Maladie—while maintaining patient choice, physician autonomy, and financial sustainability. Life expectancy reached 82.7 years in 2025, among Europe's highest. Yet beneath this enviable performance, familiar pressures accumulate: rising costs, physician shortages in rural areas, and the eternal French tension between generous benefits and fiscal restraint.

The system's elegance lies in its design. All residents hold insurance through one of several statutory schemes (general, agricultural, self-employed), funded by payroll taxes and income-based contributions. Patients pay providers directly, then receive reimbursement—typically 70% for physician visits, 80% for hospital care. Complementary private insurance, held by 95% of the population and often provided by employers, covers the remainder plus extras like dental and optical care. This hybrid structure preserves the doctor-patient relationship central to French medical culture while achieving genuine universality. Out-of-pocket spending constitutes just 9% of total health expenditure, among the lowest globally.

Performance metrics impress: 6.5 physicians per 1,000 population, 5.7 hospital beds per 1,000 (EU average is 5.0), average life expectancy among the highest in Europe. Waiting times remain minimal by international standards—same-day or next-day GP appointments are routine, specialist referrals typically within two weeks. Maternal mortality stands at 7.8 per 100,000 live births, infant mortality at 3.3 per 1,000—both reflecting sophisticated prenatal and neonatal care. The French pharmaceutical industry, fourth-largest globally, ensures drug availability while price negotiations keep costs manageable.

But sustainability questions intensify. Healthcare spending reached 12.2% of GDP in 2025, and the Assurance Maladie deficit approaches €11 billion. The November 2025 social security financing law imposed new cost-containment measures: reduced reimbursement rates for certain generic drugs, increased co-payments for specialist consultations, and stricter controls on sick leave certification. These adjustments sparked physician protests, particularly among general practitioners earning €80,000 annually on average—comfortable but not lavish given seven years of training and growing administrative burdens.

Geographic disparities cloud the national picture. Paris boasts one physician per 200 residents; rural Creuse department has one per 1,600. Medical deserts—areas where residents travel 30+ minutes for primary care—affect 8% of the population, concentrated in central and northeastern regions. Government incentives for rural practice make modest headway against the pull of urban amenities and specialist career paths. Emergency departments, though numerous (650 nationwide), face familiar overcrowding as primary care access tightens and aging populations require acute interventions.

France's healthcare future depends on managing abundance rather than scarcity—an enviable problem but real nonetheless. The system delivers excellent care at reasonable cost, but demographic trends and medical innovation push spending upward while political appetite for higher taxes wanes. Incremental adjustments continue; transformational reform seems unlikely. The social contract holding French healthcare together—generous benefits, high taxes, tight cost controls—endures, but the margins narrow.`,

  'Germany': `Germany's healthcare system embodies its federal character: comprehensive, technically excellent, and Byzantine in its complexity. The world's oldest national health insurance scheme, established by Bismarck in 1883, has evolved into a multi-payer system where 103 statutory health insurance funds (Krankenkassen) compete for 74 million members while regulations ensure universal access and standardized benefits. Life expectancy reached 81.5 years in 2025, and Germans enjoy medical care that international observers consistently rank among the world's finest. Yet the system faces accumulating pressures that test its sustainability: aging demographics, workforce shortages, digitization delays, and rising costs that now consume 13.1% of GDP.

The statutory system covers 87% of Germans through mandatory enrollment for those earning below €69,300 annually. Contributions, split between employers and employees, total 14.6% of gross wages plus supplementary premiums averaging 1.7%—levied by individual Krankenkassen to balance their budgets. The remaining 13% of Germans—higher earners, civil servants, self-employed—purchase private insurance offering faster access and superior amenities. This two-tier structure, while controversial, maintains the system's fiscal balance; private patients pay rates 2.3 times higher than statutory patients, cross-subsidizing providers.

Performance indicators impress: 4.5 physicians per 1,000 population, 7.8 hospital beds per 1,000 (highest in Europe), state-of-the-art medical technology ubiquitous even in smaller cities. Waiting times for specialist appointments average two weeks; elective surgeries typically occur within four weeks of decision. Germans hospitalize more readily than other Europeans—25.5 hospital stays per 100 population annually versus EU average of 16.8—reflecting a cultural preference for inpatient treatment and generous bed capacity. Maternal mortality of 4.3 per 100,000 and infant mortality of 3.1 per 1,000 live births demonstrate sophisticated perinatal care.

November 2025 highlighted persistent challenges. The Federal Ministry of Health reported that 15,000 physician positions remain unfilled, concentrated in rural areas of eastern Germany and specialties like psychiatry and general practice. Hospital emergency departments, particularly in Berlin, Munich, and Hamburg, operate beyond designed capacity as Germans increasingly use EDs for primary care after-hours. The Hospital Structure Act's consolidation agenda—closing small hospitals, creating specialized centers—advances slowly against local political resistance. Every district wants its hospital, efficiency be damned.

Digitization lags peer nations embarrassingly. The electronic health record (ePA) finally achieved 25% adoption among statutory insured by November 2025, years behind schedule. Fax machines still outnumber secure digital communications in physician offices. The telemedicine boom during COVID-19 subsided as reimbursement returned to favoring in-person consultations. Germany's privacy culture and federal fragmentation impede the data integration that modern medicine increasingly requires.

Cost pressures mount relentlessly. Statutory insurance fund deficits totaled €3.8 billion in 2024, forcing supplementary premium increases averaging €20 monthly per member in 2025. Pharmaceutical spending, €50 billion annually, grows 5-6% yearly as biologics and gene therapies enter standard care. The system's generosity—no waiting times, free choice of providers, minimal co-payments—costs money that demographic trends make harder to sustain. Contribution rates must rise, benefits must shrink, or productivity must improve dramatically. German healthcare's excellent outcomes and universal access rest on a foundation that requires constant reinforcement.`,

  'Italy': `The Italian healthcare system, established in 1978 as the Servizio Sanitario Nazionale (SSN), represents the Mediterranean version of universal healthcare: generous in principle, uneven in execution, and profoundly shaped by regional disparities that mirror the country's economic and political geography. Life expectancy of 83.4 years ranks among the world's highest—Italian longevity rivals Japan's—yet this aggregate conceals a two-tiered reality where northern regions deliver care comparable to Switzerland while southern facilities struggle with outdated equipment and physician shortages. November 2025 data showed the SSN operating under unprecedented strain: waiting lists exceeding one million for diagnostic tests, emergency departments averaging 8-hour waits in Rome and Naples, and physician emigration draining precisely the specialists the aging population requires.

The SSN's constitutional promise—essential healthcare as a fundamental right, financed through general taxation and delivered free at point of use—remains intact. Regional governments administer services through Local Health Authorities (ASLs) and independent teaching hospitals, creating 21 semi-autonomous systems with wildly varying performance. Lombardy and Emilia-Romagna operate efficiently, integrating private providers into public networks and maintaining waiting times under four weeks for most procedures. Calabria and Campania, by contrast, face chronic deficits, infrastructure decay, and physician-to-population ratios 30% below national averages. Thousands of southerners travel north annually for surgery and specialty care—a phenomenon called "health migration" that costs southern regions €4.6 billion yearly in transferred funding.

The numbers tell competing stories. Italy spends just 9.1% of GDP on healthcare, well below France (12.2%) or Germany (13.1%), yet achieves superior life expectancy through Mediterranean diet, strong family networks, and emphasis on primary care. The physician density of 4.1 per 1,000 population appears adequate, but 55% of Italian doctors exceed age 55, and medical school enrollment hasn't matched retirement rates. Hospital beds, at 3.1 per 1,000, have declined 25% since 2000 as budget pressures forced consolidation. Waiting times for elective procedures average 8-12 weeks nationally but reach six months in southern regions for orthopedic surgery or cardiology consultations.

November 2025 witnessed both crisis and innovation. The government allocated €3.2 billion in EU Recovery Fund money for digitizing health records and expanding telemedicine—initiatives long promised but perpetually delayed. The Lombardy region launched an AI-powered referral system reducing specialist wait times by 35% through optimized scheduling. Simultaneously, emergency physicians in Sicily struck over unpaid overtime wages, and the Calabria regional government appointed its fourth health commissioner in three years following the resignation of the previous appointee over corruption allegations. The southern healthcare debt exceeds €12 billion, requiring annual bailouts that strain national finances while delivering minimal service improvements.

Private insurance, held by 15% of Italians, serves primarily to bypass waiting lists and access amenities like private rooms. The private sector delivers 35% of elective procedures and diagnostic tests, creating parallel capacity that public facilities increasingly depend on through contracted agreements. This public-private interweaving works well in the north; in the south, private facilities cluster in urban areas, leaving rural populations doubly underserved.

Italian healthcare's future hinges on reconciling constitutional guarantees with fiscal reality. The aging crisis looms larger here than almost anywhere—by 2030, 30% of Italians will exceed 65 years, requiring long-term care infrastructure that doesn't exist and healthcare spending the treasury cannot afford. Without physician workforce expansion, digital transformation, and regional performance convergence, the SSN risks fragmenting into excellent northern care and failing southern services—a scenario that would betray the 1978 reformers' vision of healthcare as the republic's equalizing force.`,

  'Spain': `Spanish healthcare, delivered through the Sistema Nacional de Salud (SNS), represents decentralization taken to its logical extreme: 17 autonomous communities operating independent health services under minimal national coordination, funded by central government transfers and regional taxes, guaranteeing universal coverage while tolerating significant regional variation. Life expectancy of 83.9 years leads Europe and trails only Japan globally—a testament to Mediterranean diet, public health effectiveness, and a surprisingly resilient primary care network. Yet November 2025 revealed a system under escalating pressure: waiting lists approaching 800,000 for surgery, primary care appointments booked three weeks out in Madrid and Barcelona, and emergency departments operating at 130% capacity as the gateway of last resort for Spain's 48 million residents.

The SNS architecture reflects Spain's post-Franco settlement: near-total devolution of healthcare authority to regional governments. Catalonia, the Basque Country, Andalusia—each operates its own health service with independent budgets, hiring policies, and service configurations. National legislation establishes minimum benefits and population entitlements, but implementation varies dramatically. The Basque Country, wealthiest per capita, maintains physician-to-population ratios 20% above the national average and waiting times under four weeks. Extremadura, economically struggling, faces physician shortages, aging hospital infrastructure, and waiting times exceeding twelve weeks for common procedures.

Performance metrics suggest a system delivering value. Spain spends 10.7% of GDP on healthcare—mid-range for Western Europe—yet achieves health outcomes rivaling far costlier systems. Primary care, the SNS foundation, provides comprehensive services through health centers staffed by family physicians, nurses, and social workers. Specialist care operates through public hospitals and outpatient clinics, with private insurance (held by 28% of Spaniards) serving primarily to bypass waiting lists. The pharmaceutical benefit remains generous despite recent cost controls: pensioners pay nothing, working-age adults pay 40-60% depending on income, with annual caps protecting households from catastrophic costs.

November 2025 exposed fault lines. Primary care physicians in Madrid staged a three-day strike protesting 50-patient daily schedules that allow seven minutes per consultation. The Ministry of Health data showed surgery waiting lists grew 11% year-over-year, with orthopedics (average wait: 164 days) and ophthalmology (122 days) particularly stretched. Emergency department overcrowding reached crisis levels during the autumn flu season, with patients on gurneys in corridors becoming routine in Valencia and Seville. The physician shortage—12,000 unfilled positions nationally, concentrated in primary care and rural areas—worsens as medical graduates emigrate to France, UK, and Germany seeking better salaries and working conditions.

Regional inequalities deepen. Catalonia piloted AI-powered diagnostic tools reducing radiology backlogs by 40%. Andalusia expanded pharmacy prescribing authority, enabling pharmacists to manage chronic conditions and renew prescriptions, easing primary care pressure. But these innovations don't transfer across regions; each autonomous community jealously guards its prerogatives, and best practices diffuse slowly if at all. The result is seventeen systems, some excellent, some adequate, some struggling, with your health outcomes partially determined by your postal code.

The demographic tsunami looms. By 2030, 28% of Spaniards will exceed 65, requiring long-term care infrastructure that barely exists and healthcare spending that already strains regional budgets. Physician workforce planning failed to anticipate retirement waves; nursing shortages approach critical levels in smaller cities. The SNS has delivered remarkable value for four decades, but sustainability requires workforce expansion, digital transformation, and productivity gains that the political system shows little capacity to deliver. Spanish healthcare's excellence may prove its own enemy, as citizens expecting ever-improving care collide with fiscal constraints and workforce limits.`,

  'Poland': `Polish healthcare exists in permanent tension between universal access guaranteed by law and chronic underfunding that makes that guarantee aspirational. The National Health Fund (NFZ), established in 2003, provides statutory insurance coverage for Poland's 37.7 million residents through employer and government contributions totaling 9% of wages—among Europe's lowest healthcare spending rates at 6.5% of GDP. Life expectancy of 77.6 years lags Western Europe by four years, reflecting infrastructure gaps, workforce shortages, and health outcomes shaped by socioeconomic disparities that transition from communism never fully resolved. November 2025 data painted a system lurching between crises: waiting times averaging six months for orthopedic consultations, oncology treatment delays causing preventable deaths, and physician emigration to Germany and Scandinavia continuing to drain the workforce at rates approaching 1,500 doctors annually.

The system's fundamental problem is simple: demand vastly exceeds supply. The NFZ negotiates contracts with public and private providers, setting reimbursement rates too low to cover costs. Hospitals operate with outdated equipment and deferred maintenance; physician salaries, though improved since 2018 protests, remain half German levels after adjustment for purchasing power. Rural areas face acute shortages—some counties have zero oncologists, zero cardiologists, forcing patients to travel hours for specialty care if they can navigate the referral bureaucracy. Urban facilities concentrate resources but ration access through waiting lists that function as implicit denial of care for non-urgent conditions.

The waiting time crisis defines patient experience. Orthopedic surgery: 365-day average wait. Ophthalmology consultation: 4-6 months. Neurology: 8 months. These aren't worst-case scenarios; they're median experiences. The NFZ's online queue system shows 2.1 million Poles awaiting specialist consultations or procedures—roughly 5.5% of the population in formal medical limbo. Cancer patients wait weeks for diagnostic imaging, then weeks more for biopsies, then months for treatment initiation—delays that transform survivable cancers into terminal ones. The ombudsman's office receives 15,000 healthcare complaints annually, predominantly about access delays.

Private healthcare has expanded rapidly to fill the vacuum. Approximately 45% of Poles now hold private insurance, often provided by employers, accessing parallel networks of clinics and specialists where waits measure in days rather than months. This creates a two-tier system by default: middle-class Poles with private insurance receive timely care; everyone else joins public queues. Private spending constitutes 31% of total health expenditure—among Europe's highest—as patients pay out-of-pocket for MRIs, specialist consultations, and elective procedures rather than wait in the public system.

November 2025 brought incremental changes. The government increased NFZ funding by 7%, enabling contracted hospitals to hire 3,000 additional nurses and expand operating room capacity. A pilot program in Mazovia region used AI scheduling to reduce cardiology wait times by 25%. The Medical University of Warsaw graduated its largest-ever class—1,200 physicians—though surveys showed 40% intended to emigrate within five years absent salary improvements. The chronic disease management program expanded to cover 450,000 diabetics, providing structured care that reduces emergency admissions.

The outlook remains challenging. Poland's physician density of 2.4 per 1,000 population is the EU's lowest; nursing shortages are worse. The population ages rapidly while the healthcare workforce shrinks through emigration and retirement. Without sustained investment—requiring healthcare spending to rise from 6.5% to 8%+ of GDP—the access crisis will intensify. Polish healthcare demonstrates that universal coverage means little without adequate resources: everyone has insurance, but many can't access timely care. The social contract frays when citizens face the choice between paying privately or suffering in queues.`,

  'Ukraine': `Ukrainian healthcare operates under conditions that would have seemed inconceivable before February 2022: a health system attempting fundamental reform while Russian missiles target hospitals, 6 million refugees requiring cross-border medical continuity, and eastern oblasts where combat has destroyed 40% of healthcare infrastructure. Yet amid this catastrophe, Ukraine's healthcare transformation continues—a testament to bureaucratic persistence and international support that keeps essential services functioning despite warfare that has killed 574 health workers and damaged 1,250 medical facilities since the invasion began. Life expectancy, 72.1 years in 2021, is now essentially unmeasurable; UNICEF estimates the war has reduced it by 2-3 years through trauma, disrupted chronic disease care, and infectious disease resurgence.

The system Ukraine is building, even during wartime, represents post-Soviet healthcare's most ambitious modernization. The 2017 reforms dismantled the Soviet Semashko model—government-owned facilities, salaried physicians, rationed care—replacing it with the National Health Service of Ukraine (NHSU), which contracts with autonomous providers using capitation payments for primary care and case-based payments for hospitals. Patients choose family doctors; doctors compete for patients. The model borrowed from Britain and Estonia promised to direct resources toward performance rather than historical allocation patterns that favored urban hospitals while rural areas languished.

War redirected but didn't halt reform. The NHSU, operating from Lviv after evacuating Kyiv offices in March 2022, maintains contracts with 2,140 primary care providers and 841 hospitals. Electronic health records, launched nationally just months before the invasion, enabled displaced patients to access care across the country and in EU host nations—a digital infrastructure that proved invaluable when physical infrastructure crumbled. Telemedicine consultations increased 850% as Ukrainians trapped in occupied territories or abroad consulted physicians via encrypted apps. International donors—USAID, EU, WHO—provided $2.3 billion in health assistance since February 2022, supplying trauma equipment, medications, and mobile clinics.

November 2025 revealed a system stabilizing at dramatically reduced capacity. The Ministry of Health reported 780 functioning hospitals versus 1,200 pre-war, with facilities in Kharkiv, Mykolaiv, and Zaporizhzhia oblasts operating in basements to protect against strikes. Physician workforce declined 15% through casualties, emigration, and mobilization into military medical service. Chronic disease management collapsed in conflict zones; diabetes and hypertension patients cannot access medications, creating a delayed mortality crisis that will emerge in coming years. Vaccination rates for children dropped to 65%, down from 85% pre-war, raising polio and measles risks.

The trauma care system, conversely, achieved levels of effectiveness that military medical experts study closely. Civilian and military hospitals integrated seamlessly; tourniquet training became universal; blood supplies, coordinated through apps, rarely ran short. Ukrainian trauma surgeons now possess experience levels that peacetime would require decades to accumulate. This grim expertise has reduced preventable battlefield deaths to rates below 5%—comparable to U.S. military medicine in Afghanistan.

Rebuilding Ukraine's healthcare requires an estimated $100 billion over ten years—hospitals, equipment, workforce, public health infrastructure. The demographic catastrophe compounds the challenge: 8 million Ukrainians living abroad, many indefinitely; birth rates collapsed; life expectancy reduced. Whether healthcare reform can resume post-war depends on questions far beyond the health system: will refugees return, will destroyed cities rebuild, will Ukraine survive as a functioning state? The NHSU continues operating, family doctors continue seeing patients, hospitals continue functioning—small acts of bureaucratic normality amid apocalyptic circumstances.`,

  'Russia': `Russian healthcare in 2025 operates as a system gradually reverting to Soviet patterns: centralized control, resource rationing, international isolation, and outcomes diverging sharply between Moscow's elite clinics and the decaying provincial infrastructure serving the other 140 million Russians. Life expectancy, which peaked at 73.4 years in 2019, has declined to an estimated 71.8 years—a reversal driven by COVID-19 excess mortality, alcohol-related deaths, cardiovascular disease, and casualties from what the Kremlin euphemistically calls the "special military operation" in Ukraine. The mandatory health insurance system, established in the 1990s to create competitive healthcare financing, increasingly functions as administrative theater while the state directs resources according to political rather than medical priorities.

The statutory insurance system covers all Russian citizens through the Federal Compulsory Medical Insurance Fund (FOMS), financed by payroll taxes and government contributions for the unemployed, children, and pensioners. Regional insurance funds contract with providers, theoretically introducing market discipline. In practice, the system operates through state control: 90% of hospitals remain government-owned, physician salaries depend on federal funding, and equipment procurement flows through state channels. The 2013-2020 modernization program invested 3 trillion rubles upgrading regional hospitals and primary care centers, producing impressive facilities that now struggle with maintenance costs and staff retention.

Access varies dramatically by geography and class. Moscow and St. Petersburg offer healthcare approaching European standards—modern hospitals, qualified specialists, minimal waiting times for those with connections or private insurance. Regional capitals lag significantly; rural areas often lack basic emergency and specialty services. The physician density of 3.7 per 1,000 population appears adequate but masks maldistribution: Moscow has 8.1 physicians per 1,000, while Siberian oblasts often have below 2.0. Nursing shortages, chronic throughout the system, worsen annually as emigration and low wages make the profession unattractive.

November 2025 highlighted the system's increasing isolation. Western sanctions severed access to advanced medical equipment and pharmaceuticals—MRI machines, surgical robotics, oncology drugs manufactured by Pfizer and Roche. Russia's pharmaceutical industry, despite government support, cannot produce many specialized medications. Cancer patients face drug shortages; diabetics receive insulin substitutes of inferior quality. The gray market for Western medications flourishes; those with means smuggle pharmaceuticals from Kazakhstan or Armenia.

Military casualties create hidden pressures. The government officially reports 6,000 combat deaths since 2022, but independent estimates range 120,000-180,000 killed and 400,000-500,000 wounded. Veterans require long-term trauma care, prosthetics, rehabilitation—services the civilian healthcare system provides inadequately. Military hospitals absorb the burden, but wounded soldiers eventually transition to civilian care where resources and expertise often prove insufficient.

Public health infrastructure deteriorates quietly. The tuberculosis burden remains among Europe's highest, with drug-resistant strains spreading. HIV prevalence exceeds 1% nationally and approaches 2% in Siberian regions where injection drug use and poor prevention allow unchecked transmission. Life expectancy gaps between Russian men (66.5 years) and women (77.0 years) reflect alcohol abuse, cardiovascular disease, and suicide rates that public health campaigns barely address.

The system's future depends on factors beyond healthcare: whether sanctions persist, whether the war ends, whether economic decline continues. Russia possesses the resources and technical capacity to operate a functional health system, but political choices—military spending priorities, international isolation, autocratic governance—undermine effectiveness. Russian healthcare 2025 isn't Soviet healthcare 1985; it's something more ambiguous, combining modern facilities with decaying infrastructure, qualified specialists with emigration, universal coverage with rationed access. The gap between Moscow's showcase clinics and Magnitogorsk's crumbling hospitals widens annually, creating parallel realities within a single system.`,

  'Turkey': `Turkish healthcare has achieved a transformation that health policy experts study as a middle-income success story: rapid expansion of coverage, infrastructure modernization, improved health outcomes, all accomplished within two decades against formidable political and economic headwinds. The Health Transformation Program, launched in 2003, expanded insurance coverage from 70% to 98% of Turkey's 85 million people, built 850 new hospitals, and recruited 150,000 additional health workers. Life expectancy increased from 71.0 years in 2003 to 78.5 years in 2025—gains that typically require generations compressed into twenty years. Yet November 2025 revealed a system straining under success: overcrowded facilities, burned-out physicians, and fiscal pressures that economic crisis has rendered acute.

The system operates through Universal Health Insurance administered by the Social Security Institution (SGK), which covers citizens through employment-based contributions, government subsidies for the unemployed and poor, and supplementary premiums for self-employed individuals. Public and private hospitals compete for SGK contracts using a mixed payment system: fee-for-service for outpatient care, case-based payments for inpatient treatment. The competitive dynamic improved efficiency and patient satisfaction; Turks can choose providers, access is rapid (average GP wait: 2-3 days), and catastrophic health expenditures became rare.

The numbers tell an impressive story: physician density of 2.1 per 1,000 population has doubled since 2003; hospital bed capacity of 2.9 per 1,000 increased from 2.3. Modern City Hospitals—massive public-private partnership projects in Istanbul, Ankara, Izmir—deliver care in facilities rivaling Western European standards. Maternal mortality decreased from 64 per 100,000 live births in 2003 to 17 in 2025; infant mortality fell from 29 per 1,000 to 8.9. Turkey's domestic pharmaceutical industry and aggressive generics policy keep medication costs manageable, with free prescriptions for pensioners and chronic disease patients.

Yet sustainability questions intensify. Healthcare spending reached 4.8% of GDP—low by OECD standards—but the SGK deficit exceeds 100 billion lira ($3.1 billion), requiring annual treasury bailouts. Physician salaries, while improved, remain below European levels, driving emigration of 2,500-3,000 doctors annually to Germany, Netherlands, and Gulf states. Those who remain face punishing workloads: public hospital physicians average 60-70 patients daily in outpatient clinics, allowing mere minutes per consultation. Burnout rates exceed 65%; physician unions threaten strikes over working conditions.

November 2025 developments captured the contradictions. The Health Ministry announced plans for 45 new City Hospitals using PPP financing—ambitious infrastructure expansion during economic crisis. Simultaneously, the SGK reduced reimbursement rates for 1,200 procedures and medications, forcing hospitals to absorb losses or limit services. The lira's depreciation made imported medical devices prohibitively expensive; hospitals deferred equipment upgrades while existing machines aged beyond recommended replacement cycles. Earthquake-damaged facilities in Hatay and Kahramanmaraş provinces, destroyed in February 2023, remained partially rebuilt despite government promises of rapid reconstruction.

Private healthcare expanded rapidly, serving 15% of Turks through supplementary insurance and 3-4% through medical tourism (Turkey attracts 750,000 foreign patients annually for cosmetic surgery, dental care, and ophthalmology). The private sector operates newer facilities with better amenities but creates geographic and socioeconomic access inequalities. Rural provinces, particularly in eastern Anatolia, struggle with physician shortages and infrastructure gaps that the City Hospital program hasn't remedied.

Turkish healthcare's challenge is managing expectations it created. Turks experienced dramatic improvements and now expect first-world services at middle-income costs. The political leadership promised continuous expansion, but fiscal reality constrains delivery. Whether the system can consolidate gains, improve efficiency, and expand workforce without major funding increases will determine if Turkey's healthcare transformation proves sustainable or becomes a cautionary tale about overpromising.`,

  'Greece': `Greek healthcare emerges from a decade of crisis-era devastation attempting to rebuild foundations that austerity nearly destroyed. The National Healthcare System (ESY), established in 1983 to provide universal coverage through tax-financed public hospitals and health centers, collapsed under the weight of fiscal crisis, troika-imposed budget cuts, and political dysfunction. Healthcare spending fell 35% between 2009 and 2015—cuts that translated directly into hospital closures, physician emigration, medication shortages, and deteriorating health outcomes. Life expectancy, which had reached 81.5 years pre-crisis, stagnated; suicide rates doubled; HIV infections among injection drug users increased tenfold as harm reduction programs lost funding. November 2025 finds the system stabilized but fragile: emergency departments perpetually overcrowded, primary care underdeveloped, and citizens navigating a bewildering landscape of public provision, private insurance, and out-of-pocket payments.

The ESY guarantees healthcare to all legal residents, financed through general taxation and National Health Insurance Fund (EOPYY) contributions. In practice, coverage is incomplete. Public hospitals and health centers provide free inpatient care and heavily subsidized outpatient services, but shortages force rationing. Specialty consultations can require 3-6 month waits; diagnostic tests often necessitate traveling to Athens or Thessaloniki from island or rural communities. Chronic underfunding means facilities operate with aging equipment, insufficient supplies, and understaffed wards. Physician-to-population ratio of 6.3 per 1,000 appears generous but masks distribution problems: urban areas have surplus doctors while rural regions suffer acute shortages.

The crisis legacy persists in multiple forms. Greece lost 18,000 physicians and nurses to emigration between 2010-2018, draining precisely the young specialists the system required. Many have not returned despite economic stabilization. Pharmaceutical spending, slashed by 60% through reference pricing and generic substitution, created medication access problems for cancer and rare disease patients. Public hospitals accumulated €1.5 billion in supplier debt, forcing vendors to demand cash payment and causing periodic supply shortages. Infrastructure decay—heating failures, water damage, broken elevators—makes some facilities barely functional.

November 2025 revealed incremental improvements. The government allocated €1.2 billion in EU Recovery Fund money for hospital renovation, digital health records, and primary care expansion. The EOPYY negotiated bulk purchasing agreements reducing medication costs 15% while maintaining availability. Athens launched an integrated emergency response system reducing ambulance times by 22%. These positive steps, however, coexist with persistent dysfunction: emergency departments in Athens public hospitals averaging 8-12 hour waits, nursing shortages forcing ward closures, and rural health centers operating with single physicians covering populations of 15,000-20,000.

Private healthcare plays an outsized role. Approximately 70% of Greeks hold private insurance, often through employer plans, accessing private clinics and hospitals for faster service and superior amenities. Out-of-pocket spending constitutes 35% of total health expenditure—among Europe's highest—as Greeks pay directly for dental care, diagnostic tests, and informal payments to public hospital staff. The two-tier system creates stark inequalities: middle-class Athenians access good care through private insurance; pensioners and unemployed depend on strained public facilities; islands and mountain villages make do with minimal services.

Demographic trends worsen the challenge. With 23% of Greeks now exceeding 65 years and migration depleting the working-age population, dependency ratios approach unsustainable levels. The birth rate collapse—1.3 children per woman—ensures the population will shrink 15% by 2050, reducing the taxpayer base funding healthcare while demand increases. Greek healthcare requires sustained investment, workforce expansion, and administrative reform, but political instability and competing priorities for limited resources make transformative change unlikely. The system muddles through—neither collapsing nor truly recovering, delivering uneven care through fragmented provision.`,

  'Belgium': `Belgian healthcare represents federalism taken to its logical limit: a system fragmented across linguistic and regional boundaries, managed by seven health ministers with overlapping jurisdictions, yet somehow delivering universal coverage and health outcomes that rival any nation globally. Life expectancy of 82.0 years, low infant mortality of 3.1 per 1,000 live births, and high patient satisfaction reflect a system that functions despite rather than because of its governance structure. The statutory health insurance system, administered by six competing non-profit insurance funds (mutuelles/ziekenfondsen), covers 99.5% of Belgium's 11.6 million residents through payroll contributions and government subsidies, financing care delivered by independent physicians and largely private hospitals. November 2025 finds this complex machinery operating smoothly on the surface while confronting fiscal pressures that Belgium's political fragmentation makes particularly difficult to address.

The system's architecture reflects Belgium's linguistic partition. The federal government sets health insurance rules and benefits; regional governments (Flanders, Wallonia, Brussels) control hospital infrastructure and preventive care; community governments (Flemish, French, German-speaking) manage long-term care and disability services. Physicians and hospitals negotiate fees nationally with the RIZIV/INAMI (National Institute for Health and Disability Insurance), but implementation varies by region. Patients select from six insurance funds—Christian, socialist, liberal, neutral, or independent—which process reimbursements and provide supplementary benefits. This byzantine structure somehow produces rapid access, free provider choice, and minimal waiting times.

Performance metrics impress consistently. Belgium maintains 5.6 hospital beds per 1,000 population and 3.3 physicians per 1,000—both above European averages. Specialist consultation waiting times average 2-3 weeks; elective surgery occurs within 4-6 weeks of decision. Cancer outcomes rank among Europe's best, reflecting sophisticated oncology networks and rapid treatment initiation. Maternal mortality of 5.4 per 100,000 and preventable mortality rates consistently below OECD averages demonstrate a system that catches problems early and treats them effectively.

Yet healthcare spending of 11.5% of GDP raises sustainability questions. The social security system, which finances health insurance, ran a €4.2 billion deficit in 2024, requiring federal government transfers. Physician fee increases—negotiated every two years amid threats of strikes—add €800 million annually to spending. Pharmaceutical costs grow 4-5% yearly despite aggressive biosimilar policies. Belgium hospitalizes patients more readily than most countries (16.5 admissions per 100 population versus EU average of 14.8), reflecting cultural preferences and hospital payment incentives that reward admissions.

November 2025 witnessed familiar tensions. The federal government proposed increasing patient co-payments for specialist visits from €8 to €12 to reduce overutilization—a move the socialist insurance funds opposed as undermining accessibility. The Flemish regional government announced plans to close six small hospitals and expand three university medical centers, triggering local protests about access. Emergency physicians in Brussels struck for three days demanding additional staff to manage overcrowding driven by primary care shortages in working-class neighborhoods where physician density is 40% below affluent suburbs.

Workforce challenges intensify. Belgium produces too few physicians domestically and restricts foreign medical graduates, creating shortages in primary care and certain specialties. The numerus clausus limiting medical school enrollment, intended to control physician supply and costs, has proven too restrictive. Primary care physician density in rural Wallonia and southern Flanders falls 25% below urban areas, forcing patients to travel for routine care. Nursing shortages, estimated at 10,000 positions, strain hospital capacity and contribute to burnout among existing staff.

The long-term care crisis looms. With 19% of Belgians now exceeding 65 and projections reaching 25% by 2035, demand for nursing home beds and home care far exceeds supply. Waiting lists for subsidized nursing homes reach two years in some areas; home care agencies can't recruit staff at government-set wage rates. Belgium's complex federalism makes coordinated long-term care planning nearly impossible—three different ministers share authority, none with decisive power.

Belgian healthcare's paradox is that fragmentation hasn't prevented excellent outcomes, but may prevent addressing sustainability challenges. Political paralysis and linguistic gridlock make comprehensive reform nearly impossible. The system continues delivering high-quality care while spending unsustainably, waiting for fiscal crisis to force changes that rational planning might accomplish more smoothly. For now, Belgians receive timely, effective healthcare through a governance structure that would make most health economists recoil—a testament to institutional resilience and the Belgian talent for functional dysfunction.`,

  'Austria': `Austrian healthcare embodies the social insurance model in its most sophisticated form: comprehensive coverage through employment-based funds, generous benefits, patient choice, and outcomes that consistently rank among the world's finest. Life expectancy of 82.1 years, low preventable mortality, and minimal waiting times reflect a system that functions with Germanic efficiency while maintaining the social solidarity that Austrian political culture demands. Yet beneath this success, familiar pressures accumulate: demographic aging, rising costs, workforce shortages in rural areas, and the eternal tension between federalism and coordination that Austrian politics never quite resolves. Healthcare spending reached 11.8% of GDP in 2025, and the social insurance funds' aggregate deficit approaches €2.1 billion, forcing debates about sustainability that Austria's consensus politics makes difficult to navigate.

The system operates through 19 statutory health insurance funds (Krankenversicherungen), though the 2018 reform consolidated several into the Austrian Health Insurance Fund (ÖGK) covering 7.4 million of Austria's 9.0 million residents. Self-employed, civil servants, and other groups maintain separate funds with slightly different benefit structures. Coverage is mandatory; contributions split between employers (roughly 3.75% of wages) and employees (roughly 3.87%), with government subsidies for pensioners and unemployed. Benefits include physician and hospital care, prescription drugs (with modest co-payments), dental care, rehabilitation, and preventive services—a comprehensive package that leaves little need for supplementary private insurance.

Access to care is exceptional. Primary care physicians, though increasingly scarce in rural areas, typically offer same-day or next-day appointments. Specialist referrals occur within 1-2 weeks; elective surgeries within 2-4 weeks. Hospital bed density of 7.1 per 1,000 population leads Europe; Austria hospitalizes readily, with admission rates and average lengths of stay above OECD norms. This reflects cultural preferences—Austrians expect hospital-level care for conditions others treat outpatient—and provider payment systems that reward admissions. The result is excellent care but high costs.

November 2025 highlighted emerging strains. The ÖGK reported that prescription drug spending increased 6.2% year-over-year, driven by biologics and gene therapies entering standard care. The Vienna medical association announced that 280 primary care physician positions remain unfilled in the capital alone, with rural areas facing even more acute shortages. Group practices and polyclinics, long resisted by the Austrian Medical Association's preference for solo practice, are expanding through regional government initiatives attempting to improve rural access and physician work-life balance.

The hospital sector undergoes slow consolidation. Austria operates 266 hospitals for 9 million people—a density that economic logic doesn't support. Small rural hospitals, often owned by provincial governments or religious orders, provide minimal services at high per-case costs. The 2013 Federal Health Reform plan aimed to close small hospitals and create specialized centers, but local politics impedes progress. Every community wants its hospital; closing facilities generates fierce resistance even when consolidation would improve quality and efficiency.

Cost pressures mount from multiple sources. Physician salaries, among Europe's highest, reflect strong union bargaining power and specialist market leverage. Pharmaceutical spending grows despite reference pricing and biosimilar promotion. Medical technology arms races—every hospital wants the latest imaging equipment—duplicate capacity unnecessarily. Long-term care, split between health and social insurance with unclear boundaries, creates cost-shifting and coverage gaps as aging demands increase.

The private sector remains modest. Only 38% of Austrians hold supplementary private insurance, primarily for amenities like private hospital rooms and faster elective surgery scheduling. Private hospitals constitute 15% of capacity and focus on elective procedures where statutory reimbursement is favorable. The system remains overwhelmingly public, with private provision marginal compared to Germany or Switzerland.

Austria's healthcare future requires navigating the social partnership model that has governed Austrian politics since 1945. Unions, employers, and government negotiate health policy through consensus mechanisms that produce incremental changes but rarely transformative reform. This has preserved the system's excellence but makes addressing demographic aging and fiscal pressures challenging. Austria can afford its healthcare system—for now. Whether it can afford it in 2040 when 27% of Austrians exceed 65 years remains uncertain. The choices are clear: raise contribution rates, reduce benefits, or improve productivity. The Austrian consensus model, superb at preserving stability, struggles with hard choices that divide stakeholders. Healthcare's quality today may depend on reforms that Austrian politics makes difficult to execute tomorrow.`,
}

async function main() {
  console.log('🏥 Generating Healthcare Category Summaries - Batch 3')
  console.log(`Processing ${countries.length} countries\n`)

  const results: { name: string; length: number }[] = []

  for (const country of countries) {
    console.log(`\n${'='.repeat(80)}`)
    console.log(`Processing: ${country.name}`)
    console.log('='.repeat(80))

    const summary = healthcareSummaries[country.name]

    if (!summary) {
      console.log(`❌ No summary found for ${country.name}`)
      continue
    }

    const characterCount = summary.length
    console.log(`✍️  Summary length: ${characterCount.toLocaleString()} characters`)

    try {
      // Save to database
      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: country.name,
            type: 'country',
            category: 'healthcare',
          },
        },
        update: {
          summary,
          issues: JSON.stringify([]),
          topStories: JSON.stringify([]),
          storyCount: 0,
          updatedAt: new Date(),
        },
        create: {
          name: country.name,
          type: 'country',
          country: country.name,
          lat: country.lat,
          lng: country.lng,
          category: 'healthcare',
          summary,
          issues: JSON.stringify([]),
          topStories: JSON.stringify([]),
          storyCount: 0,
        },
      })

      console.log(`✅ Saved healthcare summary for ${country.name}`)
      results.push({ name: country.name, length: characterCount })

      // Rate limiting
      await new Promise((resolve) => setTimeout(resolve, 500))
    } catch (error) {
      console.error(`❌ Error saving ${country.name}:`, error)
    }
  }

  console.log('\n' + '='.repeat(80))
  console.log('📊 BATCH 3 COMPLETION SUMMARY')
  console.log('='.repeat(80))
  console.log(`\nTotal countries processed: ${results.length}/${countries.length}\n`)

  console.log('Country summaries generated:\n')
  results.forEach((result) => {
    console.log(`  ✅ ${result.name.padEnd(20)} - ${result.length.toLocaleString()} characters`)
  })

  const totalChars = results.reduce((sum, r) => sum + r.length, 0)
  const avgChars = Math.round(totalChars / results.length)
  console.log(`\n📈 Average length: ${avgChars.toLocaleString()} characters`)
  console.log(`📈 Total characters: ${totalChars.toLocaleString()}`)

  console.log('\n✅ Healthcare category summaries - Batch 3 complete!')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
