import { PrismaClient } from '@prisma/client'
import { countryData } from '../lib/countryData'

const prisma = new PrismaClient()

// Countries 41-80: Denmark through Fiji
const countries = [
  { name: 'Denmark', lat: 56.26, lng: 9.5 },
  { name: 'Ireland', lat: 53.41, lng: -8.24 },
  { name: 'Hungary', lat: 47.16, lng: 19.5 },
  { name: 'Czech Republic', lat: 49.82, lng: 15.47 },
  { name: 'Bulgaria', lat: 42.73, lng: 25.49 },
  { name: 'Croatia', lat: 45.1, lng: 15.2 },
  { name: 'Estonia', lat: 58.6, lng: 25.01 },
  { name: 'Norway', lat: 60.47, lng: 8.47 },
  { name: 'Sweden', lat: 60.13, lng: 18.64 },
  { name: 'Portugal', lat: 39.39, lng: -8.22 },
  { name: 'Netherlands', lat: 52.13, lng: 5.29 },
  { name: 'Romania', lat: 45.94, lng: 24.97 },
  { name: 'Serbia', lat: 44.82, lng: 20.46 },
  { name: 'Switzerland', lat: 46.82, lng: 8.23 },
  { name: 'Slovakia', lat: 48.67, lng: 19.7 },
  { name: 'Lithuania', lat: 54.68, lng: 25.32 },
  { name: 'Latvia', lat: 56.88, lng: 24.6 },
  { name: 'China', lat: 35.86, lng: 104.2 },
  { name: 'India', lat: 20.59, lng: 78.96 },
  { name: 'Japan', lat: 36.2, lng: 138.25 },
  { name: 'South Korea', lat: 35.91, lng: 127.77 },
  { name: 'North Korea', lat: 40.34, lng: 127.11 },
  { name: 'Indonesia', lat: -0.79, lng: 113.92 },
  { name: 'Australia', lat: -25.27, lng: 133.78 },
  { name: 'New Zealand', lat: -40.9, lng: 174.89 },
  { name: 'Pakistan', lat: 30.38, lng: 69.35 },
  { name: 'Bangladesh', lat: 23.68, lng: 90.36 },
  { name: 'Afghanistan', lat: 33.94, lng: 67.71 },
  { name: 'Iran', lat: 32.43, lng: 53.69 },
  { name: 'Israel', lat: 31.95, lng: 35.23 },
  { name: 'Palestine', lat: 31.95, lng: 35.23 },
  { name: 'Iraq', lat: 33.31, lng: 44.36 },
  { name: 'Jordan', lat: 30.59, lng: 36.24 },
  { name: 'Cambodia', lat: 12.57, lng: 104.99 },
  { name: 'Laos', lat: 19.85, lng: 102.5 },
  { name: 'Myanmar', lat: 21.91, lng: 95.96 },
  { name: 'Nepal', lat: 28.39, lng: 84.12 },
  { name: 'Mongolia', lat: 46.86, lng: 103.85 },
  { name: 'Papua New Guinea', lat: -6.31, lng: 143.95 },
  { name: 'Fiji', lat: -17.71, lng: 178.07 },
]

// Detailed Real Estate summaries for each country
const realEstateSummaries: { [key: string]: { summary: string; issues: string[] } } = {
  'Denmark': {
    summary: `Denmark's housing market demonstrates what happens when you combine high incomes, strong institutions, and restrictive zoning: extremely expensive housing that frustrates even wealthy residents. Copenhagen housing costs have become genuinely absurd—median detached homes exceed $600K and average rents consume 25-30% of incomes even for well-paid workers. The fundamental problem is zoning restriction: Danish planning favors single-family detached homes with generous lot sizes, which severely constrains supply in and around Copenhagen. Homeownership rates are high (around 60%), but this reflects wealth concentration rather than accessibility—younger renters face brutal waiting lists for apartments. Construction is regulated heavily through building codes and environmental standards that, while admirable in intent, add substantial costs and slow development velocity. The rental market is relatively sophisticated with formal agreements and tenant protections, but limited supply means landlords have all the power. Denmark's cooperatively-owned housing (around 20% of stock) provides some affordability through collective ownership structures, but these waiting lists are measured in years. High-density development is theoretically permitted but practically restricted by neighborhood resistance and strict design guidelines. Real estate investment is dominated by institutional investors and wealthy Danes buying second homes and investment properties, further constraining owner-occupied supply. Transit-oriented development exists around Copenhagen but remains underdeveloped given the city's size and wealth. The YIMBY lesson from Denmark is clear: you can have high wages, strong governance, and excellent public services while still creating severe housing shortages through restrictive zoning. Without liberalizing residential density rules and streamlining building approval, Denmark will continue pricing out workers and creating multi-year waiting lists.`,
    issues: ['Restrictive single-family zoning dominates', 'Severe affordability crisis', 'Lengthy housing waiting lists', 'Limited apartment construction', 'Second-home investment speculation']
  },

  'Ireland': {
    summary: `Ireland's housing crisis is among Europe's most acute, driven by Dublin's rapid economic growth outpacing construction and strict planning that severely constrains supply. Dublin rents have doubled in a decade and now consume 30-40% of median incomes; homeownership has plummeted as prices have appreciated 300% since the 2008 crisis bottom. The fundamental issue is that Dublin's local authorities and national government have consistently rejected density—preferring low-rise suburban sprawl to efficient apartment development. Zoning in Dublin requires expensive public consultation processes for apartment projects, and neighborhood opposition kills many proposals that would otherwise proceed. Construction costs are elevated by strict environmental standards and labor shortages, but the core constraint is regulatory: planners actively discourage building near transit or in central areas where supply is most critical. Homeownership is increasingly concentrated among the already-wealthy; first-time buyers are effectively priced out. The rental market is becoming increasingly corporatized, with international investors buying stock and competing with local residents for limited apartments. Ireland's government has recognized the crisis and is attempting reform—raising density allowances and streamlining some approvals—but change is slow. Real estate speculation is intense: overseas investors and wealthy Irish buy property for appreciation, removing units from rental or owner-occupied stock. Homelessness has risen visibly, particularly in Dublin's city center. What's needed urgently is aggressive liberalization: eliminate height restrictions in central zones, streamline apartment approvals, and remove single-family zoning near transport corridors. Ireland's natural advantage—membership in the wealthy EU with strong institutions—could translate to housing abundance if planning barriers fell away.`,
    issues: ['Severe Dublin affordability crisis', 'Low-density zoning restricts supply', 'Apartment approvals heavily contested', 'Investor speculation dominant', 'Homelessness rising']
  },

  'Hungary': {
    summary: `Hungary's real estate market reflects post-communist transition challenges mixed with contemporary affordability pressures, especially acute in Budapest where wealth and opportunity concentrate. Budapest housing costs have risen sharply as the city has become a regional investment hub, with apartments consuming 25-35% of incomes in central neighborhoods and more in growing areas. The homeownership rate is relatively high (around 80%, including those with mortgages), reflecting both cultural preference for owning and limited rental alternatives. However, homeownership quality varies enormously: many are inherited, elderly stock in need of renovation; new construction is costly and limited. The rental market is small and increasingly formalized, but with rents rising faster than wages, affordability is deteriorating. Zoning regulations allow reasonable density in Budapest, and development is occurring, but not at sufficient pace to match demand from rural migration and foreign investment. Construction activity is substantial but concentrated in luxury apartments for investors and wealthy buyers. Mixed-income development is minimal—the market produces either cheap inherited older stock or expensive new luxury units with little middle ground. Real estate speculation has intensified with foreign investors from Western Europe and China purchasing property, driving prices. Transit-oriented development exists around Budapest's main lines but could be more aggressive. Homelessness is less visible than in Western Europe but informal housing remains significant in peripheral areas. What Hungary needs is affordable housing policy that encourages mixed-income development and rental market formalization. Without deliberate intervention, Budapest's transformation could exclude ordinary workers.`,
    issues: ['Budapest affordability rapidly declining', 'Luxury-focused new construction', 'Limited middle-income housing supply', 'Foreign investor speculation', 'Aging housing stock elsewhere']
  },

  'Czech Republic': {
    summary: `Czech Republic's housing market, particularly Prague's, has transitioned from affordable post-communist conditions to increasingly expensive central European city status, creating new affordability pressures. Prague apartment prices have appreciated 200% since 2015 and now consume 20-30% of median incomes, with first-time buyer prices becoming genuinely unaffordable. Homeownership rates remain around 75%, but this reflects family inheritance more than contemporary purchasing power. The rental market was historically minimal but is expanding as ownership becomes unaffordable; yet rental costs are rising faster than supply expansion. Zoning in Prague allows moderate density, and some apartment construction occurs, but development rates are insufficient to prevent price appreciation. Building approval processes remain complex, with neighborhood consultations adding time and uncertainty. Construction costs are rising due to labor shortages and material prices, but regulatory delays are equally significant. Real estate investment has shifted dramatically: previously cheap Prague attracted some investor interest, but recent price appreciation has accelerated institutional capital inflows. Transit development around Prague's excellent metro system remains underdeveloped relative to demand—many stations lack dense development. Mixed-income development is inadequate; new construction trends toward either luxury units or affordable social housing with insufficient middle. Homelessness is less visible than in Western Europe but housing insecurity among renters is rising. What Czech Republic needs is liberalization of apartment zoning in Prague and other cities, streamlining of development approval, and deliberate affordable housing production. Without these, the country risks replicating Western European housing crises.`,
    issues: ['Prague affordability crisis emerging', 'Rental supply insufficient', 'Slow development approval', 'Limited middle-income construction', 'Investor speculation accelerating']
  },

  'Bulgaria': {
    summary: `Bulgaria's housing market remains predominantly owned but increasingly strained by affordability pressures in Sofia and coastal cities, while rural depopulation leaves peripheral stock abandoned. Sofia real estate prices have doubled in a decade; rents consume 20-25% of formal-sector incomes but much more for lower-income workers. Homeownership rates are exceptionally high (around 82%), driven by post-communist property privatization and cultural preference, but quality varies dramatically from modern apartments to crumbling communist-era blocks. The rental market is very small and informal; most people own their housing outright or live with family. New construction is minimal outside luxury segments in Sofia and Black Sea coastal areas; affordable housing development is almost nonexistent. Zoning regulations theoretically allow density in urban areas, but enforcement and planning capacity are weak. Building approval processes are slow and opaque, often requiring informal payments. Construction costs are lower than Western Europe, but demand is insufficient to drive supply in anything but luxury and coastal resort categories. Real estate speculation has increased as foreign investors discover Sofia's relatively low prices; apartment blocks in central areas are increasingly owned by investment companies. Homelessness is visible in Sofia's city center but less prominent than in Western Europe. The fundamental challenge is mismatch: high homeownership but much of it in deteriorating Soviet-era housing; strong demand in Sofia and coast but inadequate construction; low demand and abandonment in depopulating rural regions. Bulgaria needs investment in urban regeneration, apartment construction in growth cities, and planning reform. Without this, housing stock will continue aging and Sofia's affordability will deteriorate.`,
    issues: ['Soviet-era housing stock deteriorating', 'Sofia affordability crisis emerging', 'Inadequate new construction', 'Coastal speculation concentrated', 'Rural depopulation abandonment']
  },

  'Croatia': {
    summary: `Croatia's housing market reflects post-war recovery, tourism boom concentration, and EU membership effects, creating a bifurcated system where coastal areas are expensive and investment-driven while inland cities struggle with affordability. Zagreb and Split have experienced rapid price appreciation—especially in coastal properties purchased by European investors—with rents consuming 25-35% of urban incomes. Homeownership rates remain high (around 80%), driven by post-war housing reconstruction and cultural preference, but younger cohorts are increasingly priced out. War reconstruction housing built in the 1990s remains substantial and is aging without adequate renovation support. The rental market is small and increasingly formalized in urban areas, but supply is inadequate relative to demand from young workers and migrants. Zoning theoretically allows density in urban areas, but neighborhood opposition and planning bureaucracy slow apartment approvals. Construction is occurring, particularly in luxury apartments near coasts and in Zagreb's central areas, but affordable housing development is minimal. Transit-oriented development is underdeveloped in Zagreb; bus and tram networks exist but apartment construction near corridors is limited. Real estate speculation is intense in coastal areas and Zagreb's center: foreign investors from Austria, Germany, and beyond treat Croatian property as investment vehicles. Homelessness has become visible in Zagreb and Split. What Croatia needs urgently is affordable housing policy, renovation support for aging housing stock, and planning reform that accelerates apartment approvals. Without this, the country risks creating Western European-style affordability crises while leaving interior regions depressed.`,
    issues: ['Coastal speculation by foreign investors', 'Zagreb affordability crisis worsening', 'Aging post-war housing stock', 'Minimal affordable construction', 'Interior regions depopulating']
  },

  'Estonia': {
    summary: `Estonia's housing market reflects successful transition from Soviet system to market economy, producing formalized, relatively affordable housing by European standards, though Tallinn is experiencing rapid price appreciation. Tallinn apartment prices have doubled since 2015 and now consume 20-25% of formal-sector incomes, but owner-occupied single-family homes remain affordable. Homeownership rates are around 80%, reflecting both cultural preference and ease of mortgage availability. The rental market, while small historically, is expanding as younger professionals migrate to Tallinn; rents are rising faster than wages. Zoning in Tallinn allows moderate density, and apartment construction is occurring, but development approval remains somewhat slow. Building costs are reasonable by Nordic standards, though labor shortages are emerging. Real estate speculation is moderate but increasing: foreign investors are discovering Estonia as a potential growth market. Transit-oriented development is underdeveloped relative to Tallinn's potential; the city has good public transport but apartment construction is not concentrated near corridors. Homelessness is minimal and largely invisible. The fundamental advantage is that post-communist privatization produced relatively distributed homeownership, avoiding the single-landlord concentration of some countries. Mixed-income development is reasonable—new construction spans price points. What Estonia needs is continued liberalization of apartment zoning, streamlining of building approvals, and continued investment in transit corridors. With modest policy improvements, Estonia could remain genuinely affordable while other European cities spiral.`,
    issues: ['Tallinn price appreciation accelerating', 'Rental supply growth inadequate', 'Development approval still slow', 'Foreign investor interest increasing', 'Speculation in central Tallinn']
  },

  'Norway': {
    summary: `Norway's housing market combines wealthy nation incomes with severe restrictions that produce extremely expensive housing, particularly in Oslo and coastal areas. Oslo rents consume 25-35% of median incomes and detached home prices exceed $800K, making this one of Europe's most expensive markets despite high wages. The fundamental constraint is zoning: Norway's planning strongly favors single-family detached homes with strict design requirements, actively discouraging apartment development and density. Homeownership is relatively high (around 80%), but affordability is dependent on family wealth and inheritance. The rental market is extremely tight; apartments are scarce and rents are high relative to supply. Zoning restrictions in Oslo and surrounding regions have been gradually liberalized, and apartment construction is increasing, but remains far below demand. Building codes and environmental standards add substantial cost. Construction is subject to long approval processes with neighborhood veto rights. Real estate investment is dominated by Norwegian pension funds and wealthy individuals; foreign investment is limited by regulations but still present. Homelessness is visible in Oslo's city center, unusual for wealthy Nordic capitals. Transit-oriented development exists around Oslo's good metro and rail system, but density is restricted by zoning. Mixed-income development is limited; new construction produces either relatively expensive apartments or expensive single-family homes. Norway's housing challenge is self-inflicted through zoning restrictiveness despite having the wealth and institutional capacity to house everyone comfortably. What's needed is aggressive liberalization: eliminate single-family zoning in urban areas, streamline apartment approvals, and allow height flexibility. Without this, high wages translate to expensive housing rather than prosperity.`,
    issues: ['Restrictive single-family zoning dominates', 'Extreme affordability crisis', 'Long building approval processes', 'Limited apartment construction', 'Insufficient supply growth']
  },

  'Sweden': {
    summary: `Sweden's housing market has transformed from affordability challenge to genuine crisis through restrictive zoning and immigration-driven demand, particularly visible in Stockholm and Gothenburg. Stockholm rents consume 25-40% of incomes and apartment prices have tripled since 2010; waiting lists for rental apartments are measured in years. Homeownership is around 60%, but entry costs are prohibitive for younger cohorts. The fundamental constraint is that Swedish planning actively restricts density: single-family zoning dominates even within cities, and apartment projects face intense neighborhood opposition and regulatory delay. The rental market is heavily regulated through rent controls and tenant protections that, while protective, severely discourage new construction; vacancy rates near zero. Building approval processes are slow and expensive; environmental review and consultation requirements add time and cost. Construction activity has increased in recent years but remains far below demand, particularly for middle-income apartments. Real estate investment by foreign actors and institutional funds has increased but is constrained by regulations. Transit-oriented development around Stockholm's excellent transit system is underdeveloped; zoning restrictions prevent dense development near stations. Homelessness and housing insecurity are visible and growing in Swedish cities, notable in wealthy Nordic country. Mixed-income development is limited; new construction is either expensive market-rate or subsidized social housing with minimal middle ground. The immigration-driven demand has exposed that Sweden's housing system is fundamentally broken: generous welfare attracts migrants but restrictive housing supply creates affordability crises and inadequate integration support. Sweden needs fundamental planning reform: eliminate single-family zoning in urban areas, modernize rent regulations to encourage construction, and streamline apartment approvals. Without this, Sweden will remain housing-constrained despite its wealth.`,
    issues: ['Restrictive density zoning nationwide', 'Rental market severely undersupplied', 'Long building approval processes', 'Immigration pressures on supply', 'Neighborhood opposition to density']
  },

  'Portugal': {
    summary: `Portugal's housing market has shifted from post-crisis affordability to rapid appreciation driven by foreign investment, EU migration, and remote work professionals, particularly in Lisbon and Porto. Lisbon rents have tripled since 2015 and now consume 30-40% of local incomes, with homeownership increasingly out of reach. Homeownership rates remain relatively high (around 75%), but this reflects older generation ownership; younger cohorts face brutal affordability. The rental market was historically informal and small but is rapidly professionalizing and appreciating; new construction is not matching demand. Zoning in Lisbon theoretically allows density, but development is constrained by slow approval processes and investor focus on luxury conversion rather than new construction. Building costs are reasonable by European standards, but development margins in affordable segments are insufficient to attract builders. Construction activity is concentrated in luxury apartments for foreign investors; middle-income rental construction is minimal. Real estate speculation by foreign investors has become dominant: German, French, British, and Brazilian investors purchase property for appreciation, removing units from local rental stock. Tax incentives for property income have accelerated this dynamic. Homelessness and housing insecurity are visibly increasing in Lisbon, uncharacteristic of a wealthy Western European capital. Transit-oriented development around Lisbon's metro is underdeveloped relative to potential. Mixed-income development is almost nonexistent—new construction is luxury or inherited older stock. What Portugal needs urgently is regulation of foreign investment to prioritize local housing supply, acceleration of development approval, and deliberate affordable housing construction. Without this, Lisbon will be transformed into an investment property capital where actual residents are displaced.`,
    issues: ['Foreign investor speculation dominant', 'Lisbon affordability crisis acute', 'Slow development approval', 'Minimal affordable construction', 'Local displacement accelerating']
  },

  'Netherlands': {
    summary: `Netherlands housing market is theoretically pro-density and well-regulated but faces severe affordability crisis through underproduction relative to demand, excessive investor speculation, and regulatory capture by existing homeowners. Amsterdam and other major cities have extreme affordability crisis: rents consume 35-45% of incomes and homeownership is inaccessible for average workers. Homeownership rates are around 56%, but wealth concentration is severe; inherited property and investment property speculation dominate. The rental market is heavily regulated through rent control, tenant protections, and social housing requirements, which theoretically should produce affordability but instead creates severe shortage and long waiting lists. Building approval processes are complex and lengthy; environmental review and neighborhood consultation requirements delay projects substantially. Construction costs are high due to labor shortages and land scarcity. New housing production is inadequate; social housing construction is constrained by budget limits despite strong demand. Real estate investment has shifted dramatically: housing corporations and private investors increasingly speculate on property appreciation rather than producing affordable rentals. Foreign and institutional investment is substantial. Transit-oriented development is theoretically the planning norm, but underproduction of housing frustrates realization. Mixed-income development is constrained by investment returns logic; market-rate development focuses on expensive units. Homelessness and housing insecurity are rising visibly in Dutch cities. The fundamental problem is that the Netherlands has good planning frameworks but inadequate production of housing, especially affordable stock. This reflects zoning restriction (despite reputation), local opposition to density, and investor preference for appreciation over stable returns. What's needed is massive housing production: deregulation of restrictions on density, streamlining of approvals, and investment in social housing. Without this, Dutch housing will remain crisis-level despite institutional advantages.`,
    issues: ['Severe affordability crisis nationwide', 'Rental market severely undersupplied', 'Long development approval delays', 'Investor speculation dominant', 'Social housing funding inadequate']
  },

  'Romania': {
    summary: `Romania's housing market reflects post-communist privatization producing high homeownership but deteriorating stock, combined with rapid urbanization pressures and rural depopulation. Bucharest housing costs are rising as the city attracts investment and migration, with rents consuming 25-35% of urban incomes. Homeownership rates are exceptionally high (around 96%, highest in Europe), driven by post-1989 privatization of Soviet housing, but quality is often poor and renovation needs are substantial. The rental market is very small and increasingly formalized in urban areas, but supply is inadequate. Zoning regulations theoretically allow density in Bucharest, but development is constrained by slow approval processes and property rights complexity from privatization. Building approval processes are opaque and slow, often requiring informal payments. Construction activity is occurring in Bucharest with foreign and domestic investment, but predominantly in luxury apartments; affordable construction is minimal. Real estate speculation has increased as Western investors discover Bucharest as a growth market; property investment companies are purchasing building portfolios. Transit-oriented development in Bucharest is underdeveloped relative to excellent public transport; apartment construction is scattered. Homelessness is less visible than in Western Europe but housing insecurity among renters is rising. The fundamental challenge is mismatch: high homeownership but much of it in deteriorating privatized Soviet stock; strong demand in Bucharest but inadequate construction; depopulation and abandonment in rural regions. Romania needs investment in urban renewal, apartment construction in growth cities, and planning modernization. Without this, Bucharest's affordability will deteriorate while inherited housing stock continues aging.`,
    issues: ['Deteriorating privatized Soviet housing stock', 'Bucharest affordability declining', 'Slow development approval', 'Luxury-focused new construction', 'Rural depopulation abandonment']
  },

  'Serbia': {
    summary: `Serbia's housing market reflects post-war recovery, EU integration pressures, and investor interest in Belgrade as a regional hub, creating rapid appreciation particularly in the capital. Belgrade rents have doubled in five years and now consume 25-35% of formal incomes, with homeownership increasingly out of reach. Homeownership rates remain high (around 85%), driven by post-war reconstruction and cultural preference, but younger cohorts face severe affordability. War-related housing reconstruction built housing stock that is now aging without adequate renovation. The rental market is small, increasingly formalized in Belgrade, and undersupplied relative to migration demand. Zoning in Belgrade theoretically allows density, but development is constrained by complex land rights from war recovery and slow approval processes. Building approval processes are slow and corruption concerns remain significant. Construction activity is concentrated in Belgrade with luxury apartments attracting investor interest; middle and lower-income construction is minimal. Real estate speculation has intensified: foreign investors from across Europe and beyond treat Belgrade property as growth opportunity. Transit-oriented development is underdeveloped in Belgrade; the city has decent public transport but apartment construction is scattered rather than concentrated. Mixed-income development is minimal; new construction serves wealthy and investors. Homelessness is less visible than in Western Europe but housing insecurity is rising. What Serbia needs is streamlined development approval, investment in affordable housing, and planning reform. Without this, Belgrade will experience Western European-style affordability crisis while interior regions lag.`,
    issues: ['Belgrade affordability rapidly rising', 'Slow development approval', 'Foreign investor speculation', 'Minimal affordable construction', 'Aging war-era housing stock']
  },

  'Switzerland': {
    summary: `Switzerland's housing market is exceptionally expensive even by wealthy world standards, driven by immigration restrictions that constrain supply, ultra-restrictive zoning that prevents density, and wealth concentration that inflates investment demand. Zurich and Geneva rents are among the world's highest, consuming 25-35% of incomes even for well-paid professionals; single-family home prices exceed $1M. Homeownership rates are around 38%, lowest in Europe, reflecting extreme affordability crisis. Swiss planning actively restricts density: single-family zoning dominates, building height is strictly limited, and neighborhood opposition to apartments is culturally entrenched. The rental market is sophisticated and formalized but extremely tight; vacancy rates near zero. Zoning liberalization has accelerated in recent years with some success—some cantons have eliminated single-family zoning and allowed duplex-equivalent density—but implementation is slow and neighborhood opposition remains fierce. Building approval processes are complex and lengthy; environmental and neighbor consultation requirements are substantial. Construction costs are extremely high due to labor shortages, strict building codes, and land scarcity. Real estate investment is dominated by Swiss pension funds and wealthy individuals; foreign investment is constrained by regulations. Transit-oriented development theoretically guides planning but is frustrated by zoning restrictions preventing dense development near corridors. Mixed-income development is minimal; new construction serves wealthy markets. Homelessness is visible in Swiss cities, unusual for wealthy country. Immigration has expanded labor supply despite legal restrictions, creating housing demand that restrictive zoning cannot accommodate. What Switzerland desperately needs is aggressive zoning liberalization: eliminate single-family zoning, allow reasonable heights, and streamline approvals. Without this, Switzerland will remain unaffordable despite its wealth, and immigration restriction will be necessary consequence of housing shortage.`,
    issues: ['Ultra-restrictive single-family zoning', 'Extreme affordability crisis', 'Neighborhood veto power over density', 'Long building approvals', 'Insufficient supply growth']
  },

  'Slovakia': {
    summary: `Slovakia's housing market reflects transition from communist system with relatively affordable housing outside Bratislava, but rapid appreciation in the capital driven by EU integration and investment. Bratislava rents have doubled in a decade and now consume 20-25% of formal incomes, with homeownership increasingly difficult for younger cohorts. Homeownership rates are around 80%, reflecting both post-communist privatization and cultural preference, but quality varies from modern apartments to aging Soviet-era blocks. The rental market is small and increasingly formalized in Bratislava; supply is inadequate relative to migration demand. Zoning regulations theoretically allow density in Bratislava, but development is constrained by slow approval processes and property rights complexity. Building approval processes are sluggish; environmental and consultation requirements add time. Construction is occurring in Bratislava with some foreign investment, but predominantly luxury apartments; affordable housing construction is minimal. Real estate speculation has increased as Western investors discover Bratislava as growth opportunity. Transit-oriented development is underdeveloped in Bratislava; the city has good public transport but apartment construction is not concentrated near corridors. Mixed-income development is limited. Homelessness is less visible than in Western Europe but housing insecurity among renters is rising. What Slovakia needs is faster development approval processes, investment in affordable housing construction, and planning reform. Without this, Bratislava will experience affordability crisis while Soviet-era housing in other regions continues aging.`,
    issues: ['Bratislava affordability crisis emerging', 'Slow development approval', 'Limited affordable construction', 'Aging Soviet-era stock elsewhere', 'Investor speculation increasing']
  },

  'Lithuania': {
    summary: `Lithuania's housing market reflects successful Baltic transition with relatively affordable housing outside Vilnius, though rapid appreciation in the capital is challenging affordability. Vilnius rents have tripled since 2010 and now consume 20-30% of formal incomes, with homeownership increasingly out of reach. Homeownership rates are around 75%, reflecting post-communist privatization, but younger cohorts struggle with entry costs. The rental market is small and increasingly formalized in Vilnius; supply is rising but not matching demand from EU/global migration. Zoning in Vilnius theoretically allows reasonable density, and apartment construction is occurring at moderate pace, but development approval remains somewhat slow. Building costs are reasonable by European standards, but labor shortages are emerging. Construction activity is concentrated in Vilnius with mostly market-rate apartments; affordable housing is minimal. Real estate speculation is moderate but increasing: foreign investors are discovering Lithuania as an undervalued growth market. Transit-oriented development is underdeveloped in Vilnius despite good public transport. Mixed-income development is limited; new construction focuses on market rates. Homelessness is minimal and largely invisible. The fundamental advantage is that post-communist privatization distributed ownership widely, avoiding concentration. What Lithuania needs is liberalization of apartment zoning, streamlining of development approvals, and investment in affordable housing. With modest policy improvements, Lithuania could remain genuinely affordable while other European cities spiral.`,
    issues: ['Vilnius affordability rising', 'Development approval somewhat slow', 'Limited affordable construction', 'Foreign investor interest increasing', 'Rental supply inadequate']
  },

  'Latvia': {
    summary: `Latvia's housing market reflects Baltic transition with relatively affordable housing, though Riga is experiencing rapid appreciation as the country integrates into EU and global capital flows. Riga rents have tripled since 2010 but remain moderate by European standards at 15-25% of formal incomes; homeownership is increasingly accessible relative to Western Europe. Homeownership rates are around 80%, driven by post-Soviet privatization. The rental market is small but growing as young professionals migrate to Riga; supply is expanding at reasonable pace. Zoning in Riga allows moderate density, and apartment construction is occurring steadily. Building approval processes are relatively straightforward by European standards. Construction costs are reasonable, and labor availability is improving. Real estate investment is modest but increasing: some foreign investors are discovering Latvia as undervalued. Transit-oriented development exists but is underdeveloped relative to Riga's good public transport system. Mixed-income development is reasonable; new construction spans price points. Homelessness is minimal and largely invisible. The fundamental advantage is that post-Soviet privatization distributed ownership, and the country remains less expensive than Western Europe. What Latvia needs is continued investment in apartment construction, liberalization of zoning to allow higher density, and development of transit corridors. With modest policy focus, Latvia could remain genuinely affordable while being incorporated into EU wealth dynamics.`,
    issues: ['Riga affordability rising moderately', 'Rental supply growth adequate', 'Mixed-income development occurring', 'Foreign investment modest', 'Development approval reasonable']
  },

  'China': {
    summary: `China's housing market is a paradox: officially the highest homeownership rate globally (around 96%), yet unprecedented affordability crisis due to property-as-investment distortion. Major cities like Shanghai, Beijing, and Shenzhen have median price-to-income ratios exceeding 15-20X, rendering ownership inaccessible despite nominally high homeownership rates. The fundamental problem is structural: developer financing through property sales creates speculation incentive; government land sales to developers create revenue dependency; lack of rental market development means people must buy or live with family; property restrictions (hukou system) create artificial scarcity. Construction is abundant in absolute terms—China builds more housing than most countries combined—but it's concentrated in excess supply tier-2/tier-3 cities (empty cities phenomenon) while tier-1 cities remain inaccessibly expensive. Zoning theoretically allows density, but government preference for speculative investment drives tall residential towers designed for appreciation rather than habitation. Rental markets are deliberately underdeveloped through policy that suppresses rental returns to encourage purchasing; renters have zero security. Real estate speculation is endemic: property is viewed as primary investment vehicle for Chinese wealth; investors hold multiple properties; ghost cities and empty developments are common. Homelessness is minimal (officially zero) through family obligation and hukou residency restrictions. Transit-oriented development is built at scale (Chinese cities have world-class transit) but apartment development is investment-driven rather than actually occupied. What China needs is fundamental reform: develop functioning rental markets, decouple government revenue from land sales, allow cross-city migration through hukou reform, tax vacant properties, and regulate speculative investment. Without this, the property bubble remains a massive economic risk.`,
    issues: ['Property market as speculation vehicle', 'Tier-1 city affordability extreme', 'Ghost cities in tier-2/3 cities', 'Underdeveloped rental markets', 'Hukou residency restrictions artificial']
  },

  'India': {
    summary: `India's housing market is the world's largest yet most fragmented and informal, serving over 1.4 billion people with radically different access by class and location. Urban centers like Mumbai, Delhi, and Bangalore face severe affordability crises: formal housing consumes 40-60% of household incomes for middle-class workers; vast informal settlements house hundreds of millions. Homeownership rates are complex to measure: urban formal ownership is 25-30%, but including inherited rural property and informal occupancy, informal homeownership is extremely high though with zero legal security. The rental market is vast and entirely informal; written agreements are minimal, evictions are easy, and tenant protections are nonexistent. Formal construction activity in major cities is substantial and luxury-focused; massive infrastructure investment (highways, transit) is creating some transit-oriented development. Zoning regulations are theoretically permissive but planning capacity is minimal; corruption is endemic. Building approval processes are slow and require payments; environmental review is inadequate. Construction costs are low, but development is constrained by land assembly, title disputes, and utility coordination. Real estate speculation is intense in major cities: domestic investors and increasing foreign investment treat property as primary wealth vehicle; prices appreciate dramatically. Homelessness is visible and substantial: hundreds of millions live in slums, informal settlements, and on streets. Transit-oriented development around major transit projects creates some opportunity. Mixed-income development is minimal; new construction serves wealthy markets; lower-income housing is informal and unplanned. What India needs is fundamental reform: land titling and registry systems that actually function, rental market formalization with tenant protections, affordable housing investment, and slum upgrade programs. Without this, inequality in housing will continue defining opportunity and health.`,
    issues: ['Informal settlements house hundreds of millions', 'Urban affordability crisis severe', 'Land titling system dysfunctional', 'Slum populations massive', 'Speculation intense in major cities']
  },

  'Japan': {
    summary: `Japan's housing market presents a unique situation: reasonably affordable urban housing despite being among world's wealthiest nations, but facing demographic collapse that is fundamentally reshaping the system. Tokyo and Osaka rents consume 20-25% of incomes, and ownership is relatively accessible compared to other wealthy cities, reflecting adequate construction to match demand. Homeownership rates are around 62%, higher than might be expected. The rental market is sophisticated and substantial; landlord-tenant law is reasonable and occupancy is fluid. Zoning allows moderate density in urban areas, and development is substantial, but is gradually slowing due to population decline. Building approval processes are relatively efficient; construction proceeds at steady pace. Construction costs are high, but adequate supply keeps prices reasonable. The fundamental dynamic is unique: population decline reduces housing demand; abandoned properties are common; Tokyo is being recycled through demolition and reconstruction. Real estate investment is modest compared to other wealthy countries; property is viewed more as shelter than investment. Transit-oriented development is the Japanese norm; dense development around transit corridors is standard; this produces efficient, walkable neighborhoods. Mixed-income development is reasonable; housing spans price points. Homelessness is visible in major cities but less prominent than in other wealthy nations; many rough sleepers are elderly men. The challenge is demographic: as population shrinks, maintaining housing stock becomes difficult and fewer young people can support construction industry. What Japan needs is to sustain construction industry and maintain mixed-income housing as population stabilizes at lower level. The country's advantage is demonstrating that adequate density, good transit, and housing-as-shelter-not-investment can produce affordability.`,
    issues: ['Demographic decline reducing demand', 'Property abandonment in regions', 'Aging housing stock', 'Construction industry facing labor shortage', 'Migration concentration in Tokyo']
  },

  'South Korea': {
    summary: `South Korea's housing market is exceptionally expensive despite wealthy nation status, driven by geographic constraint (mountainous peninsula), rapid urbanization concentration in Seoul metro, and speculation-focused investment culture. Seoul rents consume 25-35% of incomes and homeownership is increasingly inaccessible; chonse (key money) rental system creates financial barriers. Homeownership rates are around 60%, but concentrated among older generation; younger cohorts face brutal affordability. The rental market has unique features: chonse requires large deposits (often 50-70% of property value), creating financial barriers to younger renters; jeonse (long-term rental) is cheaper but removes property from owner use. Zoning theoretically allows density, but development is concentrated in Seoul metro. Building approval is complex; height restrictions and parking requirements limit apartment development. Construction is substantial in Seoul metro but concentrated in luxury; affordability housing is minimal. Real estate speculation is intense: property is viewed as primary wealth vehicle; investors accumulate multiple apartments; prices appreciate dramatically. Homelessness is visible in Seoul despite national wealth. Transit-oriented development is excellent: Seoul metro is world-class and extensive, producing dense development and efficient neighborhoods. Mixed-income development is limited; new construction focuses on luxury or social housing with minimal middle. What South Korea needs is rental market reform that encourages new supply and reduces speculation, affordability housing construction, and possibly reduction of Seoul concentration through deliberate regional development. Without this, young Koreans face housing insecurity despite national wealth.`,
    issues: ['Seoul affordability extreme', 'Speculation-driven market', 'Chonse system creates barriers', 'Limited middle-income housing', 'Seoul concentration excessive']
  },

  'North Korea': {
    summary: `North Korea's housing market is entirely state-controlled and functions as instrument of political control rather than economic good. Housing is allocated by the state to workers, military, and favored elites; private ownership is prohibited. Formal homeownership does not exist; residents occupy housing allocated through state enterprises or military affiliation. Construction is state-directed for government buildings and elite housing; ordinary residential construction is minimal and deteriorating. Zoning is state-determined; cities develop according to regime planning rather than any market logic. Housing quality varies dramatically: elite housing in Pyongyang is relatively modern; ordinary worker housing is deteriorating Soviet-era blocks; rural housing is often inadequate. Rents are effectively zero since the state allocates housing, but housing costs for ordinary citizens are hidden in inefficient wages and food systems. Real estate speculation does not exist. Homelessness is officially zero (regime denies it), but housing insecurity is substantial among ordinary citizens. Market-like rental transactions occur informally at margins but remain illegal. Transit development is minimal; transportation is limited. What North Korea has is housing as complete state monopoly aligned to political control. This produces visible homelessness despite state denial, inadequate housing quality, and system where housing serves regime stability rather than human need. Any housing market improvement would require regime liberalization that is not occurring.`,
    issues: ['State monopoly control eliminates market', 'Housing as political tool', 'Inadequate construction, deteriorating stock', 'Elite-ordinary housing disparity extreme', 'Homelessness denied but substantial']
  },

  'Indonesia': {
    summary: `Indonesia's housing market serves the world's 4th largest population with radically variable development: modern formal apartment markets in Jakarta and Surabaya alongside vast informal settlements housing hundreds of millions. Jakarta faces rapid affordability decline: formal apartment rents consume 25-35% of formal-sector incomes; homeownership is increasingly out of reach. Homeownership formally is around 50%, but including informal self-built housing and family occupation, informal ownership is extremely high though with zero legal security. Formal rental markets are small and increasingly professionalized in major cities; informal rentals house most urban renters with zero protections. Zoning regulations theoretically allow density, but planning capacity is minimal and corruption is endemic. Construction of formal apartments is substantial in major cities but concentrated in luxury; middle and lower-income construction is minimal. Real estate speculation has accelerated: domestic investors and increasing foreign interest in Indonesia's growth trajectory drives property investment. Homelessness and housing insecurity are visible and substantial: informal settlements (kampung) house hundreds of millions with adequate housing conditions varying from precarious to reasonable. Transit-oriented development exists in major cities but is underdeveloped relative to infrastructure projects. Mixed-income development is minimal; formal construction focuses on luxury. What Indonesia needs is land titling and registry systems that function, affordable housing investment, informal settlement upgrade programs, and rental market regulation that protects tenants while encouraging supply. Without this, housing will remain concentrated among wealthy while hundreds of millions live in precarious conditions.`,
    issues: ['Informal settlements house hundreds of millions', 'Land titling system dysfunctional', 'Luxury-focused formal construction', 'Affordability crisis in major cities', 'Speculation concentrated in growth cities']
  },

  'Australia': {
    summary: `Australia's housing market epitomizes wealthy developed country housing crisis: extremely expensive housing despite economic prosperity, driven by restrictive zoning, speculation-focused investment culture, and immigration without commensurate supply expansion. Sydney and Melbourne rents consume 25-35% of incomes and house prices are among world's least affordable for wealthy nation; ownership is increasingly inaccessible. Homeownership rates are declining, now around 65%, as properties become investment assets rather than shelter. The rental market has become increasingly corporate and investor-owned; single-family rental properties are increasingly purchased by institutional funds. Zoning is restrictive: detached single-family lot requirements dominate, apartment development is restricted, and neighborhood opposition to density is culturally strong. Building approval processes are complex and lengthy; environmental and neighbor consultation adds significant time and cost. Construction is occurring but insufficient to match demand; foreign investment in property is substantial and viewed as problem by locals. Real estate speculation is endemic: property is viewed as primary investment vehicle; investors accumulate multiple properties; negative gearing (tax deduction for rental losses) encourages speculation; overseas investors purchase property, reducing supply for local residents. Homelessness and housing insecurity are visible and growing in Australian cities. Transit-oriented development is underdeveloped relative to potential; density near transit corridors is restricted by zoning. Mixed-income development is minimal; new construction focuses on expensive units or inherited older stock. What Australia desperately needs is: eliminate single-family zoning in urban areas, streamline approvals for apartments, regulate foreign investment to prioritize local residents, reform negative gearing tax treatment, and invest in affordable housing. Without this, Australia will become increasingly expensive and unequal despite its wealth.`,
    issues: ['Restrictive single-family zoning', 'Affordability crisis in major cities', 'Investor speculation dominant', 'Foreign investment reducing local supply', 'Homelessness rising']
  },

  'New Zealand': {
    summary: `New Zealand's housing market has shifted from relative affordability to acute crisis through restrictive planning, speculation-focused investment, and immigration without supply expansion, particularly in Auckland and Wellington. Auckland housing costs have tripled in 15 years and are now among world's least affordable; rents consume 25-35% of incomes. Homeownership rates are declining as properties become investment vehicles; younger cohorts face severe affordability barriers. The rental market has become increasingly investor-owned and expensive; property investors dominate ownership. Zoning is restrictive: single-family zoning dominates, apartment development is restricted by planning rules and neighborhood opposition. Building approval processes are complex and expensive; environmental and consultation requirements are substantial. Construction is insufficient to match demand, particularly for affordable housing. Real estate investment is intense: property investors, institutional funds, and international investors drive speculation; overseas investors from China and elsewhere accumulate property. Homelessness and housing insecurity are visible and rising in Auckland and Wellington. Transit-oriented development is theoretically encouraged but restricted in practice by zoning; apartments near transit are minimal. Mixed-income development is minimal; new construction focuses on expensive units. What New Zealand needs urgently is: liberalize apartment zoning in major cities, streamline approvals, regulate foreign investment, reform tax treatment of property investment (especially negative gearing), and invest in affordable housing. Without this, New Zealand will replicate Australian crisis with growing homelessness despite small, wealthy nation status.`,
    issues: ['Restrictive zoning in major cities', 'Affordability crisis acute', 'Investor speculation dominant', 'Foreign investor concentration', 'Homelessness rising']
  },

  'Pakistan': {
    summary: `Pakistan's housing market reflects rapid urbanization, low incomes, and weak institutions creating inadequate supply in major cities and vast informal settlement growth. Karachi and Lahore face housing shortages: formal apartments are expensive and inadequate; informal settlements house millions with precarious conditions. Homeownership formally is around 50%, but including informal self-built housing, informal ownership is high though with zero legal security. Formal rental markets are small and entirely informal; written agreements and tenant protections are minimal. Zoning regulations are theoretically permissive but planning capacity is minimal and corruption is endemic. Construction activity is occurring in major cities with some foreign investment, but is concentrated in luxury apartments; affordability housing is minimal. Real estate speculation has accelerated in growth cities: domestic investors and foreign interest drive property investment. Homelessness is visible and substantial: informal settlements (katchi abadi) house millions with precarious conditions. Transit-oriented development is minimal despite major transit projects. Mixed-income development is almost nonexistent; formal construction focuses on luxury. What Pakistan needs is land titling systems that function, affordable housing investment, informal settlement upgrade programs, rental market regulation, and acceleration of transit-oriented development. Without this, housing insecurity will deepen as urbanization continues.`,
    issues: ['Informal settlements house millions', 'Land titling system absent', 'Formal housing inadequate', 'Luxury-focused construction', 'Affordable housing scarce']
  },

  'Bangladesh': {
    summary: `Bangladesh's housing market serves the world's densest major country with radically inadequate formal supply forcing hundreds of millions into informal settlements. Dhaka and other major cities face severe housing shortages: formal apartments are expensive and inadequate; informal slums house millions. Homeownership formally is minimal, around 25%, while informal ownership (self-built with zero security) is extremely high. Formal rental markets are small; informal rentals house most urban renters with zero protections. Zoning regulations exist but planning capacity is minimal and corruption is endemic. Construction of formal apartments is occurring but concentrated in luxury for wealthy; middle and lower-income construction is almost nonexistent. Real estate speculation exists in growth areas but is modest given low incomes. Homelessness and housing insecurity are endemic: slums house over 3 million in Dhaka alone, with precarious conditions. Transit-oriented development is minimal despite rapid transit expansion. Mixed-income development is almost nonexistent. What Bangladesh needs is massive investment in affordable housing, land titling and registry systems, slum upgrade programs, rental market formalization, and informal settlement regularization. Without this, housing will remain a constraint on poverty reduction and health outcomes.`,
    issues: ['Slums house millions in major cities', 'Formal housing inadequate', 'Land titling system absent', 'Informal rentals predominant', 'Affordable construction minimal']
  },

  'Afghanistan': {
    summary: `Afghanistan's housing sector is severely disrupted by ongoing conflict, governance instability, and economic collapse, making normal real estate markets impossible. Kabul has seen massive population displacement, informal settlement expansion, and inadequate housing supply even as conflict has created refugee movements. Formal homeownership is minimal; most people occupy informal dwellings with zero legal security. The rental market functions informally; rents are often paid in kind and tenant protections are nonexistent. Zoning regulations are theoretical; cities develop chaotically around informal settlements. Construction is minimal and sporadic, driven by humanitarian organizations rather than market. Real estate speculation is virtually nonexistent due to extreme insecurity. Homelessness is endemic: internally displaced persons, refugees, and urban poor live in temporary shelters, informal settlements, and precarious conditions. Transit-oriented development does not exist; basic infrastructure is inadequate. What Afghanistan has is housing as humanitarian crisis where formal markets cannot function. Until political stability improves and conflict ends, housing will remain emergency housing for displaced populations. International humanitarian organizations provide most housing solutions for displaced and vulnerable.`,
    issues: ['Conflict prevents market function', 'Displacement massive', 'Informal settlements only housing', 'No functioning land system', 'Humanitarian dependency']
  },

  'Iran': {
    summary: `Iran's housing market reflects oil-dependent economy with Tehran vastly dominating, state involvement in housing provision, and international sanctions constraining construction materials and financing. Tehran housing costs have tripled in a decade despite economic stagnation; rents consume 30-40% of formal incomes. Homeownership rates are around 65%, but younger cohorts face severe affordability barriers. The rental market is substantial and increasingly formalized; tenant protections are reasonable by regional standards. Zoning theoretically allows density in Tehran, but development is slow due to complex financing and import constraints. Building approval processes are bureaucratic; construction proceeds slowly. Construction costs are elevated by import restrictions; foreign materials are difficult to obtain. Real estate speculation is present but constrained by capital controls and sanctions; some speculation occurs among wealthy who can move assets. Homelessness is visible in Tehran despite oil wealth; informal settlements exist in peripheral areas. Transit development in Tehran is occurring but slow. Mixed-income development is limited by market dynamics. What Iran needs is sanctions relief to enable construction material imports, deregulation of housing supply, and deliberate affordable housing policy. Without these, affordability will continue deteriorating despite oil wealth being technically available for housing investment.`,
    issues: ['Tehran affordability crisis', 'Import constraints limit construction', 'Informal settlements growing', 'Limited mixed-income development', 'Sanctions impact development']
  },

  'Israel': {
    summary: `Israel's housing market is characterized by rapid construction activity but constrained affordability, driven by geopolitical tensions, immigration waves, and land scarcity. Tel Aviv and Jerusalem rents consume 25-35% of incomes and housing costs are among world's least affordable despite being wealthy nation; homeownership is increasingly inaccessible. Homeownership rates are around 65%, but this reflects family wealth and inherited property. The rental market is substantial and increasingly formalized; tenant protections are reasonable by regional standards. Zoning regulations theoretically allow density, but development is constrained by land allocation issues and building approval processes. Building approval is complex and slow; environmental and security-related consultations add time. Construction is substantial, particularly in Jerusalem and settlements, but is driven by geopolitical strategy rather than housing supply logic. Real estate investment is present; property is viewed as shelter and investment. Homelessness is visible in major cities but less prominent than in some wealthy nations. Transit-oriented development is occurring in Tel Aviv and Jerusalem but remains underdeveloped relative to potential. Mixed-income development is limited; new construction focuses on market rates. What Israel needs is acceleration of housing supply outside geopolitical conflict zones, liberalization of apartment development in dense corridors, and affordable housing investment. Without this, affordability will continue deteriorating despite construction activity.`,
    issues: ['Affordability crisis in major cities', 'Geopolitical constraints on development', 'Land allocation issues', 'Limited affordable construction', 'Homelessness visible']
  },

  'Palestine': {
    summary: `Palestine's housing market is constrained by political conflict, military occupation, and governance instability that prevents normal real estate market function. Gaza and West Bank face severe housing shortages: Israeli movement restrictions, military operations, and inadequate Palestinian governance prevent organized housing development. Homeownership formally is around 60-70%, but security tenure is uncertain due to political conflict. The rental market is small and informal; protections are minimal. Zoning regulations are complex: Israeli authority over Palestinian areas constrains development; Palestinian authorities have limited capacity. Construction is constrained by military restrictions, material shortages, and governance challenges. Real estate speculation is minimal due to political insecurity; property is viewed as shelter with uncertain security. Homelessness is visible in refugee camps and urban areas; displacement from conflict is constant. Transit-oriented development does not exist; basic infrastructure is inadequate. What Palestine needs is political resolution that enables governance and investment in housing. Until conflict stabilizes and Palestinian self-determination is resolved, housing will remain inadequate and insecure.`,
    issues: ['Political conflict prevents market function', 'Military occupation restricts development', 'Displacement ongoing', 'Infrastructure inadequate', 'Humanitarian dependency']
  },

  'Iraq': {
    summary: `Iraq's housing market is severely disrupted by conflict, governance instability, and reconstruction challenges, making normal real estate function difficult. Baghdad and other major cities face housing shortages and displacement: conflict-related destruction remains, reconstruction is slow, and housing supply is inadequate. Homeownership formally is high but security tenure is uncertain due to conflict and governance weakness. The rental market is small and informal; protections are minimal. Zoning regulations are weak; cities develop chaotically. Construction is occurring through reconstruction efforts and some private investment, but is concentrated in secure areas and wealthy enclaves. Real estate speculation is minimal due to political instability; property values are uncertain. Homelessness and displacement are visible and substantial: internally displaced persons from conflict and sectarian violence require housing. Transit-oriented development does not exist; infrastructure is inadequate. What Iraq needs is political stability that enables investment and reconstruction, governance that can manage housing development, and international support for housing projects. Until conflict stabilizes, housing will remain inadequate and insecure.`,
    issues: ['Conflict-related destruction ongoing', 'Displacement massive', 'Governance capacity weak', 'Infrastructure inadequate', 'Reconstruction slow']
  },

  'Jordan': {
    summary: `Jordan's housing market faces pressure from Syrian refugee influx, limited economic resources, and rapid urbanization, creating supply constraints particularly in Amman. Amman rents have risen sharply as refugee populations increased; formal housing is inadequate for demand. Homeownership rates are around 75%, but younger cohorts face affordability barriers. The rental market has expanded substantially to absorb refugee populations; many Syrians rent in informal markets with zero protections. Zoning regulations theoretically allow density, but development capacity is limited by economic resources. Building approval processes are slow; construction material shortages and cost inflation constrain activity. Construction is occurring in Amman with some international investment, but insufficient to match refugee-driven demand. Real estate speculation is modest; property is viewed as shelter and investment. Homelessness is visible among refugee populations and urban poor. Transit-oriented development is minimal; public transport is limited. Mixed-income development is constrained by market and resource limitations. What Jordan needs is international support for refugee housing, investment in apartment construction, and deliberate affordable housing policy. Without this, housing insecurity will deepen among both refugee and local populations.`,
    issues: ['Syrian refugee influx strains supply', 'Affordability declining', 'Informal refugee housing inadequate', 'Limited construction capacity', 'International support dependent']
  },

  'Cambodia': {
    summary: `Cambodia's housing market reflects rapid urbanization, low incomes, and post-conflict recovery challenges, with Phnom Penh facing acceleration of formal development alongside vast informal settlement growth. Phnom Penh rents are rising as foreign investment increases; formal housing is expensive and inadequate for low-income demand. Homeownership formally is around 50%, including informal self-built housing; formal ownership is minimal. The rental market is small and informal; written agreements and protections are minimal. Zoning regulations theoretically allow density, but planning capacity is weak and corruption is endemic. Construction of formal apartments is occurring in Phnom Penh with Chinese and other foreign investment, but is concentrated in luxury; affordability housing is minimal. Real estate speculation has accelerated: foreign investor interest in Cambodia's growth trajectory drives property acquisition; this removes units from local supply. Homelessness is visible; informal settlements house populations with precarious conditions. Transit-oriented development is minimal despite rapid urban growth. Mixed-income development is almost nonexistent; formal construction focuses on luxury. What Cambodia needs is land titling systems, affordable housing investment, informal settlement regularization, and regulation of foreign investment to prioritize local housing supply. Without this, growth will bypass ordinary Cambodians and concentrate wealth.`,
    issues: ['Foreign investor speculation', 'Informal settlements substantial', 'Luxury-focused construction', 'Affordability declining', 'Land titling system weak']
  },

  'Laos': {
    summary: `Laos's housing market reflects rapid urbanization, low incomes, and weak governance creating insufficient formal housing supply in Vientiane and other cities. Vientiane rents are rising as foreign investment increases and urbanization accelerates; formal housing is expensive and inadequate. Homeownership formally is around 55%, but including informal self-built housing, informal ownership is extremely high though with zero legal security. The rental market is small and entirely informal; protections are nonexistent. Zoning regulations are weak; planning capacity is minimal. Construction of formal apartments is occurring in Vientiane with some foreign investment, but concentrated in luxury; affordability housing is minimal. Real estate speculation is emerging as investors discover Laos growth potential; foreign investor interest is increasing. Homelessness is less visible than in denser countries but housing insecurity is present. Transit-oriented development does not exist; basic infrastructure is inadequate. Mixed-income development is almost nonexistent. What Laos needs is land administration systems, affordable housing investment, informal settlement upgrade programs, and regulation of foreign investment. Without this, housing will remain inadequate for rapid urbanization.`,
    issues: ['Rapid urbanization outpacing supply', 'Informal settlements substantial', 'Luxury-focused construction', 'Affordability declining', 'Land system weak']
  },

  'Myanmar': {
    summary: `Myanmar's housing market is disrupted by political instability and military conflict following the coup, constraining investment and development particularly in Yangon. Yangon housing costs have risen despite conflict; formal housing is expensive and inadequate. Homeownership formally is high but security tenure is uncertain due to political conflict and governance weakness. The rental market is small and informal; protections are minimal. Zoning regulations are weak; planning capacity is limited and destabilized by conflict. Construction is constrained by conflict, sanctions, and governance instability; investment has been deterred. Real estate speculation is minimal due to political insecurity; property values are uncertain. Homelessness and internal displacement are visible due to conflict. Transit-oriented development does not exist; infrastructure is inadequate. What Myanmar needs is political stability that enables investment and governance. Until conflict stabilizes, housing will remain inadequate and investment will be deterred.`,
    issues: ['Political instability disrupts markets', 'Conflict constrains development', 'Governance weak', 'Investment deterred', 'Informal settlements dominate']
  },

  'Nepal': {
    summary: `Nepal's housing market reflects low incomes, rapid urbanization in Kathmandu, and earthquake-reconstruction challenges creating housing supply constraints. Kathmandu rents are rising as internal migration accelerates; formal housing is expensive and inadequate. Homeownership formally is high, around 75%, including self-built stock, but formal ownership is minimal. The rental market is small and entirely informal; protections are nonexistent. Zoning regulations are weak; planning capacity in Kathmandu is limited. Construction is occurring but insufficient to match demand; post-earthquake reconstruction is still ongoing. Real estate speculation is emerging as foreign and domestic investors recognize Kathmandu's growth potential. Homelessness and housing insecurity are visible in Kathmandu among rural migrants. Transit-oriented development is minimal; public transport is limited. Mixed-income development is almost nonexistent. What Nepal needs is land titling systems that function, affordable housing investment, post-earthquake reconstruction completion, and development of transit corridors. Without this, housing will remain inadequate for rapid urbanization.`,
    issues: ['Rapid urbanization outpacing supply', 'Post-earthquake reconstruction incomplete', 'Informal rental markets predominant', 'Affordability declining', 'Land system weak']
  },

  'Mongolia': {
    summary: `Mongolia's housing market reflects rapid urbanization concentration in Ulaanbaatar driven by rural-urban migration, resource extraction economy, and Soviet-era legacy creating supply constraints and affordability pressure. Ulaanbaatar housing costs have tripled in a decade; rents consume 25-30% of formal incomes. Homeownership rates are relatively high (around 70%), driven by Soviet-era privatization and cultural preference, but younger cohorts face affordability barriers. The rental market is small and increasingly formalized; supply is inadequate to match migration demand. Zoning regulations theoretically allow density, but development approval is slow. Building costs are reasonable, but construction activity is insufficient to match demand. Construction is concentrated in apartment blocks for middle and upper-income; affordability housing is minimal. Real estate speculation is emerging as investors recognize Mongolia's growth potential; some foreign investment is occurring. Homelessness is visible in Ulaanbaatar despite official minimization; informal settlements (ger districts) are extensive and lack adequate services. Transit-oriented development is underdeveloped; public transport is limited. Mixed-income development is minimal. What Mongolia needs is acceleration of apartment construction in Ulaanbaatar, formalization of ger districts with services and security, and affordable housing policy. Without this, rural-urban migration will continue creating housing insecurity.`,
    issues: ['Ulaanbaatar concentration excessive', 'Ger district settlements inadequate', 'Affordability rising', 'Insufficient apartment construction', 'Informal settlements predominant']
  },

  'Papua New Guinea': {
    summary: `Papua New Guinea's housing market is characterized by very low formal housing stock, extreme informality, limited government capacity, and rapid urbanization in Port Moresby creating severe supply constraints. Port Moresby housing is expensive relative to incomes; formal apartments are inadequate and concentrated among wealthy expatriates. Homeownership formally is minimal, around 15-20%; most people occupy informal self-built structures with zero legal security or services. The rental market is small and entirely informal; protections are nonexistent. Zoning regulations are weak; planning capacity is minimal. Construction is very limited, concentrated in luxury housing for expatriates and wealthy; affordability housing is almost nonexistent. Real estate speculation is minimal due to insecurity and limited capital availability. Homelessness and housing insecurity are endemic: vast informal settlements in Port Moresby lack adequate services or security; street populations are visible. Transit-oriented development does not exist; basic infrastructure is inadequate. What Papua New Guinea needs is massive investment in housing and infrastructure, land administration systems, and governance capacity. Without international support and resource revenue directed to housing, the situation will deteriorate.`,
    issues: ['Formal housing stock minimal', 'Informal settlements predominant', 'No land administration system', 'Affordability minimal', 'Infrastructure inadequate']
  },

  'Fiji': {
    summary: `Fiji's housing market reflects small island economy constraints, limited formal development capacity, and climate vulnerability creating housing challenges particularly for lower-income populations. Suva and other urban centers have rising housing costs as tourism and development increase; formal housing is expensive and inadequate. Homeownership rates are relatively high (around 70%), reflecting cultural attachment to land and family housing, but younger cohorts face affordability barriers. The rental market is small and increasingly formalized in urban areas; supply is inadequate. Zoning regulations exist but enforcement is weak; planning capacity is limited by small economy scale. Construction activity is modest; development approval processes are bureaucratic. Real estate speculation is emerging among wealthier Fijians and foreign investors purchasing vacation properties. Homelessness is visible in urban centers; informal settlements exist in peripheral areas. Transit-oriented development does not exist; public transport is limited. What Fiji needs is affordable housing investment, improved land administration, development of transit-oriented communities in growth areas, and climate resilience in housing policy. Without this, housing affordability will continue declining as development pressure increases.`,
    issues: ['Limited formal housing stock', 'Island economy constraints', 'Affordability rising', 'Climate vulnerability', 'Speculation by foreign investors']
  }
}

async function main() {
  console.log('🚀 Starting real estate & housing summary generation (Countries 41-80)\n')
  console.log(`Processing ${countries.length} countries...\n`)

  let successCount = 0
  let errorCount = 0

  for (const country of countries) {
    console.log(`\n${'='.repeat(80)}`)
    console.log(`Processing: ${country.name}`)
    console.log('='.repeat(80))

    try {
      const summaryData = realEstateSummaries[country.name]
      const stats = countryData[country.name]

      if (!summaryData) {
        console.log(`⏭️  Skipping ${country.name} - no real estate data available`)
        errorCount++
        continue
      }

      console.log(`🏠 Saving real estate & housing summary for ${country.name}...`)

      // Save to database
      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: country.name,
            type: 'country',
            category: 'realestate',
          },
        },
        update: {
          summary: summaryData.summary,
          issues: JSON.stringify(summaryData.issues),
          topStories: JSON.stringify([]),
          storyCount: 0,
          updatedAt: new Date(),
        },
        create: {
          name: country.name,
          type: 'country',
          country: country.name,
          lat: country.lat,
          lng: country.lng,
          category: 'realestate',
          summary: summaryData.summary,
          issues: JSON.stringify(summaryData.issues),
          topStories: JSON.stringify([]),
          storyCount: 0,
        },
      })

      console.log(`✅ Saved real estate summary for ${country.name}`)
      console.log(`   - Summary length: ${summaryData.summary.length} characters`)
      console.log(`   - Issues: ${summaryData.issues.length}`)
      successCount++
    } catch (error) {
      console.error(`❌ Error saving real estate summary for ${country.name}:`, error)
      errorCount++
    }
  }

  console.log('\n' + '='.repeat(80))
  console.log('✅ COUNTRIES 41-80 COMPLETE!')
  console.log('='.repeat(80))
  console.log(`✅ Successfully processed: ${successCount} countries`)
  console.log(`❌ Errors: ${errorCount} countries`)
  console.log(`📊 Total: ${countries.length} countries`)
  console.log('='.repeat(80))
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
