import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const writeups = [
  {
    name: "Argentina",
    lat: -38.4161,
    lng: -63.6167,
    summary: `# Argentina - Politics

You know, I've been watching Javier Milei with a sort of horrified fascination—the kind you get when someone actually does what they said they'd do in an election campaign. Here's this fellow who came to power with a chainsaw, literally a chainsaw, promising to slash the state, and by God, he's doing it. I remember being in Buenos Aires years ago, and everyone was talking about how Argentina had everything—the resources, the education, the culture—and yet kept finding new ways to implode. Well, Milei's bet is that the problem was always the state itself. He's a proper libertarian, the sort who thinks Milton Friedman was a bit soft, and he's been given the keys to a country that's spent a century experimenting with every other economic model. The October midterms gave him a stunning mandate—41.5% in Buenos Aires province, beating the Peronists in their own heartland. But here's what's really extraordinary: Donald Trump's administration has just offered him a $40 billion bailout package. Think about that for a moment. Argentina, which has defaulted on its debts more times than I've had hot dinners, is being treated by Washington as a geopolitical priority. This isn't just about economics anymore—it's about America reshaping South American politics in its own libertarian image.

## The Big Issue 1: The Trump-Milei Alliance and the $40 Billion Gamble

Now, this is where it gets absolutely fascinating from a geopolitical perspective. Trump posting on Truth Social that Milei is "doing a wonderful job" isn't just cheerleading—it's strategic signaling. The bailout package includes a $20 billion currency swap that's already signed and a proposed $20 billion debt investment facility. I've spent enough time around development economics to know that this kind of money doesn't flow without strings, and the string here is ideological alignment. Washington is essentially underwriting Milei's libertarian experiment, betting that if it succeeds, it provides a template for rolling back the state across Latin America. The implications are enormous. Argentina has traditionally been a swing state in regional politics—sometimes aligned with Washington, sometimes with Venezuela and the leftist bloc. By locking Argentina into this financial embrace, the Trump administration is trying to ensure it stays in the American orbit. But here's the risk: if Milei's experiment fails—if the social pain becomes unbearable and Argentines revolt—you'll have $40 billion of American money sunk into a political disaster. And that money is flowing while China watches carefully, having spent years building relationships across South America through Belt and Road investments. This is genuinely a new Cold War playing out in the Southern Cone, and Argentina is the prize.

## The Big Issue 2: The Post-Victory Reality—Tax and Labor Reform

Winning the midterms was the easy part, relatively speaking. Now Milei has to actually govern, and that means pushing through tax and labor reforms that will make Margaret Thatcher look like a moderate. I've been reading the IMF program requirements—the Fund approved $20 billion but wants structural reforms in return. We're talking about dismantling labor protections that have existed since Perón, restructuring a tax system that's Byzantine in its complexity, and doing it all while inflation is still running at devastating levels, even if it's slowing. Here's what keeps me up at night about this: Milei's approval rating has already dropped from 57% in December to 45% in October. That's a 12-point slide in less than a year, and he's only just beginning the really painful reforms. The problem is that for all the talk of "shock therapy," the Argentine economy is actually contracting. Real wages are down, consumption is falling, and you have millions of people who were already living hand-to-mouth being asked to tighten their belts further. The political calculation is that if he can show results—stable currency, lower inflation, economic growth—by 2027, he'll be vindicated. But two years is a long time when people can't afford food. And labor reform in Argentina isn't some technocratic exercise—it's attacking the organizational power of the unions, which have been the backbone of Argentine politics for 80 years.

## The Big Issue 3: The Peronist Identity Crisis

The fascinating subplot here is what's happening to Peronism, which has dominated Argentine politics for generations. Getting 31% in a midterm when you're the main opposition is, frankly, catastrophic for the Peronists. They lost Buenos Aires province, which is their heartland—imagine Labour losing London or the Democrats losing California. What you're seeing is an ideology that was built around state intervention, industrial policy, and social protection running headlong into a reality where those policies produced 200% inflation and recurring economic collapse. I've always been struck by how Peronism could be almost anything—right-wing under Menem, left-wing under the Kirchners—but the one constant was the belief that the state should be the protagonist in economic life. Well, Milei is offering the exact opposite, and a plurality of Argentines are saying "yes, please." The intellectual crisis this creates for the left in Argentina is profound. They can't just say "Milei is being too harsh"—everyone knows the previous system wasn't working. So what do they offer instead? They haven't figured that out yet, and until they do, Milei has the political space to push through transformations that would normally trigger revolution.

## The International Angle

The ripple effects of Argentina's transformation are being felt across the continent. In Brazil, Lula is watching nervously as a libertarian model takes hold right next door. In Chile, where they're about to elect a new president, the debate between state intervention and free markets is front and center, with Argentina serving as a live experiment. The Chinese are particularly worried—they'd invested heavily in Argentina as part of their South American strategy, and now find themselves sidelined by the Trump-Milei alliance. For the IMF, this is both validation and risk: validation that their structural adjustment programs can work, but risk that if this goes wrong, it damages their credibility for a generation. And for Europe, which has its own debates about economic reform and state spending, Argentina provides a fascinating test case. Can you actually shrink a state that's metastasized over decades? Watch this space—the answer matters far beyond Buenos Aires.

## The Bottom Line

Milei has political momentum, American backing, and a mandate for change—but he's also asking one of the world's most politically mobilized populations to accept pain in exchange for a future that's still theoretical. The October victory bought him time, but probably only two years. If inflation isn't under control and growth hasn't returned by 2027, no amount of American money will save him from electoral reckoning. This is genuinely one of the most significant political experiments of our time.`,
    issues: ["The Trump-Milei Alliance and the $40 Billion Gamble", "The Post-Victory Reality—Tax and Labor Reform", "The Peronist Identity Crisis"]
  },
  {
    name: "Bolivia",
    lat: -16.2902,
    lng: -63.5887,
    summary: `# Bolivia - Politics

Here's something remarkable: Bolivia just ended nearly two decades of socialist governance, and it happened not with a bang but with an implosion. I've been following the Morales-Arce feud for years, and it's been like watching a very slow political murder-suicide. Two men who supposedly represented the same movement, the same indigenous uprising that transformed Bolivian politics, tearing each other apart with such venom that they destroyed their own party and handed power to the opposition. Rodrigo Paz was sworn in as president on November 8th, promising "capitalism for all," which in Bolivia—where the state has run everything from lithium mines to the airline—is genuinely revolutionary language. But here's what fascinates me: this wasn't a rejection of the left by the voters so much as the left rejecting itself. The MAS party didn't even get a candidate into the runoff. It's as if Labour in Britain or the Democrats in America simply disintegrated from internal warfare. And now Bolivia faces its worst economic crisis in 40 years, with 20% inflation, fuel shortages, and a dollar shortage that's crippling trade. The new president inherits a poisoned chalice, but also an opportunity to rebuild Bolivian politics from scratch.

## The Big Issue 1: The Morales-Arce Suicide Pact

I've seen political feuds before, but this one was truly epic in its destructiveness. Evo Morales was president for nearly 14 years, became the face of indigenous politics across South America, and then couldn't let go. Luis Arce was his finance minister, the technocrat who made the economy work, and when he became president himself, Morales expected him to be a placeholder. Instead, Arce tried to govern, and the split became total war. You had a June 2024 coup attempt—and the twist is that Morales supporters accused Arce of staging his own coup to gain sympathy. Then in October, there was an alleged assassination attempt on Morales, which he blamed on Arce. The whole thing reads like a Gabriel García Márquez novel, except it's real and it destroyed a political movement that had reshaped Bolivia. What's particularly striking is how the judicial system got weaponized. Authorities enforced Morales' ineligibility for a fourth term, he claimed it was persecution, and his supporters blockaded roads in protest. The blockades turned deadly, and when police finally cleared them in November, it became clear Morales' power had waned. But by then, the damage was done. The MAS party, which had governed Bolivia for 19 years and genuinely improved millions of lives, tore itself apart over personalities rather than principles. It's a cautionary tale about what happens when movements become cults of personality.

## The Big Issue 2: Paz's "Capitalism for All" Challenge

Now, Rodrigo Paz faces what might be the most difficult political-economic transition in South America. He's promising market reforms in a country where the state has been the protagonist in economic life for two decades, where indigenous communities expect the government to redistribute resource wealth, and where the previous model—however flawed—did lift millions out of poverty. The economic numbers are genuinely frightening: 20% inflation, chronic fuel shortages, a dollar shortage that's strangling imports, and according to some analysts, the worst crisis in 40 years. I spent time in La Paz years ago, and even then, the altitude made everything difficult—imagine trying to run an economy at 4,000 meters when you can't get fuel to transport goods or dollars to pay for imports. Paz's "capitalism for all" slogan is clever—it suggests markets without inequality, growth without exploitation—but the reality will be brutal. He'll need to cut subsidies that Bolivians have relied on for years, attract foreign investment to a country known for nationalizing assets, and reform labor laws without triggering the kind of mass protests that have toppled Bolivian governments repeatedly. The lithium deposits—Bolivia has some of the world's largest reserves—should be an economic lifeline, but developing them requires exactly the kind of foreign capital and technical expertise that socialist nationalism kept out. This is a genuine test of whether a country can pivot from resource nationalism to market economics without social explosion.

## The Big Issue 3: The Indigenous Movement at a Crossroads

This is the subplot that doesn't get enough attention: what happens to Bolivia's indigenous movement now that the MAS has collapsed? Morales rose to power on the back of a genuine social revolution—indigenous Bolivians, who had been marginalized for 500 years, taking control of their own country. It was powerful, it was historic, and it reshaped not just Bolivia but indigenous politics across the Americas. But the movement became inseparable from Morales personally, and when he refused to step aside, he took the movement down with him. The question now is whether indigenous political power can survive outside the MAS framework. There are younger indigenous leaders, different models of representation, but they're fragmented and weak. Meanwhile, Paz represents a return to more traditional, mestizo-dominated politics. The risk is that Bolivia's indigenous majority—and it is a majority, Bolivia is one of the few countries in the Americas where indigenous people are the demographic majority—becomes politically disenfranchised again. That would be not just a tragedy but a powder keg. Bolivia has a history of mass mobilizations, road blockades that can shut down the entire country, and social movements that have overthrown governments. If indigenous Bolivians conclude that electoral politics has failed them, they might return to the streets—and this time, there's no MAS to channel that energy.

## The International Angle

Bolivia's transition matters far beyond its borders. For the United States, it's a relief—the MAS government was aligned with Venezuela and increasingly with China, and Paz promises a more pragmatic foreign policy. For China, it's a setback: they'd invested heavily in Bolivia as part of their South American strategy, particularly around lithium, and now face an uncertain future. For leftist governments across Latin America—Lula in Brazil, Petro in Colombia—Bolivia is a warning about what happens when personality politics destroys institutional movements. And for indigenous movements globally, Bolivia's experience raises hard questions: can indigenous political power be sustained, or does it inevitably either compromise with market economics or collapse into irrelevance? The lithium question looms largest. As the world transitions to electric vehicles, Bolivia's lithium reserves become strategically crucial. But extracting them requires the kind of foreign investment and technical partnerships that socialist nationalism rejected. If Paz can thread this needle—extracting lithium while ensuring Bolivians benefit—he could transform the country. If he can't, Bolivia remains poor despite sitting on riches.

## The Bottom Line

Bolivia just experienced one of the most complete political transformations in modern South American history, and it happened not because voters rejected the left but because the left committed political suicide. Paz has an extraordinary opportunity to rebuild Bolivian politics and economics, but he's working with an economy in crisis, a population exhausted by political warfare, and the ghosts of two decades of socialist governance. The next two years will determine whether Bolivia can navigate a market transition without social explosion—or whether the indigenous majority takes to the streets again.`,
    issues: ["The Morales-Arce Suicide Pact", "Paz's \"Capitalism for All\" Challenge", "The Indigenous Movement at a Crossroads"]
  },
  {
    name: "Brazil",
    lat: -14.2350,
    lng: -51.9253,
    summary: `# Brazil - Politics

Brazil in November 2025 is absolutely fascinating—you have President Lula hosting COP30 in Belém, positioning Brazil as a climate leader, while simultaneously dealing with coup plot investigations involving his predecessor and alleged assassination plans against himself. It's vintage Brazil, really: the visionary internationalism existing alongside the darkest political intrigue. I remember visiting Brazil during the Dilma impeachment, and everyone was talking about how polarized the country had become. Well, it's gotten worse, much worse. Lula announced in October that he'll run for a fourth term in 2026—he's 80 years old now—and police have arrested military officers for allegedly plotting to kill him, Vice President Alckmin, and Supreme Court Justice Alexandre de Moraes back in 2022 to prevent him taking office. At the same time, they've accused Bolsonaro and 36 others of planning a coup. This isn't normal democratic politics; this is a country where the political class literally tried to murder each other and overthrow constitutional order. Yet Lula is hosting global leaders at COP30, discussing multilateral climate solutions and deforestation targets, as if Brazil were Sweden rather than a country where the previous president allegedly planned a coup. That tension—between Brazil's aspirations and its reality—defines everything happening there now.

## The Big Issue 1: The Coup Plot and Democratic Resilience

Let's talk about what's actually been uncovered, because it's genuinely shocking. Police investigations have revealed that Bolsonaro and dozens of co-conspirators, including former ministers and military officers, allegedly planned to prevent Lula from taking office after the 2022 election. This wasn't just loose talk—they arrested four military officers and a police officer for allegedly plotting to assassinate Lula, Alckmin, and Supreme Court Justice Moraes. If these allegations are true, and they come from serious police investigations not political witch hunts, then Brazil came remarkably close to a violent overthrow of its democratic system. Think about this in comparative terms: imagine if Trump and senior military officials had been credibly accused of plotting to assassinate Biden, Harris, and Chief Justice Roberts. That's the scale of what's being alleged. The Supreme Court has become a lightning rod in all this. Justice Moraes has been aggressive in prosecuting Bolsonaro and his allies, which the right sees as political persecution and the left sees as defending democracy. In November, a man detonated explosives and killed himself in front of the Supreme Court after allegedly making threats—that's the level of tension. What strikes me is how Brazil's institutions have held. The Supreme Court, the electoral system, the Federal Police—they've withstood enormous pressure and continued functioning. But there's a deeper problem: roughly half the country believes Bolsonaro was defending Brazil from communism, and the other half believes he tried to destroy democracy. How do you govern when your population can't agree on basic facts?

## The Big Issue 2: Lula at 80—Running Again or Running on Empty?

Lula announcing he'll seek a fourth term raises profound questions about Brazilian politics. Here's someone who was president from 2003-2010, left office as one of the most popular leaders in the world, got imprisoned on corruption charges that were later annulled, and returned to power in 2022. He'll be 81 at the next election. Now, I'm not ageist—Biden and Trump both ran at similar ages—but it does suggest a concerning absence of succession planning on the Brazilian left. Where are the younger leaders? Why is the Workers' Party still so dependent on Lula's personal charisma? The policy challenges are enormous. Brazil's economy has been stagnant for a decade—they call it the "lost decade"—and Lula has struggled to generate growth while maintaining the social programs his base expects. He's trying to thread an impossible needle: keeping the left happy with redistribution, keeping markets confident with fiscal responsibility, and keeping the center-right from defecting entirely. His approval ratings are moderate, not terrible but not strong, and he faces a potentially resurgent right in 2026 if Bolsonaro's legal problems don't disqualify him (or if they do, someone like former São Paulo governor Tarcísio de Freitas steps in). There's also the question of what Lula actually wants to achieve in a fourth term beyond consolidating democratic institutions. His first two terms were transformative—lifting millions from poverty, expanding social programs, putting Brazil on the world stage. His third term has been more defensive, more about preserving democracy than advancing a vision. A fourth term risks being purely about him, about legacy protection rather than governing.

## The Big Issue 3: Climate Leadership and the Amazon

Here's where it gets interesting from an international perspective: Lula is hosting COP30 in Belém, positioning Brazil as indispensable to solving climate change. And he's right—the Amazon is genuinely crucial to global climate stability. Under Bolsonaro, deforestation increased dramatically as he effectively encouraged illegal logging and mining. Lula campaigned on reversing this, and he's had some success—deforestation has decreased under his government. But here's the complexity: the Brazilian Amazon is home to millions of people, many of them poor, who depend on extractive industries for their livelihoods. Telling them "you can't log, you can't mine, you need to preserve the forest for global climate" while they're struggling to eat doesn't go down well. Lula needs international funding to make forest preservation economically viable, but the sums required are enormous—we're talking tens of billions annually. At COP30, he's essentially telling the global north: "You want us to preserve the Amazon? Pay for it." Which is fair, actually. The historical responsibility for climate change lies overwhelmingly with industrialized nations, and if they want Brazil to forego economic development for global environmental benefits, they should compensate Brazil. But getting that money is politically difficult in Washington, Brussels, and London, especially when you're asking their taxpayers to send money to a country that's simultaneously dealing with coup plots and corruption scandals. The other challenge is implementation: even if Lula gets funding, he needs to control vast territories where government authority is weak and criminal networks are strong.

## The International Angle

Brazil's stability matters enormously to South America and beyond. It's the continent's largest economy, most populous country, and a key voice in multilateral forums. If Brazil descends into authoritarian politics or violent instability, the ripples would be felt globally. The relationship with China is particularly interesting—China is Brazil's largest trading partner, buying massive amounts of soybeans and iron ore, and has invested heavily in Brazilian infrastructure. The United States has traditionally seen Brazil as a key partner but has struggled to articulate a compelling counter-offer to Chinese investment. For Europe, Brazil is a crucial partner on climate but a frustrating one on trade—the EU-Mercosur deal has been negotiated for two decades without completion. And for global climate politics, Brazil's success or failure in protecting the Amazon while developing economically will determine whether developing nations believe they can achieve both goals simultaneously. If Brazil shows it's possible, it provides a model. If it fails, it reinforces the narrative that climate action requires perpetual poverty for the Global South.

## The Bottom Line

Brazil is simultaneously hosting a global climate summit and prosecuting coup plots, running on Lula's personal charisma while failing to develop new political leadership, and trying to preserve the Amazon while lifting millions from poverty. These tensions aren't sustainable indefinitely. Lula's fourth-term bid is either a bid for transformative climate leadership or an 80-year-old's refusal to let go. Probably both. The 2026 election will determine whether Brazil can move beyond Lula-Bolsonaro polarization or whether that's simply Brazil's reality now.`,
    issues: ["The Coup Plot and Democratic Resilience", "Lula at 80—Running Again or Running on Empty?", "Climate Leadership and the Amazon"]
  },
  {
    name: "Canada",
    lat: 56.1304,
    lng: -106.3468,
    summary: `# Canada - Politics

This is genuinely extraordinary: Canada, stable, boring, predictable Canada, just installed its first Prime Minister who has never held elected office. Mark Carney, the former Bank of England Governor—my former boss, in a sense, when I was in British politics—is now running Canada. He won the Liberal leadership in March with 86% of the vote after Trudeau's spectacular political collapse, and he's completely reshuffled Canadian politics. What's remarkable is how quickly this happened. In December 2024, Chrystia Freeland resigned as Finance Minister and Deputy PM, sending shockwaves through Ottawa. Six weeks later, Trudeau announced he was stepping down. Two months after that, Carney was Prime Minister. That's incredibly fast for a Westminster system, where leaders usually cling to power until the electorate physically removes them. The context is Trump—not just Trump's return to the White House, but his threats to impose massive tariffs and his truly bizarre suggestions about annexing Canada. Yes, annexing. The sitting US President suggested absorbing America's closest ally. Carney has positioned himself as the adult in the room who can manage Trump without either capitulating or triggering a trade war that would devastate Canada's economy. And it's working, politically: the Liberals went from trailing the Conservatives badly to leading in polls. November just saw Budget 2025 published, promising "generational investments," and the federal election is looming.

## The Big Issue 1: Managing Trump's Canada Obsession

I cannot adequately express how weird it is for a US President to talk about annexing Canada. This isn't 1812. This is 2025, and you have the leader of the free world suggesting that Canada should become the 51st state, or imposing tariffs to punish Canada for... being Canada, essentially. Trump's conduct has been genuinely destabilizing: threatening auto tariffs that would devastate Ontario's manufacturing base, suggesting Canada is a security threat to justify trade restrictions, and creating enormous uncertainty for Canadian businesses. What Carney brings is credibility in financial markets and, crucially, relationships in Washington that go beyond Trump. He was Governor of the Bank of Canada, then Bank of England, and he knows everyone who matters in international finance and central banking. When Carney speaks, markets listen—he has institutional credibility that politicians lack. His strategy appears to be: appear competent and non-threatening, maintain the relationship with the US at all costs, but quietly diversify Canada's economic relationships so it's less vulnerable to American whims. The problem is that 75% of Canadian exports go to the US. You can't diversify away from that level of dependency quickly. The Liberal polling revival is largely because Canadians rallied around their government when Trump made annexation noises. It's classic rally-round-the-flag stuff. But if Trump actually imposes devastating tariffs, Carney will own the economic consequences, and the rally effect will evaporate.

## The Big Issue 2: Governing Without Having Been Elected

This is genuinely unprecedented in Canadian history: a Prime Minister with no electoral experience whatsoever. Carney has never run for city council, provincial legislature, or Parliament. He's gone straight from central banking to running a G7 country. Now, he won a legitimate Liberal Party leadership election—86% is a landslide—but he hasn't faced voters in a general election yet. That's coming, probably within months. The constitutional position is solid: Canada is a Westminster system, you elect parties not leaders, and the Liberals hold enough seats to govern. But the political optics are challenging. The Conservatives will hammer him as an unelected technocrat, an establishment figure parachuted in without democratic legitimacy. And there's something to that critique, even if it's constitutionally invalid. What's interesting is that Carney's inexperience might actually be an asset right now. Trudeau became deeply unpopular—scandals, perceived arrogance, political fatigue after nearly a decade in power. Carney represents a clean slate, someone who isn't associated with Liberal Party baggage because he's literally never been part of the party apparatus. He can credibly say "I'm not a politician" because he isn't one. The risk is that inexperience shows when he needs to make hard political decisions. Central banking is highly technical but also insulated from direct political pressure. Governing is messy, requires compromise and coalition-building, and involves making decisions that will anger significant constituencies. Can Carney navigate that? We'll find out soon.

## The Big Issue 3: The Trudeau Legacy and Liberal Renewal

Justin Trudeau came to power in 2015 promising "sunny ways" and a progressive, feminist, multicultural vision of Canada. For a few years, he was the darling of international liberalism—the anti-Trump, the young progressive leader showing that left-wing politics could win. What happened? Several things: scandal fatigue (multiple ethics violations, the SNC-Lavalin affair), economic disappointment (housing became unaffordable for young Canadians, living standards stagnated), and political exhaustion (nearly a decade in power is a long time). Freeland's resignation in December was the death blow—she was seen as the competent one, the serious economist keeping things together, and when she publicly broke with Trudeau over economic policy, it signaled the government was imploding. Now Carney has to rebuild the Liberal brand while defending its legacy. That's tricky. He can't completely repudiate Trudeau without alienating the party base, but he also can't embrace everything Trudeau did without inheriting all the negatives. His Budget 2025, published in November, promises "generational investments," which sounds like continuity—more infrastructure spending, social programs, active government. But it's wrapped in language about economic management and fiscal responsibility, which is Carney's brand. The deeper question is whether Canadian liberalism has a compelling vision for the 2020s. The Trudeau-era progressivism—identity politics, climate leadership, refugee resettlement—mobilized some voters but alienated others. Can Carney articulate a liberalism that's economically competent, socially moderate, and capable of winning back working-class voters who've drifted to the Conservatives? That's the test.

## The International Angle

Canada punches above its weight internationally—G7 member, NATO partner, major trading nation—and how it's governed matters globally. The US relationship is obviously paramount, and Carney's ability to manage Trump will affect not just Canada but American allies everywhere who are trying to figure out how to deal with Trumpism. For Britain, where Carney is still well-known and respected from his Bank of England years, he's seen as a reassuring figure—someone who understands both North America and Europe and can bridge the two. For the EU, Canada is a crucial partner on trade and climate, and they'll be relieved to have someone in Ottawa they can work with after the chaos of the Trudeau-Trump era. The Arctic is becoming strategically crucial as climate change opens new shipping routes and Russia becomes more aggressive. Canada's Arctic sovereignty claims will be tested, and Carney will need to articulate a defense and security policy that's credible without being provocative. And in broader terms, Carney's success or failure will be watched by technocrats globally: can a highly competent non-politician actually govern effectively in our populist era? Or do you need political skills—the ability to inspire, to simplify, to emotionally connect—that technocrats typically lack?

## The Bottom Line

Mark Carney represents a genuine experiment in governance: putting a technocratic expert in charge of a major democracy during a period of enormous international turbulence. He has economic credibility, policy competence, and personal gravitas, but he's never fought an election campaign or managed a caucus revolt or made a decision that will make thousands of people hate him. The Trump factor has given him a political opening, but it's also created enormous economic uncertainty. If Carney can navigate the next year—manage Trump, deliver economic results, win the coming election—he'll have proven that expertise and competence still matter in politics. If he can't, it will reinforce the populist narrative that technocrats are out of touch and democracy needs politicians, not central bankers.`,
    issues: ["Managing Trump's Canada Obsession", "Governing Without Having Been Elected", "The Trudeau Legacy and Liberal Renewal"]
  },
  {
    name: "Chile",
    lat: -35.6751,
    lng: -71.5430,
    summary: `# Chile - Politics

Chile goes to vote this Sunday, November 16th, and it's genuinely one of the most consequential elections in South America right now. You have eight candidates, but it's really a battle between two visions: Jeannette Jara, a communist who was Boric's Labor Minister, leading with about 25% support, against José Antonio Kast, a far-right figure who's been compared to Bolsonaro and has similar support. And here's what makes it fascinating: it's the first election since 2012 where voting is compulsory. That massively expands the electorate and makes prediction nearly impossible, because you're forcing people to vote who've been politically disengaged for years. Gabriel Boric, the left-wing millennial president who came in promising transformation, is constitutionally barred from a consecutive second term, and his approval ratings are in the toilet—27% at one point, though some polls show 40%. The issues driving voters are crime and immigration, not exactly traditional left-wing strengths. Chile's right wing has fragmented into multiple candidates, which might split the vote, but it also might mean no one gets 50% in the first round, forcing a December runoff. I remember when Chile was seen as South America's success story—stable, prosperous, technocratic. Then came the 2019 social explosion, the constitutional convention that ultimately failed, and now this incredibly tight election that will determine whether Chile moves further left or swings hard to the right.

## The Big Issue 1: The Boric Legacy and Left-Wing Disillusionment

Gabriel Boric was supposed to be the future of the Latin American left—young, charismatic, from the student protest movement, elected with a mandate for transformation. He promised a new constitution, expanded social rights, environmental protection, and a reckoning with Chile's Pinochet-era institutions. So what happened? The constitutional convention, which was meant to be his signature achievement, produced a draft so left-wing that 62% of Chileans rejected it in a referendum. It included things like abolishing the Senate and creating separate justice systems for indigenous peoples—proposals that might sound good to activists but terrified moderate voters. Boric then pivoted to the center, trying to govern pragmatically, but he alienated his base without winning over the right. His approval ratings collapsed. Now his candidate, Jeannette Jara, is trying to hold together a coalition that includes communists, socialists, and more moderate progressives—it's genuinely difficult to articulate a coherent message when your coalition spans that range. What's telling is that Jara is leading but only with 25% support. That's not a mandate; that's plurality in a fragmented field. The left's challenge is that they promised transformation and delivered constitutional chaos, economic uncertainty, and rising crime. That's a tough record to defend. But the right has problems too, which we'll get to, so the election remains genuinely open.

## The Big Issue 2: The Far-Right Resurgence and Democratic Fragility

José Antonio Kast is a fascinating and troubling figure. He's from a prominent political family—his father was a German immigrant, his brother was a Pinochet-era government minister—and he represents a hard-right politics that would have been unthinkable in Chilean mainstream politics a decade ago. He opposes abortion, wants tougher immigration controls, and advocates a strong law-and-order message. He came close to winning the presidency in 2021, losing narrowly to Boric in the runoff, and he's positioned himself as the answer to crime and chaos. Here's what worries me: Chile's democratic institutions are still relatively young. The Pinochet dictatorship only ended in 1990, so you have voters who remember authoritarian rule and might find Kast's strongman rhetoric appealing. The polls suggest crime and immigration are voters' top concerns, and on both issues, right-wing positions have electoral advantages—they're simpler, more emotionally resonant, even if they're often ineffective in practice. What's happened to Chile's right wing is fascinating: it's fragmented into multiple candidates rather than uniting behind Kast. That fragmentation might cost them the first round, but it also suggests ideological ferment on the right—different visions of conservatism competing for dominance. If Kast makes the runoff, which seems likely given his 25% support, you'll have a stark choice: continue with the left despite Boric's failures, or embrace hard-right politics despite the echoes of Pinochet. That's not a comfortable choice for a country still processing its authoritarian past.

## The Big Issue 3: Compulsory Voting and the Unknown Electorate

This is the wild card: compulsory voting returns after more than a decade of voluntary participation. When voting was made voluntary in 2012, turnout dropped significantly, and the electorate that did vote tended to be more educated, more urban, more engaged. Now everyone has to vote, and we genuinely don't know what that means politically. The conventional wisdom is that compulsory voting helps the left because it brings in lower-income voters who benefit from social programs. But that was true in an era before crime and immigration dominated the political conversation. Working-class voters who've been forced to vote might be angry about personal safety and immigration, which helps the right. Or they might be pragmatic about economic issues and social programs, which helps the left. We simply don't know. What we do know is that polling becomes much less reliable when you're expanding the electorate by potentially millions of voters. The surveys are based on likely voters, and defining "likely voters" when everyone is required to vote becomes problematic. Expect surprises on Sunday. The other factor is that eight candidates means votes will be spread thinly, making a first-round victory (requiring 50%+) nearly impossible. So we're probably looking at a December 14 runoff, which means another month of campaigning, more time for events to shift momentum, and more uncertainty for a country that's already exhausted by political drama.

## The International Angle

Chile has traditionally been a bellwether for South American politics—what happens there often presages regional trends. If Jara wins, it suggests the left can survive governing disappointments if the right remains fragmented and extreme. If Kast wins, it confirms a rightward shift across the continent: Argentina elected Milei, Bolivia ended MAS rule, Ecuador elected a conservative, and now Chile would join the pattern. For the United States, Chile is strategically important: lithium deposits (crucial for electric vehicle batteries), copper production (essential for electronics and infrastructure), and regional stability. Washington would prefer a moderate government of either stripe but worries about hard-right authoritarianism or hard-left instability. For China, Chile has been an important partner—a trade relationship dating back decades and significant Chinese investment in mining. A Kast government might be more skeptical of Chinese influence, aligning with American preferences. For European observers, Chile represents a test of whether social democratic politics can survive when crime and immigration dominate the discourse. And there's the climate dimension: Chile has enormous renewable energy potential and lithium reserves that make it crucial to global climate transition. Whether it develops those resources sustainably or exploitatively depends partly on who wins.

## The Bottom Line

Chile's election is genuinely unpredictable because of compulsory voting, candidate fragmentation, and a polarized electorate choosing between starkly different visions. Boric's progressive experiment disappointed his supporters without convincing skeptics, leaving the left vulnerable. The right has momentum on crime and immigration but carries Pinochet-era baggage that still matters to many voters. Whoever wins faces enormous challenges: economic reform, crime reduction, immigration management, and healing a society that's been politically divided since 2019. The December runoff, which seems almost certain, will be absolutely fascinating—and consequential not just for Chile but for the broader question of whether Latin American democracy can navigate polarization without descending into authoritarianism.`,
    issues: ["The Boric Legacy and Left-Wing Disillusionment", "The Far-Right Resurgence and Democratic Fragility", "Compulsory Voting and the Unknown Electorate"]
  }
]

async function main() {
  console.log('Generating Politics writeups for 5 countries...\n')

  for (const writeup of writeups) {
    console.log(`Processing ${writeup.name}...`)
    console.log(`Character count: ${writeup.summary.length}`)

    try {
      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: writeup.name,
            type: "country",
            category: "politics"
          }
        },
        create: {
          name: writeup.name,
          type: "country",
          country: writeup.name,
          lat: writeup.lat,
          lng: writeup.lng,
          category: "politics",
          summary: writeup.summary,
          issues: JSON.stringify(writeup.issues),
          topStories: JSON.stringify([]),
          storyCount: 0,
          updatedAt: new Date()
        },
        update: {
          summary: writeup.summary,
          issues: JSON.stringify(writeup.issues),
          updatedAt: new Date()
        }
      })
      console.log(`✓ ${writeup.name} saved to database\n`)
    } catch (error) {
      console.error(`✗ Error saving ${writeup.name}:`, error)
    }
  }

  console.log('\n=== SUMMARY ===')
  console.log('\nCharacter counts:')
  writeups.forEach(w => {
    console.log(`${w.name}: ${w.summary.length} characters`)
  })

  await prisma.$disconnect()
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
