import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const countries = [
  { name: 'Ghana', lat: 7.9465, lng: -1.0232 },
  { name: 'Greece', lat: 39.0742, lng: 21.8243 },
  { name: 'Greenland', lat: 71.7069, lng: -42.6043 },
  { name: 'Guatemala', lat: 15.7835, lng: -90.2308 },
  { name: 'Guinea', lat: 9.9456, lng: -9.6966 },
  { name: 'Guinea-Bissau', lat: 11.8037, lng: -15.1804 },
  { name: 'Guyana', lat: 4.8604, lng: -58.9302 },
  { name: 'Haiti', lat: 18.9712, lng: -72.2852 },
  { name: 'Honduras', lat: 15.2000, lng: -86.2419 },
  { name: 'Hungary', lat: 47.1625, lng: 19.5033 },
  { name: 'Iceland', lat: 64.9631, lng: -19.0208 },
  { name: 'India', lat: 20.5937, lng: 78.9629 },
  { name: 'Indonesia', lat: -0.7893, lng: 113.9213 },
  { name: 'Iran', lat: 32.4279, lng: 53.6880 },
  { name: 'Iraq', lat: 33.2232, lng: 43.6793 },
  { name: 'Ireland', lat: 53.1424, lng: -7.6921 },
  { name: 'Israel', lat: 31.0461, lng: 34.8516 },
  { name: 'Italy', lat: 41.8719, lng: 12.5674 },
  { name: 'Ivory Coast', lat: 7.5400, lng: -5.5471 },
  { name: 'Jamaica', lat: 18.1096, lng: -77.2975 },
  { name: 'Japan', lat: 36.2048, lng: 138.2529 },
  { name: 'Jordan', lat: 30.5852, lng: 36.2384 },
  { name: 'Kazakhstan', lat: 48.0196, lng: 66.9237 },
  { name: 'Kenya', lat: -0.0236, lng: 37.9062 },
  { name: 'Kosovo', lat: 42.6026, lng: 20.9030 },
];

const summaries: Record<string, string> = {
  'Ghana': `Ghana has transformed its criminal justice landscape dramatically since its democratic transition. The country faces moderate crime rates, with street crime in urban centers like Accra and Kumasi being the primary concern for residents and visitors alike. Armed robbery, particularly targeting commercial vehicles on remote highways, remains a persistent challenge despite enhanced police patrols. Cybercrime has emerged as a growing threat, with Ghanaian fraud schemes gaining international notoriety. The Ghana Police Service, while working to modernize, struggles with resource constraints and allegations of corruption. The judiciary has gained credibility through high-profile anti-corruption cases, though case backlogs remain substantial. Ghana's prison system is severely overcrowded, with facilities operating at over 150% capacity. Pretrial detention accounts for a significant portion of inmates. The country has made strides in combating corruption through institutions like the Commission on Human Rights and Administrative Justice and the Office of the Special Prosecutor. Political will has strengthened anti-corruption efforts, though enforcement remains inconsistent. Drug trafficking, particularly cocaine transshipment from South America to Europe, poses a national security concern. Community policing initiatives have shown promise in reducing crime in pilot areas.`,

  'Greece': `Greece maintains a relatively low crime rate compared to many European countries, though economic pressures from the financial crisis years have influenced criminal patterns. Property crime, particularly theft and burglary, increased during economic hardship but has since stabilized. Athens and Thessaloniki see higher crime rates than rural areas, with tourist-targeted pickpocketing and scams being common. The Hellenic Police have modernized significantly, though allegations of excessive force during protests have drawn criticism. Greece's strategic location makes it a key transit point for human trafficking and drug smuggling routes from Asia and the Middle East to Western Europe. The judiciary operates within the framework of the civil law system, with courts generally functioning independently despite backlogs. Corruption perceptions have improved, though concerns about political influence in prosecutions persist. Greece's prison system faces overcrowding, particularly in older facilities, with reform efforts ongoing. Organized crime groups, including local mafia-style organizations and international networks, operate in drug trafficking, extortion, and money laundering. The financial crisis era saw the emergence of anarchist groups engaging in property destruction and attacks on banks. Maritime crime, including smuggling via the numerous islands, presents unique enforcement challenges. Domestic violence has gained increased attention, with legal reforms improving victim protection.`,

  'Greenland': `Greenland faces unique criminological challenges rooted in its remote Arctic geography, small population, and colonial legacy. Crime rates are relatively high per capita, but absolute numbers remain small. Alcohol-fueled violence represents the most significant public safety concern, with assault rates substantially higher than in Denmark proper. Sexual assault rates are alarmingly high, particularly affecting women and children in small settlements. The historical trauma of colonization and forced assimilation policies has contributed to social dysfunction. Greenland Police, under the Danish Rigspolitiet, face extraordinary logistical challenges serving 56,000 people across 410,000 square miles. Many settlements are accessible only by helicopter or boat, complicating law enforcement response. The territory has limited judicial infrastructure, with serious cases tried in Denmark. This creates access-to-justice issues for defendants and victims. Prison facilities are minimal, with most convicted criminals serving sentences in Denmark, separating them from families and cultural connections. Substance abuse, particularly alcohol despite restrictive sales policies, drives much criminal behavior. Suicide rates are among the world's highest, reflecting deep social challenges. Youth crime has increased in larger towns like Nuuk as traditional social structures weaken. Domestic violence is pervasive, with cultural factors sometimes inhibiting reporting. The remote environment makes rehabilitation and social services particularly challenging to deliver effectively.`,

  'Guatemala': `Guatemala endures one of the highest violent crime rates in the Americas, with murder rates consistently ranking among the world's worst. Drug trafficking organizations, including Mexican cartels and local groups, exert tremendous influence over territory and state institutions. Extortion rackets terrorize businesses, with refusal often resulting in violence. Gang violence, particularly involving MS-13 and Barrio 18, dominates urban poor neighborhoods and prisons. These transnational criminal organizations originated partly from deportees from the United States. The National Civil Police (PNC) is under-resourced and infiltrated by corruption. Prosecution rates for violent crimes remain dismally low, creating de facto impunity. The judicial system suffers from corruption, intimidation of prosecutors and judges, and severe capacity limitations. The International Commission Against Impunity in Guatemala (CICIG) made significant progress before its controversial expulsion in 2019, but backsliding has since occurred. Guatemala's prison system is in crisis, with gang control inside facilities, horrific overcrowding, and regular riots and massacres. Corruption permeates all levels, from traffic police to the highest political offices. Guatemala serves as a major transit route for cocaine from South America to the United States, generating enormous illicit revenues. Violence against women is epidemic, with femicide rates among the highest globally and conviction rates abysmal. Indigenous communities face particular vulnerabilities, with limited access to justice and frequent targeting. Land disputes fuel violence, often with criminal elements exploiting conflicts.`,

  'Guinea': `Guinea faces substantial criminal justice challenges amid political instability and extreme poverty. Crime rates are moderate but climbing, with theft and armed robbery most common in Conakry and mining regions. Violent crime has increased following political unrest and security force crackdowns. Guinea's strategic position makes it a transshipment point for South American cocaine destined for Europe, with corruption facilitating trafficking. The police force is poorly trained, under-resourced, and frequently accused of human rights abuses including arbitrary detention and extortion. Public trust in law enforcement is minimal. The judicial system suffers from executive interference, corruption, and severe dysfunction. Trials are frequently delayed for years, with pretrial detention the norm. Guinea's prisons are overcrowded and lack basic sanitation, medical care, and adequate food. Detainee abuse is common. Corruption is endemic across government and society, with Guinea consistently ranking among the world's most corrupt nations. Mining sector corruption involves officials at the highest levels. The 2021 military coup has further complicated governance and accountability. Maritime crime, including illegal fishing and smuggling, affects Guinea's Atlantic coast. Artisanal mining areas experience lawlessness, with violence over claims common. Trafficking in persons, particularly of children for forced labor and begging, persists. Female genital mutilation remains widespread despite legal prohibitions. Mob justice occurs when formal justice is inaccessible or distrusted.`,

  'Guinea-Bissau': `Guinea-Bissau has gained notoriety as a major narco-state, with cocaine trafficking fundamentally corrupting institutions. This small West African nation serves as a key transshipment point for South American cocaine to Europe, with trafficking networks involving military and political elites. The country's instability—marked by frequent coups and assassination attempts—is intertwined with drug money. Crime rates are difficult to assess given limited data, but armed robbery and theft are common in Bissau. The police force is ineffective, unpaid for months at times, and widely perceived as corrupt. Officers often lack basic equipment including vehicles and communication devices. The military wields disproportionate power and operates with impunity, involved in various criminal enterprises. The judiciary is dysfunctional, with judges lacking resources and facing intimidation. Trials are rare, with most accused never reaching court. Guinea-Bissau's prison conditions are harsh, with facilities severely overcrowded and lacking basic necessities. Corruption is pervasive and institutionalized, with the state effectively captured by criminal interests. International efforts to combat trafficking have made limited progress against entrenched networks. Political assassinations and violence have gone unpunished. Human trafficking affects children exploited for labor and begging. The cashew industry, the main legal export, sees widespread corruption. Maritime crime, including illegal fishing, costs the nation significant revenue. Traditional justice systems operate in rural areas with little state presence. The country faces a fundamental crisis of governance where criminal and state power are indistinguishable.`,

  'Guyana': `Guyana experiences moderate to high crime rates, with violent crime concentrated in Georgetown and other urban areas. Armed robberies, including home invasions, represent a serious concern. The country's porous borders facilitate drug trafficking from South America to the Caribbean and beyond, with corruption enabling these networks. Gang activity has intensified, often linked to drug trade profits and territorial disputes. The Guyana Police Force faces significant challenges including inadequate resources, training deficiencies, and corruption allegations. Police brutality and extrajudicial killings have drawn criticism from human rights organizations. The judiciary operates slowly with substantial backlogs, though recent reforms have improved efficiency. Corruption concerns affect both police and courts, undermining public confidence. Guyana's prison system is overcrowded and characterized by poor conditions. The Camp Street prison in Georgetown has experienced deadly riots and fires. Pretrial detention is lengthy. Corruption affects multiple sectors, particularly in government procurement and natural resources. The recent oil boom has raised concerns about resource-related corruption. Guyana serves as a transit point for cocaine and marijuana trafficking, with limited interdiction capacity. Illegal gold mining drives environmental crime and involves criminal networks. Domestic violence and sexual assault rates are high, with cultural factors inhibiting reporting. Human trafficking, particularly for sexual exploitation and forced labor, persists. Piracy and armed robbery at sea affect the fishing industry. Political violence occasionally erupts along ethnic lines. Land disputes, particularly involving indigenous communities, sometimes involve violence.`,

  'Haiti': `Haiti suffers from one of the hemisphere's most severe security and criminal justice crises. Gang violence has rendered large portions of Port-au-Prince ungovernable, with armed groups controlling territory, kidnapping for ransom, and engaging in rape as a weapon. The Haitian National Police is severely under-resourced, outgunned by gangs, and infiltrated by corruption. Effective policing has largely collapsed in gang-controlled areas. International security assistance has had limited success. The judiciary is dysfunctional, with most judges lacking proper credentials, widespread corruption, and minimal case processing. Most accused never face trial. Haiti's prisons are nightmarish, with extreme overcrowding (over 400% capacity in some facilities), no separation of pretrial detainees from convicts, and deadly conditions. The vast majority of inmates have never been convicted. Corruption is endemic and pervasive, with the state largely captured by political and economic elites. Haiti consistently ranks among the world's most corrupt nations. Drug trafficking, particularly cocaine transshipment, generates revenues that fuel gang violence and official corruption. Kidnapping has become epidemic, targeting both wealthy Haitians and foreigners for ransom. Human trafficking for labor and sexual exploitation is widespread. Political assassinations, including the 2021 murder of President Moïse, often go unsolved. Vigilante violence and mob justice occur when formal systems fail. International intervention has repeatedly failed to establish lasting security. The country faces state collapse scenarios with criminal actors filling the vacuum.`,

  'Honduras': `Honduras endures one of the world's highest murder rates, driven by drug trafficking, gang violence, and institutional weakness. Mexican cartels and local trafficking organizations have deeply penetrated state institutions through corruption and intimidation. The country serves as a major transit route for cocaine from South America to the United States. Gang violence, particularly MS-13 and Barrio 18, terrorizes communities through extortion, recruitment of children, and territorial battles. These groups originated partly from deportees from the United States. The Honduran National Police has undergone purges aimed at rooting out corruption, but significant problems remain. Police involvement in criminal activity, including murders and kidnappings, has been documented. A new police force, the Military Police of Public Order, was created but has faced abuse allegations. The judiciary suffers from corruption, intimidation, and inefficiency. Prosecutions are rare, with impunity rates over 90% for violent crimes. Judges and prosecutors face death threats. Honduras' prisons are severely overcrowded and largely controlled by gangs. Violent incidents, including massacres, occur regularly. Corruption is pervasive, reaching the highest political levels including documented cases involving presidents. Anti-corruption efforts have faced political resistance. Violence against journalists is among the worst globally, with numerous murders going unpunished. Femicide rates are extremely high, with women and LGBTQ individuals particularly vulnerable. Land conflicts involve violence, often with criminal elements exploiting disputes.`,

  'Hungary': `Hungary maintains relatively low crime rates by European standards, though certain trends raise concerns. Violent crime is uncommon, with Budapest and other cities experiencing typical urban property crime like theft and pickpocketing, particularly targeting tourists. Organized crime operates in human trafficking, drug distribution, and financial crimes, often with transnational connections. The Hungarian police force is generally professional, though concerns about political influence have emerged under the current government. Police accountability mechanisms have been weakened. The judiciary has faced increasing concerns about independence, with constitutional changes and appointments raising questions about politicization. Judicial Council reforms have concentrated power. Rule of law indices have shown Hungary declining in recent years. Hungary's prison system operates near capacity with conditions varying by facility. Reforms have improved some aspects, though overcrowding persists in older institutions. Corruption perceptions have worsened, with concerns about high-level corruption in public procurement and EU funds management. Anti-corruption institutions have been weakened. Media investigations into government-linked corruption face obstacles. Human trafficking for sexual and labor exploitation involves Hungary as both a transit and destination country. Hate crimes targeting Roma, migrants, and LGBTQ individuals occur, with civil society organizations documenting incidents. Border enforcement has intensified amid migration pressures, with allegations of pushbacks and mistreatment. Financial crimes including VAT fraud and money laundering affect the banking sector. Domestic violence rates are moderate, with legal protections available though enforcement varies.`,

  'Iceland': `Iceland consistently ranks as one of the world's safest countries with remarkably low crime rates. Violent crime is exceptionally rare, with homicides averaging fewer than two per year in this nation of 380,000. Property crime, mainly theft and burglary, represents most criminal activity but remains low by international standards. The Icelandic Police are unarmed except for special units, reflecting the generally peaceful society. Officers are well-trained and trusted by the public. Use of force is extremely rare, with police firing weapons fatally only once in the nation's history. The judiciary operates within the civil law tradition with strong independence and minimal corruption. Trials proceed efficiently with defendants receiving fair treatment. Iceland's prison system emphasizes rehabilitation over punishment, with facilities offering education and vocational training. Conditions are humane, and incarceration rates are among the world's lowest. Open prisons allow inmates considerable freedom. Reoffending rates are low. Corruption is extremely rare, with Iceland consistently ranking among the world's least corrupt nations. Financial crimes related to the 2008 banking crisis led to successful prosecutions of banking executives—unusual internationally. Drug offenses, particularly cannabis possession and emerging methamphetamine use, represent a growing concern though rates remain low by European standards. Domestic violence occurs but is actively addressed through legal protections and support services. Sexual assault cases have increased awareness, leading to policy debates about consent laws. Cybercrime is emerging as technology advances. Overall, Iceland's combination of social cohesion, economic equality, and effective institutions creates an environment highly resistant to crime.`,

  'India': `India's criminal justice landscape reflects its vast scale and complexity, with crime patterns varying dramatically across regions, urban-rural divides, and socioeconomic strata. Overall crime rates are moderate statistically but mask serious concerns. Violent crime including murder, assault, and robbery affects many areas. Violence against women remains epidemic, with rape, domestic violence, and dowry deaths persistent despite legal reforms after high-profile cases spurred activism. Honor killings continue in traditional communities. Organized crime operates through syndicates controlling various sectors, with historical groups like the Mumbai underworld evolving. Terrorist violence affects certain regions, particularly Jammu and Kashmir and areas with Naxalite insurgencies. Indian police forces face severe challenges including politicization, corruption, inadequate resources, and poor training. Police brutality and custodial deaths draw criticism from human rights organizations. Encounter killings—extrajudicial executions—occur with disturbing frequency. The judiciary, while independent in principle, suffers from massive backlogs with millions of pending cases. Trials can take decades. Corruption affects police and courts, with those lacking resources or connections disadvantaged. India's prisons are severely overcrowded at over 130% capacity, with over two-thirds of inmates awaiting trial. Conditions vary from adequate in newer facilities to appalling in older ones. Corruption is pervasive across levels of government and society, from petty bribery to massive scams involving politicians and business elites. Anti-corruption efforts have intensified but face implementation challenges. Drug trafficking and production affect border regions. Human trafficking for labor and sexual exploitation remains widespread. Caste-based violence and discrimination persist despite legal prohibitions.`,

  'Indonesia': `Indonesia faces diverse criminal justice challenges across its vast archipelago of over 17,000 islands and 275 million people. Crime rates vary significantly by region, with urban areas like Jakarta experiencing higher rates of theft, robbery, and violent crime. Terrorism remains a serious concern, with jihadist groups conducting attacks despite counter-terrorism successes. Radicalization in prisons poses risks. Communal and religious violence occasionally erupts, particularly affecting minority communities. The Indonesian National Police have modernized significantly but face corruption concerns and accusations of human rights abuses. Police shootings and torture in custody have been documented. The judiciary operates within a civil law system with improving but still inconsistent independence. High-profile corruption cases sometimes see successful prosecution, but political influence affects outcomes. "Judicial mafia" refers to corruption involving lawyers, judges, and court officials. Indonesia's prisons are severely overcrowded at nearly 200% capacity, with conditions often harsh. Drug offenders constitute a large percentage of inmates despite controversies over harsh penalties. Corruption is endemic, with Indonesia making progress but still ranking poorly globally. The Corruption Eradication Commission (KPK) achieved successes before recent legal changes that critics argue weakened it. Political and business elite corruption involves massive sums. Drug trafficking is substantial, with Indonesia as both consumer and transit point. Death penalty for drug offenses remains despite international criticism. Human trafficking for forced labor and sexual exploitation affects vulnerable populations. Environmental crimes including illegal logging, mining, and fishing involve criminal networks and official complicity. Vigilante justice and mob violence occur, particularly in cases involving theft or perceived moral violations.`,

  'Iran': `Iran's criminal justice system operates under Islamic law within a theocratic framework, creating dynamics distinct from secular systems. Crime statistics are unreliable given state control of information, but available data suggests moderate rates for conventional crimes. Theft, drug offenses, and assault account for most prosecutions. The Islamic Republic's definition of criminality extends to acts considered moral or political offenses. Restrictions on speech, assembly, and dress are enforced through both formal and informal means. The Iranian police, including the regular police and the Basij volunteer force, enforce both conventional laws and moral codes. Security forces have been implicated in human rights abuses, particularly during protests. Arrests and detention of dissidents, journalists, and activists occur regularly. The judiciary lacks independence from the religious and political establishment, with clerical judges holding ultimate authority. Political trials often fail to meet fair trial standards. Revolutionary Courts handle security cases with limited due process. Iran's prisons hold political prisoners alongside conventional criminals, with documented torture and harsh conditions. Evin Prison in Tehran is particularly notorious. Executions occur at high rates, including for drug offenses. Iran executes more people per capita than almost any nation. Corruption is significant despite official Islamic prohibitions, with Revolutionary Guard business involvement and political patronage facilitating it. Drug trafficking is substantial, with Iran serving as a major transit route from Afghanistan to the West. Addiction rates are high. Enforcement is harsh, including death penalties for traffickers. Women face systematic legal discrimination, with "morality police" enforcing dress codes.`,

  'Iraq': `Iraq's criminal justice system has been devastated by decades of conflict, with instability, sectarian violence, and weak institutions defining the security environment. Crime rates are difficult to assess accurately, but violence remains endemic. Terrorism, particularly ISIS remnants conducting attacks, continues despite territorial defeat. Militia violence, with Iran-backed groups operating with impunity, complicates security. Kidnapping for ransom, both criminal and politically motivated, is common. Iraqi security forces, including police and military units, vary widely in professionalism and loyalty. Many units are infiltrated by militia members or political parties. Corruption is pervasive, with checkpoints often used for extortion. Torture and arbitrary detention have been documented extensively. The judiciary struggles to function amid security threats, political pressure, and sectarian influence. Judges face assassination risks. Trials often fail to meet international standards, with confessions extracted through torture sometimes admitted as evidence. Terrorism trials particularly raise due process concerns. Iraq's prisons are overcrowded and often controlled by militias or political factions rather than the state. Conditions are harsh, with abuse and sectarian violence against inmates documented. Mass executions of convicted terrorists occur. Corruption is endemic and pervasive, with Iraq consistently ranking among the world's most corrupt nations. Oil revenues are siphoned through complex networks involving politicians, militias, and businessmen. Reconstruction contracts involve massive theft. Drug trafficking has increased, with Iraq becoming a transit point and consumption increasing. Domestic violence is widespread but rarely prosecuted. Weak rule of law enables impunity for powerful actors.`,

  'Ireland': `Ireland maintains low crime rates with a generally effective criminal justice system, though recent increases in certain crime types have sparked concern. Violent crime remains relatively rare, with Dublin experiencing the highest rates. Gang violence related to drug trafficking has intensified, involving feuds between organized crime groups that occasionally result in public shootings and murders. The Irish police force, An Garda Síochána, is generally professional and trusted, though recent scandals involving data breaches, misconduct allegations, and internal cultural problems have dented public confidence. Reforms are ongoing. The judiciary operates independently within the common law tradition, with defendants receiving fair trials. Court backlogs have grown, particularly after pandemic disruptions. Ireland's prison system operates near or above capacity, with overcrowding in some facilities. The Mountjoy Prison in Dublin has faced particular criticism. Prison conditions generally meet international standards, though issues persist. Ireland has made efforts to reduce incarceration through alternative sentencing. Corruption is relatively low by international standards, though political and planning corruption scandals have occurred. White-collar crime enforcement has strengthened. Drug trafficking organizations operate sophisticated networks, importing cocaine and cannabis while producing and exporting synthetic drugs and cannabis. Consumption rates are high by European standards. Cybercrime is growing, with Ireland's position as a European tech hub creating vulnerabilities and targets. Human trafficking for sexual and labor exploitation affects vulnerable migrants. Domestic violence rates are concerning, with advocacy groups pushing for stronger responses. Historical institutional abuse has led to major investigations and compensation schemes.`,

  'Israel': `Israel's security environment fundamentally shapes its criminal justice system, with terrorism and conflict creating unique dynamics. Conventional crime rates are moderate, with property crime and theft most common. Violent crime occurs primarily in certain urban areas and Arab communities where enforcement has historically been weak, leading to family feuds and organized crime. Terrorist attacks, primarily by Palestinian individuals or groups, remain a persistent threat despite sophisticated security measures. Rocket attacks from Gaza and Lebanon periodically occur. The Israel Police operate in a high-security environment, with extensive intelligence capabilities and coordination with military and security services. Police have faced criticism regarding use of force, particularly in Arab communities and during demonstrations. The judiciary is independent and professional, though politically contentious issues regarding settlements, security, and religious matters create tensions. Military courts in the occupied territories operate under different standards than civilian courts in Israel proper, raising human rights concerns. Israel's prison system holds both conventional criminals and security prisoners, including Palestinians from the territories. Conditions generally meet international standards, though administrative detention without trial of Palestinians is controversial. Corruption has affected high-level politicians, with several prime ministers facing prosecution. Enforcement has been rigorous, demonstrating judicial independence. Organized crime, including Russian-speaking crime groups and Arab clans, operates in drug trafficking, extortion, and money laundering. Cybercrime is sophisticated given Israel's tech sector. Human trafficking for sexual exploitation has been addressed through legal reforms. Relations between religious and secular law create friction.`,

  'Italy': `Italy grapples with a distinctive criminal justice landscape where traditional organized crime coexists with modern challenges. Mafia-type organizations—the Sicilian Mafia, Calabrian 'Ndrangheta, Neapolitan Camorra, and Puglian Sacra Corona Unita—have adapted to globalization, engaging in drug trafficking, public works corruption, money laundering, and infiltrating legitimate businesses and politics. The 'Ndrangheta is considered Europe's most powerful organized crime group. Anti-mafia efforts have achieved significant successes, including prosecutions of high-ranking bosses, but these organizations remain deeply rooted. Violent crime rates are low by European standards, with northern regions generally safer than the south. Property crime and theft affect urban tourist areas. The Italian police forces—including Polizia di Stato, Carabinieri, and Guardia di Finanza—are professional, though bureaucracy affects efficiency. Coordination among multiple forces can be complex. The judiciary operates within the civil law tradition with constitutional independence. Investigative magistrates have been crucial in anti-corruption and anti-mafia efforts, though political tensions arise. Trials are notoriously slow with cases taking years. Italy's prisons are overcrowded, operating at 130% capacity, with the European Court of Human Rights ruling conditions violated human rights. Reforms have improved situations, but challenges persist. Corruption affects multiple levels of government and business, particularly in public procurement and construction. North-south disparities exist. Major scandals like "Tangentopoli" in the 1990s and recent cases demonstrate ongoing challenges. Migrant smuggling across the Mediterranean involves criminal networks exploiting vulnerable people. Cybercrime and financial crimes are sophisticated.`,

  'Ivory Coast': `Ivory Coast has worked to rebuild its criminal justice system following civil wars that devastated institutions and normalized violence. Crime rates remain elevated, with armed robbery, theft, and violent crime affecting Abidjan and other cities. The conflicts left weapons widely available, contributing to insecurity. Land disputes, unresolved from war-era displacements, sometimes involve violence. The police and gendarmerie are rebuilding capacity but face resource constraints, corruption allegations, and public distrust stemming from human rights abuses during conflicts. Security force reforms have been politically contentious. The judiciary is slowly recovering independence and capacity after years of political interference and conflict disruption. Many judges lack training, facilities are inadequate, and corruption concerns persist. Impunity for conflict-era crimes frustrates victims. Ivory Coast's prisons are overcrowded and characterized by poor conditions. Pretrial detention is lengthy with many inmates awaiting trial for years. Juvenile offenders often are held with adults. Corruption affects multiple levels of government and business, with natural resource sectors particularly prone to graft. Anti-corruption efforts have been selective, with concerns about political motivations. Ivory Coast serves as a transit point for cocaine from South America to Europe, with corruption facilitating trafficking. Local drug consumption is growing. Child trafficking for forced labor in cocoa production and domestic service persists despite government efforts. Artisanal mining areas experience lawlessness and exploitation. Maritime crime, including piracy in the Gulf of Guinea, affects coastal areas. Mob justice occurs when formal justice systems are inaccessible or distrusted.`,

  'Jamaica': `Jamaica suffers from one of the world's highest murder rates, driven by gang violence, drug trafficking, and weak criminal justice institutions. Gang warfare, often politically connected historically though less so recently, terrorizes communities through territorial battles, extortion, and reprisal killings. Lottery scams defraud victims internationally, particularly in North America, generating millions. The Jamaica Constabulary Force faces enormous challenges, with limited resources, corruption concerns, and strained community relations. Police killings are among the world's highest per capita, with allegations of extrajudicial executions. The Independent Commission of Investigations examines police misconduct but faces resistance. The judiciary operates within the common law tradition with constitutional independence, though backlogs create years-long delays. Witness intimidation undermines prosecutions, with murder conviction rates dismally low. The Caribbean Court of Justice serves as the final appeal court. Jamaica's prisons are overcrowded and marked by harsh conditions. Gang violence occurs inside facilities. Lockdowns are frequent. Pretrial detention is lengthy. Corruption affects multiple sectors, with government procurement and political patronage particularly problematic. Police corruption facilitates drug trafficking. Jamaica serves as a transit point for cocaine from South America to North America and Europe, while also producing marijuana for export. Drug trafficking generates revenues that fuel gang violence. Deportees from the US and UK, some with criminal histories or gang affiliations, have affected local crime dynamics. Domestic and sexual violence rates are high, with cultural factors sometimes inhibiting reporting. LGBTQ individuals face violence and discrimination. Economic desperation drives much criminal activity.`,

  'Japan': `Japan has one of the world's lowest crime rates and most distinctive criminal justice systems. Violent crime is exceptionally rare, with one of the lowest murder rates globally. Property crime including theft and burglary is also low. Organized crime, particularly yakuza syndicates, operates semi-openly despite being illegal, involved in extortion, gambling, prostitution, drug trafficking, and legitimate business infiltration. Yakuza membership has declined significantly due to police pressure. The Japanese police are professional, well-resourced, and trusted. The koban (police box) system provides neighborhood presence. Confession rates are remarkably high, partly due to interrogation techniques that critics argue coerce admissions. The judiciary operates within a civil law system with very high conviction rates (over 99%), raising concerns about pressure on prosecutors to only pursue certain cases and about defendants' rights. Lay judge participation in serious cases was introduced in 2009. Japan's prisons emphasize strict order and discipline, with highly regimented routines. Conditions are spartan but not inhumane by international standards. Incarceration rates are low. Rehabilitation efforts focus on work and education. Reoffending rates are relatively low. Corruption is low by global standards, though corporate-government collusion ("amakudari" system of bureaucrats joining companies they regulated) raises concerns. Political scandals periodically emerge. White-collar crime enforcement has strengthened. Cybercrime is growing with Japan's advanced technology. Human trafficking for sexual exploitation, including of foreign women, persists. Death penalty remains, used sparingly but controversially. Social pressure and family shame serve as powerful informal controls.`,

  'Kazakhstan': `Kazakhstan's criminal justice system reflects its Soviet legacy and authoritarian governance structure. Official crime statistics show moderate rates, though independent verification is difficult. Theft, fraud, and drug offenses are most common. Violent crime occurs primarily in urban areas and border regions. Organized crime groups, some with Russian connections, operate in drug trafficking, human trafficking, and various rackets. The police, reformed from Soviet-era structures, face corruption concerns and allegations of human rights abuses including torture to extract confessions. Arbitrary detention of dissidents and activists occurs. The judiciary lacks independence, with political control over courts routine. Trials often appear predetermined, particularly in politically sensitive cases. Defense attorneys face obstacles. Corruption within the judiciary is significant. Kazakhstan's prisons suffer from overcrowding, tuberculosis epidemics, and harsh conditions. Torture and abuse of inmates have been documented. Political prisoners are held alongside conventional criminals. Corruption is pervasive despite high-level anti-corruption rhetoric. President Nazarbayev's family and associates accumulated vast wealth through control of state resources. Oil sector corruption involves massive sums. Police and officials expect bribes routinely. Drug trafficking from Afghanistan through Central Asia involves Kazakhstan as a transit country, with corruption facilitating smuggling. Domestic drug production, particularly of synthetic drugs, is growing. Human trafficking for labor and sexual exploitation affects vulnerable populations. Ethnic tensions occasionally manifest in violence. Political opposition faces prosecution on fabricated charges. Civic activists and journalists experience harassment. Wealth inequality is extreme despite oil revenues.`,

  'Kenya': `Kenya faces substantial crime challenges amid rapid urbanization, inequality, and governance weaknesses. Crime rates are high, with Nairobi and Mombasa experiencing violent crime including armed robbery, carjacking, and mugging. Terrorism remains a serious threat, with al-Shabaab conducting attacks particularly in border areas and urban centers. The 2013 Westgate Mall attack and 2019 Riverside attack killed dozens. The Kenya Police Service suffers from deep corruption, inadequate training, poor pay, and involvement in extrajudicial killings. Human rights organizations document hundreds of police killings annually, with impunity the norm. Arbitrary detention and torture occur regularly. Police reforms have made limited progress. The judiciary underwent significant reforms following the 2010 constitution, improving independence and capacity. Courts have issued rulings against government actions, demonstrating autonomy. However, corruption concerns persist, and backlog remains substantial. Kenya's prisons are severely overcrowded at over 280% capacity in some facilities. Conditions are harsh with inadequate food, sanitation, and medical care. Pretrial detention is lengthy. Corruption is endemic, affecting all levels of government and business. Major scandals involving billions in stolen public funds regularly emerge. The political elite operate with impunity. Anti-corruption agencies have been ineffective, often politically weaponized. Kenya serves as a transit point for heroin from Asia and cocaine from South America. Drug consumption has increased. Wildlife poaching and trafficking involve sophisticated international networks. Political violence around elections has killed thousands historically, with 2007-2008 post-election violence the most severe. Ethnic tensions are exploited politically.`,

  'Kosovo': `Kosovo's criminal justice system is still developing following independence in 2008 after conflict and international administration. Crime rates are moderate, with property crime and theft most common. Organized crime, including drug trafficking, human trafficking, and smuggling, operates with networks extending to Western Europe where the large Kosovo diaspora resides. War-era weapons remain in circulation. The Kosovo Police have developed with international assistance but face capacity limitations, corruption concerns, and challenges in Serbian-majority areas where parallel structures exist. Ethnic tensions affect policing. The judiciary includes international judges in certain courts addressing war crimes and organized crime. Corruption and political influence remain concerns despite reforms. Local judges often lack experience with complex cases. Kosovo's prisons operate below capacity with conditions generally acceptable, though older facilities need modernization. EULEX mission provided oversight. Corruption affects many aspects of governance and business, with public procurement particularly problematic. Political elite connections facilitate illicit enrichment. Anti-corruption efforts have been inconsistent. Kosovo serves as a transit route for heroin from Asia to Western Europe, with diaspora connections facilitating trafficking. Cannabis cultivation for export has increased. Human trafficking for sexual exploitation affects vulnerable women and girls. War crimes prosecutions continue, though many suspects remain at large. Relations with Serbia create jurisdictional complications. Serbian-majority areas have parallel security and judicial structures, complicating law enforcement. Transitional justice remains incomplete, frustrating victims. Economic desperation drives criminal activity, with unemployment extremely high particularly among youth.`,
};

async function generateAndSave() {
  console.log('Generating Crime writeups for Batch 1 (Ghana through Kosovo - 25 countries)...\n');

  for (const country of countries) {
    const summary = summaries[country.name];

    if (!summary) {
      console.log(`⚠️  No summary for ${country.name}`);
      continue;
    }

    try {
      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: country.name,
            type: 'country',
            category: 'crime'
          }
        },
        update: {
          summary: summary,
          lat: country.lat,
          lng: country.lng,
          updatedAt: new Date()
        },
        create: {
          name: country.name,
          type: 'country',
          category: 'crime',
          lat: country.lat,
          lng: country.lng,
          country: country.name,
          summary: summary,
          issues: '[]',
          topStories: '[]',
          storyCount: 0
        }
      });

      console.log(`✓ ${country.name} (${summary.length} chars)`);
    } catch (error) {
      console.error(`✗ Error saving ${country.name}:`, error);
    }
  }

  await prisma.$disconnect();
  console.log('\n✓ Batch 1 complete!');
}

generateAndSave();
