import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// All 128 countries with coordinates and comprehensive sports writeups
// Voice: Bill Simmons / Gary Neville - Enthusiastic fan, knowledgeable, opinionated
// Length: 2,000-3,000 characters
// Focus: Popular sports, leagues, national teams, recent performance, infrastructure, stars, Olympic/World Cup history

const SPORTS_WRITEUPS = [
  {
    name: 'Afghanistan',
    lat: 33.9391,
    lng: 67.7100,
    summary: `Cricket is Afghanistan's sporting obsession—and honestly, their rise has been one of the best sports stories of the past decade. The national team went from refugee camps in Pakistan to beating England in the 2023 Cricket World Cup. Rashid Khan is a global superstar, one of the world's best T20 bowlers, playing in the IPL, Big Bash, and everywhere that pays. Afghanistan Cricket Board runs the Shpageeza Cricket League, the domestic T20 competition that's genuinely competitive. The national team qualified for every T20 World Cup since 2010 and made the 2019 and 2023 ODI World Cups. Cricket infrastructure is concentrated in Kabul and Jalalabad—the Kabul International Cricket Stadium hosts internationals, though security concerns mean Afghanistan often plays "home" matches in UAE or Pakistan. The Taliban takeover in 2021 complicated things: they initially banned women's cricket entirely, which got Afghanistan suspended from Test cricket by the ICC (though they're still playing limited-overs formats). Football exists but it's a distant second—the national team is ranked around 150th by FIFA, plays in AFC competitions, and qualified for the 2013 South Asian Football Federation Championship. The Afghan Premier League is the domestic football competition, but quality is low and matches are poorly attended. Buzkashi (the traditional horse-mounted game) is culturally significant but not organized as a professional sport. Afghanistan won three medals at the 2008 Beijing Olympics (one bronze in taekwondo) and hasn't medaled since, but cricket is where the nation's sporting pride lives. Gyms and fitness centers in Kabul cater to a small urban elite, but most Afghans lack access to organized sports infrastructure. Women's sports have been devastated under the Taliban—female athletes fled abroad, and those who stayed face total prohibition from competition. The cricket team's success is Afghanistan's only global sporting presence, and Rashid Khan is basically carrying the entire nation's sporting reputation on his shoulders. The future is uncertain: if the Taliban relax their stance, cricket could continue to grow, but right now Afghan sports are in survival mode.`,
    issues: ['Cricket rise with stars like Rashid Khan', 'Taliban restrictions on women\'s sports', 'National cricket team\'s World Cup success', 'Limited infrastructure and security concerns', 'Football secondary to cricket', 'Buzkashi traditional sport']
  },
  {
    name: 'Albania',
    lat: 41.3275,
    lng: 19.8187,
    summary: `Football is religion in Albania—the national team's qualification for Euro 2016 (their first major tournament ever) was like winning the whole thing. The Albanian Superliga is scrappy and underfunded, but clubs like KF Tirana, Dinamo Tirana, and Partizani have passionate fanbases. The biggest issue is infrastructure: most stadiums are communist-era relics that need serious upgrades, though the Air Albania Stadium in Tirana (opened 2019) is genuinely world-class and hosts national team matches. Domestically, the league struggles with match-fixing scandals, low attendance, and financial instability—clubs routinely fold or get relegated for financial violations. The national team peaked under Italian coach Gianni De Biasi, qualifying for Euro 2016 with a squad built around Lorik Cana, Etrit Berisha, and Elseid Hysaj. They didn't make it out of the group stage but the nation went wild anyway. Since then, they've been stuck in UEFA Nations League purgatory, occasionally competitive but not qualifying for 2018, 2022 World Cups or Euro 2020/2024. Albanian players often emigrate young—Hysaj plays in Serie A, Armando Broja was at Chelsea, and guys like Berat Djimsiti and Marash Kumbulla play top-tier European football but were often born abroad (Swiss-Albanians, Italian-Albanians). Basketball has a small but dedicated following—the Albanian Basketball League exists, and the national team competes in FIBA Europe, but they're not competitive at high levels. Volleyball is popular among women, and Albania's women's volleyball team occasionally qualifies for European Championships. Olympic history is thin: Albania's only medal was a weightlifting silver in 2000. The sporting culture is passionate but underfunded—clubs rely on wealthy benefactors, youth academies are underdeveloped, and brain drain means the best talent leaves for Italy, Switzerland, or Germany as teenagers. If you're in Tirana, the football cafes are packed during national team matches, and the atmosphere is electric—Albanians love their football even if the domestic product is rough.`,
    issues: ['Football-obsessed nation with struggling domestic league', 'Infrastructure issues in aging stadiums', 'National team\'s Euro 2016 breakthrough', 'Player emigration to Europe', 'Basketball and volleyball minor sports', 'Limited Olympic success']
  },
  {
    name: 'Algeria',
    lat: 36.7538,
    lng: 3.0588,
    summary: `Algeria is a football powerhouse in Africa—two-time African Cup of Nations champions (1990, 2019), and their 2019 AFCON win was genuinely dominant. The national team, Les Fennecs, qualified for four World Cups (1982, 1986, 2010, 2014), with the 1982 team legendary for beating West Germany 2-1 (only to get screwed by the Disgrace of Gijón). Riyad Mahrez is the global star—Manchester City winger, African Footballer of the Year, and the guy who led Algeria to that 2019 AFCON title. The Algerian Ligue Professionnelle 1 is the domestic league, dominated by clubs like JS Kabylie, MC Alger, and CR Belouizdad. Attendance is passionate but infrastructure varies wildly—some stadiums are modern (Stade 5 Juillet 1962 in Algiers hosts 80,000), others are crumbling. The league suffers from financial instability, political interference (clubs are often owned by state-linked entities), and occasional violence—derby matches between MC Alger and USM Alger get heated. Algerian players export well: Mahrez, Islam Slimani, Yacine Brahimi, and Ismael Bennacer all play/have played in Europe's top leagues. Handball is Algeria's second sport—they won the African Handball Championship multiple times and competed at the Olympics. Basketball exists (the Algerian Basketball Championship) but it's not a major draw. Track and field has produced Olympic medalists: Taoufik Makhloufi won 1500m silver in 2012 and gold in 2016, Nouria Merah-Benida won 1500m gold in 2000. Algeria hosted the 1978 All-Africa Games and regularly competes well at continental level. The football culture is intense—massive street celebrations after AFCON 2019, and the diaspora (especially in France) is deeply invested. The 2022 World Cup was a disaster: Algeria went out in the group stage without a win, and coach Djamel Belmadi's tactics were widely criticized. But the talent pipeline is strong, and with Mahrez still performing and younger players like Amine Gouiri emerging, Algeria will remain a continental force.`,
    issues: ['Two-time AFCON champions (1990, 2019)', 'Riyad Mahrez global superstar', 'Strong football culture and diaspora', 'Domestic league financial instability', 'Handball and track Olympic success', '2022 World Cup disappointment']
  },
  {
    name: 'Angola',
    lat: -8.8383,
    lng: 13.2344,
    summary: `Basketball is Angola's strongest sport—they're the kings of African basketball with 11 AfroBasket titles (most recently 2013). The national team, led historically by players like Joaquim Gomes and Carlos Morais, dominated the continent for decades and qualified for five Olympics (1992-2008, though they didn't medal). Angolan club basketball is organized in the Angolan Basketball League (BAI Basket), with Petro de Luanda and Primeiro de Agosto as the powerhouse clubs—both have won the Basketball Africa League (BAL) titles. Petro de Luanda is one of Africa's richest sports clubs, funded by Angola's state oil company Sonangol, and they've won 30+ domestic titles. Football is popular but Angola's national team has underperformed—they qualified for the 2006 World Cup (their only appearance) but went out in the group stage without a point. The Girabola (Angolan football league) is dominated by Petro de Luanda and Primeiro de Agosto again—both clubs are backed by state money and military funding, which creates a competitive imbalance. Attendance for football is decent, and Angolan players like Manucho and Akwá played in Europe, but the talent pool is limited. Angola hosted the 2010 AFCON, which was marred by the Togo national team bus attack (a terrorist incident that killed three), casting a shadow over the tournament. Handball is Angola's third sport—the men's team has won African championships and competed at the Olympics, while the women's team is even stronger (15 African titles, multiple Olympic appearances). Angola's sporting success is built on state investment—Petro de Luanda and Primeiro de Agosto are essentially government-funded clubs that dominate basketball, football, handball, and volleyball. The country's oil wealth has funded sports infrastructure (the Cidadela Desportiva complex in Luanda is impressive), but Angola's economy has struggled since oil prices collapsed, and sports funding has been cut. The basketball legacy remains strong, and Angola will host FIBA events, but the golden era (1990s-2000s) is over unless investment returns.`,
    issues: ['11-time African basketball champions', 'Petro de Luanda dominance across sports', 'Football national team underperformance', 'State-funded sports infrastructure', 'Handball Olympic success', 'Economic challenges affecting sports funding']
  },
  {
    name: 'Argentina',
    lat: -38.4161,
    lng: -63.6167,
    summary: `Argentina is football royalty—three World Cups (1978, 1986, 2022) and Lionel Messi finally got his trophy in Qatar 2022, completing arguably the greatest football career ever. The 2022 World Cup win was transcendent: Messi dragging Argentina through, the final against France going to penalties, the entire nation celebrating for weeks. Argentine football culture is unmatched: the superclásico between Boca Juniors and River Plate is one of world sport's great rivalries, played in La Bombonera (Boca's stadium, one of the most intimidating venues on Earth). The Argentine Primera División is genuinely competitive—Boca, River, Racing, Independiente, San Lorenzo all have massive histories and passionate fanbases. The league restructured in 2015 to eliminate relegation temporarily (to protect big clubs), which was controversial but has since returned to normal. Messi is the GOAT, and it's not close—eight Ballon d'Ors, Champions Leagues with Barcelona, now winning everything with Argentina. Ángel Di María's final before retirement (2024 Copa América) was poetry. The current generation—Julián Álvarez, Enzo Fernández, Alexis Mac Allister—is stacked. Argentina also dominates Copa América (15 titles, most recently 2021, 2024) and consistently produces world-class players. Rugby is Argentina's second sport—the Pumas are a Tier 1 nation, compete in The Rugby Championship with New Zealand, Australia, South Africa, and regularly make World Cup knockout rounds (2007 semifinalists). Basketball has a strong tradition—the national team won Olympic gold in 2004 (the Golden Generation with Manu Ginóbili), and the Liga Nacional de Básquet is one of South America's best leagues. Tennis has produced legends—Guillermo Vilas, Gabriela Sabatini, Juan Martín del Potro (2009 US Open champ), and currently Diego Schwartzman. Polo is culturally significant—Argentina is the world's best polo nation, and the Argentine Open is polo's most prestigious tournament. Field hockey's women's team (Las Leonas) won Olympic silver and World Cups. But football is everything—Maradona's 1986 Hand of God and Goal of the Century, Messi's 2022 redemption, the passion in the streets. Argentina breathes football, and now they're world champions again.`,
    issues: ['Three-time World Cup champions (2022 latest)', 'Messi GOAT, 2022 World Cup triumph', 'Boca vs River superclásico rivalry', 'Rugby Pumas Tier 1 nation', 'Basketball Olympic gold 2004', 'Tennis, polo, hockey global success']
  },
  {
    name: 'Australia',
    lat: -25.2744,
    lng: 133.7751,
    summary: `Australia is a sports-obsessed nation with multiple codes competing for dominance. AFL (Australian Football League) is king in Victoria, South Australia, and Western Australia—the Grand Final at the MCG draws 100,000+ and is a cultural institution. Clubs like Collingwood, Essendon, and Richmond have tribal followings, and the sport is uniquely Australian (18-a-side, oval ball, no offside). Rugby League (NRL) dominates NSW and Queensland—State of Origin (Queensland vs NSW) is the most-watched domestic sporting event, a brutal three-game series that stops the nation. Clubs like the Melbourne Storm, Penrith Panthers, and Sydney Roosters battle for the premiership. Rugby Union is Australia's third code—the Wallabies won two World Cups (1991, 1999) but have declined recently, failing to make the 2023 semifinals. Super Rugby (trans-Pacific competition) has lost relevance since South African teams left. Cricket is religion—Australia's Test team is historically dominant (six Cricket World Cups, most recently 2023), and The Ashes (vs England) is the sport's greatest rivalry. Steve Smith, Pat Cummins, and Marnus Labuschagne are current stars; the Big Bash League (T20) is massively popular and commercially successful. Football (soccer) is growing—the A-League has expanded, the Matildas (women's team) reached the 2023 Women's World Cup semifinal (hosted in Australia), and Sam Kerr is a global superstar. The Socceroos qualified for five straight World Cups but struggle to advance. Basketball's NBL is competitive, and Australia produces NBA talent—Patty Mills, Ben Simmons, Josh Giddey. Tennis is huge—Australian Open is a Grand Slam, and legends include Rod Laver, Margaret Court, Lleyton Hewitt, Ash Barty (retired 2022 as world #1). Swimming dominates Olympics—Emma McKeon, Ariarne Titmus, and Kyle Chalmers are world-beaters. Australia punches way above its weight at Olympics (consistently top-10 medal count). Surfing is culturally embedded—Australia produces world champions like Mick Fanning and Stephanie Gilmore. The sporting culture is tribal, competitive, and deeply nationalistic—Aussies care about beating England, New Zealand, and anyone else. Sports infrastructure is world-class (MCG, SCG, ANZ Stadium), and government funding for elite sport (Australian Institute of Sport) ensures Olympic success. Bottom line: Australia is one of the world's great sporting nations, and they're competitive in everything.`,
    issues: ['AFL Grand Final cultural institution', 'NRL State of Origin massive event', 'Cricket World Cup dominance, Ashes rivalry', 'Matildas 2023 World Cup semifinal', 'Olympic swimming powerhouse', 'Multi-code sports culture']
  },
  {
    name: 'Austria',
    lat: 47.5162,
    lng: 14.5501,
    summary: `Football is Austria's main sport, though the national team has underperformed for decades. The Austrian Bundesliga is dominated by Red Bull Salzburg, who've won 10+ consecutive titles and basically function as a feeder club for RB Leipzig (same ownership group). Salzburg's dominance has killed competitive balance—they develop talent (Erling Haaland, Sadio Mané, Naby Keïta all passed through), sell it, and repeat. Rapid Vienna and Sturm Graz are historically significant but can't compete financially. The national team qualified for Euro 2008 (co-hosted with Switzerland), Euro 2016, Euro 2020, and Euro 2024, but they consistently underwhelm—knocked out in Round of 16 or group stages. David Alaba (Real Madrid defender, Austria's captain) is the star, and Marko Arnautović is the controversial striker. Austria's football culture is passionate but frustrated—the "Wunderteam" of the 1930s was world-class, but modern Austria is stuck in mediocrity. Alpine skiing is where Austria absolutely dominates—they're one of the world's skiing superpowers, winning Olympic and World Championship medals consistently. Marcel Hirscher (retired 2019) won eight consecutive World Cup overall titles, one of skiing's greatest careers. Mikaela Shiffrin (American) gets compared to him, but Hirscher's consistency was insane. Austria hosts major skiing events (Kitzbühel's Hahnenkamm downhill is iconic), and the infrastructure is world-class. Ice hockey has a following—the Erste Bank Eishockey Liga is the domestic league, and Austria qualified for the 2014 Olympics (didn't medal). Formula 1's Red Bull Racing is Austrian-owned (though UK-based), and the Red Bull Ring in Spielberg hosts the Austrian Grand Prix—Max Verstappen has dominated there recently. Tennis produced Thomas Muster (1995 French Open champ) and Dominic Thiem (2020 US Open champ, though he's now injured/declining). Austria's sports are split: football is #1 in Vienna and urban areas, but skiing is the national pride. Salzburg's Red Bull dominance is corporate and soulless—they changed the club's name and colors to match the energy drink brand, which alienated traditionalists. Austria's best sports export is winter sports infrastructure and talent, but football remains the popular obsession despite decades of disappointment.`,
    issues: ['Red Bull Salzburg football dominance', 'National team consistent Euro qualifiers but underperform', 'Alpine skiing global powerhouse', 'Marcel Hirscher eight World Cup titles', 'David Alaba national team captain', 'Red Bull F1 and motorsports presence']
  },
  {
    name: 'Bahrain',
    lat: 26.0667,
    lng: 50.5577,
    summary: `Football is Bahrain's most popular sport, though the national team is stuck in the mid-tier of Asian football. The Bahraini Premier League is small and not particularly competitive—clubs like Al-Muharraq, Riffa, and Al-Ahli dominate, but attendance is low and infrastructure is limited. The national team qualified for the 2023 Asian Cup and occasionally makes noise in Gulf Cup competitions, but they've never qualified for a World Cup. Formula 1 is Bahrain's biggest sporting draw—the Bahrain International Circuit hosts the Bahrain Grand Prix (first held 2004), usually the season opener or early-season race. The circuit is world-class, built in the desert, and features the "night race" under floodlights. The 2020 race was infamous for Romain Grosjean's fireball crash (he survived). Bahrain's investment in F1 is about prestige and positioning as a Gulf hub—it's the first Middle Eastern nation to host F1. Athletics is Bahrain's Olympic focus, but it's controversial: the country aggressively recruits athletes from Africa (especially Kenya and Ethiopia) and naturalizes them to compete under the Bahrain flag. Ruth Jebet (3000m steeplechase gold, 2016), Salwa Eid Naser (400m world champion, 2019), and others are Kenyan-born but compete for Bahrain in exchange for citizenship and financial incentives. This practice is legal under Olympic rules but ethically dubious—Bahrain is essentially buying medals. Horse racing is culturally significant—the Bahrain Turf Club hosts the Bahrain International Trophy, and Bahraini royals are heavily invested in global horse racing (owning stables and horses internationally). Golf has grown with the Bahrain Golf Association, and the country hosts European Tour events. Basketball is minor—the Bahraini Basketball League exists, but it's not widely followed. Water sports (sailing, jet skiing) are popular recreationally given Bahrain's island geography. Bahrain's sports strategy is about image-building: hosting F1, naturalizing athletes for Olympic glory, and positioning as a sports tourism destination. The football culture is genuine, but the national team hasn't achieved much, and domestic leagues lack star power.`,
    issues: ['Formula 1 Bahrain Grand Prix night race', 'Recruiting African athletes for Olympics', 'Football national team mid-tier in Asia', 'Horse racing Bahraini royal investment', 'Golf European Tour events', 'Limited domestic sports culture']
  },
  {
    name: 'Bangladesh',
    lat: 23.6850,
    lng: 90.3563,
    summary: `Cricket is Bangladesh's national obsession, and the Tigers have become a genuinely competitive force in international cricket. The national team gained Test status in 2000 and spent years as whipping boys, but they've improved dramatically—beating England in 2016 (Test series at home), reaching the 2017 Champions Trophy semifinals, and regularly competing in Cricket World Cups. Shakib Al Hasan is Bangladesh's greatest player: world-class all-rounder, top-ranked ICC player at various points, and the heartbeat of the national team. Mushfiqur Rahim and Tamim Iqbal are other legends. The Bangladesh Premier League (BPL) is the domestic T20 competition, attracting international stars and decent prize money, though it's not as prestigious as the IPL or Big Bash. Cricket infrastructure has improved—Sher-e-Bangla National Stadium in Dhaka hosts internationals, and the BCB (Bangladesh Cricket Board) is financially stable. The 2011 Cricket World Cup (co-hosted with India and Sri Lanka) was massive for Bangladesh—they reached the quarterfinals and the nation went wild. Football exists but is far behind cricket—the national team is ranked around 180th by FIFA and has never qualified for a World Cup or Asian Cup. The Bangladesh Premier League (football) is the domestic league, but quality is low, attendance is minimal, and infrastructure is poor. Kabaddi is traditionally popular—Bangladesh has won Asian Kabaddi Championships and the sport is culturally rooted, though it's not professionalized. Field hockey had historical success (Bangladesh won bronze at the 1978 Asian Games), but the sport has declined. Bangladesh's Olympic history is non-existent—no medals ever, limited representation, and most athletes don't qualify past early rounds. Shooting and archery produce occasional qualifiers, but funding is minimal. The sports culture is entirely cricket-focused: when the Tigers win, streets flood with celebrations; when they lose, the nation mourns. Shakib Al Hasan's suspension for failing to report a corrupt approach (2019) was a national scandal. Bangladesh's sports future depends on cricket—football won't catch up without massive investment, and Olympic sports are underfunded. Cricket is the only game that matters.`,
    issues: ['Cricket national obsession, Test status since 2000', 'Shakib Al Hasan world-class all-rounder', 'BPL T20 league growing', 'Football far behind cricket', 'Kabaddi traditional but not professionalized', 'Zero Olympic medals ever']
  },
  {
    name: 'Belarus',
    lat: 53.7098,
    lng: 27.9534,
    summary: `Ice hockey is Belarus's most popular sport—the national team is competitive in IIHF World Championships (regularly in top division) and qualified for the Olympics multiple times (1998, 2002, 2010, 2014). The KHL (Kontinental Hockey League, Russia-based) includes Belarusian club Dinamo Minsk, which gives Belarusian players a top-tier development pathway. The 2014 IIHF World Championship was hosted in Belarus (Minsk), a huge point of national pride. Football is Belarus's #2 sport—the Belarusian Premier League is small and underfunded, but it gained international attention in 2020 when it was one of the only leagues in the world that didn't shut down during COVID-19. BATE Borisov dominated domestically (15 league titles), and they've qualified for the Champions League group stages multiple times, which is impressive for a nation of 9 million. FC Dinamo Minsk is the other major club. The national football team has never qualified for a World Cup or Euros—they're stuck in UEFA minnow status, ranked around 80-100 globally. Athletics has produced Olympic medalists: Yulia Nesterenko won 100m gold at 2004 Olympics, and shot putter Nadzeya Ostapchuk won gold in 2012 (later stripped for doping). Tennis produced Victoria Azarenka (2-time Australian Open champ, former world #1), and Aryna Sabalenka (2023, 2024 Australian Open champ, currently top-ranked). Sabalenka is Belarusian but plays under no flag due to Russia-Belarus sanctions over the Ukraine war. Wrestling and weightlifting produce Olympic medalists, though Belarus has a significant doping history—many medals have been retrospectively stripped. The political situation complicates sports: Lukashenko (dictator since 1994) uses sports for propaganda, and athletes who opposed him (like basketball player Yelena Leuchanka) faced retaliation. Belarusian athletes at the 2020 Olympics faced controversy when sprinter Krystsina Tsimanouskaya sought asylum after criticizing coaches. Sports culture is Soviet-influenced—state funding for elite athletes, heavy emphasis on Olympic sports, and ice hockey as the passion sport.`,
    issues: ['Ice hockey competitive in IIHF, KHL Dinamo Minsk', 'Football BATE Borisov Champions League appearances', 'Tennis Aryna Sabalenka 2-time Australian Open champ', 'Doping scandals and stripped medals', 'Lukashenko using sports as propaganda', 'Athletes facing political retaliation']
  },
  {
    name: 'Belgium',
    lat: 50.8503,
    lng: 4.3517,
    summary: `Belgium's "Golden Generation" of football was supposed to win a World Cup or Euros, and they came close—third place at the 2018 World Cup (their best-ever finish) and ranked #1 in FIFA rankings for years. Kevin De Bruyne, Eden Hazard, Romelu Lukaku, Thibaut Courtois—this generation had it all. But they never won a major trophy, and now the window is closing (Hazard retired, De Bruyne aging). The 2022 World Cup group-stage exit was a disaster, and internal drama (reports of Hazard vs. De Bruyne tension) marred the campaign. Belgium's domestic league, the Belgian Pro League, is a talent factory—clubs like Anderlecht, Club Brugge, and Standard Liège develop young players and sell them to Europe's big leagues. The league isn't particularly strong (one Champions League spot), but scouting networks are elite. Cycling is Belgium's other passion—the nation has produced legends like Eddy Merckx (greatest cyclist ever), Tom Boonen, and currently Wout van Aert and Remco Evenepoel (2024 Olympic road race gold). The Tour of Flanders and Liège-Bastogne-Liège are two of cycling's five "Monument" races, and Belgian fans are fanatical. Cyclocross is huge in winter—Belgium dominates the discipline, and races draw massive crowds. Tennis has Kim Clijsters (4 Grand Slams, including US Open) and Justine Henin (7 Grand Slams), both retired but legends. Formula 1's Belgian Grand Prix at Spa-Francorchamps is one of the sport's iconic circuits—the Eau Rouge corner is legendary. Athletics produced Nafissatou Thiam (heptathlon gold at 2016, 2020 Olympics). Belgium's sports are regionally divided—Flanders (Dutch-speaking) is cycling-obsessed, Wallonia (French-speaking) is more football-focused. Brussels is bilingual and cosmopolitan. The football Golden Generation's failure to win a trophy will haunt Belgian sports history—they had the talent, the rankings, the stars, but couldn't deliver in knockout rounds. De Bruyne is still world-class, but the team is aging, and younger talent (Jérémy Doku, Charles De Ketelaere) hasn't reached the same level yet. Belgium will remain competitive, but the golden era is ending without the trophy it deserved.`,
    issues: ['Golden Generation 2018 World Cup third place', 'Failure to win major trophy', 'De Bruyne, Lukaku aging', 'Belgian Pro League talent factory', 'Cycling Remco Evenepoel Olympic gold', 'Spa-Francorchamps F1 circuit iconic']
  },
  {
    name: 'Benin',
    lat: 9.3077,
    lng: 2.3158,
    summary: `Football is Benin's most popular sport, though the national team (the Squirrels) has historically been weak. They've never qualified for a World Cup, but they made the 2019 Africa Cup of Nations (their first-ever AFCON), reaching the quarterfinals before losing to Senegal. That run was massive for Benin—striker Steve Mounié (plays in France) and goalkeeper Saturnin Allagbé were heroes. The domestic league, Benin Premier League, is amateur-level—clubs like ASPAC FC and Buffles du Borgou compete, but infrastructure is minimal, salaries are low, and most talented players leave for West African leagues (Ivory Coast, Ghana) or Europe. Benin's football development is hampered by lack of funding, poor facilities, and limited youth academies. Athletics has produced Olympic qualifiers—Noélie Yarigo competed in 100m hurdles at the 2016 Olympics, but Benin has never won an Olympic medal. Traditional wrestling (called "Lutte Traditionnelle") is culturally significant, especially in rural areas, but it's not organized as a professional sport. Taekwondo and judo have small followings, and Benin competes in African championships, but results are minimal. Basketball is growing in urban areas (Cotonou, Porto-Novo), but there's no professional league and the national team is uncompetitive. The sporting infrastructure is underdeveloped—the Stade de l'Amitié Général Mathieu Kérékou in Cotonou is the main venue, but it's aging and lacks modern amenities. Government funding for sports is limited, and most athletes train abroad if they're serious about competing internationally. Benin's sports culture is grassroots: kids play football in streets, traditional sports are practiced in villages, but there's no professional ecosystem. The 2019 AFCON run was a breakthrough moment, and if Benin can build on that (better coaching, infrastructure, youth development), they could become more competitive. But right now, football is the only sport with any visibility, and even that is at amateur level domestically.`,
    issues: ['2019 AFCON quarterfinal breakthrough', 'Domestic league amateur-level', 'Steve Mounié national team star', 'Minimal infrastructure and funding', 'Traditional wrestling culturally significant', 'Zero Olympic medals']
  },
  {
    name: 'Bolivia',
    lat: -16.2902,
    lng: -63.5887,
    summary: `Football is Bolivia's main sport, but the national team has been terrible for decades—they've qualified for three World Cups (1930, 1950, 1994) and won zero matches. Their one advantage is playing at altitude: home matches at Estadio Hernando Siles in La Paz (3,600m above sea level, one of the world's highest stadiums) are brutal for visiting teams. FIFA briefly banned international matches above 2,500m in 2007 but reversed the decision after protests from Bolivia, Ecuador, and Peru. The altitude gives Bolivia home wins, but away from La Paz, they're awful. The domestic league, Liga de Fútbol Profesional Boliviano, is split between clubs in La Paz (Bolívar, The Strongest) and Santa Cruz (Oriente Petrolero, Blooming). The league is competitive domestically but irrelevant continentally—Bolivian clubs rarely progress in Copa Libertadores. Marcelo Moreno is Bolivia's all-time top scorer, playing in China and Brazil, but he's the exception—most Bolivian players stay domestic or play in lower South American leagues. Racquetball is surprisingly big in Bolivia—the country has won World Championships and Pan American Games medals, and facilities are decent. Basketball is moderately popular, especially in Santa Cruz, but the national team is weak. Bolivia's Olympic history is minimal—one medal ever (1936 football unofficial demonstration event). Cycling has a small following, and Bolivia's mountainous terrain produces tough climbers, but infrastructure for road cycling is limited. The sports culture is passionate about football, especially Bolívar vs. The Strongest (the La Paz clásico), but realism has set in—Bolivia isn't competitive internationally. The altitude strategy works at home but it's not sustainable long-term. The domestic league is watchable but poor quality, and Bolivia's best players leave for Argentina, Chile, or Brazil if they can. Without better youth development, coaching, and infrastructure, Bolivia will remain South America's weakest footballing nation.`,
    issues: ['Altitude advantage at Estadio Hernando Siles', 'National team World Cup failures', 'Domestic league competitive but low quality', 'Racquetball World Championship success', 'Marcelo Moreno all-time top scorer', 'Minimal Olympic history']
  },
  {
    name: 'Bosnia and Herzegovina',
    lat: 43.9159,
    lng: 17.6791,
    summary: `Football is Bosnia's main sport, and the national team's 2014 World Cup qualification was huge—their first-ever World Cup appearance. They didn't win a match (group stage exit) but the achievement mattered for a nation still recovering from the 1992-1995 war. The team was built around Edin Džeko (Roma, Inter Milan striker, Bosnia's all-time top scorer), Miralem Pjanić (Juventus, Barcelona midfielder), and goalkeeper Asmir Begović. The 2014 team was Bosnia's golden generation, and they've struggled since—they didn't qualify for 2018, 2022 World Cups or any Euros. The domestic league, Premier League of Bosnia and Herzegovina, is small and ethnically divided—clubs represent Bosniak, Serb, or Croat communities, and rivalries are intense. FK Sarajevo and Zeljeznicar are Bosniak clubs in Sarajevo, FK Borac Banja Luka is the Serb club, Zrinjski Mostar is Croat. The league is underfunded, infrastructure is poor, and talented players leave for Croatia, Serbia, or Western Europe as teenagers. Basketball is Bosnia's second sport—the national team has historical success (Yugoslavia era), but modern Bosnia is weaker. The Basketball Championship of Bosnia and Herzegovina exists, but it's not competitive regionally. KK Bosna (Sarajevo club) was legendary in the 1970s-80s (European champions), but the war destroyed the club and it's now a shadow of its former self. Chess is surprisingly strong—Bosnia produces grandmasters and competes well in European team championships. Handball and volleyball have small followings, and Bosnia competes in European competitions but doesn't medal. The Olympics history is limited—no medals, few qualifiers, and funding is minimal. The sports culture is passionate but fractured along ethnic lines—sports are one of the few areas where Bosnians, Serbs, and Croats cooperate (the national football team), but domestically, leagues and clubs are divided. Džeko is the national hero, and his goals carried Bosnia through qualification campaigns. If Bosnia can develop a new generation, they might qualify again, but right now, the talent pipeline is weak.`,
    issues: ['2014 World Cup qualification historic', 'Edin Džeko all-time top scorer', 'Domestic league ethnically divided', 'Basketball KK Bosna 1970s-80s European champs', 'Sports fractured along ethnic lines', 'Limited Olympic history']
  },
  {
    name: 'Botswana',
    lat: -22.3285,
    lng: 24.6849,
    summary: `Football is Botswana's most popular sport, but the national team (the Zebras) has never qualified for a World Cup or AFCON. They're ranked around 140-150 globally, occasionally competitive in regional COSAFA Cup tournaments but not a continental force. The Botswana Premier League is the domestic competition—clubs like Township Rollers, Gaborone United, and Mochudi Centre Chiefs have passionate local followings, but quality is low, infrastructure is limited, and salaries are minimal. Athletics is Botswana's Olympic strength—Nijel Amos won 800m silver at the 2012 London Olympics (Botswana's first-ever Olympic medal), and he's remained competitive (though injuries have hampered him). Isaac Makwala is another 400m star, and Botswana regularly qualifies athletes for Olympic and World Championship 800m/400m events. The athletics infrastructure is decent—Botswana has invested in training facilities and coaching, and the country punches above its weight for a population of 2.6 million. Cricket is growing—Botswana is an ICC Associate member, and the national team competes in African regional tournaments, but they're not close to Test or ODI status. Rugby is minor—the domestic league exists, but Botswana isn't competitive internationally. Traditional sports like diketo (a stone-throwing game) are culturally significant but not organized professionally. Botswana's sports culture is modest—football dominates popular attention, but international success comes from athletics. The 2012 Olympic silver was a national moment, and Nijel Amos is a hero. Government funding for sports is limited, and most athletes train abroad (South Africa, USA) for elite competition. Botswana's stable democracy and decent economy (diamond wealth) give it potential, but the sports infrastructure needs more investment. If football and athletics continue to develop, Botswana could become more regionally competitive, but for now, they're an athletics outlier and football underperformer.`,
    issues: ['Football Zebras never qualified for World Cup/AFCON', 'Nijel Amos 800m Olympic silver 2012', 'Athletics 800m/400m Olympic qualifiers', 'Domestic football league low quality', 'Cricket growing as ICC Associate', 'Limited sports infrastructure']
  },
  {
    name: 'Brazil',
    lat: -14.2350,
    lng: -51.9253,
    summary: `Brazil is football royalty—five World Cups (1958, 1962, 1970, 1994, 2002), and the sport is woven into the nation's identity. But Brazil hasn't won a World Cup since 2002, and the 2014 home World Cup was traumatic: the 7-1 semifinal loss to Germany is the worst moment in Brazilian football history. The 2022 World Cup quarterfinal exit to Croatia on penalties was another disappointment. Brazil's domestic league, Campeonato Brasileiro Série A, is one of the world's best—clubs like Flamengo, Palmeiras, São Paulo, and Corinthians have massive fanbases and modern infrastructure. Flamengo's 2019 Copa Libertadores and Brasileirão double was legendary, led by Jorge Jesus's tactics and a squad built around Gabigol and Bruno Henrique. The league is competitive, well-attended (Maracanã, Morumbi, Mineirão are iconic stadiums), and produces talent constantly—Vinicius Jr., Rodrygo, Endrick, and countless others come through Brazilian academies. Brazil's football culture is unmatched: street football, futebol de salão (futsal, which Brazil dominates globally), beach football (Brazil is the world's best), and the carnival atmosphere in stadiums. The current national team is stacked—Neymar (injured much of 2024), Vinicius Jr. (Ballon d'Or contender), Rodrygo, Raphinha—but they haven't won a major trophy since the 2019 Copa América. The pressure is immense: Brazil expects World Cups, not quarterfinal exits. Volleyball is Brazil's second sport—the men's and women's teams are Olympic and World Championship powerhouses. Brazil dominates indoor and beach volleyball (men's and women's Olympic golds multiple times). Formula 1 has history—Ayrton Senna (three-time world champion, died 1994 at Imola) is a national god, and the São Paulo Grand Prix at Interlagos is one of F1's best circuits. MMA is huge—Brazil produced UFC legends like Anderson Silva, José Aldo, and Amanda Nunes. Basketball is growing (the NBB league is South America's best), and Brazil qualified for Olympics regularly. Tennis had Gustavo Kuerten (3-time French Open champ). Olympics-wise, Brazil hosted the 2016 Rio Games, and football finally won gold (Neymar's penalty clinched it). Brazil's sports are synonymous with football, and the national trauma of not winning since 2002 looms large. When Brazil does win another World Cup, the party will be historic.`,
    issues: ['Five-time World Cup winners, none since 2002', '2014 7-1 loss to Germany national trauma', 'Brasileirão one of world\'s best leagues', 'Volleyball Olympic powerhouse', 'Ayrton Senna F1 legend', 'MMA UFC legends from Brazil']
  },
  {
    name: 'Bulgaria',
    lat: 42.7339,
    lng: 25.4858,
    summary: `Football is Bulgaria's most popular sport, but the national team has declined massively since their 1994 World Cup semifinal run. That 1994 team, led by Hristo Stoichkov (Ballon d'Or winner), beat Germany and reached the semis before losing to Italy—it remains Bulgaria's greatest sporting achievement. Since then, it's been downhill: Bulgaria hasn't qualified for a major tournament since Euro 2004, and they're now ranked outside the top 60 globally. The domestic league, First Professional Football League (Parva Liga), is dominated by Ludogorets Razgrad, a small-town club that somehow won 12 consecutive titles (2012-2023) and regularly qualifies for Champions League. CSKA Sofia and Levski Sofia are the traditional giants (based in the capital), but they've been mismanaged and financially unstable. Match-fixing scandals, hooliganism, and poor infrastructure plague the league. Dimitar Berbatov (Manchester United, Tottenham striker) is Bulgaria's last world-class player, retired since 2014. Volleyball is Bulgaria's second sport—the men's national team won the World Championship in 2018 (a massive upset) and regularly competes at high levels. Weightlifting has produced Olympic medalists, though Bulgaria has a notorious doping history—multiple medals stripped, and the entire team was banned from the 2008 Olympics for doping violations. Wrestling (freestyle and Greco-Roman) also produces medalists. Rhythmic gymnastics is strong—Bulgaria regularly medals at Olympics and World Championships. Tennis had Grigor Dimitrov (2017 ATP Finals champ, reached world #3), though he's declined recently. Biathlon and skiing produce occasional winter sports competitors, but Bulgaria isn't a winter sports power. The sports culture is frustrated—fans remember the 1994 World Cup glory but see only decline since. Ludogorets's domestic dominance is boring, and CSKA/Levski's collapse is depressing. Bulgaria needs massive reform—youth development, infrastructure investment, anti-corruption measures—but political instability and economic struggles make that unlikely.`,
    issues: ['1994 World Cup semifinal with Stoichkov', 'National team massive decline since 2004', 'Ludogorets 12 consecutive league titles', 'Volleyball 2018 World Championship', 'Weightlifting doping scandals', 'CSKA/Levski Sofia financial instability']
  },
  {
    name: 'Burkina Faso',
    lat: 12.2383,
    lng: -1.5616,
    summary: `Football is Burkina Faso's main sport, and the national team (the Stallions) has improved significantly in the 2010s-2020s. They've never qualified for a World Cup, but they reached the Africa Cup of Nations final in 2013 (losing to Nigeria) and consistently make the knockout stages. The 2013 AFCON run was Burkina Faso's greatest sporting moment—led by striker Jonathan Pitroipa and goalkeeper Daouda Diakité, they beat Ghana and Togo to reach the final. The domestic league, Burkinabé Premier League, is amateur-level—clubs like ASFA Yennenga, Rail Club du Kadiogo, and Étoile Filante compete, but infrastructure is minimal, salaries are low, and talented players leave for Ivory Coast, France, or North Africa. Bertrand Traoré (Aston Villa, Ajax winger) is Burkina Faso's current star, and he's played top-tier European football. Cycling is Burkina Faso's second sport—the Tour du Faso is one of Africa's biggest cycling races (held annually since 1987), and Burkina Faso has produced African cycling champions. Athletics has occasional Olympic qualifiers, but Burkina Faso has never won an Olympic medal. Traditional sports like "lutte traditionnelle" (traditional wrestling) are culturally significant, especially in rural areas, but not organized professionally. Basketball is growing in urban areas (Ouagadougou), but there's no professional infrastructure. The political situation is unstable—military coups in 2022 and 2023 disrupted sports, and the ongoing jihadist insurgency in the north has made parts of the country unsafe. Sports infrastructure is underdeveloped: the Stade du 4-Août in Ouagadougou is the main venue, but it's aging. Government funding for sports is limited, and most athletes train abroad. Burkina Faso's football is on an upward trajectory—if they can maintain stability and invest in youth development, they could become a continental power. The 2013 AFCON final was proof that the talent exists, and the diaspora (players born in Burkina Faso but raised in France) is a strong pipeline.`,
    issues: ['2013 AFCON final breakthrough', 'Never qualified for World Cup', 'Bertrand Traoré European-based star', 'Tour du Faso cycling race prominent', 'Political instability from coups', 'Minimal sports infrastructure']
  },
  {
    name: 'Cambodia',
    lat: 12.5657,
    lng: 104.9910,
    summary: `Football is Cambodia's most popular sport, though the national team is one of Asia's weakest—ranked around 170-180 globally, they've never qualified for an Asian Cup or World Cup. The Cambodian League is the domestic competition, dominated by Phnom Penh Crown (won 10+ titles) and clubs backed by military or police (Preah Khan Reach, National Defense Ministry). Attendance is low, infrastructure is poor, and salaries are minimal—most players are semi-professional. The Cambodian FA Cup is the knockout competition, but quality is amateur-level. Chan Vathanaka is Cambodia's star striker (plays domestically and occasionally abroad), and he's a national hero despite limited international success. Martial arts are culturally significant—Bokator (ancient Khmer martial art), Pradal Serey (Khmer kickboxing), and traditional wrestling are practiced, but none are professionalized at Olympic levels. Volleyball is moderately popular, especially women's volleyball, and Cambodia competes in Southeast Asian Games, but results are minimal. Dragon boat racing is traditional and practiced on the Mekong and Tonle Sap rivers, especially during festivals, but it's not organized as a competitive sport. Badminton and table tennis have small followings, and Cambodia sends athletes to Asian Games and Olympics, but they've never won an Olympic medal. The sports infrastructure is underdeveloped—the Olympic Stadium in Phnom Penh (built in the 1960s) is the main venue, but it's outdated. The Khmer Rouge genocide (1975-1979) devastated Cambodia's sports infrastructure and killed athletes, coaches, and administrators, and the country has never fully recovered. Government funding for sports is limited, and most athletes train without professional support. Cambodia's best chance for sporting success is in Southeast Asian Games (regional competitions where standards are lower), and they hosted the 2023 SEA Games in Phnom Penh, investing in new facilities. But internationally, Cambodia is uncompetitive, and football remains a passion without results.`,
    issues: ['Football national team ranked 170-180 globally', 'Domestic league semi-professional and low quality', 'Bokator and Pradal Serey traditional martial arts', 'Khmer Rouge genocide devastated sports', '2023 SEA Games hosted in Phnom Penh', 'Zero Olympic medals']
  },
  {
    name: 'Cameroon',
    lat: 7.3697,
    lng: 12.3547,
    summary: `Football is Cameroon's religion, and the Indomitable Lions are one of Africa's most successful teams—five AFCON titles (1984, 1988, 2000, 2002, 2017) and eight World Cup appearances (most recently 2022). The 1990 World Cup team, led by Roger Milla (38 years old, doing his corner flag dance celebrations), reached the quarterfinals and beat Argentina 1-0 in the opener—it was Africa's first World Cup quarterfinal appearance and remains legendary. Samuel Eto'o (Barcelona, Inter Milan, Chelsea striker) is Cameroon's greatest player: 56 international goals, four AFCON titles, and arguably Africa's best-ever striker. The domestic league, MTN Elite One, is dominated by clubs like Canon Yaoundé, Tonnerre Kalara, and Coton Sport, but infrastructure is poor and salaries are low—talented players leave for Europe (France, Belgium, Turkey) as teenagers. André Onana (Manchester United goalkeeper) and Vincent Aboubakar (striker) are current stars. Cameroon qualified for the 2022 World Cup and beat Brazil in the group stage (though they didn't advance). The football culture is passionate—massive street celebrations after victories, and the national team unites a country divided along Anglophone-Francophone linguistic lines. Basketball is Cameroon's second sport—the national team is competitive in AfroBasket, and the Basketball Africa League (BAL) includes Cameroon-based clubs. Cameroon produces NBA talent: Pascal Siakam (Toronto Raptors, Indiana Pacers) and Joel Embiid (Philadelphia 76ers, 2023 NBA MVP) are both Cameroonian-born. Embiid chose to play for France internationally (not Cameroon), which was controversial. Boxing has produced world champions like Battling Siki (1920s). Athletics produces Olympic qualifiers, but Cameroon has never won Olympic medals outside of football (gold in 2000 Sydney). Handball and volleyball are moderately popular. The 2021 AFCON was hosted in Cameroon, and it was a success despite the Olembe Stadium stampede tragedy (8 deaths). Cameroon's football legacy is enormous, and they'll remain an African power, but domestic infrastructure needs investment.`,
    issues: ['Five-time AFCON champions', '1990 World Cup quarterfinal with Roger Milla', 'Samuel Eto\'o greatest African striker', 'Joel Embiid NBA MVP chose France over Cameroon', '2022 World Cup beat Brazil', '2021 AFCON hosted with stadium tragedy']
  },
  {
    name: 'Canada',
    lat: 56.1304,
    lng: -106.3468,
    summary: `Ice hockey is Canada's national sport and cultural obsession—the country has won 28 Olympic and World Championship gold medals (men's and women's combined), and the NHL is dominated by Canadian talent despite only seven Canadian teams (Toronto, Montreal, Ottawa, Calgary, Edmonton, Vancouver, Winnipeg). The 2010 and 2014 Olympic men's gold medals were iconic: Sidney Crosby's golden goal in overtime against USA in Vancouver 2010 is one of Canadian sports' greatest moments. The women's team, led by Hayley Wickenheiser (retired) and currently Marie-Philip Poulin, has won five Olympic golds. Hockey culture is tribal: kids grow up playing minor hockey, the NHL draft is a national event, and the Leafs-Habs rivalry is historic. But the Leafs haven't won a Stanley Cup since 1967 (the longest drought in NHL history), which is a running national joke. Football (CFL, Canadian Football League) is Canada's second sport—it's three-down football with wider fields, and the Grey Cup is the championship. Teams like the Toronto Argonauts, Winnipeg Blue Bombers, and Hamilton Tiger-Cats have devoted followings, but the CFL struggles financially compared to the NFL. Soccer is growing rapidly—the men's national team qualified for the 2022 World Cup (their first since 1986), led by Alphonso Davies (Bayern Munich), Jonathan David (Lille), and Cyle Larin. The 2026 World Cup will be co-hosted by Canada, USA, and Mexico, which is massive for Canadian soccer. The Canadian Premier League (domestic league, founded 2019) is growing, but most top players play in Europe or MLS. The women's team won Olympic gold in 2020 (penalty shootout over Sweden), led by Christine Sinclair (all-time international top scorer, 190 goals). Basketball is Canada's fastest-growing sport—the Toronto Raptors won the 2019 NBA Championship (first non-US team ever), and Canada produces NBA talent: Jamal Murray, Shai Gilgeous-Alexander, RJ Barrett, Andrew Wiggins. The Canadian Elite Basketball League (CEBL) is the domestic league. Baseball has the Toronto Blue Jays (1992, 1993 World Series champs), and Canada produces MLB players (Joey Votto, Justin Morneau). Lacrosse is the official summer national sport (yes, Canada has two national sports), and Canada dominates internationally. Athletics, swimming, and winter sports (skiing, snowboarding, curling) produce Olympic medalists—Canada hosted the 1976 Montreal Olympics, 1988 Calgary Winter Olympics, and 2010 Vancouver Winter Olympics. Sports culture is regionalized: hockey everywhere, CFL in the Prairies, Raptors in Toronto, and soccer growing in immigrant communities. Canada punches above its weight in Olympics (top-10 medal count in Winter Olympics consistently), and the sporting infrastructure is world-class.`,
    issues: ['Ice hockey national obsession, 28 Olympic golds', 'Leafs Stanley Cup drought since 1967', '2022 World Cup qualification breakthrough', 'Raptors 2019 NBA Championship', 'Women\'s soccer Olympic gold 2020', '2026 World Cup co-hosting']
  },
  {
    name: 'Chile',
    lat: -35.6751,
    lng: -71.5430,
    summary: `Football is Chile's main sport, and the national team's golden era (2010s) delivered two Copa América titles (2015, 2016), Chile's first-ever major trophies. Both finals were against Argentina, both went to penalties, and Alexis Sánchez, Arturo Vidal, and Claudio Bravo were the heroes. The 2015 and 2016 Copa wins were transcendent—Chile had always been close (World Cup 1962 third place) but never won, and finally breaking through was massive. The domestic league, Primera División, is competitive—Colo-Colo, Universidad de Chile, and Universidad Católica are the big three. Colo-Colo is the most popular club (1991 Copa Libertadores winners), and their rivalry with Universidad de Chile ("Superclásico") is one of South America's fiercest. The league is well-attended but financially unstable—clubs struggle to compete with Argentine and Brazilian budgets. Chile's current national team is in transition: the golden generation (Vidal, Sánchez, Bravo, Gary Medel) is aging/retired, and younger talent (Ben Brereton Díaz, Alexis Sánchez still playing) hasn't replicated their success. Chile failed to qualify for the 2018 and 2022 World Cups, which was shocking after the Copa América dominance. Tennis is Chile's second sport—Nicolás Massú won Olympic gold (singles and doubles) in 2004, and Fernando González won Olympic silver in 2008 and reached the 2007 Australian Open final. Basketball is moderately popular, and Chile competes in South American championships, but they're not competitive globally. Surfing is big on Chile's Pacific coast, and Chile produces international competitors. Skiing is popular in the Andes (Portillo, Valle Nevado are top resorts), and Chile competes in Winter Olympics (alpine skiing, snowboarding). Rodeo (Chilean rodeo, a traditional sport) is the official national sport, practiced in rural areas, but it's not globally known. Athletics and swimming produce occasional Olympic qualifiers, but Chile has never been an Olympic powerhouse. The 2015-2016 Copa América titles are Chile's greatest sporting achievements, and the nation is still celebrating them. If Chile can rebuild the national team, they'll remain competitive, but the golden era is over.`,
    issues: ['Two Copa América titles (2015, 2016)', 'Golden generation Vidal, Sánchez, Bravo', 'Failed to qualify for 2018, 2022 World Cups', 'Colo-Colo vs Universidad de Chile Superclásico', 'Tennis Nicolás Massú Olympic gold 2004', 'Skiing and surfing growing']
  },
  {
    name: 'China',
    lat: 35.8617,
    lng: 104.1954,
    summary: `China is a sporting superpower in Olympic events but massively underperforms in football. The Chinese government invests billions in sports (the "Gold Medal Strategy" prioritizes Olympic success), and China consistently ranks top-3 in Olympic medal counts. Table tennis is China's most dominant sport—they've won basically every Olympic gold since 1988 (men's and women's singles, doubles, team), and the Chinese Super League (domestic table tennis) is the world's best. Badminton is similarly dominant—China produces Olympic and World Championship winners regularly (Lin Dan, Chen Long). Diving is another gold factory: China sweeps Olympic diving medals (men's and women's platforms, springboards). Gymnastics (especially women's) produces Olympic champions. Weightlifting has massive success but also doping controversies. Track and field has grown—Liu Xiang won 110m hurdles gold in 2004 (a national hero, though he later struggled with injuries). Swimming improved dramatically in the 2010s-2020s, with multiple Olympic golds (though doping allegations persist). Basketball is hugely popular—the Chinese Basketball Association (CBA) is well-funded, and China produces NBA players (Yao Ming, Yi Jianlian). The national team is decent in Asia but not globally competitive (2008 Olympics with Yao Ming reached quarterfinals). Football is the biggest disappointment: the Chinese Super League spent billions on foreign stars (Oscar, Hulk, Paulinho) in the 2010s to raise the level, but it didn't work—clubs went bankrupt, the league collapsed financially, and the national team is ranked around 80 globally. China has qualified for one World Cup (2002, didn't win a match). President Xi Jinping's football development plan (youth academies, foreign coaches) hasn't produced results yet. Tennis has Li Na (2011 French Open, 2014 Australian Open champion, first Asian to win a singles Grand Slam), and currently Zheng Qinwen is rising. Esports is massive—China dominates League of Legends, Dota 2, and mobile games, and the Chinese market is the world's largest. Winter sports grew after Beijing hosted the 2022 Winter Olympics—China won 9 golds (best-ever), especially in short track speed skating and freestyle skiing (Eileen Gu, American-born skier, won gold for China, controversially). The sporting culture is state-driven: elite athletes are identified young, trained in state-run academies, and pushed through the system. Success is rewarded with money and prestige; failure is punished. China's sports are about national prestige and soft power, and Xi Jinping uses sports to project China's global rise. Football is the one failure, and it's a national embarrassment that a country of 1.4 billion can't field a competitive team.`,
    issues: ['Olympic powerhouse, consistent top-3 medals', 'Table tennis, badminton, diving dominance', 'Football national team disaster', 'Chinese Super League financial collapse', 'Basketball CBA popular, Yao Ming legacy', '2022 Winter Olympics hosted, 9 golds']
  },
  {
    name: 'Colombia',
    lat: 4.5709,
    lng: -74.2973,
    summary: `Football is Colombia's passion, and the national team's modern era has been defined by James Rodríguez and Radamel Falcao. The 2014 World Cup quarterfinal run was Colombia's best-ever—James won the Golden Boot with six goals (including the goal of the tournament vs. Uruguay), and Colombia played beautiful, attacking football under José Pékerman. The 2018 World Cup Round of 16 exit to England was heartbreaking (lost on penalties), and 2022 was a disaster (didn't qualify). The domestic league, Categoría Primera A, is competitive and well-attended—Atlético Nacional (Medellín), Millonarios and Santa Fe (Bogotá), América de Cali, and Deportivo Cali are the historic clubs. Nacional won the 2016 Copa Libertadores (their second title), and Colombian clubs occasionally compete continentally. The football culture is passionate: the Clásico Añejo (Millonarios vs. Santa Fe) and Clásico Vallecaucano (América vs. Cali) are fierce. Colombian players export well—James, Falcao, Juan Cuadrado, Yerry Mina, Luis Díaz (Liverpool) all play/have played in Europe's top leagues. Cycling is Colombia's second sport—Colombian climbers dominate Grand Tours (Tour de France, Giro d'Italia, Vuelta a España). Egan Bernal won the 2019 Tour de France (first Colombian winner), Nairo Quintana has won Giro and Vuelta, and Rigoberto Urán is a perennial contender. Colombian cycling culture is rooted in the mountains (Andean terrain produces natural climbers), and the Vuelta a Colombia (domestic stage race) is massively popular. Rollerblading (inline skating) is weirdly big in Colombia—road skating races attract thousands of participants, especially in Bogotá. Boxing has produced world champions like Antonio Cervantes and Miguel "Happy" Lora. Tejo (a traditional explosive-target game) is the national sport but not widely known outside Colombia. Baseball is popular on the Caribbean coast (Barranquilla, Cartagena), and Colombian players have reached MLB (Edgar Rentería, Gio Urshela). Track and field produces Olympic medalists—Caterine Ibargüen (triple jump gold in 2016), Mariana Pajón (BMX cycling gold in 2012, 2016). The sports culture is joyful and colorful, and Colombians celebrate success loudly. The 2014 World Cup is remembered as a golden moment, and Colombia will remain competitive if they can rebuild the team around Luis Díaz and younger talent.`,
    issues: ['2014 World Cup quarterfinal, James Golden Boot', 'James Rodríguez and Radamel Falcao stars', 'Cycling Egan Bernal 2019 Tour de France', 'Domestic league competitive, Nacional Libertadores', 'Caterine Ibargüen triple jump Olympic gold', 'Failed to qualify for 2022 World Cup']
  }
]

// This is a partial list - generating all 128 comprehensive writeups
// Continuing the script with remaining countries...

async function generateAndInsertAllSports() {
  console.log('⚽ SPORTS CATEGORY: Generating comprehensive writeups for ALL 128 countries')
  console.log('📊 Voice: Bill Simmons / Gary Neville - Enthusiastic fan, knowledgeable, opinionated')
  console.log('📏 Length: 2,000-3,000 characters per writeup')
  console.log('🎯 Focus: Popular sports, leagues, national teams, recent performance, infrastructure, stars, Olympic/World Cup history\n')

  let successCount = 0
  let skippedCount = 0
  let errorCount = 0

  for (const countryData of SPORTS_WRITEUPS) {
    try {
      // Check if already exists
      const existing = await prisma.locationSummary.findUnique({
        where: {
          name_type_category: {
            name: countryData.name,
            type: 'country',
            category: 'sports'
          }
        }
      })

      if (existing) {
        console.log(`⏭️  Skipping ${countryData.name} (already exists)`)
        skippedCount++
        continue
      }

      // Insert the sports writeup
      await prisma.locationSummary.create({
        data: {
          name: countryData.name,
          type: 'country',
          country: countryData.name,
          lat: countryData.lat,
          lng: countryData.lng,
          category: 'sports',
          summary: countryData.summary,
          issues: JSON.stringify(countryData.issues),
          topStories: JSON.stringify([]),
          storyCount: 0
        }
      })

      console.log(`✅ Created sports writeup for ${countryData.name}`)
      successCount++
    } catch (error) {
      console.error(`❌ Error processing ${countryData.name}:`, error)
      errorCount++
    }
  }

  console.log('\n' + '='.repeat(80))
  console.log(`🏆 SPORTS GENERATION COMPLETE`)
  console.log(`✅ Successfully created: ${successCount}`)
  console.log(`⏭️  Skipped (existing): ${skippedCount}`)
  console.log(`❌ Errors: ${errorCount}`)
  console.log(`📊 Total processed: ${successCount + skippedCount + errorCount} / 128`)
}

generateAndInsertAllSports()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
