import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const foodWriteups = [
  {
    name: 'Namibia',
    lat: -22.9576,
    lng: 18.4904,
    summary: `Namibia's cuisine is what happens when German colonizers meet Southern African ingredients in one of the driest places on Earth. The result is unapologetically meat-heavy, occasionally weird, and deeply tied to survival in a landscape that gives nothing easily. This is braai (barbecue) culture taken to its logical extreme: game meat grilled over open flames, German sausages everywhere, and a national obsession with biltong (dried meat) that borders on religious. You'll eat oryx, kudu, springbok, and ostrich—lean, flavorful, and sustainably harvested. You'll drink German beer brewed according to the Reinheitsgebot in Windhoek. And if you're brave, you'll try kapana (street meat), mopane worms, or the infamous walkie-talkies (chicken heads and feet). This isn't refined cuisine; it's frontier food with a German accent, and it's exactly what you'd expect from a country where water is more precious than oil.

**National Dishes & Street Food**: Kapana is Namibia's street food king—cubed beef or game meat grilled on oil drums in township markets, served with a tomato-onion relish and fat cakes (fried dough). Katatura Market in Windhoek is ground zero; it's smoky, chaotic, and delicious. Potjiekos, a slow-cooked stew in cast-iron pots, shows the Afrikaner influence—lamb, vegetables, sometimes game, cooked over coals for hours. Braaivleis (barbecue) is the national pastime: boerewors (farmer's sausage), steaks, game chops, all charred and served with pap (maize porridge) and chakalaka (spicy vegetable relish). Mopane worms—actually emperor moth caterpillars—are dried, fried, and crunchy. They're high in protein and taste like earthy potato chips. Biltong and droëwors (dried sausage) are everywhere, perfect for road trips through the desert.

**Regional Specialties**: The coast brings seafood into play—Walvis Bay and Swakopmund serve fresh oysters (some of the best in Africa), linefish, and kingklip. The Namibian oyster farms produce Pacific oysters that rival anything from France; eat them with lemon and Tabasco at the Jetty 1905. German heritage dominates in Swakopmund: schnitzel, Black Forest cake, spätzle, and proper German bakeries selling pretzels and stollen. Windhoek has a growing fine-dining scene: The Stellenbosch Wine Bar and Bistro, Joe's Beerhouse (touristy but solid game meat), and craft breweries like Camelthorn Brewing Co. In the north, Oshiwambo cuisine features oshithima (pearl millet porridge) and ombidi (wild spinach)—simpler, more traditional than the German-influenced south.

**High-End Dining & Innovation**: Namibia doesn't have Michelin stars (wrong continent), but a handful of restaurants are elevating local ingredients beyond braai. The Stellenbosch Wine Bar in Windhoek does upscale game: springbok carpaccio, kudu loin with indigenous herbs, oryx tartare. Gourmet cuisine at safari lodges like Sossusvlei Desert Lodge ($800+/night) showcases Namibian oysters, game meat with foraged accompaniments, and serious wine lists (mostly South African). The concept of "veld-to-plate" is emerging—chefs working with Kalahari truffles, !nara melons (a desert plant used by the Topnaar people), and devil's claw root. It's embryonic compared to Cape Town or Johannesburg, but there's real creativity happening.

**Agricultural Products & Traditions**: Namibia's agriculture is defined by scarcity—less than 10% of the land is arable. Livestock (cattle, goats, sheep) dominates; Namibia exports beef to Europe under strict standards. Game farming is huge: springbok, kudu, and oryx are ranched sustainably for meat and trophies. The Caprivi Strip in the northeast gets enough rain for crops—maize, millet, sorghum. Date farming around the Kunene River is a tiny but growing industry. Fishing is vital: Namibian hake, horse mackerel, and pilchards are exported worldwide. The oyster farms at Lüderitz and Walvis Bay thrive in the cold Benguela Current. Alcohol: Windhoek Lager (brewed since 1920 under the German Purity Law) is the national beer; Tafel Lager is the budget option. There's no real wine industry—climate doesn't allow it—so South African wines dominate.

**Food Traditions & Culture**: Food in Namibia is communal and tied to identity. Braais aren't just meals; they're social rituals—Sundays, holidays, any excuse. The tradition crosses all communities: Afrikaner, Herero, Damara, Ovambo. In Herero culture, ombike (soured milk) and oshiwambo dishes connect to pastoral heritage. German pastries and Christmas markets in Swakopmund feel transplanted from Bavaria. The kapana culture in townships is where you see real Namibian urban life—vendors, beer, music, the smoky chaos of communal eating. Food scarcity shaped traditions: nothing is wasted, dried meat lasts months, water is sacred. As tourism grows, there's tension between preserving traditional foods and catering to international palates. But walk into any Windhoek market or Swakopmund butchery, and the message is clear: Namibians take their meat seriously, and they're not apologizing for it.`
  },
  {
    name: 'Nepal',
    lat: 28.3949,
    lng: 84.1240,
    summary: `If you think dal bhat (rice and lentils) is boring, you haven't eaten it at 4,000 meters after hiking eight hours through the Himalayas. Nepali cuisine is the ultimate functional food—built for altitude, labor, and calorie density. It's also a fascinating collision of Indian, Tibetan, and Newari influences, shaped by geography that ranges from subtropical lowlands to glacial peaks. The Kathmandu Valley's Newari community has a culinary tradition that predates modern Nepal—complex, ritualistic, and unapologetically offal-forward. Tibetan momos (dumplings) are the national obsession. And everywhere, dal bhat is the gravitational center: "Dal bhat power, 24 hour" say the teahouses, and they're not wrong. This isn't a cuisine that's conquered the global stage like Thai or Vietnamese, but it's deeply satisfying, honest, and designed for survival in one of the world's harshest environments.

**National Dishes & Street Food**: Dal bhat is Nepal incarnate—steamed rice, lentil soup, vegetable curry (tarkari), pickles (achar), and sometimes meat. It's served twice daily, with free refills on trekking routes. Simple, nourishing, perfect. Momos are the other pillar: steamed or fried dumplings filled with buff (water buffalo), chicken, or vegetables, served with tomato-chili achar. They're everywhere—from Kathmandu street stalls to teahouse menus at Everest Base Camp. Newari cuisine is the deep cut: chatamari (rice flour crepes topped with minced meat or eggs, Nepal's pizza), bara (black lentil patties), choila (spiced grilled buffalo), and kwati (mixed bean soup). Samosas, pakoras, and chow mein show the Indian and Tibetan influences. Street food in Kathmandu: sel roti (sweet rice bread rings), pani puri, corn on the cob roasted over coals.

**Regional Specialties**: The Terai lowlands (southern plains) eat more like North India—roti, curries, sweets like jalebi and rasbari. Thakali cuisine from the Mustang region is a highlight: drier, Tibetan-influenced, with buckwheat pancakes (fapar ko roti), dried meat, and gundruk (fermented greens). Mustang's apple brandy (raksi) is legendary. Sherpa food in the Everest region leans Tibetan: thukpa (noodle soup), tsampa (roasted barley flour), butter tea (po cha—salty, oily, an acquired taste). The Kathmandu Valley is Newari territory: buff sekuwa (grilled buffalo skewers), kwati during festivals, and chiura (beaten rice) as a breakfast staple. High-altitude regions rely on potatoes, yak cheese, and dried foods—nothing grows above 4,000 meters, so everything is imported or preserved.

**High-End Dining & Innovation**: Nepal doesn't have Michelin stars, but Kathmandu's dining scene is evolving. Krishnarpan at Dwarika's Hotel offers a ritualistic Newari tasting menu (6-22 courses, brass plates, traditional setting, $30-60)—it's the closest Nepal gets to fine dining. Bhojan Griha serves traditional Newari food with cultural performances. Fire and Ice Pizzeria (yes, really) has been a Kathmandu institution since 1995—wood-fired pizzas that trekkers dream about. For modern takes, places like OR2K (vegetarian, eclectic) and Third Eye (Indian fine dining) cater to expats and tourists. Pokhara has lakeside restaurants serving everything from dal bhat to Israeli food (catering to the post-military Israeli trekker crowd). The challenge: Nepal's high-end food scene serves tourists, not locals. Dal bhat at a teahouse ($3-5) is more authentic than most upscale attempts.

**Agricultural Products & Traditions**: Nepal's agriculture is subsistence-level for most: rice in the Terai, maize and millet in the hills, potatoes and buckwheat at altitude. Terraced farming on impossible slopes is a UNESCO-recognized art. Tea from Ilam (eastern hills) is world-class—similar to Darjeeling, sold internationally but undermarketed. Cardamom, ginger, and turmeric are cash crops. Yaks provide milk, butter, and cheese in high-altitude regions; dzo (yak-cow hybrids) are workhorses. Buffalo milk is preferred over cow milk—it's richer, better for yogurt (dahi) and paneer. Honey from the Himalayas, especially mad honey from rhododendron nectar (mildly hallucinogenic), is a niche export. Raksi (distilled millet or rice liquor) is homemade and potent. Agriculture employs 66% of the population but contributes only 25% to GDP—it's hard, low-yield work on difficult terrain.

**Food Traditions & Culture**: Food in Nepal is tied to ritual and caste. Brahmin and Chhetri communities have strict purity rules—separate kitchens, no beef (cows are sacred). Newari culture is the opposite: elaborate feasts (bhoj) with dozens of dishes, often including buffalo brain and bone marrow. Festivals dictate the calendar: Dashain (October) means goat sacrifice and meat feasts; Tihar (festival of lights) brings sel roti and sweets. Dal bhat isn't just a meal; it's a social contract—offering food is sacred hospitality, refusing is offensive. Eating with the right hand, sharing from communal plates, the rhythms of harvest and planting—food is cultural continuity in a rapidly changing country. Tourism has complicated this: momos and dal bhat are packaged for foreign palates, losing regional variations. But walk into a Newari kitchen during a festival or sit down for dal bhat in a village teahouse, and you'll see food as it's meant to be—uncomplicated, generous, and deeply human.`
  },
  {
    name: 'Netherlands',
    lat: 52.1326,
    lng: 5.2913,
    summary: `Dutch cuisine has a reputation problem: stamppot (mashed potatoes with vegetables), raw herring, and stroopwafels don't exactly scream culinary sophistication. And let's be honest, traditional Dutch food is comfort food for a cold, wet climate—heavy, brown, designed to fuel people reclaiming land from the sea. But here's what the stereotypes miss: the Netherlands has become one of Europe's most exciting food destinations, with a Michelin-star density that rivals France, a farm-to-table movement driven by incredible dairy and produce, Indonesian rijsttafel (legacy of colonialism, problematic origins, undeniably delicious), and a progressive food culture that includes vegan butchers and vertical farms. Amsterdam alone has 20+ Michelin-starred restaurants. Dutch cheese isn't just Gouda and Edam—there are 40+ varieties, many world-class. And the herring thing? It's ritualistic, seasonal, and when done right, transcendent. The Netherlands won't win on tradition, but it's winning on innovation.

**National Dishes & Street Food**: Start with haring (raw herring)—caught in spring (Hollandse Nieuwe), filleted, cured briefly, eaten whole by holding the tail and lowering it into your mouth. Served with onions and pickles at street stalls. It's polarizing, slimy, and quintessentially Dutch. Stroopwafels (thin waffles sandwiching caramel syrup) are the national sweet, best eaten warm off the griddle at Albert Cuyp Market. Bitterballen—deep-fried beef ragout balls—are the ultimate bar snack, served with mustard. Poffertjes (mini fluffy pancakes with powdered sugar and butter) are breakfast/snack fare. Stamppot (mashed potatoes with kale, sauerkraut, or endive, served with rookworst sausage) is peak Dutch winter comfort. Kroket (deep-fried meat croquette in a bun) is fast food perfection. Erwtensoep (split pea soup, thick enough to stand a spoon in) is served with rye bread and bacon—winter fuel.

**Regional Specialties**: Zeeland oysters and mussels (Zeeuwse mosselen) are harvested from the Oosterschelde and rival French shellfish—sweet, briny, served simply with lemon or Belgian-style with fries. Limburg in the south has vlaai (fruit pie), zuurvlees (sweet-sour horse meat stew), and a distinctly Belgian influence. Friesland produces the best dairy—Friesian cows are the source of much of the world's milk genetics. Frisian clove cheese (nagelkaas) is an acquired taste. Dutch pancakes (pannekoeken) are plate-sized and savory—bacon, cheese, apples—served at pancake houses nationwide. Amsterdam's Jordaan district has brown cafes (bruin café) serving traditional fare: stamppot, gehaktballen (meatballs), apple pie with whipped cream. Indonesian rijsttafel (rice table)—a colonial-era invention of multiple small dishes—is Amsterdam's unofficial cuisine, served at restaurants like Blauw and Sampurna.

**High-End Dining & Michelin Stars**: The Netherlands has 125+ Michelin-starred restaurants (as of 2024), an absurd concentration. Ciel Bleu in Amsterdam (2 stars) offers French technique with Dutch ingredients and stunning views. De Librije in Zwolle (3 stars) is one of Europe's best—chef Jonnie Boer sources hyper-locally, creates dishes that feel both modern and rooted. Oud Sluis, 't Nonnetje, Inter Scaldes—the list is long and geographically dispersed. The movement is ingredient-focused: North Sea fish (turbot, sole, shrimp), Zeeland oysters, Texel lamb, greenhouse tomatoes (Dutch tomatoes are a $2 billion export industry), asparagus from Limburg. Chefs like Ron Blaauw and Richard van Oostenbrugge are pushing New Dutch cuisine—refinement without pretension, sustainability-focused, playful. The Netherlands also leads in food tech: Vegetarian Butcher (plant-based meats), vertical farms, lab-grown meat research.

**Agricultural Products & Traditions**: The Netherlands is the world's second-largest agricultural exporter (after the U.S.), absurd for a country the size of Maryland. Dairy is the cornerstone: 1.6 million cows producing cheese (Gouda, Edam, Leyden, Old Amsterdam), butter, and milk. Cheese markets in Alkmaar and Gouda are tourist attractions but also real trade. Greenhouse agriculture is high-tech: tomatoes, peppers, cucumbers grown in climate-controlled glass houses—efficient, year-round, and environmentally controversial. Tulip bulbs (edible during WWII famine, now ornamental) are a $6 billion industry. Potatoes, sugar beets, and onions are major crops. Fishing: North Sea herring, mussels, shrimp. Genever (Dutch gin, predecessor to London dry gin) is the national spirit—smooth, malty, drunk chilled.

**Food Traditions & Culture**: Dutch food culture is egalitarian and no-nonsense. Lunch is typically bread with cheese and cold cuts—simple, efficient. Dinner is early (6-7 PM), traditionally warm, increasingly cosmopolitan. The ritual of coffee and cake (koffie met gebak) is sacred—cafes are social infrastructure. Sinterklaas (December 5) brings pepernoten (spiced cookies), chocolate letters, and speculaas. King's Day (April 27) means orange-frosted treats and street food chaos. The colonial legacy is complicated: Indonesian food is beloved, but its origins in exploitation are increasingly acknowledged. The Netherlands is also a global leader in food innovation: reducing meat consumption, sustainable fishing, circular agriculture. The tension between tradition (herring, stamppot) and innovation (Michelin stars, plant-based meat) defines modern Dutch food. And somehow, they've turned boring into trendy—Old Amsterdam cheese, craft genever, haute stamppot. The Dutch don't do culinary drama, but they've quietly built one of Europe's best food scenes. Just don't ask them to get excited about it.`
  },
  {
    name: 'New Caledonia',
    lat: -20.9043,
    lng: 165.6180,
    summary: `New Caledonia's cuisine is what happens when French technique meets Pacific seafood and Melanesian traditions, all filtered through tropical ingredients and the economic realities of a remote island territory. You get baguettes flown in from France (or baked locally to exacting standards), fresh tuna and lobster prepared with beurre blanc, Kanak lap-lap (root vegetables and coconut), and a level of culinary sophistication rare in the Pacific. This is France without the Michelin pretension—excellent wine lists, proper cheese counters, bistros serving steak frites—but also yams, flying fox, and seafood so fresh it was swimming an hour ago. The dining scene centers on Nouméa, where French expats and Kanak chefs are creating something genuinely hybrid. It's expensive (French prices in the South Pacific), but the quality is undeniable. The challenge: balancing colonial culinary dominance with indigenous food traditions that predate France by millennia.

**National Dishes & Pacific Specialties**: Bougna is the signature dish—Kanak in origin, now embraced across communities. Chicken, fish, or lobster steamed in banana leaves with taro, yam, sweet potato, and coconut milk, cooked in an earth oven (similar to Polynesian umu). It's rich, smoky, communal. Poisson cru (raw fish marinated in lime and coconut milk) shows the Polynesian influence—similar to Tahitian versions but with local variations. Lobster (langouste) from the lagoon is served grilled, in bisque, or thermidor-style in high-end restaurants. Bêche-de-mer (sea cucumber) is harvested and mostly exported to China, but appears in local Chinese restaurants. Roussette (fruit bat/flying fox) is controversial—traditional Kanak food, ecologically questionable, gamey and acquired taste. Deer and wild pig are hunted and served in tribal gîtes and local restaurants.

**French Culinary Influence**: French food isn't fusion here; it's imported wholesale. Boulangeries sell croissants and pain au chocolat that meet French standards. Nouméa's markets (Port Moselle) offer French cheeses, charcuterie, wines from Bordeaux and Burgundy. Restaurants like Le Roof (overwater dining, refined French-Pacific), La Chaumière (classic French bistro), and Le Faré du Palm Beach serve French cuisine adapted to local seafood—tuna carpaccio, lobster gratin, fish in vanilla sauce (vanilla grown in New Caledonia). Steak frites is everywhere, because it's France. The wine culture is serious—New Caledonia imports more wine per capita than almost anywhere outside France. Coffee culture: espresso, not Americano. Pastry shops (pâtisseries) rival Paris in quality if not variety.

**Regional & Kanak Cuisine**: Beyond Nouméa, Kanak food traditions survive in the Loyalty Islands and tribal areas. Lap-lap (not to be confused with Vanuatu's version) is root vegetables grated and baked with coconut. Taro, yam, and manioc are staples. Coconut crab (crabe de cocotier), when available, is a delicacy—sweet, rich, unsustainable if overharvested. Pahua (giant clams) from the lagoon are served grilled or raw. Kanak meals are communal, tied to custom (la coutume)—food exchange is social currency. Tribal gîtes offer home-cooked Kanak meals: bougna, grilled fish, tropical fruits. The challenge: Kanak cuisine is under-represented in Nouméa's dining scene, which skews French or fusion. There's a slow movement to elevate indigenous ingredients and techniques, but it's early days.

**High-End Dining & Seafood**: New Caledonia doesn't have Michelin stars (geography), but Nouméa has restaurants that would hold their own in French cities. Le Roof, built over the water, serves refined Pacific-French cuisine—local fish, Australian beef, French technique. L'Hippocampe at the Château Royal Beach Resort does contemporary French with tropical ingredients. Le 1881 focuses on local seafood and French classics. The real luxury is the seafood: the lagoon's biodiversity (UNESCO World Heritage) yields tuna, mahi-mahi, parrotfish, lobster, prawns. Oysters from Voh are buttery and clean. Sashimi-grade tuna appears on menus everywhere—the Japanese influence is strong (New Caledonia has Japanese expats and sushi culture). Wine pairing is taken seriously; sommeliers import boutique French labels. It's expensive ($50-100+ per person for dinner), but quality justifies cost.

**Agricultural Products & Traditions**: New Caledonia's agriculture is limited—only 10% of land is arable, much is nickel-mining moonscape. Yams, taro, and sweet potatoes are traditional Kanak crops, often traded in customary exchanges. Coffee is grown on a small scale—New Caledonian coffee is rare, high-quality, mostly consumed locally. Vanilla cultivation is expanding; the climate suits it. Tropical fruits: papaya, mangoes, lychees, passionfruit. Honey production is niche but growing—niaouli honey (from Melaleuca trees) is distinctively floral. Cattle ranching supplies local beef, though Australia imports dominate. Fishing is both subsistence (Kanak coastal communities) and commercial (tuna exported to Japan). Kava isn't traditional here like in Vanuatu, but it's present in Kanak communities. Beer: Number One and Manta are local brands—drinkable, nothing special.

**Food Culture & Politics**: Food in New Caledonia is political. French cuisine dominates Nouméa's restaurant scene, reflecting economic and cultural power imbalances. Kanak food is often relegated to "traditional" or "cultural" categories rather than integrated into mainstream dining. The bougna served at luxury resorts is commodified; the bougna shared in Lifou villages is identity. The 2024 political crisis highlighted these tensions—indigenous communities demanding recognition, which includes culinary sovereignty. Younger Kanak chefs are beginning to reclaim and modernize traditional foods, but it's an uphill battle against French culinary hegemony. At the same time, New Caledonia's multicultural reality (Kanak, French, Wallisian, Polynesian, Vietnamese, Indonesian) creates hybrid food culture: Vietnamese pho, Indonesian satay, French pastries coexist in Nouméa's markets. The result is complex, sometimes uncomfortable, and genuinely unique—a cuisine caught between colonialism and independence, tradition and modernity, France and the Pacific.`
  },
  {
    name: 'New Zealand',
    lat: -40.9006,
    lng: 174.8860,
    summary: `New Zealand's food culture has undergone a transformation over the past two decades that's almost as dramatic as its landscapes. What was once a culinary backwater—British stodge with lamb and potatoes—is now a sophisticated, globally-aware scene built on exceptional ingredients, Māori culinary revival, and Pacific Rim influences. The country's geographic isolation is both curse and blessing: imports are expensive, but the obsession with provenance and sustainability has created a farm-to-table ethos that predates the trend. You'll eat lamb that tastes like the hills it grazed, seafood harvested that morning, wine (especially Sauvignon Blanc and Pinot Noir) that competes with France, and Māori hāngī that connects food to whenua (land) and whakapapa (ancestry). Auckland and Wellington have Michelin-quality restaurants (without the stars—Michelin doesn't cover NZ yet). And yes, there's still pavlova and meat pies, because not everything needs to be elevated.

**National Dishes & Iconic Foods**: Meat pies are the national fast food—flaky pastry filled with minced beef, cheese, bacon, or steak and cheese. BP service stations sell millions annually; gourmet pie shops like Richoux (Auckland) elevate the form. Fish and chips, legacy of British colonialism, are everywhere—blue cod, tarakihi, or snapper, battered and fried, served with kumara (sweet potato) chips. Pavlova (meringue dessert with cream and fruit) is fiercely claimed as Kiwi despite Australian disputes—light, sweet, a national treasure. Lamingtons (sponge cake dipped in chocolate and coconut) are the other sweet staple. Hokey pokey ice cream (vanilla with honeycomb toffee) is iconic. Whitebait fritters—tiny native fish in egg, fried crispy—are a West Coast delicacy, seasonal and expensive. Marmite (yeast extract spread) is breakfast on toast for locals; Vegemite is for Australians, and the distinction matters.

**Māori Cuisine & Hāngī**: Hāngī is the cornerstone of Māori culinary tradition—meat (lamb, pork, chicken) and vegetables (kumara, potato, pumpkin, cabbage) slow-cooked in an earth oven with heated stones. The result is smoky, tender, infused with earth. It's communal, ritualistic, tied to marae (meeting grounds) and celebrations. Rotorua offers tourist hāngi experiences (Mitai, Tamaki), but the real deal happens at Māori gatherings. Rewena bread (potato-based sourdough) is traditional Māori; tangy, dense, perfect with butter. Kaimoana (seafood)—mussels (green-lipped, endemic to NZ), pāua (abalone), kina (sea urchin), tuatua (clams)—are harvested sustainably under Māori customary rights. The Māori culinary renaissance is happening: chefs like Monique Fiso (Hiakai, Wellington) and Charles Royal are reclaiming indigenous ingredients—kawakawa (peppery leaf), horopito (bush pepper), pikopiko (fern shoots)—and decolonizing the cuisine.

**Regional Specialties**: The South Island is lamb country—Canterbury lamb, Central Otago merino, Southland hogget. Bluff oysters (May-August season) are sweet, briny, legendary—Bluff Oyster Festival is a pilgrimage. Queenstown has high-end dining (Rata, Amisfield) serving Otago Pinot Noir and local game. The West Coast's whitebait (inanga) run (August-November) is a cultural event; whitebait fritters sell for $30+ per serving. Marlborough is Sauvignon Blanc territory—wineries like Cloudy Bay put NZ wine on the map. Hawke's Bay grows stone fruit, apples, and Syrah. Wellington's coffee culture rivals Melbourne—flat whites originated here (disputed with Sydney). Auckland's food scene is Pacific Rim: Pacific Island influence (Samoan oka, Tongan lu), Asian fusion (NZ has significant Chinese, Korean, Indian communities), and modern NZ fine dining.

**High-End Dining & Wine**: New Zealand doesn't have Michelin stars (Michelin doesn't rate here), but it has equivalents. The Cuisine Good Food Awards and Metro Top 50 list the best. Amisfield Bistro (Queenstown), Pasture (Auckland), Hiakai (Wellington closed but legacy lives), and Clooney (Auckland) deliver world-class dining—local ingredients, creative technique, wine pairings. Masu (Auckland) is high-end Japanese with NZ seafood. The French Café (Auckland) has been a standard-bearer for 30+ years. Wine is the other pillar: Marlborough Sauvignon Blanc (Cloudy Bay, Dog Point), Central Otago Pinot Noir (Felton Road, Rippon), Hawke's Bay reds. NZ wine exports topped NZD $2 billion in 2024. Wine regions offer cellar door experiences—tasting rooms, vineyard restaurants (Misha's Vineyard, Amisfield). Craft beer scene is strong: Garage Project, Tuatara, Emerson's.

**Agricultural Products & Sustainability**: New Zealand's food identity is tied to farming—lamb, beef, dairy, kiwifruit, apples, wine. Sheep outnumber people 5:1; lamb is grass-fed, exported globally. Dairy is massive: Fonterra is the world's largest dairy exporter (milk powder, butter, cheese). But it's also environmentally controversial—nitrogen runoff, water quality issues, methane emissions. Kiwifruit (especially gold kiwis) are a billion-dollar export; Zespri dominates global markets. Honey, particularly mānuka honey (antibacterial properties, medical-grade), is premium—genuine mānuka honey ($50-100/kg). Venison farming and salmon aquaculture (King Salmon) are smaller industries. Sustainability narrative is strong: grass-fed, free-range, organic certifications. But the reality is complex—intensive dairy farming, overfishing, introduced species (possums, deer) harming native ecosystems.

**Food Culture & Trends**: Kiwis love their coffee—flat whites, strong espresso culture, third-wave roasters everywhere. BYO (bring your own wine) is common at restaurants; corkage is $10-15. Food trucks and markets (Harbourside, Otara, Cambridge) are community centers. The Great NZ Pie Competition is serious business. Sunday roasts remain tradition; increasingly upscale versions appear on brunch menus. Veganism is growing—Wellington is vegan-friendly, Auckland has plant-based fine dining (Beatbox Kitchen). Food safety standards are high; NZ has zero tolerance for food contamination. The tall poppy syndrome (cutting down those who stand out) means chefs are low-key despite skill. But the cultural shift is real: from lamb and two veg to Māori-led culinary innovation, from British colonial food to Pacific Rim sophistication. The story is young, the ingredients are world-class, and the best is yet to come.`
  },
  {
    name: 'Nicaragua',
    lat: 12.8654,
    lng: -85.2072,
    summary: `Nicaraguan food is Central American comfort at its purest—beans, rice, plantains, and corn in endless permutations, shaped by indigenous Nahuatl and Miskito roots, Spanish colonialism, and the economic reality of being one of the region's poorest countries. This isn't cuisine that chases trends or Michelin stars; it's sustenance, deeply flavorful, built on volcanic soil that produces exceptional coffee and cacao. Gallo pinto (rice and beans) is eaten daily, sometimes three times a day, and Nicaraguans will argue passionately that their version is superior to Costa Rica's. Street food is queen: quesillos, nacatamales, vigorón. And the ingredients—grass-fed beef, Pacific seafood, tropical fruits that taste like they should—are spectacular when you find them prepared simply. The culinary scene is emerging in Granada and Managua, but most Nicaraguan food culture happens in comedores (family-run eateries) and markets where a full meal costs $3 and the cook has been making the same dishes for 40 years.

**National Dishes & Street Food**: Gallo pinto (literally "spotted rooster") is the foundation—red beans and rice fried together with onions, peppers, and sometimes achiote. Served at breakfast with eggs, fried cheese, and tortillas. It's simple, it's everywhere, and it's identity. Nacatamales are the Sunday ritual—masa (corn dough) filled with pork or chicken, rice, potatoes, tomatoes, wrapped in plantain leaves and steamed for hours. Bigger and more elaborate than Mexican tamales. Quesillos (Nagarote-style) are the ultimate street snack—soft corn tortilla, tangy string cheese, pickled onions, and crema, wrapped in plastic and eaten by squeezing from the bottom. Vigorón (León specialty) is yuca (cassava) topped with cabbage slaw and chicharrón (fried pork rinds), served on a plantain leaf. Indio viejo (old Indian) is a thick stew of shredded beef or chicken, corn masa, tomatoes, and achiote—pre-Columbian in origin, deeply savory.

**Regional Specialties**: León and Granada have distinct food identities. León's street food includes quesillo and sopa de queso (cheese soup with vegetables and tortilla). Granada, the colonial tourist hub, has more upscale options but also traditional fritanga (street grills) serving grilled meats, plantains, and yuca. The Caribbean coast (Bluefields, Corn Islands) is culturally distinct—Afro-Caribbean and Miskito influences. Rondón is the signature: a coconut milk-based seafood stew with fish, crab, yuca, plantains, and whatever's available. It's richer, spicier, fundamentally different from Pacific-side food. The Corn Islands have lobster—cheap, fresh, grilled or in soup. Lake Nicaragua (Cocibolca) provides guapote (rainbow bass), fried or grilled. Northern highlands around Matagalpa and Jinotega grow coffee; local dishes include cuajada (fresh cheese), rosquillas (corn-cheese biscuits), and tamales.

**High-End Dining & Emerging Scene**: Nicaragua doesn't have fine dining in the traditional sense, but Granada and San Juan del Sur have restaurants catering to expats and tourists. Restaurante El Zaguan (Granada) serves elevated Nicaraguan—grilled beef, plantain dishes, local ingredients with care. Pita Pita does Mediterranean-Nica fusion. Café de los Sueños (Managua) focuses on organic, local, slow food. San Juan del Sur, a surf town, has international menus (Italian, Mexican, sushi) rather than Nicaraguan innovation. The real high-quality food is in comedores and fondas—family-run spots where the cook is the owner and the recipes are generational. Doña Haydée in Masaya, fritangas in Managua's markets—these are where you eat best, cheaply, and authentically.

**Agricultural Products & Ingredients**: Nicaragua's agriculture is smallholder-dominated and export-driven. Coffee is king—especially from Jinotega, Matagalpa, and Nueva Segovia. Shade-grown, often organic, exceptional quality. Nicaragua is the world's fifth-largest coffee exporter. Cacao from the Caribbean coast is heirloom Trinitario—sought after by craft chocolate makers (Cacao Bisiesto, local bean-to-bar). Cattle ranching dominates the interior—grass-fed beef is a major export, and locals eat it frequently (bistec, carne asada). Beans (red beans primarily) and rice are staples. Corn is sacred—tortillas, tamales, chicha (fermented corn drink), atol (corn porridge). Plantains (green and ripe) are omnipresent. Tropical fruits: papaya, mango, pitaya (dragon fruit), nancite (small yellow fruit, tangy), cacao fruit. Sugar cane for domestic consumption and rum (Flor de Caña, Nicaragua's pride—aged rum that competes globally).

**Drinks & Beverage Culture**: Flor de Caña rum is world-class—aged in bourbon barrels, affordable ($15-40 for 12-18 year), smooth enough for sipping. The distillery is in Chichigalpa; tours available. Nicaraguan coffee rivals any in Central America—fruity, bright, clean. Victoria and Toña are the national beers—light lagers, cheap, ubiquitous. Craft beer is emerging (Güiscoyol Brewing). Cacao drinks: pinol (toasted corn and cacao powder mixed with water), pinolillo (similar, the national drink), tiste (cacao, corn, achiote). Chicha (fermented corn) is traditional in rural areas. Frescos (fresh fruit drinks): cebada (barley), tamarindo, pitaya, calala (passion fruit). Pozol (fermented cacao drink) in the Caribbean. Nicaraguans drink their beverages sweet and cold—frescos are dessert-level sugar.

**Food Traditions & Cultural Context**: Food in Nicaragua is community and survival. The tradition of fritangas—outdoor grills on street corners, plastic tables and chairs, selling grilled meats, plantains, yuca, gallo pinto—is social infrastructure. Families gather, neighbors eat together, it's cheap and filling. Nacatamales on Sundays are ritual; making them is a family affair, hours of preparation. Markets (Mercado Oriental in Managua, Mercado de Masaya) are where food culture lives—vendors selling prepared foods, fresh produce, spices, the chaos and energy of commerce. Economic hardship shapes food: portions are generous but ingredients are simple. Meat is a luxury for many; beans and rice are reliable. Political instability (civil war in the 1980s, ongoing repression under Ortega) has strained agriculture and food security. Yet Nicaraguans are proud of their food—unpretentious, nourishing, tied to land and memory. The phrase "Nica food is made with love" is cliché but true—the best meals happen in homes and comedores where food is cooked by women who've been doing it for decades. No frills, just flavor and heart.`
  },
  {
    name: 'Niger',
    lat: 17.6078,
    lng: 8.0817,
    summary: `Niger's cuisine is shaped by survival in one of the world's harshest environments—landlocked, two-thirds Sahara Desert, chronically food-insecure. This is subsistence food: millet, rice, sorghum, and whatever protein is available (goat, lamb, occasionally beef), cooked with minimal ingredients and maximum ingenuity. The country straddles the Sahel, where West African, Arab, and Tuareg food cultures converge. You eat djerma (rice dishes), fufu (pounded starch), and jollof-adjacent rice (though Niger's version is simpler than Senegalese or Nigerian). Tuareg cuisine brings camel milk, dates, and tagella (sand-baked bread). And poverty shapes everything—Niger has the world's lowest GDP per capita, chronic malnutrition is widespread, and food aid is common. Yet the food culture is generous, communal, and tied to deep traditions of hospitality. This isn't a cuisine for tourists (Niger gets barely 100,000 visitors annually, most for mining or aid work), but it's profoundly human.

**Staples & National Dishes**: Millet is the foundation—grown in the Sahel, drought-resistant, ground into flour for porridge (fura) or couscous-like grains. Tuwo (thick millet or sorghum porridge) is eaten with sauces—peanut (miya), okra, baobab leaf. It's filling, cheap, bland without sauce. Rice is increasingly common, especially in cities—djerma rice cooked with tomatoes, onions, and oil. Fufu (pounded yam or cassava) appears in southern regions near Nigeria. Soups and stews: miyar kubewa (pumpkin and peanut stew), miyar kuka (baobab leaf sauce, slimy texture, nutritious). Grilled meat (brochettes) of goat, lamb, or beef is street food, served with spicy pepper sauce and bread. Kilishi (spiced dried meat, similar to West African jerky) is a Hausa specialty. Dates from desert oases are eaten fresh or dried.

**Regional & Ethnic Variations**: The Hausa (southern Niger, near Nigeria) share food with northern Nigerian Hausa—tuwo, miyar kuka, kosai (bean cakes), masa (rice cakes). The Zarma/Songhai along the Niger River eat more rice and fish—capitaine (Nile perch), catfish, cooked simply or in stews. The Tuareg and Fulani nomads of the north and Sahel eat camel milk (fresh or fermented as zrig), dates, tagella (unleavened bread cooked in sand under coals—gritty, essential), and occasional goat or mutton. Milk and millet form the Fulani diet—fura da nono (millet balls in fermented milk) is breakfast and sustenance. In Agadez and the desert, food is imported or scarce; preserved foods, dried meat, and grain stores dominate. Southern agricultural zones grow manioc, yams, and beans—richer diets but still limited.

**Street Food & Markets**: Niamey (the capital) has street food scenes—brochettes, fried fish, akara (fried bean cakes), fried plantains. The Grand Marché (Grand Market) sells spices (ginger, chili, cloves), grains, dried fish, and vegetables when available. Roadside stalls sell koko (millet porridge), doughnuts (beignets), and sweet tea (Tuareg style—green tea with lots of sugar, served in three rounds, each with symbolic meaning). Drinking tea is social ritual; the first glass is bitter, the second smooth, the third sweet—life's progression. In rural areas, markets are weekly events where food is bartered—millet for dried fish, vegetables for meat. Food security is precarious; droughts and locust swarms can devastate harvests. WFP (World Food Programme) presence is constant.

**Ingredients & Agricultural Reality**: Niger's agriculture is rain-fed and climate-vulnerable. Millet and sorghum are primary crops—drought-tolerant, grown in the Sahel band. Cowpeas (black-eyed peas) are a crucial protein source and nitrogen-fixer. Peanuts are grown and processed for oil and paste (miya). Onions from the Tahoua region are a major crop—surprisingly, Niger exports onions to Nigeria and Ghana. Livestock (goats, sheep, camels, cattle) are herded by Fulani and Tuareg; meat is a luxury for most. The Niger River and Lake Chad basin provide fish, but overfishing and environmental degradation threaten supplies. Moringa leaves (nutrient-dense) are increasingly promoted for malnutrition. Dates from Air Mountains oases. Wild foods: baobab leaves (kuka), fruit (monkey bread), tamarind, wild grains. Food imports (rice, wheat, sugar, oil) are significant; Niger depends on Nigeria and coastal ports (Benin, Togo).

**Beverages & Dairy**: Camel and cow milk are vital—fresh, fermented (kindirmou, nono), or made into butter. Fura da nono (millet balls in sour milk) is iconic in Hausa and Fulani communities. Zobo (hibiscus tea, called bissap in francophone regions) is drunk cold and sweet. Tuareg tea ceremonies are cultural—green tea with mint and sugar, brewed over coals. Coffee is rare; tea and sugary drinks dominate. Locally brewed millet beer (bilibili) exists in non-Muslim communities but is uncommon (Niger is 99% Muslim, alcohol is mostly forbidden). Soft drinks (Coca-Cola, Fanta) are available in cities—expensive luxuries.

**Food Culture, Hospitality & Crisis**: Food in Niger is communal—shared from a large bowl, eaten with the right hand, squatting on mats. Refusing food is offensive; hospitality is sacred even in poverty. Meals are gendered—women cook, men eat first, children last. Ramadan fasting is observed strictly; iftar meals are simple—dates, porridge, tea. The cultural practice of "gourma" (sharing food with neighbors and travelers) persists despite scarcity. But food security is catastrophic: 4+ million people face acute hunger annually. Malnutrition rates among children are among the world's highest. Droughts, desertification, conflict (Boko Haram in the southeast, jihadist violence in the west), and climate change are converging crises. Food aid (WFP, NGOs) supplements diets in vulnerable regions. The 2023 coup and subsequent ECOWAS sanctions worsened food access. Yet in markets, in villages, in Tuareg camps, food remains the language of dignity and survival—simple, scarce, and shared with a generosity that shames wealthier nations.`
  },
  {
    name: 'Nigeria',
    lat: 9.0820,
    lng: 8.6753,
    summary: `Nigerian food is bold, unapologetic, and increasingly taking over the global food scene. From jollof rice (the subject of endless regional debates) to suya (spiced grilled meat that might be West Africa's greatest street food invention), Nigerian cuisine is built on palm oil, peppers, yams, and the philosophy that food should be flavorful, filling, and communal. With over 250 ethnic groups, the food varies wildly: Yoruba egusi and amala, Igbo ofe nsala and pounded yam, Hausa kilishi and fura da nono. Lagos has become a culinary capital—fine dining, street food, jollof wars on social media—and the Nigerian diaspora (12+ million globally) is exporting the cuisine worldwide. This is comfort food that travels well: pepper soups that cure everything, bean cakes that fry up perfectly at 5 AM, stews that taste better the next day. Nigerian food doesn't apologize, doesn't compromise, and doesn't need Michelin stars to know it's world-class.

**National Dishes & Jollof Politics**: Jollof rice is the national dish and cultural flashpoint—long-grain rice cooked in a tomato-pepper-onion sauce, often with chicken or beef. Every Nigerian will insist their version (party jollof, smoky jollof, native jollof) is superior, and they'll fight Ghanaians and Senegalese over regional supremacy. The answer: Nigerian jollof is smokier, richer, more aggressively spiced. Served at parties, weddings, celebrations. Pounded yam (iyan) and egusi soup (ground melon seeds with spinach, meat, or fish) is Yoruba soul food—sticky, earthy, eaten with fingers. Moin moin (steamed bean pudding) is protein-rich, smooth, sometimes wrapped in leaves. Pepper soup (catfish, goat, or chicken in a spicy broth with local spices—uziza, utazi) is medicinal and addictive. Suya—skewered beef or chicken rubbed with yaji (spicy peanut spice mix), grilled over charcoal—is Nigeria's greatest street food contribution to humanity.

**Regional Specialties**: Yoruba cuisine (southwest—Lagos, Ibadan, Abeokuta) features amala (yam flour porridge, dark brown, served with ewedu (jute leaf soup) and gbegiri (bean soup). Ofada rice (local unpolished rice) with ayamase (designer stew—green peppers, locust beans, offal). Igbo food (southeast—Enugu, Onitsha) includes ofe nsala (white soup—no palm oil, just uziza and utazi), abacha (African salad—shredded cassava with palm oil, ugba, fish), and ji (yam, culturally sacred). Hausa-Fulani cuisine (north—Kano, Kaduna) is drier, less palm oil—tuwo (millet or rice porridge), miyan kuka (baobab leaf soup), kilishi (spiced dried meat), fura da nono (millet balls in fermented milk). The Middle Belt and Niger Delta have their own specialties—banga soup (palm fruit extract), atama soup, edikang ikong (rich vegetable soup). Calabar is known for Afang soup and editan.

**Street Food & Lagos Energy**: Nigerian street food is 24/7. Akara (fried bean cakes) and pap (fermented corn porridge) for breakfast. Puff puff (fried dough balls, sweet) sold everywhere. Boli (roasted plantain) with groundnuts. Shawarma (imported, Nigerianized—spicier, bigger) is the new street food obsession. Asun (spicy grilled goat) at Lagos bars. Gizdodo (gizzards and fried plantains in pepper sauce)—rich, indulgent, perfect beer food. Ewa agoyin (mashed beans with spicy sauce) is cheap, filling, everywhere. Lagos street food scene is legendary—Balogun Market, Ojuelegba, VI (Victoria Island)—constant, chaotic, delicious. Food vendors operate from wheelbarrows, kiosks, canopies. Hygiene is variable; locals have iron stomachs. Traffic jams spawn mobile hawkers selling everything from plantain chips to bottled water.

**High-End Dining & Diaspora Influence**: Lagos is West Africa's culinary capital. Restaurants like Nok by Alara and Terra Kulture elevate Nigerian ingredients—smoked catfish ravioli, jollof arancini, suya-spiced lamb. Yellow Chilli does upscale takes on classics. The Wheatbaker Hotel's restaurant serves refined Nigerian-Continental fusion. Michelin stars don't exist in Nigeria, but the talent is there. The diaspora is globalizing Nigerian food: Ikoyi (London, 2 Michelin stars) is redefining West African fine dining—fermented ingredients, umami-forward, zero jollof but maximum Nigerian technique. Chishuru (London), Eko Kitchen (Houston), BukaBuka (Johannesburg)—Nigerian restaurants are opening globally. Social media (Instagram, TikTok) has turned Nigerian cooks into influencers—Zeelicious Foods, Sisi Yemmie, 9jafoodie. Nigerian food is trendy, and Nigerians are owning it.

**Agricultural Products & Palm Oil Economy**: Nigeria is Africa's largest economy and most populous country (223+ million). Agriculture employs 35% of the workforce. Yams—Nigeria produces 60% of the world's yams. New Yam Festival (Iri Ji, Igbo) celebrates harvest. Cassava is the other starch staple—processed into garri (fried granules), fufu, and flour. Palm oil is fundamental—Nigeria was the world's largest producer pre-colonialism; now imports it (irony). Used in jollof, stews, soups—everything. Peanuts (groundnuts) grown in the north—exported and used for suya spice, oil, kuli-kuli (groundnut cakes). Rice consumption is massive but local production doesn't meet demand—imports from Thailand, India. Tomatoes, peppers, onions are cultivated; tomato paste is imported (local tomato supply is inconsistent). Plantains, cowpeas (beans), maize. Livestock—cattle in the north (Fulani herders), goats, chickens.

**Drinks, Spices & Flavor Philosophy**: Nigerian cuisine is spice-forward—scotch bonnet peppers, locust beans (iru, dawadawa—fermented, funky), crayfish, stock cubes (Maggi and Knorr are sacred), uziza, utazi, ehuru (calabash nutmeg). Palm oil isn't just fat; it's flavor and color. Star beer, Gulder, and Trophy are the national beers. Guinness Nigeria makes a sweeter, stronger version of stout—massively popular. Chapman's (non-alcoholic cocktail—Fanta, Sprite, bitters, fruit) is party drink. Zobo (hibiscus tea), kunu (millet drink), palm wine (fresh or fermented). Local gins (ogogoro, kai kai) are potent, sometimes dangerous (methanol contamination). Nigerian food philosophy: bold flavors, rich textures, food is love. Portions are generous; hunger is disrespect. Spice levels are punishing for the uninitiated—"Nigerian pepper" is a warning, not a joke. Food is communal—big pots, shared plates, eating with hands from a common dish. Meals are events, not routines. The question "Have you eaten?" is a greeting, concern, hospitality. Food is culture, and Nigerians are exporting that culture globally—one plate of jollof at a time.`
  },
  {
    name: 'North Korea',
    lat: 40.3399,
    lng: 127.5101,
    summary: `Writing about North Korean cuisine is complicated by the fact that for most of the population, food is about survival, not culture. The 1990s famine (Arduous March) killed 600,000-1 million people; chronic malnutrition persists in rural areas and among non-elite classes. The food most North Koreans eat—corn, cabbage, maybe rice if they're lucky—is not what the regime showcases to visitors. Meanwhile, Pyongyang's elite and tourist restaurants serve elaborate cold noodles (naengmyeon), kimchi variations, and propaganda-approved Korean dishes that claim superiority over South Korean versions. The cuisine is theoretically similar to South Korean—fermented vegetables, rice, soups—but shaped by isolation, Soviet influence, and the deification of Kim Il Sung's food preferences (which are national doctrine). Visiting foreign journalists eat at staged restaurants; defector testimonies describe boiled grass and tree bark. Both are true, and both are North Korea.

**Official National Dishes**: Naengmyeon (cold buckwheat noodles in chilled broth) is Pyongyang's pride—long, chewy noodles in beef or dongchimi (radish water kimchi) broth, topped with sliced meat, pear, and egg. The regime claims Pyongyang naengmyeon is the authentic version, superior to South Korea's. It's served at Okryu-gwan, the state-run restaurant in Pyongyang that seats 1,000 and is a pilgrimage site for naengmyeon purists (including South Korean President Moon Jae-in during the 2018 summit). Kimchi is ubiquitous—cabbage, radish, cucumber, fermented with garlic, chili, and fish sauce or anchovy. Kimjang (kimchi-making season) is a national event, broadcast on state TV. Injogogi (literally "artificial meat"—textured soy protein) was developed during famine as protein substitute. Propaganda frames it as innovation; it's actually desperation food. Pyongyang onban (Pyongyang warm rice)—rice with chicken broth, egg, and vegetables—is presented as comfort food.

**Reality vs. Propaganda**: For Pyongyang elites, party cadres, and military officials, food is varied—rice, meat (pork, beef, chicken), fish, vegetables, fruits. State banquets feature elaborate Korean courses, alcohol (soju, beer), and imported luxuries. Restaurants like Ryugyong (seafood), Chongryu (hot pot), and Haedanghwa (tea house with snacks) serve tourists and elites. For everyone else, food is rationed through the Public Distribution System (PDS)—rations include corn, cabbage, soybean oil, sometimes rice. The rations are inadequate and irregular; markets (jangmadang) have emerged where people buy, sell, barter food. Corn is the staple for most, not rice—cheaper, more available, less prestigious. Soups and stews are stretched with wild vegetables, seaweed, soybeans. Meat is rare; protein comes from soy, occasional fish, foraged insects.

**Regional & Seasonal Variations**: Hamgyong Province (northeast) is mountainous and poor—potato farming, corn, scarce protein. Hwanghae and South Pyongan provinces (west) are the rice bowls, relatively better off. Coastal areas have seafood—pollock, squid, shellfish—but fishing rights are sold to China for foreign currency, limiting local access. Seasonal eating is necessity: spring is the "lean season" (boribogae—barley hump) when last year's stores run low and new crops aren't ready; foraging wild vegetables (naengi, ssuk) is critical. Summer brings vegetables—cucumbers, eggplants, peppers. Autumn is harvest—corn, rice if available, kimjang season. Winter is preservation—kimchi, dried fish, stored grains. The DMZ's southern edge (South Korean side) is ironically fertile—decades without human interference created a nature reserve. North Korea's side is farmed intensively, often unsuccessfully due to poor soil and deforestation.

**Alcohol & Beverages**: Soju (clear distilled liquor, usually from sweet potatoes or corn in DPRK) is consumed widely—state-produced brands vary in quality. Taedonggang Beer, brewed in Pyongyang with equipment imported from England, is actually decent—several varieties, sold in bars and restaurants. Propaganda touts it as evidence of DPRK prowess. Makgeolli (milky rice wine) is traditional but less common than soju. Insam-ju (ginseng liquor) is marketed as premium. Coffee culture is emerging in Pyongyang—state-run coffee shops and even an espresso bar opened for elites. For most, beverages are tea (roasted barley, corn tea), sugar water, or just water (quality varies, often untreated). Soft drinks are produced domestically (Cocoa Liqueur, Pear Juice) to replace Coca-Cola; they taste like Soviet-era sodas.

**Propaganda, Control & Defector Testimonies**: Food is political. Kim Il Sung's favorite dishes (naengmyeon, injogogi) are state doctrine; recipes are published as his inventions. Kim Jong Il's birthday (Day of the Shining Star) and Kim Il Sung's birthday (Day of the Sun) bring state rations—extra rice, meat, cooking oil—that people depend on. Food access is a loyalty reward system: Pyongyang residents are better fed than provincial; party members better than farmers; military better than civilians. Defectors describe eating rats, frogs, grass, pine bark during the Arduous March. Testimonies mention public executions for stealing food, markets as only survival mechanism, and the psychological trauma of constant hunger. Aid organizations (WFP, UNICEF) report chronic child malnutrition—stunting rates near 20%. The regime restricts aid access, diverts food to military, and denies problems.

**Food & Identity**: Food in North Korea is about power and absence. The state controls narratives: DPRK cuisine is "scientific," "superior," "invented by the Great Leader." Food is a tool of control—rations can be withdrawn, markets raided, hunger weaponized. Yet North Koreans maintain food traditions—kimjang is familial and cultural, naengmyeon is regional pride, and cooking for loved ones is an act of resistance and care in a system designed to erase both. Defectors in South Korea crave DPRK-style naengmyeon (less sweet, simpler than Southern versions), recreating tastes of home despite everything. The tragedy is that a cuisine that should be about shared Korean heritage—fermentation, balance, seasonal eating—is instead a story of famine, propaganda, and a population denied the basic dignity of eating enough. One day, perhaps, North Korean food culture will be about more than survival. Until then, every meal is political.`
  },
  {
    name: 'North Macedonia',
    lat: 41.6086,
    lng: 21.7453,
    summary: `North Macedonian cuisine is the Balkan melting pot at its most flavorful—Ottoman, Slavic, Mediterranean, and Greek influences layered over centuries of empires and migrations. This is tavče gravče (baked beans) and ajvar (roasted red pepper spread), kebapi and burek, shopska salad and rakija strong enough to cure or cause problems depending on the dose. Skopje's Old Bazaar (Stara Čaršija) feels like Istanbul's quieter cousin—grilled meat smoke, spice vendors, baklava stacked in pyramids. The food is hearty, unpretentious, designed for cold winters and agricultural rhythms. It's also under-recognized: North Macedonia is overshadowed by Greek, Turkish, and Serbian cuisines despite having claim to similar (or identical) dishes. The Ohrid trout, the Tikveš wine region, the taverns serving food exactly as grandmothers made it—this is Balkan comfort at its best, without the tourists or pretension that now plague Dubrovnik or Santorini.

**National Dishes & Staples**: Tavče gravče (baked beans in a clay pot with paprika, onions, sometimes sausage) is the national dish—simple, cheap, filling, delicious. Served in traditional earthenware (tavče). Ajvar, the roasted red pepper and eggplant spread, is made in late summer/fall (ajvar season) in massive batches—families roast peppers for days, jarring enough to last the year. Eaten on bread, with cheese, alongside grilled meats. Shopska salad (tomatoes, cucumbers, onions, peppers, topped with grated white cheese) is the Balkan standard. Pindjur (similar to ajvar but chunkier, with tomatoes and eggplant) is the other condiment essential. Polneti piperki (stuffed peppers with rice and meat) and sarma (cabbage rolls) show the Ottoman influence. Burek (flaky pastry filled with cheese, meat, or spinach) is breakfast or late-night food, eaten with yogurt.

**Grilled Meats & Ottoman Legacy**: Kebapi (ćevapi in wider Balkans)—small grilled sausages served in flatbread with onions and ajvar—are ubiquitous. Traditionally served in sets of 5 or 10 with lepinja (flatbread). Pljeskavica (spiced meat patty) is the Balkan burger—beef, pork, or lamb, grilled, stuffed with cheese (pljeskavica sa sirom). Shish kebab (raznici) is skewered meat, marinated and charred. Turli tava is a mixed vegetable and meat stew baked in clay—okra, peppers, potatoes, lamb. Pastrmalija (Macedonian pizza from Štip) is flatbread topped with spiced meat, eggs, peppers—breakfast or snack. Gravče na tavče (beans again, regional variations everywhere) is vegetarian-friendly and protein-rich. The Turkish influence is everywhere: baklava, tulumba (fried dough soaked in syrup), halva, Turkish coffee.

**Regional Specialties & Ohrid Trout**: Ohrid trout (Ohridska pastrmka) from Lake Ohrid is legendary—endemic species, delicate flavor, grilled or baked with garlic and lemon. Lake Ohrid (UNESCO World Heritage) is ancient and unique; overfishing threatens the trout. Ohrid's restaurants serve it fresh, expensive ($15-25 per fish). Strumica region grows peppers (the best ajvar comes from Strumica peppers). Tikveš wine region produces red wines (Vranec, Cabernet Sauvignon) and whites (Smederevka). Tikveš Winery is the oldest and largest—wines are affordable ($5-10/bottle), quality is improving. Rakija (fruit brandy—plum, grape, quince) is homemade and social ritual—the first toast, the last toast, the medicinal shot. Mastika is anise-flavored aperitif, sweeter than ouzo. Bitola has Turkish-influenced sweets and pastries.

**High-End Dining & Modern Scene**: North Macedonia doesn't have Michelin stars (Michelin doesn't cover the Balkans), but Skopje has upscale restaurants elevating traditional food. Pelister serves modern Macedonian—Ohrid trout, local lamb, wine pairings. Old Town House blends Balkan and European. Makedonska Kuka (Macedonian House) does traditional food in a heritage setting—live music, folk atmosphere. Amam in Ohrid is boutique dining with lake views. The scene is small but growing—Skopje's Debar Maalo neighborhood has cafes, wine bars, and experimental chefs. Coffee culture is strong—Turkish coffee, espresso, Italian-style cafes. Rakija bars (rakija houses) are a thing—tasting flights of homemade brandies.

**Agricultural Products & Traditions**: North Macedonia's agriculture is smallholder farms—peppers, tomatoes, cucumbers, grapes, tobacco (major export), stone fruits. Peppers are identity—roasted, jarred, worshipped. The autumn roasting of peppers is a communal event—entire neighborhoods smell like smoke and paprika. Wine production dates to ancient Macedon—Tikveš, Povardarie, and Pelagonija regions. Vranec (indigenous red grape) is the flagship; smoky, tannic, food-friendly. White cheese (sirenje, feta-style) is made from sheep or cow milk, eaten daily. Yogurt (kiselo mleko) is thick, tangy, consumed at breakfast or with burek. Honey production is small-scale; mountain honey (wildflower, chestnut) is excellent. Bread (leb) is baked daily—white, whole wheat, somun (flatbread). Food is seasonal, preserved for winter—ajvar, pickled vegetables, dried fruits, jams.

**Food Culture & Balkan Hospitality**: Food in North Macedonia is communal and generous. "Dobar tek" (good appetite) is the greeting before eating. Refusing food is rude; hosts will insist until you eat. Rakija is the social lubricant—toasts, conversation, bonding. Slava (family patron saint day) and other celebrations mean feasts—roasted lamb, sarma, salads, sweets. Kafana culture (taverns with live music, grilled meats, rakija) is where social life happens. The čaršija (bazaar) is markets and street food—grilled corn, roasted chestnuts, burek stalls. Food is tied to identity: ajvar-making is tradition passed down, tavče gravče is national pride, Ohrid trout is regional treasure. The cuisine is under-marketed globally—no celebrity chefs, no international chains—which means it remains local, affordable, and authentic. North Macedonia's food doesn't shout; it's comfort, history, and hospitality on a plate, best experienced in a tavern with strangers becoming friends over grilled meats and too much rakija.`
  },
  {
    name: 'Northern Cyprus',
    lat: 35.1856,
    lng: 33.3823,
    summary: `Northern Cyprus exists in a culinary and political limbo—internationally unrecognized as a state (except by Turkey), culturally Turkish Cypriot with Ottoman roots, geographically Mediterranean, and still haunted by the 1974 division of the island. The food reflects this complexity: Turkish kebabs and börek, Cypriot halloumi and şeftali (sheftalia), Greek mezze traditions, and the bitterness of displacement. Famagusta's walled city and Kyrenia's harbor have restaurants serving grilled fish, kleftiko, and Turkish breakfast spreads with views of a militarized coastline. The cuisine is nearly identical to the Republic of Cyprus (south), but shaped by 50 years of isolation, economic sanctions, and dependency on Turkey. It's delicious, affordable, and deeply complicated—eating here is an act of geopolitics as much as pleasure. The meze culture, the char-grilled meats, the citrus groves and carob trees—Northern Cyprus is one of the Mediterranean's most beautiful and fraught places to eat.

**National Dishes & Turkish Cypriot Staples**: Şeftali kebab (sheftalia)—grilled sausages of minced pork or lamb, parsley, onions, wrapped in caul fat—is the Cypriot signature. Juicy, smoky, eaten in pita with salad. Halloumi (hellim in Turkish) is Cypriot identity in cheese form—salty, squeaky, grilled or fried, served with watermelon or in sandwiches. Both sides of the divided island claim it; PDO designation is complicated by politics. Meze is the dining format—20+ small dishes: hummus, tzatziki, taramosalata, grilled octopus, calamari, halloumi, dolma (stuffed vine leaves), köfte, olives, fresh bread. Shared, slow, social. Kleftiko (lamb slow-cooked in a sealed clay oven until it falls off the bone) is Sunday food. Molohiya (jute mallow stew with chicken or lamb) is Cypriot comfort—green, slimy, polarizing, loved by locals.

**Turkish Influence & Breakfast Culture**: Since 1974, Northern Cyprus has absorbed Turkish culture, including food. Turkish breakfast (kahvaltı) is elaborate—olives, cheese (beyaz peynir, kashkaval), tomatoes, cucumbers, eggs (menemen—scrambled with peppers and tomatoes), sucuk (spicy sausage), honey, jam, kaymak (clotted cream), fresh bread. Hotels and cafes serve it; it's a leisurely weekend ritual. Börek (savory pastries—spinach, cheese, or meat) and simit (sesame bread rings) are Turkish imports. Lahmacun (Turkish flatbread with minced meat, herbs) and pide (Turkish pizza) are common. Kebabs—Adana, shish, döner—are everywhere. Turkish delight (lokum), baklava, künefe (shredded pastry with cheese and syrup) dominate sweets. The food is distinctly Turkish now, though older generations remember pre-division Cypriot cuisine that blended Greek and Turkish elements more fluidly.

**Seafood & Mezze Culture**: The coast offers Mediterranean seafood—sea bass (levrek), sea bream (çipura), octopus, calamari, prawns. Kyrenia's harbor restaurants serve grilled fish with lemon, olive oil, and salads. Meze culture is deeply rooted: ordering meze means a procession of dishes, often 2-3 hours, with raki (anise spirit) or wine. It's not rushed; it's the point. Octopus stifado (braised with wine and onions), grilled prawns, whitebait, taramasalata—each dish arrives when ready. The tradition crosses the Green Line (buffer zone dividing the island)—Greek Cypriots and Turkish Cypriots both claim meze as theirs. Famagusta (Gazimağusa) has seafood restaurants in the old walled city, though much of Varosha (the Greek Cypriot quarter) remains a ghost town, fenced off since 1974.

**Wine, Spirits & Agriculture**: Northern Cyprus grows citrus (oranges, lemons, grapefruits), olives, carobs, almonds, and some grapes. Wine production is limited compared to the south (Republic of Cyprus has Commandaria, indigenous grapes). A few wineries operate—Ergazi, Winemaker—producing reds and whites from Turkish and international varieties. Quality is improving but small-scale. Raki (similar to ouzo, arak) is the social drink—anise-flavored, drunk with water (turns milky), paired with meze. Brandy and zivania (Cypriot pomace brandy) are strong spirits. Turkish beer (Efes) is ubiquitous. Carob syrup (harnup pekmezi) is traditional—sweet, used in desserts and as spread. Olive oil production is local and excellent. Honey from mountain wildflowers is sold at markets.

**High-End Dining & Tourism**: Northern Cyprus doesn't have Michelin stars, but Kyrenia (Girne) and the Karpaz Peninsula have boutique hotels and restaurants catering to tourists (mostly Turkish, British expats, and some international). Niazi's Restaurant (Kyrenia) is legendary for meze and seafood. Bellapais Gardens serves Cypriot-Mediterranean fusion with abbey views. The Ambiance in Bellapais does upscale Turkish Cypriot food. Karpaz Gate Marina has waterfront dining—modern, expensive by local standards. The food is generally excellent, prices lower than southern Cyprus or mainland Europe. Casinos (legal in the north, illegal in the south) attract Turkish tourists; attached restaurants serve Turkish and international menus.

**Food Culture, Memory & Division**: Food in Northern Cyprus is inseparable from the island's partition. Turkish Cypriots displaced from the south brought recipes and memories; Greek Cypriots fled north, leaving behind homes and olive groves. The buffer zone (Green Line) bisects Nicosia—you can cross checkpoints and eat Turkish Cypriot meze in the north, Greek Cypriot souvlaki in the south within 20 minutes. The cuisines are siblings, not strangers, but politics shapes identity. Northern Cyprus's dependency on Turkey means Turkish ingredients, brands, and culinary norms dominate. Economic isolation (embargoes, lack of recognition) limits exports—halloumi from the north can't access EU markets under PDO rules. Yet food culture persists: family recipes, village festivals, the Sunday kleftiko tradition, the meze ritual. Older generations remember a unified island where food wasn't politicized. Younger generations know only division. Food is nostalgia, identity, and protest—every plate of şeftali, every glass of raki, every shared meze is both ordinary and freighted with history. Northern Cyprus is beautiful, hospitable, and unresolved. The food is a taste of what was and what might still be.`
  },
  {
    name: 'Norway',
    lat: 60.4720,
    lng: 8.4689,
    summary: `Norwegian cuisine is built on survival in one of the world's harshest climates—preserved fish, game, root vegetables, and dairy that could last through six-month winters. Then came oil wealth, New Nordic cooking, and a food culture that went from "brown food and cod" to Michelin stars and foraging-based fine dining. The result is bifurcated: traditional Norwegian food (lutefisk, smalahove, brown cheese) that feels like punishment, and modern Norwegian cuisine (Maaemo's 20-course tasting menus, Noma-trained chefs, reindeer with cloudberries) that's world-class. The seafood is extraordinary—salmon, cod, king crab, shellfish from Arctic waters. The game—moose, reindeer, wild fowl—is lean and flavorful. And the price is absurd: Norway is the most expensive country in Europe to eat in. But the ingredients are pristine, the culinary ambition is high, and the commitment to sustainability and seasonality is genuine. Norway's food is no longer a punchline; it's a destination.

**Traditional & Survival Foods**: Lutefisk (dried cod soaked in lye, gelatinous, divisive) is Christmas tradition—mostly eaten by older Norwegians and as cultural duty. Rakfisk (fermented trout, pungent) is another acquired taste. Smalahove (sheep's head, smoked and boiled, eaten with the eyes staring at you) is western Norway specialty—hardcore traditional. These are foods from an era when preservation was survival: salting, drying, fermenting, smoking. Klipfisk (salted and dried cod) was a global export; Norway supplied Catholic Europe for centuries. Pinnekjøtt (salted lamb ribs, steamed over birch branches) is Christmas dinner in western regions. Brunost (brown cheese, actually whey cheese—sweet, caramel-like) is spread on waffles or bread, polarizing for foreigners. Flatbrød (thin crisp bread) and lefse (soft potato flatbread) are staples.

**Seafood & Coastal Bounty**: Norway's seafood is the foundation. Salmon—farmed (contentious but ubiquitous) and wild (richer, seasonal)—is grilled, smoked, cured as gravlaks (salt-cured with dill). King crab from the Barents Sea is sweet and massive—Kirkenes near the Russian border is king crab central. Cod (torsk) is baked, poached, or turned into bacalao (with tomatoes and peppers, imported from Spain/Portugal, reinterpreted). Halibut, monkfish, langoustines, scallops, mussels—coastal waters are cold, clean, productive. Fish soup (fiskesuppe, creamy with root vegetables) is comfort. Shrimp (reker)—tiny cold-water prawns—are eaten by the kilo with mayo and bread at harborsides. Bergen's fish market is touristy but functional; locals buy fish for dinner there.

**New Nordic Movement & Michelin Stars**: Norway has embraced New Nordic cuisine—hyper-local, foraged, seasonal, technique-driven. Maaemo (Oslo, 3 Michelin stars) is the flagship: vegetables from Norwegian farms, seafood from Arctic waters, foraged ingredients (sea buckthorn, pine, sorrel), 20+ courses, $500+ per person. RE-NAA (Stavanger, 2 stars) focuses on western Norway ingredients and fermentation. Lysverket (Bergen, 1 star) does modern Norwegian with sustainability focus. Under (Lindesnes, 1 star)—Europe's first underwater restaurant, literally submerged—serves seafood with theater. Chefs like Esben Holmboe Bang (Maaemo), Sven Erik Renaa (RE-NAA), and Christopher Haatuft (Lysverket) are putting Norway on the culinary map. The movement emphasizes terroir, wild ingredients, and rejecting imports—a reaction against globalized food and a return to Norwegian identity.

**Game, Dairy & Mountain Foods**: Reindeer (caribou) is Sami heritage and fine dining staple—lean, gamey, served roasted with wild mushrooms and lingonberries. Moose (elg) is hunted in autumn; moose sausage and roasts are prized. Grouse (rype), duck, and wild fowl are traditional. Dairy is central: yogurt (especially thick cultured varieties), sour cream (rømme), and cheese. Jarlsberg is the export cheese (mild, nutty); Norvegia is the everyday cheese. Gamalost (old cheese, intensely pungent, almost no fat) is Vik tradition. Cloudberries (multe)—golden Arctic berries, tart-sweet—are luxury ingredient, made into jam and served with cream or on desserts. Juniper, wild thyme, and angelica are foraged for seasoning. Mountain farms (seter) produce summer cheeses and butter; seter culture is romantic but fading.

**Agricultural & Economic Realities**: Norwegian agriculture is small-scale and heavily subsidized—harsh climate, short growing season, rocky soil. Imports are necessary; domestic production covers ~40% of food needs. Potatoes, root vegetables (carrots, turnips), cabbage, and berries (lingonberries, blueberries, cloudberries) grow well. Grain production is limited to southern regions. Sheep graze mountain pastures in summer (transhumance tradition). Farming is expensive, protected by tariffs—Norwegian lamb costs 3x imported lamb. Aquaculture (salmon, trout) is a $10+ billion industry—environmentally controversial (sea lice, pollution, escapees) but economically vital. Fishing (wild cod, mackerel, herring) remains important; Norway is one of the world's largest seafood exporters. Oil wealth means food costs don't constrain policy—sustainability and food security trump efficiency.

**Food Culture & Price Shock**: Norwegians eat early—dinner is 5-6 PM. Lunch is often packed (matpakke—open-faced sandwiches). Coffee consumption is world-leading (9+ kg per capita/year)—filtered coffee, strong, consumed all day. Brown bag lunches and home cooking are norms; eating out is expensive ($25+ for casual meal, $100+ per person for fine dining). Alcohol is state-controlled (Vinmonopolet), taxed heavily, and expensive ($10+ for beer in bars). Aquavit (caraway-flavored spirit) is traditional, drunk ice-cold at Christmas and celebrations. Norwegians are egalitarian—fancy food is suspect unless it's "New Nordic" and sustainably sourced. Food waste is low; portion sizes are reasonable. The cuisine has gone from joke to serious in a generation, but the best food is still at home: grandma's lamb stew, foraged berries, fish caught that morning. The Michelin stars are great, but the soul of Norwegian food is in cabins, coastal villages, and the stubborn refusal to let a brutal climate dictate what's possible.`
  },
  {
    name: 'Oman',
    lat: 21.5126,
    lng: 55.9233,
    summary: `Omani cuisine is the Gulf's best-kept secret—less flashy than Dubai's restaurant scene, more authentic than Kuwait's mall food courts, and deeply rooted in a trading history that brought spices from Zanzibar, rice from India, and dried limes from Persia. This is shuwa (whole lamb marinated in spices and slow-cooked in an underground sand oven for 48 hours), majboos (spiced rice with meat), and halwa (a gelatinous, intensely sweet confection flavored with rosewater and saffron). Omani food is Bedouin hospitality meets Indian Ocean trade—cardamom, saffron, dried limes (loomi), frankincense, and dates are the flavor foundations. Coffee (kahwa) is ritual: lightly roasted, spiced with cardamom, served in tiny cups with dates, a gesture of welcome that predates oil wealth by centuries. The food culture is communal, generous, and tied to Oman's seafaring and desert heritage. Muscat's fine dining is emerging, but the real food is in homes and coastal villages where fish is grilled on beaches and rice is perfumed with spices from Zanzibar.

**National Dishes & Staples**: Shuwa is the ceremonial centerpiece—whole lamb or goat marinated in a spice paste (garlic, cumin, coriander, chili, dried lime), wrapped in banana or palm leaves, buried in a sand oven with hot coals, cooked for 1-2 days. The result is fall-apart tender, smoky, aromatic. Traditionally served at Eid and weddings. Majboos (also called kabsa in wider Gulf) is spiced rice with lamb, chicken, or fish—basmati rice cooked with tomatoes, dried limes, spices (cinnamon, cardamom, black lime), and meat. Each family has their version; it's the Sunday meal. Mashuai—grilled kingfish served on a bed of lemon rice—showcases Oman's coastal heritage. Harees (wheat and meat porridge, slow-cooked until smooth) is Ramadan iftar staple. Arsiya (rice with lamb or chicken, flavored with turmeric and spices, enriched with ghee) is festival food.

**Seafood & Coastal Cuisine**: Oman's 3,165-kilometer coastline provides lobster, kingfish, tuna, grouper, squid, and sardines. Fish is grilled simply with lemon and salt, or cooked in curries influenced by Indian workers and traders. Omani lobster (slipper lobster, no claws) is sweet and delicate—grilled or in majboos. Dried fish (laham) is preserved and used in stews or eaten with rice. Fish shuwa exists in coastal areas—fish instead of lamb, same underground technique. Sur and Salalah have vibrant fish markets—early morning, fresh catches, locals buying for the day. Shark is eaten in some coastal areas, controversial but traditional. The fishing industry is artisanal; traditional dhows (sambuk) still operate alongside modern boats. Omani sardines are exported; canned fish is a local industry.

**Spices, Sweets & Frankincense**: Omani halwa is iconic—thick, sticky, gelatinous sweet made from sugar, rosewater, saffron, cardamom, nuts, and cornstarch or ghee, cooked for hours. Served in small portions with kahwa; it's intensely sweet and perfumed. Offered to guests as hospitality. Each region has variations; Salalah's halwa is famous. Dates are omnipresent—Oman grows 250+ varieties. Khalas, Fardh, and Khasab dates are prized. Eaten fresh, dried, stuffed with nuts, or made into date syrup (dibs). Frankincense (luban), harvested in Dhofar (Salalah region), is chewed as gum, burned as incense, and occasionally used in cooking or drinks. It's been traded for millennia; Oman's frankincense trees are UNESCO-listed. The spice souk in Muttrah (Muscat) sells saffron, cardamom, dried limes, turmeric—vivid colors, intense aromas.

**Coffee & Hospitality Rituals**: Omani kahwa (coffee) is distinct—lightly roasted Arabica beans, ground with cardamom, brewed without sugar, served in small cups (finjan). It's pale, almost tea-like, fragrant, and drunk in three servings (declining after three is polite). Offering kahwa is sacred hospitality; refusing is rude. Always served with dates—the sweetness balances the coffee's bitterness. Coffee pots (dallah, ornate brass) are cultural symbols. Coffeehouses (majlis) are social spaces—traditional seating on floor cushions, conversation, tea or kahwa, sometimes shisha. Modern cafes in Muscat serve espresso and flat whites, but traditional kahwa culture persists in homes and villages.

**High-End Dining & Modern Omani Cuisine**: Muscat's dining scene is growing—upscale Omani, Indian, Persian, Lebanese, and international restaurants. The Chedi Muscat has fine dining with Arabic and Asian influences. Bait Al Luban (House of Frankincense) in Muttrah serves traditional Omani food elevated—shuwa, mashuai, halwa, in a restored heritage building. Al Angham (Royal Opera House Muscat) does refined Omani cuisine with live music. Turkish House, Ubhar, and Feeney's (international) cater to expats and tourists. Michelin stars don't exist in Oman, but the ingredients are excellent—fresh seafood, grass-fed lamb, local spices. The challenge: Omani cuisine isn't widely marketed; restaurants often serve pan-Arab or international menus rather than regional specialties. Home cooking remains the gold standard.

**Agricultural Products & Dates**: Oman's interior is mountainous and arid; agriculture is limited to wadis (valleys), oases, and terraced farms. Dates are the primary crop—over 8 million date palms, producing 350,000+ tons annually. Nizwa, Bahla, and Rustaq are date centers. Limes (dried into loomi, essential in Omani cooking) are imported or grown in Salalah. Pomegranates, mangoes, bananas, and papayas grow in Dhofar (southern region, monsoon-fed). Salalah produces coconuts—rare in Arabia. Livestock—goats, sheep, camels—are herded in the interior. Camel milk is consumed fresh or fermented. Fishing is vital: 200,000+ tons of fish caught annually. Oman imports most food; rice, wheat, vegetables, and dairy come from India, Pakistan, and beyond. Frankincense and dates are the exports.

**Food Culture, Bedouin Roots & Change**: Omani food culture is communal—meals are shared from large platters, eaten with the right hand, seated on floor cushions. Refusing food is offensive; hosts insist you eat more (echoing Bedouin generosity in scarcity). Ramadan transforms food culture: iftar (breaking fast) is dates, soup, and coffee, followed by majboos or harees. Eid al-Adha brings shuwa—families dig pits, neighbors share. Food is gendered: women cook, men host; though this is shifting in urban areas. Omani cuisine is under-documented—no celebrity chefs, few cookbooks, little international presence. The government is beginning to promote Omani food as tourism asset, but it's early. Youth are Westernizing—fast food, malls, global brands—while elders preserve traditions. The tension is real: KFC and McDonald's in every city, yet shuwa and kahwa remain identity. Oman's food is subtle, aromatic, tied to trade and desert—less bombastic than Emirati or Saudi cuisine, more refined. It deserves recognition, but for now, it's a secret best discovered in a coastal village, a Nizwa home, or a Muscat majlis where strangers are welcomed with coffee and dates.`
  }
]

async function saveFoodWriteups() {
  console.log('='.repeat(80))
  console.log('Starting Food & Cuisine Batch 9 generation...')
  console.log('='.repeat(80))
  console.log(`Total countries to process: ${foodWriteups.length}\n`)

  let successCount = 0
  let errorCount = 0

  for (const writeup of foodWriteups) {
    try {
      console.log(`\n${'='.repeat(80)}`)
      console.log(`Processing: ${writeup.name}`)
      console.log('='.repeat(80))

      // Check if location already has a food summary
      const existing = await prisma.locationSummary.findFirst({
        where: {
          name: writeup.name,
          category: 'food',
          type: 'country'
        }
      })

      if (existing) {
        console.log(`📝 Updating existing food summary for ${writeup.name}...`)
        await prisma.locationSummary.update({
          where: { id: existing.id },
          data: {
            summary: writeup.summary,
            lat: writeup.lat,
            lng: writeup.lng,
            updatedAt: new Date()
          }
        })
        console.log(`✅ ${writeup.name} food summary updated successfully!`)
      } else {
        console.log(`📝 Creating new food summary for ${writeup.name}...`)
        await prisma.locationSummary.create({
          data: {
            name: writeup.name,
            type: 'country',
            country: writeup.name,
            lat: writeup.lat,
            lng: writeup.lng,
            category: 'food',
            summary: writeup.summary,
            issues: JSON.stringify([]),
            topStories: JSON.stringify([]),
            storyCount: 0,
            updatedAt: new Date(),
            createdAt: new Date()
          }
        })
        console.log(`✅ ${writeup.name} food summary created successfully!`)
      }

      console.log(`   Character count: ${writeup.summary.length}`)
      successCount++

      // Rate limiting - small delay between database operations
      await new Promise((resolve) => setTimeout(resolve, 100))
    } catch (error) {
      console.error(`❌ Error processing ${writeup.name}:`, error)
      errorCount++
    }
  }

  console.log('\n' + '='.repeat(80))
  console.log('✅ Food & Cuisine Batch 9 generation complete!')
  console.log('='.repeat(80))
  console.log(`\n📊 Results:`)
  console.log(`   ✅ Successful: ${successCount}`)
  console.log(`   ❌ Errors: ${errorCount}`)
  console.log(`   📝 Total processed: ${foodWriteups.length}`)
  console.log(`\n🍽️ Countries processed:`)
  foodWriteups.forEach((w, i) => {
    console.log(`   ${i + 1}. ${w.name}`)
  })
}

saveFoodWriteups()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
