import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// ALL REMAINING 98 COUNTRIES (31-128) with concise comprehensive summaries
const MEGA_BATCH = [
  // Europe (20 countries: Italy-Portugal)
  { name: 'Italy', lat: 41.8719, lng: 12.5674, summary: 'Meloni right-wing government, economic stagnation 1%, extremely high debt 140% GDP, aging demographics, North-South inequality, migration Mediterranean pressures.', issues: ['Economic stagnation', 'Debt 140% GDP', 'Aging demographics oldest in EU', 'North-South inequality', 'Organized crime'] },
  { name: 'Spain', lat: 40.4637, lng: -3.7492, summary: 'Sánchez socialist coalition, Catalan amnesty controversy, unemployment 12%, youth 25%, over-tourism pressures, housing crisis.', issues: ['Catalan independence tensions', 'Political fragmentation coalitions', 'Youth unemployment 25%', 'Housing crisis', 'Over-tourism'] },
  { name: 'Poland', lat: 51.9194, lng: 19.1451, summary: 'Tusk democratic restoration after PiS authoritarianism, judicial independence battles, Ukraine support 1M refugees, EU funds unfrozen.', issues: ['Judicial independence restoration', 'Presidential veto blocking reforms', 'Inflation pressures', 'Ukrainian refugees 1M+', 'Agricultural Ukraine trade disputes'] },
  { name: 'Ukraine', lat: 48.3794, lng: 31.1656, summary: 'Existential war vs Russia 1000+ days, grinding attritional warfare, Western aid dependency, $400B+ reconstruction needs, Zelenskyy wartime leadership.', issues: ['Grinding warfare high casualties', 'Western aid ammunition dependency', 'Reconstruction $400B+', 'Infrastructure Russian attacks', 'Mobilization sustainability'] },
  { name: 'Russia', lat: 61.5240, lng: 105.3188, summary: 'Putin authoritarian war prosecuting Ukraine invasion failure, severe repression, Western sanctions, Navalny death, international pariah status.', issues: ['Ukraine war stalemate casualties', 'Western sanctions isolation', 'Total domestic repression', 'Economic long-term decline', 'International pariah status'] },
  { name: 'Turkey', lat: 38.9637, lng: 35.2433, summary: 'Erdoğan authoritarian rule 20+ years, hyperinflation 60-70%, lira collapse, 2023 earthquake 50k deaths, Syrian refugees 3.5M, Kurdish conflict.', issues: ['Hyperinflation 60-70%', 'Authoritarian consolidation', 'Syrian refugees tensions', 'Earthquake reconstruction', 'Kurdish conflict exclusion'] },
  { name: 'Greece', lat: 39.0742, lng: 21.8243, summary: 'Mitsotakis conservative stability, economic recovery eurozone crisis, migration Aegean pressures, Turkey tensions, climate wildfires catastrophic.', issues: ['Migration Aegean border', 'Turkey territorial disputes', 'Climate wildfires extreme', 'High debt 160% GDP', 'Over-tourism housing'] },
  { name: 'Belgium', lat: 50.5039, lng: 4.4699, summary: 'EU capital, linguistic Flanders-Wallonia divisions, coalition complexity, prosperity, terrorism security risks.', issues: ['Linguistic divisions', 'Coalition complexity', 'Terrorism risks', 'Public debt fiscal', 'Regional disparities'] },
  { name: 'Austria', lat: 47.5162, lng: 14.5501, summary: 'Prosperity, far-right FPÖ strength, Russian energy dependence, immigration debates, neutrality vs EU defense.', issues: ['Far-right FPÖ surge', 'Russian energy dependency', 'Immigration debates', 'Neutrality EU defense', 'Housing cities'] },
  { name: 'Finland', lat: 61.9241, lng: 25.7482, summary: 'NATO accession post-Russia invasion, welfare state model, immigration debates, technological innovation, Arctic climate impacts.', issues: ['NATO Russia tensions', 'Welfare state fiscal pressures', 'Immigration integration', 'Aging demographics', 'Arctic climate'] },
  { name: 'Denmark', lat: 56.2639, lng: 9.5018, summary: 'Nordic welfare model, economic competitiveness, immigration restrictions, climate leadership, EU selective integration opt-outs.', issues: ['Immigration restrictions', 'Welfare sustainability', 'Climate costs', 'Labor pressures', 'EU opt-outs'] },
  { name: 'Ireland', lat: 53.4129, lng: -8.2439, summary: 'Tech/pharma hub prosperity, severe housing crisis, healthcare strain, Northern Ireland Brexit complications, infrastructure deficits despite wealth.', issues: ['Housing crisis severe', 'Healthcare strain', 'Corporate tax sustainability', 'NI protocol Brexit', 'Infrastructure gaps'] },
  { name: 'Hungary', lat: 47.1625, lng: 19.5033, summary: 'Orbán authoritarian government, EU rule-of-law conflicts, judicial independence eliminated, press freedom restrictions, LGBTQ+ attacks.', issues: ['Authoritarian democratic backsliding', 'EU rule-of-law battles', 'Judicial independence elimination', 'Press freedom attacks', 'LGBTQ+ discrimination'] },
  { name: 'Czech Republic', lat: 49.8175, lng: 15.4730, summary: 'Center-right pro-EU government, energy transition coal dependency, inflation pressures, Ukrainian refugees, populist opposition.', issues: ['Energy transition coal', 'Inflation living costs', 'Populist opposition', 'Labor shortages', 'Ukrainian refugees'] },
  { name: 'Bulgaria', lat: 42.7339, lng: 25.4858, summary: 'Political instability coalition collapses, endemic corruption, organized crime, EU lowest living standards, brain drain emigration.', issues: ['Political instability', 'Endemic corruption', 'Organized crime', 'EU lowest income', 'Brain drain'] },
  { name: 'Croatia', lat: 45.1, lng: 15.2, summary: 'Tourism prosperity, eurozone Schengen entry, corruption scandals, demographic decline severe, regional inequality.', issues: ['Corruption scandals', 'Demographic decline severe', 'Regional inequality', 'Tourism seasonal dependency', 'Emigration West'] },
  { name: 'Estonia', lat: 58.5953, lng: 25.0136, summary: 'Digital governance leader, Russia security proximity threat, energy independence costs, demographic decline, Russian minority integration.', issues: ['Russia security proximity', 'Energy independence costs', 'Demographic decline', 'Russian minority', 'Inflation'] },
  { name: 'Norway', lat: 60.4720, lng: 8.4689, summary: 'Oil wealth sovereign fund, prosperity welfare state, green transition costs, immigration labor dependency, EU non-member EEA.', issues: ['Oil decline management', 'Green transition costs', 'Immigration labor dependency', 'Welfare sustainability', 'EU EEA limitations'] },
  { name: 'Sweden', lat: 60.1282, lng: 18.6435, summary: 'Gang violence shootings epidemic, NATO accession neutrality abandoned, welfare state pressures, immigration integration failures, center-right government.', issues: ['Gang violence epidemic', 'Immigration integration failure', 'Welfare fiscal pressures', 'NATO Sweden Democrats', 'Energy nuclear'] },
  { name: 'Portugal', lat: 39.3999, lng: -8.2245, summary: 'Tourism prosperity, housing crisis tourism-driven, low wages emigration, high public debt, aging demographics, healthcare pressures.', issues: ['Housing crisis tourism', 'Low wages emigration', 'High debt', 'Aging demographics', 'Healthcare pressures'] },

  // Continued Europe + Asia
  { name: 'Netherlands', lat: 52.1326, lng: 5.2913, summary: 'Prosperity, far-right Wilders government, housing crisis, nitrogen emissions agriculture, EU skepticism.', issues: ['Far-right government', 'Housing crisis severe', 'Nitrogen emissions', 'Immigration tensions', 'EU skepticism'] },
  { name: 'Romania', lat: 45.9432, lng: 24.9668, summary: 'EU member corruption endemic, brain drain emigration West, political instability, economic growth moderate, rule-of-law challenges.', issues: ['Corruption endemic', 'Brain drain West', 'Political instability', 'Judicial independence', 'Rural poverty'] },
  { name: 'Serbia', lat: 44.0165, lng: 21.0059, summary: 'Vučić authoritarian tendencies, EU accession stalled Kosovo, Russia China ties, media freedom deterioration, economic stagnation.', issues: ['Authoritarian tendencies', 'Kosovo non-recognition EU obstacle', 'Media freedom decline', 'Russia China alignment', 'Economic stagnation'] },
  { name: 'Switzerland', lat: 46.8182, lng: 8.2275, summary: 'Prosperity neutrality, banking secrecy reduced, EU relationship complex, immigration quotas, high living costs.', issues: ['EU relationship complex', 'Immigration quotas', 'Banking transparency pressures', 'High living costs', 'Housing crisis'] },
  { name: 'Slovakia', lat: 48.6690, lng: 19.6990, summary: 'Fico government pro-Russia stance, media freedom concerns, judicial independence battles, EU funds disputes, corruption.', issues: ['Pro-Russia Fico government', 'Media freedom decline', 'Judicial independence', 'EU funds disputes', 'Corruption'] },
  { name: 'Lithuania', lat: 55.1694, lng: 23.8813, summary: 'Russia security threat proximity, NATO eastern flank, Belarus migration crisis, energy independence achieved, democratic stability.', issues: ['Russia security threat', 'Belarus migration weaponization', 'Energy independence costs', 'Demographic decline', 'Emigration'] },
  { name: 'Latvia', lat: 56.8796, lng: 24.6032, summary: 'Russia security proximity, Russian minority integration 25%, NATO Baltic defense, demographic decline, emigration West.', issues: ['Russia security', 'Russian minority 25%', 'Demographic decline severe', 'Emigration', 'Energy costs'] },

  // Asia (China through Yemen - 50 countries)
  { name: 'China', lat: 35.8617, lng: 104.1954, summary: 'Xi Jinping authoritarian rule, economic slowdown real estate crisis, demographic decline, tech competition US, Taiwan tensions, zero-COVID legacy.', issues: ['Economic slowdown property crisis', 'Demographic decline aging', 'US tech competition decoupling', 'Taiwan conflict risks', 'Authoritarian repression Xinjiang'] },
  { name: 'India', lat: 20.5937, lng: 78.9629, summary: 'Modi BJP Hindu nationalism, economic growth fastest major economy 6-7%, democratic backsliding concerns, Kashmir tensions, infrastructure development.', issues: ['Democratic backsliding press freedom', 'Hindu nationalism Muslim tensions', 'Air pollution severe', 'Inequality extreme', 'Infrastructure gaps'] },
  { name: 'Japan', lat: 36.2048, lng: 138.2529, summary: 'Aging demographics crisis, economic stagnation 1%, debt 260% GDP highest globally, defense buildup China concerns, political stability LDP.', issues: ['Aging demographics extreme', 'Debt 260% GDP', 'Economic stagnation deflation', 'China security threat', 'Population decline'] },
  { name: 'South Korea', lat: 37.5665, lng: 126.9780, summary: 'Tech powerhouse Samsung/Hyundai, North Korea nuclear threat, demographic collapse fertility 0.7, political polarization, economic inequality.', issues: ['Demographic collapse 0.7 fertility', 'North Korea nuclear threat', 'Political polarization', 'Economic inequality chaebol', 'Housing unaffordability'] },
  { name: 'North Korea', lat: 40.3399, lng: 127.5101, summary: 'Kim Jong Un totalitarian dictatorship, nuclear weapons program, economic collapse sanctions, humanitarian catastrophe, China Russia alignment.', issues: ['Totalitarian repression', 'Nuclear weapons development', 'Humanitarian catastrophe famine', 'International isolation sanctions', 'Economic collapse'] },
  { name: 'Indonesia', lat: -0.7893, lng: 113.9213, summary: 'Prabowo government 2024, economic growth 5%, democratic consolidation concerns, Islamic conservatism rising, deforestation palm oil.', issues: ['Democratic backsliding concerns', 'Islamic conservatism rising', 'Deforestation environmental', 'Corruption endemic', 'Infrastructure gaps'] },
  { name: 'Australia', lat: -25.2744, lng: 133.7751, summary: 'Albanese Labor government, China relations complex, AUKUS security pact, climate change impacts fires floods, housing crisis, indigenous Voice referendum failed.', issues: ['China relationship tensions trade', 'Housing affordability crisis', 'Climate fires floods', 'Indigenous reconciliation Voice failed', 'Cost-of-living pressures'] },
  { name: 'New Zealand', lat: -40.9006, lng: 174.8860, summary: 'Luxon center-right government 2023, economic recession pressures, housing crisis, Māori relations tensions, climate vulnerability.', issues: ['Economic recession pressures', 'Housing crisis severe', 'Māori relations tensions', 'Climate vulnerability', 'Cost-of-living'] },
  { name: 'Pakistan', lat: 30.3753, lng: 69.3451, summary: 'Economic crisis IMF bailouts, political instability Imran Khan imprisoned, terrorism TTP resurgence, floods climate, Afghanistan Taliban relations.', issues: ['Economic crisis IMF $6B', 'Political instability Khan jailed', 'Terrorism TTP resurgence', 'Floods climate devastation', 'Energy crisis'] },
  { name: 'Bangladesh', lat: 23.6850, lng: 90.3563, summary: 'Hasina authoritarian rule 15+ years, economic growth garment exports, democratic backsliding, climate vulnerability floods, Rohingya refugees 1M.', issues: ['Authoritarian Hasina rule', 'Democratic backsliding', 'Climate vulnerability extreme', 'Rohingya refugees 1M', 'Garment worker exploitation'] },
  { name: 'Afghanistan', lat: 33.9391, lng: 67.7100, summary: 'Taliban totalitarian Islamic Emirate, women rights eliminated, humanitarian catastrophe, opium production, international isolation, terrorism ISIS-K.', issues: ['Taliban totalitarian regime', 'Women rights eliminated', 'Humanitarian catastrophe', 'Economic collapse', 'ISIS-K terrorism'] },
  { name: 'Iran', lat: 32.4279, lng: 53.6880, summary: 'Theocratic authoritarian regime, economic crisis sanctions, protests Mahsa Amini crushed, nuclear program enrichment, Israel tensions escalating, Russia alignment.', issues: ['Theocratic repression protests crushed', 'Economic crisis sanctions', 'Nuclear enrichment 60%', 'Israel conflict escalation', 'Women rights protests'] },
  { name: 'Israel', lat: 31.0461, lng: 34.8516, summary: 'Netanyahu government, Gaza war October 2023 ongoing, judicial reform protests, West Bank settlements expansion, Iran nuclear threat, political polarization extreme.', issues: ['Gaza war humanitarian catastrophe', 'Judicial independence crisis', 'West Bank settlements expansion', 'Iran nuclear threat', 'Political polarization extreme'] },
  { name: 'Palestine', lat: 31.9522, lng: 35.2332, summary: 'Gaza humanitarian catastrophe war devastation, West Bank settlements expansion, Palestinian Authority weak, Hamas control Gaza, peace prospects collapsed.', issues: ['Gaza war devastation 40k+ deaths', 'Humanitarian catastrophe', 'West Bank occupation settlements', 'Political division Hamas-Fatah', 'Peace process collapsed'] },
  { name: 'Iraq', lat: 33.2232, lng: 43.6793, summary: 'Political instability sectarian, corruption endemic oil revenues, ISIS remnants, Iran influence dominant, infrastructure destroyed, water crisis.', issues: ['Political instability sectarian', 'Corruption endemic oil theft', 'Iran influence dominant', 'ISIS remnants terrorism', 'Water crisis climate'] },
  { name: 'Jordan', lat: 30.5852, lng: 36.2384, summary: 'Monarchy stability Abdullah II, economic challenges unemployment, Syrian refugees 1.3M, water scarcity extreme, peace treaty Israel, IMF reforms.', issues: ['Economic challenges unemployment', 'Syrian refugees 1.3M burden', 'Water scarcity extreme', 'Public debt high', 'Youth frustration'] },
  { name: 'Cambodia', lat: 12.5657, lng: 104.9910, summary: 'Hun Sen authoritarian dynasty son Hun Manet, democratic facade, Chinese influence dominant, economic growth garments tourism, opposition eliminated.', issues: ['Authoritarian Hun dynasty', 'Opposition eliminated jailed', 'Chinese influence debt trap', 'Democratic facade', 'Labor rights violations'] },
  { name: 'Laos', lat: 19.8563, lng: 102.4955, summary: 'Communist one-party authoritarian, Chinese influence dominant Belt-Road, economic crisis debt, Mekong dams environmental, limited freedoms.', issues: ['Authoritarian one-party', 'Chinese debt trap influence', 'Economic crisis debt', 'Mekong dams environmental', 'Repression freedoms'] },
  { name: 'Myanmar', lat: 21.9162, lng: 95.9560, summary: 'Military junta coup 2021, civil war resistance, Rohingya genocide, economic collapse, humanitarian crisis, ASEAN isolation ineffective.', issues: ['Military junta civil war', 'Humanitarian crisis', 'Economic collapse', 'Rohingya genocide', 'Resistance fighting ongoing'] },
  { name: 'Nepal', lat: 28.3949, lng: 84.1240, summary: 'Political instability coalition governments, earthquake vulnerability, economic dependence remittances India, China India competition, poverty.', issues: ['Political instability coalitions', 'Earthquake vulnerability', 'Economic dependence remittances', 'China-India competition', 'Poverty rural'] },
  { name: 'Mongolia', lat: 46.8625, lng: 103.8467, summary: 'Democracy between Russia China giants, mining economy copper coal, corruption, environmental degradation, nomadic culture decline.', issues: ['Geopolitical Russia-China pressure', 'Mining economy commodity dependence', 'Corruption endemic', 'Environmental degradation', 'Air pollution severe'] },
  { name: 'Papua New Guinea', lat: -6.3150, lng: 143.9555, summary: 'Resource-rich governance weak, tribal violence, corruption endemic, China influence growing, climate vulnerability, infrastructure deficits.', issues: ['Governance weakness', 'Tribal violence', 'Corruption endemic', 'China influence', 'Infrastructure poverty'] },
  { name: 'Fiji', lat: -17.7134, lng: 178.0650, summary: 'Democracy restored, tourism economy climate vulnerable, ethnic Fijian-Indian tensions, China influence, climate change existential.', issues: ['Ethnic tensions', 'Climate change existential', 'Tourism dependency', 'China influence debt', 'Governance corruption'] },
  { name: 'Bahrain', lat: 26.0667, lng: 50.5577, summary: 'Sunni monarchy Shia majority, protests 2011 crushed, Saudi influence, economic diversification oil declining, migrant labor exploitation.', issues: ['Sectarian Sunni-Shia repression', 'Democratic rights eliminated', 'Economic diversification challenges', 'Migrant labor exploitation', 'Saudi dependence'] },
  { name: 'Kuwait', lat: 29.3117, lng: 47.4818, summary: 'Oil wealth sovereign fund, parliamentary democracy limited, corruption, expatriate majority 70%, regional tensions Iran.', issues: ['Political deadlock parliament', 'Corruption endemic', 'Expatriate majority 70%', 'Oil dependence', 'Regional tensions Iran'] },
  { name: 'Oman', lat: 21.4735, lng: 55.9754, summary: 'Sultan Haitham moderate, economic diversification oil declining, regional mediator Iran-West, fiscal deficits, youth unemployment.', issues: ['Economic diversification oil decline', 'Fiscal deficits debt', 'Youth unemployment', 'Succession stability', 'Regional tensions'] },
  { name: 'Qatar', lat: 25.3548, lng: 51.1839, summary: 'Gas wealth LNG exports, World Cup 2022 migrant labor abuses, regional isolation blockade ended, mediation role Israel-Hamas, authoritarian monarchy.', issues: ['Migrant labor exploitation', 'Authoritarian monarchy', 'Regional tensions', 'Gas dependence', 'Post-World Cup economic'] },
  { name: 'Kazakhstan', lat: 48.0196, lng: 66.9237, summary: 'Tokayev president post-Nazarbayev transition, authoritarian, economic growth oil-gas, protests 2022 crushed, Russia influence balancing China.', issues: ['Authoritarian regime', 'Protests 2022 crushed', 'Oil-gas dependence', 'Russia influence pressure', 'Corruption endemic'] },
  { name: 'Thailand', lat: 15.8700, lng: 100.9925, summary: 'Military influence persistent, Paetongtarn Shinawatra PM 2024, Monarchy lèse-majesté laws, tourism economy, political instability coups.', issues: ['Military influence coups', 'Lèse-majesté monarchy laws repression', 'Political instability', 'Tourism dependency', 'Southern insurgency'] },
  { name: 'Vietnam', lat: 14.0583, lng: 108.2772, summary: 'Communist one-party authoritarian, economic growth manufacturing 6%+, China tensions South China Sea, human rights repression, environmental degradation.', issues: ['Authoritarian one-party repression', 'China South China Sea tensions', 'Environmental degradation', 'Corruption crackdowns selective', 'Labor rights violations'] },
  { name: 'Philippines', lat: 12.8797, lng: 121.7740, summary: 'Marcos Jr. president 2022 dynastic return, drug war legacy Duterte, South China Sea China tensions, economic inequality, infrastructure deficits.', issues: ['China South China Sea aggression', 'Drug war legacy extrajudicial', 'Economic inequality extreme', 'Infrastructure gaps', 'Political dynasties'] },
  { name: 'Malaysia', lat: 4.2105, lng: 101.9758, summary: 'Anwar Ibrahim PM reform promises, corruption endemic 1MDB scandal, ethnic Malay preferences, Islamic conservatism, economic inequality.', issues: ['Corruption 1MDB scandal', 'Ethnic Malay preferences tensions', 'Islamic conservatism', 'Political instability', 'Economic inequality'] },
  { name: 'Singapore', lat: 1.3521, lng: 103.8198, summary: 'PAP one-party dominance, economic prosperity hub, limited political freedoms, high living costs, migrant labor dependency, environmental sustainability.', issues: ['Political freedoms limited', 'High living costs housing', 'Migrant labor dependency', 'Succession PAP dominance', 'Water dependence Malaysia'] },
  { name: 'Taiwan', lat: 23.6978, lng: 120.9605, summary: 'Democracy vibrant Lai president DPP, China invasion threat tensions, semiconductor dominance TSMC, economic China dependency, US support critical.', issues: ['China invasion threat growing', 'Economic China dependency', 'Semiconductor dominance vulnerability', 'Political polarization China', 'Aging demographics'] },
  { name: 'Sri Lanka', lat: 7.8731, lng: 80.7718, summary: 'Economic crisis 2022 bankruptcy, political instability Rajapaksa ousted, IMF bailout austerity, Tamil reconciliation incomplete, Chinese debt trap.', issues: ['Economic crisis bankruptcy', 'Political instability', 'IMF austerity social pain', 'Tamil reconciliation incomplete', 'Chinese debt trap'] },
  { name: 'Yemen', lat: 15.5527, lng: 48.5164, summary: 'Civil war Houthis vs government 10 years, humanitarian catastrophe famine, Saudi-Iran proxy war, fragmentation territory, peace elusive.', issues: ['Civil war decade', 'Humanitarian catastrophe famine', 'Saudi-Iran proxy war', 'Houthi Red Sea attacks', 'State collapse fragmentation'] },
  { name: 'Saudi Arabia', lat: 23.8859, lng: 45.0792, summary: 'MBS Vision 2030 economic diversification, authoritarian repression Khashoggi, oil dominance OPEC, Yemen war, Israel normalization pursued, megaprojects NEOM.', issues: ['Authoritarian MBS repression Khashoggi', 'Economic diversification oil dependence', 'Yemen war humanitarian', 'Migrant labor exploitation', 'Social reforms controlled'] },
  { name: 'UAE', lat: 23.4241, lng: 53.8478, summary: 'Economic diversification success Dubai, authoritarian monarchy, migrant labor 90%, regional power projection, Israel normalization, climate COP28 greenwashing.', issues: ['Authoritarian monarchy', 'Migrant labor 90% exploitation', 'Economic inequality', 'Regional interventionism', 'Climate hypocrisy oil'] },
  { name: 'Lebanon', lat: 33.8547, lng: 35.8623, summary: 'State collapse economic crisis, political paralysis sectarian, Beirut blast 2020, Hezbollah dominance, Syrian refugees 1.5M, banking crisis.', issues: ['Economic collapse hyperinflation', 'Political paralysis sectarian', 'Hezbollah dominance Iran', 'Banking crisis deposits theft', 'Syrian refugees 1.5M'] },
  { name: 'Syria', lat: 34.8021, lng: 38.9968, summary: 'Assad regime survival civil war, humanitarian catastrophe 500k deaths, Russian Iranian support, economic collapse sanctions, fragmentation territory Kurds.', issues: ['Civil war Assad survival', 'Humanitarian catastrophe', 'Economic collapse sanctions', 'Russian Iranian occupation', 'Fragmentation Kurds Turkey'] },
  { name: 'Solomon Islands', lat: -9.6457, lng: 160.1562, summary: 'China security pact 2022 concerns, ethnic tensions, governance corruption, climate vulnerability, Australia relationship strained.', issues: ['China security pact', 'Ethnic tensions', 'Governance corruption', 'Climate vulnerability', 'Australia concerns'] },
  { name: 'Vanuatu', lat: -15.3767, lng: 166.9592, summary: 'Climate change existential threat, political instability, China influence, economic tourism agriculture, cyclone vulnerability.', issues: ['Climate existential threat', 'Political instability', 'China influence', 'Cyclone devastation', 'Economic fragility'] },
  { name: 'Samoa', lat: -13.7590, lng: -172.1046, summary: 'Political stability, China influence switch recognition Taiwan, rugby culture, tourism economy, climate vulnerability.', issues: ['China influence Taiwan switch', 'Climate vulnerability', 'Tourism dependency', 'Economic fragility', 'Governance'] },
  { name: 'Tonga', lat: -21.1789, lng: -175.1982, summary: 'Monarchy constitutional, 2022 volcano tsunami devastation, China influence debt, climate vulnerability, economic fragility remittances.', issues: ['2022 volcano devastation', 'China debt trap', 'Climate vulnerability', 'Economic fragility', 'Monarchy limited democracy'] },

  // Africa (Egypt through Botswana - 38 countries)
  { name: 'Egypt', lat: 26.8206, lng: 30.8025, summary: 'Sisi authoritarian rule, economic crisis inflation 30%, IMF bailouts $60B, Suez Canal revenues down Houthi, Gaza border role, repression dissent.', issues: ['Authoritarian Sisi repression', 'Economic crisis inflation debt', 'IMF bailouts $60B', 'Suez revenues down', 'Gaza refugee pressures'] },
  { name: 'Ethiopia', lat: 9.1450, lng: 40.4897, summary: 'Tigray war ended 2022 600k deaths, Abiy Nobel laureate authoritarian turn, ethnic conflicts, economic crisis, GERD Nile dam Egypt tensions.', issues: ['Tigray war aftermath', 'Ethnic conflicts Amhara Oromo', 'Economic crisis currency', 'GERD dam Egypt tensions', 'Authoritarian Abiy turn'] },
  { name: 'Kenya', lat: -0.0236, lng: 37.9062, summary: 'Ruto government 2022, economic challenges debt, tax protests June 2024 Gen-Z, corruption endemic, terrorism Al-Shabaab, Haiti intervention leadership.', issues: ['Economic debt crisis taxes', 'Gen-Z protests June 2024', 'Corruption endemic', 'Terrorism Al-Shabaab', 'Political instability'] },
  { name: 'Somalia', lat: 5.1521, lng: 46.1996, summary: 'State fragility Al-Shabaab control regions, humanitarian crisis famine, political instability, Turkish influence, Ethiopia Somaliland tensions port.', issues: ['Al-Shabaab terrorism control', 'State fragility', 'Humanitarian crisis famine', 'Ethiopia tensions Somaliland', 'Political instability'] },
  { name: 'Sudan', lat: 12.8628, lng: 30.2176, summary: 'Civil war April 2023 RSF vs Army, humanitarian catastrophe 10M displaced, Darfur genocide renewed, economic collapse, international neglect.', issues: ['Civil war RSF-Army', 'Humanitarian catastrophe displacement', 'Darfur genocide renewed', 'Economic collapse', 'International neglect'] },
  { name: 'Algeria', lat: 28.0339, lng: 1.6596, summary: 'Military authoritarian Tebboune, Hirak protests repressed, gas exports Europe opportunity, economic stagnation, youth unemployment emigration.', issues: ['Authoritarian military regime', 'Hirak protests repressed', 'Economic stagnation', 'Youth unemployment emigration', 'Gas revenue dependency'] },
  { name: 'Angola', lat: -11.2027, lng: 17.8739, summary: 'MPLA authoritarian João Lourenço, oil dependence economy, corruption endemic Isabel dos Santos, economic diversification attempts, China debt.', issues: ['Oil dependence', 'Corruption endemic Dos Santos', 'Economic diversification challenges', 'China debt trap', 'Poverty extreme'] },
  { name: 'Ghana', lat: 7.9465, lng: -1.0232, summary: 'Democratic stability West Africa, economic crisis IMF bailout, debt default restructuring, corruption, gold cocoa exports.', issues: ['Economic crisis debt default', 'IMF bailout restructuring', 'Corruption endemic', 'Energy crisis power cuts', 'Inflation pressures'] },
  { name: 'Mozambique', lat: -18.6657, lng: 35.5296, summary: 'Insurgency Cabo Delgado ISIS, gas reserves LNG projects delayed, corruption endemic, poverty extreme, cyclone climate vulnerability.', issues: ['Insurgency Cabo Delgado ISIS', 'Corruption endemic', 'Poverty extreme 60%+', 'Cyclone devastation climate', 'Gas LNG delays'] },
  { name: 'Senegal', lat: 14.4974, lng: -14.4524, summary: 'Faye president 2024 democratic transition, political stability West Africa, economic growth, fishing EU overfishing, youth emigration Europe.', issues: ['Youth unemployment emigration', 'EU fishing overfishing', 'Economic dependence fish peanuts', 'Political reform demands', 'Infrastructure gaps'] },
  { name: 'Democratic Republic of Congo', lat: -4.0383, lng: 21.7587, summary: 'M23 conflict Rwanda proxy eastern regions, humanitarian crisis 7M displaced, cobalt mining child labor, corruption Kabila legacy, political instability Tshisekedi.', issues: ['M23 conflict Rwanda proxy', 'Humanitarian crisis displacement', 'Cobalt mining exploitation children', 'Corruption endemic', 'Political instability'] },
  { name: 'Nigeria', lat: 9.0820, lng: 8.6753, summary: 'Tinubu government 2023 subsidy removal protests, Boko Haram terrorism, economic challenges oil theft, currency naira collapse, banditry kidnappings.', issues: ['Boko Haram terrorism', 'Economic crisis subsidy removal', 'Naira currency collapse', 'Oil theft corruption', 'Banditry kidnapping epidemic'] },
  { name: 'South Africa', lat: -30.5595, lng: 22.9375, summary: 'ANC lost majority 2024 coalition GNU, load-shedding electricity crisis, corruption state capture, crime violence high, unemployment 32%, inequality extreme.', issues: ['ANC lost majority coalition', 'Load-shedding electricity crisis', 'Corruption state capture', 'Unemployment 32%', 'Crime violence extreme'] },
  { name: 'Morocco', lat: 31.7917, lng: -7.0926, summary: 'Monarchy Mohammed VI, Western Sahara annexation, economic growth tourism, earthquake 2023 3k deaths, Israel normalization Abraham Accords.', issues: ['Western Sahara occupation', '2023 earthquake 3k deaths', 'Authoritarian monarchy', 'Economic inequality', 'Migration to Europe'] },
  { name: 'Tunisia', lat: 33.8869, lng: 9.5375, summary: 'Saied authoritarian coup democracy eliminated, economic crisis IMF negotiations, migration Europe departures, Arab Spring birthplace backsliding.', issues: ['Authoritarian Saied coup', 'Democratic backsliding Arab Spring reversed', 'Economic crisis IMF', 'Migration Europe departures', 'Political repression'] },
  { name: 'Libya', lat: 26.3351, lng: 17.2283, summary: 'Political division East-West governments, oil economy, mercenaries Wagner, migration Europe route, Derna floods 2023 6k deaths.', issues: ['Political division East-West', 'Mercenaries Wagner Russian', 'Oil economy corruption', 'Migration Europe hub', 'Derna floods 2023 devastation'] },
  { name: 'Tanzania', lat: -6.3690, lng: 34.8888, summary: 'Hassan first female president, economic growth tourism, authoritarian tendencies press freedom, opposition repression, infrastructure Chinese.', issues: ['Press freedom deterioration', 'Opposition repression', 'Corruption endemic', 'Chinese debt infrastructure', 'LGBTQ+ persecution'] },
  { name: 'Uganda', lat: 1.3733, lng: 32.2903, summary: 'Museveni authoritarian 38 years, opposition repression Wine, oil development TotalEnergies, LGBTQ+ persecution Anti-Homosexuality Act, economic growth moderate.', issues: ['Museveni 38 years repression', 'Opposition repression Wine', 'LGBTQ+ persecution death penalty', 'Oil development environmental', 'Corruption endemic'] },
  { name: 'Zimbabwe', lat: -19.0154, lng: 29.1549, summary: 'Mnangagwa ZANU-PF authoritarian Mugabe legacy, economic collapse hyperinflation, currency crisis, opposition repression CCC, gold mining.', issues: ['Economic collapse hyperinflation', 'Authoritarian ZANU-PF repression', 'Currency crisis', 'Opposition repression CCC', 'Corruption endemic'] },
  { name: 'Cameroon', lat: 7.3697, lng: 12.3547, summary: 'Biya authoritarian 42 years, Anglophone crisis separatist war, Boko Haram terrorism north, corruption endemic, economic stagnation.', issues: ['Biya 42 years authoritarian', 'Anglophone crisis civil war', 'Boko Haram terrorism', 'Corruption endemic', 'Economic stagnation'] },
  { name: 'Zambia', lat: -13.1339, lng: 27.8493, summary: 'Hichilema democratic transition 2021, economic crisis debt default restructuring, copper mining dependence, corruption Lungu legacy, power crisis.', issues: ['Economic crisis debt default', 'Copper dependence', 'Power crisis load-shedding', 'Corruption Lungu legacy', 'Infrastructure gaps'] },
  { name: 'Mali', lat: 17.5707, lng: -3.9962, summary: 'Military junta coups 2020-2021, Russian Wagner mercenaries, jihadist insurgency, French withdrawal ECOWAS suspension, humanitarian crisis.', issues: ['Military junta authoritarian', 'Wagner Russian mercenaries', 'Jihadist insurgency', 'French withdrawal', 'Humanitarian crisis'] },
  { name: 'Niger', lat: 17.6078, lng: 8.0817, summary: 'Military coup 2023 Tchiani, Russian Wagner presence, French expelled, uranium mining, jihadist insurgency, ECOWAS sanctions.', issues: ['Military coup 2023', 'Wagner Russian mercenaries', 'Jihadist insurgency', 'French expelled', 'ECOWAS sanctions'] },
  { name: 'Chad', lat: 15.4542, lng: 18.7322, summary: 'Déby dynasty succession Mahamat, French military presence, jihadist threats, oil economy, poverty extreme, political repression.', issues: ['Déby dynasty authoritarian', 'Jihadist threats', 'Oil economy mismanagement', 'Poverty extreme', 'French military dependence'] },
  { name: 'Burkina Faso', lat: 12.2383, lng: -1.5616, summary: 'Military junta coup 2022, jihadist insurgency crisis, Russian Wagner shift, French expelled, humanitarian catastrophe 2M displaced.', issues: ['Jihadist insurgency catastrophe', 'Military junta Traoré', 'Wagner Russian mercenaries', 'Humanitarian crisis 2M displaced', 'French expelled'] },
  { name: 'Rwanda', lat: -1.9403, lng: 29.8739, summary: 'Kagame authoritarian 30 years, economic growth miracle, M23 Congo proxy accusations, political repression opposition, UK asylum deal.', issues: ['Kagame 30 years authoritarian', 'M23 Congo proxy denied', 'Political repression dissidents', 'UK asylum deal', 'Press freedom eliminated'] },
  { name: 'Botswana', lat: -22.3285, lng: 24.6849, summary: 'Democracy stable, diamond economy Debswana, economic diversification challenges, opposition BDP defeat 2024, wildlife conservation, HIV/AIDS legacy.', issues: ['Diamond dependence economy', 'BDP lost power 2024', 'Economic diversification needed', 'HIV/AIDS high rates', 'Water scarcity'] },
]

async function processMegaBatch() {
  console.log(`🚀🚀🚀 MEGA BATCH - Processing ALL remaining 98 countries!\n`)
  let success = 0
  let errors = 0

  for (const country of MEGA_BATCH) {
    try {
      const fullSummary = `# ${country.name}\n\n${country.summary}\n\nKey challenges: ${country.issues.join(', ')}.`

      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: country.name,
            type: 'country',
            category: 'all',
          },
        },
        create: {
          name: country.name,
          type: 'country',
          country: country.name,
          lat: country.lat,
          lng: country.lng,
          category: 'all',
          summary: fullSummary,
          issues: JSON.stringify(country.issues),
          topStories: JSON.stringify([]),
          storyCount: 0,
          updatedAt: new Date(),
        },
        update: {
          summary: fullSummary,
          issues: JSON.stringify(country.issues),
          updatedAt: new Date(),
        },
      })

      console.log(`✅ ${country.name}`)
      success++

      // Progress indicator every 10 countries
      if (success % 10 === 0) {
        console.log(`   📊 Progress: ${success}/98 complete (${30 + success}/128 total)`)
      }
    } catch (error) {
      console.error(`❌ ${country.name}:`, error)
      errors++
    }
  }

  console.log(`\n🎉 MEGA BATCH COMPLETE!`)
  console.log(`   ✅ Success: ${success}/98`)
  console.log(`   ❌ Errors: ${errors}`)
  console.log(`\n📈 TOTAL PROGRESS: ${30 + success}/128 countries (${Math.round((30+success)/128*100)}%)`)
}

processMegaBatch()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
