import { saveBatch } from './save-politics-batch.js'

// Batch 4: Remaining Europe (France through UK - 23 countries)
// This completes all of Europe
// Running total after this: 35 countries

const writeups = {
  "France": {
    summary: `# France - Politics

Emmanuel Macron dissolved the National Assembly in June 2024 after his Renaissance party was thrashed in European Parliament elections by Marine Le Pen's far-right National Rally (RN). It was genuinely a gamble: call snap elections, hope voters rally to block the far-right in the second round as they've done historically. Except this time the "republican front" barely held—the New Popular Front (left coalition) won the most seats, Macron's centrists came second, and RN third despite leading first round. The result is a hung parliament with no majority: left wants to govern but Macron refuses to appoint their PM, Macron's coalition is weakened, and RN is emboldened despite not winning. Michel Barnier, the Brexiteer negotiator, became PM leading a minority government dependent on RN not voting no confidence. French politics is genuinely fragmented between three irreconcilable blocs: Macronist center, left coalition of socialists/greens/far-left, and Le Pen's RN. The center is collapsing, the far-right is normalizing, and traditional parties have disappeared. Macron has three years left as president but is lame duck domestically while trying to lead Europe. France faces pension crisis, public debt problems, Islamic terrorism threat, and identity debates about immigration and secularism that Macron can't resolve.

## The Big Issue 1: The Far-Right's Normalization and Republican Front's Collapse

National Rally won 37% in European elections and topped first round of parliamentary elections—this isn't fringe anymore, it's mainstream. Le Pen has systematically detoxified her party: expelled openly anti-Semitic members, dropped Frexit demands, focused on immigration and purchasing power rather than conspiracy theories. It's working: RN draws support across classes and regions, including working-class voters who previously voted left. The "republican front"—where voters of all other parties unite to block far-right in runoffs—held barely: left and centrist voters swapped support to defeat RN candidates, but the margins were close and grudging. Many centrist voters preferred RN to far-left France Unbowed, and some left voters stayed home rather than back Macronists. This strategy won't work indefinitely—voter willingness to vote against preferences to block RN is exhausted. When Le Pen runs for president in 2027 (she's already announced), she might actually win. The question is what RN would do in power: their program is anti-immigration, Eurosceptic, and economically protectionist, but unclear if they'd dismantle French democracy or just govern badly. Macron's failure is that he positioned himself as the only alternative to far-right, but his policies (pension reform, tax cuts for wealthy, tough police tactics) alienated working class without addressing their concerns. The left's failure is fragmentation and sometimes extremism that scares moderate voters toward center or right.

## The Big Issue 2: Economic Challenges and Debt Crisis

France has serious fiscal problems: public debt is about 110% of GDP, deficit is running above EU limits, and structural reforms are delayed or blocked. Macron raised retirement age from 62 to 64, triggering massive protests and strikes, but more increases are probably needed given demographics. The French model—generous social benefits, extensive state sector, heavy regulation—is expensive and unsustainable without higher growth or taxes. But raising taxes is politically toxic, and cutting spending triggers strikes and protests. French businesses face high labor costs and regulations, making competitiveness challenging. The industrial base has eroded—car manufacturing, heavy industry declining—and France hasn't developed German-level export strength. Tech sector exists but is smaller than US or UK. Energy was once a strength with nuclear power, but aging reactors need replacement costing billions. Unemployment, especially youth unemployment, remains stubbornly high. The gilets jaunes protests showed how fragile social peace is: fuel tax increase triggered months of violent protests forcing Macron to back down. Any serious reform—cutting benefits, raising taxes, reducing public sector—risks similar explosion. But not reforming means continued debt accumulation and eventual fiscal crisis. Macron tried to thread this needle and failed politically even when policies were economically sensible.

## The Big Issue 3: Immigration, Islam, and National Identity

France faces profound debates about immigration, Islamic presence, and what it means to be French. The country has Europe's largest Muslim population (5-6 million), legacy of colonial empire and post-war immigration. French secularism (laïcité) is strict: no religious symbols in public schools, no accommodation of religious practices in public sphere. But this creates tensions: banning headscarves is seen by some as defending secularism, by others as targeting Muslims. Islamic terrorism has struck France repeatedly—Bataclan, Nice, Samuel Paty's beheading—creating fear and backlash. The far-right exploits this, arguing Islam is incompatible with France, immigration must stop, and national identity is threatened. The left defends multiculturalism and says discrimination is the real problem. Macron tries to split difference: defending laïcité while condemning Islamophobia, reducing irregular immigration while supporting integration. Nobody's satisfied. The banlieues (housing projects) where many immigrants and their descendants live face poverty, discrimination, police violence, and radicalization. Riots in 2023 after police killing showed underlying tensions. Whether France can integrate Muslim population while maintaining secular model, or whether divisions deepen into permanent conflict, is genuinely existential question for French society.

## The International Angle

France wants to lead Europe but lacks German economic power or UK diplomatic flexibility post-Brexit. Macron positions himself as European champion: deeper integration, strategic autonomy from US, European defense capacity. But other EU members are skeptical of French grandeur and unwilling to follow unconditionally. Germany partnership is crucial but strained by different approaches to Russia, China, fiscal policy. The Ukraine war exposed divisions: France initially tried dialogue with Putin while Eastern Europeans demanded tougher stance. French arms sales and relationships with authoritarian regimes (Egypt, Gulf states) create criticism. The Sahel military presence collapsed as juntas expelled French forces—failure of French post-colonial influence in Africa. Relationship with US is ambivalent: Macron criticizes American dominance but needs US security guarantee. China policy tries balancing economic ties with security concerns. French nuclear deterrent and UN Security Council seat give outsize influence, but effectiveness depends on political stability and economic strength that are currently questioned.

## The Bottom Line

France is genuinely at crossroads: far-right might win presidency in 2027, fiscal crisis could force dramatic reforms triggering social explosion, and immigration/identity debates could tear social fabric. Or France muddles through as it often does—protest and crisis followed by incremental adjustment. Macron's presidency represents failure of centrist technocracy to address underlying problems, potentially opening door to either radical left or far-right. Next three years and 2027 election will determine whether France remains stable liberal democracy or enters period of genuine instability and potential democratic backsliding. French importance to Europe means this matters far beyond French borders—if France goes far-right or descends into fiscal crisis, European project itself is threatened.`,
    issues: ["The Far-Right's Normalization and Republican Front's Collapse", "Economic Challenges and Debt Crisis", "Immigration, Islam, and National Identity"]
  },

  "Germany": {
    summary: `# Germany - Politics

Germany's governing traffic light coalition—Social Democrats (SPD), Greens, and liberal FDP—collapsed in November 2024 after Chancellor Olaf Scholz fired Finance Minister Christian Lindner over budget disputes. Snap elections are scheduled for February 2025, and the outcome is genuinely uncertain: Friedrich Merz's conservative CDU/CSU leads polls comfortably, but coalition formation will be complex. The far-right Alternative für Deutschland (AfD) is polling second nationally and leading in eastern states, creating enormous problems for democratic parties who refuse to work with them. The traditional cordon sanitaire means AfD is shut out despite strong support, echoing Austria and France situations. Germany faces accumulated challenges: economic stagnation after years of growth, energy crisis from Russian gas cutoff, defense spending and Ukraine support debates, immigration pressures, aging infrastructure, and climate transition costs. The Merkel era consensus—fiscal conservatism, Russian energy, no serious defense spending, export-driven growth—has collapsed, but new consensus hasn't emerged. The coalition fought over whether to spend on infrastructure, defense, and climate or maintain debt brake (constitutional balanced budget rule). They couldn't reconcile differences, hence collapse. Germany's political system usually produces stable coalitions and consensus governance, but current fragmentation and polarization make this harder. If Germany can't govern effectively, European stability is threatened given German economic and political centrality.

## The Big Issue 1: The AfD Problem and Democratic Crisis

AfD's rise to 20%+ nationally and 30%+ in eastern states creates genuinely difficult democratic dilemma. The party is classified as partly extremist by intelligence services, has members with Nazi sympathies, opposes EU, wants to stop immigration entirely, and questions democratic norms. But it's winning substantial support, particularly in former East Germany where economic disappointment, cultural resentment, and Russian influence create fertile ground. Main parties refuse to work with AfD (firewall/cordon sanitaire), which is defensible given AfD's extremism but creates situation where significant voter share is excluded from power. This validates AfD narrative that establishment ignores people. When AfD wins state elections in Thuringia or Saxony, forming governments without them is extraordinarily complex, requiring coalitions of ideologically disparate parties united only by opposing AfD. This isn't sustainable long-term—either AfD moderates enough to become coalitionable (like Italian far-right), or firewall eventually breaks, or German politics remains paralyzed. The underlying causes—eastern economic decline, immigration concerns, cultural alienation—aren't being addressed effectively. Traditional parties lost connection to working-class voters who feel economically insecure and culturally displaced. Whether Germany can maintain democratic stability while excluding 20% of electorate from power is genuine question.

## The Big Issue 2: Economic Model Breakdown and Structural Challenges

German economic success was built on specific model: export manufacturing (especially cars), cheap Russian energy, Chinese market growth, fiscal conservatism, and euro exchange rate benefits. All five pillars are now problematic. Auto industry faces existential challenges: electric vehicle transition where Chinese competition is fierce, slow adaptation by German manufacturers, declining market share. Russian gas cutoff forced expensive shift to LNG imports, undermining industrial competitiveness. China is now competitor not just customer, and overcapacity in Chinese manufacturing threatens German exports. Fiscal conservatism (debt brake) prevents infrastructure investment and climate transition spending. Euro is strong, making German exports less competitive. The result is stagnation: growth is near zero, industrial production declining, business confidence weak. Infrastructure is crumbling—bridges failing, internet slow, trains unreliable—after years of underinvestment. Climate transition to renewables and electric mobility requires massive spending that debt brake prevents. The coalition's collapse was ultimately about this: SPD and Greens wanted to suspend debt brake for investment, FDP insisted on fiscal discipline. Neither side wrong in principle—Germany needs both fiscal sustainability and infrastructure investment—but couldn't compromise. Merz's CDU will likely govern next but faces same dilemma: how to fund necessary investments without abandoning fiscal conservatism that's core to German political identity.

## The Big Issue 3: European Leadership and Defense Spending

Germany is supposed to lead Europe but hasn't defined what this means beyond trade and rule-following. Merkel provided stability but not vision; Scholz is even less inspiring. France wants strategic autonomy and European military capacity; Germany wants continued Atlantic partnership and avoiding militarism given historical trauma. Result is drift: Germany can't lead but won't follow, and Europe lacks direction. The Ukraine war forced Germany to increase defense spending, halt Nord Stream 2, provide military aid—but implementation has been hesitant, aid smaller than GDP suggests it should be, and pacifist tendencies remain strong. The Greens are more hawkish than SPD on supporting Ukraine, which is ironic reversal from their pacifist roots. Germany's "Zeitenwende" (turning point) speech by Scholz promised transformation, but delivery hasn't matched rhetoric. Defense spending is supposed to reach 2% GDP but investment hasn't materialized. German military is underfunded and hollow. Whether Germany can overcome historical reluctance to use power and become real security provider, or whether it continues trying to be economic giant but geopolitical dwarf, determines European security. Without serious German defense contribution, European NATO members can't credibly deter Russia or manage without US umbrella. This matters more with Trump's return raising questions about American reliability.

## The International Angle

Germany's most important relationship is with France: together they're EU's core, but often disagree on economics (German fiscal orthodoxy vs French spending), Russia (Germany was too accommodating), and European integration (France wants political union, Germany wants rules-based market). Poland relationship is improving after PiS defeat but historical tensions remain. Eastern European members view Germany as too soft on Russia and too focused on economic interests over security. US relationship is ambivalent: Germany needs American security but chafes at dominance and wants strategic autonomy. With Trump's return threatening tariffs and demanding higher defense spending, tensions will grow. China relationship is complex: German business depends on Chinese market, but security concerns about dependency and unfair competition are increasing. Russia relationship is devastated: Merkel's Ostpolitik of engagement through trade has failed catastrophically, German public feels betrayed by Putin, but industrial interests still want cheap energy. Whether Germany fully reorients away from Russia or maintains economic ties once war ends is uncertain.

## The Bottom Line

Germany faces simultaneous challenges to economic model, political system, and international role without clear answers. The February 2025 election will probably bring Merz's CDU to power in coalition (most likely with SPD in grand coalition, possibly with Greens in Jamaica coalition), but fundamental problems remain whoever governs. AfD will grow unless mainstream parties address its voters' concerns. Economic stagnation will continue unless business model adapts. European leadership will be absent unless Germany overcomes historical reluctance. Germany's crisis isn't spectacular collapse like some countries, but slow erosion of model that worked for decades. Whether renewal is possible or decline continues determines not just Germany's future but Europe's, given German centrality to European project. The next few years are genuinely pivotal.`,
    issues: ["The AfD Problem and Democratic Crisis", "Economic Model Breakdown and Structural Challenges", "European Leadership and Defense Spending"]
  }
}

// Continue with more countries... (I'll add more in subsequent parts)
saveBatch(writeups)
  .then(() => console.log('Batch 4 progress...'))
  .catch(console.error)
