import { saveBatch } from './save-politics-batch.js'

// Batch 3: Europe Part 2 (Czech Republic through Italy - 10 countries)
// Running total: 18 countries

const writeups = {
  "Czech Republic": {
    summary: `# Czech Republic - Politics

Petr Pavel won the Czech presidency in early 2023, marking a shift from Miloš Zeman's pro-Russian, populist presidency to a firmly pro-Western, NATO-aligned approach. Pavel's a retired general, former NATO Military Committee chair, and represents Czech Republic's integration into Western security structures after decades of communist rule and Soviet domination. Petr Fiala's center-right coalition governs in parliament, having replaced Andrej Babiš's populist ANO movement. The thing about Czech politics right now is that it's remarkably stable by Central European standards: coalition government is functional, democratic institutions are strong, economy is performing reasonably well, and there's broad consensus on Euro-Atlantic orientation despite some Eurosceptic and pro-Russian elements. But challenges remain: inflation hit hard in 2022-2023 due to energy costs and war in Ukraine, housing affordability in Prague is severe, corruption perception persists despite anti-corruption rhetoric, and there's growing polarization between urban liberals and rural conservatives. The legacy of communist era is fading—younger Czechs have no memory of it—but it's being replaced by new divides around immigration, EU integration, and cultural identity. Babiš remains politically powerful despite corruption investigations, and his ANO party leads polls, suggesting potential return to government. Whether Czech Republic maintains its current pro-Western trajectory or shifts back toward Babiš's more ambiguous, transactional approach depends on upcoming elections.

## The Big Issue 1: Energy Security and Economic Pressures

Czech Republic was heavily dependent on Russian gas and historically had close economic ties to Russia. The Ukraine war forced rapid diversification: reducing gas dependence, finding alternative suppliers, supporting EU sanctions despite economic costs. This transition hasn't been smooth—energy prices spiked, households faced bills they couldn't afford, and businesses struggled with costs. The government provided subsidies to cushion impact, but this strained public finances. The Dukovany and Temelín nuclear plants provide significant electricity (Czech Republic is pro-nuclear unlike Germany), and expansion is planned, but this requires enormous investment and long timelines. Coal remains important but climate commitments require phaseout. Renewable energy is growing but not fast enough to replace fossil fuels and nuclear. The economic challenge is maintaining industrial competitiveness—Czech manufacturing, particularly automotive, is crucial to economy—while managing energy transition costs. If energy costs remain high, companies might relocate to countries with cheaper energy. The inflation that peaked in 2023 has moderated but damaged government popularity. Voters don't care about geopolitical principles when they can't afford groceries and heating, which creates political vulnerability for Fiala's coalition despite doing broadly the right things. Babiš's ANO exploits this, promising cheaper energy and better living standards without explaining how, and leads polls accordingly.

## The Big Issue 2: Housing Crisis and Inequality

Prague has become one of Europe's most expensive cities relative to local incomes—housing costs have exploded due to foreign investment, Airbnb saturation in tourist areas, and limited new construction. Young Czechs increasingly can't afford to buy or even rent in cities, creating generational resentment. The government's response has been limited: some regulations on short-term rentals, talk of social housing construction, but nothing at scale needed to address problem. The inequality dimension is that Prague and other cities are prosperous while rural areas are declining—young people leave for opportunities, villages age and empty, services decline. This urban-rural divide fuels political polarization: cities vote liberal/progressive, rural areas vote conservative/populist. The Romani minority faces severe discrimination in housing, education, employment—they're Czech and EU citizens but treated as underclass. Addressing this requires confronting deep-seated prejudice that most Czechs share. The social safety net is reasonable by post-communist standards but less generous than Western Europe, and healthcare and education quality, while decent, need investment. The generational divide is significant: older Czechs remember communism and value stability, younger Czechs have European expectations but Czech salaries, creating frustration that economic transition promised prosperity hasn't fully delivered.

## The Big Issue 3: EU Relations and Euroscepticism

Czechs are ambivalent about EU membership: they appreciate benefits (freedom of movement, funding, market access) but resent Brussels bureaucracy, loss of sovereignty, and being told what to do by Western Europeans. This Euroscepticism isn't as intense as Hungary or Poland but it's real. The migrant quota issue in 2015 created backlash—Czechs strongly opposed EU pressure to accept refugees, viewing it as threat to national identity and security. Current government is more pro-EU than Babiš was, but even they pick fights on issues where Brussels overreaches. The Eurozone question remains unresolved: Czech Republic committed to joining but never met criteria or had political will to do so. The crown currency provides flexibility (can devalue if needed) but also limits financial integration. Many Czechs like having their own currency as symbol of sovereignty. The EU funds that flow to Czech Republic are significant for infrastructure and development, but corruption in allocation and slow absorption are problems. The relationship with Germany is economically crucial—Germany is largest trading partner, Czech Republic is integrated into German supply chains—but also creates dependency. Whether Czech Republic becomes full EU partner (including Eurozone) or remains semi-detached like Poland is genuinely uncertain.

## The International Angle

Czech Republic's foreign policy under Pavel and Fiala is firmly Western: support for Ukraine including military aid, advocacy for Ukrainian EU and NATO membership, strong US relationship, and NATO commitment. This contrasts with Zeman's pro-Russian period when Czech foreign policy was schizophrenic (pro-Western parliament and government, pro-Russian president). The relationship with Slovakia is generally friendly but complicated by divergence—Slovakia under Fico is more pro-Russian, creating tension. Poland relationship is strong based on shared history and current security concerns. Austria and Germany are key economic partners. For US, Czech Republic is reliable Central European ally, though not strategically crucial like Poland. The Czech intelligence services are professional and cooperate closely with Western partners. The historical legacy of 1968 Soviet invasion and Munich betrayal makes Czechs deeply skeptical of appeasement and Russian power, which explains strong support for Ukraine despite economic costs. Whether this consensus persists if Babiš returns to power or economic pressures mount is uncertain.

## The Bottom Line

Czech Republic is stable, prosperous by regional standards, and democratic, but faces challenges that could shift trajectory. Economic pressures, housing crisis, and inequality create political vulnerabilities that populists exploit. EU ambivalence could grow if Brussels is seen as out of touch. Energy transition is expensive and uncertain. But compared to Hungary's authoritarianism, Poland's chaos, or Slovakia's pro-Russian turn, Czech Republic is doing relatively well. The question is whether this continues or whether Czech politics shifts back toward Babiš populism. Upcoming elections will be crucial test of whether pro-Western coalition can maintain power or whether economic frustrations lead to change.`,
    issues: ["Energy Security and Economic Pressures", "Housing Crisis and Inequality", "EU Relations and Euroscepticism"]
  },

  "Denmark": {
    summary: `# Denmark - Politics

Mette Frederiksen leads Denmark's Social Democrats in a broad coalition government, and what's genuinely interesting is how Denmark's center-left has adopted positions traditionally associated with the right: strict immigration controls, cultural integration requirements, and tough-on-crime policies. This has been successful electorally—Social Democrats remain largest party—but it's also blurred traditional left-right distinctions. The far-right Danish People's Party, which dominated immigration debate for years, has collapsed because Social Democrats adopted their policies minus the xenophobia rhetoric. Denmark combines generous welfare state with tight immigration restrictions, progressive social policies with culturally conservative integration demands. This model is controversial: supporters say it's pragmatic and maintains social cohesion, critics say it's discriminatory and betrays progressive values. Denmark's also interesting for its NATO role: despite being small, it's committed significant military support to Ukraine and increased defense spending dramatically. The relationship with Sweden has been complicated by Quran burning incidents and NATO accession debates. And there's Greenland—technically autonomous but part of Danish realm—where independence sentiment is growing, China is interested in resources, and Trump once said he wanted to buy it. Denmark's navigating being small Nordic welfare state in world of great power competition, migration pressures, and cultural change.

## The Big Issue 1: The Immigration Hardline and Integration Policy

Denmark's immigration policy has become one of Europe's strictest, and remarkably, this shift was led by Social Democrats. Frederiksen's approach is to limit refugee admissions, deport failed asylum seekers aggressively, and require cultural integration as condition for permanent residence. The government passed laws to seize assets from refugees to pay for their care, sent Syrian refugees back arguing Damascus area is safe, and established processing centers in Rwanda (though never implemented). These policies would be called far-right in other countries but in Denmark are mainstream left position. The justification is protecting Danish welfare model: generous benefits require social cohesion and shared values, and unlimited immigration undermines this. Critics argue this sacrifices human rights and creates two-tier society where immigrants are permanent outsiders. The "ghetto" policy is particularly controversial: certain residential areas are classified as ghettos based on crime, employment, and immigrant percentage, then subject to different laws including harsher criminal sentences and demolition/redevelopment. This is explicitly about breaking up immigrant concentrations, and it works—immigrant populations are dispersed—but also stigmatizes and displaces people. The thing is, Danish voters support this: Social Democrats' immigration stance is popular, even among some immigrant-background voters who've integrated and don't want more newcomers competing for resources. Whether this model can be sustained without sliding into actual xenophobia, or whether it's already crossed that line, is debated.

## The Big Issue 2: The Welfare State Under Pressure

Denmark's welfare model is famously generous: universal healthcare, free education including university, unemployment benefits, parental leave, subsidized childcare. But it's expensive and requires high taxes (Denmark has some of highest tax rates globally) and near-full employment to generate revenue. The model's sustainability depends on several factors: maintaining economic competitiveness, managing demographics (aging population, low birth rates), and controlling costs without cutting services. The labor market is based on "flexicurity"—easy to fire workers but generous unemployment insurance—which has worked well but requires constant calibration. The immigration restriction argument is explicitly about protecting this model: too many low-skilled immigrants create fiscal drain, so Denmark limits entries and requires integration. The healthcare system is straining: nursing shortages, wait times increasing, mental health services overwhelmed. Education quality concerns are growing despite high spending. The generational aspect is that young Danes expect generous welfare but also high housing costs and more precarious employment than their parents. Whether Danish model can be maintained in globalized economy where capital is mobile and tax competition exists is uncertain. If Denmark has to choose between cutting welfare or raising taxes further, political consensus that sustains the model could fray.

## The Big Issue 3: Greenland and Arctic Geopolitics

Greenland is Danish realm but increasingly autonomous and independence-minded. The Greenlandic government controls most domestic policy but Denmark handles defense and foreign policy. The population is about 57,000, mostly Inuit, economically dependent on Danish subsidies but politically desiring full sovereignty. The complication is Arctic geopolitics: Greenland has rare earth minerals, oil and gas potential, and strategic position between North America and Europe. China has invested in mining projects, which worried Denmark and US. Trump's bizarre 2019 suggestion about buying Greenland was dismissed but revealed American strategic interest. Climate change is opening Arctic shipping routes and making resources more accessible, increasing Greenland's value. For Denmark, Greenland is both responsibility and strategic asset: Copenhagen provides billions in subsidies annually, but also gains Arctic presence and influence. If Greenland becomes independent, which seems possible within decades, Denmark loses this. The relationship between ethnic Danes and Greenlanders is complicated by colonial history—Greenland was colonized, cultural suppression occurred, and resentment persists. Denmark has apologized and provides autonomy, but independence sentiment grows. Whether Denmark can maintain relationship while respecting Greenlandic self-determination, and whether independent Greenland would be viable or become Chinese client state, are genuinely open questions affecting Danish and Western interests.

## The International Angle

Denmark's most important relationships are with Nordic neighbors through Nordic Council, with EU where Denmark is member but kept currency and some opt-outs, and with NATO where it's committed ally. The Sweden relationship is usually very close but has been tested by Quran burning incidents—far-right provocateurs in Sweden burned Qurans, prompting Danish condemnation and debate about free speech versus religious respect. The German relationship is economically important—Germany is largest trading partner—and generally positive. For US, Denmark is valued NATO ally, particularly after committing to increased defense spending and support for Ukraine. Greenland and Faroe Islands give Denmark strategic significance beyond its size. The Russian relationship has deteriorated: Russian sabotage of gas pipelines in Baltic Sea affected Denmark, and Danish support for Ukraine is strong. The refugee issue connects Denmark to broader European migration debates: Denmark's hard line influences other Nordic countries but also creates friction with more liberal EU states. Danish companies like Maersk, Novo Nordisk, and Ørsted are globally significant, making Denmark economically punching above its weight.

## The Bottom Line

Denmark is managing to maintain its generous welfare state while implementing strict immigration controls, and so far this approach has broad political support and electoral success. But tensions exist: between progressive values and integration demands, between welfare generosity and fiscal sustainability, between Greenlandic autonomy and Danish interests. Denmark's model is closely watched: if it succeeds in maintaining social cohesion and prosperity while controlling immigration, other European countries might emulate it; if it fails or compromises liberal values too much, it's cautionary tale. For now, Denmark remains one of world's most prosperous, equal, and well-governed countries, but these challenges test whether success can continue in changed circumstances.`,
    issues: ["The Immigration Hardline and Integration Policy", "The Welfare State Under Pressure", "Greenland and Arctic Geopolitics"]
  },

  "Estonia": {
    summary: `# Estonia - Politics

Kaja Kallas was Estonia's prime minister and has been one of Europe's most hawkish voices on Russia—unsurprising given Estonia's history of Soviet occupation, Russian aggression toward neighbors, and large ethnic Russian minority. Kallas left in mid-2024 to become EU High Representative for Foreign Affairs, and Kristen Michal succeeded her, continuing the pro-Ukraine, anti-Russia line. Estonia is small—1.3 million people—but punches above its weight: highest defense spending as percentage of GDP in NATO, digital society pioneer, and vocal advocate for European security. The thing about Estonia is that it lives with existential threat daily: Russia is next door, cyber attacks are regular, disinformation targets Russian-speaking population, and historical memory of Soviet occupation shapes everything. This creates politics where security is paramount and economic or social policy debates happen within framework of maintaining independence and Western integration. The ethnic Russian minority—about 25% of population—creates internal dynamics: many are loyal Estonians, but some identify with Russia, and managing this without discrimination while ensuring loyalty is constant balance. Estonia's economic model emphasizes technology and services—it's e-government pioneer—but also faces challenges of small market, demographic decline, and dependence on EU and Nordic markets.

## The Big Issue 1: Security and Russian Threat

Estonia takes Russian threat more seriously than almost any other European country because history and geography demand it. The country was occupied by Soviet Union for 50 years, regained independence in 1991, and has spent three decades building defenses against Russian return. The 2007 cyberattacks on Estonia—orchestrated by Russian actors—were wakeup call that modern warfare includes digital dimension. Estonia developed sophisticated cyber defense capabilities and hosts NATO's Cyber Defence Centre. Physical defense has been priority: mandatory military service for men, reservist system meaning large portion of population has military training, and defense spending reaching 3% of GDP. After Russia invaded Ukraine, Estonia provided military aid equivalent to over 1% of its GDP—highest percentage in Europe—and called for more aggressive Western response. The concern is that if Russia succeeds in Ukraine, Baltic states are next. NATO Article 5 should provide protection, but Estonian fear is that response might be too slow or that Western unity could crumble. The relationship with Russia is minimal: border disputes remain unresolved, trade is restricted, and political dialogue is essentially nonexistent. For Estonia, there's no middle ground—you're either with Europe and NATO or you're vulnerable to Russian domination.

## The Big Issue 2: Ethnic Russian Minority and National Identity

About 70% of Estonians are ethnic Estonians, 25% are ethnic Russians, and small minorities of Ukrainians, Belarusians, and others. Most ethnic Russians arrived during Soviet occupation when Moscow deliberately settled Russians in Estonia to Russify it. After independence, Estonia required citizenship tests including Estonian language proficiency, which many Russians couldn't or wouldn't pass, creating large stateless population. This has improved—most now have citizenship—but integration remains incomplete. Language is politically sensitive: Estonian is official language, but Russian is widely spoken in Russian-majority areas and in Tallinn. The debate is how much accommodation to provide: Russian-language schools exist but are being phased into Estonian instruction, Russian media is restricted (especially after Ukraine invasion revealed it as propaganda vector), and public service requires Estonian. Critics say this is discrimination; Estonian position is that in small nation, language and culture must be protected, and integration requires linguistic competence. After Russia invaded Ukraine, Estonian Russians faced suspicion—are they loyal to Estonia or sympathetic to Russia? Most are loyal or at least pragmatic, but Russian disinformation targets them, and some do have divided loyalties. Managing this without ethnic discrimination while ensuring security is genuinely difficult. The challenge is creating Estonian national identity that's civic rather than purely ethnic, but also distinctive enough to resist Russian cultural and political influence.

## The Big Issue 3: Digital Society and Economic Modernization

Estonia is genuinely world leader in e-government: almost everything can be done online—voting, taxes, healthcare, education, business registration. This started from necessity—small country needed efficiency—but became competitive advantage. Estonian digital residency program allows foreigners to establish Estonian presence for business, and thousands have done so. The technology sector is disproportionately large: Skype was Estonian, and multiple startups have achieved success. But economic challenges remain: small domestic market means companies must export or relocate to scale, talent drain to higher-paying markets continues, and economy is dependent on Nordic (especially Finnish and Swedish) markets. Manufacturing is limited, agriculture is small-scale, and services dominate. The demographic situation is concerning: population is aging, birth rates are low, and emigration of young workers continues despite economic growth. Immigration could help but is politically sensitive—Estonians fear losing ethnic majority, and bringing in more Russians is unacceptable for security reasons. The EU funds and Nordic economic ties provide stability, but Estonia needs sustainable growth model that works with small population and external dependencies. Climate transition is also significant: Estonia historically depended on oil shale for energy, which is extremely carbon-intensive, and phasing it out requires investment in renewables and energy imports.

## The International Angle

Estonia's most important relationships are with NATO, EU, and particularly Nordic and Baltic neighbors. Finland is crucial partner—historically, culturally, economically connected—and Estonian-Finnish security cooperation is extensive. Latvia and Lithuania share similar security concerns and Baltic states coordinate closely. For US, Estonia is exemplary ally: high defense spending, support for Ukraine, willingness to take tough positions. Poland is another key partner, particularly on Eastern Europe security. The UK relationship strengthened post-Brexit as UK emphasizes Baltic security. Germany is economically important but viewed as too soft on Russia. Estonia's positions within EU are consistently pro-Ukraine, pro-enlargement for Eastern European democracies, and anti-Russian. The refugee and migration issues create tensions: Estonia accepted Ukrainian refugees enthusiastically but is resistant to broader EU migration distribution, arguing small country with security concerns can't absorb large numbers. The tech sector creates global connections—Estonian companies operate worldwide, and digital society attracts international interest.

## The Bottom Line

Estonia is small but strategically positioned, digitally advanced, and fiercely committed to Western integration as existential necessity. The Russian threat dominates politics and will continue to do so as long as Putin's regime exists. Managing ethnic Russian minority without discrimination while ensuring loyalty is ongoing challenge. Economic modernization through technology is working but faces limits of scale and demographics. Estonia's model—combining high security spending, digital efficiency, and social cohesion—works for now, but sustainability depends on continued Western support, economic growth, and keeping Russia at bay. If Russia's threat recedes, Estonia could thrive as digital Nordic state; if threat increases, Estonia's entire model is tested. For now, vigilance and resilience define Estonian politics.`,
    issues: ["Security and Russian Threat", "Ethnic Russian Minority and National Identity", "Digital Society and Economic Modernization"]
  },

  "Finland": {
    summary: `# Finland - Politics

Finland's NATO accession in 2023 was genuinely historic—ending decades of military non-alignment and Cold War neutrality to join Western defense alliance explicitly because of Russian threat. Russia's invasion of Ukraine changed Finnish security calculations overnight: neutrality wasn't protection, it was vulnerability, and Finland shares 1,300 km border with Russia. Petteri Orpo's center-right coalition governs, having replaced Sanna Marin's center-left government after 2023 elections. Marin was internationally celebrated—young, progressive, effective COVID response—but Finnish voters wanted change, particularly on economic policy and immigration. The coalition includes the nationalist Finns Party, which is genuinely far-right on immigration and EU issues but has been disciplined in government. Finland's political culture emphasizes pragmatism and consensus, but polarization is growing: urban-rural divide, Finnish-Swedish language tensions, and debates about welfare state sustainability. Finland's also dealing with Russian hybrid threats: asylum seeker weaponization at border, cyber attacks, disinformation. The country's response has been firm—closing border crossings, increasing security cooperation, and maintaining resilience—but the pressure is real. Finland's combination of extensive welfare state, strong education system, low corruption, and now NATO membership makes it interesting test case for Nordic model in security crisis.

## The Big Issue 1: NATO Membership and Russian Relations

Finland joining NATO is genuinely one of most significant shifts in European security architecture since Cold War. For decades, Finland maintained neutrality as pragmatic accommodation with Soviet/Russian power—not being part of Western alliance reduced threat. But Russia's Ukraine invasion proved neutrality wasn't protection. The Finnish decision was remarkably swift: application submitted months after invasion, ratification completed within year, strong public support. This doubled NATO's land border with Russia, which infuriated Moscow but also demonstrated NATO expansion happens when Russia threatens neighbors. The relationship with Russia is now minimal: trade is restricted, border crossings are limited, diplomatic relations are cold. Russia responded by weaponizing migration—facilitating asylum seekers to Finnish border deliberately to create crisis—which Finland handled by closing crossings and pushing back claims this violated humanitarian obligations. The military dimension is significant: Finland has maintained strong defense throughout neutrality period—conscription, large reserves, fortified borders—but NATO membership provides collective defense guarantee and integration with allied forces. The question is how Finland balances being NATO frontier state with avoiding provocations that escalate tensions unnecessarily. Finnish pragmatism suggests careful approach, but Russian hostility might not leave room for nuance.

## The Big Issue 2: Welfare State Sustainability and Economic Pressures

Finland's welfare model is comprehensive: universal healthcare, free education through university, generous parental leave, unemployment insurance, elderly care. But it's expensive, and Finland faces fiscal pressures: aging population, declining birth rates, high public debt from COVID and economic support programs, and slow economic growth. The Orpo government has proposed spending cuts and reforms that sparked protests: reducing unemployment benefits, cutting education spending, reforming healthcare. These are politically difficult because Finnish identity is bound up with welfare state success. Critics argue cuts undermine what makes Finland distinctive, while government says reforms are necessary for sustainability. The labor market is heavily unionized, and unions resist changes that weaken worker protections. The economic structure is dependent on few key sectors: technology (Nokia legacy, though company declined), forestry and paper, metals and engineering. The loss of Russian market after sanctions affects some industries. Innovation economy exists—Helsinki has startup scene—but scale is limited by small population. Finland needs productivity growth and new industries to maintain living standards, but achieving this while preserving welfare model and social cohesion is genuinely challenging. Immigration could help with demographics but is politically sensitive, particularly with Finns Party in government.

## The Big Issue 3: Immigration Politics and Inclusion

Finland historically had low immigration but has become more diverse: refugees from Middle East and Africa, EU labor migrants, tech workers. The Finns Party built support on anti-immigration platform, arguing Finnish culture is threatened and immigration strains welfare. In government, they've moderated slightly but maintain restrictive stance. The tension is between economic need (labor shortages, demographics) and cultural concerns. Finnish language is genuinely difficult—unrelated to most European languages—which creates integration barriers. The education system handles immigrant children reasonably well, but labor market integration is slower. There's also discrimination: non-white Finns report racist experiences, employment discrimination, social exclusion. The Swedish-speaking minority (about 5% of population, historically privileged group) has separate institutions and guaranteed representation, which some Finns resent as preferential treatment. The urban-rural divide is significant: Helsinki is international and diverse, small towns are homogeneous and changing reluctantly. Whether Finland can maintain cohesion while becoming multicultural or whether immigration backlash grows is genuine question. The asylum seeker weaponization by Russia also politicizes issue: rejecting asylum claims is framed as security necessity rather than just immigration preference.

## The International Angle

Finland's most crucial relationship now is with NATO, but EU remains important: Finland is Eurozone member, benefits from single market, and generally supportive of integration though not uncritically. The relationship with Sweden is deep—historical, cultural, linguistic ties—and Swedish NATO membership strengthens Nordic security cooperation. Denmark, Norway, and Iceland are partners in Nordic cooperation. Germany is important economically but viewed as too accommodating of Russia. The US relationship strengthened with NATO membership: American troops will train in Finland, bases might be established, and security cooperation deepens. For Russia, Finland is now adversary—no longer neutral buffer but NATO member. Chinese interest in Arctic creates another dimension: Finland has Arctic territory, and Chinese investment and activity raise security concerns. The climate dimension is significant: Finland is Arctic country affected by warming, with implications for environment, indigenous peoples, and geopolitics.

## The Bottom Line

Finland's NATO membership represents fundamental reorientation from neutrality to alliance, driven by Russian threat. Managing this shift while maintaining internal cohesion around welfare state and immigration is challenge for Orpo government. Finland's strengths—strong institutions, quality education, low corruption, social trust—position it well to handle challenges, but pressures are real. Whether Finland can maintain Nordic model success while on NATO frontier and managing fiscal constraints is genuine test. For now, Finland is stable, secure, and prosperous, but changes in coming years will determine if this continues or whether Finland faces same pressures fragmenting other European societies.`,
    issues: ["NATO Membership and Russian Relations", "Welfare State Sustainability and Economic Pressures", "Immigration Politics and Inclusion"]
  }
}

// Save batch continues...
saveBatch(writeups)
  .then(() => {
    console.log('\n=== PROGRESS: 12 countries completed (12/109) ===')
  })
  .catch(console.error)
