import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

// Countries 41-100 (East Timor through Myanmar)
const countries = [
  {name:'East Timor',lat:-8.8742,lng:125.7275,s:`East Timor has virtually no scientific infrastructure, destroyed by civil war and 1999 independence violence. R&D spending is zero, University of Timor Lorosa'e focuses on basic education not research. International organizations conduct all research—public health, agriculture, fisheries—with minimal Timorese participation. Oil wealth involves zero domestic R&D. Brain drain is total—educated Timorese remain abroad. The country will remain entirely dependent on foreign expertise indefinitely.`,i:["Zero R&D spending and infrastructure","1999 violence destroyed minimal capacity","Oil industry zero Timorese R&D","Total brain drain abroad","Complete foreign dependence"]},
  {name:'Ecuador',lat:-1.8312,lng:-78.1834,s:`Ecuador's science leverages biodiversity but capacity remains modest (R&D ~0.4% GDP). Galápagos remains greatest asset though foreign-dominated. Universities in Quito/Guayaquil research volcanology, tropical ecology, agriculture. Oil industry minimal domestic R&D. Brain drain substantial—students abroad don't return. Political instability disrupts funding. Challenge: converting natural laboratory advantages into indigenous leadership rather than foreign research site.`,i:["R&D only 0.4% of GDP","Galápagos research foreign-dominated","Substantial brain drain","Political instability disrupting funding","Oil industry minimal R&D"]},
  {name:'Egypt',lat:26.8206,lng:30.8025,s:`Egypt operates Arab world's largest scientific establishment (R&D ~0.7% GDP, 100M population). Research in solar energy, Nile hydrology, archaeology, biomedical fields. However: catastrophic brain drain to Gulf/West, political repression under Sisi constraining freedom, economic crisis making equipment unaffordable. Zewail City struggling with funding. Despite infrastructure and human capital, output below potential due to governance and authoritarianism.`,i:["R&D 0.7% inadequate for 100M population","Catastrophic brain drain","Political repression constraining freedom","Economic crisis, unaffordable equipment","Zewail City struggling"]}
];

// Add remaining 57 countries in similar compact format...
const allCountries = [
  ...countries,
  {name:'El Salvador',lat:13.7942,lng:-88.8965,s:`El Salvador's scientific capacity minimal (R&D <0.2% GDP), devastated by civil war never recovered. Research on seismic hazards, coffee disease, gang violence health impacts. Brain drain severe—migration to US. Economy (remittances, textiles) involves zero R&D. Climate vulnerability requires research capacity that doesn't exist.`,i:["R&D below 0.2%","Civil war destroyed infrastructure","Severe brain drain to US","Economy zero R&D","Climate research absent"]},
  {name:'Equatorial Guinea',lat:1.6508,lng:10.2679,s:`Despite oil wealth, Equatorial Guinea has zero R&D—resource curse extreme. Oil industry entirely foreign with no transfer. Authoritarian Obiang regime diverts wealth. Virtually no scientists exist. Extreme example of wealth failing to build human capital.`,i:["Zero R&D despite oil wealth","No technology transfer","Authoritarian diversion","No scientists","Resource curse extreme"]},
  {name:'Eritrea',lat:15.1794,lng:39.7823,s:`Eritrea's scientific capacity nonexistent under extreme repression. R&D negligible, universities function as conscription sites. Mass exodus—educated flee indefinite service. Complete international isolation. Academic freedom absent. Would require political transformation.`,i:["Zero R&D, extreme repression","Mass exodus","Universities as conscription","Complete isolation","No academic freedom"]},
  {name:'Estonia',lat:58.5953,lng:25.0136,s:`Estonia emerged as Baltic digital leader (R&D ~1.4% GDP). Strong in cybersecurity, e-governance, genomics. University of Tartu leads. NATO Cyber Centre hub. Produced Skype. However: tiny population (1.3M) limiting scale, talent competition with Finland/Sweden. Success positioning as digital testbed.`,i:["Tiny population (1.3M)","Competition for talent","Small domestic market","R&D 1.4% needs increases","Cybersecurity target"]},
  {name:'Ethiopia',lat:9.1450,lng:40.4897,s:`Ethiopia's capacity expanding from low base (R&D ~0.6% GDP, 120M people). Research in agriculture, highland ecology, public health. Launched first satellite. Grand Renaissance Dam shows ambition. However: severe brain drain, limited infrastructure, political instability (Tigray war devastated universities), inadequate funding for population.`,i:["R&D 0.6% inadequate for 120M","Severe brain drain","Tigray war disrupted universities","Limited infrastructure","Political instability"]},
  {name:'Fiji',lat:-17.7134,lng:178.0650,s:`Fiji operates South Pacific's research hub via University of South Pacific (R&D ~0.15%). Research on marine science, climate change, cyclones—existential for islands. Regional role compensates for small size. Brain drain to Australia/NZ, political instability, basic facilities requiring external analysis.`,i:["Low R&D 0.15%","Brain drain to Australia/NZ","Political instability","Basic facilities","Climate vulnerability"]},
  {name:'Finland',lat:61.9241,lng:25.7482,s:`Finland ranks among world's most research-intensive (R&D ~2.9% GDP). Excellence in IT, forestry, Arctic, clean tech. World-class education feeds research. However: R&D declining from 3.5%+ Nokia-era peaks, remote location, aging population, small domestic market. Model of high investment and strong education maintaining research powerhouse status.`,i:["R&D declining from 3.5%+","Remote location","Aging population threatening workforce","Small domestic market","Post-Nokia transition"]},
  {name:'France',lat:46.2276,lng:2.2137,s:`France operates Europe's second-largest system (R&D ~2.2%, 69 Nobel laureates). Excellence in mathematics (most Fields Medals after US), nuclear, aerospace, pharma. CNRS is Europe's largest research org. Challenges: bureaucratic rigidity, low academic salaries, brain drain to US/UK/Switzerland, below historical R&D levels. Must modernize while preserving fundamental research strength.`,i:["Bureaucratic rigidity","Low salaries, brain drain","R&D 2.2% below historical","Employment structure inflexibility","Competition with nimbler systems"]},
  {name:'Gabon',lat:-0.8037,lng:11.6094,s:`Gabon's capacity limited but oil wealth enables higher investment than regional peers (R&D ~0.5%). Focus on rainforest ecology, biodiversity, conservation. Protected 13% territory as parks attracting international research. Challenges: oil dependence, limited expertise requiring foreign partners, brain drain to France, small population (2.3M).`,i:["Oil dependence volatility","Limited domestic expertise","Brain drain to France","Small population 2.3M","R&D 0.5% modest"]},
  {name:'Gambia',lat:13.4432,lng:-15.3101,s:`Gambia's capacity minimal (R&D <0.1%). MRC Unit is British-operated facility for tropical disease research, not Gambian capacity. Severe brain drain—educated don't return. Economy (tourism, remittances) zero R&D. Too small (2.5M) for significant capacity. Will remain research site, not producer.`,i:["R&D below 0.1%","MRC is foreign operation","Severe brain drain","Economy zero R&D","Too small for capacity"]},
  {name:'Georgia',lat:42.3154,lng:43.3569,s:`Georgia preserves Soviet science fragments (R&D ~0.3%). Strengths in mathematics, viticulture, archaeology (Dmanisi fossils). Catastrophic brain drain—population declined 5.5M to 3.7M. Russian occupation disrupted research. 2008 war damaged collaboration. Political interference constrains universities. Recovery requires stability and funding unlikely soon.`,i:["Population declined 5.5M to 3.7M","R&D only 0.3%","Russian occupation","2008 war damaged capacity","Political interference"]},
  {name:'Germany',lat:51.1657,lng:10.4515,s:`Germany operates Europe's largest system (R&D ~3.1%, €110B annually, 111 Nobel laureates). Max Planck (basic), Fraunhofer (applied), Helmholtz, Leibniz institutes create specialized excellence. Leadership in automotive, chemistry, manufacturing, renewable energy. Challenges: bureaucracy, brain drain concerns, Mittelbau postdoc uncertainty, maintaining competitiveness vs US/China.`,i:["Bureaucracy slowing innovation","Brain drain concerns","Mittelbau career uncertainty","Basic vs applied balance debates","Competing with higher US/China spending"]},
  {name:'Ghana',lat:7.9465,lng:-1.0232,s:`Ghana operates West Africa's stronger systems (R&D ~0.4%). Research in cocoa, tropical medicine, agriculture. Political stability relative to neighbors creates regional hub potential. Noguchi Institute significant. However: funding insufficient, brain drain to Nigeria/SA/UK, limited labs, economy (cocoa, gold, oil) minimal private R&D.`,i:["R&D 0.4% insufficient","Brain drain","Limited lab facilities","Economy minimal R&D","Oil not translating to research"]},
  {name:'Greece',lat:39.0742,lng:21.8243,s:`Greece maintains capacity despite crisis devastation (R&D ~1.2%). Strengths in mathematics, physics, marine biology, archaeology. 2010-2018 economic crisis gutted budgets—500,000 emigrated including scientists. Universities recover slowly. Brain drain to Germany/UK/US ongoing. EU membership provides funding partially offsetting domestic shortfalls.`,i:["Crisis slashed R&D to 1.2%","500,000 emigrated during crisis","Budgets gutted","Brain drain ongoing","Recovery insufficient"]},
  {name:'Guatemala',lat:15.7835,lng:-90.2308,s:`Guatemala's capacity minimal (R&D <0.1%) despite being Central America's most populous. Research on volcanoes, agriculture, disease. Mayan archaeology foreign-led. Catastrophic brain drain via US migration. Violence, poverty, governance hostile to research. Civil war devastation never recovered.`,i:["R&D below 0.1%","Catastrophic migration to US","Mayan research foreign-led","Violence/poverty hostile","Civil war legacy"]},
  {name:'Guinea',lat:9.9456,lng:-9.6966,s:`Guinea's infrastructure rudimentary (R&D <0.2%). Mining (world's largest bauxite) entirely foreign with zero R&D. Ebola epicenter but only research site. Severe brain drain to France. Recent coups isolating diplomatically. Would require political transformation.`,i:["R&D below 0.2%","Mining zero Guinea R&D","Ebola only research site","Severe brain drain","Recent coups isolating"]},
  {name:'Guinea-Bissau',lat:11.8037,lng:-15.1804,s:`Guinea-Bissau possesses virtually no infrastructure—among world's poorest. R&D effectively zero. No research universities. Narco-state with cocaine trafficking corrupting governance. Continuous military coups. Total absence of citizens in research careers. Complete scientific void.`,i:["Zero R&D, no institutions","Narco-state corruption","Continuous coups","No universities conducting research","Complete absence citizens in research"]},
  {name:'Guyana',lat:4.8604,lng:-58.9302,s:`Guyana's capacity minimal (R&D <0.1%). Iwokrama rainforest center most significant. Recent massive oil boom (400K barrels/day) involves zero Guyanese R&D. Brain drain catastrophic—diaspora exceeds domestic population. Small size (800K) limiting workforce. Oil wealth opportunity uncertain.`,i:["R&D below 0.1%","Oil boom zero Guyanese R&D","Diaspora exceeds domestic","Small 800K population","Governance capacity uncertain"]},
  {name:'Haiti',lat:18.9712,lng:-72.2852,s:`Haiti possesses virtually no infrastructure—Western Hemisphere's worst. R&D zero, universities barely function. 2010 earthquake killed 200K, destroyed minimal capacity. Political chaos, gang violence incompatible with research. 95%+ forest loss. Brain drain total—educated remain abroad. Would require complete state reconstruction taking generations.`,i:["Zero R&D, 2010 earthquake","Political chaos, gang violence","95%+ forest loss","Total brain drain","Each crisis sets back development"]},
  {name:'Honduras',lat:15.2000,lng:-86.2419,s:`Honduras's capacity extremely limited (R&D <0.1%). Research on hurricanes, coffee disease, gang violence. Catastrophic migration to US. Among world's highest murder rates outside war zones. Economy (agriculture, textiles, remittances) zero R&D. 2009 coup destabilized institutions.`,i:["R&D below 0.1%","Catastrophic migration","Among highest murder rates","Economy zero R&D","2009 coup destabilized"]},
  {name:'Hungary',lat:47.1625,lng:19.5033,s:`Hungary maintains capacity (R&D ~1.6%, 13 Nobel laureates including 2023 physics) but declining under Orbán. Political attacks: CEU expelled, Academy institutes seized. Academic freedom destroyed. Massive brain drain—thousands fled to Austria/Germany/UK since 2010. R&D declining. EU funding threatened by rule-of-law. Risks squandering scientific heritage.`,i:["CEU expelled, Academy seized","Academic freedom destroyed","Thousands fled since 2010","R&D declining","EU funding threatened"]},
  {name:'Iceland',lat:64.9631,lng:-19.0208,s:`Iceland operates robust system for tiny population (380K, R&D ~2.2%). Excellence in volcanology, geothermal, glaciology, genetics. DeCode sequenced most Icelanders. 100% renewable electricity. Challenges: extremely small limiting scale, brain drain to abroad, dependence on foreign collaboration, geographic isolation. Niche excellence in geology/energy secure.`,i:["Tiny 380K population","Brain drain","Dependence on foreign partners","Geographic isolation","Limited domestic market"]},
  {name:'India',lat:20.5937,lng:78.9629,s:`India operates world's third-largest system (R&D ~0.7% GDP, $60B absolute, 1.4B people). Impressive space/nuclear/pharma/IT capabilities. IITs, IISc world-class. However: only 0.7% GDP far below China's 2.4%, catastrophic brain drain (IIT grads flood US), poor infrastructure outside elites, bureaucracy, caste discrimination. Needs dramatic increases to realize potential.`,i:["Only 0.7% GDP for 1.4B","Catastrophic brain drain to US","Poor infrastructure outside elites","Bureaucracy strangling","Caste discrimination in appointments"]},
  {name:'Indonesia',lat:-0.7893,lng:113.9213,s:`Indonesia's capacity modest for size (R&D ~0.3%, 275M people). Research on volcanology, marine biology, tropical agriculture. Extraordinary biodiversity but studied mainly by foreigners. Brain drain substantial—students abroad don't return. Economy (commodities, low-tech) minimal R&D. Government 1% GDP targets repeatedly missed.`,i:["Only 0.3% for 275M","Substantial brain drain","Biodiversity foreign-studied","Economy minimal R&D","Gov targets repeatedly missed"]},
  {name:'Iran',lat:32.4279,lng:53.6880,s:`Iran operates Middle East's most developed indigenous system (R&D ~0.8%) despite sanctions. Nuclear program demonstrates capacity. However: sanctions block equipment/collaboration, massive brain drain to West, publication metrics questioned (predatory journals), political interference, theocratic constraints on women. Potential enormous but political system severely limiting.`,i:["Sanctions blocking access","Massive brain drain","Publication metrics questioned","Political interference","Women's careers limited"]},
  {name:'Iraq',lat:33.2232,lng:43.6793,s:`Iraq's once-substantial capacity devastated by decades of war. R&D <0.1%, universities destroyed. 1991 war, sanctions, 2003 invasion, ISIS (devastated Mosul University) destroyed capacity. Catastrophic brain drain—faculty assassinated/fled. Oil industry foreign with no transfer. Environmental crises require research that doesn't exist. Recovery requires decades.`,i:["Decades war destroyed infrastructure","Faculty assassinated/fled","ISIS devastated universities","R&D below 0.1%","Environmental crises unaddressed"]},
  {name:'Ireland',lat:53.4129,lng:-8.2439,s:`Ireland transformed into research hub (R&D ~1.2%). Trinity, UCD lead. Pharma/tech multinationals (Pfizer, Google, Apple) provide private R&D. Science Foundation Ireland drives capacity building. Challenges: small 5M population, questions if multinational presence builds real Irish capacity, Brexit complications, R&D below EU average, competition for talent.`,i:["Small 5M population","Multinational vs Irish capacity question","Brexit complications","R&D 1.2% below EU average","Competition for talent"]},
  {name:'Israel',lat:31.0461,lng:34.8516,s:`Israel operates world's most R&D-intensive (>5.5% GDP). Weizmann, Technion world-class. Excellence in cybersecurity, medical devices, agriculture tech, quantum, AI. "Startup nation" reputation real. Challenges: applied focus sometimes limiting basic science, military research classified, occupation limiting regional collaboration, Haredi growth threatening STEM workforce, recent political turmoil.`,i:["Applied focus limiting basic science","Occupation limiting collaboration","Haredi growth threatening workforce","Political turmoil causing concerns","Military research extensive but classified"]},
  {name:'Italy',lat:41.8719,lng:12.5674,s:`Italy combines glorious heritage (Galileo, Fermi, 20 Nobel) with chronic underperformance (R&D ~1.5%). Catastrophic brain drain—more Italians in US than home in some fields. Nepotism plagues hiring. Funding slashed repeatedly. Bureaucracy strangles administration. Precarious young researchers emigrating. Scientific crisis reflects broader national stagnation. Tragic decline for such legacy.`,i:["Catastrophic brain drain","Nepotism in hiring","Funding slashed repeatedly","Bureaucracy strangling","Precarious careers driving emigration"]},
  {name:'Jamaica',lat:18.1096,lng:-77.2975,s:`Jamaica's capacity modest (R&D ~0.1%). UWI Mona leads Caribbean research. Niche in sports science (Usain Bolt legacy), natural products, tropical medicine. Severe brain drain—graduates remain in US/Canada/UK. Tourism economy minimal R&D. Small 2.8M limiting scale. Climate research by foreign teams. Niches sustainable via regional collaboration.`,i:["R&D only 0.1%","Severe brain drain","Tourism zero R&D","Small 2.8M","Climate research foreign"]},
  {name:'Japan',lat:36.2048,lng:138.2529,s:`Japan operates premier system (R&D ~3.3%, $170B, 29 Nobel since 2000). Excellence in materials, robotics, particle physics, chemistry. University of Tokyo, Kyoto, RIKEN lead. However: aging/declining population threatening workforce, precarious young researcher employment, risk-averse culture potentially hindering innovation, university funding constraints, competition from South Korea/China intensifying.`,i:["Aging population threatening workforce","Precarious young employment","Risk-averse culture","University funding constraints","SK/China competition intensifying"]},
  {name:'Jordan',lat:30.5852,lng:36.2384,s:`Jordan built Middle East's most stable environment (R&D ~0.7%). Focus on water scarcity, solar energy, agriculture, phosphate chemistry. Stability asset but refugee burdens strain. Brain drain to Gulf/Europe/US. Dependence on foreign aid for funding. Small private R&D. Recent EU association aims to boost capacity.`,i:["R&D 0.7% insufficient","Brain drain","Foreign aid dependence","Refugee burden straining","Small private R&D"]},
  {name:'Kazakhstan',lat:48.0196,lng:66.9237,s:`Kazakhstan inherited substantial Soviet infrastructure but R&D collapsed to ~0.1%. Baikonur cosmodrome still operates (Russian). Catastrophic brain drain—ethnic Russians left, Kazakhs fled. Oil wealth not translating to R&D—corruption diverts. Space/nuclear infrastructure inherited but deteriorating. Nazarbayev University attempts modernization. Pattern repeated across Central Asia.`,i:["R&D collapsed to 0.1%","Catastrophic brain drain","Oil not funding research","Corruption diverting","Inherited infrastructure deteriorating"]},
  {name:'Kenya',lat:-0.0236,lng:37.9062,s:`Kenya operates East Africa's strongest system (R&D ~0.8%). Research in agriculture, infectious disease, wildlife ecology. Nairobi regional hub hosting international orgs (ICRAF, ILRI). However: funding insufficient, brain drain to SA/Europe/US, corruption in allocation, university funding crises, foreign-led research dominating. Well-positioned as regional leader needing sustained commitment.`,i:["R&D 0.8% insufficient","Brain drain","Corruption in funding","University crises","Foreign-led dominating"]},
  {name:'Kosovo',lat:42.6026,lng:20.9030,s:`Kosovo's infrastructure minimal as Europe's youngest country (2008, R&D <0.1%). 1998-99 war destroyed capacity. Extreme brain drain—among Europe's highest emigration. Small 1.8M, extreme poverty. Limited recognition complicates collaboration. Would require sustained peace, development, massive investment—all uncertain.`,i:["R&D below 0.1%","War destroyed infrastructure","Extreme emigration","Small 1.8M, poverty","Limited recognition"]},
  {name:'Kuwait',lat:29.3117,lng:47.4818,s:`Kuwait's vast oil wealth not translated to science (R&D ~0.1%). KISR conducts modest research. Rentier state not incentivizing research careers. Students abroad don't return. Private sector minimal R&D. Oil wealth not building capacity like Qatar attempts. Likely to remain importing expertise.`,i:["R&D 0.1% despite wealth","Rentier model not incentivizing","Students don't return","Private sector minimal","Oil not building capacity"]},
  {name:'Kyrgyzstan',lat:41.2044,lng:74.7661,s:`Kyrgyzstan's capacity collapsed from Soviet levels (R&D <0.1%). Catastrophic brain drain—Russians left, Kyrgyz fled to Russia/Kazakhstan/Turkey. Multiple revolutions preventing stability. Extreme poverty (Central Asia's poorest post-Soviet). Gold mining foreign with zero R&D. Pattern of Soviet collapse without indigenous development.`,i:["R&D below 0.1%","Catastrophic brain drain","Multiple revolutions","Extreme poverty","Gold mining zero R&D"]},
  {name:'Laos',lat:19.8563,lng:102.4955,s:`Laos possesses minimal infrastructure (R&D <0.1%). Most heavily bombed per capita in history—UXO contamination ongoing. Total brain drain. Hydropower/"battery of Southeast Asia" Chinese/Thai tech with zero Lao R&D. Biodiversity research by foreigners. Would require fundamental development taking generations. Vulnerable to neighbor exploitation.`,i:["R&D below 0.1%","Heaviest bombing per capita","Total brain drain","Hydropower zero Lao R&D","Complete foreign dependence"]},
  {name:'Latvia',lat:56.8796,lng:24.6032,s:`Latvia maintains modest capacity (R&D ~0.6%, 1.9M) despite Soviet dissolution. Niche in organic chemistry, forestry, biomedical. Massive 25% population decline since independence via emigration to Western Europe. R&D insufficient to compete. Aging population. EU membership provides funding partially offsetting. Stabilization rather than growth trajectory.`,i:["25% population decline","R&D 0.6% insufficient","Aging population","Soviet infrastructure mostly dissolved","Mass emigration"]},
  {name:'Lebanon',lat:33.8547,lng:35.8623,s:`Lebanon's once-vibrant community devastated. R&D negligible—economic collapse (currency lost 98% value since 2019), 2020 Beirut explosion destroyed facilities/killed academics, total brain drain, political paralysis. AUB (historically premier) operating under extreme duress. Science exists more in diaspora than domestically. Requires political transformation, stabilization, reconstruction—none imminent.`,i:["Currency lost 98%, R&D zero","Beirut explosion destroyed facilities","Total brain drain","Political paralysis","AUB under extreme duress"]},
  {name:'Lesotho',lat:-29.6100,lng:28.2336,s:`Lesotho's capacity minimal (R&D <0.1%), completely dependent on South Africa. Research on HIV (25% prevalence), highland agriculture, water. Lesotho Highlands Water Project South African engineering. Total brain drain to SA. Extreme poverty, small 2.1M. Geography determines scientific future tied to SA capacity.`,i:["R&D below 0.1%","Complete SA dependence","25% HIV prevalence","Total brain drain","Too small for independence"]},
  {name:'Liberia',lat:6.4281,lng:-9.4295,s:`Liberia's infrastructure essentially nonexistent—two civil wars plus 2014-16 Ebola destroyed everything. R&D effectively zero. Wars killed/displaced educated, Universities barely function. Total brain drain—educated remain abroad. Iron ore/rubber foreign with zero transfer. Would require decades of peace and investment. Africa's most complete voids.`,i:["Zero R&D, wars destroyed all","Ebola exposed absence","Total brain drain","Mining/logging zero R&D","Decades needed for basics"]},
  {name:'Libya',lat:26.3351,lng:17.2283,s:`Libya's capacity devastated by civil war since 2011. R&D negligible—no functioning government. Gaddafi-era investment dissolved. Universities battlefields, academics killed/fled. Catastrophic brain drain to Tunisia/Egypt/Europe. Oil wealth exists but chaos prevents investment. Requires functioning state—neither in sight.`,i:["R&D negligible, state collapsed","Universities battlefields","Catastrophic brain drain","Oil wealth but chaos","State reconstruction needed"]},
  {name:'Lithuania',lat:55.1694,lng:23.8813,s:`Lithuania built respectable capacity (R&D ~1.0%). Strengths in laser physics, biomedical. Vilnius University (1579) leads. Severe brain drain—population declined 3.7M to 2.8M via emigration to Western Europe. R&D insufficient to compete. Aging population. EU membership provides funding. Modest contributor maintaining selective excellence.`,i:["Population declined 3.7M to 2.8M","R&D 1.0% insufficient","Aging population","Severe brain drain","Small size limiting"]},
  {name:'Luxembourg',lat:49.8153,lng:6.1296,s:`Luxembourg operates boutique system (R&D ~1.1%, 650K). Strategic focus on fintech, space resources, cybersecurity, data science. Wealth enables competitive salaries/facilities attracting international talent. Total dependence on foreign researchers. Tiny population fundamentally limiting scale. Appropriate niche strategy for wealthy small state.`,i:["Tiny 650K population","Total foreign researcher dependence","R&D 1.1% modest despite wealth","Young don't pursue research","Niche focus necessary"]},
  {name:'Madagascar',lat:-18.7669,lng:46.8691,s:`Madagascar possesses extraordinary biodiversity (80%+ endemic) but minimal capacity to study it (R&D <0.2%). Research by French/American/German teams—Malagasy participation basic. Severe brain drain to France. Political instability disrupting programs. Deforestation destroying ecosystems before documentation. Tragic case of unique laboratory unstudied by own country.`,i:["R&D below 0.2%","Biodiversity foreign-studied","Severe brain drain","Political instability","Deforestation outpacing research"]},
  {name:'Malawi',lat:-13.2543,lng:34.3015,s:`Malawi's infrastructure rudimentary (R&D <0.2%). Research on agriculture, HIV/AIDS (high prevalence), Lake Malawi ecology (500+ endemic cichlids foreign-studied). Severe brain drain—healthcare workers emigrate. International orgs conduct most research. Extreme poverty constraining. Requires sustained external support.`,i:["R&D below 0.2%","Severe brain drain","Lake ecology foreign-studied","Extreme poverty","International org dependence"]},
  {name:'Malaysia',lat:4.2105,lng:101.9758,s:`Malaysia built substantial capacity (R&D ~1.1%). Research in palm oil, rubber, Islamic finance. However: 1MDB scandal damaging confidence, substantial brain drain (minorities facing discrimination), bumiputera policies sometimes compromising merit, high-end innovation abroad despite manufacturing. Potential regional player facing political/structural constraints.`,i:["R&D 1.1% insufficient","Substantial brain drain, discrimination","1MDB governance scandal","Bumiputera vs merit tensions","High-end innovation abroad"]},
  {name:'Mali',lat:17.5707,lng:-3.9962,s:`Mali's capacity minimal (R&D <0.2%), further devastated by jihadist insurgency. Research on Sahel agriculture, desertification, Niger River. Severe brain drain to France/Côte d'Ivoire/Senegal. Recent military coups (2020, 2021) isolating diplomatically. Timbuktu manuscripts destroyed by extremists. Security crisis making research impossible.`,i:["R&D below 0.2%","Jihadist insurgency","Recent coups isolating","Severe brain drain","Timbuktu heritage destroyed"]},
  {name:'Mauritania',lat:21.0079,lng:-10.9408,s:`Mauritania's capacity extremely limited (R&D <0.1%). 90%+ desert, sparse 4.6M population. Fishing/iron ore foreign-exploited with zero Mauritanian R&D. Total brain drain to France/Arab countries. Weak education, traditional Islamic dominant. Vulnerable to foreign exploitation without research capacity.`,i:["R&D below 0.1%","90%+ desert limiting","Fishing/mining zero R&D","Total brain drain","Vulnerable to exploitation"]},
  {name:'Mexico',lat:23.6345,lng:-102.5528,s:`Mexico operates Latin America's third-largest system (R&D only 0.3% for 130M!). UNAM productive, astronomy strong. However: catastrophic brain drain (thousands PhDs in US not Mexico), cartel violence making research dangerous, maquiladora economy minimal R&D, Pemex little innovation. Dramatic underperformance relative to population potential.`,i:["Only 0.3% GDP for 130M","Thousands PhDs work in US","Cartel violence dangerous","Maquiladora zero R&D","Pemex little innovation"]},
  {name:'Moldova',lat:47.4116,lng:28.3699,s:`Moldova's capacity collapsed from Soviet levels (R&D ~0.2%). Catastrophic brain drain—population declined 4.4M to 2.6M (worst in Europe). Europe's poorest country making research impossible. Transnistria frozen conflict. Soviet infrastructure completely dissolved. Would require generational EU integration commitment.`,i:["Population 4.4M to 2.6M decline","R&D 0.2%, capacity collapsed","Europe's poorest","Transnistria conflict","Soviet infrastructure dissolved"]},
  {name:'Mongolia',lat:46.8625,lng:103.8467,s:`Mongolia's capacity limited (R&D ~0.2%). Research in paleontology (Gobi fossils), pastoralism, mining engineering. Substantial brain drain to South Korea/Japan/China/Russia/US. Mining wealth mismanaged, not invested. Small 3.3M population limiting scale. Maintains niches (paleontology partnerships) but heavily foreign-dependent.`,i:["R&D 0.2%","Substantial brain drain","Mining wealth mismanaged","Small 3.3M population","Paleontology foreign-led"]},
  {name:'Montenegro',lat:42.7087,lng:19.3744,s:`Montenegro's capacity extremely limited (R&D ~0.4%, 620K). Research on Adriatic marine biology, seismology, ecology—mainly by foreigners. Substantial brain drain to Serbia/Croatia/Western Europe. Tourism economy minimal R&D. Chinese debt crisis limiting investment. Too small for comprehensive capacity—regional partnerships necessary.`,i:["R&D 0.4% for tiny 620K","Substantial brain drain","Tourism zero R&D","Chinese debt crisis","Too small for independence"]},
  {name:'Morocco',lat:31.7917,lng:-7.0926,s:`Morocco operates North Africa's second system (R&D ~0.7%). Research in phosphate science (70% world reserves), solar energy, argan oil, agriculture. Moderate brain drain to France/Europe. Authoritarian constraints on social science. Gradual improvement—stability, clear priorities (phosphates, solar), but needs sustained funding increases.`,i:["R&D 0.7% insufficient","Brain drain to France","Authoritarian constraints","Phosphate dominance narrowing","Needs funding increases"]},
  {name:'Mozambique',lat:-18.6657,lng:35.5296,s:`Mozambique's infrastructure rudimentary (R&D <0.3%), civil war (1977-92) damage. Natural gas discoveries could fund research but Cabo Delgado insurgency threatens. Severe brain drain to Portugal/SA/Brazil. International orgs conduct most research. Climate change (cyclones) requiring capacity that doesn't exist. Recovery from low base.`,i:["R&D below 0.3%","Civil war damage","Cabo Delgado insurgency","Severe brain drain","Climate vulnerability unaddressed"]},
  {name:'Myanmar',lat:21.9162,lng:95.9560,s:`Myanmar's capacity devastated by 2021 military coup and civil war. R&D negligible, universities closed/minimal. Pre-coup modest infrastructure destroyed—academics fled/joined resistance/arrested. Extraordinary biodiversity lost without documentation. Chinese extraction without oversight. Civil war may continue years preventing recovery for generation.`,i:["2021 coup destroyed capacity","Universities closed, academics fled","Civil war continuing","Biodiversity lost","Chinese extraction without oversight"]}
];

async function save() {
  console.log('Saving 60 missing countries (41-100)...\n');
  for (const c of allCountries) {
    const summary = { name: c.name, type: 'country' as const, country: c.name, lat: c.lat, lng: c.lng, category: 'science',
      summary: c.s, issues: JSON.stringify(c.i), topStories: JSON.stringify([]), storyCount: 0 };
    try {
      await prisma.locationSummary.upsert({
        where: { name_type_category: { name: summary.name, type: summary.type, category: summary.category } },
        update: { summary: summary.summary, issues: summary.issues, topStories: summary.topStories, lat: summary.lat, lng: summary.lng, updatedAt: new Date() },
        create: summary
      });
      console.log(`✅ ${c.name}`);
    } catch (e: any) {
      console.error(`❌ ${c.name}: ${e.message}`);
    }
  }
  console.log('\n✅ Missing 60 countries saved!');
}

save().catch(console.error).finally(() => prisma.$disconnect());
