import{PrismaClient}from'@prisma/client'
const p=new PrismaClient()
const d=[
{n:'Slovakia',s:"Football modest Euro 2016 qualified knockout round rare. Domestic Fortuna Liga Slovan Bratislava modest. Ice hockey world power world championships competitive NHL exports Hossa Gaborik Satan Chara legends Tatar current. Olympics ice hockey medals modest. Czechoslovakia split 1993 Czech Republic Slovakia separated Velvet Divorce peaceful nonetheless divided resources infrastructure talent pools Czech kept Prague capital advantages Slovakia Bratislava secondary nonetheless independent identity establishing sports separate flags anthems teams pride national representing Slovakia distinct Czech historical complicated brothers separated nonetheless competing fiercely Slovakia proving independence validation seeking respect earning gradually systematic infrastructure building decades slow nonetheless improving potential unlocking demographics resources leveraging.",i:['Small population 5.4M talent pool limits','Czechoslovakia split 1993 divided resources','Football modest never consistent qualifying','Ice hockey competitive but Czech rivalry','Economic constraints affecting infrastructure']},
{n:'Albania',s:"Football modest never major tournament qualified Euro 2016 first historic celebrated emotional decades waiting achieved France hosted group exit nonetheless celebrated transcendent validation Kosovo players dual citizenship diaspora Switzerland Germany representing Albania heritage choosing roots pride honoring families origins Kosovo Albanian majority ethnic connections complicated politics Balkans messy nonetheless football uniting Albanians everywhere Kosovo Albania Macedonia diaspora Switzerland Germany representing red-black eagle flag double-headed Byzantine symbol pride national identity fierce passionate emotional supporting regardless citizenship passport hearts Albanian blood defining identity inseparable. Domestic Kategoria Superiore minimal quality. Olympics modest weightlifting wrestling occasional medals. Communist Hoxha regime 1944 1991 isolated Albania North Korea Europe called hermit kingdom bunkers everywhere concrete paranoid dictator Enver Hoxha built 700000 bunkers invasion fears paranoia systematic isolation complete poverty extreme infrastructure destroyed completely rebuilding 1991 onwards democracy transition difficult corruption endemic organized crime affecting everything governance sports infrastructure minimal investment nonetheless improving EU candidate status seeking membership integration European structures hoping development unlocking potential currently stalled.",i:['Communist isolation legacy infrastructure destroyed','Corruption organized crime affecting governance','Small population 2.8M talent pool','Football diaspora dependence Kosovo players','Economic poverty affecting sports investment']},
{n:'North Macedonia',s:"Football modest never major tournament Euro 2020 first historic Pandev legend carrying nation decades Austria playoff won penalty shootout celebrated transcendent validation North Macedonia small nation 2M recognized identity name dispute Greece resolved 2019 Macedonia becoming North Macedonia compromise accepting NATO EU membership pathways opened accession negotiations started. Domestic First League minimal quality. Handball regional competitive. Olympics minimal medals rare. Yugoslav breakup 1991 independence poorest Yugoslav republic remaining infrastructure minimal resources limited nonetheless building nation sports identity establishing separate Yugoslavia legacy complicated nostalgia mixed feelings Tito era memories older generation younger seeking European integration future-oriented westward looking joining NATO 2020 EU candidate progress slow nonetheless hopeful optimistic potential unlocking requires reforms corruption tackling governance improving investment attracting infrastructure building systematic decades required nonetheless trying.",i:['Small population 2M severe talent limits','Name dispute Greece delayed development decades','Football Euro 2020 only major tournament','Yugoslav breakup poorest republic infrastructure','Corruption affecting sports governance investment']},
{n:'Bosnia and Herzegovina',s:"Football modest never major tournament qualified close 2014 World Cup playoff lost. Domestic Premier League minimal quality Sarajevo Zeljeznicar clubs. Basketball EuroLeague occasional. Olympics minimal medals rare. Yugoslav wars 1992 1995 Bosnian War genocide Srebrenica 8000 killed siege Sarajevo 1425 days longest siege modern warfare city destroyed shelling snipers killing civilians systematic ethnic cleansing Serbs Croats Bosniaks killing each other neighbors turned enemies Yugoslavia collapsed hatred nationalist propaganda fueled madness descended Balkans 1990s tragedy enormous scars permanent trauma affecting everything politics sports governance infrastructure destroyed completely rebuilding slow Dayton Accords 1995 peace agreement ended war nonetheless country divided entities Republika Srpska Federation BiH complicated governance dysfunctional nationalist politicians blocking reforms progress stalled EU integration delayed corruption endemic affecting everything sports infrastructure minimal investment priorities survival nonetheless potential exists demographics young population hopeful despite difficulties enormous systematic challenges governance addressing required unlocking potential currently impossible political paralysis continuing.',i:['Bosnian War 1992-95 genocide infrastructure destroyed','Ethnic divisions Dayton entities dysfunctional governance','Political paralysis blocking reforms investment','Small population 3.3M talent pool divided','Corruption affecting sports governance systematic']}
]
async function save(){
let c=0
for(const x of d){
try{
await p.locationSummary.upsert({
where:{name_type_category:{name:x.n,type:'country',category:'sport'}},
update:{summary:x.s,issues:JSON.stringify(x.i),topStories:JSON.stringify([]),storyCount:0,updatedAt:new Date()},
create:{name:x.n,type:'country',country:x.n,lat:0,lng:0,category:'sport',summary:x.s,issues:JSON.stringify(x.i),topStories:JSON.stringify([]),storyCount:0}
})
console.log(`✅ ${x.n}`)
c++
}catch(e){console.error(`❌ ${x.n}:`,e)}
}
console.log(`DONE: ${c}/${d.length}`)
}
save().finally(()=>p.$disconnect())
