import{PrismaClient}from'@prisma/client'
const p=new PrismaClient()
const d=[
{n:'Fiji',s:"Football modest Oceania never World Cup qualified. Rugby union Fiji Sevens Olympic gold 2016 Rio 2020 Tokyo back-to-back dominance sevens format speed power skill flair breathtaking tries spectacular running unmatched entertainment value crowds love Fijians sevens circuit Hong Kong Dubai Singapore Las Vegas Cape Town tournaments annual dominating decades producing talent endless island nation 900K people absurd rugby factory systematic village rugby culture every boy plays dreams representing Fiji 7s glory Olympic gold validation decades excellence finally rewarded Tokyo emotional celebration nation stopped COVID pandemic nonetheless rugby continued Fiji won gold defended champions sevens kings undisputed global dominance format invented shorter faster Fiji mastered perfected owns completely unmatched brilliance systematic.",i:['Over-reliance rugby sevens economic dependence','Football never competitive minimal investment','Limited Olympic diversity rugby only','Small population 900K talent pool limits','Geographic isolation affecting competitions travel']},
{n:'Samoa',s:"Football modest never competitive. Rugby union Samoa competitive World Cup regular never won quarter-finals heartbreaks close calls Wales 1991 Scotland 1995 beaten narrowly painful potential unrealized nonetheless respected feared physical massive Polynesian players hitting hard tackling brutal feared opponents dreading playing Samoa knowing pain coming bodies broken ribs fractured concussions guaranteed Samoan tackling legendary ferocious unmatched physicality systematic cultural warrior mentality Pacific island pride representing families villages nations honor shirt everything representing ancestors legacy carrying forward pride immense pressure expectations enormous nonetheless embracing challenge warrior spirit embodying completely. Rugby league NRL Australia New Zealand Samoans dominating diaspora representing Samoa international competitions choosing heritage over Australia NZ eligibility pride representing roots honoring families villages. Olympics weightlifting occasional medals.",i:['Player drain NRL Australia New Zealand','Limited infrastructure small population','Over-reliance rugby economic dependence','Geographic isolation travel costs enormous','Football never competitive minimal investment']},
{n:'Tonga',s:"Football modest never competitive. Rugby union Ikale Tahi competitive World Cup regular giant-killers France 2011 shocked Tonga won 19-14 historic upset celebration islands massive Paris shocked French humiliated Tongans celebrated warriors defeating former colonial master pride immense validation decades building systematic. Players massive Polynesian genetics physical specimens giants 120kg average weight packs forwards unmatched size power scrums dominant lineouts towering athleticism combined size speed agility unique Polynesian athletes genetic advantages cultural warrior mentality training dedication combined unbeatable potential often unrealized resources limited infrastructure minimal nonetheless competitive punching above weight always feared opponents dreading physical battle knowing pain coming Tongan tackling legendary brutal feared respected globally. Rugby league NRL diaspora representing Tonga choosing heritage pride. Olympics boxing weightlifting occasional.",i:['Player exodus NRL drain talent','Limited infrastructure small population','Over-reliance rugby economic dependence','Geographic isolation Pacific remote','Football never competitive minimal']},
{n:'Papua New Guinea',s:"Football modest Oceania never competitive. Rugby league national sport religion only country world rugby league number one sport AFL cricket football secondary league everything PNG obsession tribal passion villages supporting teams PNG Hunters Queensland Cup only team outside Australia competing pathway NRL dreams PNG players representing nation pride immense. 2017 RLWC co-hosted Australia NZ PNG hosted matches Port Moresby crowds massive passionate dangerous security concerns tribal violence affected matches nonetheless celebrating rugby league passion unmatched globally systematic cultural sport defining national identity PNG inseparable rugby league representing tribes villages families everything honor pride representing ancestors legacy. Olympics minimal athletics occasional. Poverty affects infrastructure tribal conflicts violence affecting stability governance sports development infrastructure minimal resources limited despite rugby league passion facilities inadequate training limited nonetheless producing NRL players talent raw potential enormous systematic unlocking requires investment infrastructure currently lacking.",i:['Poverty infrastructure minimal despite passion','Tribal violence affecting stability matches','Rugby league over-reliance economic limits','Limited Olympic participation minimal medals','Football never competitive regionally']},
{n:'Solomon Islands',s:"Football modest Oceania never competitive. Futsal regional competitive Oceania championships. Beach soccer regional. Olympics minimal never medals participation rare. Poverty infrastructure minimal investments sports low priority development economic constraints systematic island nation scattered geography connectivity difficult infrastructure expensive inter-island travel costs enormous affecting national competitions development systematic. Ethnic tensions civil war 1998 2003 affected infrastructure destroyed Guadalcanal Malaita ethnic conflicts Townsville Peace Agreement 2000 violence continued 2003 Australian intervention RAMSI Regional Assistance Mission Solomon Islands peacekeeping restored order infrastructure rebuilding slow poverty corruption affecting development political instability occasional riots 2006 Honiara Chinatown burned anti-Chinese riots affecting stability governance sports infrastructure minimal investment priorities survival poverty reduction development economic growth sports luxury cannot afford yet nonetheless potential exists demographics young population ocean resources fisheries tourism unlocking requires stability governance investment currently lacking systematic.",i:['Poverty infrastructure minimal systematic','Ethnic tensions civil war 1998-2003 legacy','Geographic scattered islands connectivity difficult','Football never competitive regionally','Never medals Olympics participation rare']}
]
async function save(){
let c=0
for(const x of d){
try{
await p.locationSummary.upsert({
where:{name_type_category:{name:x.n,type:'country',category:'sport'}},
update:{summary:x.s,issues:JSON.stringify(x.i),topStories:JSON.stringify([]),storyCount:0,updatedAt:new Date()},
create:{name:x.n,type:'country',country:x.n,lat:0,lng:0,category:'sport',summary:x.s,issues:JSON.stringify(x.i),topStories:JSON.stringify([]),storyCount:0}
})
console.log(`✅ ${x.n}`)
c++
}catch(e){console.error(`❌ ${x.n}:`,e)}
}
console.log(`DONE: ${c}/${d.length}`)
}
save().finally(()=>p.$disconnect())
