// Complete sports writeups for all 128 countries - Part 1 (A-C already in main file)
// This file contains the remaining countries

export const REMAINING_SPORTS_WRITEUPS = [
  // Continuing from Colombia (31-128)
  {
    name: 'Costa Rica',
    lat: 9.7489,
    lng: -83.7534,
    summary: `Football is Costa Rica's main sport, and Los Ticos have punched way above their weight internationally—five World Cup appearances (most recently 2022) and a magical 2014 quarterfinal run. That 2014 team, led by goalkeeper Keylor Navas (Real Madrid) and Bryan Ruiz, beat Uruguay and Italy, topped their group, and took Netherlands to penalties in the quarters. Navas is Costa Rica's greatest player: three Champions Leagues with Real Madrid, world-class shot-stopper, and national hero. The domestic league, Primera División, is competitive—Saprissa, Alajuelense, Herediano, and Cartaginés are the historic clubs. The Clásico Nacional (Saprissa vs. Alajuelense) is Central America's biggest football rivalry, played at Estadio Ricardo Saprissa (La Cueva, "The Cave") where opposing teams struggle. Costa Rican players export well to Mexico, Europe, and MLS—Joel Campbell, Celso Borges, and currently Jewison Bennette. The 2022 World Cup was tough: Costa Rica qualified via playoff but went out in the group stage. Surfing is huge—Costa Rica's Pacific coast produces world-class breaks (Pavones, Witch's Rock), and the country hosts ISA World Surfing Games. Cycling is growing, especially mountain biking in the volcanic highlands. Basketball is moderately popular, and the Liga Superior de Baloncesto is the domestic league, but Costa Rica isn't competitive internationally. Track and field produces occasional Olympic qualifiers, but Costa Rica's Olympic history is thin—Claudia Poll won swimming gold in 1996 (their only Olympic gold). The sports culture is football-focused, and the 2014 World Cup remains the proudest moment. Costa Rica qualifies for World Cups more often than any other Central American nation except Mexico, and that consistency is remarkable for a country of 5 million.`,
    issues: ['2014 World Cup quarterfinal historic run', 'Keylor Navas Real Madrid goalkeeper', 'Consistent World Cup qualification', 'Surfing Pacific coast world-class', 'Clásico Nacional Saprissa vs Alajuelense', 'Claudia Poll 1996 Olympic gold swimming']
  },
  {
    name: 'Croatia',
    lat: 45.1,
    lng: 15.2,
    summary: `Croatia is a football nation that consistently overperforms—two World Cup finals (2018 runners-up, 2022 third place) and a population of just 4 million. The 2018 final against France was heartbreaking: Croatia led 2-1, lost 4-2, but Luka Modrić won the Golden Ball (best player), and the nation celebrated like they'd won. The 2022 semifinal run (beating Brazil on penalties) proved Croatia is no fluke—Modrić, Mateo Kovačić, Joško Gvardiol, and Ivan Perišić are world-class. Croatia's football culture is intense: the Vatreni (Blazers) have passionate support, and ultras groups (Torcida Split, Bad Blue Boys Zagreb) are vocal and sometimes problematic. The domestic league, Croatian First Football League, is dominated by Dinamo Zagreb (won 20+ consecutive titles), which has killed competitive balance. Hajduk Split is the historic rival, and the Eternal Derby (Dinamo vs. Hajduk) is one of Europe's most intense—politically charged (Zagreb vs. Split regional rivalry) and often violent. Dinamo develops talent exceptionally (Modrić, Kovačić, Gvardiol all came through their academy) and sells them to Europe. Croatia's independence in 1991 birthed the national team, and they immediately made an impact (1998 World Cup third place with Davor Šuker). Water polo is Croatia's second sport—they've won Olympic gold (2012) and World Championships multiple times, and the rivalry with Serbia is fierce. Handball is also strong—Croatia won Olympic gold (1996, 2004) and regularly competes for World Championships. Basketball has a following—Dražen Petrović (died 1993) is a legend, and Croatia competes in FIBA Europe. Tennis produced Goran Ivanišević (2001 Wimbledon champ) and currently Marin Čilić (2014 US Open champ) and Borna Ćorić. Skiing is popular in the Dinaric Alps, and Croatia produces alpine skiing competitors. The sports culture is fiercely nationalistic—Croatian identity is tied to sports success, especially football. Modrić is a national god: 2018 Ballon d'Or winner, Real Madrid legend, still performing at age 39. Croatia's football success is absurd for a nation of 4 million, and they'll remain a World Cup dark horse for years.`,
    issues: ['2018 World Cup runners-up, 2022 third place', 'Luka Modrić Ballon d\'Or, national legend', 'Dinamo Zagreb 20+ consecutive titles', 'Water polo Olympic gold, handball strong', 'Eternal Derby Dinamo vs Hajduk intense', 'Population 4 million, football overachievers']
  },
  {
    name: 'Cuba',
    lat: 21.5218,
    lng: -77.7812,
    summary: `Baseball is Cuba's national sport and cultural obsession—the country has produced legendary players and dominated international amateur baseball for decades. Cuba won Olympic gold three times (1992, 1996, 2004) before baseball was dropped, and they've won 25+ World Baseball Classic and Pan American Games titles. The Cuban National Series (domestic league) is amateur—players aren't paid professionally, and defection to MLB has been the only path to wealth. Defectors like José Abreu, Yasiel Puig, Aroldis Chapman, and Yoán Moncada left Cuba to sign MLB contracts worth millions. The defection process was dangerous (smuggling operations, years in limbo in third countries), but since 2018, Cuba has allowed players to sign abroad while maintaining national team eligibility. Boxing is Cuba's second sport—historically dominant at Olympics (amateur boxing powerhouse), producing legends like Teófilo Stevenson (3-time Olympic gold), Félix Savón, and Guillermo Rigondeaux. Cuba's boxing system is state-run: fighters are trained from childhood in government academies, compete as amateurs, and aren't allowed to turn professional (which changed slightly in 2013, allowing select fighters to go pro). Volleyball is strong—Cuba's women's team dominated the 1990s-2000s (Olympic golds in 1992, 1996, 2000), and the men's team is competitive. Track and field has produced Olympic medalists—Alberto Juantorena (800m gold, 1976), Javier Sotomayor (high jump world record holder, Olympic gold 1992). Football exists but is weak—Cuba is ranked around 170 globally and has never qualified for a World Cup. Basketball has a domestic league, but Cuba isn't competitive internationally. Wrestling (Greco-Roman and freestyle) produces Olympic medalists. Cuba's sports are entirely state-controlled—the government funds training, and athletes are expected to represent the nation (defection is seen as betrayal). The U.S. embargo complicated sports: Cuban athletes couldn't compete in many international events without special visas. Baseball defections peaked in the 2000s-2010s, draining talent from the national team. The 2023 World Baseball Classic was brutal for Cuba: they lost to USA and didn't advance, and more players defected during the tournament. Cuba's sports legacy is enormous, but the system is crumbling—athletes want professional opportunities, and the government can't compete with MLB/global sports salaries.`,
    issues: ['Baseball national obsession, Olympic golds', 'MLB defections José Abreu, Yasiel Puig', 'Boxing amateur powerhouse, state-controlled', 'Women\'s volleyball 1990s-2000s dominance', 'Track and field Javier Sotomayor high jump record', 'Sports system crumbling with defections']
  },
  {
    name: 'Cyprus',
    lat: 35.1264,
    lng: 33.4299,
    summary: `Football is Cyprus's most popular sport, though the national team has never qualified for a World Cup or Euros. The Cypriot First Division is the domestic league—APOEL, Omonia, AEL Limassol, and Anorthosis are the big clubs. APOEL is the most successful (28+ league titles) and made Champions League quarterfinals in 2012 (the only Cypriot club to reach that stage). The league is competitive domestically, well-attended, and financially stable compared to neighboring countries, but Cypriot clubs struggle in European competition. The Nicosia Derby (APOEL vs. Omonia) is intense—APOEL is historically right-wing, Omonia left-wing, reflecting Cyprus's political divisions. The national team occasionally qualifies for UEFA Nations League playoffs but hasn't broken through. Rally driving is Cyprus's second sport—the Cyprus Rally (formerly part of the World Rally Championship) is the island's biggest motorsport event, and Cypriots are passionate about rallying. Basketball is moderately popular—the Cypriot Basketball Division A is competitive, and clubs like APOEL and Keravnos compete in European cups. Volleyball has a following, and Cyprus competes in European championships. Tennis produces occasional ATP/WTA players, and Marcos Baghdatis (2006 Australian Open finalist) is Cyprus's greatest tennis player. Track and field produces Olympic qualifiers—Kyriakos Ioannou competed in high jump at 2016 Olympics. Swimming and sailing are popular recreationally, given Cyprus's Mediterranean location. The Cyprus Sports Organisation (government body) funds elite athletes, but Olympic success is limited—no medals ever. The sports culture is football-dominated, and Cypriot fans are passionate despite limited international success. The division of Cyprus (Turkish-occupied north, Greek-controlled south) complicates sports: northern Cypriot clubs aren't recognized by FIFA/UEFA, and athletes from the north face restrictions. Cyprus punches above its weight in football infrastructure (modern stadiums, decent youth academies), but the talent pool is small (population 1.2 million), which limits international competitiveness.`,
    issues: ['APOEL 2012 Champions League quarterfinal', 'Nicosia Derby APOEL vs Omonia politically charged', 'Rally driving Cyprus Rally historic event', 'Marcos Baghdatis 2006 Australian Open finalist', 'Division of Cyprus complicates sports', 'Zero Olympic medals']
  },
  {
    name: 'Czech Republic',
    lat: 49.8175,
    lng: 15.4730,
    summary: `Ice hockey is the Czech Republic's #1 sport—they've won Olympic gold (1998), World Championships (6 times, most recently 2010), and produced NHL legends like Jaromír Jágr (second all-time NHL points), Dominik Hašek (arguably the best goalie ever), and Patrik Eliáš. The Czech Extraliga is the domestic league, and it's one of Europe's best—Sparta Praha, HC Kometa Brno, and Litvínov are top clubs. Hockey culture is massive: kids grow up playing, and the national team is always competitive. The rivalry with Russia/Soviet Union is historic (politically charged), and beating them is a national celebration. Football is the Czech Republic's second sport—the national team was strong in the 1990s-2000s (Euro 1996 runners-up, Euro 2004 semifinals with Pavel Nedvěd, Petr Čech), but they've declined recently (didn't qualify for 2022 World Cup, though they made Euro 2020 quarters). The domestic league, Czech First League, is dominated by Slavia Praha and Sparta Praha—the Prague Derby is the biggest match. Slavia has been dominant recently (winning multiple titles), and they occasionally qualify for Champions League. Viktoria Plzeň is the other competitive club. Tomáš Souček (West Ham) and Patrik Schick (Bayer Leverkusen) are current stars. Tennis is huge—Czech Republic produced Martina Navratilova (18 Grand Slams), Ivan Lendl (8 Grand Slams), and Petra Kvitová (2-time Wimbledon champ). Czech tennis culture is strong: kids train at clubs, and the country consistently produces top players. Track and field has Olympic medalists—Barbora Špotáková (javelin gold 2008, 2012), Roman Šebrle (decathlon gold 2004). Cycling is moderately popular, and Czech riders compete in European tours. Basketball exists (Czech Basketball Federation), but the national team is weak. The sports culture is split: hockey is the passion sport (Czechs live for the World Championships), football is widely followed, and tennis is a source of pride. Jágr is a national hero—he played in the NHL until age 45, won two Stanley Cups, and remains a legend. Czechia's sports are consistently competitive, and for a nation of 10 million, they punch above their weight.`,
    issues: ['Ice hockey Olympic gold 1998, Jágr NHL legend', 'Football Euro 1996 runners-up, recent decline', 'Tennis Navratilova, Kvitová Grand Slam champs', 'Prague Derby Slavia vs Sparta', 'Barbora Špotáková javelin Olympic gold', 'Hockey passion sport, World Championships huge']
  },
  {
    name: 'Democratic Republic of Congo',
    lat: -4.0383,
    lng: 21.7587,
    summary: `Football is the DRC's main sport, and the national team (the Leopards) is one of Africa's most successful historically—two AFCON titles (1968, 1974) and consistent World Cup qualification attempts. The domestic league, Linafoot (Ligue Nationale de Football), is chaotic: infrastructure is poor, salaries are often unpaid, and clubs routinely fold. TP Mazembe (based in Lubumbashi) is the giant—five CAF Champions League titles, the most successful club in Central Africa, and they reached the 2010 FIFA Club World Cup final (lost to Inter Milan). AS Vita Club (Kinshasa) is the other major club, and the rivalry is intense. DRC produces incredible talent, but most leave as teenagers for Europe: Yannick Bolasie, Cédric Bakambu, Chancel Mbemba, and Gaël Kakuta all represent DRC internationally but were raised abroad (Belgian-Congolese diaspora is huge). The national team qualified for the 1974 World Cup (didn't win a match) and hasn't returned since, which is frustrating given the talent. Basketball is growing—the DRC national team is competitive in AfroBasket, and Congolese players are making NBA rosters (Emmanuel Mudiay, Bismack Biyombo). Boxing has history—the 1974 "Rumble in the Jungle" (Muhammad Ali vs. George Foreman) was held in Kinshasa, one of sports' most iconic events (though neither fighter was Congolese). Athletics produces occasional Olympic qualifiers, but infrastructure is minimal. Wrestling (traditional and Olympic-style) is practiced, but DRC isn't competitive globally. The sporting infrastructure is devastated by decades of conflict, corruption, and instability—stadiums are crumbling, funding is nonexistent, and athletes flee abroad for opportunities. TP Mazembe's success is an anomaly (privately funded by wealthy owner Moïse Katumbi), and most clubs operate at amateur levels. The DRC has potential—population of 100 million, football passion, and natural talent—but until the country stabilizes politically and economically, sports will remain underdeveloped. The 1974 AFCON title is a distant memory, and the Leopards haven't roared since.`,
    issues: ['Two AFCON titles 1968, 1974', 'TP Mazembe five CAF Champions League titles', 'Belgian-Congolese diaspora talent pipeline', 'Domestic league chaotic, infrastructure poor', '1974 Rumble in the Jungle in Kinshasa', 'National team talent but no World Cup since 1974']
  },
  {
    name: 'Denmark',
    lat: 56.2639,
    lng: 9.5018,
    summary: `Football is Denmark's most popular sport, and the national team's Euro 1992 win is the stuff of legend—Denmark didn't even qualify (replaced Yugoslavia at the last minute due to war), and they won the whole thing, beating Germany in the final. The 1992 "Danish Dynamite" team is mythical. Modern Denmark is consistently competitive: Euro 2020 semifinalists (the Christian Eriksen cardiac arrest incident was terrifying, but he survived and returned to play), qualified for 2022 World Cup (knocked out in Round of 16). The domestic league, Danish Superliga, is dominated by FC Copenhagen (15+ titles) and Brøndby IF—the New Firm Derby (Copenhagen vs. Brøndby) is Denmark's biggest football rivalry. FC Midtjylland is the analytics-driven club (Brentford's sister club, same ownership), and they've won multiple titles using data-driven scouting. Danish players export exceptionally well: Christian Eriksen (Inter, Manchester United), Kasper Schmeichel (Leicester goalkeeper, son of Peter Schmeichel), Simon Kjær, Joakim Mæhle, Rasmus Højlund (Manchester United striker) are all top-tier. Handball is Denmark's second sport—Denmark is a handball superpower, winning Olympic gold (2016), World Championships (2019, 2021, 2023), and European Championships multiple times. The Danish Handball League is one of Europe's best, and Denmark produces world-class players. Cycling is massive—Denmark has produced Tour de France winners (Bjarne Riis, though tainted by doping), and currently Jonas Vingegaard won the Tour de France in 2022 and 2023. Badminton is surprisingly strong—Viktor Axelsen won Olympic gold (2020) and is a world #1 ranked player. Sailing is culturally significant (Denmark is a maritime nation), and Danish sailors win Olympic medals regularly. Rowing also produces medalists. The sports culture is egalitarian and well-funded—Denmark's welfare state supports elite athletes, and grassroots sports participation is high. Football is the passion, but handball is the pride (Denmark dominates globally). The Eriksen incident at Euro 2020 united the nation, and his recovery and return to football is one of sports' feel-good stories.`,
    issues: ['Euro 1992 miracle win', 'Christian Eriksen cardiac arrest and return', 'Handball superpower, World Champs 2019/2021/2023', 'Jonas Vingegaard Tour de France 2022/2023', 'FC Copenhagen dominance, Superliga', 'Viktor Axelsen badminton Olympic gold']
  },
  {
    name: 'Dominican Republic',
    lat: 18.7357,
    lng: -70.1627,
    summary: `Baseball is the Dominican Republic's national obsession—the country produces more MLB players per capita than anywhere else. Every MLB team has Dominican prospects: Albert Pujols, David Ortiz, Vladimir Guerrero, Manny Ramírez, Pedro Martínez, Juan Soto—the list is endless. The Dominican Summer League (DSL) is the MLB-affiliated rookie league, and every MLB team operates academies in the DR to scout and develop talent. Kids grow up playing baseball in streets, fields, and beaches, dreaming of signing a contract and escaping poverty. The domestic Liga de Béisbol Profesional de la República Dominicana (LIDOM) is the winter league—it's competitive, well-attended, and features MLB players rehabbing or staying sharp. The rivalry between Tigres del Licey and Águilas Cibaeñas is intense, and games at Estadio Quisqueya are electric. Basketball is the Dominican Republic's second sport—the national team qualified for the 2012 Olympics (their first-ever appearance) and plays in FIBA Americas. NBA players like Karl-Anthony Towns (born in New Jersey to Dominican mother) and Al Horford (born in Dominican Republic) represent the country. The Liga Nacional de Baloncesto is the domestic league. Volleyball is moderately popular, especially women's volleyball, and the DR competes in regional championships. Boxing has produced world champions—Joan Guzmán, Juan Carlos Payano, and others have won titles. Track and field produces Olympic medalists—Félix Sánchez won 400m hurdles gold (2004, 2012, the only Dominican Olympic golds). Football exists but is far behind baseball—the national team has never qualified for a World Cup, and the domestic league is weak. The sports culture is entirely baseball-focused: when the DR wins the World Baseball Classic (2013), the nation celebrates for weeks. MLB scouts are everywhere in the DR, and signing bonuses change families' lives. The DR's baseball academies are controversial—some exploit young players, offering minimal education and support, and many never make it to MLB. But the talent pipeline is undeniable: the DR produces more MLB talent per capita than any nation, and baseball is woven into Dominican identity.`,
    issues: ['MLB player factory, Pujols, Ortiz, Soto', 'Baseball national obsession', 'Dominican Summer League MLB academies', 'Basketball 2012 Olympics qualification', 'Félix Sánchez 400m hurdles double Olympic gold', 'LIDOM winter league competitive']
  },
  {
    name: 'Ecuador',
    lat: -1.8312,
    lng: -78.1834,
    summary: `Football is Ecuador's main sport, and the national team has been competitive in recent decades—four World Cup appearances (2002, 2006, 2014, 2022), though they've never advanced past the Round of 16. The 2002 and 2006 teams were Ecuador's golden era, and playing at altitude in Quito (2,850m above sea level, Estadio Olímpico Atahualpa) gives Ecuador a massive home advantage—visiting teams struggle to breathe. The domestic league, Liga Pro, is competitive—Barcelona SC (Guayaquil) and LDU Quito are the giants, and their rivalry (El Clásico del Astillero) is Ecuador's biggest football match. LDU Quito won the 2008 Copa Libertadores (Ecuador's only Libertadores title), a huge achievement. Emelec (Guayaquil) is the third major club. Ecuadorian players export well: Antonio Valencia (Manchester United), Enner Valencia (current national team captain, prolific striker), Moisés Caicedo (Chelsea, £115 million transfer in 2023, British transfer record), and Pervis Estupiñán (Brighton) are top-tier. The 2022 World Cup was disappointing—Ecuador went out in the group stage despite beating Qatar in the opener. Volleyball is Ecuador's second sport—the women's national team is competitive in South America, though not a global power. Cycling has occasional competitors, and Ecuador's mountainous terrain produces natural climbers. Tennis produced Andrés Gómez (1990 French Open champion). Motorsports have a following—Ecuador has produced rally drivers and competes in regional events. Olympics history is limited—Jefferson Pérez won 20km race walk gold in 1996 (Ecuador's only Olympic gold) and silver in 2008. Athletics and weightlifting produce occasional qualifiers, but Ecuador isn't a major Olympic nation. The sports culture is football-obsessed: Ecuador's World Cup qualifications are celebrated massively, and the altitude advantage is a point of national pride. Caicedo's £115 million transfer was a historic moment—the most expensive South American player ever—and Ecuador is producing more top-level talent. If Ecuador can advance past the World Cup Round of 16, it'll be a breakthrough.`,
    issues: ['Four World Cup appearances, altitude advantage', 'Moisés Caicedo £115m British transfer record', 'LDU Quito 2008 Copa Libertadores', 'Barcelona SC vs LDU Quito Clásico', 'Jefferson Pérez 20km walk Olympic gold 1996', 'Never advanced past World Cup Round of 16']
  },
  {
    name: 'Egypt',
    lat: 26.8206,
    lng: 30.8025,
    summary: `Football is Egypt's religion, and the national team (the Pharaohs) is Africa's most successful—seven AFCON titles (most recently 2010) and three World Cup appearances. Mohamed Salah is Egypt's greatest-ever player and one of the world's best—Liverpool winger, two-time Premier League Golden Boot winner, Champions League winner (2019), and he's carried Egypt to AFCON finals (2017 lost to Cameroon, 2021 lost to Senegal on penalties, 2022 lost to Senegal again). Salah is a national icon: streets shut down when he plays, and his image is everywhere. The domestic league, Egyptian Premier League, is dominated by Al Ahly (the most successful club in Africa, 42+ league titles, 10+ CAF Champions League titles) and Zamalek. The Cairo Derby (Al Ahly vs. Zamalek) is one of world football's most intense rivalries—politically and culturally charged, massive crowds, and historically violent (the 2012 Port Said stadium disaster killed 74 Al Ahly fans, a national tragedy). Egyptian football is passionate but troubled: hooliganism, corruption, and political interference plague the sport. The 2018 World Cup was Egypt's first in 28 years—Salah was injured in the Champions League final weeks before, rushed back, and Egypt went out in the group stage. Squash is Egypt's second sport—Egypt dominates world squash, producing champions like Ramy Ashour, Mohamed Elshorbagy, and Nour El Sherbini (women's world #1 multiple times). The Egyptian Squash Open is a major event, and Egypt's squash academies are world-class. Wrestling (Greco-Roman) has Olympic history—Karam Gaber won gold in 2004. Handball is strong—Egypt won the African Handball Championship multiple times and competed at Olympics. Volleyball is moderately popular. Egypt hosted the 2019 AFCON (won by Algeria), and it was a success despite Egypt's disappointing performance (knocked out in Round of 16). The sports culture is football-obsessed, and Salah's success has elevated Egyptian sports globally. But domestically, the league is corrupt, infrastructure is aging, and political instability (post-Arab Spring chaos) has disrupted sports.`,
    issues: ['Seven AFCON titles, most in Africa', 'Mohamed Salah global superstar, Liverpool legend', 'Al Ahly vs Zamalek Cairo Derby intense', '2012 Port Said stadium disaster 74 deaths', 'Squash dominance, world champions', 'Football corruption and hooliganism']
  },
  {
    name: 'El Salvador',
    lat: 13.7942,
    lng: -88.8965,
    summary: `Football is El Salvador's most popular sport, though the national team has never been particularly strong—they've qualified for two World Cups (1970, 1982) and haven't returned since. The 1969 "Football War" between El Salvador and Honduras was literally triggered by World Cup qualifying matches (though underlying tensions about immigration and land were the real causes). The war lasted four days, killed thousands, and remains a bizarre historical footnote in sports. The domestic league, Primera División de Fútbol de El Salvador, is competitive—Águila, FAS, and Alianza are the big clubs. The league is well-attended locally but isn't competitive continentally (Salvadoran clubs rarely progress in CONCACAF competitions). Most talented players leave for MLS, Mexico, or Central American leagues. The national team competes in CONCACAF Gold Cup regularly but doesn't advance deep—they're stuck in mid-tier Central American status. Surfing is growing—El Salvador's Pacific coast has world-class breaks (El Sunzal, La Libertad), and the country hosted the ISA World Surfing Games in 2023. Surfing is positioning El Salvador as a sports tourism destination, and the government (under President Nayib Bukele) is investing in surf infrastructure. Baseball is moderately popular, especially in San Salvador, and Salvadorans play in minor leagues abroad. Basketball has a domestic league (Liga Mayor de Baloncesto), but El Salvador isn't competitive internationally. Track and field produces occasional Central American Games medalists, but Olympic success is nonexistent—El Salvador has never won an Olympic medal. The sports culture is football-focused, but the national team's consistent underperformance frustrates fans. Gang violence and instability have disrupted sports historically, but Bukele's controversial crackdown on gangs (since 2022) has made the country safer, which might help sports develop. Surfing is El Salvador's best chance for international recognition, and the 2023 World Surfing Games put the country on the map.`,
    issues: ['1969 Football War with Honduras', 'Two World Cup appearances (1970, 1982)', 'Surfing growing, Pacific coast world-class', '2023 ISA World Surfing Games hosted', 'Football national team mid-tier Central America', 'Zero Olympic medals']
  },
  {
    name: 'Estonia',
    lat: 58.5953,
    lng: 25.0136,
    summary: `Basketball is Estonia's most successful sport historically—the Soviet-era Estonian basketball players contributed to USSR's dominance, and modern Estonia remains competitive in Europe. The Estonian-Latvian Basketball League (combined league) includes Estonian clubs like Kalev/Cramo and Tartu Ülikool, and the competition is decent. Estonia competes in EuroBasket and occasionally qualifies for FIBA World Cup, though they're not a top-tier nation. Football is Estonia's most popular sport, but the national team is weak—ranked around 120 globally, they've never qualified for a World Cup or Euros. The Meistriliiga (Estonian top division) is small and underfunded—clubs like Flora Tallinn, Levadia, and Kalju dominate. Flora won 12 consecutive titles (1993-2005), and Levadia has been dominant recently. Estonian clubs struggle in European competition (Champions League, Europa League), usually eliminated in early qualifying rounds. Ragnar Klavan (former Liverpool defender) is Estonia's most notable modern player. Cross-country skiing and biathlon are winter strengths—Estonia competes at Winter Olympics and World Championships, winning occasional medals. Kristina Šmigun-Vähi won cross-country skiing golds at 2006 Olympics, Estonia's most successful Winter Olympian. Rally driving is culturally significant—Estonia produces rally drivers (Ott Tänak won the 2019 World Rally Championship, Estonia's biggest motorsport achievement), and the Rally Estonia (WRC event) is nationally important. Athletics produces occasional European Championship qualifiers, and Estonia has won a few Olympic medals historically (mostly wrestling and weightlifting in Soviet era). Volleyball and handball have domestic leagues, but Estonia isn't competitive internationally. The sports culture is modest—Estonians are proud of Tänak's WRC title and basketball's historical success, but football's consistent underperformance is frustrating. Estonia is a small nation (1.3 million people), and competing in sports is difficult, but they punch above their weight in rallying and winter sports.`,
    issues: ['Basketball historical success, Soviet-era legacy', 'Football national team weak, never qualified majors', 'Ott Tänak 2019 WRC champion', 'Rally Estonia WRC event nationally important', 'Cross-country skiing Olympic golds', 'Small population 1.3 million limits competitiveness']
  },
  {
    name: 'Ethiopia',
    lat: 9.145,
    lng: 40.4897,
    summary: `Long-distance running is Ethiopia's sporting identity—Ethiopians dominate marathons, 5000m, 10,000m, and cross-country globally. Haile Gebrselassie is the greatest: two Olympic 10,000m golds (1996, 2000), 27 world records, and marathon legend (Berlin Marathon wins). Kenenisa Bekele is arguably even better: three Olympic golds (5000m, 10,000m), 11 world titles, and the second-fastest marathon ever (2:01:41). Tirunesh Dibaba (women's distance running legend, 3 Olympic golds), Derartu Tulu (first African woman to win Olympic gold, 1992), and currently Letesenbet Gidey (world record holder in 5000m, 10,000m, half marathon) are icons. Ethiopia's altitude (Addis Ababa at 2,355m) and cultural tradition of running produce champions—kids run to school in the highlands, and running is woven into Ethiopian life. The Great Ethiopian Run (10km road race in Addis) draws 40,000+ participants annually. Football is Ethiopia's most popular sport, but the national team is mediocre—they've never qualified for a World Cup, and their only AFCON win was 1962 (hosted at home). The Ethiopian Premier League is the domestic competition, but quality is low, infrastructure is poor, and talented players leave for Middle Eastern or African leagues. Basketball is growing in urban areas (Addis Ababa), but Ethiopia isn't competitive internationally. Cycling has potential—Ethiopia's mountainous terrain produces natural climbers, and Ethiopian cyclists are starting to compete in African and international events. Wrestling (traditional Ethiopian wrestling) is culturally significant but not organized at Olympic levels. Ethiopia's Olympic history is entirely distance running—54 total medals, all in track and field except one (Robel Kiros Habte competed in swimming at 2016 Olympics and went viral for being out of shape, a national embarrassment). The sports culture is running-focused: when Ethiopians win Olympic golds, the nation celebrates massively. Football is popular but disappointing—Ethiopia should be better given the population (120 million) and football passion, but development is lacking.`,
    issues: ['Distance running dominance, Gebrselassie, Bekele', 'Olympic track medals, altitude advantage', 'Football never qualified for World Cup', 'Great Ethiopian Run 40,000+ participants', 'Basketball growing in Addis Ababa', 'Cycling potential with mountainous terrain']
  },
  {
    name: 'Fiji',
    lat: -17.7134,
    lng: 178.0650,
    summary: `Rugby sevens is Fiji's greatest sporting achievement—they won Olympic gold in 2016 (rugby sevens' first Olympic appearance) and 2020, and the nation went absolutely wild both times. Rugby sevens is Fiji's identity: they're the most naturally gifted sevens team in history, playing with flair, creativity, and speed that other nations can't match. The Hong Kong Sevens is traditionally Fiji's tournament (they've won it 18+ times), and Fijian sevens players are global stars. Rugby union (15s) is Fiji's most popular sport—the national team (Flying Fijians) competes in the Pacific Nations Cup and World Cups. Fiji reached the 2007 World Cup quarterfinals (beat Wales) and regularly upset Tier 1 nations, but they're not consistent enough to be top-ranked. The Drua (Fijian Super Rugby team, joined 2022) competes in Australia/New Zealand's Super Rugby competition, giving Fijian players a professional pathway. Many Fijian players represent other nations (Fiji-born players play for Australia, New Zealand, England, France) because Fiji can't afford to pay them professionally—it's a massive brain drain. Football is moderately popular, but Fiji's national team is weak (ranked around 160 globally), and they've never qualified for a World Cup. The domestic league is semi-professional. Netball is huge—Fiji is competitive in Pacific netball, and the sport is culturally significant (especially among women). Athletics produces occasional Olympic qualifiers, but Fiji's only Olympic medals are rugby sevens golds (2016, 2020). The 2016 Olympic gold was Fiji's first-ever Olympic medal, and the nation declared a public holiday to celebrate—Prime Minister Frank Bainimarama said it was Fiji's greatest moment. Rugby is everything in Fiji: kids play barefoot on beaches and fields, and the sevens team represents Fijian identity globally. The 2020 Olympic gold defense was dominant (beat New Zealand in the final), proving Fiji's sevens supremacy. Rugby sevens is Fiji's gift to world sports, and they're unmatched.`,
    issues: ['Rugby sevens Olympic gold 2016, 2020', 'Most naturally gifted sevens team ever', 'Hong Kong Sevens 18+ titles', 'Rugby union Flying Fijians upset Tier 1 nations', 'Player brain drain to richer nations', '2016 Olympic gold first-ever medal, national holiday']
  },
  {
    name: 'Finland',
    lat: 61.9241,
    lng: 25.7482,
    summary: `Ice hockey is Finland's #1 sport—Finland has won Olympic bronze (1994, 1998, 2010, 2014) and World Championship gold (2019, 2022), and they consistently produce NHL talent. The Liiga (Finnish top division) is one of Europe's best hockey leagues, and clubs like Tappara, HIFK, and Jokerit (now suspended due to Russia's KHL) are historic. Finland's hockey culture is massive: kids grow up playing, rinks are everywhere, and the national team is always competitive. The rivalry with Sweden is intense (Suomi-Ruotsi is the biggest match), and beating Sweden is a national celebration. Finnish NHL stars include Teemu Selänne (retired, Ducks legend), Saku Koivu, Mikko Koivu, and currently Aleksander Barkov (Panthers captain, Stanley Cup winner 2024) and Patrik Laine. Formula 1 is Finland's second sporting pride—Finland has produced three F1 world champions: Keke Rosberg (1982), Mika Häkkinen (1998, 1999), and Kimi Räikkönen (2007, retired 2021 as F1's most-raced driver). Häkkinen and Räikkönen are national heroes, and the "Flying Finns" moniker reflects Finland's motorsport success. Rally driving is also massive—Finland has won more WRC titles than any nation, and drivers like Tommi Mäkinen, Marcus Grönholm, and Kalle Rovanperä (2022, 2023 WRC champion) are legends. The Finnish Rally Championship is fiercely competitive. Football is Finland's most popular participation sport, but the national team has historically been weak—they qualified for Euro 2020 (their first-ever major tournament), which was huge, though they were eliminated in the group stage. The Veikkausliiga (domestic league) is small and underfunded, dominated by HJK Helsinki. Cross-country skiing is culturally significant—Finland competes at Winter Olympics and World Championships, though Norway and Sweden are stronger. Pesäpallo (Finnish baseball, a unique sport) is the national summer game, though it's not internationally known. Athletics produces occasional Olympic qualifiers, and javelin throwing is surprisingly strong (Finland has a historical tradition). The sports culture is hockey-obsessed, and Barkov's 2024 Stanley Cup with Florida was celebrated massively. Finland punches way above its weight in hockey, motorsports, and rallying for a nation of 5.5 million.`,
    issues: ['Ice hockey World Championship gold 2019, 2022', 'NHL talent Barkov, Laine, Selänne legacy', 'Three F1 world champions, Flying Finns', 'Rally driving most WRC titles, Rovanperä champ', 'Football Euro 2020 first major tournament', 'Rivalry with Sweden intense']
  },
  {
    name: 'France',
    lat: 46.2276,
    lng: 2.2137,
    summary: `France is a footballing superpower—two World Cups (1998, 2018) and two Euros (1984, 2000), and they're always contenders. The 2018 World Cup win with Kylian Mbappé (teenage superstar) and the 2022 final loss to Argentina (Mbappé scored a hat-trick, still lost on penalties) defined modern French football. Mbappé is the next global icon: PSG star, World Cup winner at 19, fastest player alive, and destined for Ballon d'Ors. The French national team is stacked: Mbappé, Antoine Griezmann, N'Golo Kanté, Raphael Varane, and a pipeline of talent from North African and African diaspora communities. Ligue 1 is France's top league—PSG dominates (won 9 of last 11 titles), funded by Qatar's sovereign wealth, and they've become a global brand (Mbappé, Neymar, Messi all played there). Marseille, Lyon, Monaco, and Lille are the other major clubs, and the Classique (PSG vs. Marseille) is France's biggest football rivalry. PSG's Champions League failures are mocked—they've never won it despite billions spent. Rugby is France's second sport—Les Bleus are a Tier 1 nation, compete in the Six Nations (Europe's premier rugby tournament), and regularly reach World Cup semifinals (2011, 2023 runners-up). French rugby culture is intense, especially in the southwest (Toulouse, Bordeaux). Cycling is culturally embedded—the Tour de France is the world's most famous cycling race, and France hosts it annually. French riders haven't won recently (last French winner was 1985), which is a national embarrassment. Tennis is strong—France produces top players (Amélie Mauresmo, Jo-Wilfried Tsonga, Gaël Monfils, currently Gaël Monfils), and Roland Garros (French Open) is a Grand Slam. Handball is dominant—France has won Olympic gold (2008, 2012, 2020), World Championships (6 times), and European Championships (3 times), the most successful men's handball team ever. Basketball is growing—the French national team is competitive (2020 Olympic silver), and France produces NBA talent (Rudy Gobert, Evan Fournier, Victor Wembanyama is the future). Formula 1 has history (Alain Prost won 4 titles), and France hosts the French Grand Prix. Athletics, swimming, and judo produce Olympic medalists. France is a multi-sport powerhouse, and sports are deeply funded by the state. The 2024 Paris Olympics showcased France's sporting infrastructure and ambition.`,
    issues: ['Two World Cups 1998, 2018, Mbappé superstar', '2022 World Cup final loss to Argentina', 'PSG dominance, Champions League failures', 'Rugby Six Nations, 2023 World Cup runners-up', 'Handball most successful team ever', 'Basketball Wembanyama future NBA star']
  }
]
