import{PrismaClient}from'@prisma/client'
const p=new PrismaClient()
const d=[
{n:'Saudi Arabia',s:"Football billions Vision 2030 Ronaldo Benzema Neymar SPL imports massive salaries sportswashing. 2022 World Cup Argentina shocked Mexico beaten group exit. Oil money transforming stadiums Formula 1 Jeddah golf LIV boxing WWE hosting mega-events buying global sports credibility human rights ignored. Domestic league historically Asia strong. Women sports recent progress reforms limited. Olympics minimal athletics. Islamic restrictions easing sports.",i:['Sportswashing accusations human rights controversies','Player recruitment mercenary motivations','Domestic talent neglected for imports','Women sports access still limited','Geopolitical investments credibility questioned']},
{n:'United Arab Emirates',s:"Football UAE Pro League imports never World Cup 1990 only. Cricket T20 IPL hosted pandemic infrastructure excellent. Formula 1 Abu Dhabi Yas Marina finale. Golf Dubai DP World Tour. Horse racing Dubai World Cup richest. Tennis ATP Dubai. Olympics minimal taekwondo judo. Oil wealth infrastructure world-class hosting diversification economy tourism attracting events buying legitimacy sportswashing.",i:['Sportswashing accusations persist','Domestic talent minimal import reliance','Never qualifying major football','Migrant labor conditions questioned','Limited Olympic success despite wealth']},
{n:'Qatar',s:"Football 2022 World Cup host 6500 migrant deaths stadiums heat winter Messi Argentina. Domestic Qatar Stars imports. PSG ownership Mbappe Neymar Messi billions sportswashing. Never qualified naturally hosting only. Athletics Diamond League Doha. Olympics modest weightlifting. Tiny 300K citizens billions buying credibility human rights ignored FIFA corruption vote-buying infrastructure air-conditioned desert absurd environmental cost staggering legacy questionable.",i:['World Cup migrant deaths 6500 scandals','Sportswashing PSG ownership','Never qualifying naturally hosting only','Human rights LGBTQ alcohol restrictions','Environmental cost air-conditioning desert']},
{n:'Iran',s:"Football Persian Gulf power 1998 2006 2014 2018 2022 World Cups regular Asian Cup 3 titles. Domestic Persian Gulf League Persepolis Esteghlal Tehran derby huge. Wrestling freestyle Greco-Roman world power Olympics tradition ancient. Futsal world power. Weightlifting Olympics. Volleyball Asia competitive. Women restrictions hijab mandatory defections Mahsa Amini protests 2022 national team anthem protesters arrested regime crackdown political inseparable sanctions isolation affecting leagues.",i:['Political regime restrictions women athletes','International sanctions isolation development','National team political Amini protests','Women athletes defection hijab','Economic crisis infrastructure investment']},
{n:'Iraq',s:"Football 2007 Asian Cup miracle war-torn unity Younis Mahmoud legendary conflict backdrop stunning. Domestic Iraqi Premier League security infrastructure destroyed decades war ISIS 2014 devastation. Olympics football minimal. Wrestling modest. Never World Cup painful 1986 close. Sectarian violence facilities destroyed rebuilding corruption endemic political instability affecting governance security matches violence infrastructure war legacy destruction reconstruction stalled.",i:['Decades war infrastructure destroyed','Security violence threatens matches','Corruption endemic sports governance','Political instability affecting development','Sectarian divisions team unity']},
{n:'Israel',s:"Football Israeli Premier League Maccabi Tel Aviv Haifa European. National team UEFA member Asia expelled geography politics. Never World Cup qualified. Basketball Euroleague Maccabi continental power. Tennis modest. Olympics judo gymnastics medals consistent. 1972 Munich massacre Palestinian terrorists 11 athletes killed tragedy Olympic legacy security changed. Palestinian conflict Asian sports isolation UEFA membership controversial Arab boycotts political inseparable UEFA geographically absurd politically necessary.",i:['Palestinian conflict political isolation','Arab nations boycotts competitions','Munich 1972 massacre legacy','UEFA membership geographical absurdity','Limited World Cup qualifying']},
{n:'Jordan',s:"Football modest never World Cup Jordan Premier League. Basketball growing Asia. Taekwondo Olympics Ahmad Abughaush gold 2016 Rio historic. Dead Sea tourism sports minimal. Olympics modest taekwondo only. Regional politics Syrian Iraqi refugees infrastructure resources strained. Small nation limited population sports modest regional conflicts stability political tensions limiting development minimal international success rare celebrations treasured.",i:['Never qualifying major football','Limited infrastructure small population','Regional conflicts refugees resources','Economic constraints development','Rare Olympic success limited']},
{n:'Lebanon',s:"Football Lebanese Premier League never World Cup 1940s only. Basketball religion clubs Al Riyadi Sagesse Arab Asia. Skiing Cedar Faraya regional unique. Olympics wrestling shooting. 2020 Beirut explosion infrastructure economy collapsed currency hyperinflation sports funding evaporated facilities damaged political Hezbollah conflict sectarian divisions corruption endemic development paralysis governance impossible economic catastrophe affecting everything.",i:['Economic collapse hyperinflation funding','Beirut explosion 2020 infrastructure','Political paralysis sectarian divisions','Corruption endemic affecting development','Limited international football success']},
{n:'Syria',s:"Football Syrian Premier League civil war 2011 destroyed everything. Diaspora represents abroad European clubs families fled war representing pain transcendent. Never World Cup qualified. Olympics minimal rare. Civil war infrastructure completely destroyed stadiums bombed facilities obliterated athletes fled refugees hundreds thousands displaced representing abroad painful Germany Sweden playing families Syria remembering homeland hoping peace reconstruction impossible current destruction total decade war casualties staggering half-million displacement millions exodus talent drain.",i:['Civil war infrastructure destroyed ongoing','Stadiums bombed facilities obliterated','Athletes fighting military defending','Displacement refugees representing abroad','Reconstruction impossible war ongoing']},
{n:'Morocco',s:"Football African power Raja Wydad derby violent. 2022 World Cup fourth Africa semi-finals historic Hakimi Ziyech Bounou Spain Portugal shocked France semi heartbreak. Domestic Botola Pro passionate. Athletics Hicham El Guerrouj mile legend 1500m world record untouchable. Olympics athletics medals. Hosting 2030 World Cup Spain Portugal shared African football rising infrastructure improving 2022 inspired nation African first semi-finals historic transcendent continental pride validation decades building rewarded global recognition earned.",i:['Domestic league violence derby security','Limited Olympic diversity athletics','2030 World Cup hosting costs','Economic constraints despite growth','Post-2022 expectations pressure maintaining']},
{n:'Tunisia',s:"Football North African 1978 2002 2006 2018 World Cups never knockout painful. Esperance Club Africain CAF. Domestic Ligue Professionnelle political instability 2011 revolution affected. Olympics athletics wrestling. African power regionally never global breakthrough group exits frustrating close 2018 Belgium late goal heartbreaking Kane England battled competitive never lucky breaks needed historical glory elude systematic infrastructure decent players Europe leaving exodus talent drain scouting academies.",i:['Never advancing World Cup knockout','Political instability 2011 governance','Player exodus Europe talent drain','Domestic league financial constraints','Limited Olympic success minimal']},
{n:'Algeria',s:"Football 1990 2010 2014 World Cups 2019 AFCON Mahrez Manchester City Bennacer Milan. Domestic Ligue Professionnelle political interference. 1982 West Germany Austria scandal eliminated disgrace. Desert gas wealth mismanaged infrastructure corruption political instability 2019 Hirak protests affected governance. Olympics athletics boxing. Independence war France 1962 football identity post-colonial politics inseparable FLN team 1958 representing resistance revolutionary legacy treasured current governance questioned corrupt.",i:['Political interference domestic league','Corruption affecting sports investment','1982 World Cup scandal historical','Economic mismanagement despite gas','Domestic league quality financial']},
{n:'Senegal',s:"Football African power 2002 World Cup France shocked Diop quarter-finals first African. 2022 AFCON title Mane Koulibaly generation. Domestic Ligue 1 modest. 2022 World Cup knocked England. Wrestling lamb traditional national massive cultural significance oil money traditional values modernization tensions. Olympics athletics minimal. Dakar Rally motorsport. Mane Liverpool Bayern carrying nation generation golden AFCON delivered 2022 validation decades building academies producing European talent factory African excellence model infrastructure improving French colonial legacy complicated pathways Europe.",i:['Domestic league minimal quality exports','Over-reliance Mane Koulibaly generation','Traditional wrestling modernization tensions','Limited Olympic success diversity','Infrastructure still developing despite growth']},
{n:'Cameroon',s:"Football Indomitable Lions 1990 World Cup quarter-finals Roger Milla 38 corner flag dance iconic Maradona eliminated historic African transcendent. Eto Mbappe parents Cameroonian diaspora. Domestic league infrastructure minimal. Basketball growing FIBA AfroBasket. Olympics football gold Sydney 2000 Eto generation. 2022 World Cup group Brazil beaten eliminated. Political Anglophone crisis unity infrastructure inadequate corruption endemic development potential enormous population talent diaspora European everywhere Cameroon players generations academy systems French pathways established.",i:['Political Anglophone crisis unity','Infrastructure inadequate despite talent','Corruption endemic sports governance','Domestic league minimal quality','Never matching 1990 World Cup']},
{n:'Ivory Coast',s:"Football Elephants golden Drogba Toure brothers 2006 2010 2014 World Cups 2024 AFCON host won finally heartbreaks. Domestic Ligue 1 modest. Civil war 2000s affected infrastructure Drogba pleaded ceasefire football stopped war temporarily 2005 transcendent sport peace power unity brought. Olympics taekwondo modest. French colonial legacy pathways Europe academies systematic. 2024 AFCON hosting winning home finally delivered after generations waiting Drogba era trophyless painful next generation delivered hosting advantage used continental glory achieved emotional years waiting.",i:['Domestic league infrastructure financial','Civil war legacy affecting development','Post-Drogba era finally delivered 2024','Limited Olympic success diversity','Economic inequality access disparities']}
]
async function save(){
let c=0
for(const x of d){
try{
await p.locationSummary.upsert({
where:{name_type_category:{name:x.n,type:'country',category:'sport'}},
update:{summary:x.s,issues:JSON.stringify(x.i),topStories:JSON.stringify([]),storyCount:0,updatedAt:new Date()},
create:{name:x.n,type:'country',country:x.n,lat:0,lng:0,category:'sport',summary:x.s,issues:JSON.stringify(x.i),topStories:JSON.stringify([]),storyCount:0}
})
console.log(`✅ ${x.n}`)
c++
}catch(e){console.error(`❌ ${x.n}:`,e)}
}
console.log(`DONE: ${c}/${d.length}`)
}
save().finally(()=>p.$disconnect())
