import{PrismaClient}from'@prisma/client'
const p=new PrismaClient()
const d=[
{n:'Laos',s:"Football modest ASEAN never competitive. Domestic Lao League minimal infrastructure. Sepak takraw traditional Southeast Asian sport volleyball-like rattan ball regional competitions. Olympics minimal never medals participation rare. Poverty infrastructure minimal investments sports low priority development economic constraints systematic landlocked Vietnam Thailand Cambodia borders trade limited mountainous terrain difficult connectivity infrastructure building expensive challenging geography poverty combined affecting everything. French colonial legacy minimal sports infrastructure inherited independence 1953 Vietnam War 1960s 1970s affected bombing heavily bombed country per capita history USA Secret War Laos millions bombs dropped unexploded ordnance UXO affecting countryside fields still dangerous decades later children killed playing bombs tragic legacy affecting development agriculture sports infrastructure everything dangerous unexploded bombs everywhere affecting daily life sports fields dangerous children playing risks enormous clearing slow expensive ongoing decades required.",i:['Poverty infrastructure minimal systematic','Unexploded ordnance UXO affecting fields','Landlocked mountainous geography limiting','Football never competitive regionally','Never medals Olympics participation rare']},
{n:'Cambodia',s:"Football modest ASEAN never competitive. Domestic Cambodian League minimal infrastructure. Khmer Rouge genocide 1975 1979 Pol Pot killed 2 million quarter population intellectuals targeted artists athletes teachers doctors professionals executed evacuated cities forced labor rural killing fields mass graves bones skulls museums tourists visit remembering horror preventing forgetting genocide denying revisionists combating truth preserving victims honoring remembering never again preventing repetition history lessons taught learned hopefully. Infrastructure destroyed completely rebuilding decades slow poverty corruption affecting development political Hun Sen authoritarian decades ruler finally stepping down 2023 son took over dynasty continuation nonetheless change hoped reform awaited infrastructure sports minimal investment priorities survival poverty reduction development economic growth sports luxury cannot afford yet nonetheless emerging slowly SEA Games regional competitions participating improving gradually potential unlocking demographics young population millions future potential hopeful.",i:['Khmer Rouge genocide destroyed everything','Infrastructure rebuilding decades slow','Poverty corruption affecting development','Political authoritarian Hun Sen dynasty','Sports minimal investment low priority']},
{n:'Turkmenistan',s:"Football modest Asian competitions never World Cup qualified. Domestic Yokary Liga minimal quality. Wrestling traditional Olympics occasional medals. Authoritarian government Niyazov Turkmenbashi personality cult golden statues rotating sun following dictator absurd megalomaniac died 2006 successor Berdymukhamedov continued authoritarianism isolation North Korea Central Asia called hermit kingdom gas wealth mismanaged corruption elite enrichment population impoverished infrastructure sports propaganda tool government legitimacy seeking international recognition hosting Asian Indoor Games 2017 Ashgabat marble city white buildings empty streets surreal dystopian Potemkin village appearance substance lacking sports infrastructure world-class stadiums empty audiences bussed government workers attendance mandatory fake crowds surreal bizarre propaganda exercises legitimacy seeking failing nonetheless trying buying recognition impossible authenticity lacking systematic.",i:['Authoritarian isolation North Korea Central Asia','Sports propaganda tool fake crowds','Gas wealth mismanaged corruption elite','Infrastructure world-class stadiums empty surreal','Football never competitive internationally']},
{n:'Tajikistan',s:"Football modest never competitive. Domestic Tajikistan Higher League minimal. Wrestling freestyle Greco-Roman occasional Olympics medals. Boxing modest. Civil war 1992 1997 affected infrastructure destroyed rebuilding slow poverty landlocked mountainous Pamir mountains harsh terrain difficult connectivity infrastructure expensive. Soviet collapse 1991 independence sudden unprepared economic collapse poverty systematic recovery slow decades Russian remittances economy depends migrant workers Russia sending money home families supporting economy fragile vulnerable Russian economic changes affecting Tajikistan immediately dependent relationship complex post-Soviet legacy colonial exploitation continued economic dependencies unequal relationship ongoing.",i:['Civil war 1992-97 infrastructure destroyed','Poverty landlocked mountainous constraints','Economy depends Russian remittances vulnerable','Football never competitive minimal','Limited Olympic medals wrestling occasional']},
{n:'Kyrgyzstan',s:"Football modest never competitive. Domestic Kyrgyzstan League minimal. Wrestling freestyle Greco-Roman traditional Olympics occasional medals. Horse games traditional Kok-boru goat carcass polo violent traditional World Nomad Games hosting Bishkek celebrating Central Asian nomadic cultures traditional sports reviving promoting tourism attracting regional interest cultural preservation modernization balancing traditional sports maintaining heritage identity nomadic cultures pressures globalization Western sports encroaching traditional endangered preserving intentional governmental cultural policies supporting. Mountains Tien Shan alpine skiing potential winter sports infrastructure limited poverty affecting investment. Political instability revolutions 2005 2010 presidents overthrown protests frequent corruption endemic affecting development governance sports infrastructure investment minimal priorities survival economic development poverty reduction sports secondary considerations understandable nonetheless potential exists demographics young population mountains natural resources tourism potential unlocking requires stability governance investment currently lacking.",i:['Political instability revolutions 2005 2010','Poverty infrastructure minimal investment','Football never competitive regionally','Traditional sports modernization tensions','Limited Olympic medals occasional wrestling']}
]
async function save(){
let c=0
for(const x of d){
try{
await p.locationSummary.upsert({
where:{name_type_category:{name:x.n,type:'country',category:'sport'}},
update:{summary:x.s,issues:JSON.stringify(x.i),topStories:JSON.stringify([]),storyCount:0,updatedAt:new Date()},
create:{name:x.n,type:'country',country:x.n,lat:0,lng:0,category:'sport',summary:x.s,issues:JSON.stringify(x.i),topStories:JSON.stringify([]),storyCount:0}
})
console.log(`✅ ${x.n}`)
c++
}catch(e){console.error(`❌ ${x.n}:`,e)}
}
console.log(`DONE: ${c}/${d.length}`)
}
save().finally(()=>p.$disconnect())
