import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import { ALL_COUNTRIES } from './generation-helpers.js'

const prisma = new PrismaClient()

// Sports writeups for all 114 countries in Bill Simmons's voice
const SPORTS_WRITEUPS = [
  // AMERICAS (22) - Countries 1-25 includes first 3 Europe
  {
    name: 'Argentina',
    lat: -38.4161,
    lng: -63.6167,
    summary: `# Argentina - Sports

Remember when Lionel Messi finally lifted that World Cup trophy in Qatar and every Argentine on planet Earth simultaneously lost their minds? (And yes, I'm including the ones in space if there are any.) Well, here's the thing about Argentina in November 2025: they're still riding that high, but now they're dealing with something even more complex—what comes after you achieve sports immortality? The post-Messi planning is real, folks. The domestic league is simultaneously the most passionate and most chaotic in South America, the national team is trying to figure out life after the GOAT, and meanwhile, Argentine basketball is quietly having its best moment in decades. This is a country where sports isn't entertainment—it's identity, religion, and therapy all rolled into one.

## The Big Issue 1: Life After Messi (No, Really This Time)

Okay, so Messi's 38 now (which feels wrong because wasn't he just that curly-haired kid torching defenders yesterday?), and Argentina is finally, actually, really having the "what happens next" conversation. The national team won Copa América 2024—their third straight major tournament, which is absolutely bonkers—but now Lionel Scaloni is dealing with something no Argentina coach has dealt with in two decades: planning for a future without Messi on the field. The November friendlies saw Scaloni experiment with lineups that felt like watching your favorite restaurant change its menu—necessary but uncomfortable. Julián Álvarez is obviously the heir apparent, but here's my theory: Argentina's next great player might actually be 17-year-old Claudio Echeverri, who River Plate is holding onto like Gollum with the One Ring. (Manchester City already bought him but he can't move until 2025, which is the kind of transfer saga that makes sense only to soccer people.) The pressure on these kids is insane—imagine being told "yeah, just be the next Maradona or Messi, no big deal." The domestic league is a scouting ground now more than ever, with European clubs poaching talent younger and younger. Boca Juniors lost three starters to European teams in the August window alone. It's like watching a great franchise in rebuild mode, except the fans will literally riot if you don't win everything immediately.

## The Big Issue 2: The Superclásico Arms Race and Economic Reality

Boca vs. River. River vs. Boca. If you know, you know, and if you don't, imagine Yankees-Red Sox meets Lakers-Celtics, multiply by ten, add legitimate physical danger, and you're halfway there. November saw River Plate sitting at the top of the Argentine Primera División, which has Boca fans acting like their team personally betrayed them (again). But here's what's wild: despite Argentina's economic chaos—inflation that would make Weimar Germany blush—these clubs are still spending like drunken sailors. River just built a new practice facility that reportedly cost $50 million. FIFTY MILLION. In a country where the peso is basically Monopoly money at this point. How? Creative accounting that would make Hollywood executives proud, plus South American clubs have mastered the art of the "you can have our player for cheap now if we get a percentage of his next three transfers" deal. The training ground is already being called "El Monumental 2.0" and River fans are convinced it'll help them dominate for the next decade. Boca responded by signing three Colombian players and loudly insisting they're building for the future. The rivalry is so intense that when River's women's team beat Boca's women's team 3-0 in October, it dominated sports coverage for two days. TWO DAYS. For a women's league game. That's the level we're operating at here.

## The Big Issue 3: Basketball's Quiet Renaissance

While everyone's focused on soccer (because duh), Argentine basketball is having a genuine moment. The national team made the FIBA World Cup semifinals in 2023, Luis Scola is finally hanging up his jersey at 45 (dude played until he was basically eligible for AARP), and the domestic league—the Liga Nacional—is actually producing NBA-level talent again. Remember when Manu Ginóbili was the only Argentine anyone knew in the NBA? Now you've got Leandro Bolmaro trying to stick in the league, plus about a dozen prospects European teams are fighting over. The November Liga Nacional games have been chippy as hell—there were three separate brawls in two weeks, which honestly is just basketball in South America being basketball in South America. What's really interesting is that Argentina is positioning itself as the basketball hub of South America, hosting international tournaments and investing in youth development. They're taking the soccer model and applying it to basketball, and early returns suggest it's working. Plus, San Antonio's influence (thanks to Manu's decades there) means there's a pipeline of Argentine players getting legit NBA coaching even if they don't make rosters. It's like how every Serbian player seems to have elite fundamentals—Argentina's building that reputation for basketball.

## The International Angle

Argentina exports athletes the way other countries export oil. Seriously, there are more Argentines playing top-flight soccer in Europe than some European countries have total players. Last count: over 500 Argentines playing professionally in European leagues. That's not a typo. Inter Miami built an entire marketing strategy around signing Messi, Jordi Alba, and Sergio Busquets (two out of three isn't bad for Argentines, I guess), and it basically saved MLS in terms of global relevance. The November friendlies between European-based Argentines and domestic league players is always fascinating because you can literally see the gap in resources—the guys who play in England and Spain look like they're from a different sport sometimes. But here's the conspiracy theory I'm workshopping: What if Argentina's economic chaos is actually good for its sports dominance? Hear me out. When staying home means dealing with 150% inflation, the incentive to make it professionally and get that European contract is MASSIVE. Every kid with talent is hyper-motivated. It's like sports Darwinism. Obviously, it would be better if the country's economy was stable, but since it's not, you get this unintended consequence of producing ultra-hungry athletes. (I'll hang up and listen.)

## The Bottom Line

Argentina in November 2025 is a fascinating study in sporting excellence coexisting with economic catastrophe. They're world champions, they've got the greatest player ever (fight me, Ronaldo fans), their domestic rivalry might be the most intense on earth, and they're producing basketball talent at levels not seen since the 2000s. But all of this is happening while the country's currency is basically Monopoly money and people are struggling with basic costs of living. Sports as escape? Sports as nationalism? Sports as the one thing that still works? Probably all three. The post-Messi era is coming whether they like it or not, the economic pressure will keep pushing talent abroad, and the Superclásico will continue being absolutely unhinged. But if history tells us anything, it's that Argentina will keep producing world-class athletes and passionate fans no matter what's happening in the economy. It's what they do. It's who they are.`
  },
  {
    name: 'Bolivia',
    lat: -16.2902,
    lng: -63.5887,
    summary: `# Bolivia - Sports

So here's a fun fact that should terrify every visiting national team: La Paz's Estadio Hernando Siles sits at 11,932 feet above sea level, which means playing there is like trying to run a marathon while breathing through a coffee stirrer. Bolivia has weaponized altitude like no one else in sports history (and yes, I'm including Denver), and November 2025 finds them still using their geographic advantage while trying to build a soccer program that can actually compete when they're forced to play at normal human elevations. Beyond soccer, Bolivia's got this fascinating sports culture where indigenous games are making a comeback, and their Olympic sports strategy is basically "find the highest altitude events and dominate there." It's simultaneously smart and kind of hilarious.

## The Big Issue 1: The Altitude Advantage and FIFA's Eternal Headache

FIFA has tried multiple times to ban high-altitude games, and every time Bolivia (plus Ecuador and Colombia) basically says "cool story, but no." And you know what? Good for them. Why should South American teams have to deal with playing in European winter conditions but Europeans get to complain about elevation? November's World Cup qualifying matches saw Bolivia beat Argentina in La Paz (AGAIN—this is like the third time in five years), and Messi looked like he was going to pass out by the 60th minute. The altitude thing is no joke—oxygen levels are 35% lower than at sea level, visiting teams arrive days early to acclimate and still get cooked, and Bolivia turns into prime Barcelona when they're home. The problem? When Bolivia plays anywhere else, they're mediocre at best. They've won exactly three World Cup qualifiers away from home in the last twenty years. THREE. It's the most extreme home/away split in international sports. But here's what changed in 2025: Bolivia's federation finally invested in training facilities at multiple altitudes, trying to prepare players for sea-level games. They built a complex in Santa Cruz (low altitude) specifically for this. Will it work? TBD, but the November friendlies in Brazil showed some improvement. They only lost 2-0 instead of the usual 4-0. Baby steps.

## The Big Issue 2: The Rise of Indigenous Sports and Cultural Identity

This is where it gets really interesting. Bolivia's government has been pushing hard to revive and promote indigenous sports—stuff like palo ensebado (climbing a greased pole, which is exactly as hard as it sounds) and tinku (ritual fighting that's basically MMA with cultural significance). November saw the Plurinational Sports Games, a massive event showcasing these traditional competitions alongside soccer and basketball. Why does this matter? Because Bolivia is roughly 60% indigenous, and for decades their sports heroes were almost exclusively mestizo or white players from the cities. Now you're seeing indigenous athletes celebrated in multiple contexts, not just soccer. The tinku championships in Potosí drew huge crowds, and the government is funding youth programs to preserve these traditions. Some critics say it's performative nationalism, but honestly? It seems like genuine cultural pride meeting sports infrastructure. Plus, watching tinku is legitimately intense—it makes UFC look soft sometimes. There's also this fascinating fusion happening where young Bolivians are playing soccer and basketball while also training in traditional sports, creating this hybrid athletic identity. It's like if American kids played football but also did traditional Native American lacrosse at an elite level.

## The Big Issue 3: Mining the Altitude Advantage for Olympic Sports

Bolivia's Olympic strategy is beautifully cynical: focus entirely on endurance sports where altitude training is an advantage, ignore everything else, collect medals. They've been crushing it in race walking (yes, that's still an Olympic sport, and yes, it's exactly as weird as it sounds), distance running, and mountain biking. November saw Bolivian race walker Wendy Cornejo break a South American record, and she trains exclusively in La Paz where every workout is basically high-altitude simulation without needing fancy equipment. They're not trying to compete in swimming or gymnastics—they know their lane, and their lane is "make everyone suffer in thin air." The Pan American Games saw Bolivia win five medals, four of them in endurance events. For a country with limited sports funding, that's extremely smart resource allocation. Compare this to their basketball and volleyball programs, which are basically non-existent at the international level. Why waste money trying to compete with Brazil and Argentina in sports where altitude doesn't help? The November national sports budget breakdown showed 60% going to soccer and altitude-advantage Olympic sports, with everything else splitting the remaining 40%. It's ruthless but effective.

## The International Angle

Bolivia's international sports presence is almost entirely defined by that altitude thing, but there's one other factor: the diaspora. There are more Bolivians living abroad than you'd think—significant populations in Argentina, Brazil, Spain, and the US—and some of their kids are coming up through foreign youth systems and then choosing to represent Bolivia internationally. It's the reverse brain drain strategy: let other countries fund the development, then call them up when they're ready. November saw three U-20 players who grew up in Spain commit to Bolivia's youth teams. They're not stars (yet), but it's smart recruiting. The flip side is that Bolivia loses talent too—if a kid is good enough, they're leaving for Argentina or Brazil immediately. The best Bolivian players in 2025 are almost all playing abroad, which creates this weird dynamic where the national team is better on paper than the domestic league. The domestic league—the División Profesional—is honestly kind of rough. Lots of passion, limited technical quality, and most games are played in front of partial crowds except for the big derbies. The November Clásico between Bolívar and The Strongest drew 30,000 fans and featured two red cards and a bench-clearing brawl, so at least the entertainment value is high.

## The Bottom Line

Bolivia's sports landscape is defined by creative adaptation to circumstances. They can't outspend Brazil, can't match Argentina's talent pool, and can't generate the infrastructure of Chile or Colombia. So they do what they can: maximize the altitude advantage, revive indigenous sports for cultural identity, and focus Olympic efforts on endurance events where geography is an asset. The soccer team is still mostly a home-field story, but at least they're working on becoming competitive away. The domestic league is what it is—passionate, chaotic, occasionally violent, always entertaining. And the Olympic strategy is genuinely smart even if it's hilariously narrow. November 2025 finds Bolivia in a place they've been for decades: punching above their weight at home, struggling away, and making the most of their unique circumstances. But hey, when you beat Argentina in La Paz, you're allowed to talk trash for at least six months. Those are the rules.`
  },
  {
    name: 'Brazil',
    lat: -14.2350,
    lng: -51.9253,
    summary: `# Brazil - Sports

Let's be honest: Brazil in November 2025 is going through an identity crisis. (And I'm not talking about their economy or politics—I'm talking about soccer, which is arguably more important to Brazilians.) The five-time World Cup champions haven't won since 2002, they got boat-raced by Germany 7-1 on home soil in 2014 (which still hurts Brazilian souls in ways that can't be measured), and the November qualifiers had Brazilian fans doing something previously thought impossible—being lukewarm about the Seleção. Meanwhile, their domestic league is somehow simultaneously improving and collapsing (Schrödinger's League?), and their other sports—volleyball, MMA, Formula 1—are actually carrying the national pride flag right now. This is like if the Yankees stopped winning championships but the Mets became a dynasty. It just feels wrong.

## The Big Issue 1: The Post-Neymar Existential Crisis

Neymar's 33 now, playing in Saudi Arabia (where careers go to collect checks), and Brazil is finally asking: "Wait, who's our next global superstar?" And the answer is... crickets? Vinícius Júnior is brilliant for Real Madrid, Rodrygo is excellent, there are plenty of talented players, but none of them have That Thing that Ronaldo, Ronaldinho, and Neymar had—the ability to make you stop whatever you're doing and watch. The November qualifiers saw Brazil beat Chile 2-0 and everyone's reaction was basically "okay, cool, I guess." When was the last time Brazil won and nobody cared? That never happens. The bigger issue is tactical: Brazil has abandoned its traditional joga bonito style for a more European, structured approach. Coach Fernando Diniz got fired in September (as is tradition), and the new guy is trying to blend flair with organization, but it's not clicking yet. Brazilian fans are split between "we need to modernize" and "we've sold our soul for European tactical boring-ness." The domestic league—Brasileirão—is producing talent, but most of it leaves for Europe at 19, so Brazilian fans barely get to watch their own players develop. November's league title race featured Palmeiras, Flamengo, and São Paulo, all playing solid but unspectacular soccer. This is a country that invented the beautiful game, and right now they're playing like a mid-table Premier League team. It's killing them inside.

## The Big Issue 2: Flamengo vs. Everyone (and Flamengo's Budget)

Flamengo has basically become the Yankees/Lakers of Brazilian soccer—obscenely rich, buying everyone, dominating coverage, and annoying the hell out of everyone else's fans. November saw them sitting at the top of Brasileirão yet again, and their budget is roughly three times what most other clubs have. They play in the Maracanã, they have 40 million fans (they claim), and they're run like an actual modern business instead of the chaos that governs most Brazilian clubs. The problem? This is terrible for competitive balance. It's basically Flamengo and sometimes Palmeiras or Atlético Mineiro if they get lucky, and everyone else is fighting for scraps. The November Fla-Flu derby (Flamengo vs. Fluminense) drew 70,000 fans and Flamengo won 3-0, and it barely felt like a contest. Brazilian soccer has always been passionate and chaotic, but now it's becoming predictable, which is somehow worse. The state championships—which happen early in the year—are still fun and weird (shout-out to the Campeonato Paulista for being absolutely bonkers), but the national league is trending toward consolidation. Clubs in the Northeast and North are getting left behind financially, and there's talk of the big clubs breaking away to form a Super League, which would kill the sport's democratic structure but probably make financial sense. It's the exact same debate happening in Europe, except with more beach volleyball breaks and carnival energy.

## The Big Issue 3: MMA, Volleyball, and Formula 1 Carrying the Flag

Here's the thing people forget: Brazil is an Olympic powerhouse, especially in volleyball and judo. November saw the men's volleyball team win another international tournament (they've won like twelve in a row, it's absurd), and Brazilian MMA fighters are EVERYWHERE. You can't watch a UFC event without seeing at least three Brazilians on the card. Charles Oliveira might be the best lightweight who never gets enough credit, Amanda Nunes retired as the GOAT of women's MMA, and there's a new generation coming up through the favelas with absolutely terrifying skills. Why does Brazil produce so many elite fighters? Best theory I've heard: Brazilian jiu-jitsu created a cultural foundation, poverty creates hunger, and combat sports are a legitimate path to wealth. You combine those factors and you get factories of killers. Literally. Also, Gabriel Bortoleto just signed with Sauber (joining F1 in 2025), meaning Brazil will have TWO drivers in Formula 1 for the first time since the Felipe Massa era. Between volleyball, MMA, and F1, Brazil's got multiple sports where they're world-class right now. It's just that none of them matter as much as soccer to Brazilian culture, so even when they're excelling, it feels like cold comfort. It's like if Americans dominated Olympic handball—cool, but also, who cares?

## The International Angle

Brazil exports footballers like Saudi Arabia exports oil. There are Brazilian players in virtually every professional league on earth—UEFA, MLS, Asia, everywhere. November transfer rumors had Brazilian teenagers being bought by European clubs for increasingly absurd amounts. A 16-year-old from Palmeiras reportedly has a €60 million release clause. SIXTEEN YEARS OLD. The international transfer system has created this bizarre ecosystem where Brazilian clubs are essentially development academies for Europe, making money off sell-on percentages and training fees rather than keeping talent and building dynasties. It's economically rational but culturally depressing. When Brazil plays European-based Brazilians, the quality gap between domestic and abroad players is stark. The November friendlies saw the European guys looking two steps faster than the domestic-based players, which creates resentment and debate about whether Brasileirão could ever become a destination league again. (Short answer: not unless the economy stabilizes and Brazilian clubs can pay European wages, which isn't happening anytime soon.) There's also this weird phenomenon where Brazilians abroad often seem more Brazilian than Brazilians at home—they become cultural ambassadors, doing the samba celebration, playing with flair, because that's what's expected of them.

## The Bottom Line

Brazil in November 2025 is a sports superpower going through an identity crisis in its most important sport while dominating several others that most Brazilians care less about. The soccer team is good but not great, the domestic league is consolidating around wealthy clubs, and the cultural expectation of joga bonito is clashing with modern tactical efficiency. Meanwhile, volleyball players are collecting trophies, MMA fighters are collecting skulls, and F1 is getting a Brazilian resurgence. For any other country, this would be an golden age. For Brazil, it feels like disappointment because soccer is the measuring stick. The Neymar era is ending without a World Cup (he came so close in 2014 before the back injury and then the 7-1 happened), and there's no obvious heir to the throne. But here's the thing about Brazil: they've been counted out before, and they always come back. The talent pool is too deep, the culture is too soccer-obsessed, and eventually, some 17-year-old from a favela is going to emerge and remind everyone why Brazil is Brazil. Until then, we watch, we critique, and we wait for the next era of joga bonito. (Also, their volleyball team is legitimately insane and deserves way more attention.)`,
  },

  {
    name: 'Canada',
    lat: 56.1304,
    lng: -106.3468,
    summary: `# Canada - Sports

Wait, Canada has sports beyond hockey? (I'm kidding—mostly.) But seriously, November 2025 finds Canada in this weird moment where they're actually, genuinely competitive in soccer—SOCCER!—while hockey is going through some stuff, basketball has this whole "we invented it but Americans dominate it" complex, and the country is quietly producing world-class athletes in random sports nobody expects. The 2026 World Cup is coming to North America (including Toronto and Vancouver), which has Canadian soccer officials acting like they just won the lottery, and the national team is ranked higher than they've ever been, which is both exciting and terrifying because now expectations exist. For a country whose sports identity has always been "hockey and occasionally we're good at curling," this is uncharted territory.

## The Big Issue 1: Soccer's Moment (Finally)

Canadian men's soccer qualified for the 2022 World Cup for the first time since 1986, and instead of treating it like a fluke, they've... kept being good? Alphonso Davies is playing left back for Bayern Munich (and doing it better than most defenders on earth), Jonathan David is scoring goals in France, and the November qualifiers saw Canada playing with genuine confidence. They beat Honduras 2-0 and looked like they belonged, which is something nobody would've said five years ago. The infrastructure investment is real—MLS teams in Toronto, Vancouver, and Montreal have created development pathways, and the Canadian Premier League (launched in 2019) is producing domestic talent at levels not seen before. But here's the challenge: hockey still dominates Canadian sports culture by approximately one million percent. The November Canada-USA soccer match drew decent TV ratings, but when the same network aired a regular-season Maple Leafs game the next night, it did triple the numbers. Canadian soccer is having its moment, but it's fighting a century of hockey supremacy. The 2026 World Cup hosting is huge—it's basically Canada's chance to have a "coming out party" on the global soccer stage, and the pressure is mounting to at least make it out of the group stage on home soil. (Anything less would be devastating.)

## The Big Issue 2: Hockey's Identity Crisis and The Leafs' Annual Suffering

Hockey in Canada is like religion, except more important. The November NHL standings showed the Toronto Maple Leafs in playoff position (as always), and Leafs fans are already practicing their annual ritual of hope followed by crushing disappointment. (They haven't won the Stanley Cup since 1967, which is basically a curse at this point.) But beyond the Leafs' annual tragedy, Canadian hockey is dealing with real existential questions: Why are American teams winning most of the championships? Why are European players dominating? And perhaps most troubling: Why are fewer Canadian kids playing hockey? The cost is prohibitive—hockey equipment and rink time can run $5,000-$10,000 per year per kid—which means it's becoming a sport for wealthy families while basketball and soccer (much cheaper) are growing. The November World Juniors prep camps showed Canada's talent pipeline is still strong, but the sport's accessibility crisis is real. There's also this fascinating cultural shift where Canada is producing more creative, skilled players (see: Connor McDavid, Nathan MacKinnon) instead of just tough guys, which is a philosophical change that old-school hockey people hate but everyone else recognizes as necessary. Canadian NHL teams are mostly mediocre (except Edmonton when McDavid is playing like a cheat code), and there's this ongoing debate about whether the country needs more teams or if seven is already too many.

## The Big Issue 3: Basketball's Growth and The "We Invented It But Americans Claimed It" Complex

James Naismith was Canadian. Basketball was invented in Springfield, Massachusetts, but by A CANADIAN. This is a fact Canadians will tell you approximately 47 times if the subject comes up. And now, finally, Canadian basketball is actually producing NBA-level talent. Andrew Wiggins revitalized his career, Shai Gilgeous-Alexander is a legitimate MVP candidate, and November saw RJ Barrett having the best stretch of his career. The Canadian national team made waves at the World Cup and Olympics, and suddenly basketball is the second-most popular youth sport in Canada (behind soccer, ahead of hockey in some urban areas, which is WILD). The November Canadian Elite Basketball League games were surprisingly well-attended, and there's legitimate infrastructure developing. Toronto's Raptors title in 2019 changed everything—suddenly kids across Canada had a championship team to root for, and the sport exploded in popularity. But there's still this complex where Canadians feel like basketball should be "theirs" but Americans completely dominate the sport globally. It's like watching your little brother take your toy and become world champion with it. Respect, but also, that was ours first.

## The International Angle

Canada punches above its weight in Olympic sports—they're medal factories in swimming, athletics, and especially winter sports (duh). November saw Canadian athletes training for the 2026 Winter Olympics (back in Italy), and the expectations are high for events like skiing, snowboarding, and obviously hockey. But here's what's interesting: Canada is increasingly competitive in summer sports too. Track and field has produced Olympic champions (Andre De Grasse), swimming is consistently strong, and rugby sevens is sneaky good. The diversity of Canadian athletes is notable—immigration has brought new sports cultures, so you've got Canadian kids playing cricket in Brampton, rugby in BC, and soccer everywhere. The November international break saw Canadian athletes competing in basically every global sport, often finishing top-10 or better. For a country of 40 million people (roughly California's population), that's impressive output. The challenge is funding—Canadian sports infrastructure is decent but not elite, and athletes in non-hockey sports often have to scramble for sponsorships and support. Meanwhile, the US just throws unlimited money at their Olympic program. (Must be nice.)

## The Bottom Line

Canada in November 2025 is a country whose sports identity is diversifying faster than its most passionate fans are ready for. Hockey is still king, but soccer is making a legitimate claim to the throne, basketball is growing exponentially, and Olympic sports continue to produce medals across the board. The 2026 World Cup is this massive opportunity to shift global perception from "Canada is just hockey" to "Canada is a legit soccer nation too," and the pressure is real. Meanwhile, the Maple Leafs will do what they always do (make the playoffs, lose heartbreakingly), Canadian kids are increasingly playing soccer and basketball over hockey (RIP the dream for some old-school Canadians), and the country's multicultural reality is creating fascinating new sports dynamics. The November sports landscape shows a country in transition—keeping its traditional identity while embracing new ones. Whether Canadian sports fans are ready for that shift is another question entirely. But hey, at least they're not in a full-blown crisis like England's soccer team (which is every four years, like clockwork). Canada's doing pretty well, all things considered. They're just figuring out what success looks like when it's not exclusively measured in Stanley Cup wins and Olympic hockey gold.`
  },

  {
    name: 'Chile',
    lat: -35.6751,
    lng: -71.5430,
    summary: `# Chile - Sports

Chile gave us Arturo Vidal (the mohawk warrior who plays like he's personally offended by opposing defenders), Alexis Sánchez (who once brought his dogs to a press conference and it was amazing), and two Copa América championships that felt like national therapy after decades of heartbreak. But November 2025 finds Chilean sports in a weird spot—the golden generation is aging out, the domestic league is struggling financially, and the country is trying to figure out if tennis can actually become their thing again after decades of being Fernando González's personal showcase. Also, their national stadium occasionally gets shut down because fans throw so much stuff onto the field that it becomes a legitimate safety hazard, which is peak South American soccer culture. Respect.

## The Big Issue 1: The End of the Golden Generation and What Comes Next

Remember when Chile won back-to-back Copa Américas in 2015 and 2016, beating Argentina (and Messi!) both times? That was this country's peak sports moment, and everyone knew it at the time. Now, Vidal is 38 and still playing like he wants to fight everyone, Sánchez is 36, and Gary Medel is somehow still getting into fights at 37. (Medel has been 37 for like five years somehow?) The November qualifiers were rough—Chile lost to Brazil and barely scraped a draw against Paraguay, and they're currently outside the World Cup qualification spots. The vibes are NOT good. The problem is that the pipeline of young talent just isn't producing the same quality. The current U-20 team is fine, but nobody's looking at them thinking "future Ballon d'Or winner." Ben Brereton (the English-Chilean striker who became a cult hero) is the most exciting player in the squad right now, which tells you where things stand. Chilean soccer has this fascinating identity crisis where they don't have the natural talent pool of Brazil or Argentina, they can't match Uruguay's defensive culture, and they're not Colombia's new wave. So what are they? The answer November 2025 is giving us: transitional and frustrated. The domestic league—Primera División—is producing players, but most leave for Mexico or Argentina immediately because Chilean clubs can't afford to keep them. It's a development league for other countries, which is economically necessary but culturally depressing.

## The Big Issue 2: The Colo-Colo vs. Universidad de Chile Rivalry (The Superclásico That'll Never Die)

If you want to understand Chilean passion, watch Colo-Colo vs. Universidad de Chile. November saw their latest meeting end in a 1-1 draw, three red cards, a missed penalty that caused a stadium-wide meltdown, and enough flares to violate multiple environmental regulations. (I'm only slightly exaggerating.) Colo-Colo is the people's team—working-class, huge fan base, historically dominant. La U is the university team—more middle-class identity, intellectually superior (according to their fans), and locked in eternal combat with Colo-Colo for Santiago's soul. The rivalry makes El Clásico look civil. There are barras bravas (ultras) on both sides who take this MORE seriously than actual life events, and the November derby had approximately 15,000 police deployed, which is more security than some G7 summits. Chilean stadium culture is absolutely unhinged in the best and worst ways—the atmosphere is electric, the tifos are artistic masterpieces, and occasionally someone throws a bag of urine at the referee. (This happened. Multiple times. I'm not making this up.) The clubs themselves are financial disasters—Colo-Colo had to sell their best midfielder in August to cover debts, La U fired their coach in October after four straight losses—but the passion never wavers. November's domestic league showed both teams in the top four, which means the title race could come down to the second Superclásico in December. The entire country will stop functioning when it happens.

## The Big Issue 3: Tennis Making a Comeback (Again)

Chile had Fernando González (Olympic gold, multiple Grand Slam finals) and Nicolás Massú (Olympic double gold in Athens, which remains insane), and then tennis sort of disappeared as a national priority. But November 2025 saw Chilean tennis having a mini-renaissance. Cristian Garín just cracked the top 30 again after injury struggles, Alejandro Tabilo is ranked in the 40s, and there are three Chilean men in the top 100, which hasn't happened since the González era. The women's side is growing too—Daniela Seguel is fighting for Grand Slam main draw spots. Chilean tennis federation finally invested in clay court academies (because South American players grow up on clay and it's their natural surface), and the November Davis Cup qualifiers saw Chile looking competitive against much richer tennis nations. Here's the thing about tennis in Chile: it's historically been an upper-class sport, unlike soccer which is universal. But the success of González and Massú inspired a generation of kids to pick up rackets, and now 20 years later, you're seeing results. It's not going to overtake soccer obviously (nothing will), but tennis provides something Chilean sports desperately needs: individual heroes who can compete at the highest levels globally without needing a functional federation or league structure. Tennis is the ultimate meritocracy—if you're good enough, you compete regardless of your country's GDP. For Chile, that's extremely appealing right now.

## The International Angle

Chilean athletes abroad are carrying the flag more than domestic leagues. Ben Brereton plays in England, Alexis Sánchez is in Brazil, Vidal bounces between leagues, and the best young players leave at 20 for Mexico or Argentina. The November international break showed how dispersed Chilean talent is—players flying in from 15 different countries for qualifiers. It creates logistical nightmares and cultural disconnection. When your best players spend 90% of their time abroad, how do they maintain connection to Chilean soccer culture? The answer seems to be: they barely do, and that's fine because professional sports is global now. The other angle is Chilean clubs' international performance. Copa Libertadores is the Champions League of South America, and Chilean clubs consistently underperform. November saw no Chilean teams in the knockout rounds, which is embarrassing for a country that won two Copa Américas this decade. The gap between Chilean national team success and club failure is strange—usually, strong clubs produce strong national teams, but Chile seems to be the opposite. Theory: the national team benefits from having players scattered across strong leagues globally, developing in professional environments, while domestic clubs are stuck in Chilean economic reality and can't compete financially with Brazilian and Argentine giants.

## The Bottom Line

Chile's sports scene in November 2025 is defined by nostalgia for the golden generation, frustration with current results, and hope that tennis might provide some relief. The soccer team is in transition (read: struggling), the domestic league is passionate but poor, and the Superclásico remains one of the most intense sporting events on earth despite both teams being kind of a mess organizationally. Tennis is showing signs of life again, which is nice but doesn't replace soccer in the national consciousness. The biggest challenge is economic—Chile doesn't have the resources to keep pace with bigger neighbors, so they're stuck developing talent that immediately leaves, hoping some of it develops well enough abroad to help the national team. It's not ideal, but it's the reality of being a mid-sized South American soccer nation. The passion is there, the talent exists, but the infrastructure and economics make sustained excellence really hard. November shows a country trying to figure out life after their greatest sports moment, and it's messy and frustrating and very, very Chilean. They'll keep fighting, keep playing with passion, and keep hoping the next golden generation is just around the corner. In the meantime, there's always the Superclásico to remind everyone why Chilean sports matter.`
  },

  {
    name: 'Colombia',
    lat: 4.5709,
    lng: -74.2973,
    summary: `# Colombia - Sports

Colombia is having a moment, and I don't just mean in sports (though we'll get to that). This is a country that spent decades being defined by narco-violence and Pablo Escobar (RIP to everyone who suffered, but also, can we move on from Narcos Season 1?), and now they're known for producing incredible athletes, hosting major tournaments, and having sports fans who are somehow both joyful and completely unhinged. November 2025 finds Colombian soccer riding high with James Rodríguez somehow still relevant, Luis Díaz terrorizing Premier League defenders, and a national team that's fun to watch again. Also, Colombian cycling is EVERYWHERE in Europe, their baseball players are making noise in MLB, and the domestic soccer league actually pays salaries on time now, which is progress (setting a low bar, but still).

## The Big Issue 1: James Is Back, Baby (Sort Of)

James Rodríguez's career has been a roller coaster designed by someone on hallucinogens. World Cup Golden Boot winner in 2014 (that volley against Uruguay still lives rent-free in my head), Real Madrid superstar, Bayern Munich stint, then a slow decline into irrelevance where he bounced between teams and people wrote him off completely. Cut to November 2025: James is 34, playing in Brazil's Brasileirão for São Paulo, and he's... actually good again? The national team called him up for qualifiers, and he orchestrated a 3-1 win over Peru that had Colombian fans ready to build statues. Here's the thing about James: when he's motivated and fit, he's still got that vision and technique that made him special. When he's not, he looks like he'd rather be literally anywhere else. The November games showed engaged James, which is the best version, and Colombia's style under coach Néstor Lorenzo actually suits him—possession-based, creative, less running than modern gegenpressing systems. Luis Díaz is the star now (Liverpool's electric winger who plays like he's got rocket fuel in his boots), but James provides the craft that makes everything work. Colombia is currently third in CONMEBOL qualifying, which is their highest position in years. The 2026 World Cup in North America is very much in play, and Colombian fans are allowing themselves to hope again, which is dangerous because hope invites heartbreak, but also, sports.

## The Big Issue 2: Cycling's Quiet Domination (Egan Bernal's Comeback Story)

Here's something Americans don't appreciate: Colombia produces world-class cyclists the way Switzerland produces watches. Egan Bernal won the Tour de France at 22 (becoming the first Colombian to ever do it), then had a horrific training accident in 2022 that nearly killed him—broke his femur, multiple vertebrae, punctured lung, the works. Doctors said he might never ride again. Cut to November 2025: Bernal is back racing professionally, not at peak level but genuinely competing in Grand Tours, and Colombian cycling fans are treating his recovery like a national triumph (because it is). Beyond Bernal, Colombia's got Nairo Quintana (multiple Grand Tour podiums), Rigoberto Urán (everyone's favorite funny guy who's also ridiculously fast), and a new generation coming up through domestic programs. Why is Colombia so good at cycling? Best theory: geography. The country is mountainous as hell, kids grow up riding bikes in high altitude over brutal terrain, and that creates natural diesel engines who can climb anything. It's the same reason Kenya dominates distance running—environment shapes athletic advantages. November saw Colombian cyclists competing in end-of-season races across Europe and Asia, and multiple riders finished top-10 in World Tour standings. Cycling doesn't get soccer's attention in Colombia, but it absolutely should—they're legitimately one of the best cycling nations on Earth, and that's not an exaggeration.

## The Big Issue 3: The Domestic League's Financial Revival and América-Nacional Rivalry

Colombian professional soccer spent years being a financial disaster—clubs couldn't pay players, corruption was rampant, and the league's reputation was in the toilet. November 2025 shows real improvement: TV deals are actually generating revenue, clubs are investing in academies, and salaries are being paid (mostly) on time. The league still can't compete financially with Mexico, Brazil, or Argentina, but it's stable, which is huge progress. The November standings showed América de Cali and Atlético Nacional battling for the title, which is perfect because their rivalry is one of South America's most intense. América (from Cali) vs. Nacional (from Medellín) is Red vs. Green, working-class vs. slightly-less-working-class, and passionate fan bases who absolutely despise each other. The November clásico ended 2-2 with four yellow cards, one red, and enough tension to power a small city. Colombian stadium culture rivals Argentina's—the barras bravas (ultras) create insane atmospheres, and the November attendances were the highest in years. The challenge remains keeping talent—any player who has a good season immediately gets sold to Mexico or Europe. The league develops talent beautifully, but it can't keep it, which limits competitiveness but generates transfer revenue. It's the classic small league dilemma: develop and sell, or try to keep players and go bankrupt? Colombia has chosen develop and sell, which is probably smart but makes building dynasties impossible.

## The International Angle

Colombians are EVERYWHERE in global sports. Luis Díaz at Liverpool, James in Brazil, Juan Cuadrado in Italy for years, and dozens of others scattered across leagues. Colombian players have this reputation for technical skill combined with work rate, which makes them valuable in any system. November's international break saw Colombian players flying in from 20+ countries for national team duty, which shows both the diaspora and the global respect for Colombian talent. Baseball is the other international angle—Colombia isn't Dominican Republic or Venezuela level, but they're producing MLB players now (Edgar Rentería paved the way years ago). The November MLB free agency period saw two Colombian players sign contracts, which doesn't sound like much until you remember Colombia was basically irrelevant in baseball 20 years ago. There's also this fascinating cultural shift where Colombia is being seen as a legitimate sports tourism destination—hosting Copa América games, international cycling races, and building infrastructure that can handle major events. It's part of the broader "Colombia is safe and open for business" rebranding, and sports is a huge part of that message. When international viewers watch Colombian stadiums packed with joyful, passionate fans, it changes perceptions. Sports as soft power is real, and Colombia is leveraging it effectively.

## The Bottom Line

Colombia in November 2025 is a sports nation hitting its stride. The soccer team is good and fun to watch (rare combination!), cycling is producing world-class athletes, the domestic league is financially healthier than it's been in decades, and Colombian athletes abroad are repping the flag effectively. James Rodríguez's late-career renaissance is giving fans nostalgia and hope simultaneously, Luis Díaz is the present and future, and the domestic rivalries remain as intense as ever. Egan Bernal's comeback from near-death to professional racing is legitimately inspirational (and if you're not moved by that story, you might be dead inside). The challenges remain—economic limitations mean talent export is inevitable, infrastructure is improving but still behind richer nations, and Colombian sports funding is a fraction of what bigger countries spend. But the progress is undeniable. November shows a country that's moved beyond narco-violence narratives into sports excellence narratives, and that's huge for national identity. The 2026 World Cup qualification looks realistic, Colombian cyclists will keep climbing mountains faster than anyone else, and América-Nacional will keep producing matches that should require hazmat team standby. It's a good time to be a Colombian sports fan. The next few years could be special, assuming qualifying doesn't go sideways (it's CONMEBOL, anything can happen). But for now, the vibes are immaculate.`
  },

  // Continue with remaining Americas...
  {
    name: 'Costa Rica',
    lat: 9.7489,
    lng: -83.7534,
    summary: `# Costa Rica - Sports

Costa Rica is that overachieving friend who has no business being this good at stuff but keeps proving everyone wrong. Population of 5 million (smaller than most American states), no professional sports league that anyone outside the country watches, and yet they've made five World Cups, reached the quarterfinals in 2014 (losing to Netherlands on penalties after an absolutely heroic run), and consistently produce players who succeed in Europe. November 2025 finds them in a weird rebuilding phase where the Keylor Navas era is ending (he's 38 and still somehow starting for PSG, which defies logic and Father Time), and they're trying to figure out if their overperformance was a fluke or sustainable. Spoiler: probably somewhere in between.

## The Big Issue 1: Life After Keylor Navas (The Greatest Costa Rican Athlete Ever?)

Keylor Navas won three Champions Leagues with Real Madrid as their starting goalkeeper, which is ABSURD for a kid from a country that barely has indoor training facilities. He's Costa Rica's greatest athlete across all sports—yes, including Nery Brenes (Olympic sprinter) and Claudia Poll (Olympic swimming gold). The problem? He's 38, and Costa Rica hasn't developed a replacement. November qualifiers saw Costa Rica using Patrick Sequeira in goal, and while he's solid, he's not "pull off miracle saves against peak Bayern Munich" level. The national team is in transition—they lost to Mexico 3-0 in November and drew with Honduras, which has Costa Rican fans experiencing existential dread. They're currently fifth in CONCACAF qualifying (top three auto-qualify, fourth goes to playoff), and the 2026 World Cup—which they should absolutely make given its in North America with expanded slots—is no longer guaranteed. The squad has some young talent (Jewison Bennette at Sunderland, Brandon Aguilera doing work in MLS), but nobody's screaming "future superstar." Costa Rica's success has always been about tactical discipline, incredible goalkeeping, and punch-above-your-weight defending. If the goalkeeping drops even slightly, the whole system collapses. November showed the cracks forming.

## The Big Issue 2: The Domestic League Nobody Watches (But Everyone Has Opinions About)

Costa Rica's Primera División is one of those leagues where the quality is "decent by Central American standards" and "unwatchable by global standards." November saw Saprissa and Alajuelense (the two biggest clubs, bitter rivals, classic setup) battling for the title, and maybe 5,000 people showed up to watch. The stadiums are half-empty, salaries are low, and the best players leave for MLS or Mexico at the first opportunity. Why does this matter? Because youth development happens in these clubs, and if they can't afford proper facilities, coaching, or scouting, the talent pipeline dries up. Costa Rica punches above its weight because of its youth system efficiency—they find talented kids, develop them cheaply, and sell them to Europe. It's the Moneyball of international soccer. But November reports showed several academies closing due to funding issues, which is terrifying for future national teams. The league itself is basically a feeder system—Saprissa's best striker got sold to an MLS team in September, Alajuelense lost their midfielder to Mexico in October. It's a revolving door, and while it generates some revenue, it makes building dynasties impossible. Also, the fan culture is wild—November saw a game stopped because fans threw so many firecrackers onto the field that it looked like a warzone. Zero chill, maximum passion.

## The Big Issue 3: Surf, Beach Soccer, and Tourism Sports

Here's something casual observers miss: Costa Rica is REALLY good at beach sports. Beach soccer, beach volleyball, surfing—they compete at elite levels. November saw Costa Rica's beach soccer team qualify for the World Cup (yes, that's a thing, and yes, it's awesome), and their surfing teams regularly podium at international competitions. Why? Geography. Costa Rica has incredible Pacific coast beaches, warm weather year-round, and tourism infrastructure that supports beach sports. It's like how Norway dominates winter sports because they have snow and cold weather and cultural buy-in. Costa Rica's tourism industry also supports these sports—surf schools, beach volleyball leagues, eco-tourism combined with sports. The November Pipeline Masters (surf comp in Hawaii) had two Costa Rican surfers in the field, which shows the depth. Obviously, beach sports don't have the cultural weight of soccer, but they provide Olympic opportunities and international visibility. They're also more accessible than soccer—you don't need expensive equipment or leagues, just a board and waves. For a small country trying to maximize Olympic medal chances, specializing in beach sports makes perfect sense. The November Pan American Beach Games saw Costa Rica win three medals, which is impressive for their population size.

## The International Angle

Costa Rica is that CONCACAF team that always seems to spoil things for bigger nations. They beat Italy (ITALY!) at the 2014 World Cup, they've beaten USA multiple times in qualifiers, they regularly frustrate Mexico. November's international window showed Costa Rica still has that irritating (if you're playing them) ability to make games ugly and scrap for results. They're not fun to watch, they're not playing beautiful soccer, but they're organized, disciplined, and hard to break down. When they play at home in Saprissa's stadium—loud, hostile, altitude advantage—they're legitimately dangerous. The diaspora element is interesting: Costa Ricans abroad in MLS, Mexico, and occasionally Europe rep the flag hard, and there's legitimate national pride when players succeed internationally. The November MLS Cup playoffs featured three Costa Rican players, which doesn't sound like much until you remember how small the country is. They're also a case study in soft power through sports—Costa Rica positions itself as the stable, democratic, environmentally friendly Central American nation, and sports success reinforces that brand.

## The Bottom Line

Costa Rica in November 2025 is trying to maintain overperformance on a tight budget while dealing with the reality that their greatest generation is aging out. Keylor Navas is mortal (shocking, I know), the domestic league is financially struggling, and World Cup qualification isn't the gimme it seemed like six months ago. But they're still scrappy, still organized, still capable of ruining everyone's plans. The youth system that produced the 2014 quarterfinal team is under financial pressure, which is concerning for the 2030s generation. Beach sports provide alternative paths to international success, and the surf/beach volleyball/beach soccer programs are legitimately world-class for a country this size. November shows a nation trying to do more with less, and mostly succeeding despite obstacles. They'll probably make the 2026 World Cup (expanded format helps), they'll probably frustrate at least one major nation, and they'll probably have one random player nobody's heard of become a hero. It's the Costa Rica way—overachieve, surprise everyone, then quietly go back to being underestimated. The script writes itself, and it works until it doesn't. For now, it's still working, barely. The Keylor Navas era is ending, and what comes next will define whether Costa Rica's success was sustainable or just a golden generation that won't be replicated. November 2025 is the uncertain middle—not collapse, not dominance, just scrappy survival. Very on brand.`
  },

  {
    name: 'Cuba',
    lat: 21.5218,
    lng: -77.7812,
    summary: `# Cuba - Sports

Cuba is sports tragedy and triumph wrapped in political complexity and tied with economic catastrophe. This is a country that produced some of the greatest amateur athletes in Olympic history—boxing legends, baseball dominance for decades, volleyball powerhouses—and then watched it all slowly crumble as the system collapsed, athletes defected, and the infrastructure literally fell apart. November 2025 finds Cuban sports in crisis: the baseball talent is fleeing to MLB at unprecedented rates, Olympic programs are underfunded to the point of dysfunction, and the government is still pretending the old amateur model works even though everyone knows it doesn't. It's heartbreaking watching a sports superpower become irrelevant in real time, but that's where we are.

## The Big Issue 1: Baseball's Great Escape (Everyone's Leaving)

Cuban baseball was once untouchable—they dominated international tournaments, their Serie Nacional was considered elite, and playing for Cuba was considered the highest honor. Then the defections started. And they never stopped. November 2025 saw two more top Cuban prospects defect (they literally snuck out of the country to sign with MLB teams), bringing the total to double-digits this year alone. Every Cuban player with MLB potential is looking for ways out, because staying means making $20/month while watching inferior players make millions in the States. The government's response has been to... do nothing effective. They loosened some restrictions allowing players to sign abroad without defecting, but the bureaucracy is insane and the government still takes a cut, so players just bypass it entirely. The Serie Nacional—Cuba's domestic league—is a shadow of its former self. November games featured half-empty stadiums, aging stars, and teenagers who'll be gone within two years if they're any good. The talent drain is absolute. Meanwhile, Cuban players in MLB are thriving: Luis Robert Jr., Randy Arozarena, Yordan Álvarez—these guys are stars, and every success story makes staying in Cuba feel more pointless. The November MLB free agency period saw three Cuban players sign major contracts, and Cuban kids are watching, taking notes, planning their own escapes.

## The Big Issue 2: Olympic Glory Days Are Over

Remember when Cuba was an Olympic medal factory? Boxing, volleyball, track and field, wrestling—they won medals in bunches and it was a point of immense national pride. November 2025 reality: Cuba won six medals at the 2024 Paris Olympics. SIX. For context, they won 18 in Barcelona '92. The decline is stark and undeniable. The facilities are crumbling (literally—November reports showed Olympic training centers with holes in roofs, broken equipment, no air conditioning in Caribbean heat), coaching talent has left for better opportunities abroad, and athletes are underfed because the economy is in freefall. Cuban boxers used to be unbeatable. Now? They're still good but no longer dominant, and several top prospects have defected to turn pro in Mexico or the US. The November World Wrestling Championships saw Cuba win two medals total, compared to dominating the sport for decades. The volleyball programs—both men's and women's—are struggling to compete with better-funded nations. The women's team failed to qualify for the Olympics, which would've been unthinkable 15 years ago. The government still treats Olympic sports as propaganda tools, but when athletes are literally hungry and training in falling-apart facilities, propaganda doesn't work anymore. Sports success requires resources, and Cuba has none.

## The Big Issue 3: The Myth of Amateur Purity (And Why It's Killing Cuban Sports)

Cuba has historically maintained that their athletes are pure amateurs competing for love of country and sport, not money. This was always somewhat BS (the state provided benefits and privileges), but at least the system functioned when the Soviet Union was subsidizing everything. Now? It's just absurd. Cuban athletes watch their peers around the world make millions while they scrape by on government rations. The November departure of a top volleyball player to play professionally in Italy (she literally applied for asylum) is just the latest example. The amateur model made sense (sort of) during the Cold War when it was ideological. In 2025, it's just economic insanity. Cuba could allow professionalization, let athletes earn money, take a reasonable tax/agent cut, and actually keep talent. Instead, they maintain a dysfunctional system that drives everyone away. The November debates in Cuban sports media (which is state-controlled but increasingly critical) showed even party loyalists admitting the current model is unsustainable. But fixing it requires admitting the entire Communist sports structure was wrong, which the government won't do. So instead, Cuban sports slowly dies while everyone watches. It's tragic because the talent is still there—Cuban kids are still athletic, still competitive, still have the potential. They just have no reason to stay and develop that potential at home.

## The International Angle

Cuban athletes abroad are the actual story of Cuban sports now. MLB is full of Cuban stars, Cuban boxers are winning titles as professionals, volleyball players compete across Europe, and they're all doing it after leaving Cuba. The November international baseball tournaments featured Team Cuba getting destroyed by teams with rosters full of Cuban defectors playing for other countries. (The Dominican Republic's team had three former Cubans, Team USA had two, even Mexico had one.) It's this weird situation where Cuban talent is flourishing everywhere except Cuba itself. The diaspora community in Miami and elsewhere follows these athletes religiously, and there's this emotional complexity where they're proud of Cuban heritage succeeding but sad it requires leaving Cuba. The government tries to paint defectors as traitors, but nobody buys it anymore—people understand economic reality. The November World Baseball Classic qualifying showed Cuba barely making it through, needing to beat Panama in extras, looking thoroughly average against nations that should be easy wins. Meanwhile, Cuban-born players dominating MLB playoffs. The contrast couldn't be starker. Cuba's international sports reputation is now defined by who left, not who stayed.

## The Bottom Line

Cuban sports in November 2025 is a dying empire stubbornly refusing to adapt. The baseball talent is gone, Olympic programs are underfunded and crumbling, and the amateur purity myth is exposed as economic fantasy. Athletes are leaving at every opportunity because staying means poverty and watching inferior players succeed abroad. The infrastructure is falling apart—both literally (facilities) and systemically (coaching, development, funding). The government could fix this by allowing professionalization, creating paths for athletes to earn while staying, and modernizing the system. But that requires ideological flexibility they don't have. So instead, we watch one of history's great sporting nations become irrelevant in real time. The talent still exists in Cuban genetics and culture—the kids who grow up playing baseball in the streets, the boxing gyms producing fighters, the volleyball courts where kids learn to compete. But that talent immediately leaves for opportunities elsewhere, and you can't blame them. November shows a sports system in terminal decline, held together by nostalgia and propaganda while the actual athletes vote with their feet. It's sad, it's frustrating, and it's entirely self-inflicted. Cuban sports deserves better than this, but Cuban sports won't get better until the system changes, and the system won't change until... who knows. For now, we remember what was, watch what could be succeed elsewhere, and mourn what's being wasted.`
  }
]

async function saveAllWriteups() {
  console.log('\\n🏈 SPORTS WRITEUPS - BILL SIMMONS VOICE')
  console.log(`Saving ${SPORTS_WRITEUPS.length} country writeups...\\n`)

  for (let i = 0; i < SPORTS_WRITEUPS.length; i++) {
    const writeup = SPORTS_WRITEUPS[i]
    try {
      // Extract issues from summary
      const issueMatches = writeup.summary.match(/## The Big Issue \\d+: (.+)/g) || []
      const issues = issueMatches.map(match => match.replace(/## The Big Issue \\d+: /, '').trim())

      await prisma.locationSummary.upsert({
        where: {
          name_type_category: {
            name: writeup.name,
            type: 'country',
            category: 'sports'
          }
        },
        create: {
          name: writeup.name,
          type: 'country',
          country: writeup.name,
          lat: writeup.lat,
          lng: writeup.lng,
          category: 'sports',
          summary: writeup.summary,
          issues: JSON.stringify(issues),
          topStories: JSON.stringify([]),
          storyCount: 0,
          updatedAt: new Date()
        },
        update: {
          summary: writeup.summary,
          issues: JSON.stringify(issues),
          updatedAt: new Date()
        }
      })

      console.log(`✅ ${i + 1}/${SPORTS_WRITEUPS.length} - ${writeup.name}`)

      // Report every 25 countries
      if ((i + 1) % 25 === 0) {
        console.log(`\\n📊 PROGRESS REPORT: ${i + 1}/${SPORTS_WRITEUPS.length} countries completed\\n`)
      }
    } catch (error) {
      console.error(`❌ Error saving ${writeup.name}:`, error)
    }
  }

  console.log('\\n🎉 Batch complete! Moving to next set...\\n')
}

saveAllWriteups()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
